### ISSUE TITLE
merge warning - "AD" tag different lengths

### ISSUE THREAD

**Issue by klmartinez** [samtools/bcftools#1001]
When trying to merge two VCF files using the following command

`bcftools merge -m all vcf_file_1.vcf.gz vcf_file_2.vcf.gz > merge1_2`

I get the following warnings

```
Warning: trying to combine "AD" tag definitions of different lengths
Error at 1:17085171: wrong number of fields in dbNSFP_SIFT_pred?
```

What does this warning mean?

**Comment by pd3** [comment]
There are two problems: the `AD` tag is a reserved tag and should be defined as `Number=R` in the header. Even if it were not, the definitions must match in all files you are merging.

The second problem is that the tag `dbNSFP_SIFT_pred` has incorrect number of values, other than declared in the header. For more check the VCF specification http://samtools.github.io/hts-specs/VCFv4.3.pdf
