### ISSUE TITLE
bcftools [W::bcf_hdr_check_sanity] GL should be declared as Number=G

### ISSUE THREAD

**Issue by MrLocuace** [samtools/bcftools#1003]
Hello, I have some vcf files. This is the header of an example for chr 14:

##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##source=BCM:SNPTools:prob2vcf
##reference=GRCh37
##FORMAT=<ID=GL,Number=3,Type=Float,Description="three log10-scaled likelihoods for RR,RA,AA genotypes">
##contig=<ID=14>
##bcftools_mergeVersion=1.1-138-gdbd6536+htslib-1.1-125-g3768707
##bcftools_mergeCommand=merge -m id -Oz -o X.chr14.vcf.gz /path/ALL.chr14.phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.YCPPMC.vcf.gz.recode.vcf.gz ../X/OTGA/X.n46.1000G.SNPs.noBAQ.STRCT.chr14.beagle.vcf.gz

I used bgzip -c and tabix -p vcf to generate indexed files. I want to extract some individuals from these files:

for i in {1..22}; do
    bcftools view -Oz -S /path/my_list.txt \
    ~/path/my_chr${i}.vcf.gz > \
    ~/path/only_x/my_chr${i}.vcf.gz; 
done 

However I get this message:

bcftools [W::bcf_hdr_check_sanity] GL should be declared as Number=G

I am not sure about what to do. Could you please advice?

Thank you very much

All the best

**Comment by pd3** [comment]
I see that's an older format, VCFv4.0. You can use the `bcftools reheader` command to fix the offending GL header line to `Number=G` and file format to `fileformat=VCFv4.2`. That will work only if all sites in the VCF are biallelic.

**Comment by MrLocuace** [comment]
Thanks very much ! I also have monoallelic sites. What do you suggest doing in this case?

**Comment by pd3** [comment]
Maybe try to remove the GL tags from these lines, this should work: 
````
bcftools annotate -x FMT/GL -k -i'N_ALT==1' file.vcf
````

**Comment by MrLocuace** [comment]
Thanks very much, Petr. Just a last question. I'd like to merge my files with 1000G Phase3 data, which used fileformat=VCFv4.1. My data comes from genotype likelihoods (GL). For this purpose, would it still be fine to do "bcftools annotate -x FMT/GL -k -i'N_ALT==1' file.vcf, or change to Number=G and file format to fileformat=VCFv4.1", or would you rather suggest something else?

Thanks again

**Comment by pd3** [comment]
I believe it should work.

**Comment by MrLocuace** [comment]
Many thanks

**Comment by sultandromeda** [comment]
How can this error impact the downstream analysis? My VCF is biallelic. I get this complain.
