### ISSUE TITLE
bcftools merge - multiple QUAL scores

### ISSUE THREAD

**Issue by ksw9** [samtools/bcftools#1004]
Hi,
Thank you for a great software.
I'm wondering if there is any way to use bcftools merge to combine variants and retain individual sample QUAL scores? 
Is there a work-around I could use for this?
Thank you!

**Comment by pd3** [comment]
If I understood your question correctly, you'd like to transfer the site-level quality (the QUAL column) into FORMAT fields, presumably you are working with single-sample VCFs. You can use
````
bcftools query -f'%CHROM\t%POS\t%QUAL\n' file.vcf | bgzip -c > qual.txt.gz
tabix -s1 -b2 -e2 qual.txt.gz
````
to extract the QUAL column, then use it to annotate the FORMAT/QUAL column:
````
echo '##FORMAT=<ID=QUAL,Number=1,Type=Float,Description="Per-sample QUAL">' > hdr.txt
bcftools annotate -a qual.txt.gz -c CHROM,POS,FORMAT/QUAL -h hdr.txt file.vcf
````
After merging, each sample will also carry the original QUAL column annotation.

Note that the commands above are not tested, may need some tuning.

**Comment by ksw9** [comment]
Hi,
This is exactly what I was looking for, preserving single-sample QUAL information. Thank you for your help!
Best,
