### ISSUE TITLE
plot-vcfstats Requires Parameter Documented to be Optional

### ISSUE THREAD

**Issue by DarioS** [samtools/bcftools#1005]
The format of plot-vcfstats is `plot-vcfstats [OPTIONS] file.vchk […]`. If I don't specify `-p` I get an error.

```
Expected -p parameter.
 at /usr/local/bcftools/1.9/bin/plot-vcfstats line 99
```

Why is it listed as an option if it's mandatory? Also, the [bcftools documentation](samtools.github.io/bcftools/bcftools.html) never specifies what a vchk file is elsewhere on the help page. Should the documentation contain a link to somewhere that explains what the vchk file format is? Does the extension even matter? It seems to be a tab-separated text file and the software works equally well if I input a file named `LS33stats.txt`.

**Comment by pd3** [comment]
Both documentation and the usage page (type `plot-vcfstats` without arguments) say that the script plots the output of `bcftools stats` command. The name of the file, including the suffix, does not matter. The documentation is now updated to make this clear, sorry for the confusion.
