### ISSUE TITLE
Depth Plots Y-Axis Not Visible

### ISSUE THREAD

**Issue by DarioS** [samtools/bcftools#1006]
Y-axis title goes beyond the edge of the PDF page. Only a small portion of the bottom of it can be seen. The red and black tick labels are also unexplained (depth.1.pdf). Is there also a colour legend missing beyond the margins?

![image](https://user-images.githubusercontent.com/631218/56464116-c00a9f80-6425-11e9-8991-6e52ed66f878.png)
`

**Comment by pd3** [comment]
There is probably no FORMAT/DP field in your VCF and thus the y-axis ranges are different from the expected values and don't fit in the margins of the plot. I modified them to be bigger, added a check for FORMAT/AD field in case FORMAT/DP is not present, and extended the documentation to suggest that the plots can also be modified by the user.
