### ISSUE TITLE
BCF Tools cant view/query INFO field valueusing a list?

### ISSUE THREAD

**Issue by skyscraperjon** [samtools/bcftools#1007]
I am trying to extract all records for snps that belong to a particular gene set:

`bcftools view -i'INFO/Gene.ensGene=[@ensGene_list.txt]' MY_VCF.vcf.gz | bgzip > output.vcf.gz`

is there a different function for this?

**Comment by pd3** [comment]
This is not supported, sorry. You can, however, create a list of genomic regions and use the -R or -T option.

**Comment by skyscraperjon** [comment]
You would recommend getting the genomic region range of each gene (chrom, pos, pos-to) and querying a list of those using -R or -T. 

`bcftools view -R Line_Seperated_Position_File.txt MY_VCF.vcf.gz | bgzip > output.vcf.gz`

**Comment by pd3** [comment]
Yes, that's correct.
