### ISSUE TITLE
BCFtools query: Avoid grouping Alt Alleles

### ISSUE THREAD

**Issue by skyscraperjon** [samtools/bcftools#1008]
I am trying to query my vcf but I am running into a problem, the output looks like this:

   ` chr17 61615660 chr17:61615660:T:TG,TC T TG,TC`

where the columns are

    

> Chr Pos ID REF ALT

and the line of code is:

`bcftools query File_Name.vcf.gz -f'%CHROM\t %POS\t %ID\t %REF\t %ALT\n' -i'GT="alt"' | bgzip >  output.txt.gz`

Is there a way to tell bcftools query not to group the alt alleles?

Thank you in advance.

**Comment by pd3** [comment]
What do you mean by "not to group"? Print as `T TG TC` instead of `T TG,TC`? This is not currently possible, you'll need a post-processing step.

**Comment by skyscraperjon** [comment]
I mean print a new line for each alt allele.

**Comment by pd3** [comment]
You'll have to write a small post-processing script, we don't have a built-in mechanism to do that, sorry.
