### ISSUE TITLE
bcftools call QS annotation not present

### ISSUE THREAD

**Issue by noemievlz** [samtools/bcftools#1015]
Good afternoon, 

I am having troubles with bcftools call to convert the bcf file output by mpileup to vcf.
I get:
 The QS annotation not present at trevally000001:146

thank you

**Comment by pd3** [comment]
Most likely you are mixing different versions/programs. You should provide more details, including the version of the software.

Please check here for an example http://samtools.github.io/bcftools/howtos/variant-calling.html

**Comment by mathstream** [comment]
I'm getting the same message.  What is a QS annotation?  It would be nice to know what it is and why it's needed, or might be missing

**Comment by pd3** [comment]
The QS annotation is generated by the `bcftools mpileup` step. The program `bcftools call` requires that. The typical usage is
```
bcftools mpileup -Ou -f reference.fa alignments.bam | bcftools call -mv -Ob -o calls.bcf
```
