### ISSUE TITLE
Guidance on mpileup --read-groups vs --samples

### ISSUE THREAD

**Issue by kdmurray91** [samtools/bcftools#1018]
Hello,

Apologies in advance if this question results from insufficient R-ing of TFM, but I'm quite puzzled as to the differences between `bcftools mpileup --read-groups` vs `--samples`. We have one huge BAM of all samples, and I'd like to call variants within subsets of this file. The BAM contains ~4k read group IDs (a concatenation of library name and sequencing run, as RG ID) and each run/library has a sample name (as RG SM). Then,  I have lists of sample names that I'd like to use to define the subsets within which variants are called by `mpileup`. I tried reading the source (`bam_sample.[ch]`), but couldn't seem to make sense of which option suits my situation.

Thanks in advance,
Kevin

**Comment by pd3** [comment]
The difference is that a sample can have reads from multiple read groups. Unless the requirement is to exclude only selected read groups, you want to work with the `--samples` option. For more see the description of `--read-groups` here http://samtools.github.io/bcftools/bcftools.html#mpileup

**Comment by kdmurray91** [comment]
Thanks Petr.

To be explicit, if my BAM has
```
@RG     ID:plate1-6.0_J331      SM:J331
@RG     ID:plate1-6.1_J331      SM:J331
@RG     ID:plate1-6.2_J331      SM:J331
@RG     ID:plate1.1_J331-NextRAD        SM:J331
@RG     ID:plate1.1_J331-WGS    SM:J331
@RG     ID:plate1.2_J331-WGS    SM:J331
```
then either I could give --read-groups the mapping above (as `$ID\t$SM\n`), or just give --samples-file the sample IDs (i.e. a file of `$SM\n`'s for each sample).

Thanks again,
Kevin
