### ISSUE TITLE
bcftools convert fails when converting hap sample to vcf

### ISSUE THREAD

**Issue by PhilPalmer** [samtools/bcftools#1019]
Hi,

I am trying to convert a hap sample to vcf with the following command:
```bash
bcftools convert --hapsample2vcf chr10.hap.gz,chr10.samples
```

However, I get the following error when it tries parsing the first line:
```
Wrong number of fields at 2-th sample ([][][]). Error occurred while parsing: 10:126070_C_T rs11591988 126070 C T 0 0
```

My samples file (`chr10.samples`) looks like this:
```
ID_1 ID_2 missing father mother sex plink_pheno
0 0 0 D D D B
John Doe 0 0 0 1 -9
Temporary Non_person 0 0 0 1 -9
```

& hap file (`chr10.hap.gz`) looks like this:
```
10:126070_C_T rs11591988 126070 C T 0 0
10:135708_A_G rs7917054 135708 A G 1 0
10:135853_G_A rs7906287 135853 G A 0 0
10:151997_T_C rs9286070 151997 T C 0 0
10:158946_C_T rs11253562 158946 C T 0 0
10:159076_A_G rs4881551 159076 A G 0 0
10:159404_A_G rs4880750 159404 A G 0 1
10:178434_G_T rs7089889 178434 G T 1 0
10:203471_A_G rs10903451 203471 A G 0 1
10:230625_T_C rs12779173 230625 T C 0 0
```

I am using bcftools v1.9. The issue seems similar to #893 but I'm still not exactly sure what the issue is. It says wrong number of fields, but I am not sure what the correct number of fields should be or how they should look

Any ideas what the problem is?

Many thanks in advance, any help would be much appreciated

**Comment by pd3** [comment]
From a cursory glance, it seems that there are fewer columns than expected for two samples. An example of the expected format is shown in the manual http://samtools.github.io/bcftools/bcftools.html#convert

**Comment by PhilPalmer** [comment]
Ah yes, you were right. Thanks for your help. 

The  hap file did not contain the info for the 3rd individual in the samples file
