### ISSUE TITLE
isec --complement argument order changes results

### ISSUE THREAD

**Issue by sjneph** [samtools/bcftools#1020]
I'm running the following two files using version 1.9 and 1.7 separately, and I receive different results depending on where I place `--complement` in the order of options.

`./bcftools isec --complement --collapse snps -n=2 -w 1 f1.vcf.gz f2.vcf.gz`

gives back all entries of `f1.vcf.gz` (which is incorrect)
Additionally, putting `--complement` in between `--collapse snps` and `-n=2` gives all entries from `f1.vcf.gz` (incorrect)

It gives the correct output when the following is used:
`./bcftools isec --collapse snps -n=2 --complement -w 1 f1.vcf.gz f2.vcf.gz`

The output is also correct when `--complement` is the last option given.

This should be reproducible for files `f1.vcf.gz` and `f2.vcf.gz` that have some differences and direct overlaps.

**Comment by pd3** [comment]
That's an interesting observation. The arguments are parsed by `getopt_long`, I can't imagine how that would be possible. What platform are you running this on? Any chance of providing a small test case to reproduce the problem?

**Comment by sjneph** [comment]
Looks like I threw out some bad information.  The results are different, but I am not yet sure which is correct.  Counting non-header lines, b.vcf has 762.  The outputs given with two variants of `--complement` shown, are different and add up to 762 together (427 and 335).  I have not closely at the details but it suggests that `--complement` is not picked up in one  of the cases.

CentOS Linux release 7.6.1810 (Core)
3.10.0-957.5.1.el7.x86_64

There is a dependency on `libcrypto.so.1.0.0` which is being picked up from the htslib/1.7 in our module set-up, and that's brought in with my newly built bcftools/1.9.  I did not catch that initially.

Here are some small vcfs.



[f2.vcf.txt](https://github.com/samtools/bcftools/files/3162449/f2.vcf.txt)
[f1.vcf.txt](https://github.com/samtools/bcftools/files/3162450/f1.vcf.txt)

**Comment by sjneph** [comment]
When I remove the -n option, the outputs do match with 427 lines.  I'm pretty new with using these tools.

**Comment by jmarshall** [comment]
`-n` and `-c` both set the same option variable (`args->isec_op`), so whichever is last on the command line will override the other one.

**Comment by pd3** [comment]
That was indeed the case, `-C` should not be combined with `-n`. Now fixed by c406d0e to throw an error.
