### ISSUE TITLE
[E::vcf_parse_format] Invalid character 'N' in 'AC' FORMAT field

### ISSUE THREAD

**Issue by balathumma10** [samtools/bcftools#1021]
I get this error when I try to run this command
bcftools query -f'%CHROM\t %POS\t %REF\t %ALT[ %AC\t%DP]\n' tst.vcf -o test_AC_DP.txt
[E::vcf_parse_format] Invalid character 'N' in 'AC' FORMAT field
I think it is complaining about NA in AC field. 
Please help me to solve this.
Thank you

**Comment by pd3** [comment]
This error seems to come from VCF parsing. You can try `vcf-validator` from the vcftools package or inspect the VCF visually: AC should be defined as integer, therefore you should see only numbers or dots (".") .

**Comment by balathumma10** [comment]
When the the depth of ALT allele is 0, there is NA at the AC field which
could be changed to 0. However, older version of bcftools-1.1 seem to work
fine. I have now replaced NA with 0 and that seems to have solved the
problem with the new version of bcftools.

**Comment by pd3** [comment]
The parsing got more strict in recent versions to prevent user errors. It's not really a problem with the program, but with the VCF. I'll close the issue now as resolved, complain if not.

**Comment by balathumma10** [comment]
Thank you Petr. Agree the problem is with the VCF file.
