### ISSUE TITLE
i am subsetting a bcf to vcf with a small subset of samples

### ISSUE THREAD

**Issue by apampana** [samtools/bcftools#1023]
I am subsetting  a bcf to vcf for a small subset of samples and when i checked the variants counts in the vcf its very less compared to what we have in original file. I want to know how the bcf to vcf works?  When outputing vcf , it will only give out put with samples and variants within those samples or overall  variants from the original bcf?

**Comment by pd3** [comment]
Conversion between BCF and VCF and back and sample subsetting does not drop sites. If the samples in the subset had few variants then on output all sites should be there but few should have ALT allele set. You should show the exact commands you are using, it is not clear what you're doing and how you count the variants.

**Comment by apampana** [comment]
bcftools view -S samples.list --force-samples -o GenSalt.vcf  data.bcf

dataset have 100k samples and 150m variaants , but when i subsetted to 500 samples (samples.list), i am getting only 100k variants

**Comment by apampana** [comment]
i ran as a script file in linux as pid

**Comment by apampana** [comment]
i counted number of line of the vcf file with wc -l and i know how many headers are there so i removed those and got the count

**Comment by pd3** [comment]
You should get the same numbers if you run
````
bcftools view -H file.bcf | wc -l
bcftools view -H -S samples.list --force-samples | wc -l 
````
If not, the output file was probably truncated. Check for any error messages. Maybe it was killed by the system before it was able to finish, or the program encountered an error while parsing the input. 

We'll need a reproducible test case to debug this further, your description does not give enough information.

**Comment by apampana** [comment]
Hello 
I tried submitting jobs in a cluster and run it and got out vcf file(which maybe 5tb size not sure as it stalled in between and job is still running with no additional increse in file size of vcf). Am i missing anything? Is there a timeout period for data to be covnerted? I am also now getting error file not found error when i did try to query the vcf generated to extract the header and i dint found any header too. I cant give any reference to reproducability of error as its working fine for small sample set and when i am working on a big data set with 55k samples and 150m variants. as of today i got only 20m and already data file size is 5TB, is there something wrong with in the code or something i couldnt able to understand.

**Comment by pd3** [comment]
Overall, this seems more like a problem with the infrastructure struggling with the large file size. You could run multiple jobs in parallel via the `-r` option and concatenate the results afterwards. It will require less time and if one chunk fails, you'll be able to redo the small parts. That's the general strategy how to work with big data.

**Comment by apampana** [comment]
thank you. got it,i was about to do that. thank you for letting me know

**Comment by apampana** [comment]
Can i know whats the default output for bcf file when fltering?

**Comment by apampana** [comment]
how to write bcf output?

**Comment by pd3** [comment]
Using the `-Ob` switch,  please check the section "Common Options" of the manual http://samtools.github.io/bcftools/bcftools.html#common_options
