### ISSUE TITLE
Incorrect start lost annotation

### ISSUE THREAD

**Issue by Ahhgust** [samtools/bcftools#1025]
I'm getting what looks to be an incorrect start-lost annotation from bcftools csq (version 1.9). 
The annotation in question corresponds to:
rs750258622
The alternative allele is a T deletion (at frequency 100% in ExAC)  that hits the first base of the start codon on the - strand. This is annotated as a frameshift/start lost, however the base following the deletion is also a T, which suggests that it is not a frameshift (i.e., there's either ~10Ts or ~11Ts).  GENCODE (v29) documents this as an upstream gene variant, btw.

The annotation in is in the below, but the M gets translated into a C, which suggests that you try and adjust for the bases around the deletion, but maybe the case of the - strand is not being evaluated correctly (?).

I appreciate your help and for the record having a tool that makes these kinds of annotations quickly is invaluable.

-August

Example: (taken from the phase 3 1000 genomes data in GRCh37 coordinates):
CSQ     HG00099 2       1       152195728       frameshift&start_lost|HRNR|ENST00000368801|protein_coding|-|1MPKLLQGVITVIDVFYQYATQHGEYDTLNKAELKELLENEFHQILKNPNDPDTVDIILQSLDRDHNKKVDFTEYLLMIFKLVQARNKIIGKDYCQVSGSKLRDDTHQHQEEQEETEKEENKRQESSFSHSSWSAGENDSYSRNVRGSLKPGTESISRRLSFQRDFSGQHNSYSGQSSSYGEQNSDSHQSSGRGQCGSGSGQSPNYGQHGSGSGQSSSNDTHGSGSGQSSGFSQHKSSSGQSSGYSQHGSGSGHSSGYGQHGSRSGQSSRGERHRSSSGSSSSYGQHGSGSRQSLGHGRQGSGSRQSPSHVRHGSGSGHSSSHGQHGSGSSYSYSRGHYESGSGQTSGFGQHESGSGQSSGYSKHGSGSGHSSSQGQHGSTSGQASSSGQHGSSSRQSSSYGQHESASRHSSGRGQHSSGSGQSPGHGQRGSGSGQSPSSGQHGTGFGRSSSSGPYVSGSGYSSGFGHHESSSEHSSGYTQHGSGSGHSSGHGQHGSRSGQSSRGERQGSSAGSSSSYGQHGSGSRQSLGHSRHGSGSGQSPSPSRGRHESGSRQSSSYGPHGYGSGRSSSRGPYESGSGHSSGLGHQESRSGQSSGYGQHGSSSGHSSTHGQHGSTSGQSSSCGQHGATSGQSSSHGQHGSGSSQSSRYGQQGSGSGQSPSRGRHGSDFGHSSSYGQHGSGSGWSSSNGPHGSVSGQSSGFGHKSGSGQSSGYSQHGSGSSHSSGYRKHGSRSGQSSRSEQHGSSSGLSSSYGQHGSGSHQSSGHGRQGSGSGHSPSRVRHGSSSGHSSSHGQHGSGTSCSSSCGHYESGSGQASGFGQHESGSGQGYSQHGSASGHFSSQGRHGSTSGQSSSSGQHDSSSGQSSSYGQHESASHHASGRGRHGSGSGQSPGHGQRGSGSGQSPSYGRHGSGSGRSSSSGRHGSGSGQSSGFGHKSSSGQSSGYTQHGSGSGHSSSYEQHGSRSGQSSRSEQHGSSSGSSSSYGQHGSGSRQSLGHGQHGSGSGQSPSPSRGRHGSGSGQSSSYGPYRSGSGWSSSRGPYESGSGHSSGLGHRESRSGQSSGYGQHGSSSGHSSTHGQHGSTSGQSSSCGQHGASSGQSSSHGQHGSGSSQSSGYGRQGSGSGQSPGHGQRGSGSRQSPSYGRHGSGSGRSSSSGQHGSGLGESSGFGHHESSSGQSSSYSQHGSGSGHSSGYGQHGSRSGQSSRGERHGSSSGSSSHYGQHGSGSRQSSGHGRQGSGSGHSPSRGRHGSGLGHSSSHGQHGSGSGRSSSRGPYESRSGHSSVFGQHESGSGHSSAYSQHGSGSGHFCSQGQHGSTSGQSSTFDQEGSSTGQSSSYGHRGSGSSQSSGYGRHGAGSGQSPSRGRHGSGSGHSSSYGQHGSGSGWSSSSGRHGSGSGQSSGFGHHESSSWQSSGCTQHGSGSGHSSSYEQHGSRSGQSSRGERHGSSSGSSSSYGQHGSGSRQSLGHGQHGSGSGQSPSPSRGRHGSGSGQSSSYSPYGSGSGWSSSRGPYESGSSHSSGLGHRESRSGQSSGYGQHGSSSGHSSTHGQHGSTSGQSSSCGQHGASSGQSSSHGQHGSGSSQSSGYGRQGSGSGQSPGHGQRGSGSRQSPSYGRHGSGSGRSSSSGQHGSGLGESSGFGHHESSSGQSSSYSQHGSGSGHSSGYGQHGSRSGQSSRGERHGSSSRSSSRYGQHGSGSRQSSGHGRQGSGSGQSPSRGRHGSGLGHSSSHGQHGSGSGRSSSRGPYESRSGHSSVFGQHESGSGHSSAYSQHGSGSGHFCSQGQHGSTSGQSSTFDQEGSSTGQSSSHGQHGSGSSQSSSYGQQGSGSGQSPSRGRHGSGSGHSSSYGQHGSGSGWSSSSGRHGSGSGQSSGFGHHESSSWQSSGYTQHGSGSGHSSSYEQHGSRSGQSSRGEQHGSSSGSSSSYGQHGSGSRQSLGHGQHGSGSGQSPSPSRGRHGSGSGQSSSYGPYGSGSGWSSSRGPYESGSGHSSGLGHRESRSGQSSGYGQHGSSSGHSSTHGQHGSASGQSSSCGQHGASSGQSSSHGQHGSGSSQSSGYGRQGSGSGQSPGHGQRGSGSRQSPSYGRHGSGSGRSSSSGQHGPGLGESSGFGHHESSSGQSSSYSQHGSGSGHSSGYGQHGSRSGQSSRGERHGSSSGSSSRYGQHGSGSRQSSGHGRQGSGSGHSPSRGRHGSGSGHSSSHGQHGSGSGRSSSRGPYESRSGHSSVFGQHESGSGHSSAYSQHGSGSGHFCSQGQHGSTSGQSSTFDQEGSSTGQSSSHGQHGSGSSQSSSYGQQGSGSGQSPSRGRHGSGSGHSSSYGQHGSGSGWSSSSGRHGSGSGQSSGFGHHESSSWQSSGYTQHGSGSGHSSSYEQHGSRSGQSSRGERHGSSSGSSSSYGQHGSGSRQSLGHGQHGSGSGQSPSPSRGRHGSGSGQSSSYSPYGSGSGWSSSRGPYESGSGHSSGLGHRESRSGQSSGYGQHGSSSGHSSTHGQHGSTSGQSSSCGQHGASSGQSSSHGQHGSGSSQSSGYGRQGSGSGQSPGHGQRGSGSRQSPSYGRHGSGSGRSSSSGQHGSGLGESSGFGHHESSSGQSSSYSQHGSGSGHSSGYGQHGSRSGQSSRGERHGSSSGSSSHYGQHGSGSRQSSGHGRQGSGSGQSPSRGRHGSGLGHSSSHGQHGSGSGRSSSRGPYESRLGHSSVFGQHESGSGHSSAYSQHGSGSGHFCSQGQHGSTSGQSSTFDQEGSSTGQSSSYGHRGSGSSQSSGYGRHGAGSGQSLSHGRHGSGSGQSSSYGQHGSGSGQSSGYSQHGSGSGQDGYSYCKGGSNHDGGSSGSYFLSFPSSTSPYEYVQEQRCYFYQ*>1CLNSYKASSLSSMFSTNMPPSMGSMIR*|152185762C>G+152185774A>G+152185790T>C+152185792G>A+152185796A>G+152185815C>A+152185816C>G+152185819A>C+152185823C>T+152185833C>T+152185846G>T+152185859C>T+152185861G>C+152185864G>A+152185867A>G+152185869A>G+152186178C>T+152186222T>C+152187562A>C+152190720C>T+152191709C>G+152191879G>A+152192114C>T+152192293C>T+152192395G>A+152192631C>T+152192687T>C+152192825C>T+152192978T>C+152193052A>G+152193121G>T+152193286G>T+152193291G>T+152193544A>G+152193547G>A+152193851C>T+152195728ATT>AT

**Comment by Ahhgust** [comment]
The same issue is seen with rs750258622.
-August

**Comment by Ahhgust** [comment]
I just now noticed how I awesomely had a copy and paste error with that second example (sorry about that). There is another instance (many, I'm sure) that includes annotations with rs748146582, rs141946179, rs544557603, ...
I also tried downloading the development version of bcftools csq and it gives the same error; all of which involve an incorrect indel-derived start-loss due to not filling in the appropriate bases from the genome (when the bases are deleted). Interestingly, it also gives the wrong annotation when its an insertion-- in the last example RS number, the M start is on the - strand, encoded as CAT in the + strand. Individuals that have CATT (insertion of a T after the A) also are encoded as a "frameshift&start-lost" when the start codon is actually unaffected.  In HG19 coordinates (1000 genomes project), the annotation appears as:
CSQ     HG01883 1       2       211179765       frameshift&start_lost|MYL1|ENST00000352451|protein_coding|-|1MAPKKDVKKPVAAAAAAPAPAPAPAPAPAPAKPKEEKIDLSAIKIEFSKEQQDEFKEAFLLFDRTGDSKITLSQVGDVLRALGTN
PTNAEVRKVLGNPSNEELNAKKIEFEQFLPMMQAISNNKDQATYEDFVEGLRVFDKEGNGTVMGAELRHVLATLGEKMKEEEVEALMAGQEDSNGCINYEAFVKHIMSI*>1NGTKERREETCGCGCGCPSPGTGTCTCPCPSQTQRRKN*|211179765A>AT

**Comment by pd3** [comment]
Thank you for the bug report. The commit a5eebf8 adds a new "start_retained" consequence and should be able to catch cases like this. Please let me know if you spot any problems.

**Comment by Ahhgust** [comment]
Thanks for getting back to me and for your help on this!
I just re-compiled and re-ran the analyses and led me to this (bcftools csq on the GRCh37 1000 genomes data) and now I get an assertion failure:

bcftools-devel csq -f RecommendedHumanGenomes/hs37d5.fa -g GFFs/Homo_sapiens.GRCh37.85.chromosome.11.gff3.gz -O t -p r 1000Genomes/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz | gzip -9 > Consequences.chr11.gz
[W::hts_idx_load2] The index file is older than the data file: 1000Genomes/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz.tbi
Parsing GFFs/Homo_sapiens.GRCh37.85.chromosome.11.gff3.gz ...
Indexed 12204 transcripts, 71576 exons, 43666 CDSs, 18206 UTRs
Calling...
bcftools-devel: csq.c:1822: shifted_del_synonymous: Assertion `vcf_block_beg < ex_beg' failed.

and this assertion fails  for every chromosome (but it happens the soonest on chromosome 11).

**Comment by pd3** [comment]
This should be now fixed too. Note that there was another unrelated update to bcftools in the meantime (https://github.com/samtools/bcftools/commit/07f54944046807338952a5c3099cd71b6577a3a0) which requires to update htslib as well.

**Comment by Ahhgust** [comment]
It looks like we're closer-- I re-downloaded bcftools and htslib. Using the 1000 genomes data I now get a bug at line 1830:
bcftools csq -f RecommendedHumanGenomes/hs37d5.fa -g GFFs/Homo_sapiens.GRCh37.85.chromosome.6.gff3.gz -O t -p r 1000Gen_integrated_v5a.20130502.genotypes.vcf.gz > /dev/null
[W::hts_idx_load2] The index file is older than the data file: 1000Genomes/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz.tbi
Parsing GFFs/Homo_sapiens.GRCh37.85.chromosome.6.gff3.gz ...
Indexed 8439 transcripts, 52924 exons, 34439 CDSs, 12324 UTRs
Ignored the following biotypes:
        7x      .. 3prime_overlapping_ncrna
Calling...
Warning: The support for symbolic ALT insertions is experimental.
vcf_pos=24667491  ref_len=2  ndel=1  ..  vcf_block_beg=24667491 ?< ex_beg=24667491
bcftools: csq.c:1830: shifted_del_synonymous: Assertion `vcf_block_beg < ex_beg' failed.
Aborted

**Comment by pd3** [comment]
This was a forgotten and an unnecessary assert, it shoulkd work now.
