### ISSUE TITLE
Contig Name Become Short

### ISSUE THREAD

**Issue by soarsapien** [samtools/bcftools#1026]
Hi 
I met a problem when I try to call variant (bcftools mpileup) from our own DNA pool.
When I look into the final vcf file, the contig name become shorter
after bamtools faidx, still looks fine

NM_000612.5(IGF2):c.157_157+1insGC_NR_003512.3_utr3_2_0_chr11_2135367_r_Ref	154	2019	154	155
NM_000218.2(KCNQ1):c.1394-1G>T_NR_002728.3_utr3_0_0_chr11_2608328_r_Mut 155	2278	155	156
NM_000218.2(KCNQ1):c.1394-1G>T_NR_002728.3_utr3_0_0_chr11_2608328_r_Ref	155	2538	155	156
NM_000518.4(HBB):c.*110_*114delTAAAA_NM_000518.4_utr3_0_0_chr11_5225466_r_Mut	154	2804	154	155

but in the final vcf, contig become like this
##contig=<ID=NM_000612.5(IGF2):c.157_157+1insGC_NR_003512.3_utr3_2_0_chr11_2135367_r_Ref,length=154>
##contig=<ID=NM_000218.2(KCNQ1):c.1394-1G>
##contig=<ID=NM_000518.4(HBB):c.*110_*114delTAAAA_NM_000518.4_utr3_0_0_chr11_5225466_r_Mut,length=154>

seems like our own "Chromosome Name" contain ">" affect this contig, how to solve this problem?  
Thank You

**Comment by pd3** [comment]
The best way to solve the problem is to restrict contig names to a more sensible character set. The greater-than sign is not permitted by the SAM specification and will be disallowed in VCF as well.

**Comment by soarsapien** [comment]
Thank You for responded, seems like I have to fix this problem from beginning...
