### ISSUE TITLE
Hardtime understanding Bcftools stats output 

### ISSUE THREAD

**Issue by apampana** [samtools/bcftools#1029]
I am trying bcftools stats to get counts per samples. But i am getting all nRefHom,nNONrefHom,nHet,Indels and others. I want total variant count per samples and couldn't able to find any columns with information. Can i know how to calculate variant counts per samples?

**Comment by apampana** [comment]
Can someone help?

**Comment by pd3** [comment]
The total number of non-reference SNP genotypes per sample can be calculated from the output as `nNonRefHom + nHets`. The numbers stand for "non-reference homozogyous" and "heterozygous" genotypes. Similarly for indels.
