### ISSUE TITLE
Expression regex special characters

### ISSUE THREAD

**Issue by rbutleriii** [samtools/bcftools#1030]
I was wondering what the special characters are for regex operations in inclusion/exclusion expressions. I have a situation where multiple values can exist for an `INFO` tag:
```
CVCS=Pathogenic
CVCS=Pathogenic, risk factor
CVCS=Pathogenic/Likely pathogenic
CVCS=Pathogenic/Likely pathogenic, association
CVCS=Likely pathogenic
```
And I would like to be able to capture variants with `Pathogenic` without the `Pathogenic/Likely pathogenic` variants. I tried `-i 'CVCS ~ "Pathogenic[^\/]"` and `-i 'CVCS ~ "Pathogenic(?!\/)"` and both returned empty vcfs.

**Comment by pd3** [comment]
This should work (and does for me): `-i 'tag~"Pathogenic[^/]"'` vs `i 'tag~"Pathogenic/"'`.

The program uses the standard POSIX `regcomp,regexec` functions with the flags REG_NOSUB and, optionally, REG_ICASE. If this is not flexible enough, you can use an arbitrary perl code, an example of which is shown here https://github.com/samtools/bcftools/blob/develop/misc/demo-flt.pl
