### ISSUE TITLE
bcftools merge binary garbage intrusion

### ISSUE THREAD

**Issue by joelmartin** [samtools/bcftools#1031]
In merging bcf files produced by delly using bcftools built from git I get binary junk between the sample info fields.  I don't get the junk with bcftools built from the release 1.9, or the previous releases.    I also don't get the junk if I convert the bcf to vcf then merge and output in bcf and view that.

[files.zip](https://github.com/samtools/bcftools/files/3235620/files.zip)

unzip files.zip
bcftools index r.one.bcf
bcftools index r.two.bcf
bcftools merge -m id -O b -o bcf-bcf-merge.bcf r.one.bcf r.two.bcf
bcftools view bcf-bcf-merge.bcf

**Comment by joelmartin** [comment]
looks like it was this commit, before it is no problem
https://github.com/samtools/bcftools/commit/0668ecca94404152ea1dd1644b2ece3107217a1b

**Comment by pd3** [comment]
This should be fixed now. Thanks for the bug report and the test case.
