### ISSUE TITLE
Threads missing from BCFtools Csq

### ISSUE THREAD

**Issue by sbgLuka** [samtools/bcftools#1036]
Hi,

this is command line I used:
`gzip -c -f HG003.VarDict.vcf > HG003.VarDict.vcf.gz && bcftools index -f -t HG003.VarDict.vcf.gz && bcftools csq --gff-annot Homo_sapiens.GRCh37.87.gff3.gz --fasta-ref human_g1k_v37_decoy.fasta --output HG003.VarDict.csq.vcf.gz --phase s --output-type z --threads 16 HG003.VarDict.vcf.gz`

Error I got is: `csq: unrecognized option '--threads'`

It seems that threads option is missing from Csq tool.

**Comment by pd3** [comment]
This is now added.
