### ISSUE TITLE
count variants per cohort. Is there a way?

### ISSUE THREAD

**Issue by apampana** [samtools/bcftools#1038]
I am trying to count variants per sample list(cohort-specific) Is there a way to indicate samples for plugin +counts to get the count for samples which I want to uses specifically?  

Example:
Dataset have 20k samples and 500k variants. 
I wan to get counts of number of variants for 4k samples only which are in 20k , so is it possible to do that? I tried giving -S for counts and it dint worked for me

**Comment by apampana** [comment]
`bcftools +counts -S sa.samples chrX_par.bcf `, will it work ? i am getting error -S is invalid arguement ? is there a way to input samples ?

**Comment by pd3** [comment]
The plugin does not accept the -S option. To run on the subset of samples, run
````
bcftools view -c 1 -S samples.txt file.bcf -Ou | bcftools +counts
````

**Comment by apampana** [comment]
I want total number of variants. if i do  bcftools stats -s - i may get duplicate counts right?

**Comment by apampana** [comment]
and is there a way to include -i option in count+ to count number of total variants per expression i want to do ? like say if i want count for AC==1, can i do `bcftools count+ -i ' AC==0' input` , will it work?

**Comment by pd3** [comment]
Yes, it will work. As a general advice, runt `bcftools +counts` to see the list options. This works for all bcftools commands.
