### ISSUE TITLE
plot-vcfstats merge error

### ISSUE THREAD

**Issue by LaboratoryOfNeurogenetics** [samtools/bcftools#1040]
I am trying to merge two vcfstats files so that I can generate multi-sample plots, but am getting an error "Whoops, no such dst sample: B1-36490". My code is as follows:
bcftools stats B1-36489_S1.genome.vcf.gz -s- >test2.txt;
bcftools stats B1-36490_S1.genome.vcf.gz -s- >test4.txt;
plot-vcfstats  test2.txt --merge test4.txt

Any help would be appreciated.

**Comment by pd3** [comment]
This functionality was intended to merge stats from a bigger VCF split into chunks for performance. Therefore in its current form the program expects the same samples in all inputs. However, you can do instead
````
bcftools merge A.vcf.gz B.vcf.gz | bcftools stats -s - > stats.txt
````

**Comment by LaboratoryOfNeurogenetics** [comment]
Thank you Petr.
Best,
Bryan

--------------
Bryan J. Traynor MD PhD
Senior Investigator
Chief, Neuromuscular Diseases Research Section
Laboratory of Neurogenetics, NIA, NIH
35 Convent Drive, Room 1A-213, Bethesda, MD 20892-3707

Phone: (301) 451-7606           Fax: (301) 451-7295               Email: traynorb@mail.nih.gov<mailto:traynorb@mail.nih.gov>                Website:  https://www.irp.nia.nih.gov/branches/lng/ndrg.htm

The attached information is CONFIDENTIAL and may be protected under the Privacy Act of 1974 or other applicable laws. It is intended for the use of the addressee(s) identified above. This material must be destroyed appropriately when its use is no longer required. If the reader of this message is not the intended recipient(s) or the employee or agent responsible for delivering the attached information to the intended recipient(s), please note that any dissemination, distribution or copying of this communication is strictly prohibited. Anyone who receives this communication in error, please immediately advise the sender by reply email and delete this message.
