### ISSUE TITLE
sort: allegedly cannot write to /tmp 

### ISSUE THREAD

**Issue by DSLituiev** [samtools/bcftools#1041]
Version: 1.9-197-g4e51a29 (using htslib 1.9-186-gaa0b31f)

I am running `bcftools sort` command and getting an error:
```
[W::vcf_parse_format] FORMAT 'SP' is not defined in the header, assuming Type=String
[E::bcf_write] Unchecked error (2)
[buf_flush] Error: cannot write to /tmp/bcftools-sort.djXd8s/00001.bcf
```

I am running as a root. When I check `ls -lth /tmp/bcftools-sort.djXd8s/00001.bcf`, I see that the file has been created:
```
-rw-r--r-- 1 root root 7.5K Jun 17 01:07 /tmp/bcftools-sort.djXd8s/00001.bcf
```
this file contains the header of the file but no more than that.

I definitely have some 55G free drive space. 

Any suggestions how to debug it?

**Comment by pd3** [comment]
The problem here is caused by the first warning and the error that follows, "Unchecked error": the temporary files are stored as BCF for speed and the undefined tag prevents BCF writing. Update the VCF header using `bcftools reheader`, then it should work.

**Comment by DSLituiev** [comment]
Thank you @pd3 ! I believe it maybe beneficial to clarify that in the error message.
I tried 
`bcftools reheader myfile.vcf.gz` and getting help message:
`About:   Modify header of VCF/BCF files, change sample names. [...]` 

It seems I provided required argument, and I am not sure now what is missing from this help message. Can you please advise? Thank you

**Comment by pd3** [comment]
The usage is `bcftools reheader -h new-header.txt -o output.bcf input.bcf`

**Comment by pd3** [comment]
The program should now print an informative error message. It will also clean temporary files if something goes wrong. Thanks for the report.

**Comment by DSLituiev** [comment]
Thank you, Petr,

Where can I get reference on what should go into the new header file?

**Comment by pd3** [comment]
In general, the VCF specification is the resource to consult http://samtools.github.io/hts-specs/VCFv4.3.pdf. However, as FORMAT/SP is not a reserved tag and is not listed in the document, you can just put a dummy line in the header. What's important are the ID, Number and Type attributes. For example, if the SP value are all integers and there is only one value per sample, the new header line to add would look like this
````
##FORMAT=<ID=SP,Number=1,Type=Integer,Description="Some description">
````
