### ISSUE TITLE
Filtering for many samples being HET via a file, used OR instead of AND

### ISSUE THREAD

**Issue by WimSpee** [samtools/bcftools#1043]
Dear BCFTools developers,

Thank you for the functionality in bcftools for filtering on certain samples having a specific genotype. 

Filtering for variants where certain samples are required to be HET does work via the following expression.

```
bcftools view input.vcf-i "GT[0]='het' && GT[1]='het' && GT[2]='het'"

[1]SAMPLE_01:GT      [2]SAMPLE_02:GT      [3]SAMPLE_03:GT
0/1     0/1     0/1
0/1     0|1     0/1
0/1     0/1     0/1
0|1     0|1     0/1
1/2     2/3     0/2
```

For many samples  the above however is not very readable and also at least sometimes returns no variants at all (the expression might be too long to interpret). 

Therefore it is very nice that a file with sample names can be used to specify the samples that are required to have a certain genotype. 

```
cat 3_het_samples.txt
SAMPLE_01
SAMPLE_02
SAMPLE_03
```

Using this file in the filter expression as follows leads to the for me unexpected results of variants in which 1 sample being HET is already enough to be included.  

Is it the expected behavior that OR(||) is used to combine TRUE/FALSE HET criteria per sample?
Thus effectively only requiring at least sample from the file to be HET.

Can this optionally  or by default be changed to AND(&&)? 
 Thus effectively requiring all samples from the file to be HET.

Requiring all samples in the file to be HET makes more sense to me. 

```
bcftools view input.vcf-i "GT[@3_het_samples.txt]='het'"

[1]SAMPLE_01:GT      [2]SAMPLE_02:GT      [3]SAMPLE_03:GT
0|1     0/0     ./.
0|1     0/0     ./.
0/1     0/0     ./.
0/0     0|1     ./.
0/1     0|1     ./.
0/1     0/0     ./.
0|1     0/0     ./.
0/1     0/1     ./.
0/1     0/0     ./.
0/0     0|1     ./.
0/0     0|1     ./.
0|1     1|1     .
0|1     1|1     .
0/1     0/1     0/0
0/1     0/1     0/1
0/0     0/0     0/1
```

Thank you.

**Comment by pd3** [comment]
Yes, it is the expected behavior which, unfortunately, we cannot change. However, you could use the opposite logic and exclude sites which are not heterozygous in one of the samples:
````
bcftools view input.vcf -e "GT[@3_het_samples.txt]!='het'"
````

**Comment by WimSpee** [comment]
Thank you for the information and the tip.
