### ISSUE TITLE
 assert( k==ma->nout_als ); fails

### ISSUE THREAD

**Issue by alehresmann** [samtools/bcftools#1044]
Hello, 
I was trying to merge ~400 vcf.gz files into one, with bcftools merge. I got an assertion error on line 899 of vcfmerge.c:
 
```bcftools: vcfmerge.c:899: merge_chrom2qual: Assertion `k==ma->nout_als' failed.
Aborted```

Thee only reason I can see this happening is the following line:

`if ( i==0 || al_idxs[i] ) ma->out_als[k++] = strdup(ma->als[i]);`

So k can equal the number of nonzeros in al_idxs, or that value +1.
However, ma->nout_als always equals the number of 1s in al_idxs.

Is this normal, and if so, does it indicate a problem with my VCF files ? I can provide them to you if you'd like (although it is about 12GB of .vcf.gz files)

**Comment by alehresmann** [comment]
I've found the culprit vcf file, it appears to have had an invalid format. I'll close this then.

**Comment by bew0055** [comment]
How did you find which VCF was your problem one? I am running into the same issue.

**Comment by pd3** [comment]
@bew0055 Can you try with the latest code (http://samtools.github.io/bcftools/howtos/install.html), just added a more informative message which should help to narrow the problem down and identify the offending position.
