### ISSUE TITLE
bcftools concat could not load index!

### ISSUE THREAD

**Issue by Asutu** [samtools/bcftools#1045]
Hi,

I'm trying to concatenate a relatively large number of files, exactly 2737 files (which is not as such a large number), using the `--file-list` option of `bcftools concat`. However, I'm always getting an error message that `Failed to open tmp.Chr09_18095464_18242300.q13Q10.vcf.gz: could not load index`, but this is not true as I do have the index in the same directory as the compressed VCF file ($PWD).

My file list looks like the following:

```
$ head gather.fof
tmp.Chr01_0_862.q13Q10.vcf.gz
tmp.Chr01_1020_1049.q13Q10.vcf.gz
tmp.Chr01_1588_1630.q13Q10.vcf.gz
tmp.Chr01_1821_2308.q13Q10.vcf.gz
tmp.Chr01_2591_2668.q13Q10.vcf.gz
tmp.Chr01_2995_3135.q13Q10.vcf.gz
tmp.Chr01_3321_3588.q13Q10.vcf.gz
tmp.Chr01_4231_4438.q13Q10.vcf.gz
tmp.Chr01_6198_6301.q13Q10.vcf.gz
tmp.Chr01_6412_6503.q13Q10.vcf.gz
```

and if I do:

```
$ ls tmp.Chr09_18095464_18242300.q13Q10.vcf.gz
tmp.Chr09_18095464_18242300.q13Q10.vcf.gz tmp.Chr09_18095464_18242300.q13Q10.vcf.gz.tbi
```

the index file is there alongside the compressed VCF. It's not also a file-order issue because the previous and next files are contiguous with the file where `concat` is complaining:

```
# from `less`
tmp.Chr09_17940201_18094938.q13Q10.vcf.gz
tmp.Chr09_18095464_18242300.q13Q10.vcf.gz
tmp.Chr09_18242490_18268535.q13Q10.vcf.gz
```

As suggested in a previous issue (can't remember which one), we can use the `htsfile` to check the file formats, so:

```
$ htsfile tmp.Chr09_18095464_18242300.q13Q10.vcf.gz
tmp.Chr09_18095464_18242300.q13Q10.vcf.gz:	VCF version 4.2 BGZF-compressed variant calling data
$ htsfile tmp.Chr09_18095464_18242300.q13Q10.vcf.gz.tbi
tmp.Chr09_18095464_18242300.q13Q10.vcf.gz.tbi:	VCTabix compressed index data
```

Also, if I try to open this file with the `view` command there aren't any error messages printed to stderr and the command executes correctly (the file contents are good as well):

```
$ bcftools view tmp.Chr09_18095464_18242300.q13Q10.vcf.gz > /dev/null
$ echo $?
0
```

As I'm running this in a cluster, I thought `concat` could be using much more memory than I requested but this is not true as at termination of the process is only using ~321MB whereas I'm requesting 12GB (just in case...).

So, the VCF file seems to be correctly formatted, as is the index file and both are present in the same directory. Why is BCFtools complaining that it cannot find the index?

Thanks,
Pedro

Edit:

the full command I'm using is:

```
set -o pipefail
bcftools concat \
	--file-list gather.fof \
	--allow-overlaps --rm-dups both -Ov \
| (other pipes here)
```

Edit2:

BCFtools version 1.9:

```
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jmarshall** [comment]
The problem is probably too many open files — see e.g. #329 and #1022.

We had a go at producing a better error message for this case back in 2015 (see samtools/htslib#288), but that particular PR wasn't a good solution to the problem, as noted in the mailing list conversation of the time.

A simple way for htslib to improve the message in this case would be to add the particular case of `too_many_open_files` to the `bcf_sr_error` enum, print a message for it perhaps with a `ulimit` hint in `bcf_sr_strerror()`, and set that error when `bcf_sr_add_reader()` sees `EMFILE` or `ENFILE`.

**Comment by Asutu** [comment]
Thanks for your answer, not sure if that applies to this case because the `ulimit` is set to 100000 files.

```
$ ulimit -n
100000
```

**Comment by jmarshall** [comment]
Unfortunately the infrastructure is not there for bcftools to easily print out `errno` via `perror()` or `strerror()`.

What does strace say? (Look back from the end of the voluminous output for the failing system call.)

    strace bcftools concat \
	--file-list gather.fof \
	--allow-overlaps --rm-dups both -Ov > /dev/null

**Comment by Asutu** [comment]
Hmmm, right at the end of `strace` it really seems that's a problem with `Too many open files`. Not sure why this is happening then and why `ulimit` seems to give a much larger number...

```
read(1023, "\37\213\10\4\0\0\0\0\0\377\6\0BC\2\0\33\0\3\0\0\0\0\0\0\0\0\0", 32768) = 28
lseek(1023, 0, SEEK_SET)                = 0
open("tmp.Chr09_18095464_18242300.q13Q10.vcf.gz.csi", O_RDONLY) = -1 EMFILE (Too many open files)
open("tmp.Chr09_18095464_18242300.q13Q10.vcf.csi", O_RDONLY) = -1 EMFILE (Too many open files)
open("tmp.Chr09_18095464_18242300.q13Q10.vcf.gz.tbi", O_RDONLY) = -1 EMFILE (Too many open files)
open("tmp.Chr09_18095464_18242300.q13Q10.vcf.tbi", O_RDONLY) = -1 EMFILE (Too many open files)
write(2, "Failed to open tmp.NC_024339.1_R"..., 91Failed to open tmp.Chr09_18095464_18242300.q13Q10.vcf.gz: could not load index
) = 91
exit_group(-1)                          = ?
+++ exited with 255 +++
```

**Comment by wdecoster** [comment]
For a workaround to avoid too many open files: https://gigabaseorgigabyte.wordpress.com/2019/05/29/bcftools-concat-failed-to-open-variants-vcf-gz-could-not-load-index/

**Comment by Asutu** [comment]
Thanks @wdecoster, your link should have been the first hit on google.
I'm closing this issue as it as been solved.

**Comment by jkbonfield** [comment]
Ultimately I guess we should wishlist something to fix this.  Too many open files in merge simply means we need to do sub-merges and save to temporary files to avoid running out of file descriptors.  This is what the proposed workarounds do, but perhaps bcftools and samtools should be transparently doing this themselves.  (It's a bit of work so the problem is basically finding the time and deciding what priority it is.)

I'm a bit unsure why concat is doing this.  I guess it's very different to samtools concat which only needs 2-3 files open at any one time.  The bcftools concat documentation states it is still "concatenation", so I don't understand why it is opening all files at once, although it then goes on to state it can combine a SNP vcf with an indel vcf.  How is that concatenation and not merge? Confused!

**Comment by pd3** [comment]
The program is run with `--allow-overlaps`, the operation is to zip all chunks together. This could still be improved by employing the same strategy as the `--ligate` option which first identifies overlapping that must be read simultaneously.

**Comment by jkbonfield** [comment]
How is `concat --allow-overlaps` any different to `merge`?  This probably needs documenting, but from a naive read it sounds like identical operation.  If it's more efficient in `concat`, then does that just imply `merge` has room for optimisations?

I did a quick test of normal `concat` and it does appear to work sensibly; not opening all files at once.

**Comment by pd3** [comment]
`merge` creates a multi-sample file out of multiple single- or multi-sample files, the source files have different samples. The source files for `concat` must have the same samples, sometimes with overlapping sites.

This is well documented, RTFM!
;-)

**Comment by DLCrawford** [comment]
A simple answer to address to bcftools merge: Failed to open *.vcf.gz: could not load index.
If you bgzip, remove *vcf.gz.gzi (created by bgzip).
2nd  bcftools index
bcftools index -t *.vcf.gz
This solved my merge error "..could not load index"
