### ISSUE TITLE
bcftools query %END not extracting correct position

### ISSUE THREAD

**Issue by jodyphelan** [samtools/bcftools#1046]
I noticed a potential bug when running `bcftools query -f '%POS\t%END'` with a vcf file. It appears to extract the same number (`%POS`) twice for each variant instead of the proper `%END`. Strangely, if you first convert to bcf then it will extract fine.

I have uploaded the code to reproduce this issue [here](https://gist.github.com/jodyphelan/cbb8e2137d9a30ff8f567e5f78cc37ab). It should take ~3-5 min to run.

OS: Ubuntu 14.04
Samtools version: 1.9
Bcftools version: 1.9

**Comment by pd3** [comment]
This is now fixed, thank you for the bug report.
