### ISSUE TITLE
Annotating overlapping intervals

### ISSUE THREAD

**Issue by dmarkie** [samtools/bcftools#1047]
I am having trouble using the enhancement described in the closed issue #943. I have added a detailed description in that thread

**Comment by pd3** [comment]
Thank you for the bug report. Can you please check if this commit 2299ab6 fixes both issues?

**Comment by dmarkie** [comment]
The problem with variants outside annotation intervals seems fine - it runs and puts no annotation on those lines, which is great.
The second problem is largely resolved except for variants that fall within the first interval of the annotation source file. The first variant in that interval gets annotated correctly, I am using five columns from the source file (here it is within an overlap, so the append does exactly what it should):
`A=B3GALT6,B3GALT6;B=EHLERS-DANLOS_SYNDROME,SPONDYLOEPIMETAPHYSEAL_DYSPLASIA_WITH_JOINT_LAXITY_TYPE_1;C=confirmed,confirmed;D=biallelic,biallelic;E=loss_of_function,loss_of_function`
But subsequent lines from this interval (which should be identical) look like this:
`A=loss_of_function,loss_of_function;B=loss_of_function,loss_of_function;C=loss_of_function,loss_of_function;D=loss_of_function,loss_of_function;E=loss_of_function,loss_of_function`
It seems to be taking the last annotation column from the first variant, and using it for all columns in subsequent variants within that interval. This behavior is the same whether or not it is within an overlap. But curiously it only seems to happen to variants within the first interval of the source file, all subsequent intervals seem to perform as expected.

**Comment by pd3** [comment]
Any chance you could provide a small test case to reproduce the problem? This error did not show up in my tests.

**Comment by dmarkie** [comment]
Hi Petr,
I have below uploaded a cut down vcf for input, with an annotation source file and a header file, along with the output generated by the command:
`bcftools annotate -a AnnoSource.txt.gz -c CHROM,FROM,TO,Gene_symbol,-,Disease_name,-,Category,Allelic_requirement,Mutation_consequence -h Headers.txt --merge-logic Gene_symbol:append,Disease_name:append,Category:append,Allelic_requirement:append,Mutation_consequence:append Test.vcf.gz -Oz -o Testannotated.vcf.gz`

Now that I have cleared out all the other annotations and genotype information, it is a little clearer, and I had misrepresented what was happening in the output. As you can see there are no annotations (as expected) until the first interval(s) in the source file is encountered, and those variants within the interval (and within subsequent intervals) get annotated correctly. However variants between intervals get annotated in an unusual way - with every field entered as the last annotation field from the previous interval - when there should be no annotation. Hope that makes sense. Thanks for looking at this.

[Test.vcf.gz](https://github.com/samtools/bcftools/files/3367692/Test.vcf.gz)
[AnnoSource.txt.gz](https://github.com/samtools/bcftools/files/3367693/AnnoSource.txt.gz)
[Headers.txt](https://github.com/samtools/bcftools/files/3367716/Headers.txt)
[Testannotated.vcf.gz](https://github.com/samtools/bcftools/files/3367720/Testannotated.vcf.gz)

**Comment by pd3** [comment]
Thank you for the test case, hopefully this will fix it https://github.com/samtools/bcftools/commit/f1ca229d9fe3e7db29aa25edd134cbd7fdcbdc4e

**Comment by dmarkie** [comment]
Thanks Petr, that's now working as expected and is going to add real value to our annotations. 
One small remaining issue is that it is still limited to annotations of Type=String, and won't work if we are trying to "_append_" a Float or Integer type annotation. This restriction seems a bit arbitrary given that the append option probably doesn't require any maths operations, and this is probably only relevant to the _sum_, _avg_, _min_ and _max_ options which are not yet implemented. Would it be possible to relax this restriction for _append_, and treat Integer and Float annotations as if they were strings for this process? One possible workaround for us would be to label these type of annotations as "String" in the header for the purpose of annotating, and then go back and edit the entries in the vcf header to the appropriate type - but it would seem simpler just to get it done during the annotation step.
Thanks for all your help.
David

**Comment by pd3** [comment]
The numeric types should now work with sum,avg,min,max.

**Comment by dmarkie** [comment]
Hi Petr,
Is it possible for the --merge-logic append option to also accept numeric annotations? Often we don't want any maths operation during annotation, just to list the values.

Also the modifications made to bcftools to fix the issues above seem to require an enormous (and for us unfeasible) amount of memory when the annotation source file is very large. Some of our source files are precomputed values for every base substitution in the reference, and although they don't necessarily contain overlapping annotations, the memory requirement is enormous, even if the --merge-logic option is not invoked. 
Thanks David

**Comment by pd3** [comment]
The increased memory usage is an inevitable side effect of supporting the multiple overlapping intervals. It is possible to be smarter, but not easily I am afraid.

Adding `--merge-logic` for numeric annotations, yes, it should be added as well.

**Comment by dmarkie** [comment]
Thanks for all your help. I figured the memory issue was an unavoidable consequence. Given that most of our very large annotation source files are non-overlapping (they are descriptions of all single base substitutions) would a simple interim solution be for the default for --merge-logic to assume there are no overlapping intervals in the source and behave as the previous versions of BCFtools? 

With regards to numeric annotaions it is just the append option for --merge-logic that is not accepting them at present.

**Comment by pd3** [comment]
I added a new `--single-overlaps` option which triggers the original behavior and thus will keep the memory low. Please let me know in case of problems.
