### ISSUE TITLE
Genomes with high heterozygousity rates

### ISSUE THREAD

**Issue by pwmcclurg** [samtools/bcftools#1048]
I am using bcftools call  (-c or -m) to call variants after calling bcftools mpileup.  There are close by variants (looking at just the mpileup output) that have identical ref/alt ratios but one (21649581)  is getting filtered out, whereas the other (21649577) does not get filtered after the bcftools call.  These are five bases away from each other and in this berry genome we expect the het rate to be measured in percentages (say 5%).

My question is - are the default parameters for bcftools call designed for human genomes, and is there any way to increase the prior heterozygosity rate from the command line?  Below I show first the bcftools mpileup for these five lines, and next the bcftools call -c around the variant that passes the filter,  Thank you for your help and for your outstanding algorithms,

Dr. Phil McClurg
Algorithms Engineer
Driscolls, Onc.

bcftools mpileup:

Fvb1    21649577        .       C       G,<*>   0       .       DP=55;I16=15,22,4,5,1689,86107,437,23115,609,18829,263,8209,795,18815,194,4332;QS=0.710033,0.289967,0;VDB=0.460862;SGB=-0.662043;RPB=0.995315;MQB=0.0403726;MQSB=0.349453;BQB=0.633626;MQ0F=0.236364    PL:AD   86,0,191,198,218,255:37,9,0
Fvb1    21649578        .       T       <*>     0       .       DP=55;I16=20,27,0,0,2206,114738,0,0,872,27038,0,0,1003,23373,0,0;QS=1,0;MQSB=0.267268;MQ0F=0.254545     PL:AD   0,141,255:47,0
Fvb1    21649579        .       A       <*>     0       .       DP=54;I16=20,26,0,0,2145,109741,0,0,830,25274,0,0,993,23007,0,0;QS=1,0;MQSB=0.348801;MQ0F=0.259259      PL:AD   0,138,255:46,0
Fvb1    21649580        .       T       <*>     0       .       DP=55;I16=20,26,0,0,2191,116665,0,0,830,25274,0,0,983,22673,0,0;QS=1,0;MQSB=0.348801;MQ0F=0.254545      PL:AD   0,138,255:46,0
Fvb1    21649581        .       A       G,<*>   0       .       DP=55;I16=17,20,3,6,1833,100197,343,13673,749,22853,81,2421,805,18541,168,3830;QS=0.886621,0.113379,0;VDB=0.884391;SGB=-0.662043;RPB=0.877037;MQB=0.144782;MQSB=0.348801;BQB=0.436518;MQ0F=0.254545     PL:AD   0,15,255,111,255,255:37,9,0

bcftools call -c:

Fvb1    21649536        .       C       G       34.0087 .       DP=60;VDB=0.155664;SGB=-0.662043;RPB=0.913101;MQB=0.0194477;MQSB=0.0929106;BQB=0.839151;MQ0F=0.25;AF1=0.5;AC1=1;DP4=19,25,5,4;
MQ=23;FQ=37.016;PV4=0.715253,1,1,1        GT:PL:AD        0/1:64,0,181:44,9
Fvb1    21649577        .       C       G       56.0072 .       DP=55;VDB=0.460862;SGB=-0.662043;RPB=0.995315;MQB=0.0403726;MQSB=0.349453;BQB=0.633626;MQ0F=0.236364;AF1=0.5;AC1=1;DP4=15,22,4,5;MQ=24;FQ=59.0154;PV4=1,1,1,1   GT:PL:AD        0/1:86,0,191:37,9
Fvb1    21649588        .       T       C       130.008 .       DP=55;VDB=0.0437503;SGB=-0.692914;RPB=0.968928;MQB=0.278521;MQSB=0.496439;BQB=0.8864;MQ0F=0.254545;AF1=0.5;AC1=1;DP4=8,12,11,14;MQ=24;FQ=133.014;PV4=1,0.461929,0.0688002,1     GT:PL:AD        0/1:160,0,193:20,25

**Comment by pd3** [comment]
With `call -c` one can increase the `-p` option and with `call -m` the `-P` option to achieve greater sensitivity. 

However, the site 21649577 will not be called because the number of alternate reads in the pileup is too small and gives the binomial probability of 4e-5 or so. This is regardless of heterozygosity of the organism, the only assumption here is the ploidy - mpileup and calls only support haploid and diploid genomes.

**Comment by pwmcclurg** [comment]
I probably should have made the output clearer, but 21649577 is being called (bcftools call -c), whereas 21649581(bcftools mpileup) is not being called and they have precisely the same number of reference and alternate alleles. (and DP).  But I think you have answered my question.   I will lower the the P(Ref|D) threshold and that will produce what I want.

I want to thank you for your prompt reply - that is as awesome as this software!

All the best, Phil

P.S. This berry has ploidy = 4 but we are treating it as diploid for this analysis.

**Comment by pd3** [comment]
I think if you look at the genotypes (FORMAT/GT), you might find that although 21649577 appears in the output, it is called as a hom (0/0).

I suggest that you try freebayes, it can do higher ploidies as well, I think.

**Comment by pwmcclurg** [comment]
This is actually an octoploid genome so we don't expect to find all the variants (given that some occur in .875/.125 ref/alt ratios.  So the -p option will really help us.

But in this case

For Fvb1 21649577 I'm seeing 

GT:PL:AD 0/1:86,0,191:37,9

and assuming 0/1 is a heterozygous SNP.  Am I missing something?


The exact calls were

bcftools mpileup -C0 -d200 -Ov -a AD -f Fvb_genome.fas sorted_bam_filename  | bcftools call -cv -p.0000001 -Ov vcf_filename

so I used -cv which I assume will only list variants.  But this is just a report to you - you've really helped me out and I know how to proceed now.

All the best, Phil

**Comment by pwmcclurg** [comment]
oops - the -p.0000001 was NOT in the call that produced the output - I added that later for another run.  Otherwise the call is exactly as run.

Sorry, Phil

**Comment by pd3** [comment]
Sorry, I made a copy-and-paste mistake. I wanted to highlight the second variant site, 21649581, not the first one. Although the number of supporting reads is apparently the same for both, the second has smaller mapping and/or base qualities
````
$ bcftools query test.vcf -f '%POS\t%REF\t%ALT[\t%AD][\t%PL]\n' -t Fvb1:21649577,Fvb1:21649581
21649577	C	G,<*>	37,9,0	86,0,191,198,218,255
21649581	A	G,<*>	37,9,0	0,15,255,111,255,255
````

Both `-c` and `-m` calling models find the first variant with the default parameters
````
$ bcftools call -cv test.vcf | bcftools query -f '%POS\t%REF\t%ALT[\t%GT]\n' -t Fvb1:21649577,Fvb1:21649581
21649577	C	G	0/1

$ bcftools call -mv test.vcf | bcftools query -f '%POS\t%REF\t%ALT[\t%GT]\n' -t Fvb1:21649577,Fvb1:21649581
21649577	C	G	0/1

$ bcftools --version
bcftools 1.9-206-g4694164
Using htslib 1.9-247-g6eacc77
````

When the priors are maxed up, we get
````
$ bcftools call -cv test.vcf -p 1 | bcftools query -f '%POS\t%REF\t%ALT[\t%GT]\n' -t Fvb1:21649577,Fvb1:21649581
21649577	C	G	0/1
21649581	A	G	0/0

$ bcftools call -mv rmme.vcf -P 1 | bcftools query -f '%POS\t%REF\t%ALT[\t%GT]\n' -t Fvb1:21649577,Fvb1:21649581
21649577	C	G	0/1
````

which does not help you either.

Although I applaud your determination to use bcftools, in this case I'd strongly encourage you to try [freebayes](https://github.com/ekg/freebayes) instead as its model was built to handle tetraploid genomes
````
freebayes -f ref.fa -p 4 aln.bam >var.vcf
````

**Comment by pwmcclurg** [comment]
Thanks again - yes we have freebayes installed and I will definitely try that.
