### ISSUE TITLE
feature request: prune -n without regard to AF

### ISSUE THREAD

**Issue by mmatschiner** [samtools/bcftools#1050]
Hi there,
Thanks for actively developing this great tool. I welcome that the last vcftools features that were so far unavailable in bcftools are now becoming available, but I'm not sure why "bcftools +prune -n" differs from "vcftools --thin" in that bcftools removes sites with low AF first. This can often be problematic in downstream analyses that assume that thinned sites are an unbiased sample of the full set of sites. As far as I can tell, an equivalent to "vcftools --thin" that selects sites without considering AF is not available in bcftools. Please correct me if I'm wrong. If not, would it be possible to add such an equivalent option?
Thanks,
Michael

**Comment by dwuab** [comment]
I'm also looking forward to this enhancement. In my workflow, thinning is the only step where I have to step out of bcftools and use tools such as PLINK2 with info loss.

**Comment by pd3** [comment]
How does the pruning work in this scenario? Removing random sites? All but first site in the buffer?

**Comment by dwuab** [comment]
Both 1) removing random sites (like plink --thin) and 2) removing first site in the buffer (like plink --bp-space) are useful to have.

**Comment by pd3** [comment]
I added a new option
```
-N, --nsites-per-win-mode STR 
```
where STR can be
```
  maxAF .. keeps sites with biggest AF  (this is the default)
  1st   .. keeps sites that come first
  rand  .. picks sites randomly
```
Please try it out and let me know in case of problems.

**Comment by mmatschiner** [comment]
Thanks a lot, @pd3 ! I tried the new feature (`bcftools +prune -w 10000bp -n 1 -N 1st`, `bcftools +prune -w 10000bp -n 1 -N maxAF`, `bcftools +prune -w 10000bp -n 1 -N rand`) and it seems to do what it should. Great!
