### ISSUE TITLE
setGT new genotype

### ISSUE THREAD

**Issue by javierpradom** [samtools/bcftools#1053]
So far this plugin only allows to output one of the following genotypes:
       and the new genotype can be one of:
           .    .. missing ("." or "./.", keeps ploidy)
           0    .. reference allele
           M    .. major allele
           p    .. phased genotype
           u    .. unphase genotype and sort by allele (1|0 becomes 0/1)

Would it be possible to add the alternative allele and a custom genotype as options as well?

**Comment by pd3** [comment]
Possibly. Can you be more specific?

**Comment by javierpradom** [comment]
At the moment only allows to set the reference allele (0) or the major allele (M). The latter will be either set as 0/0 (or 0 depending on ploidy) or 1/1. 
This limits quite a lot the options to change the genotypes on certain queries. It is not possible to set these calls to heterozygous (0/1) or homozygous alternative (1/1), or any other genotype for multiallelic variants.

A heterozygous or alternative reference call could be set:
H .. heterozygous genotype (0/1)
A .. alternative allele (1/1)

For multiallelic variants these may not be enough and custom genotypes may be necessary. This could be set by the user with a string like:
C="GT" .. custom genotype defined by the user 

The custom genotype may be enough addition to sort this out.

**Comment by maribuon** [comment]
Hi @pd3 ,
the above could be very useful indeed. Is there are timeline for implementation?
Best wishes,
Mariana

**Comment by pd3** [comment]
This is now supported via a new `c:GT` specifier, for example to force heterozygous genotype for all:
```
bcftools +setGT in.vcf -- -t a -n c:'m/M'
```
I hope this helps

**Comment by jkobject** [comment]
Hi! 

Following on #1134 it seems this issue is more closely related to my problem.

I tried what is written here but was not able to force homozygous alt.

**Comment by pd3** [comment]
Are you running the latest version? If yes and it's not working, a small test case to reproduce the problem would be helpful. Please open as separate issue.

**Comment by jkobject** [comment]
Yes this is fixed in `1.13`! (`1.8` is what `conda` installs) 
Thanks!
