### ISSUE TITLE
bcftools query: Different samples in XXX

### ISSUE THREAD

**Issue by billzt** [samtools/bcftools#1054]
I download the 1000 genome files (VCF format) in ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/

And try to run:
```
ls *.vcf.gz >vcf.files
bcftools query -f '%CHROM\t%POS\t%ID\n' -r X:2781454-2781454 -v vcf.files
```

It complains that:
```
Different samples in ALL.chr10_GRCh38.genotypes.20170504.vcf.gz and ALL.chr11_GRCh38.genotypes.20170504.vcf.gz
```

However I checked the samples in `ALL.chr10_GRCh38.genotypes.20170504.vcf.gz` and `ALL.chr11_GRCh38.genotypes.20170504.vcf.gz` and comfirm that they are the same.

**Comment by billzt** [comment]
Well, perhaps I'm misleaded by the document. It seems as `bcftools query` can only be used on a single file? #421

**Comment by pd3** [comment]
This feature should work provided that the `-v` files have the same samples. This was not working but should be fixed now. Thank you for the bug report.

**Comment by letslearnwebdev** [comment]
Would you please elaborate what you mean by "provided that the -v files have the same samples"?
I am using latest version (i.e. ` 1.10.2`), `-v` option with two VCF files from different participants, and both VCF files have `.tbi` and `.csi` indexes and still I get the same message: "Different samples in sample1.vcf.gz and sample2.vcf.gz".

**Comment by pd3** [comment]
The option is meant to help in situations where a big VCF is split into chunks, e.g. by chromosome. If this assumption is not met, just run the command on each VCF individually.
