### ISSUE TITLE
How to generate consensus that only shows high-frequency alternate alleles?

### ISSUE THREAD

**Issue by wolfgangrumpf** [samtools/bcftools#1055]
I'm trying to generate a consensus sequence that only shows alternate alleles if they show up at greater than 1% - essentially we're trying to compensate for a slightly higher error rate in PacBio sequencing.  I've tried various permutations on excluding MAF/AF but I think I'm just not understanding how this works:

bcftools consensus -e'AF<0.009' -f reference.fa compressed.vcf.gz

Again, we want our consensus to show us deviations from the reference ONLY if they show up more than 1% of the time.  Any suggestions appreciated!!!!

**Comment by pd3** [comment]
The command looks correct. Can you try `bcftools view -H -e'AF<0.009'` to see if this indees filters the correct sites? A variation of this is `-i'AF>=0.01'`. There may be differences in how sites with/without INFO/AF annotations are handled.

**Comment by wolfgangrumpf** [comment]
That command does seem to output a VCF that only shows the desired variants.  I guess I could pipe that to a new vcf and generate the consensus against *that*?  I still can’t consensus to do it….




Cheers,


Dr. Wolfgang Rumpf
Research Scientist, Mathematical Medicine, The Research Institute at Nationwide Children's Hospital
Professor, Dept. of Biotechnology, UMUC
wolfgang.rumpf@nationwidechildrens.org . wolfgang.rumpf@gmail.com
Mobile - (614) 638-6797 . Skype - wolfgang.rumpf
---------------------------------------------------------------------------------------------

**Comment by wolfgangrumpf** [comment]
And I *still* can't get it to work.  When I view the vcf with that particular exclude parameter it does only show me the "correct" variants.  But when I try to pipeline it, my consensus sequence always has ALL variants included.  Here's what I've tried:

bcftools view -e'AF<0.009' -Oz -o simple.vcf.gz compressed.vcf.gz
bcftools index simple.vcf.gz
bcftools consensus -I -f reference.fa simple.vcf.gz > simple.consensus.fa

The idea here was to generate a new vcf, which worked, and when viewed, looked fine - but as I said, the simple.consensus.fa still showed all variants.

I also tried this:
bcftools consensus -e'AF<0.009' -I -f reference.fa simple.vcf.gz > simple.consensus.fa

with absolutely no difference.  What am I doing wrong???

**Comment by wolfgangrumpf** [comment]
So the problem is that the command bcftools view -e'AF<0.009' -Oz -o simple.vcf.gz compressed.vcf.gz does NOT actually exclude the desired variants!  Here's a sample of the vcf:

```
pNLRep-Cap2	143	.	C	G,.	0	.	DP=5631;I16=2638,2885,1,0,441022,3.72203e+07,60,3600,331380,1.98828e+07,60,3600,138075,3.45188e+06,25,625;QS=0.999811,0.000189307,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=1;BQB=1;MQ0F=0	PL	0,255,255,255,255,255
pNLRep-Cap2	144	.	G	C,.	0	.	DP=5628;I16=2641,2933,1,0,492892,4.42745e+07,13,169,334440,2.00664e+07,60,3600,139350,3.48375e+06,25,625;QS=0.999961,3.92059e-05,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=1;BQB=1;MQ0F=0	PL	0,255,255,255,255,255
```
How can I filter out those two sites?

**Comment by pd3** [comment]
There is no INFO/AF annotation in your VCF and no FORMAT/GT field to compute it on the fly, therefore the condition is not true for any of the sites.

**Comment by wolfgangrumpf** [comment]
Thanks for the pointer - apparently I was a few years out of date in my approach.  I'm using BCFTools now to call variants and the output is as we expected (no variants).
