### ISSUE TITLE
bcftools intersection of multi-vcf files with different samples

### ISSUE THREAD

**Issue by michellekee** [samtools/bcftools#1056]
Hi,

I have 3 vcf files from different sample population (ie: different n-numbers) and would like to get a file with an intersection of common SNPs found in all 3 population.

I have used bcftools isec for the first 2 populations, took the intersection (either 0002.vcf or 0003.vcf generated from this) and then did another bcftools isec with the 3rd population. However, I realised that the .vcf file only included subject IDs from the 3rd population. 

Is there a way to get a .vcf file using bcftools isec with all common SNPs, that includes 3 samples populations?

I tried bcftools concat -d -a but I'm not sure if it included SNPs that were unique to the each  population. 

Thank you very much!

**Comment by pd3** [comment]
If the resulting file should be a single VCF with all samples, you want to use the `merge` command at some point. For example, you can first merge and then filter out sites with missing genotypes. For example like this:
````
bcftools merge A.vcf.gz B.vcf.gz C.vcf.gz -Ou | bcftools view -i'GT!="mis"'
````
