### ISSUE TITLE
A bug occurred to bcftools filter/view 

### ISSUE THREAD

**Issue by biozzq** [samtools/bcftools#1059]
Dear all,

When extracting specific sites from a large vcf file (contains ~100 millions sites) by bcftools with following command, I found that the output always ignored the sites located at the end of the chromosome. However, when setting the `-R` with the ignored sites alone, the output is normal. Hope you can help me with this error. Thank you.

`bcftools filter -R $chr.site -i 'TYPE = "snp" && N_ALT = 1 && F_MISSING <= 0.1' -g 3 $chr.vcf.gz | bcftools view -S sample -o $chr.vcf.gz -O z`

Other information about the version and vcf file,
The version of bcftools I used is Version: 1.9 (using htslib 1.9).
The VCF file was generated with the GATK--4.1.2.0 and the index (.tbi) was also from GATK.

Best regards,
Zhuqing

**Comment by biozzq** [comment]
Dear all,

I also tried to change `-R` to `-T`, but the same bug occurred.

Best wishes.

**Comment by pd3** [comment]
Is it possible this is not a bug but there is a large overlapping deletion close to the missed sites?  The bug report does not provide enough information to debug the problem. Any chance you could create a small reproducible test case?

**Comment by biozzq** [comment]
Dear @pd3,
Thank you for your response. When using the missed sites alone, the output is normal, so, it is impossible that there is a large overlapping deletion close to the missed sites. I know it's better to provide some test case for you to debug the problem, but this problem just work for the large VCF file as input (the size is about 100G-200G for each chromosome). 
Best regards,

**Comment by pd3** [comment]
Don't use just the missed sites alone but include some interval before. Keep extending it until you get the error. As the issue currently stands, it's impossible to say what is wrong. For example, since the files are so big, maybe something is killing your job before it finishes and it may be a problem in bcftools at all.

**Comment by biozzq** [comment]
Dear @pd3 

When including some interval before, bcftools works ok. About the job running, I confirmed the program terminted normally. I have shared you some test files to find out the problem, hope this can help you.

The test files can be downloaded from the google drive:
https://drive.google.com/open?id=1ji6Yt34d1RG4q7-iXD9gLsOTqyDQQ9pQ

The command I used as following:
bcftools filter -T 25.site -i 'TYPE = "snp" && N_ALT = 1 && F_MISSING <= 0.1' -g 3 25.tmp.vcf.gz  | bcftools view -S sample -o 25.vcf.gz -O z

Best wishes,
Zhuqing

**Comment by pd3** [comment]
What is the output you expected? Just quickly tested with your files and the coordinates at the end are present::
````
$ tail -3 25.site
25	42857890
25	42858093
25	42858343

$ bcftools query -f'%CHROM\t%POS\n' 25.vcf.gz | tail -3
25	42857890
25	42858093
25	42858343
````

**Comment by biozzq** [comment]
Dear @pd3 

Thank you very much for your time. I found the output is ok now when using another computer. I am sorry for having disturbed you.

Best wishes,
Zhuqing
