### ISSUE TITLE
AF (Allele Frequency) not generated in BCF output?

### ISSUE THREAD

**Issue by wolfgangrumpf** [samtools/bcftools#1060]
I'm not sure what I'm doing wrong here - I've found a variant but my output isn't providing me with a frequency of the variant.  Here's the command I ran:

bcftools mpileup -d 1000 -f reference.fa my.sorted.bam | bcftools call -m -Ob -o my.bcf

The only variant found was this one - with no frequency:

AAV.CAG.CD19	4031	.	G	T	228	.	DP=2280;VDB=4.43722e-05;SGB=-0.693147;RPB=1;MQB=1;MQSB=1;BQB=1;MQ0F=0;AC=2;AN=2;DP4=1,0,677,408;MQ=60q

Help?

**Comment by pd3** [comment]
What do you mean when you say allele frequency: the frequency of the allele in the population (which is the reserved INFO/AF tag) or the number of the non-reference reads in the pileup (INFO/AD and FORMAT/AD). The first can be inferred from AN,AC and filled using the `+fill-tags` plugin. The latter can be filled with `mpileup -a FORMAT/AD`.

**Comment by wolfgangrumpf** [comment]
Ah, ok - for some reason I was expecting AF to show up automatically.  I can compute it from AN/AC as you said....thanks!
