### ISSUE TITLE
bcftools csq segfaults when alternate allele is missing

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1061]
I think this is an easy bug. In `csq.c` there is the following code:
```
    if ( !rec->n_allele ) call_csq = 0;   // no alternate allele
    else if ( rec->n_allele==2 && (rec->d.allele[1][0]=='*' || rec->d.allele[1][1]=='*') ) call_csq = 0;     // gVCF, not an alt allele
    else if ( rec->d.allele[1][0]=='<' )
    {
        if ( strncmp("<INS",rec->d.allele[1], 4) ) call_csq = 0;    // only <INS[:.*]> is supported at the moment
    }
```
However, when the alternate allele is missing `rec->n_allele = 1` and the following code ends up attempting to access `rec->d.allele[1][0]` which cause a segmentation fault. It would likely be enough to change:
```
    if ( !rec->n_allele ) call_csq = 0;   // no alternate allele
```
to this:
```
    if ( rec->n_allele < 2 ) call_csq = 0;   // no alternate allele
```
And, since I am at it, would it be possible to have the `--no-version` option available in `bcftools csq`? :-)

Best gene annotating tool ever. By far.

**Comment by pd3** [comment]
This is now fixed and the `--no-version` option added. Thanks for the bug report and the fix.
