### ISSUE TITLE
bcftools view filter to compare AD between ALT alleles fails

### ISSUE THREAD

**Issue by VenithaB** [samtools/bcftools#1063]
Hello! I am trying to compare the AD between ALT alleles within each record; however, I am facing an error when trying to check if `bcftools view -i` subsets the desired records correctly:

`>bcftools view -i 'FMT/AD[0:1] > FMT/AD[0:2]' multialleles.vcf.gz -Oz -o test_subset.vcf.gz`

`>bcftools: filter.c:3077: filter_test: Assertion !filter->flt_stack[nstack-2]->nsamples || !filter-flt_stack[nstack-1]->nsamples' failed.
Aborted (core dumped)`

A few records from `multialleles.vcf.gz`:

`2       342483  .       GAAAA   GAAA,G  784.73  PASS   GT:AD:DP:GQ:PL  1/2:2,32,9
:43:99:822,363,303,519,0,1569`

`2       483331  .       A       AAAT,AAAGGATGGTAT       1079.73 PASS     GT:AD:DP:GQ:PL  1/2:0,15,12:27:99:1117,501,453,627,0,642`

The VCF file has only multialleles. I want only records in which the ALT1 has a higher AD than ALT2. I plan to use the same filter using `bcftools consensus` along with `-H 1` option to obtain a consensus sequence where ALT1 is applied only to records where ALT1's AD is higher than ALT2.

**Comment by pd3** [comment]
Can you please check if you are using the latest version of bcftools (to get the latest version, it is best to follow the instructions here http://samtools.github.io/bcftools/howtos/install.html). If the problem persists, could you please provide a small VCF to reproduce the bug?

**Comment by VenithaB** [comment]
Hello, re-installed both htslib and bcftools as  suggested in that page. I am still getting the same error. 

Also I was previously using 

`bcftools 1.9-158-gf24ccc9`
`Using htslib 1.9-149-gf5b75ff`

I'm attaching a subset of my variants:

[test.txt](https://github.com/samtools/bcftools/files/3471648/test.txt)

**Comment by pd3** [comment]
This should be now resolved. Please try it out and let me know in case of problems.

**Comment by VenithaB** [comment]
Hello. Works fine. Thank you for the quick resolution.
