### ISSUE TITLE
When the --fai option of reheader will we be released?

### ISSUE THREAD

**Issue by serge2016** [samtools/bcftools#1066]
Hello!

Could you tell me, please, when the `--fai` option of `reheader` command will we be released?

**Comment by pd3** [comment]
The next release of bcftools is tied to htslib and the release date of it is uncertain. 

I encourage users to use the latest github version as it contains many bug fixes. A stable release is just an illusion. Please see the installation instructions here http://samtools.github.io/bcftools/howtos/install.html
