### ISSUE TITLE
Functions on INFO tags

### ISSUE THREAD

**Issue by cwhelan** [samtools/bcftools#1069]
The documentation for expressions says this in the "functions" section:

> function on FORMAT tags (over samples) and INFO tags (over vector fields): maximum; ?minimum; arithmetic mean (AVG is synonymous with MEAN); median; standard deviation; sum; string length; absolute value; number of elements.

>MAX, MIN, AVG, MEAN, MEDIAN, STDEV, SUM, STRLEN, ABS, COUNT

But when I try to count the number of items in an INFO vector, eg:

`-i 'COUNT(INFO/ALGORITHMS) == 1'`

bcftools gives the following error:

`COUNT() can be applied only on FORMAT fields`

**Comment by pd3** [comment]
The `COUNT()` function was intended to count the number of matching FORMAT columns. The commit 7171da0 expands it to count the number of fields in INFO tags and should work for your use case as well.
