### ISSUE TITLE
Filter expression does not work in bcftools view?

### ISSUE THREAD

**Issue by biozzq** [samtools/bcftools#1070]
Dear all,

When using following command, I found the ouput didn't exclude the sites with MAF < 0.001.

`bcftools view -S id -i 'MAF >= 0.001' -o subset.vcf.gz -O z --threads 4 input.vcf.gz`

However, it works like following,

`bcftools view -S id --threads 4 input.vcf.gz -Ou | bcftools view -i 'MAF >= 0.001' -o subset.vcf.gz -O z`

Best wishes,
Zhuqing

**Comment by pd3** [comment]
One must be careful when subsetting samples and filtering in one command as removing samples can change MAF. Better is to separate this and run in two explicit commands as you've done. Also note that some of these annotations are calculated on the fly but can be also taken from INFO when present.

If you still think it's a bug, please provide a small test case to reproduce the problem.

**Comment by biozzq** [comment]
Dear @pd3 

Thank you very much. I do not think it's a bug, I think we should explain these in somewhere.

best wishes,
Zhuqing

**Comment by pd3** [comment]
Added a note about this (https://github.com/samtools/bcftools/commit/0ab4d6da50160673afc58f7b7c40eda8cce69699) and closing the issue now as resolved.
