### ISSUE TITLE
how to make a union of three or more vcf files?

### ISSUE THREAD

**Issue by serine** [samtools/bcftools#1071]
Hi there, 

Apparently this is a trivial issue, but I can't figure this out. I'm trying to take a union of at least three vcf files. I expect a single vcf files - `union.vcf`. None of the several combinations that I've tried with `bcftools isec` results in a single vcf files. I always get three vcf files, with a `README.txt` similar to this one

```
This file was produced by vcfisec.
The command line was:   bcftools isec  -n +1 -p union -Oz a.vcf b.vcf c.vcf

Using the following file names:
0000.vcf.gz    for stripped    a.vcf
0001.vcf.gz    for stripped    b.vcf
0002.vcf.gz    for stripped    c.vcf
```

My understanding reading the docs is that `-n` option meant to regulate whether you want an intersect `-n =3` (intersect of three files, still expect single vcf, but  don't get one) or a union `-n +1` meaning I want a variant to be found in at least a single vcf file, once again expect a single vcf file, but don't get one. 

I'm figuring that perhaps `isec` should be used in conjunction with `merge` i.e once I created "unique" vcfs with `-n =3` meaning I have three distinct vcfs. I then `merge` them into single - **union** vcf. 
If this is the right workflow would be able update the docs, or point me to the repo with docs and I'll attempt PR in. 

just fyi this is simple python script I used to test the union (naive implementation) 

```#!/usr/bin/env python3

import sys

fn1 = sys.argv[1]
fn2 = sys.argv[2]

chk = {}

with open(fn1) as fd1:
    for i in fd1:
        line = i.strip()
        if line.startswith("#"):
            continue
        tokens = line.split("\t")

        pos = tokens[1]
        name = tokens[0]

        if pos in chk:
            sys.stderr("Oops %s" % pos)
        chk[pos] = name

with open(fn2) as fd2:
    for i in fd2:
        line = i.strip()
        if line.startswith("#"):
            continue

        tokens = line.split("\t")

        pos = tokens[1]
        name = tokens[0]

        if pos not in chk:
            chk[pos] = name
            #print(name, chk[pos], pos)

print(len(chk))
```

**Comment by pd3** [comment]
That's right, the `isec` command operates on a site level. It is not intended for combining samples and merging multiple VCFs into one, as you correctly say, `merge` is for that.

Pull requests for the man page (http://samtools.github.io/bcftools/bcftools.html) can be made here https://github.com/samtools/bcftools/blob/develop/doc/bcftools.txt and for the howtos (http://samtools.github.io/bcftools/howtos/index.html) here https://github.com/samtools/bcftools/tree/gh-pages/howtos (*.txt).

**Comment by serine** [comment]
@pd3 great, thanks, will attempt to PR

Just want to put this here for complete reference in case other will find the thread.

This is how I made a union of three vcf files

```
bcftools isec -n -1 \
              -p union_dir \
              -Oz \
              vcfFiles/A_A2/0000.vcf.gz \
              vcfFiles/B_B2/0000.vcf.gz \
              vcfFiles/B_D8/0000.vcf.gz

bcftools merge -Oz \
               -o union_dir/merged.vcf.gz \
               union_dir/0000.vcf.gz \
               union_dir/0001.vcf.gz \
               union_dir/0002.vcf.gz

bcftools index union_dir/merged.vcf.gz
```

**Comment by GuoanQi1996** [comment]
@serine From your complete reference, to my understanding, doesn't the **bcftools isec -n -1** means extract unique/private variants found in three provided vcf files?

**Comment by pd3** [comment]
@GuoanQi1996 That is right, the `isec -n -1` command will create a VCF with private variants only.

Reading the whole issue again, it is not clear to me why `bcftools merge` was not used in the first place.

**Comment by vinaydeep26** [comment]
@serine could you or anyone else guide me how would you take a consensus from the 3 vcf files.
for example I have 3 variant files and i want to take only those variants that are present in at least 2 files and then get the results in a single vcf file. 
Thanks
