### ISSUE TITLE
-R bedfile 

### ISSUE THREAD

**Issue by phickner** [samtools/bcftools#1079]
Please help with commands to call SNPs in specified regions of a genome. Whole genome calls are taking 5-6 hours, but I only want 245 genes of interest. I have tried to use the -R option, but have not had any success. The code I use for the whole genome is below. 
Thanks. 

bcftools mpileup -Ou -f LlonJ1m.fa JAC05.bam.mask | bcftools call -m -Ov | bcftools filter -e '%QUAL<30  > JAC05.vcf

**Comment by pd3** [comment]
What does it mean, that you had no success? Assuming you are using a recent version of bcftools, this should work
```` 
bcftools mpileup -Ou -R regs.txt -f ref.fa aln.bam | bcftools call -mv -Ob -o raw.bcf
bcftools view -e '%QUAL<30' raw.bcf -Oz -o calls.vcf.gz
````

**Comment by phickner** [comment]
Sorry, but it was my mistake. I had indexed the bams but then transferred them to a different directory and forgot to also transfer the index files. So the commands I listed were fine, I just had to transfer the index files to the correct directory.
