### ISSUE TITLE
feature request: can "annotate" mark variants present in -a file?

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#108]
I would like to use bcftools annotate as follows:
bcft annotate -a b.vcf.gz a.vcf.gz
And have every marker in file a.vcf.gz have a binary flag when the same marker is present in b.vcf.gz
However, either this is not possible or too complicated to understand from the help section
If it is possible to do this, please show an example in the help section

**Comment by pd3** [comment]
This is is now supported via `bcftools annotate --mark-sites`, added by https://github.com/samtools/bcftools/commit/6ccecd140528e5c005934b1f8a6177de6ddda0dc.
