### ISSUE TITLE
bcftools merge --force-samples can fail

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1081]
The following code reproduces the error:
```
(echo "##fileformat=VCFv4.2"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tA\t2:A") | bgzip > A.vcf.gz
tabix -f A.vcf.gz

(echo "##fileformat=VCFv4.2"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tA") | bgzip > B.vcf.gz
tabix -f B.vcf.gz

bcftools merge A.vcf.gz B.vcf.gz --force-samples
```

with error:
```
[E::bcf_hdr_add_sample_len] Duplicated sample name '2:A'
bcftools: vcfmerge.c:683: maux_init: Assertion `n_smpl==bcf_hdr_nsamples(args->out_hdr)' failed.
Aborted (core dumped)
```

My understanding is that the resolution of duplicate sample names is not clever enough to assign a new valid name all the time. It seems like `bcftools merge --force-samples` is changing the ID of `A` to `2:A` but this sample already exists in the VCF causing the renaming attempt to fail.

**Comment by pd3** [comment]
Such conflicts should be now avoided. Thank you.
