### ISSUE TITLE
How to install Split_vep with the default plugins?

### ISSUE THREAD

**Issue by Rosmaninho** [samtools/bcftools#1087]
Hey,

I wanted to use split_vep but it's not installed with the default plugins when I create a Docker image of bcftools.
Nor is it installed when I install bcftools in Mint 19.2.
What are the procedures to install this plugin since I can't seem to get it installed in any way and none of the Docker images that I tried has it installed??

**Comment by pd3** [comment]
The installation instructions are documented here http://samtools.github.io/bcftools/howtos/install.html

**Comment by Rosmaninho** [comment]
Maybe consider including those instructions in https://www.htslib.org/download/ and make it simpler to include all plugins even if one doesn't follow those instructions. Is there a rationale for lacking plugins if those specific instructions aren't followed?

**Comment by pd3** [comment]
The htslib.org website points to "stable" releases. The release cycle is rather slow, better is to use the latest development version. Not only it contains new features, such as the split-vep plugin, but also many bugfixes.

**Comment by student-t** [comment]
> The installation instructions are documented here http://samtools.github.io/bcftools/howtos/install.html

The instructions don't say how a plugin is installed.
