### ISSUE TITLE
Replacing Non-ACGTN reference allele

### ISSUE THREAD

**Issue by finswimmer** [samtools/bcftools#1088]
According to the vcf specs the `REF` column is only allowed to have `ACGTN` as characters.

The reference sequence I'm using have wobble codes like `B` at some positions. I came into a [situation](https://github.com/ekg/freebayes/issues/367) where I need to use `bcftools +fill-from-fasta`. This leads to situation where wobble codes are introduced in the `REF` column.

Can the `+fill-from-fasta` plugin get modified in that way, to replace wobble codes by `N`?

Thanks a lot.

fin swimmer

**Comment by pd3** [comment]
It is possible. But how about modifying the reference sequence instead? 
````
echo 'ABCDEF' | tr -c ACGTN\\n N
````

**Comment by finswimmer** [comment]
Hello @pd3 ,

as this is a one-time job this could be an option. Also replacing the characters in the final vcf is possible.

But it doesn't feel clean to me. non-ACTGN characters are allowed in fasta but not in the REF vcf field. So I would see the primary responsibility to convert wobble codes to `N` by the variant caller and/or tools that manipulate the vcf file.

Saying this, I would be very happy if it could be implemented in the plugin :)

fin swimmer

**Comment by pd3** [comment]
OK, added now.

**Comment by finswimmer** [comment]
Perfect. Thanks a lot!
