### ISSUE TITLE
bcftools norm --rmdup removed multiallelic sites

### ISSUE THREAD

**Issue by naumenko-sa** [samtools/bcftools#1089]
Hello!

Thanks for such a useful bcftools!

I wanted to remove duplicated (meaning identical chr, pos, ref, and alt) records from the vcf file.

Input vcf file
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER
chr1	146984765	rs781933389	G	T	7794.38	PASS
chr1	146984765	rs781933389	G	A	7794.38	PASS
chr1	146984765	.	G	A	8470.69	PASS
```

I assumed that the result should be:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER
chr1	146984765	rs781933389	G	T	7794.38	PASS
chr1	146984765	rs781933389	G	A	7794.38	PASS
```
However, with bcftools 1.9 using the command
```
bcftools norm --rm-dup snps -Oz input.vcf.gz> output.vcf.gz
```
I've gotten:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER
chr1	146984765	rs781933389	G	T	7794.38	PASS
```
I.e. both records with allele A were removed. Having multiple alleles at a site (multiallelic sites) is quite common for large sequencing projects, like gnomad, and their respective vcfs.

Could you please consider changing the behaviour of `bcftools norm` so it retained multiallelic sites, but removed exact duplicates?

Sergey

**Comment by pd3** [comment]
This is possible with a rather unintuitive `--rm-dup none`. To avoid future confusion, this is now replaced with `exact` by cbeca0c. For backward compatibility the `none` option remains active but is not advertised anymore.

**Comment by naumenko-sa** [comment]
thanks!

**Comment by fgvieira** [comment]
I tried this change and it is working on `bcftools norm`, but not in `bcftools concat`.
@pd3 could you do the same change on `bcftools concat`?

Thanks,

**Comment by pd3** [comment]
@fgvieira this is done for `bcftools concat` as well
