### ISSUE TITLE
bcftools ROH analysis using custom AF 

### ISSUE THREAD

**Issue by kvn95ss** [samtools/bcftools#1090]
I've tried running this command - 
`bcftools roh -G30 -e freqs.tab.gz sample.vcf -o sampleID.RHO`
And got the following output -
```
Number of target samples: 1
Number of --estimate-AF samples: 0
Number of sites in the buffer/overlap: unlimited
Number of lines total/processed: 148995/0
Number of lines filtered/no AF/not biallelic/dup: 0/148333/0/662
No usable sites were found.
```
So based on the manual, I ran the following command `bcftools view -i'type="SNP" && AF>0' -m2 -M2 -s 62540009_S28 -Ou practise_1.vcf | bcftools +counts -i'GT!="./." && GT!="."'` and got the output -

```
Number of samples: 1
Number of SNPs:    130527
Number of INDELs:  0
Number of MNPs:    0
Number of others:  0
Number of sites:   130527
```

To me, it's not entirely clear what files have to be provided. 

I've provided the sample VCF, and from the in-house VCF which we have, the AF counts were extracted with the command `bcftools query -f'%CHROM\t%POS\t%REF,%ALT\t%INFO/TAG\n' file.vcf | bgzip -c > freqs.tab.gz` 

What am I doing wrong? Also, the combined VCF has around 200+ samples, so I expected Number of --estimate-AF samples to show that number, but it's zero. 

Any help appreciated!

**Comment by pd3** [comment]
The `-e` option is supposed to take a list of samples, not allele frequencies, as described in the manual and usage page. Please check here http://samtools.github.io/bcftools/howtos/roh-calling.html for an example how to annotate your VCF first.

However, the program should throw an error or at least print a warning about the failure to find the non-existent samples in the VCF.

**Comment by pd3** [comment]
The program will not give a warning (commit 3516abc) if incorrect file is used. I hope this will solve the issue, please reopen if not.
