### ISSUE TITLE
Relink Problem of bcftools

### ISSUE THREAD

**Issue by furqan915** [samtools/bcftools#1093]
Hi
I am facing this pop up notice after every bcftools command.
bcftools: Relink `/root/miniconda3/bin/../lib/./libgfortran.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'

How can I do relink or how to remove this error?

Thanks

**Comment by pd3** [comment]
The binary was probably compiled with different version of the libgfortran library than is installed on the system. You might try to locate the correct version (if installed) and add the path to the  LD_LIBRARY_PATH environment variable. Probably easier (and safer) is to install from scratch as described here http://samtools.github.io/bcftools/howtos/install.html

**Comment by pd3** [comment]
The problem is actually different, sorry. On some systems linking with `-lrt` is necessary. This dependency has been now removed (5591c09).
