### ISSUE TITLE
bcftools roh not producing output

### ISSUE THREAD

**Issue by sahwa** [samtools/bcftools#1094]
I am trying to estimate roh in single individuals from a multi-sample bcf file. I used the following command, copied from [this page](https://samtools.github.io/bcftools/howtos/roh-calling.html). I downloaded the allele frequency files from the same website and didn't alter them.

`bcftools annotate -c CHROM,POS,REF,ALT,AF1KG -h 1000GP-AFs/AFs.tab.gz.hdr -a 1000GP-AFs/AFs.tab.gz $prefix/allExtraAllGreekAllGerman.1000GenomesSNPS.chr$chr.bgz.vcf.gz`

which produced the following stdout:

```
Number of target samples: 1
Number of --estimate-AF samples: 0
Number of sites in the buffer/overlap: unlimited
Number of lines total/processed: 2227038/1967941
Number of lines filtered/no AF/not biallelic/dup: 0/6343/0/1
```

But the results file simply had:

```
# This file was produced by: bcftools roh(1.9-207-g2299ab6+htslib-1.9-271-g6738132)
# The command line was:	bcftools roh --AF-tag AF1KG -M 100 -s Mkg12 -m genetic-map/genetic_map_chr2_combined_b37.txt -O z -o roh_results_Mkg12_chr2.txt
#
```

Am I missing something - why is it not producing any output, even when it is processing lines?

**Comment by pd3** [comment]
The `-o z` should imply that but apparently it does not. It is easy to fix. In the meantime, can you run the roh command with `-o srz` instead of `-o z`?

**Comment by pd3** [comment]
This should be now fixed.
