### ISSUE TITLE
Bcftools mpileup exit without finishing, without warnings

### ISSUE THREAD

**Issue by kirsten2** [samtools/bcftools#1096]
Hi there,

Im having some issues with getting bcftools to run to completion, it crashes in a consistent manner, depending on the combination of input bam-files.  I have made two subset bamfiles, containing reads mapping to three consecutive genomes in my reference database. In this case the crash occurs towards processing the second genome in the database, but only when the two bam-files are processed together.

#Running mpileup with bcftools, doesnt complete (input bam-files and output attached)
bcftools mpileup --max-depth 2000 -f  db_191017_red AcCh01_sub.bam AcCh02_sub.bam > AcCh01_AcCh02_sub_mpileup_bcf.vcf

#Running mpileup with samtools directly (mpileup format) works fine (output attached)
samtools mpileup --max-depth 2000 -f  db_191017_red AcCh01_sub.bam AcCh02_sub.bam > AcCh01_AcCh02_sub_mpileup.txt

#Running each sample independently works fine too.
bcftools mpileup --max-depth 2000 -f ~/Bee_metagenome_databases/db_191017_red AcCh01_sub.bam > AcCh01_sub_mpileup_bcf.vcf
bcftools mpileup --max-depth 2000 -f ~/Bee_metagenome_databases/db_191017_red AcCh02_sub.bam > AcCh02_sub_mpileup_bcf.vcf

Any hint at whats going on here? Thanks in advance!

[AcCh01_sub.bam.gz](https://github.com/samtools/bcftools/files/3760840/AcCh01_sub.bam.gz)
[AcCh02_sub.bam.gz](https://github.com/samtools/bcftools/files/3760843/AcCh02_sub.bam.gz)
[AcCh01_AcCh02_sub_mpileup.txt.gz](https://github.com/samtools/bcftools/files/3760846/AcCh01_AcCh02_sub_mpileup.txt.gz)
[AcCh01_AcCh02_sub_mpileup_bcf.vcf.gz](https://github.com/samtools/bcftools/files/3760847/AcCh01_AcCh02_sub_mpileup_bcf.vcf.gz)

**Comment by kirsten2** [comment]
#Versions: 
bcftools 1.9
Using htslib 1.9-404-g5162f01

**Comment by pd3** [comment]
The command does not look right, the `-f` option expects the reference sequence
````
bcftools mpileup -f reference.fa alignments.bam | bcftools call -mv -Ob -o calls.bcf
````

**Comment by kirsten2** [comment]
The fasta-file is named: "db_191017_red" (no fasta suffix). The database is too large to upload here (15M zipped).

If you like, I can try to re-do the error, with a reduced database.

**Comment by pd3** [comment]
I just tested with the latest development version (1.9-255-g3516abc, using htslib 1.9-404-g5162f01) and it finished OK, also valgrind was happy
````
$ samtools index AcCh01_filt_sorted.bam
$ samtools index AcCh02_filt_sorted.bam
$ samtools faidx db_191024.fa
$ bcftools mpileup --max-depth 2000 -f db_191024.fa AcCh01_filt_sorted.bam AcCh02_filt_sorted.bam
````

Can you please try with a later version? http://samtools.github.io/bcftools/howtos/install.html

**Comment by kirsten2** [comment]
I now installed bcftools 1.9-255-g3516abc, Using htslib 1.9-407-g1c1a5b0), using the instructions on the link you provided. Apart from the warning about "AC_CONFIG_SUBDIRS: you should use literals", it looks ok from what I can see

Are you sure you got output for the third genome? With bcftools mpileup, I get info for data for this number of positions per genome:

10003.1003.BINDI        129394
10004.1004.Ga0072399    7835

With samtools mpileup, I get:
10003.1003.BINDI        129315
10004.1004.Ga0072399    7941
10005.1005.Ga0077910    32325

No errors are printed to stdout, but Im missing everything from the third genome.

**Comment by pd3** [comment]
Indeed, you are right. This turns out to be a problem in htslib, introduced when moving to 64-bit positions by this commit https://github.com/samtools/htslib/commit/eb2334e6e895982ba280dedc1a3884547089fd43. 

This is now fixed by https://github.com/samtools/htslib/commit/e43b472fcd44be2a935e40e2cbdb4202a1e743c4.

**Comment by kirsten2** [comment]
Thanks!


I'll re-install and try it out first thing monday,


Best,

Kirsten

________________________________
