### ISSUE TITLE
bcftools merge error when fields are not defined

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#110]
I have a VCF file with two individuals, and the genotype lines read like this:
1	10146	rs375931351	AC	A	...	GT:AD:DP:GQ:PL	./.:.:.:.:.	./.:.:.:.:.
When trying to merge the VCF file with another VCF file, I get the following error:
Incorrect number of PL fields at 1:10146, cannot merge.
However, the VCF file was generated as a result of first calling genotypes with the GATK Haplotype Caller and then extracting two individuals with bcftools view.
My best guess is either this is a bug in bcftools merge or it is a bug in bcftools view when extracting samples (i.e. it should not have outputted the above line if the fields were empty for each individual that was extracted)

**Comment by hberger** [comment]
I have the same problem as the OP. Two VCF files, one generated with GATK, the second one generated manually. GATK was instructed to emit calls for all positions from the second file if reaching confidence. 

Position 1:82154 was the conflicting position. I was not among the called variants, and in the custom files all PL fields were set to missing:

$ bcftools query -f'%REF %ALT [ %PL]\n' -r1:82154  ../GATK_called.vcf.gz
$ bcftools query -f'%REF %ALT [ %PL]\n' -r1:82154  wgEncodeHaibGenotypeGtypeSnp2014-09-15.sorted.vcf.gz
A G  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

I solved the problem by re-creating the second file without any PL fields.

**Comment by pd3** [comment]
There were some fixes after 1.1 release, can you please check if you get the same error with the latest github version? 
http://samtools.github.io/bcftools/

**Comment by hberger** [comment]
You are right, the last version of bcftools from github does not show this problem any more.

 

bcftools 1.1-134-g868b818
Using htslib 1.1-123-g5f7a4ea

 

Thanks a lot !

 

Best, Hilmar

 

Gesendet: Montag, 12. Januar 2015 um 09:28 Uhr
Von: pd3 <notifications@github.com>
An: samtools/bcftools <bcftools@noreply.github.com>
Cc: hberger <ju0815nk@gmx.net>
Betreff: Re: [bcftools] bcftools merge error when fields are not defined (#110)


There were some fixes after 1.1 release, can you please check if you get the same error with the latest github version?
http://samtools.github.io/bcftools/

**Comment by pd3** [comment]
Great, closing the issue now.
