### ISSUE TITLE
Omitting header items with timestamp (e.g. bcftools_viewCommand)

### ISSUE THREAD

**Issue by steveb-cirina** [samtools/bcftools#1100]
My end goal is, given the same vcf input, output an identical bcf. It appears that the output bcf has a header item which captures the command and date/time, and this appears to be the only thing that differs.

**Question** is there a way to omit header items that capture a time/date stamp ?

**For example**
```
bcftools view -o output1.bcf -O b input.vcf
bcftools view -o output2.bcf -O b input.vcf
# I would like the following to indicate no differences, but the date/time
# in the header will indicate they are different.
cmp output1.bcf output2.bcf
```

I may have missed something in the documentation but I didn't see anything.

**Comment by valeriuo** [comment]
Try `bcftools view -o output1.bcf -O b input.vcf --no-version`

**Comment by steveb-cirina** [comment]
@valeriuo Thanks. I'm doing some testing to see if this works but so far things are looking good. I will reply either way with success or failure.

**Comment by steveb-cirina** [comment]
This appears to have addressed / fixed my issue, thanks again.
