### ISSUE TITLE
Read depth of one shows Het

### ISSUE THREAD

**Issue by sandeshsth** [samtools/bcftools#1104]
I was wondering about the Het call even with just single allele depth. 0,1 and 1,0 are giving 0/1 genotype. The output is from Bcftools (Default).

![Picture1](https://user-images.githubusercontent.com/11355194/68400143-285c6c80-013d-11ea-98b6-90b73b1abe16.png)

**Comment by pd3** [comment]
The caller assumes Hardy-Weinberg equilibrium and with insufficient evidence, a het call becomes more likely than an ALT hom. There are some parameters that can be tweaked (-P, -F). However, with just one read there is no way of knowing if it's a hom or a het.

**Comment by sandeshsth** [comment]
@pd3 Do you have any suggestion to improve the call? Any specific parameters in -P and -F that I should try? We will have very low coverage sequencing of around 0.05x. Thanks

**Comment by pd3** [comment]
It's hard to tell what counts as improvement. If it is, in your scenario, beneficial to see samples individually rather than assuming HWE, the sensitivity can be increased by running in a single sample mode as suggested here https://github.com/samtools/bcftools/issues/1168#issuecomment-595771828

**Comment by sandeshsth** [comment]
I think `--group-samples -` solved the problem. Thanks.
