### ISSUE TITLE
Installation problem for make

### ISSUE THREAD

**Issue by ctlxu** [samtools/bcftools#1108]
Hi, I just installed samtools-1.9 and htslib-1.9 with cywgin on a window10 workstation. However, for the bcftools-1.9, I got the following error for the make command:

make: *** No rule to make target 'plugins/GTsubset.cygdll', needed by 'plugins'.  Stop.

Please help. Thanks.

**Comment by valeriuo** [comment]
Windows support is not available for any released version of bcftools.
You can currently build the develop branch over MSYS/MinGW. After PR #1109 is merged, you should also be able to build and use bcftools over Cygwin.
