### ISSUE TITLE
bcftools norm

### ISSUE THREAD

**Issue by roselucia** [samtools/bcftools#1114]
Hi everyone,

I have a question regarding bcftools norm ( bcftools norm Left-align and normalize indels; check if REF alleles match the reference; split multiallelic sites into multiple rows; recover multiallelics from multiple rows (Galaxy Version 1.9+galaxy1)).
Using the tool 6 variants in my vcf got realigned. However, for one of them it seems like the realignment is not the most left position according to the following definition:
„A VCF entry is left aligned if and only if its base position is smallest among all potential VCF entries having the same allele length and representing the same variant“ (Adrian Tan, Gonçalo R. Abecasis and Hyun Min Kang. (2015) Unified Representation of Genetic Variants. Bioinformatics. https://academic.oup.com/bioinformatics/article/31/13/2202/196142 )

original:
chr1: 115254052 C-CTC

realigned:
chr1: 115254051 T -TCT

Here is part of the sequence (GRCh37) as presented in the Genome Data Viewer by NCBI starting with Position 115254047:
-CAAGTCTACTAA-

Shouldn’t be the correct realigned position:
chr1: 115254050 G GTC

In order to double check my assumption I ran vt normalize (VT normalize normalizes variants in a VCF file (Galaxy Version 0.1.0))  with the following options: 

Choose the source for the reference list | cached
-- | --
Using reference genome | hg19
File containing list of intervals |  
Window size for local sorting of variants | 10000
Choose the output format | VCF

 I compared the too vcf files and for all 6 variants for which the bcftools norm did a realignment, the variants got realigned also. All realignments were the same, except for the one variant I thought to be realigned incorrectly.

realigned with vt normalize:
chr1: 115254050 G - GTC

I am glad for any suggestions or explanations.

Thanks a lot!
Rose

**Comment by pd3** [comment]
This looks like a bug, thank you for reporting it.

**Comment by roselucia** [comment]
Hi thanks for the fast response! Is there a chance the bugg gehts fixed fast? Then I would wait before using the tool for my analysis. 
Thanks a lot.
Rose

**Comment by pd3** [comment]
I just checked with 1.9 and the latest development version and both produce the correct result:
````
# input
1   115254052   .   C   CTC

# output
1   115254050   .   G   GTC
````

Can you please provide a test case to reproduce the problem?

**Comment by roselucia** [comment]
Can you provide an email addrress? Then I will provide an example file right away.

Thanks Rose

**Comment by pd3** [comment]
It's on the profile page. Thanks.

**Comment by roselucia** [comment]
Perfect! I will send you a file right when I get home from work. 

Von meinem iPhone gesendet

**Comment by roselucia** [comment]
Hi Peter, unfortunately the file is too big to be sent via email. Is there another way to send you the file?
Thanks a lot Rose

**Comment by pd3** [comment]
Thanks for the testing data. However, I am unable to reproduce the behavior:
````
chr1   115254050   .   G   .   100 PASS    DP=1176
chr1   115254050   .   G   GTC 98  LowAQ   DP=1151;ANT=ENST00000369535|intron_variant|YES|ENST00000369535.4:c.291-1703_291-1702dupGA||NRAS||
````
Please try to upgrade bcftools, maybe you are using an old version by accident.  (Try `bcftools --version`)

**Comment by roselucia** [comment]
Hi Peter,
thanks a lot for your answer.
I am using bcftools norm 1.9 (available on usegalax.eu).
To my knowledge this is the newest version isn’t it? 
All the best Rose


Von meinem iPhone gesendet

**Comment by pd3** [comment]
That's correct, 1.9 is the latest released (numbered) version. Then there is the latest development version which can be installed as described here http://samtools.github.io/bcftools/howtos/install.html.

However, the version you are supposedly running works fine, so it's probably some error on your side:
````
bcftools norm -f  ref.fa test.bcf | bcftools view -H -t 1:115254050 | cut -f1-5
1	115254050	.	G	.
1	115254050	.	G	GTC
````

**Comment by wm75** [comment]
Hi @pd3, Wolfgang here from the usegalaxy.eu team, to whom @roselucia reported this initially.
I can actually reproduce the incomplete normalization she's seen with conda-installed bcftools 1.9 and my local copy of hg19.fa, but observed something confusing:
```
bcftools norm -f ref.fa test.vcf  | grep -C1 115254051
chr1	115254050	.	G	.	100	PASS	DP=1176	GT:GQ:AD:DP:VF:NL:SB:NC:GQX	0/0:100:1154:1176:0.0187:20:-100:0.0109:100
chr1	115254051	.	T	.	100	PASS	DP=1144	GT:GQ:AD:DP:VF:NL:SB:NC:GQX	0/0:100:1141:1144:0.0026:20:-100:0.0387:100
chr1	115254051	.	t	tCT	98	LowAQ	DP=1151;ANT=ENST00000369535|intron_variant|YES|ENST00000369535.4:c.291-1703_291-1702dupGA||NRAS||	GT:GQ:AD:DP:VF:NL:SB:NC:AQ:GQX	0/1:98:1112,39:1151:0.0339:20:-42.3699:0:3.208:98
chr1	115254053	.	T	.	100	PASS	DP=1151	GT:GQ:AD:DP:VF:NL:SB:NC:GQX	0/0:100:1146:1151:0.0043:20:-100:0.0213:100
```
I noticed the lowercase `t` and retried with the same ref with nucleotides turned to all uppercase:
```
chr1	115254050	.	G	GTC	98	LowAQ	DP=1151;ANT=ENST00000369535|intron_variant|YES|ENST00000369535.4:c.291-1703_291-1702dupGA||NRAS||	GT:GQ:AD:DP:VF:NL:SB:NC:AQ:GQX	0/1:98:1112,39:1151:0.0339:20:-42.3699:0:3.208:98
chr1	115254051	.	T	.	100	PASS	DP=1144	GT:GQ:AD:DP:VF:NL:SB:NC:GQX	0/0:100:1141:1144:0.0026:20:-100:0.0387:100
chr1	115254053	.	T	.	100	PASS	DP=1151	GT:GQ:AD:DP:VF:NL:SB:NC:GQX	0/0:100:1146:1151:0.0043:20:-100:0.0213:100
```
So, it seems that bcftools norm at 1.9 is still case-sensitive? I found #601 suggesting that this should be fixed since quite some time?

**Comment by pd3** [comment]
Thank you for identifying the bug, it is fixed now.
