### ISSUE TITLE
Clarification regarding bcftools view -x

### ISSUE THREAD

**Issue by VenithaB** [samtools/bcftools#1124]
According to the bcftools documentation:

>-x, --private: print sites where only the subset samples carry an non-reference allele.

I have used the command as follows:

```bcftools view -S sample.txt -x input.vcf.gz -Oz -o output.vcf.gz```

According to my understanding, output.vcf.gz contains records where at least one sample in ```sample.txt``` has 0/1 or 1/1 or 1/2, and 0/0 in all other samples not included in the sample text file. Is that right?

**Comment by pd3** [comment]
That should be the case. Note the other samples can as well have missing genotypes `./.`.
