### ISSUE TITLE
feature request: filter snps near indels and other structural variations

### ISSUE THREAD

**Issue by dwuab** [samtools/bcftools#1126]
bcftools filter --SnpGap is great, but only works with indels. For example, it does not work with the following variant because it is categorised as "other" in bcftools view (variant from 1KG3):
```
22      18211021        rs202228518     T       AC      100     PASS
```
I suggest a feature to filter snps near indels, structural variations and "other" variants.

**Comment by pd3** [comment]
This feature has been now added and can be used for example like this:
````
# the default, these two commands are equivalent
bcftools filter -s + -g 2
bcftools filter -s + -g 2:indel

# filter SNPs close to indels, complex events (eg. T>AC)
bcftools filter -s + -g 2:indel,other
````
