### ISSUE TITLE
bcftools merge change ./. to 0/0 unexpectedly! HELP!!!

### ISSUE THREAD

**Issue by KingCM** [samtools/bcftools#1127]
I need to divided ./. and 0/0 in my project .But when I merged multiple gvcf with command blow
`bcftools-1.9 merge -g b37.fasta -l vcf_list -r 22 -Oz -o merged.g.vcf.gz
bcftools index -t merged.126.g.vcf.gz
` 
I suddenly found that some sites in some samples are ./. but present  0/0 in merged vcf ,for example in gvcf of sample named X1000 

**#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  X1000  
22      38119137        .       A       .       .       PASS    END=38120040;MinDP=103  GT:DP   0/0:103  
22      38120042        .       T       .       .       PASS    END=38122450;MinDP=100  GT:DP   0/0:100**

we can see that sample of X1000 is ./. at 22:38120041 ,because the first line END with 38120040
and the second line start with  38120042, but this site changed in merged vcf 0/0 with the same DP of first line 103! Look at the merged vcf result below:
`$bcftools view -H -s X1000 chr22.726.g.vcf.gz 22:38120041`

**22	38120041	.	G	A	228	PASS	VDB=0.220144;SGB=-0.693147;RPB=2.16709e-07;MQB=2.24518e-10;MQSB=0.589603;BQB=0.202026;MQ0F=0;ICB=1;HOB=0.5;MQ=31;DP=119704;DP4=31546,15142,32164,6881;MinDP=10;AN=2;AC=0	GT:PL:DP:AD	0/0:.:103:.**

And you can notice the last column `0/0:.:103:.`
I also decrease some samples when merging them and the result is ./. correctly ,but how this happened, is it related with samples size?
I need to use result to run by Plink software and it can recognize the different of ./. and 0/0 ,and I
also need to figure out the call rate of the sites ,so, it's really important for this problem.Plsease Someone give me some help .Best wishes!

**Comment by pd3** [comment]
Any chance you could provide a small ready-to-use test case to reproduce the problem? Also, what version of bcftools are you running, does the problem occur with the latest version?

**Comment by KingCM** [comment]
> Any chance you could provide a small ready-to-use test case to reproduce the problem? Also, what version of bcftools are you running, does the problem occur with the latest version?

[bcftools_merge.20191231.zip](https://github.com/samtools/bcftools/files/4012111/bcftools_merge.20191231.zip)
A complete example is submitted and please try in your way.
The bcftools version I used is 1.9,bcftools --version information list below
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
In the example,I have find the different result with 3 and 4 samples' merge
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A000	B000	P001	P002
9	6686815	.	G	A	222	PASS	VDB=0.000704574;SGB=-0.662043;RPB=0.0443614;MQB=0.0443614;MQSB=0.98568;BQB=0.995736;MQ0F=0;ICB=1;HOB=0.5;MQ=38;DP=174;DP4=33,33,48,51;AN=6;AC=3	GT:PL:DP:AD	0/1:183,0,64:12:3,9	./.:.:.:.	0/1:255,0,154:25:9,16	0/1:188,0,224:18:10,8
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A000	B000	P001	P002	P004
9	6686815	.	G	A	222	PASS	VDB=0.000704574;SGB=-0.662043;RPB=0.0443614;MQB=0.0443614;MQSB=0.98568;BQB=0.995736;MQ0F=0;ICB=1;HOB=0.5;MQ=38;DP=174;DP4=33,33,48,51;MinDP=10;AN=8;AC=3	GT:PL:DP:AD	0/1:183,0,64:12:3,9	0/0:.:25:.   0/1:255,0,154:25:9,16	0/1:188,0,224:18:10,8	./.:.:.:.
Sample B000's GT changed from ./. to 0/0 you will see.
PS: Thanks for your kindness and happy new year!

**Comment by pd3** [comment]
Thank you for the test case, I just pushed a fix. Please try it out and let me know if you spot any other problems.
