### ISSUE TITLE
bcftools call -c : unknown file type

### ISSUE THREAD

**Issue by francicco** [samtools/bcftools#1129]
Hi,

I running this pipe:

`samtools mpileup -f $fasta $bam | bcftools call -c - | vcfutils.pl vcf2fq -d 1`

and I get this error:
```
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[mpileup] 1 samples in 1 input files
Failed to read from standard input: unknown file type
@
Use of uninitialized value $l in numeric lt (<) at /mnt/storage/home/tk19812/software/bcftools/misc/vcfutils.pl line 566.
+
Use of uninitialized value $l in numeric lt (<) at /mnt/storage/home/tk19812/software/bcftools/misc/vcfutils.pl line 566.
```

From the first pipe `samtools mpileup -f $fasta $bam` I get this type of output:
```
1_1	114	A	1	^K.	C
1_1	115	T	1	.	F
1_1	116	A	1	.	H
1_1	117	C	1	.	E
1_1	118	T	1	.	H
1_1	119	A	1	.	H
1_1	120	G	1	.	G
1_1	121	T	1	.	H
1_1	122	T	1	.	H
1_1	123	A	1	.	D
```

The problem is with the `bcftools call`, because it throws me the error:

```
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[mpileup] 1 samples in 1 input files
Failed to read from standard input: unknown file type
```

I used to run this command before, maybe there's an issue with the versions?

```
Program: samtools (Tools for alignments in the SAM format)
Version: 1.9-166-g74718c2 (using htslib 1.9-348-ga44f5ae)
```
```
Program: bcftools (Tools for variant calling and manipulating VCFs and BCFs)
Version: 1.9-226-g63f4b93 (using htslib 1.9-348-ga44f5ae)
```

What's the problem?
Thanks
F

**Comment by pd3** [comment]
Just in case anyone else stumbles upon the same problem: `bcftools mpileup` should have been used, not `samtools mpileup`

**Comment by francicco** [comment]
Yes, thanks, I figured it out. I should have text a follow up to that
mistake with the solution.
Thanks a lot for your help
F

**Comment by yongjiam** [comment]
Hi Francicco,
I am having the same problem here, how did you solve it? Thanks.

**Comment by pd3** [comment]
@yongjiam This thread was resolved, not sure what else do you need? Please see here http://samtools.github.io/bcftools/howtos/variant-calling.html
If this does not help, open a new issue.

**Comment by SunWinner01** [comment]
But I also had similar problems using bcftools mpileup. Can you help me analyze the cause of the error? @pd3

**Comment by SunWinner01** [comment]
I also encountered a similar problem and wanted to ask how you solved it? Do you still have an impression? @yongjiam

**Comment by SunWinner01** [comment]
I use bcftools mpileup and bcftools call. An error occurred when using it. Then in order to find errors. I run these two commands separately. Found no errors in bcftools mpileup. The error just occurred when running bcftools call. But I don't know what causes it. Hope to get your reply. @pd3
