### ISSUE TITLE
remove multi-allelic SNPs and INDELs and remove extra annotations

### ISSUE THREAD

**Issue by safiqu** [samtools/bcftools#1130]
Dear all
I am new in this NGS world, I know I can use "bcftools view" and do "bcftools annotate" this but I don't know how to handle this . 
bcftools view -m2 -M2  data.vcf  |  bcftools annotate  > mydata.vcf

someone could help me pls

**Comment by pd3** [comment]
It is not clear what you want to do. The program aims to be a multi-purpose tool that needs to be told what to do, it does not automagically annotate with annotations you need. Please read the full documentation here http://samtools.github.io/bcftools/howtos/index.html and here http://samtools.github.io/bcftools/bcftools.html.
