### ISSUE TITLE
bcftools norm error

### ISSUE THREAD

**Issue by Fazulur** [samtools/bcftools#1131]
Dear bcftools team,

I got the below error when I tried to normalize vcf (generated using gatk jointcalling for genome build 37)  using bcftools 1.9 version. 
**Error: wrong number of fields in FMT/MMQ at 1:10146, expected 14474, found 21711**

Command I used
bcftools view --threads 16 -r 1 sample.vcf.gz  |bcftools norm --threads 16 -m -any -O b -o test.bcf.gz

Could you please help me to resolve this issue.

Thanks In Advance
Fazulur Rehaman

**Comment by pd3** [comment]
This looks like a big VCF. The error message suggests that the FORMAT annotation MMQ across all samples has different number of values than expected. Can you share the output of
```
bcftools view sample.vcf.gz -r 1:10146 -Oz -o test.vcf.gz
```
eg send it to my email listed on the profile page?

**Comment by pd3** [comment]
Thank you for the test case. It seems you are using an older version of bcftools, as otherwise it should have failed with the following error message
````
[E::bcf_hdr_add_sample_len] Empty sample name: trailing spaces/tabs in the header line?
````
After removing the trailing blank spaces, I can run
````
$ bcftools query -f '[%REF,%ALT  %MMQ\n]' test.vcf |  awk '$2!="."' 
AC,A,*  40,0
AC,A,*  36,0
AC,A,*  40,0
AC,A,*  40,0
AC,A,*  30,0
AC,A,*  32,0
AC,A,*  25,0
AC,A,*  36,0
AC,A,*  35,0
AC,A,*  27,0
AC,A,*  39,0
AC,A,*  37,0
AC,A,*  0,25,0
AC,A,*  34,0
````
and see that although the MMQ tag is defined as Number=A in the header, only one of the samples has the correct count of three values but the rest has only two. This should be fixed in the program that produced the VCF, ideally a bug report should be issued. If you don't need the tag, a quick work around for you is to remove the offending tag by running `bcftools annotate -x FMT/MMQ`.

**Comment by Fazulur** [comment]
Dear Petr Danecek,

Thanks a lot for your quick resposne & resolving the issue.
I will submit bug report to GATK regarding this issue. For now, i will remove MMQ tag from my VCF file.

Thanks & Regards
Fazulur Rehaman

**Comment by zofieLin** [comment]
Hi, 
I also suffered a similar error when using bcftools norm.
I was using bcftools/1.11, 
`bcftools norm -m-both -o test.norm.vcf test.vcf`
and the error message is 
`Error: wrong number of fields in INFO/PG at chr6:44095266, expected 6, found 10`

below is the INFO/PG in the vcf file
> chr6	44095266	.	T	C,*    .       .    AC=1,1;AF=0.056,0.056;AN=18;BaseQRankSum=-0.556;ClippingRankSum=0;DP=121;ExcessHet=4.8688;FS=196.232;InbreedingCoeff=0.2413;MQ=53.06;MQRankSum=0;****PG=0,16,36,19,38,41,16,35,38,36****;QD=13.53;ReadPosRankSum=-1.614;SOR=5.416

It could be solved by removing the PG tag `##INFO=<ID=PG`  in the header of vcf, but I guess it may not be a good solution, it there any good suggestion for this problem? 

Many thanks!

**Comment by pd3** [comment]
@zofieLin you can redefine the tag as `Number=.` and reheader
```
bcftools view -h file.vcf > hdr.txt
# edit hdr.txt, make PG tag Number=.
bcftools reheader -h hdr.txt -o fixed.vcf file.vcf
```

**Comment by pd3** [comment]
@ManuelMoradiellos please do not append to existing and closed issues, as such will be easily overlooked
