### ISSUE TITLE
bcftools plugin dlopen error messages are not communicated clearly to the users

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1135]
When a plugin fails to load, the following error message is displayed:
```
No functional bcftools plugins were found in
	BCFTOOLS_PLUGINS="xxx".

- Is the plugin path correct?

- Run "bcftools plugin -lv" for more detailed error output.

Could not load "xxx.so".
```
This often leads to difficulties in diagnosing the problem. For a start, I think it is wrong to request to use `bcftools plugin -lv` for more detailed error output. I think what was meant here was to use `bcftools plugin <name> -vv` which provides the true error.

I also don't understand why the following code is in vcfplugin.c:
```
    if ( args->verbose > 1 )
    {
        if ( !handle )
#ifdef _WIN32
            fprintf(stderr,"%s:\n\tLoadLibraryA   .. %lu\n", fname, GetLastError());
#else
            fprintf(stderr,"%s:\n\tdlopen   .. %s\n", fname, dlerror());
#endif
        else fprintf(stderr,"%s:\n\tplugin open   .. ok\n", fname);
    }
```
I think it would be more appropriate to display the error message all the time when the plugin fails to load, and not only when the level of verbosity is set to 2.

**Comment by pd3** [comment]
The messages should be more informative now.
