### ISSUE TITLE
Mpileup selecting reference despite variant present

### ISSUE THREAD

**Issue by havard78** [samtools/bcftools#1136]
I am running the following command after mapping with bowtie2 against a reference:

`bcftools mpileup -O v --skip-indels -Q 7 -d 10000000 -h 50 -o 10 -e 17 -a INFO/AD -f anno.fa infile.bam > outfile.vcf`

I the first part of the segment there are clearly two variants, as seen in IGV (pos 51 and 86) :
![igv_snapshot_1425](https://user-images.githubusercontent.com/57938148/71880001-a504ca80-312f-11ea-8b0f-e4b7943ac46a.png)

However, they are not reported by mpileup:

`MH_mGl215_rosa_gruppe	51	.	G	<*>	0	.	DP=228;AD=0,0;I16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;QS=0,0;MQ0F=0	PL	0,0,0`
`MH_mGl215_rosa_gruppe	86	.	C	<*>	0	.	DP=227;AD=0,0;I16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;QS=0,0;MQ0F=0	PL	0,0,0`

Despite that all reads in these positions are counted (same read depth in both mpileup output and IGV (228 and 227). 

I am not able to identify any explanation to why these should not be reported. Hope you can help!

Best regards,

Håvard

**Comment by pd3** [comment]
Most likely all reads were removed because of their flag or BQ.

**Comment by havard78** [comment]
All flags are 0 or 16. It does not appear to be due to BQ scores either, all BQ in these two positions are >7 (most are >22 and <32). Am I missing something? I'm attaching a few entries from the BAM file. Do you need anything else?

`4VCOS:03781:01351       0       MH_mGl215_rosa_gruppe   1       42      11S100M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATG CB@>???AAA?BB@BBCB?BAAA278>8>;5<>>7A@=69>C7755.//(/7788?===:=<==8=<=;;5;>?>D:;:3;:8808;><>;=<689:7888*8=8==;>>? AS:i:188
        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C14   YT:Z:UU
4VCOS:03968:01566       0       MH_mGl215_rosa_gruppe   1       42      11S100M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATG CB?BBBBBBB@AAABBBB@>?>C>BAC8??:?=>;???:;@@9@DD68818?@>??@@A<@?@?;<<=>><@@@?D8AA9@;>>;A;A>>;;;6;6607;<3=>;>@=>>> AS:i:187
        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C14   YT:Z:UU
4VCOS:04686:01825       0       MH_mGl215_rosa_gruppe   1       42      11S100M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATG BC?CBABBBB?BBA>>?A>AABD>BBB<AA<ABB@BBD>CBC=CBD9>>=BBB=>>???<@@AA:=<=;;5;?BBC:AA:>;==9=<@@B=@?;?::5:?B9AA=::79== AS:i:187
        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C14   YT:Z:UU
4VCOS:00887:01445       0       MH_mGl215_rosa_gruppe   1       44      11S103M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATGCTT      BC?BAABBBB>BB@@@@@<@@>?8999,:>5=A>;BBB=A??9???9??=BCAA>>=@@;>>?>499=;;7<AAAB:@@6959:4<6=>A<??;?=<8=>?6>A<::6:A>==<      AS:i:194        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C17   YT:Z:UU
4VCOS:01189:01522       0       MH_mGl215_rosa_gruppe   1       42      11S100M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTCGTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATG BB@D:::@:917>>>@A>9>@==5000)/)///50333(33912..'..(/99789:;;288991765256=>;??8>?:>9>=5;4;==:>>9>8918=>6==8==188= AS:i:178
        XN:i:0  XM:i:4  XO:i:0  XG:i:0  NM:i:4  MD:Z:19T0C29G34C14      YT:Z:UU
4VCOS:01194:01806       0       MH_mGl215_rosa_gruppe   1       44      11S298M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATGCTTCCAGAGACTGGACCAGCAAGCATCCCGGACGACATAACGGAGAGACACATCCTAAAACAAGAGACCTCGTCATACAACCTAGAGGTCTCCGAATCAGGAAGTGGCATTCTTGTTTGTTTCCCTGGGGCACCAGGCTCACGGATCGGTGCACACTACAGATGGAATGCGAACCAGACGGGGCTGGAGTTCGACCAG   AB?@??A???=@@AAAB@;9::9,9<<3;>6?@A?BBC>CCC>A@B:>>:ABB@@@@AA:=89939///69==BDD9@@:=:881718881886866-56<5>>=BB<=<<==8<8=>>===>>;>B=>>>B1889:::/:4:>=>>>>>7;;<@@?@?A===8838?EE;AA;??>??6;;;;?@@@@C=@=@BA;;6;?==89<6///7171;<<8=;;7;A=BBA5>>D:BB86777+//97==39>?A??:>>::5:<=@@>>>>BA????1818@@@A=D<;;;ADDD;?@@<?66169//+/:   AS:i:584        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C212  YT:Z:UU
4VCOS:01233:01534       0       MH_mGl215_rosa_gruppe   1       44      11S298M *       0       0       AGGAGCTCTCCGTCGATGGCGAAAGCCCTTTCTAACAAACAAACAAACAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATGCTTCCAGAGACTGGACCAGCAAGCATCCCGGACGACATAACGGAGAGACACATCCTAAAACAAGAGACCTCGTCATACAACCTAGAGGTCTCCGAATCAGGAAGTGGCATTCTTGTTTGTTTCCCTGGGGCACCAGGCTCACGGATCGGTGCACACTACAGATGGAATGCGAACCAGACGGGGCTGGAGTTCGACCAG   BB?BBCBAAA@BBBB@@@=>=<=889929A;BB@;BCD=DAA;ABB:??=BB@====@A:=>>>:=:;;=:=ABCB:?@7;7:A=B7;;@=AA=A==9=>?8??=AA=A>>=<8<:::9==<<=:>?::;;@=AA>??D7>:=@@??@@@7:;=@@>>>AAA===7;;HE5BB:>=?=<8<:;;>@@BAA:>:=A?<<8;=::5;:8==<=5:6;>>;???;=>9989-8=C:BB:AAAA588A=;;7;;BAAA>H?;;7;===BD??>CAAABB<><>>>>?=E====?AAA5A<<8<8718>::6;?   AS:i:584        XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:50G34C212  YT:Z:UU
4VCOS:04675:06368       0       MH_mGl215_rosa_gruppe   1       41      11S10M1I27M1I64M        *       0       0       AGGAGCTCTCCGTCGATGGCGAAAAGCCCTTTCTAACAAACAAACAAACAAATCTATATCAATACAAGATGAACACAAACAAGGCAACCGCAACTTACTTGAAATCCATTATGC      BC>A;;;@>=7=?885:9388777+333(3;19991333(39>3;;;3777(7788787;:6//..(./335.55556/6759(./(/(//706:6:993688///(/7(/.56      AS:i:175        XN:i:0  XM:i:2  XO:i:2  XG:i:2  NM:i:4  MD:Z:50G34C15   YT:Z:UU
`

**Comment by havard78** [comment]
Can it be because all reads are in forward direction in this region? (there are no reads with the 16 flag in this part of the segment)

**Comment by pd3** [comment]
Hmm, I don't think that is the problem. Any chance you could provide this as a small bam with a full header for testing, including the reference sequence?

**Comment by pd3** [comment]
Thank you for the test case (provided offline). The problem is in BAQ realignment. There are multiple indels outside the IGV screenshot where the BAQ algorithm thinkgs realignment makes more sense than keeping the SNPs. If you disable BAQ with the `-B` option, the SNPs will be called.
