### ISSUE TITLE
question regarding --ignore-homref in bcftools roh

### ISSUE THREAD

**Issue by duartemolha** [samtools/bcftools#1137]
Hi. I am confused about this option on bcftools roh

the inclusion of this parameter (--ignore-homref) leads me to the understanding that if I do not include it bcftools orh command, it will consider homozygotic reference SNPS on my input VCF file for ROH calculation.

However, as homozygotic reference SNPS are not a biallelic site they are ignored whether you use this or not. 

Since my design is targeting common snps I would very much like BCFtools to include the homozygotic snps in the analysis but it does not as they are skipped by default as non-biallelic, and this argument changes nothing to the behavior of the program.

Can you please clarity?

Many thanks

**Comment by duartemolha** [comment]
Just as a addendum ... to test how the ROH would be if the homref positions had been considered , I modified my VCF file and converted my homref positions to homalt and sure enough the previously ignored homref snps (skipped because they where not biallelic) , were then considered on the report output

**Comment by duartemolha** [comment]
I have looked into this a bit more closely and I beleive it if failing because BCFTOOLS is interpreting a  
VCF line where the alt_allele field is missing "." and skipping it 

Take for example this line:

`chr1    494542  .       G       .       1.9004e-15      .       DP=53;DPB=53;EPPR=3.37904;GTI=0;MQMR=56.7358;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=1806;RO=53;RPPR=3.05127      GT:DP:AD:RO:QR:AO:QA:GL   0/0:53:53:53:1806:.:.:0`

This is a perfectly valid entry of a homref position
The 5th column has a "." as on that position there is only the ref allele found. 

but bcftools skips this line.
If we replace the . with another base, or even the same base as ref it works

**Comment by pd3** [comment]
That's correct. The program discards mono-allelic sites and the option only considers ref homs when alternate allele is present. The reason for that is that we can have allele frequency different from 1 for polymorphic sites only.

**Comment by duartemolha** [comment]
I am sorry, but I don't understand. The vcf hom-ref entries I am including on my vcf file are of polymorphic sites... in fact of common polymorphic sites.

for 1/1 sites (hom-alt) in that position is as informative as the 0/0 sites and it might as well be monoallelic in the sense that there might not be a single case of a read containing the reference allele but you nevertheless consider them.

What am I missing?

**Comment by pd3** [comment]
Maybe I don't understand what you mean. In the example you gave above, the site may as well be polymorphic in the population, but the program does not know about it, unless the information can be learned from the VCF. Are you providing a separate file with population allele frequencies?

**Comment by duartemolha** [comment]
I am sorry if I am not explaining myself clearly enough.

Let me try to expand a little.

My panel is targeting very common SNPS (with average heterozygosity approaching 0.5) and I am force-genotyping these common SNPs I know I have captured in my panel. Those SNPS might (and many times are) homozygotic to the reference allele (and only contain reads with the reference allele) on many samples. For snps with an average heterozygosity approaching 0.5, he majority of individuals are heterozygous, but the rest are equally likely to be homozygous reference or homogeneous alt.  So we include them on our VCF as lines. Those lines according to VCF specifications should have on the alt allele column the "." as a missing value (since we see no reads containing the alt allele).

What I don't understand about your point is that you say a monoallelic sites are discarded...but that is clearly not the case since you do consider a hom-alt (that might not have any reads with the reference alleles) for your program. Those SNPS, by your own definition, are monoallelic (they only have the alt-allele present).

All I am saying is that, for the common SNPS I am considering, a hom-alt SNPs (containing only alternative allele reads) is as informative for detection of runs of homozygosity as are the hom-ref ones.

I know that the program does not know about population frequencies (and no... I am not providing a file with the population allele frequencies), but as is the case for the hom-alt ones, you are accepting that their frequency on the population is what has been given in the  command line with the argument --AF-dflt 0.4 

So all I am saying is this value applies to your hom-alt as much as it does to your hom-ref , if the SNPs I have genotyped and included on the VCF file are known common snps in your population.

Does this make it any clearer?

Many thanks

Duarte

**Comment by pd3** [comment]
Sorry for the inaccuracy, when I said mono-allelic I meant reference-only sites, with no alternate allele present. The vast majority of these are not polymorphic, therefore the program skips them as uninformative. I understand your case is different. There are two options: either another switch is added to indicate that these should be considered as well (something like `--keep-ref-only-sites`) or you can add a dummy ALT allele in the VCF so that these sites will not be skipped.

**Comment by duartemolha** [comment]
This second option is what I have done as a temporary fix... I dont know if you would have enough people interested in doing so to merit adding a new switch.

You probably know your community of users needs better than I do :)

I just wanted to understand the behavior and especially I believe the report output should be changed as these lines with reference only bases are being reported as filtered out as "non-bialelic" and that is clearly not the case. Maybe a new category should be added for filtration of these entries?

Thank you for your help

**Comment by duartemolha** [comment]
As an additional point... what happens in a multisample VCF where the genotypes are like this:

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NA00001 NA00002
20 14370 rs6054257 G A 29 PASS NS=3;DP=14;AF=0.5;DB;H2 GT:GQ:DP:AD:HQ 0/0:48:50:50,0:51,51 1/1:48:50:0,50:51,51

as you can see in this line the first sample is 100% ref allele but your bcftools roh your consider it  because the alt-allele column is filed

But it this had been two separate input vcf files

vcf1 for sample NA00001 : 
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NA00001 
20 14370 rs6054257 G . 29 PASS NS=3;DP=14;AF=0.5;DB;H2 GT:GQ:DP:AD:HQ 0/0:48:50:50:51,51

vcf2 for sample NA00002 : 
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NA00002
20 14370 rs6054257 G A 29 PASS NS=3;DP=14;AF=0.5;DB;H2 GT:GQ:DP:AD:HQ 1/1:48:50:0,50:51,51

The first VCF would have discarded the entry even though there are absolutely no difference between the multivcf and the single sample vcf. Surely this is not a good behaviour.

**Comment by pd3** [comment]
I added a new `--include-noalt` option to do what you want. However, the default remains the same, because that's the desired behavior when working with WGS.

**Comment by duartemolha** [comment]
Many Thanks 

That is great!
