### ISSUE TITLE
bcftools merge fails with too many alt alleles

### ISSUE THREAD

**Issue by fminneci** [samtools/bcftools#1138]
I am trying to merge a large number of VCF files using `bcftools merge`, and I get an error that may be related to a previously reported issue in HTSlib/bcftools when dealing with too many alternate alleles at an individual location.

My task is to merge 80 files with ~ 1,000 samples each, for a total of ~ 80,000 samples, but unfortunately I cannot share the files here for a test case due to confidentiality (it is a Genomics England project).

When I do that, I encounter a problem that might be the same one reported in #929 :
 * If I use bcftools 1.9 for my task, I get the exact "Segmentation fault" error reported in that issue page (at a location with a very large number of alt alleles)
 * If I then use [the suggestion found towards the bottom of that page](https://github.com/samtools/bcftools/issues/929#issuecomment-447414168) (using `bcftools annotate -x FORMAT/PL` beforehand) everything works perfectly, but obviously I lose the FORMAT/PL field
 * Finally, if I use any recent version of bcftools (1.10, 1.10.1, 1.10.2), which presumably implement [the solution at the very bottom of that issue page](https://github.com/samtools/bcftools/issues/929#issuecomment-448922910), I get the following warning and then error:

`Warning: The row size is too big for FORMAT/PL at chr12:40203423, requires 26098651964 bytes, skipping.`
`bcftools: vcf.c:4058: bcf_update_format: Assertion 'nps && nps*line->n_sample==n' failed.`
`Aborted (core dumped)`

The warning and the error seem to always happen together, and it seems to me that the warning indicates that [the fix mentioned at the very bottom](https://github.com/samtools/bcftools/issues/929#issuecomment-448922910) of #929 is applied, but then a later check fails.

Quick inspection of line 4058 of htslib's `vcf.c` seems to suggest that in this case the number of fields is not necessarily a multiple of the number of samples any more.

Thank you very much for any help with this.

**Comment by pd3** [comment]
Could you please recompile with this added just before the line vcf.c:4058 to verify which of the fields fails?
```
if ( !(nps && nps*line->n_sample==n) )
    fprintf(stderr,"%s:%d   .. n=%d  n_smpl=%d  key=%s\n", bcf_seqname(hdr,line),(int)line->pos+1,n,line->n_sample,key);
```

**Comment by fminneci** [comment]
Thanks a lot for your help and suggestion - here is the error message printed out in that case:

    Warning: The row size is too big for FORMAT/PL at chr12:40203423, requires 26098651964 bytes, skipping.
    chr12:40203432   .. n=1542569024  n_smpl=78971  nals=384 key=PL
    bcftools: vcf.c:4060: bcf_update_format: Assertion `nps && nps*line->n_sample==n' failed.
    Aborted (core dumped)

Note that 78971 is exactly the total number of samples I have.  
The coordinate seems to have progressed a little bit between the warning and the error (by 9bp).. please let me know if you think this means that the error and the "row size too big" warning may be unrelated (although the "key" value seems to be the same one).

**Comment by pd3** [comment]
I think these are unrelated, thanks Federico. To debug this further, can you please contact me offline, my email is on the profile page.

**Comment by pd3** [comment]
This is now fixed, thank you for the testing data.
