### ISSUE TITLE
confusing behavior for bcftools query and filter with arithmetic operators 

### ISSUE THREAD

**Issue by hassanfa** [samtools/bcftools#1139]
I am trying to use arithmetic operators to filter some specific sites in VCF either based on their AD or AF. This is to compare if two individuals have different AF ratio at a specific AF values.

Example: AF value for individual 1 `0.061` and individual 2 `0.011`
```
bcftools view -f PASS samples.vcf.gz \
    | bcftools query -i \
      '(FMT/AF[0] == 0.061 && FMT/AF[1] == 0.011)' \
      -f '%POS[ %SAMPLE:%AF %AD]\n'
```

The output is expected, and prints the following values:
```
12345 sample_1:0.061 107,7 sample_2:0.011 89,1
```

But when I try to to filter based on their sum of AD for alt allele (third criteria), nothing prints:

```
bcftools view -f PASS samples.vcf.gz \
    | bcftools query -i \
      '(FMT/AF[0] == 0.061 && FMT/AF[1] == 0.011)  && (FMT/AD[0:1]+FMT/AD[1:1])>7' \
      -f '%POS[ %SAMPLE:%AF %AD]\n'
```

Same behavior on adding a filter for AF ratio: `(FMT/AF / FMT/AF) > 2`

I created an example VCF file to demonstrate:

example.vcf
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=1,Type=Float,Description="Allele fraction of the event in the tumor">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1	sample_2
1	12345	.	G	A	28.34	PASS	.	GT:AD:AF	0/1:107,7:0.061	0/0:89,1:0.011
1	12346	.	G	C	28.34	PASS	.	GT:AD:AF	0/1:107,7:0.061	0/0:85,4:0.045
```

The goal is to add a filter to sites that fail the condition below holds:
- `sum of alternative alleles in all samples greater than 10`

Have I misunderstood arithmetic operations and they don't apply across samples? I guess this is because operators apply to sites within _each_ sample only?

Edit:  fyi, I have a solution for this and it is to apply `sum` function before comparing AF, AD, etc. Example:

`bcftools filter -i 'sum(FMT/AF[0])>sum(FMT/AF[1])*4' -s 'af_ratio' -m '+' example.vcf` works, but 
`bcftools filter -i 'FMT/AF[0]> (FMT/AF[1]*4)' -s 'af_ratio' -m '+' example.vcf` does not.

**Comment by pd3** [comment]
You are correct, when the arithmetic operators are used on FORMAT tags, they only work within sample, not across samples. In order to remedy this, we'd need to be able to distinguish between two possible use cases similarly to the logic operators (e.g. `&&` vs `&`).

A quick solution would be to use INFO/AD instead.

**Comment by hassanfa** [comment]
Thank you for quick feedback.

Is applying `sum` to avoid within/across sample filter an intended behavior (example above)? If that's by design, it would be great to use it reliably in production.

**Comment by pd3** [comment]
Using `sum()` will force the sample array into a scalar, so yes, that should work
```
bcftools view -H -i '(sum(AD[0:1])+sum(AD[1:1]))==8' test.vcf
```
However, for greater flexibility you might consider using the perl filtering capabilities, see an example here https://github.com/samtools/bcftools/blob/develop/misc/demo-flt.pl

That or the INFO/AD option.

**Comment by hassanfa** [comment]
That clears things up. Thanks.
