### ISSUE TITLE
bcftools merge not producing expected result

### ISSUE THREAD

**Issue by seanstankowski** [samtools/bcftools#1140]
Hi there!

Im trying to merge two sets of calls that include different sets of individuals but that were generated using the same sequencing method, genome and pipeline. Specially, have two vcf.gz files, let's say 1_vcf.gz and 2_vcf.gz. The first file contains calls for 81 my SNPs from 60 (38G file size) individuals and the second contains 73 my SNPs from 48 individuals (35G file size). Obviously not all of these sites will be variable in both sets (when I bcftools isec, it says there are files, there are 49 million snps in common), but id like to assign the ref allele to sites that were present in either one of the files, so that I have genotypes for all 108 individuals at all of the unique positions present across the 2 vcfs. 

My understanding is that I can do this with bcf tools merge using the flag --missing-to-ref. 

So I am am running this command with the goal of producing a merged vcf, that expect to be larger than either of the starting vcfs, containing 108 individuals and  at least 81 my SNPs, but probably many more.

bcftools merge 1_vcf.gz 2_vcf.gz --threads 16 --missing-to-ref --merge snps -O b -o Full_merged.vcf_new.gz

This command produces a vcf with 108 individuals as expected, but only 17G, so less than half the size of the larger of the 2 original files, and with only 22 million SNPs. when I bcftools stats this file, I get the warning:

No BGZF EOF marker; file 'Full_merged.vcf_new.gz' may be truncated

I don't get this for either of my original files. So i'm wondering if the merge is just dying for some reason, or am I miss-interpreting how this toll works. Oddly, when i remove the --missing-to-ref flag, I get roughly the same size file (I'm expecting 49 million based on isec), so I'm really puzzled about what is going on. 

Any suggestions and information about this would be much appreciated! Happy to provide any additional info that might be useful!

Thanks in advance

Sean

**Comment by pd3** [comment]
What version of bcftools are you running? The warning suggests that the file is probably truncated, therefore the merging probably did not have a happy ending. Debugging problems of this size is tricky. I am afraid that from your description it is not possible to know if something is killing your job or if it is a bug in bcftools. Try to run in gdb maybe?

**Comment by seanstankowski** [comment]
Thanks for your response. I was using 1.9-41. Happy to report that an update to 1.10.2 solved this issue.
