### ISSUE TITLE
bcftools mpileup 1.10.2 no longer has "dummy VCF creation" functionality

### ISSUE THREAD

**Issue by ahstram** [samtools/bcftools#1141]
Hi there,

I'm not sure if this was intentional, but bcftools version 1.9 had a nice ability to create a "dummy" empty VCF, which I could do with this command:

`bcftools mpileup - --no-reference <<< ""`

bcftools would then create a "dummy" VCF file with no records, but sufficient header information such that I could then pass this empty VCF file to a command like "bcftools concat" without running into an error about a malformed VCF header, which will happen with an empty file.

The significance of creating a "dummy" VCF is to act as a placeholder for analyses that did not produce results (no variants called), but later steps in our pipelines still expect a well-formed VCF file to operate on (for steps such as "bcftools concat").

It seems that with bcftools 1.10.2, running the command `bcftools mpileup - --no-reference <<< ""` now results in an error message:

> [mpileup] fail to read the header of -

Would it be possible to bring back the "dummy VCF creation" functionality which existed in bcftools v1.9 by running the command `bcftools mpileup - --no-reference <<< ""`?

Thank you,

Alex

**Comment by jmarshall** [comment]
This error is due to the feature whereby empty files are no longer considered valid SAM files. You can do what you want by giving it a non-empty dummy input file instead:

    bcftools mpileup --no-reference - <<< $'@HD\t'

**Comment by ahstram** [comment]
Great, thank you!

**Comment by trutane** [comment]
> This error is due to the feature whereby empty files are no longer considered valid SAM files. You can do what you want by giving it a non-empty dummy input file instead:
> 
> ```
> bcftools mpileup --no-reference - <<< $'@HD\t'
> ```

Seems like a risky change, leading to backward incompatibility and users not being willing or able to upgrade from v1.9. I'm wondering what prompted the "empty files no longer considered valid" change? Are there are problems with a "do nothing when given nothing" policy when processing SAM files?

**Comment by jmarshall** [comment]
If you read the release notes, consider the information content of an empty file, and think about it for more than 10 seconds — I think you'll realise this is a sensible change and the backward incompatibility is “samtools/bcftools no longer masks earlier failures”.
