### ISSUE TITLE
command line help for bcftools roh --AF-file

### ISSUE THREAD

**Issue by mzaki-jp** [samtools/bcftools#1142]
In commit 96b9067d1d028295e8cbf0560235c4b215f6f71f,
the command line help for bcftools roh --AF-file changed from
CHR\\tPOS\\tREF,ALT\\tAF
to
CHR\\tPOS\\tREF\\tALT\\tAF
But I think it was wrong. The code (read_AF() in vcfroh.c) expects the former (REF,ALT) format.

**Comment by pd3** [comment]
This is now fixed, thank you
