### ISSUE TITLE
multi-fasta from multiple sample vcf

### ISSUE THREAD

**Issue by marcotoffoli** [samtools/bcftools#1143]
Hi, 
I am looking for  away to create a multi-fasta from a multiple sample vcf file. 
To give some more details, I am sequencing a gene using nanopore technology and my final result is a big vcf file with hundreds of samples and all mutations called and phased within the gene of interest. 

I would like to do haplotype analysis, but to do that I first need to convert the vcf into a multi-fasta. 
currently, I use the bcftools consensus command and I convert each sample and haplotype separately. I then merge all the fasta into a big fasta file using the TAIL command. this pipeline however is long and I was wondering if there is any easy way to go from multi-vcf to multi-fasta with bcftools. 

Kind regards, 
Marco

**Comment by pd3** [comment]
I don't know of a better way, what you are describing sounds sensible enough. Not sure why you need `tail`, simple concatenation should suffice
````
bcftools consensus ... > out.fa
bcftools consensus ... >> out.fa
bcftools consensus ... >> out.fa
````
