### ISSUE TITLE
bcftools roh RG emit negative length

### ISSUE THREAD

**Issue by mzaki-jp** [samtools/bcftools#1144]
I noticed, in rare cases, that bcftools roh emit a negative length for RG.

Cause:
When RG is composed of a single variant, `smpl->rg.end` is never updated, so that the value from the previous RG is used for length calculation, giving negative length.

Fix:
`smpl->rg.end` as well as `smpl->rg.beg` should be initialized at https://github.com/samtools/bcftools/blob/develop/vcfroh.c#L550

Why "single variant RG" ? I have no idea. It seems related to sliding HMM mechanism with --buffer-size, because such extremely short RG is reported only when some values specified to --buffer-size.

**Comment by pd3** [comment]
This is now fixed, thank you. A reproducible test case would be helpful to debug this further and check whether the HMM has gone insane.
