### ISSUE TITLE
Behaviour of bcftools roh and regions file unclear 

### ISSUE THREAD

**Issue by dminkley** [samtools/bcftools#1145]
When using bcftools roh and a regions file that excludes large internal chromosome pieces, the program appears to just use the variants on either side of the excluded region to create one very large ROH that spans the entire region.  I can understand why this behaviour would occur, but I think it's important that the documentation warn of this fact.  My initial interpretation was that ROHs would not be found in the excluded region - the actual behaviour was to find massive ROHs that inappropriately spanned the entire excluded region in a number of individuals.

Is there a way to achieve my desired behaviour?  IE Identify ROHs that only incorporate bases from the included regions?

**Comment by pd3** [comment]
The HMM model does not see the sites from the excluded region, for the model it is the same as if the sites were not present in the VCF at all. You'll have to do some post-processing, e.g. subtract the excluded regions using bedtools. In this example regions in A not present in B are clipped:
````
bedtools subtract -a a.bed -b b.bed
````
