### ISSUE TITLE
[W::vcf_parse] Extreme INFO/MPOS value encountered and set to missing at chr1:17082839

### ISSUE THREAD

**Issue by jeongmeani** [samtools/bcftools#1148]
Hi, Happy new year!

i ran bcftools to parse tumor sample of somatic vcf.
but it returned warning message like below

> [W::vcf_parse] Extreme INFO/MPOS value encountered and set to missing at chr1:17082839

my code is
`bcftools view -s TNB_17_tumor TNB_17.mutect2.filtered.vcf.gz > TNB_17.mutect.tumor.vcf`

i have a look input vcf and out vcf file but i don't know what is difference among them
and even at chr1:17082839 the line is same!

what is the problem?

Thanks!

**Comment by pd3** [comment]
Can you show the value of INFO/MPOS at that position before and after? Also, important, what version of htslib+bcftools are you running? Make sure to test with 1.10.2 or the latest github version.

**Comment by jeongmeani** [comment]
OK!

before

> chr1    165378737       .       C       T       .       PASS    CONTQ=93;DP=99;ECNT=1;GERMQ=93;MBQ=38,35;MFRL=228,228;MMQ=60,60;MPOS=-2147483648;NALOD=1.44;NLOD=7.51;POPAF=6.00;SEQQ=18;STRANDQ=17;TLOD=7.18 GT:AD:AF:DP:F1R2:F2R1:SB        0/0:26,0:0.036:26:10,0:15,0:22,4,0,0    0/1:57,4:0.083:61:25,3:29,0:44,13,3,1

after

> chr1    165378737       .       C       T       .       PASS    CONTQ=93;DP=99;ECNT=1;GERMQ=93;MBQ=38,35;MFRL=228,228;MMQ=60,60;MPOS=.;NALOD=1.44;NLOD=7.51;POPAF=6;SEQQ=18;STRANDQ=17;TLOD=7.18;AC=1;AN=2    GT:AD:AF:DP:F1R2:F2R1:SB        0/1:57,4:0.083:61:25,3:29,0:44,13,3,1

i think this is perfectly match each other.
and my version is 1.10.2.

**Comment by pd3** [comment]
The error message and your data are consistent and quite clear: `MPOS=-2147483648` was out of bounds and is replaced by `MPOS=.`

**Comment by jkbonfield** [comment]
Note this is caused by a bug in Mutect2.  More information and background here:

https://gatkforums.broadinstitute.org/gatk/discussion/24398/mpos-is-2147483648-in-mutect2-gatk-4-1-3-0

https://github.com/broadinstitute/gatk/issues/5492

The change in bcftools / htslib is that with extra validation it is not spotted these illegal values and issuing a warning.  Older versions just truncated or wrapped around the data silently.

**Comment by jeongmeani** [comment]
OK!
i got it.
Thank you for your answers.

happy new year!

Jeongmin.
