### ISSUE TITLE
Under what conditions does bcftools consensus convert a position to lower case?

### ISSUE THREAD

**Issue by gwct** [samtools/bcftools#1150]
Hello,

I'm wondering if you can explain why a position would be converted to lower case by bcftools consensus.

The command I ran:
```
bcftools consensus -f 11-all-masked.fa -o 11-all-masked-consensus.fa -c 11-all-masked-consensus.chain 11-all-filtered-no-NON_REF.vcf.gz
```

Region of interest from input file (which is softmasked -- maybe that's relevant):

```
>11:3220291-3220311
CCACAGAGACTAAGCTTTGGA
```

Region of interest from output file:

```
>11:3220291-3220311
CCACAGAGACgAAGCTTTGGA
```

Variant from VCF file:

```
11      3220301 .       T       G       77.6    PASS    AC=1;AF=0.5;AN=2;BaseQRankSum=-0.126;DP=7;ExcessHet=3.0103;FS=3.979;MLEAC=1;MLEAF=0.5;MQ=58.32;MQRankSum=-0.524;QD=15.52;ReadPosRankSum=-0.842;SOR=2.833        GT:AD:DP:GQ:PL  0/1:2,3:5:66:85,0,66
```

In this example, the G variant at that position has been converted to a lower case g. Is there some threshold of DP or AD that bcftools is using to decide this? If so, are these thresholds changeable? Hopefully I didn't miss it, but I couldn't find anything related to this in the documentation (https://samtools.github.io/bcftools/howtos/consensus-sequence.html, http://samtools.github.io/bcftools/bcftools.html#consensus).

Thanks!

**Comment by pd3** [comment]
The program uses the case of the first base in fasta sequence. This was written with the assumption that the case is the same for the whole sequence, softmasking was not considered.

**Comment by gwct** [comment]
Ah, mystery solved! Thanks.
Would you be open to a pull request if I added an option to let the user choose the case of the output variants? I think this is critical for softmasked sequences so all the variants don't get filtered out later on.

**Comment by pd3** [comment]
Rather than choosing the case by a command line option, ideally the program would decide on the case automatically based on the case of the fasta reference at each position. This should be add and yes, I would accept such a pull request if also tests are included. Thank you for the offer.

**Comment by pd3** [comment]
The case is now decided locally based on the first character of REF in the fasta sequence. Please try it out and let me know if you encounter any problems.
