### ISSUE TITLE
bcftools 1.9: Silent failure with overlapping intervals. 

### ISSUE THREAD

**Issue by MurphyDavid** [samtools/bcftools#1151]
I hit this error while trying to create a merged vcf file from 5 source vcf.gz files and using a region file. 

The output was getting truncated in the middle of chromosme 1. 

The last entry in the output was at position chr1:108852355. 

The command used was 

/path/bcftools/bcftools merge -l releaselist.txt -R forProcessing.txt -O v -o forProcessing.vcf  --force-samples

The region file was based on the peddy grch38 sites plus and minus 1. After some testing the problem replicated with a regions file starting with these 4 lines. 

```
 chr1	108851941	108851943
 chr1	108852353	108852355
 chr1	108852355	108852357
 chr1	108918718	108918720

```
The program returns an exit status of 0

 echo $?
0

I was prepared to check for duplicates and out of order entries but silent failure with success exit status seems dangerous. 

Changing the first 108852355 to 108852354 allows it to run through. 

/bcftools/bcftools --version
bcftools 1.9-114-gd9f1262
Using htslib 1.9-130-gf5a6a87

**Comment by pd3** [comment]
Can you try with the latest version please and come back if the problem persists?

**Comment by MurphyDavid** [comment]
My bad, it seems to work correctly in bcftools-1.10.2
