### ISSUE TITLE
bcftools gtcheck: Unexpected behavior for multiallelics and input file order

### ISSUE THREAD

**Issue by jligencove** [samtools/bcftools#1152]
Hi, 

Running into unexpected behavior while using `bcftools gtcheck` on files with multiallelic sites. In particular, 

1. When running `gtcheck` on a sample whose multiallelics have been normed against the same sample's unnormed calls via, for example,  `bcftools gtcheck -G 1 -g normed.vcf.gz unnormed.vcf.gz`, `gtcheck` reports non-zero discordant calls, even though these are the same genotypes (which I expect should result in no discordance being reported): 

To take a minimal example, taking a VCF with an un-normed multiallelic: 
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1	s2	s3	s4	s5	s6
11	33	v9	C	A,T	.	PASS	.	GT	0|2	2|0	0|1	2|0	1|1	0|0
```
and norming it using `bcftools norm` to obtain 
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1	s2	s3	s4	s5	s6
11	33	v9	C	A	.	PASS	.	GT	0|0	0|0	0|1	0|0	1|1	0|0
11	33	v9	C	T	.	PASS	.	GT	0|1	1|0	0|0	1|0	0|0	0|0
```
and then running `bcftools gtcheck -G 1 -g normed.vcf.gz unnormed.vcf.gz` yields 
```
# [1]CN	[2]Discordance with s1 (total)	[3]Discordance (avg score per site)	[4]Number of sites compared	[5]Sample	[6]Sample ID
CN	1.000000e+00	1.000000e+00	1	s1	0
...
```
which seems incorrect, as these are the same genotypes from the same samples; the discordance rate I expect would be zero. 

2. However, if one runs `bcftools gtcheck -G 1 -g unnormed.vcf.gz normed.vcf.gz` (the same command as in 1.) but passing the unnormed vcf into the `-g` flag instead of the normed vcf), `gtcheck` yields 
```
# [1]CN	[2]Discordance with s1 (total)	[3]Discordance (avg score per site)	[4]Number of sites compared	[5]Sample	[6]Sample ID
CN	0.000000e+00	0.000000e+00	0	s1	0
```
which indicates to me that the multiallelic sites were skipped. 

Is this behavior intended? Certainly the dependence of whether or not multiallelics are considered on which VCF is passed to the `-g` flag is unintuitive, and the behavior of `gtcheck` when they _are_ considered seems incorrect.

**Comment by pd3** [comment]
The program is not smart enough in this respect. It attempts to pair matching records from the genotype and the query file one pair at a time. In your case it happens to use
````
    REF ALT  GT
    C   A    C|C
````
and
````
    C   A,T  C|T
````
which is a genotype mismatch. If you normalize both files, you should see the records paired correctly.

I hope this helps.

**Comment by jligencove** [comment]
Thanks for the response. That part makes sense -- however, this doesn't explain the behavior I outlined in (2), whereby passing in the same files except with which file is passed with the `-g` flag yields a different result and skips the multiallelic site.

**Comment by pd3** [comment]
This is an artefact of the internal implementation and while not exactly a bug, definitely not a desired feature.  The explanation is a bit technical but in short, the program for convenience skips sites where the ALT alleles in the -g file are not present in the query file. As the program is intended for determining the identity of samples, skipping a few sites is not an issue. However, if this is a problem, one can avoid multiallelic sites by normalizing the files before running gtcheck and things should start working.
