### ISSUE TITLE
Inaccuarate GT calls ?bug 

### ISSUE THREAD

**Issue by oalavijeh** [samtools/bcftools#1157]
Dear bcftools team, 

I have been trying to extract heterozygote calls from a region of a bcf file and multiple iterationsof code are failing, giving me all the genotypes instead of filtering. I have run:

bcftools view -g het my.bcf -r ch10:x-y > output
bcftools view -r chr10:x-y | bcftools query -i 'GT="het"' -f '%LINE' > output 
bcftools query -r chr1-:x-y -i 'GT="1/0" | "0|1"' -f %LINE' my.bcf > out 

On all these outputs when I run:
 bcfttols query -f '[%GT\t%SAMPLE\n]' output
I get a series of 0/0, 0/1, 1/0 calls.

Am I doing something wrong here? 

Many thanks

**Comment by pd3** [comment]
I am guessing this is a VCF with multiple samples? The logic of the `-i` filtering is to include any site with at least one sample passing the expression. Try
````
bcftools view -e 'GT!="het"' | bcftools query -f'[%CHROM %POS %GT %SAMPLE\n]'
````
or
````
bcftools query -i'GT="het"' -f'[%CHROM %POS %GT %SAMPLE\n]'
````
For more pointers see http://samtools.github.io/bcftools/howtos/filtering.html

**Comment by oalavijeh** [comment]
Thanks!
