### ISSUE TITLE
query format string options %INFO and %FORMAT not working

### ISSUE THREAD

**Issue by coffee-and-genomics** [samtools/bcftools#1158]
When using `bcftools query` and specifying the format string with `-f`, the [documentation](http://samtools.github.io/bcftools/bcftools.html#query) says:

> #### Format:
>
> ```
> [...]
> %FORMAT         Prints all FORMAT fields or a subset of samples with -s or -S
> [...]
> %INFO           Prints the whole INFO column
> [...]
> ```

However, when I try to implement these options in the format string, they both give errors where it seems like their functionality does not work, with or without inclusion in brackets:

`%INFO`:

```
> bcftools query \
> --print-header \
> --include 'TYPE="snp"' \
> -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO\n' \
> test.vcf.gz
Could not parse format string: %CHROM\t%POS\t%REF\t%ALT\t%INFO\n
```

`%FORMAT`:

```
> bcftools query \
> --print-header \
> --include 'TYPE="snp"' \
> -f '%CHROM\t%POS\t%REF\t%ALT\t%FORMAT\n' \
> test.vcf.gz
# [1]CHROM      [2]POS  [3]REF  [4]ALT  [5]FORMAT
Error: no such tag defined in the VCF header: INFO/FORMAT. FORMAT fields must be in square brackets, e.g. "[ FORMAT]"
```

`[%INFO]`:

```
> bcftools query \
> --print-header \
> --include 'TYPE="snp"' \
> -f '%CHROM\t%POS\t%REF\t%ALT[\t%INFO]\n' \
> test.vcf.gz
Could not parse format string: %CHROM\t%POS\t%REF\t%ALT[\t%INFO]\n
```

`[%FORMAT]`

```
> bcftools query \
> --print-header \
> --include 'TYPE="snp"' \
> -f '%CHROM\t%POS\t%REF\t%ALT[\t%FORMAT]\n' \
> test.vcf.gz
# [1]CHROM      [2]POS  [3]REF  [4]ALT  [5]NORMAL:FORMAT        [6]TUMOR:FORMAT
Error: no such tag defined in the VCF header: FORMAT/FORMAT
```

The VCF does have multiple `FORMAT` and `INFO` fields, so this seems like a bug:

![image-20200214110211452](https://user-images.githubusercontent.com/43548130/74551892-afc63280-4f19-11ea-9b77-4e18e6b1a22f.png)

![image-20200214110226089](https://user-images.githubusercontent.com/43548130/74551912-b785d700-4f19-11ea-9473-0b39d00d9e04.png)

![image-20200214110259328](https://user-images.githubusercontent.com/43548130/74551919-bf457b80-4f19-11ea-9e3f-26a648909ad9.png)

**Comment by pd3** [comment]
The option works for me alright, you should consider upgrading to a newer version of bcftools.
http://samtools.github.io/bcftools/howtos/install.html
