### ISSUE TITLE
Feat/support passing index files

### ISSUE THREAD

**Issue by blajoie** [samtools/bcftools#1160]
v1.10 brought about the new -X option (-X include customized index file), to samtools.
samtools/samtools#978

Is it possible to request for tabix/bcftools/etc?

Use case would be for passing in signed s3 urls into all of the various tools.

e.g.
```
tabix <signed_vcf_url> -X <signed_vcf_tbi_url> chr2
bcftools view <signed_vcf_url> -X <signed_vcf_tbi_url> chr2
samtools view <signed_bam_url> -X <signed_bam_bai_url> chr2
```

**Comment by pd3** [comment]
This is already possible in a different / better way, see https://github.com/samtools/bcftools/issues/984 for more.

**Comment by blajoie** [comment]
Not sure this is better, but thanks :)  Will meet the need for now.

**Comment by pd3** [comment]
It is better in the sense that the change happened in htslib and all programs that use htslib, including bcftools with its 20+ commands and 30+ plugins, can now use this feature just by recompiling, no changes to the programs required.
