### ISSUE TITLE
setGT query based on AD and DP

### ISSUE THREAD

**Issue by oleraj** [samtools/bcftools#1161]
Hi,

I'm trying to use setGT to set genotypes with allelic balance (AD/DP) < 0.2 to missing, however I'm getting results different from expected.  The problem is that genotypes are being set to missing even if they don't pass the filter.  

Here is what the original genotype looks like:
```
GT:AD:DP:GQ:PL	0/0:60,0:60:0:0,0,1630
```
My filter:
```
bcftools +setGT  - -- -t q -i 'GT!="RR" && ((FORMAT/AD / FORMAT/DP) < 0.2)' -n .
```
And the output:
```
GT:AD:DP:GQ:PL	./.:60,0:60:0:0,0,1630
```

It's true that the AD/DP value is zero (0/60) but I want to switch only non-ref variants, which is why I added the `GT!="RR"` part, but it seems that is being ignored.  Is my query constructed incorrectly or is this a bug?

I am also wondering if I am indicating the AD and DP portions correctly.  I assume I don't need to add indexes for AD and DP since setGT will iterate through each GT one by one, is that correct?

I'm using bcftools v.1.10.2.

Thanks,

Andrew

**Comment by pd3** [comment]
Can you test if replacing `&&` with `&` makes any difference? 

From the manual page:
````
    FMT/DP>10  & FMT/GQ>10 .. both conditions must be satisfied within one sample
    FMT/DP>10 && FMT/GQ>10 .. the conditions can be satisfied in different samples
```` 
and more examples here http://samtools.github.io/bcftools/howtos/filtering.html

**Comment by oleraj** [comment]
Thanks, that helps.  The GT isn't changed if I use `&` instead.  

It's still not clear to me when an index (array subscript) is needed for a FORMAT value in a query expression and when it's not needed as in this case apparently. Is there any sort of suggested rule of thumb?

**Comment by pd3** [comment]
The expressions work with scalar values or vectors, but not with matrices. A FORMAT field can span multiple samples and can have multiple values per sample, so the array subscripts are intended to create a vector or scalar slice. I am not sure what is happening at the AD/DP step exactly, it's possible that it's doing something unintended. Better to create a small toy example to make sure.
