### ISSUE TITLE
bcftools isec and compact gvcf

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#1162]
Hello,
Deepvariant uses a gvcf where it merges adjacent RefCall that are mostly similar. This seems to break bcftools isec, for example if vcf B does have the position

chromosome_1 17096815

but vcf A has
chromosome_1 17096810
chromosome_1 17096821
which implies that sites from 17096810 to 17096820 are present but merged, bcftools isec seems to belief that the position 17096815 is not present in A. 

am I missing something or do I need to rewrite the vcf A to "unpack" it? 

thank you!

**Comment by pd3** [comment]
The program only looks at POS and does not take into account REF or END unfortunately. However, there are multi-step workarounds, what do you need to do?

**Comment by aderzelle** [comment]
Thanks for your reply. Well, simple enough, I want to intersect individual sample vcf files to identify variants that are private to each sample. In my example, the position chromosome_1 17096815 is merged with neighbours in one vcf, called as a RefCall (0/0). And in another vcf it is not merged because there were some reads supporting an alternative allele, but ultimately the retained genotype is RefCall anyway. So that site shouldn't be output by bcftools isec.

I have a working "joint calling" approach but I would have liked to compare it with a "per sample" approach.

**Comment by pd3** [comment]
The `bcftools merge -g` command is able to spit the REF blocks producing a multi-sample VCF as a byproduct. Would that help?

**Comment by aderzelle** [comment]
yes, thanks!
