### ISSUE TITLE
[E::bcf_hdr_add_sample] Empty sample name: trailing spaces/tabs in the header line?

### ISSUE THREAD

**Issue by hyl317** [samtools/bcftools#1163]
I want to remove some samples from .vcf and I ran into the error as indicated in the title.
Below is the head of my .vcf file. I have chekced that all lines have the same number of fields (awk '{print NF}' file) so it seems to me there should not be any empty fields in the header. I have attached the the first 100 lines of my .vcf here.
[head.txt](https://github.com/samtools/bcftools/files/4240445/head.txt)

**Comment by pd3** [comment]
The sample names in the VCF file are all messed up, there are many redundant tab characters. Try to visualize the sample line e.g. by splitting by tabs
````
cat head.txt | grep ^#CH | awk  '{gsub("\t","\n",$0); print;}' | less
````
