### ISSUE TITLE
SnpGap failure to parse

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#1167]
Hello,

I am trying to use the following option with SnpGap but I am running into "failed to parse"

`bcftools filter -s + -g 10:indel,other
`
I guess it's not implemented in the 10.2 release?  Therefore I must compile the development version right? 

Also, will the feature works in the following case? 

`22      18211021        rs202228518     ACC      T      100     PASS
`

This feature has been now added and can be used for example like this:
````
# the default, these two commands are equivalent
bcftools filter -s + -g 2
bcftools filter -s + -g 2:indel

# filter SNPs close to indels, complex events (eg. T>AC)
bcftools filter -s + -g 2:indel,other
````

_Originally posted by @pd3 in https://github.com/samtools/bcftools/issues/1126#issuecomment-575361419_

**Comment by pd3** [comment]
Are you using an older version perhaps? Please try with the latest github checkout as described here http://samtools.github.io/bcftools/howtos/install.html
