### ISSUE TITLE
Does the --missing argument to bcftools consensus do anything?

### ISSUE THREAD

**Issue by terrycojones** [samtools/bcftools#1170]
I'm trying to obtain a consensus that has `-` characters at sites where nothing matches the reference (due to a VCF call that indicates a deletion from the reference). The `bcftools consensus` help text says "-M, --missing <char> output <char> instead of skipping the missing genotypes" which I thought might give me what I want, but when I use it (I tried it with various different characters, including ones that are not shell metacharacters, like `x`), I get no indication in the output that there was a deletion (apart from the fact that the consensus is shorter than the reference).

To give an example, the `REF` and `ALT` fields in my VCF file might look like `GTGCTTTTTAC G,<NON_REF>` (TAB replaced with space). Note that this is actually a gVCF file produced by gatk (see https://gatk.broadinstitute.org/hc/en-us/articles/360035531812), but I wouldn't think that makes any difference, since `bcftools` is correctly producing the `G` in the consensus (for the example above). I would like the consensus to have the `G` followed by 10 `-` characters.

Is that what `--missing` should be doing for me, or am I misunderstanding?  Thanks!

**Comment by pd3** [comment]
You are misunderstanding, that's not what the option is supposed to do, it's intended for samples with missing genotypes (GT=./.).  For what you need, I am thinking maybe if you modified the VCF and replaced deletions such as `REF=AAA ALT=A` with `REF=AAA ALT=A--`, the program might blindly replace the reference with dashes. I am not sure, you'll have to try it out. If it works, note that such VCF is not a valid VCF and programs may complain. An alternative is to replace with `ALT=ANN`, that should work and results in a valid VCF.

**Comment by terrycojones** [comment]
@pd3 Thanks a lot Petr, that makes sense and should be easy enough to fix as you suggest.

**Comment by terrycojones** [comment]
In case anyone else wants to do this, I ended up doing the following:

```sh
$ samtools depth -a file.bam | awk '$3 == 0 {printf "%s\t%d\t%d\n", $1, $2 - 1, $2}' > mask.bed
$ bcftools consensus --mask mask.bed .... > consensus.fasta
```

This also works if `mask.bed` ends up empty due to no uncovered sites.
