### ISSUE TITLE
Configure script needs to check options

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#1171]
(Fixes #1166)

Right now, the build instructions mention optional things like "--enable-libgsl" and "--enable-perl-filters".  The configure script does absolutely nothing with these bar adding the appropriate #define to config.h.  It may as well be a `make CPPFLAGS=-DENABLE_PERL_FILTERS`.

Consequentially if you enable them but they're not installed on the system, configure doesn't notice and the user then assumes it's set up and the build will work, which it may not.

IMO the correct behaviour for these options, as they're not enabled by default, is for configure to hard fail if the necessary header files or libraries are missing.

**Comment by pd3** [comment]
Both `--enable-libgsl` and `--enable-perl-filters` are doing more than adding defines to config.h https://github.com/samtools/bcftools/blob/develop/configure.ac#L198-L233, 
https://github.com/samtools/bcftools/blob/develop/configure.ac#L235-L244.

The first checks the presence of the headers and instructs to exit with an error if not found. For the latter, I don't know the autoconf magic well enough to create a check for the existence of perl.h and the corresponding libraries with setting PERL_CCOPTS and PERL_LIBS first. But I am  surprised this code https://github.com/samtools/bcftools/blob/develop/configure.ac#L236-L238 did not catch it.

The original issue (#1166) does not show what version of bcftools/htslib was used and where it was downloaded from and it does not show the output from configure.

**Comment by jkbonfield** [comment]
That test looks to just be running perl to ask for the options you would need to use, but it doesn't actually test it works.  I haven't investigated, but it's possible with a distribution that splits up executables from development packages that the executable will tell you the appropriate command line options but wouldn't actually validate you've installed the packages.

The autoconf is to use things like AC_SEARCH_LIBS and AC_CHECK_LIBS.

I know the original issue didn't state the version of bcftools, but I tried it with develop on a fresh openstack machine and sure enough it doesn't work, and nor does it list this as a dependency (hence the other issues, which you've now fixed - thanks).
