### ISSUE TITLE
Amalgamate INSTALL and github.io instructions

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#1172]
We have two different sets of build instructions (actually three but if I recall I managed to nuke htslib.org's copy).  The fact they differ *is not helpful*!

For example, INSTALL lists the various dependencies including libperl-dev and libgsl0-dev.  The copy at http://samtools.github.io/bcftools/howtos/install.html however misses out these packages.   Github.io also includes packages which are missing from the INSTALL file, eg ncurses.  Is that an error, or actually a requirement?  I suspect the former.

The github.io pages however are more detailed for instructions on building from github including the need to clone an up to date copy of htslib in the sibling directory too plus it has documentation on using the plugins.

Could we please make these documents identical.  Ideally we'd just use INSTALL.md and have the same file in both places.  Keeping them in sync is demonstrably something we fail at.

**Comment by pd3** [comment]
The .io page now points to the INSTALL document http://samtools.github.io/bcftools/howtos/install.html
