### ISSUE TITLE
"-lz -lpthread" is listed twice on some link lines

### ISSUE THREAD

**Issue by tseemann** [samtools/bcftools#1173]
eg.

```
gcc   -o test/test-regidx test/test-regidx.o regidx.o htslib-1.10.2/libhts.a -lpthread -lz -lm -lbz2 -llzma -lpthread -lz  
```

Not really important but thought I would let you know.

**Comment by pd3** [comment]
Likely one set is imported from htslib options, the other from bcftools. It should not be an issue though, or is it?

**Comment by tseemann** [comment]
I don't think gcc has issue with this, i just thought it may be indicative of a higher level problem. Thought it best to just let you know and see. I'll close - thank you!
