### ISSUE TITLE
Indel genotype likelihoods for haploid sample

### ISSUE THREAD

**Issue by LLN273** [samtools/bcftools#1175]
Hi,

I run "bcftools call" for a haploid sample and got the following for an indel:

II	7912	.	GAAA	GAA	217.469	PASS	INDEL;IDV=54;IMF=0.981818;DP=55;VDB=0.357981;SGB=-0.693146;MQSB=0.850742;MQ0F=0;AF1=1;AC1=1;DP4=0,0,23,19;MQ=58;FQ=-999	GT:PL	1:255,126,0

I am puzzled about the genotype likelihoods listed (PL:255,126,0) as this is a haploid sample and we used the option --ploidy 1 when running bcftools. 
All indels listed in the VCF file show 3 likelihoods. 
I tried several bcftools versions (1.5, 1.6, 1.10) and always got the same result.

Likelihoods for SNPs look fine:
II	7511	.	G	A	225.007	PASS	DP=53;VDB=0.769896;SGB=-0.693147;MQSB=1;MQ0F=0;AF1=1;AC1=1;DP4=0,0,22,25;MQ=60;FQ=-999	GT:PL	1:255,0

Also, variant calling using GATK lists only two likelihoods for the same indel variant shown above:
II	7912	.	GA	G	1567.97	.	AC=1;AF=1.00;AN=1;DP=45;FS=0.000;MLEAC=1;MLEAF=1.00;MQ=58.05;QD=34.84;SOR=1.038	GT:AD:DP:GQ:PL	1:0,45:45:99:1607,0

Any idea about the meaning of the three likelihoods shown for indels when running bcftools? 
Thanks a million! Any help would be appreciated :)

**Comment by pd3** [comment]
I have been unable to reproduce the bug in my test case. Could you please provide a toy example, including full VCF headers, to reproduce and debug the problem?

**Comment by LLN273** [comment]
Hello, thanks for looking into this!

The commands used:

module load samtools/1.6
module load bcftools/1.6

samtools mpileup -v -u --reference ./S288C_reference_strain.fa ./Illumina.W303.ref-S288C.bam > ./Illumina.W303.ref-S288C_var.raw.vcf

bcftools call -c -v --ploidy 1 -O v -o ./Illumina.W303.ref-S288C_var.called.vcf ./Illumina.W303.ref-S288C_var.raw.vcf

The files (reference fasta, bam and resulting vcf) can be downloaded from [this](https://drive.google.com/open?id=1_ZcmbxOb7jhZxu1r4i1kQxYSt0rihyfX) link (96MB).

**Comment by pd3** [comment]
The version you are using is way too old. Please upgrade and your problem should go away
http://samtools.github.io/bcftools/howtos/install.html

**Comment by LLN273** [comment]
Hi,
the problem persists after upgrading to bcftools 1.10 and running the following commands:

bcftools mpileup -O v -f ./S288C_reference_strain.fa ./Illumina.W303.ref-S288C.bam > ./Illumina.W303.ref-S288C_var.raw.vcf
bcftools call -c -v --ploidy 1 -O v -o ./Illumina.W303.ref-S288C_var.called.vcf ./Illumina.W303.ref-S288C_var.raw.vcf

**Comment by pd3** [comment]
Ah, I did not notice before this, sorry: the ploidy works only with the `-m` calling model and was not implemented for `-c`.

**Comment by LLN273** [comment]
That did the trick, thank you! :)
