### ISSUE TITLE
Symbolic alleles other than <DEL> are currently not supported error

### ISSUE THREAD

**Issue by terrycojones** [samtools/bcftools#1176]
I have a VCF (actually gVCF) file with the following line (TABs replaced with newlines to try to help with formatting):

```
Chromosome
28883
.
G
*,GAC,C,GAAAGAACTTCTCC,<NON_REF>
88371.02
.
DP=2328;ExcessHet=3.0103;MLEAC=0,0,0,0,2;MLEAF=0.00,0.00,0.00,0.00,1.00;RAW_MQandDP=4476393,2328
GT:AD:DP:GQ:PL:SB
5/5:0,0,0,0,0,0:0:8:106486,88349,82429,113792,89735,2147483647,7235,6956,7381,75,113792,89735,2147483647,7381,2147483647,7162,6949,7306,8,7306,0:0,0,0,0
```

When I pass the file to `bcftools consensus`, I get an error:

```
Symbolic alleles other than <DEL> are currently not supported: <NON_REF> at Chromosome:28883
```

If I delete just that line from the VCF file, all is well.  I don't understand why this line is triggering the error because there are many other lines in the VCF file that have `<NON_REF>`.  E.g., here is another such line:

```
Chromosome
27046
.
C
T,A,<NON_REF>
82712.03
.
BaseQRankSum=3.047;DP=2078;ExcessHet=3.0103;MLEAC=2,0,0;MLEAF=1.00,0.00,0.00;MQRankSum=-0.177;RAW_MQandDP=4014763,2078;ReadPosRankSum=1.113
GT:AD:DP:GQ:PL:SB
1/1:3,2073,1,0:2077:99:82726,6147,0,82722,6249,82897,82739,6255,82871,82877:1,2,1548,526
```

and another example that causes no problem:

```
Chromosome
28881
.
G
*,A,<NON_REF>
88423.05
.
DP=2367;ExcessHet=3.0103;MLEAC=0,2,0;MLEAF=0.00,1.00,0.00;RAW_MQandDP=4552537,2367
GT:AD:DP:GQ:PL:SB
2/2:0,2,2306,0:2308:99:106542,88401,82473,7172,6889,0,98684,86615,7165,94547:0,0,1695,613
```

**Comment by terrycojones** [comment]
Hmmmm... I took a look at the source and see the handling of this was changed in https://github.com/samtools/bcftools/commit/f5da043696666ca4bebb32b72de8faf72174fcbc  I'll try building from source.

**Comment by pd3** [comment]
Can you please confirm the problem is not present in the latest version and close the issue if so?

**Comment by terrycojones** [comment]
Yes, will get back to this ASAP and will update. Thanks!

**Comment by terrycojones** [comment]
Confirmed that this is no longer an issue, using the latest (git clone) bcftools & htslib sources.

**Comment by kennyworkman** [comment]
👍 solved by building from source
