### ISSUE TITLE
Feature? --private for homozygous

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#1179]
Hello, 
maybe it's an existing feature but then I have missed it
If one wants to find a new heterozygous site the following option exists:

```-x/X, --private/--exclude-private           select/exclude sites where the non-reference alleles are exclusive (private) to the subset samples```

But I couldn't find the opposite: select/exclude sites where the non-reference allele is absent in the subset samples. 

In other words, if I have 10 samples in my vcf, let's  say I want to find sites that in samples 2 are homozygous whereas they are heterozygous in all the other samples. Is there already a way to do it? 
Or maybe a way to use bcftools roh and then finding roh that are unique to each sample? 

Thank you!

**Comment by pd3** [comment]
No, `bcftools roh` would definitely not work for this. There is the `bcftools +contrast` plugin which finds novel alleles or genotypes in a subset of samples. One could also use the filtering -i/-e expressions to include/exclude sites where specific samples are het/hom/ref etc, for example `GT[@samples.txt]="het"`

**Comment by aderzelle** [comment]
Regarding the second option, how would it differ from my approach?
counting for each sample, ancestral and descendants, the heterozygosity  in windows of 100 Kb and then, simply reporting windows where the heterozygosity of a descendant is lower than that of the ancestor. 

I am trying to understand if bcftools filter does something more under the hood than this:

```awk -v var="$SAMPLE" '{if ($8 < $4) {print var"\t"$1"\t"$2"\t"$3"\t"$4-$8}}' > "${SAMPLE}".loh```

where $4 = the heterozygosity in the ancestor
$8 = the heterozygosity in the descendant
Thank you!

**Comment by pd3** [comment]
It was just for an illustration; the expression will do what (and only what) you tell it to do. In that example it includes sites where some samples listed in the file `samples.txt` are hets, it does not calculate heterozygosity rates or anything like that

**Comment by aderzelle** [comment]
Okay, that's what I wanted to make sure (I learned it was dangerous to assume things in bioinformatics).  
thanks for the support and always useful replies.
