### ISSUE TITLE
Filter variants by genotypes

### ISSUE THREAD

**Issue by biocyberman** [samtools/bcftools#118]
Hi,
Thank you very much for this interesting bcftools. I have been trying to filter variants based on samples' genotypes but  have not succeeded. I tried:

```
bcftools view -g "hom,het,het,het,het,hom" six_samples.vcf 
```

What I want to get is all variants that are are "hom" on sample1 and sample6, and "het" on all others.
If this works, then I want another command:

```
bcftools view -g "hom,,,,,hom" six_samples.vcf 
```

This is to get all variants that are "hom" on sample1 and sample6, and ignore genotypes of other samples (whether hom, het, or missing).

I am thinking that this may require to use `bcftools filter -i <EXPRESSION>`. But I don't know how to write this expression. 

Thanks
Vang

**Comment by jperales** [comment]
Hi,
Thank you very much for developing bcftools, it is very promising.

Here, I have the same issue: six single sample VCFs merged into a multi-sample VCF (by using `bcftools merge`). Then I tried to extract those variants which are GT=0/0 in the first sample AND GT=0/1 in the rest of them.

Firstly, I thought GT was an array of genotypes in the same order as the header. For instance, to retrieve variants meeting the first criteria, the command would be:
`$bcftools view -f PASS -i 'GT[0]="0/0"' combined.vcf.gz`
But it did NOT work, the obtained list of variants seems like "if ANY sample has "0/0" in that site, include it". Curiously, I obtained the same result using the following expressions:
`$bcftools view -f PASS -i 'GT="0/0"' combined.vcf.gz`
OR
`$bcftools view -f PASS -i 'GT[9999]="0/0"' combined.vcf.gz`

Finally, I got something as I was looking for using:
`$bcftools view -f PASS -i 'GT~"0/0.*0/1.*0/1.*0/1.*0/1"' combined.vcf.gz`
So my conclusion is that GT is really a single concatenated string which is separated by *something*. Could we query individual genotypes using REGEXPR?

Thanks
Javier

**Comment by ckandoth** [comment]
+1 for ability to filter on specified sample genotypes. In the field of cancer genetics, somatic variant callers produce VCFs with tumor and normal genotypes, and the following are some typical FP filters we would apply:

    LowTotalDepth - Less than 14 total reads in tumor, or less than 8 reads in normal
    LowTumorSupport - Less than 3 allele supporting read(s) in tumor
    HighNormalSupport - More than 2 allele supporting read(s) in the normal

The inability to do this with existing VCF tools, is the reason so many cancer bioinformaticians are writing their own ad-hoc code around the infernal [MAF format](https://wiki.nci.nih.gov/x/eJaPAQ).

**Comment by winni-genp** [comment]
It would be nice to have a way of setting specific genotypes to missing based on site-wide and FORMAT data.

**Comment by pd3** [comment]
This is now possible via `setGT` plugin, please see this thread https://github.com/samtools/bcftools/issues/433

**Comment by winni-genp** [comment]
Sweet!  Thanks.

**Comment by dwaggott** [comment]
+1 on filtering by FMT tags. Case example would be segregation under different genetic models. AD is needed as well as GT to remove false called genotypes.

**Comment by biocyberman** [comment]
Fantastic to have this feature implemented 👍
