### ISSUE TITLE
bcftools consensus: absent sites

### ISSUE THREAD

**Issue by ksw9** [samtools/bcftools#1184]
Hi, Thank you for providing this --absent option. I'm wondering which version this option is available on? I couldn't find it on the below version: 
 bcftools 1.10.2
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
Thank you in advance!

_Originally posted by @ksw9 in https://github.com/samtools/bcftools/issues/848#issuecomment-599816220_

**Comment by pd3** [comment]
You'll need the latest version from github, please see the installation instructions here http://samtools.github.io/bcftools/howtos/install.html

**Comment by ksw9** [comment]
Thank you!!

**Comment by tseemann** [comment]
@pd3 this, and the `ampliconclip` PR would be _very_ useful for international COVID work using the popular ARTIC protocol.  Any chance of a special "pandemic" 1.11 release?

**Comment by pd3** [comment]
@tseemann There is a new release coming at some point, but no clear timeline set. However, the code is freely available via git, so shouldn't be a problem?

**Comment by tseemann** [comment]
I will continue to do it an alternative way until an official release. 
Rushing is usually not a good idea.

**Comment by pd3** [comment]
As you wish. But note that stable version is just an illusion. I strongly encourage to use the latest github version of bcftools as it contains many bug fixes present in the official release.

**Comment by tseemann** [comment]
When working in accredited systems we need tagged releases to validate etc
ie. containers and bioconda packages

**Comment by pd3** [comment]
The failing test was added later and only revealed a bug which was present in the tagged release (which is now fixed, thanks for the nudge by the way). Github clones can be identified by the commit hash, e.g. the current version is 1.10.2-58-g37af152. But of course, you should do whatever works best for you. Just wanted to point out that there are many unfixed bugs in the last tagged bcftools release and that, in general, the bcftools releases come at more or less random time points so in terms of stability you don't gain much, if anything at all.
