### ISSUE TITLE
Possible to annotate the FILTER from an annotation VCF file, as an INFO/TAG in the target?

### ISSUE THREAD

**Issue by annblackz** [samtools/bcftools#1187]
Hi,

I was wondering if it was possible to annotate the FILTER tag of a VCF annotations file as an INFO tag in my target VCF file (such that it does not override or append to my sample's FILTER in its VCF)?  For example, I would like to annotate my sample VCF file with gnomAD frequencies.  I would like to annotate frequencies regardless of filter status from gnomAD, but also annotate  the variant's  gnomAD's filter status into my sample VCF, to know that the annotations did not pass specific filters.

Thanks,

Ann

**Comment by pd3** [comment]
Do you mean something like this?
````
$ bcftools filter -e 'AF<0.01' -s LowAF -m + file.vcf | bcftools query -f '%AF  %FILTER\n'
0.0  LowAF;ExistingFilter
0.2  ExistingFilter 
````

**Comment by annblackz** [comment]
Hi, thanks for your response.  Basically I was wanting to do something like the following:

gnomAD VCF data (simplified):

22      38136964        rs764626864     A       G       5441.68 gnomad_exome_AC0        gnomad_exome_AN=168344;gnomad_exome_AC=0;gnomad_exome_AF=0

My sample VCF data (simplified):

22	38136964	.	A	G	10717.8	PASS	AC=1;AF=0.5;AN=2	GT:AD:DP:GQ:PL	0/1:494,480:974:99:10746,0,11138

Output I would like have (I want to move the filter from gnomad_exome into a INFO tag in my sample in addition to all the INFO fields):

22	38136964	.	A	G	10717.8	PASS	AC=1;AF=0.5;AN=2;gnomad_exome_AN=168344;gnomad_exome_AC=0;gnomad_exome_AF=0;**gnomad_exome_FILTER=gnomad_exome_AC0**	GT:AD:DP:GQ:PL	0/1:494,480:974:99:10746,0,11138

Command something like:

bcftools -annotate -a gnomad_exome_data.vcf -c INFO,**FILTER:=INFO/gnomad_exome_FILTER** mysample.vcf

**Comment by pd3** [comment]
This is now possible. Note that the command is the opposite of what you suggested:
````
bcftools annotate -c INFO/NewTag:=FILTER
````

**Comment by annblackz** [comment]
Thank you so much!

**Comment by SpikyClip** [comment]
> This is now possible. Note that the command is the opposite of what you suggested:
> 
> ```
> bcftools annotate -c INFO/NewTag:=FILTER
> ```

Unfortunately this solution is not working for me. Here is my full code block:
```bash
main() {
    module load "bcftools/1.16"
    for vcf_in in "$@"; do
        echo "Filtering '${vcf_in}'"
        local vcf_out="${vcf_in%%.vcf*}.ngpmp_filt.vcf"
        bcftools view "${vcf_in}" --threads 8 |
            bcftools +split-vep - --columns "${VEP_COLS}" |
            bcftools filter \
                --threads 8 \
                --include "${KEEP_FILTER}" |
            bcftools annotate \
                --threads 8 \
                --columns "INFO/NewTag:=FILTER" \
                --output "${vcf_out}"
    done
}
```
With the argument `--columns "INFO/NewTag:=FILTER"` I get the following error:
```
Could not parse "FILTER NewTag", expected INFO, FORMAT, or FILTER prefix
```
With the argument `--columns "INFO/NewTag:=FILTER/FILTER"` I get the following error:
```
Cannot transfer FILTER to INFO
```

Note that while it seems silly transferring the `FILTER` column to `INFO` the reason why I have to do it is because [GATK funcotator drops the `FILTER` column in its conversion to `MAF`](https://gatk.broadinstitute.org/hc/en-us/community/posts/360057822171/comments/16901394854427) and I was hoping this might be a solution to retaining the `FILTER` column.

**Comment by dennishendriksen** [comment]
I'm running into the same issue as @SpikyClip.

I can reproduce the error using the bcftools test case: https://github.com/samtools/bcftools/blob/1.18/test/test.pl#L509

```
$ bcftools annotate -c FILTER,INFO/FILTER\:=FILTER,INFO/INFO_FILTER:=INFO/FILTER annotate19.src.vcf
Could not parse "FILTER INFO/FILTER", expected INFO, FORMAT, or FILTER prefix
```

Any thoughts @pd3?

**Comment by pd3** [comment]
I just pushed a commit that addresses this issue, please see the updated tutorial here http://samtools.github.io/bcftools/howtos/annotate.html#transfer_filter_to_info. With this commit it should work.

The problem was that the program likes to transfer annotations between files but not as much within the same file. A quick workaround for versions of bcftools without the fix is to use the same file as the annotation file, i.e.
```
bcftools annotate -c INFO/tag:=FILTER -a file.bcf file.bcf
```

**Comment by SpikyClip** [comment]
Thanks @pd3! 

> The problem was that the program likes to transfer annotations between files but not as much within the same file. A quick workaround for versions of bcftools without the fix is to use the same file as the annotation file

I actually tried this earlier and while it did produce output, all the tags were `.`
```
$ bcftools annotate --columns info/newtag:=FILTER -a test.vcf.gz test.vcf.gz
chr1    4457552 .       CAAAAA  C,CAA,CAAA      .       clustered_events;germline;multiallelic;weak_evidence    AS_FilterStatus=weak_evidence|weak_evidence|weak_evidence;AS_SB_TABLE=1,1|2,0|2,1|0,3;DP=16;ECNT=3;GERMQ=2;MBQ=30,33,33,33;MFRL=303,334,309,297;MMQ=60,60,60,60;MPOS=65,31,40;POPAF=7.3,2.04,0.461;ROQ=93;RPA=21,16,18,19;RU=A;STR;STRQ=93;TLOD=5.24,4.73,4.12;ANN=C|intergenic_region|MODIFIER|LINC01777-ENSG00000284694|ENSG00000235054-ENSG00000284694|intergenic_region|ENSG00000235054-ENSG00000284694|||n.4457553_4457557delAAAAA||||||,CAA|intergenic_region|MODIFIER|LINC01777-ENSG00000284694|ENSG00000235054-ENSG00000284694|intergenic_region|ENSG00000235054-ENSG00000284694|||n.4457555_4457557delAAA||||||,CAAA|intergenic_region|MODIFIER|LINC01777-ENSG00000284694|ENSG00000235054-ENSG00000284694|intergenic_region|ENSG00000235054-ENSG00000284694|||n.4457556_4457557delAA||||||;CSQ=-|intergenic_variant|MODIFIER|||||||||||||||||||sequence_alteration||||||||||||||||||||||||||||||||||||||||||||||||||||||||,AA|intergenic_variant|MODIFIER|||||||||||||||rs59365409||||sequence_alteration||||||||||||||||||||||||||||||||||0.001707|0.001039|0|0.001372|0|0.002073|0.00446|0.006944|0.001956|0.003112|0.002395|0.006944|gnomADg_MID||||||||||,AAA|intergenic_variant|MODIFIER|||||||||||||||rs59365409||||sequence_alteration||||||||||||||||||||||||||||||||||0.4528|0.4225|0.4371|0.4752|0.4025|0.6596|0.5806|0.5211|0.4473|0.4566|0.4815|0.6596|gnomADg_EAS||||||||||;newtag=.    GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1/2/3:2,2,3,3:0.199,0.271,0.306:10:1,2,2,0:1,0,0,1:2,2,3,3:1,1,4,4
```

However your recent update worked using `-c INFO/newtag:=./FILTER`. 

Thank you so much for fixing this so quickly, it was a real annoyance in my pipeline having to split each filter into separate VCFs, I was planning to learn `awk` so I could pull lift the `FILTER` to `INFO` but now I don't have to. Appreciate your work 😊
