### ISSUE TITLE
bcftools annotate adding default . as value when variant not in annotation.vcf

### ISSUE THREAD

**Issue by cvlvxi** [samtools/bcftools#1188]
Hey there,

I was just wondering if it's possible to use bcftools annotate where it will always append something for the -c <ARGS...>, INFO/MyAnnotation, INFO/MyAnnotation2 you give it such that if it doesn't find an overlapping variant in the -a <VCF_FILE> it will please a default missing value e.g. '.' ?

So in this case it should always add MyAnnotation=., MyAnnotation=. if the input vcf has a variant that doesn't overlap the annotations..

Cheers

**Comment by pd3** [comment]
Not in a single step I am afraid. However, you could first annotate as you have done, and then add the missing annotations back explicitly, for example as follows
````
bcftools annotate -c ... -a annots.vcf.gz ori.vcf.gz -Ob -o tmp.bcf
bcftools query -f '%CHROM\t%POS\t%Annotation\n' tmp.bcf | bgzip -c > tmp.txt.gz
tabix -s1 -b2 -e2 tmp.txt.gz
bcftools annotate -c ... -a tmp.txt.gz tmp.bcf -Oz -o new.vcf.gz
````

**Comment by cvlvxi** [comment]
Great thanks!
