### ISSUE TITLE
Clean my vcf file

### ISSUE THREAD

**Issue by pwang16** [samtools/bcftools#1191]
Dear Sir/Madam,
Hope all is well with you and stay health.

Which command lines I should use to clean my vcf file? There are a small part of "2|1, 0|2, 2|0, 2|2, 1|2" in my vcf file, and I do not know what they are.

I am new and never use the bcftools before.

Thanks,
Peng

**Comment by mp15** [comment]
Those are phased variants. It is a bit of a complex topic so I would suggest you have a read of the VCF specification at: http://samtools.github.io/hts-specs

**Comment by mp15** [comment]
Oh and as regards “cleaning” your VCF file if you mean filtering out poor variants, that depends on what tool you used to call them. Petr wrote some pointers here: https://samtools.github.io/bcftools/howtos/variant-calling.html

**Comment by pwang16** [comment]
Can I regard the "2|1, 0|2, 2|0, 2|2, 1|2" in my vcf file as the missing data? – use the "NA" to replace them?

**Comment by mp15** [comment]
You could but assuming this is the GT field that would be the wrong thing to do. If it is in the GT field then you can treat the | as equiv to a /
