### ISSUE TITLE
Invalid character '.' in 'DP' FORMAT

### ISSUE THREAD

**Issue by sbgLuka** [samtools/bcftools#1192]
Hi, 

I tried to use **BCFtools Concat** to merge multiple VCF chunks after parallelization, however I get error:
`Invalid character '.' in 'DP' FORMAT` since I have '.' on samples where there is no mutation. 
Here is that field in the header:
`##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth for tier1">`

I noticed that **BCFtools Merge also creates files with dots for the samples where mutation is missing**, so why other BCFtools fail (BCFtools Sort also) when there is the dot in the sample? Am I doing something wrong?

Thanks,
Luka.

**Comment by pd3** [comment]
This looks like an invalid VCF, you have not provided enough information. The error message should include at which position the error occurred, you should inspect the data manually or try `vcf-validator` from the vcftools package.

**Comment by sbgLuka** [comment]
Thanks for quick answer. I wasn't clear enough. When I try:
` bcftools concat -o test.vcf --allow-overlaps HCC1143-HCC1143BL.3.vcf.gz HCC1143-HCC1143BL.4.vcf.gz`. I get: 
`[E::vcf_parse_format] Invalid character '.' in 'DP' FORMAT field at chr1:880128
[E::vcf_parse_format] Invalid character '.' in 'DP' FORMAT field at chr1:117156857`
And **it outputs a VCF with header only**.

Here are the compressed VCF attached so you can try to reproduce the issue.
[HCC1143-HCC1143BL.4.vcf.gz](https://github.com/samtools/bcftools/files/4445942/HCC1143-HCC1143BL.4.vcf.gz)
[HCC1143-HCC1143BL.3.vcf.gz](https://github.com/samtools/bcftools/files/4445943/HCC1143-HCC1143BL.3.vcf.gz)

This only an example. In real use case I am trying to concatenate 20 VCF files, and **when I tried without** `--allow-overlaps` I got an error: 
`The chromosome block chr1 is not contiguous, consider running with -a.`

**Comment by pd3** [comment]
You were clear enough, too bad my answer was not. Looking in the VCF, the DP field is defined as `Type=Integer` yet in the VCF a float is present 0.111, therefore the parser complains about the unexpected dot. If you change the definition, it should work.
