### ISSUE TITLE
What is the correct replacement line command of -bvcg of BCFTools in the new version?

### ISSUE THREAD

**Issue by Bruna-Trevisan** [samtools/bcftools#1194]
About the BCFTools, what is equivalente in the new version of -bvcg?

Old command:
$ samtools mpileup -uf genome.fasta sorted.bam | bcftools view -bvcg - > var.raw.bcf  
$ bcftools view var.raw.bcf | vcfutils.pl varFilter -D100 > var.flt.vcf

New command:
$ samtools mpileup -uf genome.fasta sorted.bam | bcftools call -c - > var.raw.bcf  
$ bcftools view var.raw.bcf | vcfutils.pl varFilter -D100 > var.flt.vcf

But I am not sure that -c make the same as -bvcg. Could you help me, please?

**Comment by pd3** [comment]
This is the recommended usage
````
bcftools mpileup -f reference.fa alignments.bam | bcftools call -mv -Oz -o calls.vcf.gz
````
Check also http://samtools.github.io/bcftools/howtos/variant-calling.html
