### ISSUE TITLE
plot-vcfstats error

### ISSUE THREAD

**Issue by zoeluo15** [samtools/bcftools#1197]
Hello,

I am using BCFtools 1.10.2-GCC-9.2.0 and trying to execute the following command:

plot-vcfstats -p ${outFolder} ${fileName}.stats

and this gives me the following  error message:

Plotting graphs: python3 plot.py
Can't exec "python3": No such file or directory at /opt/nesi/CS400_centos7_bdw/BCFtools/1.10.2-GCC-9.2.0/bin/plot-vcfstats line 299.
The command exited with non-zero status -1:
        python3 plot.py

 at /opt/nesi/CS400_centos7_bdw/BCFtools/1.10.2-GCC-9.2.0/bin/plot-vcfstats line 111.
        main::error('The command exited with non-zero status -1:\x{a}\x{9}python3 plot.py\x{a}\x{a}') called at /opt/nesi/CS400_centos7_bdw/BCFtools/1.10.2-GCC-9.2.0/b$
        main::plot('HASH(0x63c0f8)') called at /opt/nesi/CS400_centos7_bdw/BCFtools/1.10.2-GCC-9.2.0/bin/plot-vcfstats line 70

I have also tried two earlier versions which are 1.8-gimkl-2017a and 1.9-GCC-7.4.0, and got different error messages:

Plotting graphs: python plot.py
Traceback (most recent call last):
  File "plot.py", line 54, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib
The command exited with non-zero status 256:
        python plot.py

 at /opt/nesi/CS400_centos7_bdw/BCFtools/1.9-GCC-7.4.0/bin/plot-vcfstats line 99.
        main::error('The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}') called at /opt/nesi/CS400_centos7_bdw/BCFtools/1.9-GCC-7.4.0/bin/$
        main::plot('HASH(0x63bc20)') called at /opt/nesi/CS400_centos7_bdw/BCFtools/1.9-GCC-7.4.0/bin/plot-vcfstats line 69

Any help would be greatly appreciated!

**Comment by pd3** [comment]
In order to produce the plots, `python3` and `matplotlib` must be installed.

**Comment by zoeluo15** [comment]
> In order to produce the plots, `python3` and `matplotlib` must be installed.

Thank you very much!
