### ISSUE TITLE
bcftools 1.10.2: sort fails on vcf with "Data contains 64-bit values not representable in BCF."

### ISSUE THREAD

**Issue by TomHarrop** [samtools/bcftools#1202]
Hi, I'm getting an error about 64-bit values using bcftools 1.10.2.

```
bcftools 1.10.2
Using htslib 1.10.2
```

The following command fails 

```
bcftools sort --max-mem 500G \
	--output-type v \
	--temp-dir /path/to/tmp/tmp1m7n7ndu \
	output/popgen/mapped/populations_header.vcf \
	> output/popgen/mapped/populations_sorted.vcf \
	2> output/logs/sort_vcf.mapped.log
```

Here's the log:

```
Writing to /path/to/tmp/tmp0jab5udl
[E::bcf_write] Data contains 64-bit values not representable in BCF.  Please use VCF instead
[buf_flush] Error: cannot write to /path/to/tmp/tmp0jab5udl/00001.bcf
Cleaning
```

The same command is working fine with the following three bcftools installations:

```
bcftools 1.9
Using htslib 1.9
```

```
bcftools 1.9-294-g1f21775
Using htslib 1.9-456-gc1c8c80-dirty
```

```
bcftools 1.9-53-g2dd4ea5
Using htslib 1.9-39-g0a8cdc6
```

The longest scaffold in the genome is 2.178 MB.

It's an 817 MB VCF so I increased `--max-mem` to a high value to make sure it fit in memory, but that didn't help.

Our system has scratch mounted somewhere other than `/tmp` so I'm specifying that manually, but I have no problem using `touch` to make a file in that directory.

Thanks!

**Comment by pd3** [comment]
Can you try with the latest github version of bcftools and htslib please? There was some work done on this since the last release.

**Comment by TomHarrop** [comment]
Hi, just tried it with the following version and got the same error:

```
bcftools 1.10.2-36-gd6d1ca6
Using htslib 1.10.2-58-g2e36fa6
```

**Comment by pd3** [comment]
Thank you for this and sorry about the delays. Could you please compile htslib with this new pull request https://github.com/samtools/htslib/pull/1059? With this it should print a more informative error message in which the position of the offending line should be included. Hopefully then you'll be able to locate the offending record and with that I'll be able to reproduce the problem and create a fix.

**Comment by TomHarrop** [comment]
OK, thanks for the help with this. Here's the offending line.

```
contig_35277	4294967290	680129_88	T	A	.	PASS	NS=17;AF=0.294;loc_strand=m	GT:DP:AD:GQ:GL	./.	1/1:1:0,1:25:-2.65,-1.94,-0.01	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:1:1,0:29:-0.00,-2.31,-3.39	./.	./.	./.	./.	./.	./.	./.	./.	0/0:9:9,0:40:-0.00,-4.71,-27.52	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:2:2,0:32:-0.00,-2.61,-6.41	./.	0/0:3:3,0:35:-0.00,-2.91,-9.43	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:5:5,0:40:-0.00,-3.51,-15.46	0/0:3:3,0:35:-0.00,-2.91,-9.43	0/0:3:3,0:35:-0.00,-2.91,-9.43	./.	./.	1/1:1:0,1:25:-2.65,-1.94,-0.01	./.	./.	./.	./.	./.	./.	./.	1/1:1:0,1:25:-2.65,-1.94,-0.01	0/0:5:5,0:40:-0.00,-3.51,-15.46	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:4:4,0:39:-0.00,-3.21,-12.44	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	0/0:4:4,0:39:-0.00,-3.21,-12.44	./.	./.	./.	./.	./.	1/1:2:0,2:28:-5.66,-2.24,-0.00	./.	./.	./.	./.	./.	./.	./.	./.	0/0:3:3,0:35:-0.00,-2.91,-9.43	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	./.	1/1:1:0,1:25:-2.65,-1.94,-0.01	./.	./.	0/0:4:4,0:39:-0.00,-3.21,-12.44	./.	./.	./.
```
Here's the line from the `fai` for that contig... 

```
contig_35277	182791	344416269	60	61
```

This was the version:
```
bcftools 1.10.2-37-g034b466
Using htslib 1.10.2-59-g42825b7
```
Here's the output:
```
[E::bcf_write] Data at contig_35277:4294967290 contains 64-bit values not representable in BCF. Please use VCF instead
[buf_flush] Error: cannot write to /path/to/tmp/tmp.mqPTT4hypS/00001.bcf
Cleaning
```

**Comment by pd3** [comment]
Yes. The problem is that the coordinate exceeds 32bits but BCF, which is internally used for efficiency, cannot handle 64bit coordinates. In your case it seems to be a bug since the contig size is supposed to be only 182791.
