### ISSUE TITLE
Improve Explanation of bcftools mpileup Regions File

### ISSUE THREAD

**Issue by DarioS** [samtools/bcftools#1206]
`-R` is defined as "As for `-r`, `--regions`, but regions read from FILE; see Common Options" The definition of `-r` shows you can use the format chr1:12345 or chr2, for example. However, when I click on the Common Options hyperlink, I see "FILE Files can be both VCF or BCF, uncompressed or BGZF-compressed." So, can the regions file simply be CHR:POS format in a plain text file, one location per line, or does it need to be VCF format instead? The wording is unclear and needs improvement; how exactly is it "As for -r"?

**Comment by pd3** [comment]
If you scroll little bit down in the manual, in "Common Options" there is a description for `-r, --regions` and `-R, --regions-file`. I don't understand what the problem is http://samtools.github.io/bcftools/bcftools.html
