### ISSUE TITLE
Strange result expression bcftools query -i

### ISSUE THREAD

**Issue by ralonso-igenomix** [samtools/bcftools#1212]
Hello,
If I execute this in bcftools 1.10.2

clinvar.vcf.gz is https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz

<pre>bcftools query -i "CLNREVSTAT='criteria_provided,_conflicting_interpretations'"  -f '%CLNREVSTAT\n' clinvar.vcf.gz | sort -u</pre>

I get this results:

<pre>
criteria_provided,_conflicting_interpretations
criteria_provided,_multiple_submitters,_no_conflicts
criteria_provided,_single_submitter
</pre>

I was expecting to get only criteria_provided,_conflicting_interpretations. Is there anything that I don't understand.

Many thanks for this awesome tools.

**Comment by pd3** [comment]
This is an unpleasant side effect of comma having a special meaning. In VCF comma is used to separate multiple values and when multiple values are compared, the OR logic is used and  consequently these filtering expressions become equivalent
```
-i "CLNREVSTAT='criteria_provided,_conflicting_interpretations'"
-i "CLNREVSTAT='criteria_provided' || CLNREVSTAT='_conflicting_interpretations'"
```
So if you change the expression to
```
-i "CLNREVSTAT='criteria_provided' && CLNREVSTAT='_conflicting_interpretations'"
```
it should work. I'll make sure this is documented and ideally cases like this are detected and a warning printed.
