### ISSUE TITLE
Allow index loading from a specific path

### ISSUE THREAD

**Issue by davidlougheed** [samtools/bcftools#1213]
Hello
I'm working on a project where TBI files are not necessarily stored in the same location as their corresponding VCFs (they're stored as encoded names based on their hash on the filesystem). It would be convenient if we could pass a specific path to an index instead of relying on the implicit "append `.tbi`" behaviour when using tools such as `bcftools index --nrecords`.

**Comment by pd3** [comment]
This feature was added recently, one can add non-standard index names by appending the suffix `##idx##` and the index file name. See the example in the manual page http://samtools.github.io/bcftools/bcftools.html
```
bcftools view -r X:2928329 file.vcf.gz##idx##non-standard-index-name
```

**Comment by davidlougheed** [comment]
Thank you!
