### ISSUE TITLE
No SNPs, but only InDels

### ISSUE THREAD

**Issue by reneshbedre** [samtools/bcftools#1214]
Hi,

I am running `bcftools mpileup` and `call` commands to call variants from plant GBS data. But, I see only InDel and no SNPs in final bcf file generated from `bcftools call` command

Here is the commands I am running
 `bcftools mpileup --illumina1.3+  --fasta-ref genome.fa --ignore-RG --min-BQ 20 --min-MQ 20 --max-depth 8000  --threads 18 -Ou bam1 bam2 bam3 bam4 > raw.bcf`

`bcftools call --consensus-caller --variants-only --output-type u -o raw_bcfcall.bcf raw.bcf`

Please, let me know what is the issue. Thanks. 

Version: 1.10.2 (using htslib 1.10.2)

**Comment by pd3** [comment]
Can you try `call -m` and `call -mv` instead of `call -cv`? Other things to try, run `mpileup` with `-B` and drop the `--illumina1.3+ --min-BQ 20 --min-MQ 20` options to see if it makes any difference?

**Comment by reneshbedre** [comment]
Hi Petr,

Thank you for your reply. I am running the `bcftools mpileup` without `--illumina1.3+ --min-BQ 20 --min-MQ 20` and I have started to see the SNPs in raw bcf file. The program is still running and I will update you again. 

Is it some kind of bug in the `bcftools`? It should also call SNPs with `--illumina1.3+ --min-BQ 20 --min-MQ 20` options, right?

**Comment by pd3** [comment]
I don't think it is a problem with bcftools, the program just does what you tell it to do. It seems you are applying filtering criteria that are too strict for your data. You can check the mapping and base qualities in your BAM files. The default values (i.e. no options given) work for data mapped with the most commonly used aligners, such as bwa, and data that pass basic quality control and have reasonable BQ distributions.

**Comment by reneshbedre** [comment]
Hi Petr,

Thank you for your explanation. It did work finally!
