### ISSUE TITLE
fill-tags for multi-allelic sites

### ISSUE THREAD

**Issue by marqueda** [samtools/bcftools#1216]
I may have spotted a bug: when I apply the fill-tags plugin to a site with several alleles, the AF filed wos not correctly updated (only the first allele was correctly updated).

Here is the pre-filtering entry:
```
chrM    2699   .        GC      GCC,GCCC,GCCCC,G        1.1478e+07      .       AC=1,0,0,0;AF=0.472,0.084,0.002868,0.026;AN=2;BaseQRankSum=-0.241;ClippingRankSum=0;DP=695189;ExcessHet=-0;FS=3.198;InbreedingCoeff=0.7305;MLEAC=497,88,3,27;MLEAF=0.475,0.084,0.002868,0.026;MQ=34.57;MQRankSum=-0.058;QD=29.6;ReadPosRankSum=-0.259;SOR=1.103       GT:AD:DP:GQ:PGT:PID:PL  0/1:518,1904,51,0,0:2473:99:.:.:60247,0,2907,57598,7653,71009,65711,10063,76739,101023,60890,9495,71633,80380,74931
```

And here is the post-filtering entry:
```
chrM    2699   .        GC      GCC,GCCC,GCCCC,G        1.1478e+07      .       AC=1,0,0,0;AF=0.5,0,0,0;AN=2;BaseQRankSum=-0.241;ClippingRankSum=0;DP=695189;ExcessHet=-0;FS=3.198;InbreedingCoeff=0.7305;MLEAC=497,88,3,27;MLEAF=0.475,0.084,0.002868,0.026;MQ=34.57;MQRankSum=-0.058;QD=29.6;ReadPosRankSum=-0.259;SOR=1.103        GT:AD:DP:GQ:PGT:PID:PL  0/1:518,1904,51,0,0:2473:99:.:.:60247,0,2907,57598,7653,71009,65711,10063,76739,101023,60890,9495,71633,80380,74931
```

I got the same result, whether I just used +fill-tags or +fill-tags -- -t AF. Could this be a bug in the fill-tags plugin?

Thank you for having a look at this!
David

**Comment by pd3** [comment]
I don't see a problem, the program worked as expected. The single `0/1` genotype was correctly used to produce the allele frequencies. Perhaps your confusion comes from the fact that the AF tag is defined as Number=A and hence only alternate alleles have a value assigned?

**Comment by marqueda** [comment]
Dear Petr,
Indeed, I totally forgot about that. Sorry! No bug here, my mistake...
Thanks for maintaining this fantastic software, my first choice for most analyses we do!
Best regards,
David
