### ISSUE TITLE
converting from hap/legend/sample file to vcf results in no variant IDs in vcf file 

### ISSUE THREAD

**Issue by Arslan-Zaidi** [samtools/bcftools#1217]
Hi, 

I am trying to convert a hap/legend/sample file set to vcf using the command:

bcftools --haplegendsample2vcf <prefix> -Oz -o <out_file> 

The conversion works fine except for the fact that there are no IDs for variants in the vcf file. They show up with a "." in the ID column. I've tried the --vcf-id flag as well to no avail. My legend file has variant IDs, which look like this:

id position a0 a1
9:5_A_T 5 A T  
9:25_A_T 25 A T  
9:39_A_T 39 A T  
9:55_A_T 55 A T  
9:84_A_T 84 A T  
9:88_A_T 88 A T  
9:117_A_T 117 A T  
9:127_A_T 127 A T  
9:144_A_T 144 A T  

Am i missing something or is this a bug? I can add the variant IDs later using bcftools annotate but it takes time and adds an extra step to an already long and time-consuming pipeline. I'd appreciate any help in the matter. 

Thanks!

**Comment by pd3** [comment]
Thank you for reporting this issue. The switch was silently ignored, it was originally introduced to work in the other direction. This is now fixed, if you encounter any problems, please let us know.
