### ISSUE TITLE
bcftools annotate error message

### ISSUE THREAD

**Issue by rozaimirazali** [samtools/bcftools#1221]
Hello.

I am trying to annotate my vcf with Ensembl PostGAP.txt.gz file and i am getting the following error message

`[E::bcf_sr_regions_init] Could not parse the file ../input/postgap.txt.gz, using the columns 1,2[,-1]`
`Could not initialize the annotation file: ../input/postgap.txt.gz`

My bcftools annotate command is:

> bcftools annotate -a ../input/postgap.txt.gz --threads 4 -O z -o ../output/chr22/chr22.postgap.vcf.gz -c chrom,pos,GRCh38_chrom,GRCh38_pos,afr,amr,eas,eur,sas,gnomad,gnomad_sas,gnomad_oth,gnomad_asj,gnomad_nfe,gnomad_afr,gnomad_amr,gnomad_fin,gnomad_eas,gene_symbol,gene_id,gene_chrom,gene_tss,GRCh38_gene_chrom,GRCh38_gene_pos,disease_name,disease_efo_id,score,rank,r2,cluster_id,gwas_source,gwas_snp,gwas_pvalue,gwas_pvalue_description,gwas_odds_ratio,gwas_odds_ratio_ci_start,gwas_odds_ratio_ci_end,gwas_beta,gwas_size,gwas_pmid,gwas_study,gwas_reported_trait,ls_snp_is_gwas_snp,vep_terms,vep_sum,vep_mean,GTEx_Thyroid,GTEx_Testis,GTEx_Small_Intestine_Terminal_Ileum,GTEx_Nerve_Tibial,GTEx_Brain_Frontal_Cortex_BA9,GTEx_Skin_Not_Sun_Exposed_Suprapubic,GTEx_Vagina,GTEx_Whole_Blood,GTEx_Breast_Mammary_Tissue,GTEx_Pituitary,GTEx_Adrenal_Gland,GTEx_Heart_Atrial_Appendage,GTEx_Stomach,GTEx_Brain_Caudate_basal_ganglia,GTEx_Artery_Tibial,GTEx_Colon_Transverse,GTEx_Brain_Cerebellum,GTEx_Esophagus_Muscularis,GTEx_Liver,GTEx_Brain_Hypothalamus,GTEx_Prostate,GTEx_Pancreas,GTEx_Adipose_Subcutaneous,GTEx_Spleen,GTEx_Colon_Sigmoid,GTEx_Brain_Anterior_cingulate_cortex_BA24,GTEx_Esophagus_Gastroesophageal_Junction,GTEx_Brain_Hippocampus,GTEx_Brain_Cortex,GTEx_Heart_Left_Ventricle,GTEx_Cells_Transformed_fibroblasts,GTEx_Uterus,GTEx_Ovary,GTEx_Cells_EBV-transformed_lymphocytes,GTEx_Artery_Coronary,GTEx_Adipose_Visceral_Omentum,GTEx_Brain_Nucleus_accumbens_basal_ganglia,GTEx_Brain_Cerebellar_Hemisphere,GTEx_Esophagus_Mucosa,GTEx_Artery_Aorta,GTEx_Brain_Putamen_basal_ganglia,GTEx_Muscle_Skeletal,GTEx_Lung,GTEx_Skin_Sun_Exposed_Lower_leg,GTEx,VEP,Fantom5,DHS,PCHiC,Nearest,Regulome,VEP_reg,GERP,ld_snp_rsID -h head.txt chr22.vcf.gz

head.txt contains:

`##INFO=<ID=ld_snp_rsID,Number=1,Type=String,Description="">`
`##INFO=<ID=chrom,Number=1,Type=Integer,Description="">`
`##INFO=<ID=pos,Number=1,Type=Integer,Description="">`
`##INFO=<ID=GRCh38_chrom,Number=1,Type=Integer,Description="">`
`##INFO=<ID=GRCh38_pos,Number=1,Type=Integer,Description="">`
`##INFO=<ID=afr,Number=1,Type=Float,Description="">`
`##INFO=<ID=amr,Number=1,Type=Float,Description="">`
`##INFO=<ID=eas,Number=1,Type=Float,Description="">`
`##INFO=<ID=eur,Number=1,Type=Float,Description="">`
`##INFO=<ID=sas,Number=1,Type=Float,Description="">`

**Comment by pd3** [comment]
Recently there were improvements in htslib which should produce more informative error messages. Can you please try with the latest version of htslib and bcftools to see if that helps identify the problem? http://samtools.github.io/bcftools/howtos/install.html

**Comment by rozaimirazali** [comment]
> Recently there were improvements in htslib, recompiling with the updated version should provide more informative error messages. Can you please try with the latest version of htslib and bcftools to see if that helps identify the problem? http://samtools.github.io/bcftools/howtos/install.html

It works after I updated to ver 1.10.2
