### ISSUE TITLE
Filtering vcf using bcftools filter-Expression Question

### ISSUE THREAD

**Issue by luised94** [samtools/bcftools#1224]
Hello! 
I want to filter my vcf file using the QD (Qual score normalized by Allele Depth, QUAL/AD) metric. 
To do this I have been using the following command:

bcftools filter -i 'QUAL/FMT/AD[0:1]>2' -o calls_filt.vcf calls.vcf

I am trying to divide the QUAL value by the second value of the format AD array.

My initial vcf (calls.vcf) has around 8000 variants. Using this command reduces the number to 16. However, these variants don't satisfy the condition as you can see from the following output:
![bcftools image for filtering issue](https://user-images.githubusercontent.com/65787386/82706752-799afc00-9c48-11ea-90c8-d97e33be0547.png)

I am not sure how it is actually performing the filtering or how division is working inside the expression. Filtering by one condition works just fine. Not sure if i am missing something for how expressions work for filtering or if there is way to do this with another tool. 

Thanks for your time and help. Let me know if any additional info can help.
Hope everyone is staying safe.
Best

**Comment by luised94** [comment]
I annotatetd the total allelic depths in the info column and use the following command:

bcftools query -i 'QUAL/INFO/AD[1]>2' -f '%CHROM %POS %QUAL [%AD{0} %AD{1}]\n' call.vcf | wc -1 

The result shows that they comply with the condition. I do get the warning: Assuming INFO/AD even tho I specify it.

I think its working now but will wait for some feedback before I close the issue just in case.

**Comment by pd3** [comment]
Ah, thank you for noticing and reporting the bug, now fixed by 68c8aba. Regarding the warning, I am not able to reproduce it with the latest github version. Can you please test if it indeed disappears with the latest version? http://samtools.github.io/bcftools/howtos/install.html
