### ISSUE TITLE
calculation of nHets and nHomA

### ISSUE THREAD

**Issue by rturba** [samtools/bcftools#1225]
Hello! I am trying to understand how the program calculates the number of nHet and nHomA sites. I really tried looking at the script, but I need some help understanding the code.

I know the header says it's only using SNP data, but when I filter my vcf file to remove indels (vcftools -remove-indels), I get different numbers for SNPs, with the filtered vcf file having ~100,000 less.

Also, I am comparing the results with another custom python script (offered by @dechavezv), and strangely, the nHomR always match but never the nHets and nHomR. The bcftools results are always higher. I'm attaching his script here, if that proves useful!
[HetPerInd_editRT.txt](https://github.com/samtools/bcftools/files/4670661/HetPerInd_editRT.txt)

**Comment by pd3** [comment]
This is a different repository, you meant to ask your question here https://github.com/vcftools/vcftools/issues. If you'd like to use bcftools, the command is `bcftools stats -s - file.vcf`.

**Comment by rturba** [comment]
I don't understand. My question is related to the bcftools -stats, not vcftools.

When I use it and look at the .vchk file, I can see the number of nHets and nHomA that was used to calculate the heterozygosity ratio but I don't know how the script is counting the number of nHet and nHomA SNPs. When I compare the script I have with the results from bcftools -stats, the nHomR always match, but not the others.

Is bcftools ignoring some filters, maybe? I saw this on your code: type2ploidy[GT_HET_AA] = 1. So, does this mean that for nHets you are also considering this for calculating heterozygosity? This could explain why the nHomA and nHets from both scripts do not match, but only the nHomR.

**Comment by pd3** [comment]
Well, the only command you show is `vcftools -remove-indels`, you talk about a script (which bcftools is not, but vcf-stats from vcftools is) and now you mention `bcftools -stats` which does not exist. Perhaps you meant `bcftools stats` and the corresponding source code in vcfstats.c.

The short answer is that unless you use the `-f`,`-i` or `-e` options, the program does not do any filtering. If you can provide a small test case which narrows down the problem and highlights the difference between the expected and observed numbers, then it is worth another look to rule out a potential bug.
