### ISSUE TITLE
Add Filter per sample

### ISSUE THREAD

**Issue by awitney** [samtools/bcftools#1226]
Hi,

is it possible to add a FILTER field within FORMAT per sample?

thanks

adam

**Comment by pd3** [comment]
Only by transferring from another VCF or a tab-delimited file using `bcftools annotate` I am afraid. One can also set GT to missing using either `bcftools filter` or `bcftools +setGT`. Can you describe what exactly you need? It may be possible to add this functionality.

**Comment by awitney** [comment]
I was trying to filter the sites like this on a multi sample vcf file

`bcftools filter -S . -s LowQual -g3 -G10 -m + -e '%QUAL<30 || FORMAT/DP<4' calls.vcf.gz`

which adds a FILTER for the site as a whole, but it would be useful to see which particular samples where specificaly filtered, so that i could query like this:

`bcftools query -H -f '%POS [ %FILTER][ %GT][ %DP:%ADF:%ADR]' calls.vcf.gz`

thanks

**Comment by pd3** [comment]
The manual page provides an example how to do this:
```
QUAL>10 |  FMT/GQ>10   .. true for sites with QUAL>10 or a sample with GQ>10, but selects only samples with GQ>10
QUAL>10 || FMT/GQ>10   .. true for sites with QUAL>10 or a sample with GQ>10, plus selects all samples at such sites
```

**Comment by pd3** [comment]
This is because your output format is confusing. The FILTER is set per-row, not per-sample, and it is the string in the FILTER column. Look in the VCF using `bcftools view` or `zless`.

The commands work as expected:
```
$ bcftools query -f '%POS\t%FILTER[\t%GT:%DP]\n' calls.vcf.gz
37132	.	1:3	0:130

$ bcftools filter -S . -s LowQual -g3 -G10 -m + -e 'FORMAT/DP<4' calls.vcf.gz | bcftools query -f '%POS\t%FILTER[\t%GT:%DP]\n' 
37132	LowQual	.:3	0:130
```
