### ISSUE TITLE
Error: incorrect AN/AC count at x:8946489

### ISSUE THREAD

**Issue by diebleu** [samtools/bcftools#1229]
When attempting to try to parse files based off of ID, I am recieving the following error:
incorrect AN/AC count at x:8946489
I have attempted to read the line, in addition to see if the AN/AC count needed to be updated. I haven't been successful with either.

**Comment by pd3** [comment]
I don't understand the question, sorry. Best if you give a complete example, showing the full command line. To recalculate AN/AC counts, the plugin `+fill-tags` can be used http://samtools.github.io/bcftools/howtos/plugin.fill-tags.html

**Comment by diebleu** [comment]
Hi
This is what I have currently:
# To download to current working directory:
# cp https://storage.googleapis.com/gnomad-public/papers/2019-sv/gnomad_v2.1_sv.sites.vcf.gz .
# BCFtools was used to sort and parse the files
# To view SV IDs:
# /opt/tools/bcftools/bin/bcftools query -f '%ID\n' gnomad_v2.1_sv.sites.vcf.gz
# To parse the files:
# /opt/tools/bcftools/bin/bcftools stats -I gnomad_v2.1_sv.sites.vcf.gz > svID.txt
When I view the SV IDs, I can see them, but am unable to parse

**Comment by pd3** [comment]
The AC values at that site is bigger than AN
```
$ bcftools query gnomad_v2.1_sv.sites.bcf -r X:8946489 -f'%POS\t%REF\t%ALT\t%AC\t%AN\n'
8830256	N	<DEL>	1	16120
8911999	N	<DUP>	1	16120
8946489	N	<INS>	16751	15354
```
and the program cannot calculate the allele frequency bin for some stats. A quick work around is to remove the incorrect tag
```
bcftools annotate -x INFO/AC,AN  gnomad_v2.1_sv.sites.bcf -r X:8946489 | bcftools stats
```
Note that the option `-I` is useless here because all sites have an ID.

**Comment by diebleu** [comment]
> The AC values at that site is bigger than AN
> 
> ```
> $ bcftools query gnomad_v2.1_sv.sites.bcf -r X:8946489 -f'%POS\t%REF\t%ALT\t%AC\t%AN\n'
> 8830256	N	<DEL>	1	16120
> 8911999	N	<DUP>	1	16120
> 8946489	N	<INS>	16751	15354
> ```
> 
> and the program cannot calculate the allele frequency bin for some stats. A quick work around is to remove the incorrect tag
> 
> ```
> bcftools annotate -x INFO/AC,AN  gnomad_v2.1_sv.sites.bcf -r X:8946489 | bcftools stats
> ```
> 
> Note that the option `-I` is useless here because all sites have an ID.

After doing this, I still recieved the error. Is there a better way to be able to parse them by ID type into flat files?Thanks

**Comment by pd3** [comment]
Well, check what is coming out of the first `bcftools annotate -x` command. If it does what it is supposed to do, there can't be any INFO/AC or INFO/AN tags and `stats` has no reason to complain. If you still believe it is a problem with the program and not the way you are using it, please include the version you are using (`bcftools --version`), the full command and the exact error you are getting. 

Regarding the record type, you'd need to use run the stats separately for each type. For this, the filtering `-i` option could be used, e.g
```
bcftools stats nomad_v2.1_sv.sites.bcf -i 'SVTYPE="DEL"' 
```

**Comment by Nheyer** [comment]
@pd3  This seems to be an issue when pulling out samples using the -s flag as well introduced sa the INFO/AN is not updated when sub-sampleing
