### ISSUE TITLE
HWE assumption

### ISSUE THREAD

**Issue by crougeux** [samtools/bcftools#1234]
Hi, 
I am running a BCFtools pileup and call pipeline. While I was interested by the -G option, I then realize that I may have undesired effects of HWE assumptions in my dataset. As I might be interested by slightly deviations from HWE, I am wondering of HWE is tested when -G _population_map_  is set on? If this is an exact test, what is the threshold? Is the threshold set by default and so, is any deviation discarded from the dataset?
Very looking forward to have a bit more understanding about what this option is doing.
Thanks!

**Comment by pd3** [comment]
HWE is not explicitly tested, it is only used to estimate genotype frequencies. Say you do variant calling in the context of 1000 samples, then observing GT=0/0 in 999 samples and 1/1 in the remaining sample is less likely than observing 0/1 in that sample. For the exact calculation see here http://samtools.github.io/bcftools/call-m.pdf, the -G groups just set a context for each sample.
