### ISSUE TITLE
Expanding gvcf blocks

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#1235]
Hello,

I am using convert gvcf2vcf to expand gvcf blocks. 
However, doing so doesn't carry on the depth information, nor GQ 

```
Chrom_3 410     .       A       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 411     .       T       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 412     .       A       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 413     .       G       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 414     .       A       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 415     .       T       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0
Chrom_3 416     .       A       <*>     0       .       .       GT:GQ:MIN_DP:PL 0/0:1:0:0,0,0

```

I would have expected it would take the gVCF values for those sites. Is there a reason it's not the case?

What I am trying to do is to count the number of bases in my gVCF that pass a GQ and DP threshold. Obviously, doing it directly on the gVCF doesn't return the correct number because reference blocks are not expanded. 

Of course one can do something like this but I am just curious.

```
bcftools view -i 'GQ >= 15' ../D2A1.g.vcf.gz|bcftools view -i 'DP >= 10'|bcftools convert -f ../A.fasta --gvcf2vc|grep -v "#"|wc -l
```

**Comment by pd3** [comment]
I don't understand what you expect the program to do, gvcf records are expanded as is and all the INFO and FORMAT fields are preserved.

Anyway, for your task you want to use `bcftools query -f'%POS %END\n'`
http://samtools.github.io/bcftools/bcftools.html#query
