### ISSUE TITLE
 Linkage_pruning in BCFtools+prune:phased or unphased VCF input file?

### ISSUE THREAD

**Issue by aremkh** [samtools/bcftools#1237]
Dear Developers and Colleagues,
I would like to thank you for updating the list. 
I am wondering if the LD pruning method applied in bcftools+prune plugin required the input VCF file to be phased or alternatively unphased VCF files still can be used?

Many thanks in advance
-l, --max-LD R2 remove sites with r2 bigger than R2 within the -w window

**Comment by pd3** [comment]
The program works with unphased data and if the genotypes are phased, the phase is ignored.

**Comment by aremkh** [comment]
Thanks for your response!
