### ISSUE TITLE
Feature request for bcftools +split

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1240]
I have noticed that bcftools +split now can also split across sample subsets, which is cool. I find the way this happens a little bit cumbersome though. Ideally, I would have envisioned a `-S` option taking a file with two columns, with the first column the name of the sample that we plan to extract, and the optional second column (separated by a tab) indicating the prefix of the output file that sample is supposed to end in. That is, for example:
```
NA06984	CEU
NA06985	CEU
NA06986	CEU
NA06989	CEU
NA18486	YRI
NA18488	YRI
NA18489	YRI
HG00403	CHS
HG00404	CHS
NA18939	JPT
```
Should request to create four VCFs, CEU.vcf, YRI.vcf, CHS.vcf, and JPT.vcf such that CEU.vcf contains the first four samples, YRI.vcf the three subsequent samples, CHS.vcs the third to last and second to last, and JPT.vcf the last sample. As a plus, omitting the second column could resort to creating single sample VCFs limiting to the listed samples (similarly to `bcftools view -S FILE | bcftools +split`). This design would be much easier to implement scatter and gather workflows in cloud pipelines, if that was the intended goal. It should not be hard to re-implement init_subsets() this way using khash to track set->fname strings. It would also solve the problem of allowing commas in the sample names.

An example of how this could be used would be with 1000 Genomes project data, by downloading population file `ftp://ftp.ncbi.nlm.nih.gov/hapmap/phase_3/relationships_w_pops_051208.txt` which contains samples and population assignments in two separate column.

**Comment by pd3** [comment]
This is now done. The feature is available via the new `-G` option. As described in the usage page, the file can have up to three columns to allow sample renaming similarly to `-S`, the file name comes as last to make it consistent and `-` indicated no sample renaming. Please try it out and let me know in case of problems

**Comment by freeseek** [comment]
I just tried it and it works great! I still think it was more appropriate to have the 2nd and 3rd column names swapped as I think renaming is a secondary feature, while I understand why it is important in your trio scenario. My original idea was to have this work well with WDL for scatter/gather purposes and in WDL you can easily output Nx2 table maps while having to output an Nx3 table will require an extra bash line. Regardless, this is much appreciated and I like the flexibility of having two options to split in groups. Thank you!

**Comment by pd3** [comment]
I agree swapping the two would have been better, but don't want to break backward compatibility. The dash `-` can be added by piping through awk, for example, so hopefully should not be an unsurmountable problem for anyone.
