### ISSUE TITLE
Feature request: consensus IUPAC codes for insertions

### ISSUE THREAD

**Issue by yanwang271** [samtools/bcftools#1241]
Hello,

I am using ```bcftools consensus``` to get the consensus sequence in IUPAC code for the region of interest. In this region, there is one insertion and the genotype of my sample is "1/2". The sequences of the two ALT alleles are in different length. My command is:
```
samtools faidx ref.fa chrX:XXXX-XXXX | bcftools consensus -I -o out.fa sample.vcf.gz -c liftover.txt --sample sample_name
```
In the output, it seems that only the first ALT alleles was inserted into the reference.

Is there something wrong in my command? What should I do to apply both of the ALT alleles to the reference sequence?

**Comment by pd3** [comment]
I am assuming you'd like the program to do the following: take the length of the shorter insertion, create IUPAC codes based on that and then add the remaining bases. This is not currently possible although would not be too difficult to add. I'll mark this as a feature request.

**Comment by yanwang271** [comment]
Yes, that is what I assumed bcftools consensus would do. Thanks for your response.

**Comment by pd3** [comment]
Thank you for the issue, this is now supported. Please try it out and let me know in case of problems.
