### ISSUE TITLE
converting 23andme v5 format to VCF format

### ISSUE THREAD

**Issue by jkotl0327** [samtools/bcftools#1243]
Hello,
I downloaded your source code (in mac terminal, bash shell) using the simple copy-paste command you offered. I then pointed the environment label to the proper location by copying and pasting the command on your website. Then I entered your command to convert my 23andme file into VCF format: 'bcftools convert --tsv2vcf input.tab.gz -f ref.fa -s Jeremy -Ob -o JeremyDNA.bcf'
At this point I got: 'bcftools: command not found'
What should I do? I have attached 3 screenshots of everything I did below.
Thank you.
<img width="1439" alt="Screen Shot 2020-06-14 at 10 32 40 PM" src="https://user-images.githubusercontent.com/66458931/84612592-18ed9080-ae8f-11ea-8487-3eff9bc7f820.png">
<img width="1440" alt="Screen Shot 2020-06-14 at 10 32 52 PM" src="https://user-images.githubusercontent.com/66458931/84612593-18ed9080-ae8f-11ea-8dae-ba224b579a1b.png">
<img width="1439" alt="Screen Shot 2020-06-14 at 10 33 14 PM" src="https://user-images.githubusercontent.com/66458931/84612594-19862700-ae8f-11ea-85bd-3413e985ec62.png">

**Comment by freeseek** [comment]
You have to copy the bcftools binary inside a directory in your binary path or, alternatively, invoke the command as `./bcftoools` rather than as `bcftools` while making sure it is located in the same directory where you are running the shell command

**Comment by pd3** [comment]
Also note that the command `export BCFTOOLS_PLUGINS` must have the proper directory set. You can't just blindly copy and paste it, unless the literal path '/path/to/bcftools/plugins' exists.
