### ISSUE TITLE
bcftools produces seg fault with consensus command

### ISSUE THREAD

**Issue by JacobPorter** [samtools/bcftools#1245]
[var.vcf.gz](https://github.com/samtools/bcftools/files/4788211/var.vcf.gz)
[1035377.4.fna.gz](https://github.com/samtools/bcftools/files/4788216/1035377.4.fna.gz)
[var.vcf.gz.tbi.gz](https://github.com/samtools/bcftools/files/4788218/var.vcf.gz.tbi.gz)

1. Fastq data from the SRA read archive was downloaded with accession SRR10961160.
2. This data was aligned to the given Yersinia pestis genome with Bowtie2 2.2.9.
3. FreeBayes v1.3.2-1-gabab37f was run on the alignment files.
4. bcftools was used with the following command (with both versions 1.9 and 1.3):
bcftools consensus -c chain -f 1035377.4.fna var.vcf.gz > consensus
5. A segmentation fault was produced.

Attached are data files that were used to produce the result.
bgzip version 1.9 was used for var.vcf.gz

**Comment by pd3** [comment]
It should work now, thank you for the bug report.
