### ISSUE TITLE
if samtools can useRNA-Seq to calculate the SNP expression in VCF files.

### ISSUE THREAD

**Issue by Trandamere** [samtools/bcftools#1248]
Hi：
I want to know if samtools can use RNA-Seq to calculate the SNP expression in VCF files.

**Comment by pd3** [comment]
If I understand the question correctly, you probably want to determine the number of reference vs alternate bases at a site. This can be done by adding the FORMAT/AD field during variant calling  `bcftools mpileup -a FORMAT/AD`. See also http://samtools.github.io/bcftools/howtos/variant-calling.html
