### ISSUE TITLE
output from `bcftools csq` with multiple positions

### ISSUE THREAD

**Issue by MWendorff** [samtools/bcftools#1251]
I used bcftools csq on my dataset and in most cases the output is quite easy to interpret, but for example the following line I do not understand completely. For which cases are the entries 1855T>1854A and 1855T>1856A relevant? 

9	132298298	9_132298298_T_C	T	C	1820	.	AF=0.156939;AQ=1820;BCSQ=missense|SETX|ENST00000436441|protein_coding|-|97T>97A|132298298T>C,*missense|SETX|ENST00000224140|protein_coding|-|1855T>1855A|132298298T>C,@132326354,missense|SETX|ENST00000224140|protein_coding|-|1855T>1854A|132298298T>C,missense|SETX|ENST00000224140|protein_coding|-|1855T>1856A|132298298T>C,@132331321

**Comment by MWendorff** [comment]
I figured it out: For some individuals this mutation occurs together with an inframe-mutation. Unfortunately you have to lookup the corresponding mutation by hand.

**Comment by pd3** [comment]
The command `bcftools query` can be  used to visualize per-sample consequences, the documentation gives some examples 
http://samtools.github.io/bcftools/bcftools-man.html#csq
