### ISSUE TITLE
bcftools annotate error

### ISSUE THREAD

**Issue by carladosanjos** [samtools/bcftools#1256]
Dear author

 I am trying to add the t_alt_count and t_ref_count from a annotation maf file (tab-delimited) into a vcf without success as follows. By following the instructions [http://samtools.github.io/bcftools/bcftools.html#annotate](http://samtools.github.io/bcftools/bcftools.html#annotate), my annotation file header looks like this:

```
##INFO=<ID=t_alt_count,Number=1,Type=Integer,Description="Yet another header line">
##INFO=<ID=t_ref_count,Number=1,Type=Integer,Description="Example header line">

#Sample annotation file with columns CHROM,FROM,TO,t_alt_count,t_ref_count
chr1	22601514	22601514	4	6
chr1	27749048	27749049	3	4
```

Then,
`bcftools annotate -a annotation.maf -c "t_alt_count, t_ref_count" file.vcf`

Error:

`The tag "t_alt_count" is not defined in annotation.maf`

I would like to know where the "t_alt_count" is missing in the annotation.maf.  Is there a tab-limited annotation file template anywhere?

Thanks

**Comment by pd3** [comment]
The command line seems incorrect, shouldn't it be `-c CHROM,FROM,TO,t_alt_count,t_ref_count` ?

**Comment by carladosanjos** [comment]
Hi pd3,

This command has only worked when I've found out what was causing the error:

The vcf file must contain the header below, otherwise it will not work.
`##INFO=<ID=t_alt_count,Number=1,Type=Integer,Description="Yet another header line">
##INFO=<ID=t_ref_count,Number=1,Type=Integer,Description="Example header line">` 

So, the tag must be defined in both, the vcf file and the annotation file. It would have been more informative if the log error indicated that the tag was actually missing in the vcf file. 

My suggestion is to change this log in order to specify the exact file where the tag is missing.

Thanks for your help anyway.

Best wishes

**Comment by golrokh51** [comment]
Hi, 
I have similar problem and still didn't solve it. 
I am using `bcftools/1.10.2` 

This is my header file:

    ##INFO=<id=strand,number=1,type=String,description="strand">
    ##INFO=<id=gene_id,number=1,type=Integer,description="gene_id">
    ##INFO=<id=locus,number=1,type=String,description="locus">
    ##INFO=<id=locus_tag,number=1,type=String,description="locus_tag">
    ##INFO=<id=protein_product,number=1,type=String,description="protein_product"> 
    ##INFO=<id=length,number=1,type=Integer,description="length">
    ##INFO=<id=protein_name,number=1,type=String,description="protein_name">

This is the first two lines of my annotation file (sorted, bgzipped and tabix indexed with `tabix -s 1 -b 2 -e 3 annotation_proteins_85_22812_chr_sorted.tab.gz` ):

    #CHROM	FROM	TO	strand	gene_id	locus	locus_tag	protein_product	length	protein_name
    chr1	252392	322063	-	100856150	ENPP1	-	XP_003638833.1	916	ectonucleotide pyrophosphatase/phosphodiesterase family member 1 isoform X2

This is my command line :
` bcftools annotate -a annotation_proteins_85_22812_chr_sorted.tab.gz -h header.hdr -c CHROM,FROM,TO,-,gene_id,locus,-,protein_product,-,protein_name $f1 > $out`

and I get this error:
`The tag "gene_id" is not defined in annotation_proteins_85_22812_chr_sorted.tab.gz`

Could you please help me with this?

**Comment by pd3** [comment]
The first version of the header which does not respect the case ("id" instead of "ID" and "type" instead of "Type") results in rather uninformative error messages such as
```
[W::bcf_hdr_register_hrec] An INFO field has no Type defined. Assuming String
[W::bcf_hdr_register_hrec] An INFO field has no Number defined. Assuming '.'
```
and this should be improved in htslib.

However, after fixing these errors in the `header.hdr` file, the annotation works alright for me.
