### ISSUE TITLE
A multi-allelic site recognized as a SNP and INDEL!

### ISSUE THREAD

**Issue by dwuab** [samtools/bcftools#1257]
bcftools 1.10.2 on Centos 7
I have the following record in my vcf file:
```
chrY    5916561 rs9786162       A       T,AT    99642.5 PASS    AC=304,12;AF=0.821,0.0272;AN=390;BaseQRankSum=-0.589;ClippingRankSum=-0;DB;DP=4019;ExcessHet=-0;FS=0.873;InbreedingCoeff=0.6543;MLEAC=489,12;MLEAF=0.832,0.0204;MQ=48.65;MQRankSum=0;QD=37.79;ReadPosRankSum=0.29;SOR=0.478;VQSLOD=4.42;culprit=DP
```
This record will show up when I type `bcftools view -v snps` or `bcftools view -v indels`. Moreover, `bcftools stats` will report there is 1 SNP, 1 indel, but only 1 record.
This is really confusing. Is this intended or a bug?

**Comment by pd3** [comment]
I don't understand the confusion, clearly the site has both a SNV and an indel. If you want to see only SNVs but no indels, the filtering expressions can be used:
```
# show sites with SNVs only
$ bcftools view -H -i'type="SNP"' test.vcf
1	3000151	.	C	A	.	.	.

# show sites with SNVs
$ bcftools view -H -i'type~"SNP"' test.vcf
1	3000000	.	C	T,CCG	.	.      .
1	3000151	.	C	A	.	.	.

```
