### ISSUE TITLE
adding DP to FORMAT from INFO

### ISSUE THREAD

**Issue by gsd050** [samtools/bcftools#1258]
Hi
I have multiple vcf files generated from single samples using samtools mpileup ‘-q 1 -C 50 -m 2 -F 0.002 -d 1000
The vcf files look like this

**#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | M46
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
NC_028351.1 | 4297 | . | T | C | 80.5 | . | DP=4;VDB=9.421102e-03;AF1=1;AC1=2;DP4=0,0,4,0;MQ=60;FQ=-39 | GT:PL:GQ | 1/1:113,12,0:21
NC_028351.1 | 4310 | . | C | T | 80.5 | . | DP=4;VDB=9.421102e-03;AF1=1;AC1=2;DP4=0,0,4,0;MQ=60;FQ=-39 | GT:PL:GQ | 1/1:113,12,0:21
NC_028351.1 | 4350 | . | T | C | 116 | . | DP=8;VDB=8.616184e-02;AF1=1;AC1=2;DP4=0,0,4,1;MQ=60;FQ=-42 | GT:PL:GQ | 1/1:149,15,0:27**

I want to merge these files and then filter on basis of DP later on.
The INFO tags have DP while FMT doesnt. So merging these files by **bcftools merge**  I loose individual samples DP info. 

So i want to know if there is away to merge them without loosing the individual DP. Or if there is a way to add DP from INFO to FORMAT before merging?

**Comment by pd3** [comment]
This is an old version of samtools, the recommended workflow is outlined here http://samtools.github.io/bcftools/howtos/variant-calling.html. Per sample depth can be added with `bcftools mpileup -a FORMAT/DP`. Otherwise, if you can't re-create the files, you'll have to extract the INFO/DP annotation (`bcftools query -f'%CHROM\t%POS\t%DP\n'`) and annotate sample the column using `bcftools annotate`.

**Comment by gsd050** [comment]
Hi Danecek,
I was trying to escape calling snps again with samtools. So, I tried extracting the info with bcftools earlier, but wasnt able to annotate the DP to FORMAT using following 
 ** bcftools annotate -a M1.tab.gz -c CHROM,POS,REF,ALT,INFO/DP:=FORMAT/DP M1_sorted.vcf.gz
  bcftools annotate -a M1.tab.gz -c CHROM,POS,REF,ALT,FMT/INFO/DP:=FORMAT/DP M1_sorted.vcf.gz**
If you could find out what i have been doing wrong in the code, and suggest the right code

**Comment by pd3** [comment]
I created an example here http://samtools.github.io/bcftools/howtos/annotate.html
