### ISSUE TITLE
bcftools annotate -c -TAG fails when source and target VCF have the same samples

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1259]
If you generate the two following VCFs:
```
(echo "##fileformat=VCFv4.1"
echo "##FORMAT=<ID=GT,Number=1,Type=String,Description=Genotype>"
echo "##contig=<ID=20,length=63025520>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1\tSAMPLE2"
echo -e "20\t20202020\t.\tC\tG\t.\t.\t.\tGT\t0/1\t./.") | bgzip > target.vcf.gz
tabix target.vcf.gz

(echo "##fileformat=VCFv4.1"
echo "##FORMAT=<ID=GT,Number=1,Type=String,Description=Genotype>"
echo "##contig=<ID=20,length=63025520>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1\tSAMPLE2"
echo -e "20\t20202020\t.\tC\tG\t.\t.\t.\tGT\t0|1\t0/0") | bgzip > source.vcf.gz
tabix source.vcf.gz
```

The first command gives one output:
```
$ bcftools annotate -a source.vcf.gz -c -FMT/GT target.vcf.gz | bcftools view -H
20	20202020	.	C	G	.	.	.	GT	0|1	0/0
```
And the `-TAG` option is effectively ignored.

While the second command gives another output:
```
$ bcftools query -l target.vcf.gz | bcftools annotate -a source.vcf.gz -c -FMT/GT -S /dev/stdin target.vcf.gz | bcftools view -H
20	20202020	.	C	G	.	.	.	GT	0|1	./.
```
Here the `-TAG` option is honored and the missing genotype is left as missing.

The issue arises from the following snippet of code in function `vcf_setter_format_gt()` in file `vcfannotate.c`:
```
    if ( !args->sample_map )
        return bcf_update_genotypes(args->hdr_out,line,args->tmpi,nsrc);
```
Whenever `args->sample_map` is not set, this makes the function return and ignore the rest of the code in the function where `col->replace==REPLACE_NON_MISSING` and `col->replace==REPLACE_MISSING` are handled appropriately instead.

Unfortunately it does not seem very obvious to me how to best fix this bug. The offending snippet of code is there for efficiency and maybe this added efficiency should be just dropped when the `-TAG` option is used.

**Comment by pd3** [comment]
This is now fixed, than you for the bug report.
