### ISSUE TITLE
Compile fails on latest version

### ISSUE THREAD

**Issue by shaze** [samtools/bcftools#1260]
I've just tried to compile the latest version of bcftools (commit 365d117a9a83a912d1e461ba75695bdfaf6aa142) and ran into the following compile error. I'm using gcc 8.3.2 and a CentOS 7 system.

```
vcfmerge.c: In function ‘main_vcfmerge’:
vcfmerge.c:2722:36: error: ‘BCF_SR_ALLOW_NO_IDX’ undeclared (first use in this function); did you mean ‘BCF_SR_REQUIRE_IDX’?
         bcf_sr_set_opt(args->files,BCF_SR_ALLOW_NO_IDX);
                                    ^~~~~~~~~~~~~~~~~~~
                                    BCF_SR_REQUIRE_IDX
vcfmerge.c:2722:36: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:136: vcfmerge.o] Error 1
```

I checked out the previous commit `f27f849a54c5a455fad427ae14fa8ef28f22d144` and it compiles, installs and runs OK. Not sure if I did something wrong in the configure step that provoked this or if it's a problem in the code

**Comment by pd3** [comment]
Also HTSlib needs to be updated, please see here http://samtools.github.io/bcftools/howtos/install.html

**Comment by shaze** [comment]
Sorry about that yes that was the problem -- thanks for the prompt response
