### ISSUE TITLE
Conda dependency doesn't exist

### ISSUE THREAD

**Issue by sheerun** [samtools/bcftools#1265]
Hello,

It seems it's impossible to install 10.x versin of bcftools from conda because it lists `gsl >=2.5,<2.6.0a0` as dependency, and there is no gsl 2.5:

```
conda search gsl
Loading channels: done
# Name                       Version           Build  Channel
gsl                            2.2.1      h0743c53_2  pkgs/main
gsl                            2.2.1      h0c605f7_3  pkgs/main
gsl                            2.2.1      h8267d9d_2  pkgs/main
gsl                              2.4      h14c3975_4  pkgs/main
gsl                              2.4      h1bed415_3  pkgs/main
```

Coul you please fix it? Thank you :)

**Comment by jmarshall** [comment]
This is a problem with your conda installation, not bcftools — so you will have better luck asking people who know about conda. In this case, the problem is probably that you are not using the `conda-forge` channel [as required by bioconda](https://bioconda.github.io/user/install.html#set-up-channels).

**Comment by sheerun** [comment]
Hmm. OK, I thought it's you who publish bcftools on bioconda

**Comment by sheerun** [comment]
btw. with these channels installed it install bcftools 1.8 which is even worse..

**Comment by sheerun** [comment]
Hmm. OK it seems to work with fresh miniconda installation. Anaconda3 doesn't work

**Comment by jmarshall** [comment]
> with these channels installed it installs bcftools 1.8 which is even worse..

Yes, that's a known ongoing bioconda disaster (cf conda/conda#9905). You need to bring this up with Bioconda. In the meantime, use `conda install bcftools==1.10.2` or similar.
