### ISSUE TITLE
bcftools filter -e  'GT="het"' recognize GT 2/2 as heterozygous

### ISSUE THREAD

**Issue by esctrionsit** [samtools/bcftools#1268]
hi,

When i am using `-e 'GT="het"'` to filter heterozygous variation, it seems to recognize 2/2 as heterozygous.

Is that a bug? Or I just misunderstood the meaning of `-e 'GT="het"'`?

Here are the command line return:
![图片](https://user-images.githubusercontent.com/25820435/88305731-6c7bb580-cd3c-11ea-9cef-b0a0f0a270f5.png)

Thanks.

**Comment by pd3** [comment]
It's the other way around isn't it? You asked the program to exclude heterozygous genotypes which `2/2` is not (`-e` was used in your command, not `-i`).

**Comment by pd3** [comment]
Sorry, was too rash, did not notice at the first glance there were two commands in your screenshot. The explanation is that your file contains multiple samples (guessing from the `-s` option) and some of the samples are heterozygous at that site. The filtering is performed prior to removing the other samples. You should split this in two commands
```
bcftools view file.vcf -s sample -Ou | bcftools view -e 'GT="het"'
```

**Comment by SunWinner01** [comment]
Hello, sorry to bother you. Currently, I’m using the command `bcftools view -m 2 -M 2 --threads 4 -Ob -o referencePanel.22.bcf referencePanel.vcf.gz` to process my data. My file `referencePanel.vcf.gz` contains a combination of SNPs and structural variant (SV) data, with SV information included among the SNPs. However, after running this command, I noticed that there was no change in the resulting file. I’d like to ask if this is normal, as I have the following questions:

1. Does `bcftools view -m 2 -M 2` have no effect on SV data?
2. What kind of SNPs would not pass the filter using the command `bcftools view -m 2 -M 2`?
3. In my file, the REF and ALT columns of the SNP data are composed solely of one of the letters A, G, C, or T.

These are all my questions. I look forward to your reply! Thank you so much, and I wish you all the best.    @pd3

**Comment by SunWinner01** [comment]
Hello, sorry to bother you. Currently, I’m using the command `bcftools view -m 2 -M 2 --threads 4 -Ob -o referencePanel.22.bcf referencePanel.vcf.gz` to process my data. My file `referencePanel.vcf.gz` contains a combination of SNPs and structural variant (SV) data, with SV information included among the SNPs. However, after running this command, I noticed that there was no change in the resulting file. I’d like to ask if this is normal, as I have the following questions:

1. Does `bcftools view -m 2 -M 2` have no effect on SV data?
2. What kind of SNPs would not pass the filter using the command `bcftools view -m 2 -M 2`?
3. In my file, the REF and ALT columns of the SNP data are composed solely of one of the letters A, G, C, or T.

These are all my questions. I look forward to your reply! Thank you so much, and I wish you all the best. @esctrionsit
