### ISSUE TITLE
bcftools norm --rm-dup id

### ISSUE THREAD

**Issue by cindywen96** [samtools/bcftools#1269]
My input vcf file has biallelic SNPs only, some of them possibly with duplicate IDs (in rsID format). I'm not sure about chr/pos/ref/alt. I wonder is there some function filtering out duplicate SNPs by id column only? I'm looking for something like bcftools norm --rm-dup id. In the documentation of "collapse", "id" is only available for bcftools merge. Thank you!

**Comment by pd3** [comment]
No, this is not possible, duplicate removal works only with chr+pos and ref+alt.
