### ISSUE TITLE
bcftools reheader format

### ISSUE THREAD

**Issue by cindywen96** [samtools/bcftools#1271]
Hi! I was using "bcftools reheader -s ${new_names.txt} ${input} -o ${output}" to change sample names. I got a few questions:
1. why is there no -O b/u/z/v conversion like the other commands?
2. when my input is in BCF (piped from other bcftools commands with -Ou), I couldn't output a VCF format file.
It seems like the output can only be in the same format as the input, in terms of VCF/BCF and bgzipped or not. I was wondering if the reheader command could have more flexible format conversions like the other ones?

**Comment by pd3** [comment]
The observation is correct, reheader does not support conversion between formats. This is to make the reheader command fast, it can run without recompressing the data. You can pipe the output through `bcftools view` if you need to convert between formats, for example
```
bcftools reheader ... | bcftools view -Ov test.vcf
```
