### ISSUE TITLE
bcftools consensus segmentation fault with `--absent` + `--iupac-codes`

### ISSUE THREAD

**Issue by brantfaircloth** [samtools/bcftools#1273]
Good morning,

I know the `--absent` flag is newly added to the code (and much appreciated), but I've run into a segfault when combining `--absent` with `-I, --iupac-codes`.

I've tried to track this down to a problematic locus. However, when running the locus where `bcftools` hits the segfault on its own, everything behaves normally.  I've attached the bcf file and fasta file that i was using to generate the consensus - FYI, i had to add `.txt` to the fasta and `.gz` to the bcf to get github to accept the upload.

One potentially important thing to note is that the bcf file contains *all* sites, because of our use-case. So:
```
bcftools consensus  -f contigs.fasta --absent '.' calls.norm.flt-indels.Q20.DP10.bcf > test-1.fasta
```
runs correctly, while:
```
bcftools consensus  -f contigs.fasta -I --absent '.' calls.norm.flt-indels.Q20.DP10.bcf > test-2.fasta
```
hits the segfault.  I'm on:

* bcftools commit 7cd83b71405c993d2f81fb91126abe3e44344398
* CentOS 7
* Linux 3.10.0-693.11.6.el7.x86_64
* gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

[calls.norm.flt-indels.Q20.DP10.bcf.gz](https://github.com/samtools/bcftools/files/5002057/calls.norm.flt-indels.Q20.DP10.bcf.gz)
[contigs.fasta.txt](https://github.com/samtools/bcftools/files/5002060/contigs.fasta.txt)

Please let me know if you need any other files/information - I'm happy to provide those.

Thanks very much!
-b

**Comment by pd3** [comment]
Thank you for the bug report, this is now fixed.
