### ISSUE TITLE
vcfutils.pl running problem

### ISSUE THREAD

**Issue by shiyi-pan** [samtools/bcftools#1274]
hi , I run the vcfutils.pl in the pipe like this:

$SAMTOOLS mpileup -C50 -uf Gmax_275_v2.0.fa Z_516_sorted.bam | $BCFTOOLS/bcftools view | $BCFTOOLS/vcfutils.pl vcf2fq -d 10 -D 100 -Q 3 | gzip > diploid.fq.gz

Gmax_275_v2.0.fa is my reference genome and I got some messages in my log file and my result file 'diploid.fq.gz' is empty:

Use of uninitialized value $q in addition (+) at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 539, <> line 12576562.
Use of uninitialized value $q in numeric lt (<) at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 529, <> line 12576591.
Use of uninitialized value $q in addition (+) at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 539, <> line 12576591.
Use of uninitialized value $q in numeric lt (<) at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 529, <> line 12576617.
substr outside of string at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 557, <> line 51455434.
substr outside of string at /ds3512/home/panyp/ruanjian/bcftools-1.3.1/vcfutils.pl line 557, <> line 51455434.

my bamtools and bcftools is 1.3.1 .can you tell my how I avoid the problem. Do I need to Preprocessing my files? thank you.

**Comment by pd3** [comment]
The vcfutils.pl script is not supported any longer, please see here for the current recommendation http://samtools.github.io/bcftools/howtos/variant-calling.html

**Comment by sjfleck** [comment]
@pd3 I'm using vcfutils.pl vcf2fq in the same way that @shiyi-pan was trying. I don't want to keep using an unsupported tool if I can avoid it. What I'm struggling to find is something to replace the "vcfutils.pl vcf2fq" command. Does bcftools or samtools have a way to convert vcf to fastq? any help would be greatly appreciated. Thank you

**Comment by pd3** [comment]
There is the `bcftools consensus` http://samtools.github.io/bcftools/howtos/consensus-sequence.html or the new `samtools consensus` command. Would that help?

**Comment by AstridAlexAndersson** [comment]
> @pd3 I'm using vcfutils.pl vcf2fq in the same way that @shiyi-pan was trying. I don't want to keep using an unsupported tool if I can avoid it. What I'm struggling to find is something to replace the "vcfutils.pl vcf2fq" command. Does bcftools or samtools have a way to convert vcf to fastq? any help would be greatly appreciated. Thank you

I am having the exact same problem as @sjfleck and I do not see the solution anywhere. Where you able to fix this?
