### ISSUE TITLE
Filtering expressions for sample-specific DP4 values don't work

### ISSUE THREAD

**Issue by leowill01** [samtools/bcftools#1275]
I'm trying to filter some tumor-normal somatic mutation VCFs according to the following parameters:

1. No alt reads in the normal sample (i.e. normal DP4[2-3] == 0, OR normal AD == 0)
2. At least 1 alt read in both fwd/rev directions in the tumor sample (i.e. tumor DP4[2-3] > 0)

However, I'm running into problems because `bcftools` doesn't seem to be able to specify which sample to look at (normal or tumor) when evaluating the filter logic for the DP4 values.

I've tried this:

```zsh
bcftools view \
--include 'FORMAT/AD[0] == 0' \
"$GZVCF"
```

Which seems to work in excluding any variants with alt reads in the normal, but when I try to filter by the DP4 values ***only for the tumor sample***, the results still contain tumor variants that have a value of 0 for DP4[2] or DP4[3] (the 3rd and 4th values for the DP4 parameter, respectively). The following command:

```zsh
# include variants where sample 1 (the normal; sample index [0]) has no alt reads AND where sample 2 (the tumor; sample index [1]) has at least 1 alt read in both directions:
bcftools view \
--include 'FORMAT/AD[0] == 0 & (DP4[1:2] > 0 & DP4[1:3] > 0)' \
"$GZVCF"
```

Returns an empty VCF file (but with an intact header). This makes me think it's also applying the logic to the normal sample and basically filtering out every variant. However, it explicitly says it's looking for a sample index because if I try to run the following command without a sample index for the DP4 values:

```zsh
bcftools view \
--include 'FORMAT/AD[0] == 0 & (DP4[2] > 0 & DP4[3] > 0)' \
"$GZVCF"
```

, it returns the error:

```
> bcftools view \
> --include 'FORMAT/AD[0] == 0 & (DP4[2] > 0 & DP4[3] > 0)' \
> "$GZVCF"
The sample index is too large: 2
```

, which seems to directly contradict the DP4 expression example provided in the [Expressions](http://samtools.github.io/bcftools/bcftools.html#expressions) section of the bcftools manual:

> * array subscripts (0-based), "*" for any element, "-" to indicate a range. Note that for querying FORMAT vectors, the colon ":" can be used to select a sample and an element of the vector, as shown in the examples below
>
> [...]
>
> ```
> (DP4[0]+DP4[1])/(DP4[2]+DP4[3]) > 0.3
> ```

Any help would be great as I cannot get this to work.

**Comment by pd3** [comment]
Do you mean something like this?
```
$ cat test.vcf
##fileformat=VCFv4.2
##FORMAT=<ID=DP4,Number=4,Type=Integer,Description="">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="">
##contig=<ID=1>
##reference=ref.fa
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  normal  tumor
1   100 .   G   C   .   PASS    .   AD:DP4  10,0:5,5,0,0    10,2:5,5,1,1
1   101 .   G   C   .   PASS    .   AD:DP4  10,0:5,5,0,0    10,1:5,5,1,0

$ bcftools view -H test.vcf -i'AD[0:1]==0 && DP4[1:2]>0 && DP4[1:3]>0'
1	100	.	G	C	.	PASS	.	AD:DP4	10,0:5,5,0,0	10,2:5,5,1,1
```
The manual page shows more examples explaining how to specify a sample. You are probably using an older version of bcftools. Also make sure you have the latest version of bcftools from github, there were some bugs in filtering expressions fixed recently.
