### ISSUE TITLE
bcftools merge -R region limited to 2500 entries ?

### ISSUE THREAD

**Issue by andrewSharo** [samtools/bcftools#1277]
I'm running the following command

bcftools merge -0 -m none -O z --threads 20 -R GRCH38.regions.bed.gz file1.vcf.gz file2.vcf.gz > bcftools.merged.vcf.gz

My regions file has ~25,000 regions. However, I'm finding that the output vcf file stops at chr6 and contains exactly 2500 entries. Is there some limit on the number of regions in the region file? Is there another reason this would stop prematurely? It gives no informative error message, the only output is about old tbi files and vcf format:

[W::hts_idx_load2] The index file is older than the data file: /data/CIAPM-S/longranger/BC00302_longranger/outs/phased_variants.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /data/CIAPM-S/longranger/BC00302_longranger/outs/phased_variants.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /data/CIAPM-S/longranger/BC03503_longranger/outs/phased_variants.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /data/CIAPM-S/longranger/BC03503_longranger/outs/phased_variants.vcf.gz.tbi
[W::vcf_parse_format] FORMAT 'GL' is not defined in the header, assuming Type=String

Zipping or unzipping the bed regions file makes no difference. Curiously, I ran the same analysis with vcf-merge, and had no trouble, except that it takes 100 times longer. 

Best, Andrew

**Comment by pd3** [comment]
No, there is no limit like that. Any chance you could provide a reproducible test case to debug the problem?
