### ISSUE TITLE
run-roh.pl Warning: Could not determine the genetic map files [genmap/][.txt]

### ISSUE THREAD

**Issue by alig99** [samtools/bcftools#1280]
Hi,
I am trying to use the run-roh.pl script using genetic map files.
The option -m says to give a directory which I do genmap/  which contains impute2 files i.e. genetic_map_chr1_combined_b37.txt
Command used
run-roh.pl -i Roh_input -a Roh_input/1000GP-AFs/AFs.tab.gz -m genmap -M 100 -q 30 -n 100 -o Roh_output_params

bcftools annotate --rename-chrs Roh_output_params/chr-names.txt 'Roh_input/myfile.hc.vqsr.vcf.gz' -Ou | bcftools annotate -c CHROM,POS,REF,ALT,AF1KG -h Roh_input/1000GP-AFs/AFs.tab.gz.hdr -a Roh_input/1000GP-AFs/AFs.tab.gz -Ob -o Roh_output_params/myfile.hc.vqsr.bcf.part && mv Roh_output_params/myfile.hc.vqsr.bcf.part Roh_output_params/myfile.hc.vqsr.bcf

But I just get the ERROR  Warning: Could not determine the genetic map files [genmap/][.txt]

I can run the script without genetic map files, but I would really like to use genetic map files if possible.

Any help would be gratefully received,
Thanks alig99

**Comment by pd3** [comment]
Can you show the output of `ls -al genmap` please?

**Comment by alig99** [comment]
Hi,  this is the output of      ls -al genmap
total 121880
drwxrwxr-x  2 neuro     4096 Aug  6 09:16 .
drwxrwxr-x 10 neuro     4096 Aug 18 12:41 ..
-rwxr-x---  1 neuro  6813552 Sep 25  2014 genetic_map_chr10_combined_b37.txt
-rwxr-x---  1 neuro  6357243 Sep 25  2014 genetic_map_chr11_combined_b37.txt
-rwxr-x---  1 neuro  6151965 Sep 25  2014 genetic_map_chr12_combined_b37.txt
-rwxr-x---  1 neuro  5138675 Sep 25  2014 genetic_map_chr13_combined_b37.txt
-rwxr-x---  1 neuro  4057540 Sep 25  2014 genetic_map_chr14_combined_b37.txt
-rwxr-x---  1 neuro  3511911 Sep 25  2014 genetic_map_chr15_combined_b37.txt
-rwxr-x---  1 neuro  3513867 Sep 25  2014 genetic_map_chr16_combined_b37.txt
-rwxr-x---  1 neuro  2831582 Sep 25  2014 genetic_map_chr17_combined_b37.txt
-rwxr-x---  1 neuro  3846050 Sep 25  2014 genetic_map_chr18_combined_b37.txt
-rwxr-x---  1 neuro  1776710 Sep 25  2014 genetic_map_chr19_combined_b37.txt
-rwxr-x---  1 neuro  9798376 Sep 25  2014 genetic_map_chr1_combined_b37.txt
-rwxr-x---  1 neuro  3086646 Sep 25  2014 genetic_map_chr20_combined_b37.txt
-rwxr-x---  1 neuro  1669990 Sep 25  2014 genetic_map_chr21_combined_b37.txt
-rwxr-x---  1 neuro  1686715 Sep 25  2014 genetic_map_chr22_combined_b37.txt
-rwxr-x---  1 neuro 10975990 Sep 25  2014 genetic_map_chr2_combined_b37.txt
-rwxr-x---  1 neuro  8476265 Sep 25  2014 genetic_map_chr3_combined_b37.txt
-rwxr-x---  1 neuro  8006964 Sep 25  2014 genetic_map_chr4_combined_b37.txt
-rwxr-x---  1 neuro  8141057 Sep 25  2014 genetic_map_chr5_combined_b37.txt
-rwxr-x---  1 neuro  8798602 Sep 25  2014 genetic_map_chr6_combined_b37.txt
-rwxr-x---  1 neuro  6945309 Sep 25  2014 genetic_map_chr7_combined_b37.txt
-rwxr-x---  1 neuro  7219386 Sep 25  2014 genetic_map_chr8_combined_b37.txt
-rwxr-x---  1 neuro  5950834 Sep 25  2014 genetic_map_chr9_combined_b37.txt
-rw-rw----  1 neuro      441 Apr 10  2017 README.txt~

**Comment by alig99** [comment]
Hi,  I did delete the README.txt file, but unfortunately it made no difference.
Still got the same error,

**Comment by pd3** [comment]
Can you show the output of `ls -al genmap` again?

**Comment by pd3** [comment]
I just added a better error reporting, clearly your problem comes from not deleting `README~`, instead you probably attempted to delete a non-existent `README`. Yes, the heuristic could be improved, but it is easy enough to delete the offending file.

**Comment by alig99** [comment]
Thank you, much appreciated your help with this
