### ISSUE TITLE
bcftools filter the snps with R2>0.8, but the output of filtered.vcf file has much less than the info.filered snps

### ISSUE THREAD

**Issue by lovelymaoqin** [samtools/bcftools#1281]
bcftools filter the snps with R2>0.8, but the output of filtered.vcf file has much less than the info.filered snps

Not sure the reason.
When I check the original total.vcf.gz, there are lots of duplicated sites.They are in the same position, but have different alleles.  Is anyway not remove the duplicated sites automatically?

**Comment by pd3** [comment]
I don't understand the question and the statement "bcftools filter the snps with R2>0.8". What command did you run? If you believe it is a bug, please provide a small test case to reproduce the problem.
