### ISSUE TITLE
merge contains extra strings

### ISSUE THREAD

**Issue by tjwu** [samtools/bcftools#1283]
bcftools version is 1.9
This is the command.
bcftools merge Chr21_NA12878.vcf.gz Chr22_NA12878.vcf.gz -Ov -o TempOutput.vcf --force-samples

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878      2:NA12878
21      9411245 21:9411245:C:A  C       A       .       PASS    AF=0;MAF=0;R2=0;IMPUTED GT:DS   0|0:0   ./.:.
21      9411302 21:9411302:G:T  G       T       .       PASS    AF=0;MAF=0;R2=0;IMPUTED GT:DS   0|0:0   ./.:.
21      9411313 21:9411313:G:A  G       A       .       PASS    AF=0;MAF=0;R2=0;IMPUTED GT:DS   0|0:0   ./.:.

Not sure where is ./.:. came from. 
Is there a way to force bcftools not going to output that extra string?

**Comment by DrMcStrange** [comment]
Going by your input filenames, it looks like you meant to use `bcftools concat`, not `bcftools merge`.

The `bcftools merge` command combines files with different samples, so it's given you a sample column for each of the two input files, but one has no calls for chr21. (If you look at the bottom of the file, I'm guessing you'll see calls for chr22 where the first sample is missing and the second sample has genotypes.)
