### ISSUE TITLE
bcftools convert vcf to gen removes multiallelic variants as duplicates

### ISSUE THREAD

**Issue by pallolason** [samtools/bcftools#1286]
I am trying to convert a decomposed vcf to gen/sample, but "bcftools convert" only outputs the first of any multiallelic variant, removing the rest as duplicates, even though the alleles are different and the IDs also (CHROM:POS:REF:ALT). Common option "-c" has no effect.

**Comment by pallolason** [comment]
Thanks - that works as expected

**Comment by FogatoHub** [comment]
> I am trying to convert a decomposed vcf to gen/sample, but "bcftools convert" only outputs the first of any multiallelic variant, removing the rest as duplicates, even though the alleles are different and the IDs also (CHROM:POS:REF:ALT). Common option "-c" has no effect.

Hi, can i ask you what command line did you use to convert a vcf to gen and sample files?
Because i can't understand from the help what the input and output files should be given in the command.
Thank you.
