### ISSUE TITLE
output vcf doesn't have all SNP positions present in --targets-file with --insert-missed

### ISSUE THREAD

**Issue by sandeshsth** [samtools/bcftools#1289]
I am trying to get all SNP positions, present in `2239149_SNPs.tsv.gz`, in `out.vcf` file using following command. But, out.vcf has 1,849,137 SNPs. I was wondering if I am missed something here?

`bcftools mpileup -T 2239149_SNPs.tsv.gz --annotate AD,DP,INFO/AD --skip-indels -f ref.fa -b 5bams.txt -B | bcftools call -m --constrain alleles -T 2239149_SNPs.tsv.gz --variants-only --skip-variants indels --output-type v -o out.vcf --group-samples - --insert-missed`

**Comment by pd3** [comment]
So the problem is that the option `--insert-missed` does not seem to be working.

**Comment by sandeshsth** [comment]
Yes, there is a problem with `--insert-missed`. Will the fix be available soon?

**Comment by pd3** [comment]
@sandeshsth, any chance you could provide a small test case to reproduce the bug? I suspect the missing sites have no alternate alleles, e.g. `REF=C ALT=<*>`, but since you are calling with `--variants-only` and such sites are not missed in the bams, they will not appear on output. If you drop the `-v` switch, you'll probably see all sites?

**Comment by sandeshsth** [comment]
@pd3 After removing `--variants-only`, all sites appeared in the output VCF. Thank you

**Comment by sandeshsth** [comment]
@pd3 here `--insert-missed` outputs missing SNPs as `.`. When I was imputing the missing using Beagle, it is not working. Is it possible to output the missings as `./.`?

**Comment by pd3** [comment]
Try `bcftools +fixploidy`?

**Comment by sandeshsth** [comment]
@pd3 I will check `bcftools +fixploidy` but this will add an extra step. It would be great if `--insert-missed` could add missing SNPs as `./.`. Also, `./.` is standard for missing in the VCF format?

**Comment by pd3** [comment]
Both representations are valid. I am not sure about adding `./.` by default as it directly implies a missing diploid genotype, which is not always the case.
