### ISSUE TITLE
isec error: "Could not load the index"

### ISSUE THREAD

**Issue by CoryFunk** [samtools/bcftools#129]
I have two vcf files, one generated from a single sample (hereafter A.vcf.gz), the other being a subset of a vcf file from the Sanger Institute that has all the mouse strain variants. I used bcftools to get a subset of the vcf file (hereafter B.vcf.gz). I'm now trying to use isec to find the differences between the two files as such:

bcftools isec A.vcf.gz B.vcf.gz -n -1 -c all

This command generates the following error:

[add_reader] Could not load the index of A.vcf.gz

I have the idx file for A.vcf.gz in the working directory. I do not have an idx file for B.vcf.gz.  When I try to make an idx file for B.vcf.gz with the following command:

bcftools index B.vcf.gz ,

I get the following error:

[E::main_vcfindex] tbx_index_build failed for B.vcf.gz 

I found another user got the same "Could not load the index" error and found it was because of a pipe ( | ) in the headers of his fasta file. I checked and I do not have any pipes in my headers. That said, I did do a custom concatenation of my fasta from the individual mouse chromosomes so they would be in numeric order (different from how ENSMBL choses to order them). 

Any ideas what I might be missing or overlooking?

**Comment by Nazeeefa** [comment]
I have a file compressed with bgzip, however it says: 

> Failed to open file.vcf.gz: could not load index

the command was:` bcftools isec file1.vcf.gz file2.vcf.gz -p .`

**Comment by pd3** [comment]
It's probably because the file is not indexed: `bcftools index file1.vcf.gz && bcftools index file2.vcf.gz`

**Comment by Nazeeefa** [comment]
Thank you!

**Comment by atiaamin2019** [comment]
Thank you!
