### ISSUE TITLE
Problem with consensus 

### ISSUE THREAD

**Issue by Lcornet** [samtools/bcftools#1291]
Dear bcftools team,

I have a mistake using  bcftools consensus, it actually do not the consensus in my cases.

This is my pipeline:

$ bowtie2-build ref-mask.fa ref-mask.bt2index
#end to end mapping
$ bowtie2 -x ref-mask.bt2index -1 NG-25505_IHEM_13375_R1-fastp.fastq -2 NG-25505_IHEM_13375_R2-fastp.fastq -S NG-25505_IHEM_13375-mask.sam --end-to-end -p 40
#output bam file
$ samtools sort NG-25505_IHEM_13375-mask.sam > NG-25505_IHEM_13375-mask.bam
#index bam file
$ samtools index NG-25505_IHEM_13375-mask.bam
#call variant in VCF format
$ samtools mpileup -Ou -g -f ref-mask.fa NG-25505_IHEM_13375-mask.bam | bcftools call -mv -Oz --ploidy 1 -o calls.vcf.gz
#index VCF file
$ bcftools index calls.vcf.gz
#Normalization of vcf file, to avoid skipping due to overlap
$ bcftools norm -f ref-mask.fa calls.vcf.gz -Ob -o calls.norm.bcf
$ bcftools filter --IndelGap 5 calls.norm.bcf -Ob -o calls.norm.flt-indels.bcf
$ bcftools filter -s LOWQUAL -e '%QUAL<20 || DP>100' calls.norm.flt-indels.bcf -Oz -o calls.norm.flt-indels-qual.bcf
$ bcftools index calls.norm.flt-indels-qual.bcf
#create the consensus fast file
$ cat ref-mask.fa | bcftools consensus calls.norm.flt-indels-qual.bcf > consensus.fa

This is a sequence of the consensus file :
>KK210157.1
GAGTAGAATTaaaatctaatagaaattaaagGCTCTTAATTAAGAAGAGACTactaatag

This is the image of the alignment on this region from IGV : 
![IGV](https://user-images.githubusercontent.com/37297858/90907931-fa969a80-e3d3-11ea-9963-bc6c813f9e4d.png)

The sequences are very similar with few variations,  but the variations are not in the consensus (especially fifth one).
Did I misunderstand something ?

Thanks,
Luc

**Comment by pd3** [comment]
The question is impossible to answer as it stands. The command `consensus` takes on input a VCF and the reference sequence. We do not know what is in `calls.norm.flt-indels-qual.bcf`. Also, you are using a very old workflow that has been deprecated a long time ago. Please see http://samtools.github.io/bcftools/howtos/consensus-sequence.html

**Comment by Lcornet** [comment]
Thank you for your answer.

I am sorry but I am not sure to understand why its is an old workflow. Is it because of the use of samtools mpileup in place of bcftools mpileup ? 

Because if I use calls.norm.flt-indels.bcf as recommended in http://samtools.github.io/bcftools/howtos/consensus-sequence.html, I have the same result.

Thanks for the help,
Luc

**Comment by pd3** [comment]
It is hard to tell from a screenshot and a sequence of commands. You'll need to check all the intermediate steps to see if the variant was called, filtered, and finally applied to the consensus sequence. If you identify the problematic step, a small test case to reproduce the problem would be helpful.
