### ISSUE TITLE
Does bcftools enforce types for standard genotype fields, both in the header and records?

### ISSUE THREAD

**Issue by nh13** [samtools/bcftools#1293]
The `PS` format field in the header has type `String`, which is not spec-compliant (should be `Integer`), but `bcftools 1.9` works just fine
```bash
bcftools view https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/latest/GRCh38/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz chr1:4001310-4001310
```

Given c`cyvcf2` has an error](https://github.com/brentp/cyvcf2/issues/161), and it uses `htslib`, I am confused why I don't see the same thing when running `bcftools` directly:
```
...
[E::vcf_parse_format] Invalid character 'P' in 'PS' FORMAT field at 1:4001310
...
```

See: https://github.com/genome-in-a-bottle/giab_latest_release/issues/15

**Comment by pd3** [comment]
BCFtools and HTSlib does not check whether the VCF violates reserved VCF tags. As long as the definition in the header is consistent with the body, both will work.
