### ISSUE TITLE
plot-vcfstats of single chromosome files lead to a suspicious shift in HWE curve

### ISSUE THREAD

**Issue by MWendorff** [samtools/bcftools#1296]
Hey,
I calculated the `bcftools stats -s- vcf_file_chr > chr_stats` for the single chromosomes and plotted the data using `plot-vcfstats -p '' chr_stats` and the result looks ok e.g. 
![hwe 0](https://user-images.githubusercontent.com/61823978/92469241-c7764880-f1d4-11ea-839d-3a5a9fc0f135.png)
 But if I combine the different alleles (`plot-vcfstats -p '' *_stats`) the curve is completely drawn.
![hwe 0](https://user-images.githubusercontent.com/61823978/92467205-7a44a780-f1d1-11ea-9d17-89288a97775a.png)

I also tested combining the files in advance. It looks like all results are the same except for the HWE part.

Is there any known bug in this part or a reason for this?

**Comment by pd3** [comment]
I am not aware of such a bug, you are the first reporting it. Any chance you could share the stats outputs to debug?

**Comment by MWendorff** [comment]
I have removed the PSI and PSC paragraphs from the stats file (but the results are the same).
[HWE.Chromosomes.zip](https://github.com/samtools/bcftools/files/5209410/HWE.Chromosomes.zip)

Thanks for checking this.

**Comment by MWendorff** [comment]
And additional here are the summary statistics if the chromosomes 1 and 2 are combined in advance and using plot_vcfstats with the single chromosome files posted in advance.
[chr1and2.zip](https://github.com/samtools/bcftools/files/5209829/chr1and2.zip)

**Comment by pd3** [comment]
Thank you for the testing data. The HWE case requires a special treatment when merging, I think this stats was added only after the merge functionality and the merge functionality was not considered. Note that the resulting graph is an approximation, the summary percentiles cannot be calculated exactly without the source data.
