### ISSUE TITLE
plot-vcfstats: Genotype discordance by AF is misreported from .vchk input file

### ISSUE THREAD

**Issue by winni2k** [samtools/bcftools#1297]
I ran plot-vcfstats on a stats file containing this NRD section:

```
# NRD and discordance is calculated as follows:
#   m .. number of matches
#   x .. number of mismatches
#   NRD = (xRR + xRA + xAA) / (xRR + xRA + xAA + mRA + mAA)
#   RR discordance = xRR / (xRR + mRR)
#   RA discordance = xRA / (xRA + mRA)
#   AA discordance = xAA / (xAA + mAA)
# Non-Reference Discordance (NRD), SNPs
# NRDs  [2]id   [3]NRD  [4]Ref/Ref discordance  [5]Ref/Alt discordance  [6]Alt/Alt discordance
NRDs    2       0.579613        0.990299        0.224524        0.294973
```
and I got this output:

![image](https://user-images.githubusercontent.com/304958/92587415-e984cf00-f297-11ea-8071-bf48ce924cb6.png)

I think the % signs need to be removed for the output of the plotting to be correct.

**Comment by pd3** [comment]
These really are percents https://github.com/samtools/bcftools/blob/develop/vcfstats.c#L1498-L1500 (99% discordance would be a bit too high!). I updated the explanation to make it obvious 75ac03d.

**Comment by winni2k** [comment]
Oh wow! That's great news :D I just figured something had gone terribly wrong in my genotyping experiments.
