### ISSUE TITLE
Question - bcftools - time taken/performance for concat or merge

### ISSUE THREAD

**Issue by Ak784** [samtools/bcftools#1298]
Hello team,

am new to bioinformatics and vcf files analysis. I came to know about bcftools for vcf data analysis.

So, I was playing around with the tool and was trying to combine/merge/concat all my vcf files into one vcf file

However, when I use the below command, I don't get any output

`bcftools concat -f list.txt -Oz > final.vcf.gz`

My list.txt file only contains 2 vcf files for different chromosome positions but the same samples in both files.

q1) May I know how much time does bcftools merge or concat takes?

q2) I have data from different chromosomes that are stored in different files such as `file_chr5.vcf.gz` and `file_chr7.vcf.gz` etc. So, if I have to combine them all together, should I merge them or concat them?

**Comment by pd3** [comment]
This is explained in the man page http://samtools.github.io/bcftools/bcftools.html: `concat` is used to "concatenate" files split by region or chromosome (i.e. the same samples) whereas `merge` puts together files with different samples (e.g. single-sample input files with the same positions will result in a one multi-sample file with the same positions).

As for the performance, I don't have any numbers to show, but you should see some output immediately. Try to run without the `-Oz > final.vcf.gz` part and there should be some output printed on the screen.

**Comment by Roshinisundararajan** [comment]
Hi Petr Danecek,
If I have a directory of different samples vcf files, should I use bcftools merge or concat to combine them into one vcf file.

**Comment by pd3** [comment]
@Roshinisundararajan Thank you for your trust in me, but how am I supposed to know? :)) Please read the documentation, both tools are intended for different purpose
http://samtools.github.io/bcftools/bcftools.html#merge
http://samtools.github.io/bcftools/bcftools.html#concat

Please open a new issue next time, instead of adding unrelated questions to resolved issues
