### ISSUE TITLE
bcftools annotate does not recognize a tag

### ISSUE THREAD

**Issue by golrokh51** [samtools/bcftools#1299]
I am using `bcftools/1.10.2` 

This is my header file:

    ##INFO=<ID=strand,Number=1,Type=String,Description="strand">
    ##INFO=<ID=gene_ID,Number=1,Type=Integer,Description="gene_ID">
    ##INFO=<ID=locus,Number=1,Type=String,Description="locus">
    ##INFO=<ID=locus_tag,Number=1,Type=String,Description="locus_tag">
    ##INFO=<ID=protein_product,Number=1,Type=String,Description="protein_product"> 
    ##INFO=<ID=length,Number=1,Type=Integer,Description="length">
    ##INFO=<ID=protein_name,Number=1,Type=String,Description="protein_name">

This is the first two lines of my annotation file (sorted, bgzipped and tabix indexed with `tabix -s 1 -b 2 -e 3 annotation_proteins_85_22812_chr_sorted.tab.gz` ):

    #CHROM	FROM	TO	strand	gene_id	locus	locus_tag	protein_product	length	protein_name
    chr1	252392	322063	-	100856150	ENPP1	-	XP_003638833.1	916	ectonucleotide pyrophosphatase/phosphodiesterase family member 1 isoform X2

This is my command line :
`f1=0000.vcf.gz`
` bcftools annotate -a annotation_proteins_85_22812_chr_sorted.tab.gz -h header.hdr -c CHROM,FROM,TO,-,gene_id,locus,-,protein_product,-,protein_name $f1 > $out`

and I get this error:
`The tag "gene_id" is not defined in annotation_proteins_85_22812_chr_sorted.tab.gz`

The first 100 lines of my annotation file:
[annotation_proteins_85_22812_chr_sorted.tab.gz](https://github.com/samtools/bcftools/files/5196235/zcatHead100_bed.txt)

Header file:
[header.hdr](https://github.com/samtools/bcftools/files/5196222/header.txt)

The first 100 lines of my vcf file:
[$f1](https://github.com/samtools/bcftools/files/5196223/zcatHead100.txt)

**Comment by pd3** [comment]
The tag names are case sensitive: the header defines the tag as `gene_ID` but on the command line it appears as `gene_id`.
