### ISSUE TITLE
`bcftools norm --check-ref s` does not properly correct ALT field for indels

### ISSUE THREAD

**Issue by 0xaf1f** [samtools/bcftools#1300]
bcftools version 1.10.2

```
bcftools norm --check-ref s --fasta-ref H37Rv.fasta debug.vcf
```

turns

```
1       3552584 .       NCG     N       57      PASS    DP=6
```

to

```
1       3552584 .       A       N,NCG   57      PASS    DP=6
```

instead of the expected

```
1       3552584 .       ACG       A   57      PASS    DP=6
```

test files attached - [debug.zip](https://github.com/samtools/bcftools/files/5197962/debug.zip)

**Comment by 0xaf1f** [comment]
I'm still trying to figure out why my variant caller made the VCF like that to begin with, but that's another issue.

**Comment by pd3** [comment]
This is a bit out of the intended scope, but should be now working. Thank you for reporting the bug and the test case.

**Comment by 0xaf1f** [comment]
thanks! Though thinking about this a little more, perhaps the N should be maintained in the ALT field so as not to assume the variant was intended to be a simple deletion. I agree that would be out of scope for this command's job.

so then 
```
NCG       N
```
rather corrected to just
```
ACG        N
```
but at least not introducing a second ALT allele like it was before.
