### ISSUE TITLE
bcftools consensus to the very first place in the sequence

### ISSUE THREAD

**Issue by arangrhie** [samtools/bcftools#1302]
Hello, bcftools team!

I was trying to patch the telomeric sequence to our assembly using `bcftools/1.9`.
The vcf line looked as following:

```
chr18	1	sv_15	A	CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT...(sequences)...A	.	PASS	.	GT	1/1
```

`bcftools consensus -H 1 -c` produced Segmentation fault, so I had to manually attach the sequence.

Is this already fixed in the latest samtools/bcftools? If not, could this be fixed in near term?

I am asking because there will be more telomeres coming after, and would be really handy if the bcftools consensus works as one would expect. I like how handy it is to use the chain file :)

Thanks!
Arang

**Comment by pd3** [comment]
This should work with the latest version in github, a new release is imminent.
