### ISSUE TITLE
bcftools csq used together with +split-vep misses all intergenic variants

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1303]
I have noticed that `bcftools csq` will not assign any `BCSQ` field for intergenic variants.

When used with `bcftools +split-vep` this causes all intergenic sites to be dropped due to the following code:
```
static void process_record(args_t *args, bcf1_t *rec)
{
    int len = bcf_get_info_string(args->hdr,rec,args->vep_tag,&args->csq_str,&args->ncsq_str);
    if ( len<=0 ) return;
```

I wanted to use `bcftools +split-vep --format` as a replacement for `bcftools query --format` to build tables out of a given VCF, but the fact that all intergenic sites are dropped is a bit of a drawback.

**Comment by pd3** [comment]
Perhaps more useful would be to add an option to make `+split-vep` output also sites with no annotation?

**Comment by freeseek** [comment]
Yes, that would work as well. I would see that as the default behavior, even if it changes how it currently operates, with the previous behavior recoverable with the `--severity` option. There would be one question remaining though: if you annotated a VCF with `bcftools csq` and then you use `bcftools +split-vep --severity intergenic --format "..."`, what output should you expect?

**Comment by pd3** [comment]
I'd like the default behavior to remain the same. The unannotated sites would be printed optionally by requesting `-s :unknown` or `-s :unk` or `-s n/a` for short.

**Comment by pd3** [comment]
Actually, thinking about it more, I don't think changes should be required, have you checked the tutorial http://samtools.github.io/bcftools/howtos/plugin.split-vep.html? What you want can be achieved like this:
```
# Output VCF adding the INFO/Consequence column only to missense sites. However, outputs all sites.
bcftools +split-vep test/split-vep.5.vcf -c Consequence -s :missense | bcftools query -f'%POS\t%Consequence\n' | head -2
69270    .
69428    missense_variant,regulatory_region_variant
```
Is there a reason why not to use that?

**Comment by freeseek** [comment]
My understanding is that you would still hit the vcf-split.c code:
```
static void process_record(args_t *args, bcf1_t *rec)
{
    int len = bcf_get_info_string(args->hdr,rec,args->vep_tag,&args->csq_str,&args->ncsq_str);
    if ( len<=0 ) return;
```
which would drop all variants without BCSQ fields (no matter what `-s :xxx` command you use), while my goal would be to convert all variants in a given VCF to table format with the BCSQ field split in multiple columns when available.

Maybe the problem is then that `bcftools csq` does not add the BCSQ info field to all variants (the `test/split-vep.5.vcf` file has the CSQ info fields for all variants).

**Comment by pd3** [comment]
I don't follow completely. You'd have missing values (dots) at the end in the output, I thought that's what you wanted. Best if you could provide an example of input and desired output and we'll see

**Comment by freeseek** [comment]
Here is an example of a VCF that could be output by `bcftools csq`:
```
(echo "##fileformat=VCFv4.2"
echo "##contig=<ID=chr1,length=248956422,assembly=38>"
echo "##INFO=<ID=BCSQ,Number=.,Type=String,Description=\"Local consequence annotation from BCFtools/csq, see http://samtools.github.io/bcftools/howtos/csq-calling.html for details. Format: Consequence|gene|transcript|biotype|strand|amino_acid_change|dna_change\">"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "chr1\t975523\trs4970429\tT\tC\t.\t.\tBCSQ=3_prime_utr|PLEKHN1|ENST00000379410|protein_coding"
echo -e "chr1\t1020060\t.\tGCC\tG\t.\t.\t.") > test.vcf
```

Now, if I run:
```
$ bcftools query -f "%CHROM\t%POS\n" test.vcf
chr1	975523
chr1	1020060
```

While if I run:
```
$ bcftools +split-vep -a BCSQ -c Consequence -f "%CHROM\t%POS\t%Consequence\n" test.vcf
chr1	975523	3_prime_utr
```
Variant 1020060 gets lost.

Similarly with piping:
```
$ bcftools +split-vep test.vcf -a BCSQ -c Consequence -s :3_prime_utr | \
  bcftools query -f "%CHROM\t%POS\t%Consequence\n"
chr1	975523	3_prime_utr
```
Variant 1020060 gets lost.

**Comment by pd3** [comment]
Thank you for the test case, you were right, it behaves differently from what I thought/remembered. It is now fixed and behaves as expected:
```
$ bcftools +split-vep -a BCSQ -c Consequence ~/test.vcf | bcftools query -f "%CHROM\t%POS\t%Consequence\n"
chr1	975523	3_prime_utr
chr1	1020060	.

$ bcftools +split-vep -a BCSQ -c Consequence ~/test.vcf -x | bcftools query -f "%CHROM\t%POS\t%Consequence\n"
chr1	975523	3_prime_utr
```

**Comment by freeseek** [comment]
Sorry to comment again on such an old issue. I still find the behavior a bit puzzling.

```
wget -O- ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz | \
  gzip -d > GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
samtools faidx GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
wget ftp://ftp.ensembl.org/pub/current_gff3/homo_sapiens/Homo_sapiens.GRCh38.104.gff3.gz
(echo "##fileformat=VCFv4.2"
echo "##contig=<ID=1,length=248956422,assembly=38>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "1\t975523\trs4970429\tT\tC\t.\t.\t."
echo -e "1\t1020060\t.\tGCC\tG\t.\t.\t.") > in.vcf
bcftools csq --no-version -c CSQ -f GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -g Homo_sapiens.GRCh38.104.gff3.gz in.vcf -o csq.vcf
```

This generates the following VCF:
```
$ cat csq.vcf
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=248956422,assembly=38>
##INFO=<ID=CSQ,Number=.,Type=String,Description="Haplotype-aware consequence annotation from BCFtools/csq, see http://samtools.github.io/bcftools/howtos/csq-calling.html for details. Format: Consequence|gene|transcript|biotype|strand|amino_acid_change|dna_change">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	975523	rs4970429	T	C	.	.	CSQ=3_prime_utr|PLEKHN1|ENST00000379410|protein_coding,3_prime_utr|PERM1|ENST00000341290|protein_coding,3_prime_utr|PERM1|ENST00000433179|protein_coding
1	1020060	.	GCC	G	.	.	.
```
(notice that with bcftools 1.13 the first variant is not annotated ... though this seems to be a separate bug in `bcftools csq`)

Now I can run:
```
$ bcftools +split-vep -f '%CHROM\t%POS\t%Consequence\n' -s worst csq.vcf
1	975523	3_prime_utr
```

Or I can run:
```
$ bcftools +split-vep -c Consequence -s worst csq.vcf | bcftools query -f '%CHROM\t%POS\t%Consequence\n'
1	975523	3_prime_utr
1	1020060	.
```

I find it counterintuitive that the first command drops the second variant, since I did not specify which type of variants I wanted to retain. I think this could lead users to inadvertently drop variants when they do not mean to. At a minimum, `bcftools csq` should annotate the variant as `intergenic` as it is not a correct interpretation that the variant has unknown annotation (i.e. it is known that it does not fall within a gene). What do you think?

**Comment by pd3** [comment]
This behavior is deliberate. Typically one uses the formatting functionality of `+split-vep` to extract the "interesting" consequences. When everything is required, streaming through `bcftools query` allows to print everything.

As for not marking intergenic variants, this was also a deliberate decision. The way `csq` operates, it will add consequences to features defined in the GFF file. Intergenic regions are not listed and therefore "missing" and "intergenic" are used interchangeably. I am not aware of a situation where this could lead to a misleading interpretation.

**Comment by freeseek** [comment]
My current implementation looks for variants from WGS that are either coding or they have been classified by ClinVar as pathogenic, regardless of whether they are coding. After annotating the input VCF using `bcftools csq` and `bcftools annotate`, I then extract these variants with code like this:
```
bcftools +split-vep \
  --columns Consequence,gene,amino_acid_change \
  --select worst \
  --include 'Consequence="missense,inframe,protein_altering,transcript_amplification,exon_loss,disruptive,start_lost,stop_lost,stop_gained,frameshift,splice_acceptor,splice_donor,transcript_ablation" ||
    CLNSIG="Likely_pathogenic,Pathogenic,_association,Pathogenic/Likely_pathogenic"' \
  input.vcf | \
  bcftools query \
  --format "%CHROM\t%POS\t%REF\t%ALT\t%gene\t%Consequence\t%amino_acid_change\t%CLNID\t%CLNDN\t%CLNSIG\n"
```
(which compared to previous pipelines before `bcftools csq` and `bcftools +split-vep` existed is so incredibly compact)

But it is easy to slip and use the following code instead:
```
bcftools +split-vep \
  --columns Consequence,gene,amino_acid_change \
  --format "%CHROM\t%POS\t%REF\t%ALT\t%gene\t%Consequence\t%amino_acid_change\t%CLNID\t%CLNDN\t%CLNSIG\n" \
  --select worst \
  --include 'Consequence="missense,inframe,protein_altering,transcript_amplification,exon_loss,disruptive,start_lost,stop_lost,stop_gained,frameshift,splice_acceptor,splice_donor,transcript_ablation" ||
    CLNSIG="Likely_pathogenic,Pathogenic,_association,Pathogenic/Likely_pathogenic"' \
  input.vcf
```
Which will omit all the intergenic ClinVar variants.

I think a new user could easily get confused. At least a warning could be provided in the help for the command which is currently:
```
   -f, --format <string>           Formatting expression for non-VCF/BCF output, same as `bcftools query -f`
```
And it should clarify that this is not the same as `bcftools query -f` as it will drop all the variants without `CSQ` annotations.

As for `bcftools csq` leaving out the `intergenic` annotations, I can see how that saves space in the output VCF, but there is a difference between not knowing whether a variant is exonic/intronic/intergenic and knowing that a variant is neither exonic nor intronic as the latter is still some information.

(PS I should probably have opened a separate issue, but were you able to replicate the issue with BCFtools 1.13 where `bcftools csq` fails to annotate the 3' PLEKHN1 variant?)

**Comment by pd3** [comment]
The usage page has been updated to reflect the difference between `query -f` and `+split -f` (https://github.com/samtools/bcftools/commit/795661837458ebec273ea34b588365eb0a40613c)

It would be great if each problem was opened as a separate issue, otherwise it's hard to keep track of what's been addressed and what remains unsolved. Thank you
