### ISSUE TITLE
bcftools fill-tags INFO/HWE on chrX (non-PAR regions)

### ISSUE THREAD

**Issue by mbyrska** [samtools/bcftools#1305]
I have a VCF with haploid calls in males (diploid in females) on non-PAR regions of chrX. I annotated it using the bcftools fill-tags plugin and noticed that HWE p-value annotations are provided for such mixed ploidy sites in the output. How are these estimated? I couldn't find any information about handling of chrX in the publication cited on the plugin page (PMID:15789306) so I just wanted to make sure that the fill-tags plugin properly estimates HWE p-values on non-PAR regions of chrX. Any information on that would be greatly appreciated! Thank you!

**Comment by pd3** [comment]
Only diploid genotypes are included in the calculation, so if the correct ploidy (e.g. `1` rather than `1/1`) is set, it should do the correct thing. Hemizygous genotypes are ignored and don't inform allele frequency.
