### ISSUE TITLE
merging issue

### ISSUE THREAD

**Issue by oalavijeh** [samtools/bcftools#1306]
Dear bcftools team, 

Firstly thank you for supporting such an awesome tool! 

Secondly I am trying to merge 70 vcfs by a region and getting the following error:

bcftools: vcfmerge.c:689:mau_init: Assertion 'n_smpl==(args->out_hdr)->n[2]' failed 
Aborted

I'm afraid I work in an airlock so can't really provide a reproducible example but the code use is:
bcftools merge --force-samples -f "PASS,." -r chr1:1241413-43656322 -l paths.txt 
 
What would such an error be caused by usually? The VCFs are all generated using a standard Illumina pipeline and I haven't fiddled with them at all....

All the best

**Comment by pd3** [comment]
What version of bcftools is this? I've never seen this error before, it has something to do with merging of headers that went wrong. Please try with the latest github version of bcftools+htslib, it might give a more informative error message

**Comment by oalavijeh** [comment]
this is bcftools 1.10.2-foss-2018b. I work in an airlock on the genomics england HPC (https://cnfl.extge.co.uk/display/GERE/Software+Available+on+the+HPC). Is this the latest version? Otherwise I can ask the HPC admin to import another.

**Comment by pd3** [comment]
That's recent enough. Maybe try to narrow it down to a subset of VCFs that still have the problem. How many samples there are in total? I don't expect an internal integer limit was exceeded.

**Comment by oalavijeh** [comment]
there are 72 samples in total. I'll try a couple of random vcfs and see what happens but not sure it'll help find the culprit!

**Comment by oalavijeh** [comment]
so it seems to give the error after merging any more than 17 gvcfs. This can be any combination of the 72 vcfs. The vcfs themselves are all in good nick.  Pretty weird....

**Comment by pd3** [comment]
I might be able to take a look at in GEL myself. Can you contact me privately please, my email is on the profile page.

**Comment by pd3** [comment]
This was resolved by updating to a more recent version of bcftools.
