### ISSUE TITLE
+fill-tags plugin cant add INFO/TYPE tag to vcf

### ISSUE THREAD

**Issue by tomoosting** [samtools/bcftools#1310]
I've been trying to add INFO/TYPE tag to my vcf file but the plugin does not appear to support that anymore.
The manual page does mention it:
https://samtools.github.io/bcftools/howtos/plugin.fill-tags.html

I've tried both:
`bcftools +fill-tags in.vcf.gz -Ov -o out.vcf -- -t INFO/TYPE`
`bcftools +fill-tags in.vcf.gz -Ov -o out.vcf -- -t all`
The last command does add various tags, so I know the command works.
I've tried this with bcftools/1.9 and 1.10.1

Any help on how to obtain the INFO/TYPE tag would be much appreciated.
Cheers,

**Comment by pd3** [comment]
This feature was added in May 2020, to use it you'll need to use the latest github version or wait for the next release.
