### ISSUE TITLE
Missing mpileup records 

### ISSUE THREAD

**Issue by BioGeorge** [samtools/bcftools#1311]
Hi, I am working with SNVs of one genome. I found little SNVs detected of one higly variable gene in my genome according to the vcf records. When I extracted the gene sequence from assembly and aligned with the reference, the differences were obviously viewed.

When I mpileup it again with the following commands  ` bcftools mpileup -C50 -B -Q 0 ` , I still couldn't see any records in the output. It looks like a gap from 106943 to 108043. 
![image](https://user-images.githubusercontent.com/42829875/94252075-071f8d00-ff56-11ea-924a-d8433eed9c28.png)

But when I look the bam file in IGV, I can see the mapped reads and the variants in the 'missing' region.
![image](https://user-images.githubusercontent.com/42829875/94252261-42ba5700-ff56-11ea-8a8c-e018d22d97db.png)

By the way, the version of bcftools is v1.6. Could you please tell me why I got such a confusig result? 
Thanks in advance.

**Comment by pd3** [comment]
Wow, this is odd. The VCF output suggests that from some reason only one read was considered in calling, DP=1. Can you share slice of your bam and the reference genome?

Also you should update to the latest version, 1.6 is way too old
http://samtools.github.io/bcftools/howtos/install.html
http://www.htslib.org/download/

**Comment by BioGeorge** [comment]
Thanks, I've updated the samtools/bcftools to the latest one but still found the problem. I've tried in many ways and compared the results. I think it's the -C50 causing this problem as I mpileup with default parameters and the results look fine. But I don't know why as mapping was done with BWA. 

Related files were uploaded as below. For some reason, the file were renamed. If any problem, please let me know.

[Test0930.zip](https://github.com/samtools/bcftools/files/5303758/Test0930.zip)

**Comment by BioGeorge** [comment]
> Wow, this is odd. The VCF output suggests that from some reason only one read was considered in calling, DP=1. Can you share slice of your bam and the reference genome?
> 
> Also you should update to the latest version, 1.6 is way too old
> http://samtools.github.io/bcftools/howtos/install.html
> http://www.htslib.org/download/

Thanks, I've updated the samtools/bcftools to the latest one but still found the problem. I've tried in many ways and compared the results. I think it's the -C50 causing this problem as I mpileup with default parameters and the results look fine. But I don't know why as mapping was done with BWA.

Related files were uploaded as below. For some reason, the file were renamed. If any problem, please let me know.

[Test0930.zip](https://github.com/samtools/bcftools/files/5303767/Test0930.zip)

**Comment by pd3** [comment]
Thank you for the test case. The -C option reduces the number of false calls (and thus increases the number of missed calls) which are triggered by reads with many mismatches. If you run `samtools view Test.bam chromosome_1:106943-108043`, you'll see that 60% of the reads in this region are soft-clipped, so I guess that's observing -C at work. If you leave the option out or set it to a very big value (e.g. -C200), the variants will be called again.
