### ISSUE TITLE
bcftools call --keep-alts 

### ISSUE THREAD

**Issue by soleneconrad** [samtools/bcftools#1312]
Dear bcftools team,

I tried to use bcftools call --keep-alts to keep variants with low allele frequency in the vcf of parental pools for exome sequencing. Which works very well.
What I would like to know is if this argument--keep-alts just keep in final vcf variants which doesn't appear in genotype (GT) because of a low frequency or if it also recruts bad quality alleles? Does it change the standard qualities of bcftools?

Thank you for your answer

**Comment by pd3** [comment]
The option merely preserves all alternate alleles considered by the `mpileup` step, that's all it does.
