### ISSUE TITLE
bcftools +fill-tags calculates unexpected MAF for multiallelic variants

### ISSUE THREAD

**Issue by KallyopeBio** [samtools/bcftools#1313]
Consider the following simple VCF file:

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	2	3	4	5
1	75125008	rs543997273	ATG	ATGTG,A	.	PASS	.	GT	0/2	0/0	0/0	0/1	0/1

Call this file test.vcf. I get the following result if I run the command
> bcftools +fill-tags test.vcf -Ov -o annt_test.vcf -- -t AF,MAF,TYPE

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency">
##INFO=<ID=MAF,Number=A,Type=Float,Description="Minor Allele frequency">
##INFO=<ID=TYPE,Number=.,Type=String,Description="Variant type">
##bcftools_pluginVersion=1.11+htslib-1.11
##bcftools_pluginCommand=plugin fill-tags -Ov -o annt_test.vcf -- test.vcf -t AF,MAF,TYPE; Date=Fri Sep 25 13:24:00 2020
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	2	3	4	5
1	75125008	rs543997273	ATG	ATGTG,A	.	PASS	AF=0.2,0.1;MAF=0.2,0.1;TYPE=INDEL	GT	0/2	0/0	0/0	0/1	0/1

Everything here looks good, except that I'd expect the INFO field to read "AF=0.2,0.1;**MAF=0.2**;TYPE=INDEL"

Even a multiallelic variant only has a single MAF: it's the allele frequency of the second most common allele. But the fill-tags plugin computes the MAF as if I had given this variant in biallelic form, with each ALT allele given separately. Is this expected behavior? Is there a way to get the behavior I want from bcftools?

**Comment by KallyopeBio** [comment]
Ultimately, what i really care about is applying a MAF filter to the annotated file. For instance, with bcftools view -i 'MAF >= x'. And this seems to work as expected.

**Comment by pd3** [comment]
You are right; this has been revised now and the second most common allele will be used as the minor allele. Thanks for the issue.
