### ISSUE TITLE
Dynamic call to `bcftools filter` fails

### ISSUE THREAD

**Issue by franrodalg** [samtools/bcftools#1314]
Hi everyone,

In order to try a few thresholds I want to run `bcftools filter` with a dynamically created expression, but it's not working, and I can't understand why. For instance, if I store an expression such as:

`filt="'(AD[:1]/(AD[:1]+AD[:0])>=0.1 && AD[:0]+AD[:1]>100)'"`

and then run:

`bcftools filter -i $filt ../../data/variants/HG02461/HG02461.bcf`

I get:

```
[E::_regions_init_string] Could not parse the region(s): AD[:0]+AD[:1]>100)',../../data/variants/HG02461/HG02461.bcf
Failed to read the regions: (null)
```

so it seems to be interpreting the space as the end of the expression even if it is within the single quotes. It works perfectly fine if I use:

`bcftools filter -i '(AD[:1]/(AD[:1]+AD[:0])>=0.1 && AD[:0]+AD[:1]>100)' ../../data/variants/HG02461/HG02461.bcf`

which should be completely equivalent (I think).

My ultimate goal is to replace "0.1" and "100" with some shell variables, but I'm happy to do it in multiple steps if necessary, since simply replacing the variables within the `bcftools call` doesn't work either:

`bcftools filter -i '(AD[:1]/(AD[:1]+AD[:0])>=${min_th} && AD[:0]+AD[:1]>${min_cov})' ../../data/variants/HG02461/HG02461.bcf`

`[filter.c:2491 filters_init1] Error: the tag "${min_th}" is not defined in the VCF header`

Any help would be greatly appreciated.

Cheers!
Fran

**Comment by pd3** [comment]
The problem is with shell expansion, not with bcftools. You need to run as `bcftools filter -i "$filt"`. (Note the use of double quotes.)

**Comment by franrodalg** [comment]
Oh, thank you so much!

For anyone interested, it still wouldn't work if the single quotes are included in the variable containing the expression, as in my original post above (the output is empty, for some reason). The only way it works is:

```
filt="(AD[:1]/(AD[:1]+AD[:0])>=0.1 && AD[:0]+AD[:1]>100)"
bcftools filter -i "$filt" ../../data/variants/HG02461/HG02461.bcf
```
