### ISSUE TITLE
bcftools mpileup: Difference between DP and AD.

### ISSUE THREAD

**Issue by ehans245** [samtools/bcftools#1315]
I am using mpileup to generate the counts of each allele for an individual at given loci, command below.
bcftools mpileup -Q 30 -q 30 -f ../ref/scaffold.fa --bam-list slice --annotate AD

When I run this command, the output generates the AD for each sample but the sum of these values across all samples are not equal to the reported DP.

For example:
chr10	1	.	G	<*>	0	.	DP=39;I16=1,0,0,0,36,1296,0,0,60,3600,0,0,0,0,0,0;QS=1,0;MQ0F=0	PL:AD	0,3,36:1,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0	0,0,0:0,0

At this site there is only one read reported under AD for all of the samples, yet DP=39. Does AD represent the amount of each allele or is it possible that it only represents amount of each allele given informative reads (similar to this explanation https://gatk.broadinstitute.org/hc/en-us/articles/360035532252-Allele-Depth-AD-is-lower-than-expected)? If it is the latter, is there another way of getting the counts of each allele for an individual given all the reads that pass initial filtering?

**Comment by pd3** [comment]
DP is the raw read depth, AD includes only high-quality bases.  If you are running a reasonably recent version of bcftools, this is described in the header.
