### ISSUE TITLE
Assertion error while running bcftools consensus

### ISSUE THREAD

**Issue by Avibr8** [samtools/bcftools#1319]
Hey,

I have the following error while trying to run the consensus function:

> cat human_g1k_v37.fasta | ./bcftools consensus mycalls.bcf -s 10120_10120 -H 1 > 10120_10120_consensus.fa
The site 1:99069 overlaps with another variant, skipping...
The site 1:1323947 overlaps with another variant, skipping...
bcftools: consensus.c:638: apply_variant: Assertion `rec->d.allele[0][1]==0' failed.
Aborted (core dumped)

what does that exactly mean? is there a way to pass that?

**Comment by pd3** [comment]
What version of bcftools are you running? If the problem persists with the latest version, can you provide a small test case to reproduce the problem please?

**Comment by Avibr8** [comment]
version i use is: 1.11-1-g87d355e (using htslib 1.11-2-g3c1ea37)

the problem repeated in:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	10120_10120
1	10140	.	A	G	.	PASS	AC=0;AN=2	GT	0|0
1	10146	.	AC	A	.	PASS	AC=0;AN=2	GT	0|0
1	10147	.	C	<DEL>	.	PASS	AC=0;AN=2	GT	0|0
1	10153	.	A	C	.	PASS	AC=0;AN=2	GT	0|0
1	10159	.	A	G	.	PASS	AC=0;AN=2	GT	0|0
1	10291	.	C	T	.	PASS	AC=0;AN=2	GT	0|0
1	10297	.	C	T	.	PASS	AC=0;AN=2	GT	0|0
1	10389	.	AC	<DEL>	.	PASS	AC=0;AN=2	GT	0|0
1	10396	.	AC	<DEL>	.	PASS	AC=0;AN=2	GT	0|0
1	10397	.	C	<DEL>	.	PASS	AC=0;AN=2	GT	0|0

i did a few tests and i found that the error occured starting with the variant at 10389.
line 638 at consensus.c is:
        assert( rec->d.allele[0][1]==0 );           // todo: for now expecting strlen(REF) = 1

does that mean that REF allele can only be single nuc while ALT is deletion?

**Comment by pd3** [comment]
How was your VCF generated?

With symbolic deletions, the VCF specification and the program expects a single base in the REF column and the deletion is assumed to start at POS+1. With multiple bases in REF it is unclear where the deletion starts: is it at POS+1 or POS+length(REF)?

**Comment by pd3** [comment]
I amended the code assume that the `<DEL>` starts at `POS+1` and a warning is printed. However, the producer of such VCFs should fix their code.

**Comment by Avibr8** [comment]
That helped! thank you
