### ISSUE TITLE
filter genotypes based on PL values

### ISSUE THREAD

**Issue by BjoernStelbrink** [samtools/bcftools#1321]
Hi,

I used mpilup to call SNPs for 80 samples and filtered those SNPs using different options in bcftools and set several genotypes to missing (./.) accordingly. I now noticed that the phred-scaled likelihoods (PLs) for some SNPs are ambiguous (at least for my taste), e.g.: REF=A, ALT=G; GT:**PL** = 1/1: **221,9,0**. In this example, the likelihood for AG is also quite high (81%) and I want to filter those genotypes, i.e. set them to missing using "filter -S ." The filter function "PL>30" actually works, but in this example, the genotype is kept as at least one of those 3 PL values is above 30.

I was thinking of using Unix command lines that check if the sum of 2 of these 3 PL values are e.g. <30, anf if so the genotype is set to "missing", i.e. ./.:221,9,0. However, maybe there is already a solution within bcftools that I overlooked.

Thank you in advance for any help or suggestion!

Cheers

Bjoern

**Comment by pd3** [comment]
I am hesitant to go into this filtering issue seeing the motivation is flawed. The genotype likelihoods should not be used this way, moreover you are interpreting them incorrectly, the probability of the heterozygous genotype is 0.11
```
10**(-0.1*9) / (10**(-0.1*221) + 10**(-0.1*9) + 10**(-0.1*0)) = 0.11
```
Better idea is to filter based on AD.

**Comment by BjoernStelbrink** [comment]
Oh, thanks for the clarification and your suggestion.

Best wishes

Bjoern
