### ISSUE TITLE
bcftools compile error under fedora and centos

### ISSUE THREAD

**Issue by kelepiradam** [samtools/bcftools#1322]
Hi 
I am facing an issue with fedora and centos systems when compiling bcftools with perl filters and libgsl enabled. 

`
gcc -rdynamic   -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o consensus.o ploidy.o bin.o hclust.o version.o regidx.o smpl_ilist.o csq.o vcfbuf.o mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o vcfsort.o cols.o extsort.o ccall.o em.o prob1.o kmin.o  polysomy.o peakfit.o vcfplugin.o htslib-1.11/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lm -lz  -ldl  -lgsl -lgslcblas -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc -lpthread
gcc   -o test/test-regidx test/test-regidx.o regidx.o htslib-1.11/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lpthread -lz  -ldl 
/usr/bin/ld: main.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfindex.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: tabix.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfstats.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfisec.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfmerge.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfquery.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcffilter.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfsom.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfnorm.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfgtcheck.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfview.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfannotate.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfroh.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfconcat.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfcall.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: mcall.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcmp.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: gvcf.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: reheader.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: convert.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfconvert.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: tsv2vcf.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfcnv.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: HMM.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: consensus.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ploidy.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: bin.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: hclust.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: version.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: regidx.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: smpl_ilist.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: csq.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfbuf.o: relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: mpileup.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: bam2bcf.o: relocation R_X86_64_32S against symbol `seq_nt16_int' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: bam2bcf_indel.o: relocation R_X86_64_32S against symbol `seq_nt16_table' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: bam_sample.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfsort.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: extsort.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ccall.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: em.o: relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: prob1.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: polysomy.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: peakfit.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: vcfplugin.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(kstring.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(bgzf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(faidx.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile_net.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hts.o): relocation R_X86_64_32S against symbol `seq_nt16_table' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(multipart.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(probaln.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(realn.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(region.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(sam.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(synced_bcf_reader.o): relocation R_X86_64_32 against symbol `tbx_readrec' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(tbx.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(textutils.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(thread_pool.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(vcf.o): relocation R_X86_64_32S against symbol `bcf_type_shift' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(vcfutils.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_decode.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_encode.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_index.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_io.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_samtools.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_stats.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(mFILE.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(open_trace_file.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(rANS_static.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile_libcurl.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile_gcs.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile_s3.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(hfile_s3_write.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(knetfile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(bcf_sr_sort.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(header.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(md5.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: htslib-1.11/libhts.a(cram_codecs.o): relocation R_X86_64_32S against hidden symbol `ltf8_bytes' can not be used when making a PIE object
collect2: error: ld returned 1 exit status
make: *** [Makefile:216: bcftools] Error 1
`

All dependencies were installed according to the INSTALL file however no matter what I tried there is no way to compile bcftools with perl filters on. 
When perl filters is not enabled compilation lasts and produces a viable executable with libgsl enabled. 

Debian ubuntu and arch systems don't seem to cause any issues. 

My fedora and centos systems are all latest 32 and 8 respectively. Fedora uses gcc 10.2.1 and centos uses gcc 8. 

Can someone help with this?

**Comment by jmarshall** [comment]
This has come from some linker flags generated from your system's Perl installation, so removing `‑‑enable-perl-filters` will fix this.

Alternatively, to retain the Perl filter functionality, edit _config.mk_ and remove `-specs=/…/redhat-hardened-ld` (two instances) and this will link successfully. I haven't looked to see if there are any Red Hat bug reports related to _redhat-hardened-ld_.

**Comment by kelepiradam** [comment]
Hi 

Thanks for the quick return. It actually worked and saved me from using docker image for a simple filtering action.

**Comment by dvg-p4** [comment]
For posterity: `config.mk` is one of the files produced by `./configure`, so you need to make this edit *between* `./configure` and `make`.

**Comment by dvg-p4** [comment]
Also, would it be possible to prevent the addition of `-specs=/…/redhat-hardened-ld` from the scripts in this repo that build `config.mk`, so the manual edit isn't necessary?

**Comment by jmarshall** [comment]
On further investigation, the problem is that `-specs=/…/redhat-hardened-ld` (and the `-specs=/…/redhat-hardened-cc1` used at compile time) set the build up to produce a PIE position-independent executable, for ASLR purposes. As the rest of bcftools has not been built position-independent, the build fails.

It would be possible to build against _libhts.so_ (or otherwise get htslib object files that have been built with `-fpic`) and build the rest of bcftools's *.o files with the same PIE-selecting PERL_CFLAGS. This would produce a working `bcftools` executable that is built as PIE. So the fact that this doesn't work could be considered a bug in bcftools's Makefile's C flags usage.

However it's relatively esoteric and it would be non-trivial to support such a build in general. There is precedent for filtering undesired flags out of these Perl-provided options. Hence this is a good suggestion and is now PR #2138.

**Comment by jowodo** [comment]
this is the command I used between `./configure` and `make` to compile on Oracle Linux 9.3: 

```
./configure --enable-libgsl --enable-perl-filters --prefix=$PREFIX
sed -i -e "s@-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1@@g" -e "s@-specs=/usr/lib/rpm/redhat/redhat-hardened-ld@@g" config.mk # https://github.com/samtools/bcftools/issues/1322
make
```
