### ISSUE TITLE
How to filter out identical genotype calls in two samples

### ISSUE THREAD

**Issue by AntonYuryev** [samtools/bcftools#1324]
So far we tried:
##bcftools_filterCommand=filter -e 'FORMAT/GT[0,0]="0/1" & FORMAT/GT[1,0]="0/1"'
##bcftools_filterCommand=filter -e 'FORMAT/GT[0,0]="1/1" & FORMAT/GT[1,0]= 1/1"'
##bcftools_filterCommand=filter -e 'FORMAT/GT[0,0]="0/0" & FORMAT/GT[1,0]= 0/0"'
##bcftools_filterCommand=filter -e 'FORMAT/GT[0-1] ="0/1"'
##bcftools_filterCommand=filter -e 'FORMAT/GT[0-1] ="0/0"'
##bcftools_filterCommand=filter -e 'FORMAT/GT[0-1] ="1/1"'

None of these filters gave the correct result :(  Could you please advise?

**Comment by pd3** [comment]
Wat version of bcftools are you using? Make sure to use the latest version of bcftools for this, there were bug fixes.

Another problem is that the expression should have `&&` not `&`. This works for me:
```
$ bcftools view -H test.vcf
1	281	.	T	A	.	.	.	GT	0/0	0/0
1	282	.	T	A	.	.	.	GT	0/0	0/1
1	283	.	T	A	.	.	.	GT	0/0	1/1

$ bcftools filter -e 'FMT/GT[0]="0/0" && FMT/GT[1]="0/1"' test.vcf | bcftools view -H
1	281	.	T	A	.	PASS	.	GT	0/0	0/1
1	283	.	T	A	.	PASS	.	GT	0/0	1/1
```

Perhaps better would be to use for this task the `+contrast` plugin which can add the NOVELGT annotation when there is a genotype observed in one sample and not in the others:
```
$ bcftools +contrast -a NOVELGT -0 A -1 B test.vcf  | bcftools view -H -i 'NOVELGT!="."'
2	280	.	T	A	246	.	NOVELGT=B	GT	0/0	0/1
2	280	.	T	A	246	.	NOVELGT=B	GT	0/0	1/1
```
For this make sure to use the latest github code as there was a bug fixed just now https://github.com/samtools/bcftools/commit/67c95eeff392d01fce04df2d8c802fe41401c734
