### ISSUE TITLE
bcftools annotate : Inappropriate file type or format

### ISSUE THREAD

**Issue by kghimire09** [samtools/bcftools#1326]
Hi, so I have a vcf file that needs its chromosome name column annotated in the correct format. But when I run this command: bcftools annotate --rename-chr conversion_file.txt file.vcf.gz | bgzip rename.vcf.gz it gives me a Failed to open file file.vcf.gz : Inappropriate file type or format. I zipped the vcf file using bigzip. 

When I run this command on a different file it works. Any suggestions?

Thank you

**Comment by pd3** [comment]
Unrelated to this, what version of bcftools are you using? Try to run `htsfile file.vcf.gz` to see what format the program thinks it is. The program `htsfile` is included in the htslib package.
