### ISSUE TITLE
bcftools query output vcf

### ISSUE THREAD

**Issue by satzel** [samtools/bcftools#1329]
Hello,

is there a way to subset a vcf to extract GT information and get a vcf file as output?
When I use 

bcftools query -f '%CHROM \t %POS\t %ID\t %REF \t%ALT\t %QUAL\t %FILTER \t PL \t GTs: [\t%GT]\n' file.vcf 

I can't seem to be able to get a proper vcf file as output.
It looks like the output is a matrix which would be fine if there would be a way to add a vcf header. But even cutting a valid vcf header and adding it to the matrix file, bcftools view doesn't recognise the vcf and throws a parsing error.
Specifially: 
W::vcf_parse] FILTER ' PASS ' is not defined in the header
[E::vcf_parse] Could not add dummy header for FILTER ' PASS '

So I was hoping instead of some weird work around with pasting headers I can get a vcf directly from bcftools query?

thanks for your help
saskia

**Comment by pd3** [comment]
What do you mean by a "subset"? Subset by sample? `bcftools view` can do that. Or remove all annotations but GT? `bcftools annotate -x` can do that.

**Comment by satzel** [comment]
for the love of.... YES, bcftools annotate -x was what I was looking for. Thanks a million

saskia
