### ISSUE TITLE
bcftools allele depth '0,0' were called 'REF' instead of missing data? 

### ISSUE THREAD

**Issue by umngao** [samtools/bcftools#1332]
![image](https://user-images.githubusercontent.com/13056210/97254018-7d284580-17db-11eb-947a-fb2f3e8e2fb8.png)
I have a lot of REF calls when AD is '0,0', DP is decent.  These types of sites should be called './.' instead of '0/0' right?  I am using bcftools v1.11 (2020). And enabled -G - when making the bcftools call. 

`CM008368.1      378     .       G       C       102     .       DP=1351;VDB=0.749013;SGB=33.2439;RPB=0.00506497;MQB=1;MQSB=1;BQB=0.216942;MQ0F=0
;ICB=0.366451;HOB=0.00775182;AC=0;AN=2;DP4=630,350,34,16;MQ=60   GT:PL:DP:DV:AD:GQ        0/0:218,218,218:7:7:0,0:127`

**Comment by umngao** [comment]
Since DV is so high, suggesting non-reference depth 100%. They should rather be called 'ALT' or at the least missing data right?

**Comment by pd3** [comment]
There will be probably good explanation, but it does look odd. Any chance you could share a slice of the alignments at this position and the reference sequence?

**Comment by umngao** [comment]
![image](https://user-images.githubusercontent.com/13056210/97315698-f3a66100-1836-11eb-91c8-5b83460f8e35.png)
So does this help explain? Ref-genome wild inbred wheat. Sample, supposed to be the same sub-species of reference genome? 

The reference genome is a wild inbred wheat. The sample is another wild wheat, supposedly in the same sub-species.

**Comment by pd3** [comment]
This would have to be the actual alignment data (bam)

**Comment by umngao** [comment]
http://people.beocat.ksu.edu/~lianggao/owwc/troubleshoot_AD_00_ref_call/

**Comment by pd3** [comment]
I am unable to reproduce the problem:
```
$ bcftools mpileup -f GCA_002575655.1_Aet_v4.0_genomic.fna test.bam -r CM008368.1:378 | bcftools call -mv -G - | grep -v ^#

CM008368.1	378	.	G	A,T	156	.	DP=8;VDB=0.937661;SGB=-0.636426;MQSB=1.01283;MQ0F=0;AC=1,1;AN=2;DP4=0,0,3,4;MQ=60	GT:PL	1/2:218,98,86,135,0,126
```

In any case, note that bcftools assume haploid or diploid genomes. For polyploid genomes try freebayes.

**Comment by umngao** [comment]
This is a diploid inbred wild wheat. I was not able to reproduce the problem either using just one sample. But I was able to reproduce them using more samples. I will keep trying out what is the problem and make you reproducible dataset (hopefully small).

**Comment by umngao** [comment]
Here it is the reproducible dataset and code: 
http://people.beocat.ksu.edu/~lianggao/owwc/troubleshoot_AD_00_ref_call/small.subsel.bams/

> bcftools mpileup -q 20 -a DP,DV,AD,INFO/AD -b new.small.bam.list.txt -r CM008368.1:378 -f GCA_002575655.1_Aet_v4.0_genomic.fna | bcftools call -G - -mv -f GQ - > temp2.vcf &
> bcftools view temp2.vcf -s './small.subsel.bams/BW_01148_sort_rmdup.bam.sel1000' | awk '$2==378'
CM008368.1      378     .       G       C       264     .       DP=1351;AD=980,1;VDB=0.749013;SGB=33.2439;RPB=0.00506497;MQB=1;MQSB=1;BQB=0.216942;MQ0F=0;ICB=0.366451;HOB=0.00775182;AC=0;AN=2;DP4=630,350,34,16;MQ=60  GT:PL:DP:DV:AD:GQ       0/0:218,218,218:7:7:0,0:127

**Comment by pd3** [comment]
Just to let you know that this is work in progress. I have a fix but as this required changes in the core calling code, extensive testing is underway...

**Comment by pd3** [comment]
The code is now life, sorry about the longer delay.

**Comment by umngao** [comment]
Thanks for the fix. i haven't had time to check if the fix is working on my dataset. I will keep you posted if there is still an issue.
