### ISSUE TITLE
query -f and hyphens in field names [feature request: tag renaming]

### ISSUE THREAD

**Issue by pdl** [samtools/bcftools#1335]
Given a VCF with INFO fields containing hyphens, is it possible to use `bcftools query -f` to extract those fields?

```
bcftools query -f '%AC-XX'
```

returns values of the form `1-XX`, i.e. `${AC}-XX` not `${AC-XX}`.

The documentation doesn't seem from what I've found to indicate how to handle field names that need any sort of quoting/escaping.

(Observed on bcftools 1.7 Using htslib 1.7-2 in case it makes a difference).

**Comment by pd3** [comment]
First of all, 1.7 is very old, please update. Second, hyphens are not allowed in tag names by VCF specification.

**Comment by pdl** [comment]
Ah drat. It looks like I have a VCF (from gnomAD v3.1) which says it is v4.2 and that particular restriction was first explicitly specified (as far as I can find) in v4.3. Interestingly, `bcftools annotate -x` will accept hyphenated tag names, but I can't see a way to fix (rename) them with bcftools.

**Comment by pd3** [comment]
Tag renaming would be a worthwhile addition, I will mark this as a feature request.

**Comment by pd3** [comment]
A new option was added, VCF annotations can be now renamed using `bcftools annotate --rename-annots`. I hope this will be useful.
