### ISSUE TITLE
bcftools mpileup creates an empty output file

### ISSUE THREAD

**Issue by yeroslaviz** [samtools/bcftools#1336]
I try to run `bcftools` to create a vcf file of my data, but I keep getting empty output files

The command I use are

```
bwa mem -t14 -M ~/genomes/Sce.R64-1-1/bwaIndex/Sce.R64-1-1 HHgDNA1.R1.fastq.gz HHgDNA1.R2.fastq.gz | samtools view -buh - | samtools sort -@ 14 -o bamFiles/bwa/HHgDNA1.sorted.bam
samtools index bamFiles/bwa/HHgDNA1.sorted.bam
bcftools mpileup -A  -t 10 -Ou -f $REF_FASTA bamFiles/bwa/HHgDNA1.sorted.bam
```

while `$REF_FASTA` is the fastA file also used to create the bwa indexed genome. I know the output goes to `STDOUT`, but I'm still trying to figure it out. looking at the bam files i have ~99% mapped and properly paired reads.

Both `bcftools` and `samtools` are of the latest version.  I have tested it both on my linux server and my iMac desktop computer.

All I get is the header of the file, but nothing more.

any ideas what is going on?

thanks

**Comment by pd3** [comment]
You requested that the mpileup is created for chr `-t 10`. Is this one of the sequences in the BAM, i.e. maybe your sequences use the `chr10` convention? Note that `-t` streams the whole file and drops everything what does not match. Better is to use `-r` which uses index.
