### ISSUE TITLE
How to filter with formated INFO fields?

### ISSUE THREAD

**Issue by eat1000** [samtools/bcftools#1340]
I am trying to select variants using the vcf files provided by VEP that include annotation information of variants. There are two INFO fields that I am particularly interested in:

##INFO=<ID=Sift,Number=.,Type=String,Description="Prediction for effect of missense variant on protein function as computed by Sift. Format=Index|Sift_qualitative_prediction|Sift_numerical_value|Feature_id. The index identifies the missense variant. Qualitative prediction is tolerated or deleterious. The numerical value is the normalized probability that the amino acid change is tolerated, so scores nearer 0 are more likely to be deleterious.">
##INFO=<ID=Polyphen,Number=.,Type=String,Description="Prediction for effect of missense variant on protein function as computed by Polyphen (human only). Format=Index|Polyphen_qualitative_prediction|Polyphen_numerical_value|Feature_id. The index identifies the missense variant. Qualitative prediction (one of probably damaging, possibly damaging, benign or unknown). Numerical value which is the probability that a substitution is damaging, so values nearer 1 are more confidently predicted to be deleterious.">

I want to find variants with Sift_numerical_value<0.05 and Polyphen_numerical_value>0.15.  What would be the right filtering options for bcftools? I was using

bcftools filter -i 'Sift < 0.05 & Polyphen > 0.15' vep_data.vcf.gz -o my_variants.vcf

which seems not working correctly. 

Any suggestions will be highly appreciated!

**Comment by pd3** [comment]
Formatted fields are not supported, the only exception is the VEP-like annotations that can be queried using the [split-vep](http://samtools.github.io/bcftools/howtos/plugin.split-vep.html) plugin.

What you could do is to compile with perl expression support and write a custom filter. An example of such a script and its usage is here https://github.com/samtools/bcftools/blob/develop/misc/demo-flt.pl. Check the [INSTALL](https://github.com/samtools/bcftools/blob/develop/INSTALL) document for how to add support for perl at compilation time.
