### ISSUE TITLE
Best way to filter on allelic frequency when using multi-allelic calling mode?

### ISSUE THREAD

**Issue by charlesfoster** [samtools/bcftools#1341]
Hi,

I'd like to use `-m`/`--multiallelic-caller` mode with `bcftools call`. However, I'd like to only report alleles that have a certain proportion of reads supporting that allele. For example, consider the following line in the .vcf file:

>chr1	10000	.	A	G,T	225	.	DP=1279;ADF=0,767,0;ADR=0,367,1;AD=0,1134,1;VDB=0.998449;SGB=-0.693147;MQSB=1;MQ0F=0;AC=1,0;AN=1;DP4=0,0,767,368;MQ=60	GT:PL:DP:SP:ADF:ADR:AD	1:255,0,255:1135:0:0,767,0:0,367,1:0,1134,1

The total depth = 1279, number of reads supporting variant G = 1134, number of reads supporting variant T = 1. I might want to keep only those variants that are supported by >25% of the reads. In this case:

* Support for G = 1134/1279 = 88% (0.88)
* Support for T = 1/1279 = 0.08% (0.0008)

So, I'd only retain the G variant based on my >25% filter. To implement this filter, thus far I've tried:

`bcftools mpileup --count-orphans --no-BAQ -d 300000 -Q 0 -Ou --min-BQ 20 --annotate FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,INFO/AD,INFO/ADF,INFO/ADR -f reference.fasta sample.bam | bcftools call --ploidy 1 --keep-alts --keep-masked-ref --multiallelic-caller --variants-only -Ou --threads 8 | bcftools norm -m - | bcftools view -i "(INFO/AD[1]/INFO/DP) > 0.25" | bcftools norm -m + -Ov`

The command appears to do what I would like. However, is there a more efficient way to go about the issue other than having to use `bcftools norm` twice?

Thanks!

**Comment by pd3** [comment]
I see you ran `bcftools call --keep-alts`, that's why the second alternate allele was not removed automatically. I am afraid that there is currently no other way than going through the norm command as you've done. Maybe the `filter` command could be extended to support allele removal, not sure if it's worth the effort though? 

Unrelated, add `-Ou` to the `norm` and `view` commands as well.

**Comment by charlesfoster** [comment]
Thanks for your reply. Yep, I used `--keep-alts` because I want to keep both alts in a situation where both alternate alleles might be supported by >25% of the reads. However, agreed that this is a niche situation and probably not worth the effort of extending the `filter` command. I'm working with a very small genome so it doesn't take too much overhead to use `norm` twice. Good to know that my little workaround works, anyway.

Thanks, too, for the tip of adding `-Ou` to the commands.
