### ISSUE TITLE
Ploidy setting for durum genome (AABB)

### ISSUE THREAD

**Issue by xie186** [samtools/bcftools#1345]
Hi, @pd3 , thanks for developing bcftools. I'm working on durum genome which is a tetraploid species (BBAA). The current genome assembly have chromosome level sequence for each of the subgenomes (A and B): 
[ftp://ftp.ensemblgenomes.org/pub/plants/release-48/fasta/triticum_turgidum/dna/
](url)
Although it has tetraploid genome, I'm thinking we should consider it as `diploid` regarding the parameter '--ploidy' because we have the assembly for the subgenomes. 
Could you please help me check whether my understanding is correct or not? 
Only problem is the the sequences from `Triticum_turgidum.Svevo.v1.dna.chromosome.Un.fa.gz`: 
[ftp://ftp.ensemblgenomes.org/pub/plants/release-48/fasta/triticum_turgidum/dna/Triticum_turgidum.Svevo.v1.dna.chromosome.Un.fa.gz](url)
Sequence (498,719,471 bps) from this contig is the one that can not be assigned to any of the subgenomes.  

Could you please let me know you comments? 
Thanks in advance,
Shaojun

**Comment by pd3** [comment]
The `--ploidy` parameter is not about the reference genome in the fasta file, but how man alleles one can encounter at any given position and what allele fractions can we expect. For diploid genomes, we know that we are sampling reads from two chromosomal copies, therefore for heterozygous genotypes we can expect two alleles sampled in 1:1 ratio (safe for statistical fluctuations). On the other hand, for tetraploid genomes the two alleles could appear in 1:1 as well as in 1:3 ratio, not mentioning there could be more than two alleles at the position. For this reason, I don't recommend using bcftools for this task. Please check freebayes instead, it supports polyploid genomes.

**Comment by xie186** [comment]
Thank you!
