### ISSUE TITLE
corp dumped when fill-tags AF,MAF

### ISSUE THREAD

**Issue by hungweichen0327** [samtools/bcftools#1347]
Dear community,

I want to update the information of AF and add MAF tags. The code was below:
``
bcftools +fill-tags SNP_bcftools_no_mono.vcf.gz --output-type z -o SNP_bcftools_no_mono_add_MAF.vcf.gz -- -t AF,MAF
``

However, I got the error:
``
WARNING: bcftools version mismatch .. bcftools at 1.10.2, the plugin "fill-tags" at 1.5-5-geeef386
/var/spool/torque/mom_priv/jobs/134896.gc3.SC: line 11: 30148 Segmentation fault      (core dumped) bcftools +fill-tags SNP_bcftools_no_mono.vcf.gz --output-type z -o SNP_bcftools_no_mono_add_MAF.vcf.gz -- -t AF,MAF
``

As I know, the AF info. can be updated using ``bcftools +fill-tags -- -t AF`` mentioned in  #1189. So I don't think the core dumped is due to existed AF info. in input.vcf file.

Look forward for your response. Thank you.

**Comment by pd3** [comment]
The warning tells you that the plugin is very old (1.5) and was compiled with a different version of bcftools from what you are running. Best advice I can give is to install the latest version as described here http://samtools.github.io/bcftools/howtos/install.html and try again. If the problem persists, a small test case to reproduce the problem will be necessary.
