### ISSUE TITLE
`bcftools +split-vep` fails on VCF (but works on BCF)

### ISSUE THREAD

**Issue by tedil** [samtools/bcftools#1349]
When trying to run `bcftools +split-vep --annotation "ANN" -c IMPACT -i "INFO/IMPACT[*] ~ 'MODIFIER'"` on a VCF file, such as [example VCF](https://gist.github.com/tedil/468caf092cc175798f2214e7a9875bd1#file-spltivep-vcf), bcftools fails with:
```
[E::bcf_write] Broken VCF record, the number of columns at chr1:817186 does not match the number of samples (0 vs 1)
```
However, running the exact same command on [example BCF](https://gist.github.com/tedil/468caf092cc175798f2214e7a9875bd1#file-splitvep-bcf) works as expected.

(Also tested with the corresponding bgzipped VCF (generated with `bcftools view splitvep.vcf -Oz`) which, too, fails.)

```
> bcftools --version
bcftools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

> uname -a
Linux 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
```

**Comment by pd3** [comment]
This was a curious problem, now fixed in git. Thanks for the bug report!
