### ISSUE TITLE
Generate consensus for a target region

### ISSUE THREAD

**Issue by kpatankar** [samtools/bcftools#1350]
Greetings,

I am trying to generate a vcf and a consensus sequence for a haploid organism. I am using samtools/bcftools version 1.11

1. VCF calling
`bcftools-1.11/bcftools mpileup -B -d 1000000 -L 1000000 -f refseq.fasta -r refseq:4000-9000 Sample.sorted.bam | bcftools-1.11/bcftools call --ploidy 1  -vc -Ov - > Sample.SAMtools.vcf`

This vcf is successfully generated

2. Compress vcf using bgzip

`bgzip Sample.SAMtools.vcf`

3. Generate index for vcf.gz

`bcftools-1.11/bcftools index Sample.SAMtools.vcf.gz`

4. Consensus calling 
`samtools-1.11/samtools faidx refseq.fasta refseq:4000-9000 | bcftools consensus Sample.SAMtools.vcf.gz > Sample.consensus.fa`

The step 4 fails with an error message `Segmentation fault (core dumped)` 

Please let me know how to resolve this error.

Thanks in advance !

**Comment by pd3** [comment]
Unfortunately this does not provide enough information to help, any chance you could provide a small test case to reproduce the segfault?
