### ISSUE TITLE
Changes in DS and GP fields after view command (v. 1.10.2)

### ISSUE THREAD

**Issue by jcgrenier** [samtools/bcftools#1359]
Hello developpers,

I discovered some strange behaviors today while running a simple bcftools view command :
For example : 
`bcftools view -i 'INFO>.7' -Oz $f.vcf.gz > INFO_0.7/$f.INFO_0.7.vcf.gz`

before :
XX      XXXX rsXXX       A       G       .       PASS    RefPanelAF=0.585109;AN=8004;AC=1979;INFO=0.790511       GT:DS:GP        1/1:2:0,0,1     0/0:0:1,0,0     0/1:1.15:0,0.85,0.15    0/0:0:1,0,0     0/0:0:1,0,0
after :
XX      XXXX rsXXX       A       G       .       PASS    RefPanelAF=0.585109;AN=8004;AC=1979;INFO=0.790511       GT:DS:GP        1/1:0:0,0,0     0/0:0:0,0,0     0/1:0:0,0,0     0/0:0:0,0,0     0/0:0:0,0,0

Thanks for your help fixing this!

JC

**Comment by pd3** [comment]
What a curious behavior! Any chance you could share a fragment of the VCF, including the header, to test and reproduce the bug?

**Comment by jcgrenier** [comment]
Hello Petr,

I will send you an example by email. 

Thanks a lot for looking into this!

Best,
JC

**Comment by jcgrenier** [comment]
Hi again @pd3 ,

I was able to solve my issue by loading the corresponding htslib module on my server. So bcftools and htslib needed to be under the same version (1.10.2). 

Thanks!
JC
