### ISSUE TITLE
bcftools merge error: could not load index

### ISSUE THREAD

**Issue by nrcombs** [samtools/bcftools#1360]
Hi there,

I've run into an issue with the `bcftools merge` utility and am hoping for feedback on how to resolve. I'm not sure whether it is user error or a bug in the program. 

I have three VCF files for a non-model species that I'd like to merge into a single VCF file. Each file corresponds with a unique set of individuals and a subset of SNPs that is overlapping among files.

I first compress my VCF files in bgzip format with 
`bgzip -ci infileA.vcf > outfileA.vcf.gz`

I next attempt to merge the files with
` bcftools merge outfileA.vcf.gz outfileB.vcf.gz outfileC.vcf.gz`

But I get an error message that the index files cannot be found, even though they are in the same directory: `Failed to open outfileA.vcf.gz: could not load index`

I've seen posts elsewhere that discuss this error message when attempting to use other tools in bcftools...some of these posts describe the issue as resulting from the system attempting to open too many files at once. But the system I am working on allows over 4,000 files to be open at once, and either way I am working with only six files (including the compressed VCF files and index files).

When I check the format of my files with `htsfile` I get the following:

    htsfile outfileA.vcf.gz
    outfileA.vcf.gz: VCF version 4.2 BGZF-compressed variant calling data

    htsfile outfileA.vcf.gz.gzi
    outfileA.vcf.gz.gzi: unknown data

Are the index files created via `bgzip` inappropriate for use with `bcftools merge`? Thanks!

**Comment by pd3** [comment]
The correct way is:
```
bcftools -Oz -o out.vcf.gz in.vcf
bcftools index out.vcf.gz
bcftools merge ...
```

**Comment by nrcombs** [comment]
Thanks for your help @pd3!
