### ISSUE TITLE
bcftools mpileup seg fault for reads with only 1 match

### ISSUE THREAD

**Issue by delafoy** [samtools/bcftools#1362]
Hi there,
I have an issue with ```bcftools mpileup```.
It seems that softclipped reads with only one match create a seg fault.
For example, reads with CIGAR code 50S1M98S ; 40S1M108S ; 60S1M88S

```
bcftools mpileup -f NC_045512.2.fasta bug_bcftool_mpileup1.11.sam.txt
```
see ```https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2?report=fasta``` for NC_045512.2.fasta
and  bug_bcftool_mpileup1.11.sam.txt is attached 

This error does not occur with 1.10.2

Hope it can be useful for everyone.
[bug_bcftool_mpileup1.11.sam.txt](https://github.com/samtools/bcftools/files/5697629/bug_bcftool_mpileup1.11.sam.txt)

**Comment by pd3** [comment]
Thank you for reporting the issue, just want to add more information. 

The problem is caused by the read V1:1:HJ5T3DRXX:1:2255:20663:5807 which has **all** bases soft-clipped. Out of curiosity, what program was used to map the reads?

The problem can be traced to the pileup engine in htslib. In this call https://github.com/samtools/bcftools/blob/develop/bam2bcf.c#L189 the value of p->qpos is incorrectly set to 14511 but the read is only 149 bases long.

**Comment by delafoy** [comment]
Hi,

Thanks for your reply.
The programm used to map the reads was bwa 0.7.17 piped to samtools ampliconclip 1.11

Best regards

**Comment by jkbonfield** [comment]
My guess is this was an ampliconclip thing then as I've never seen this behaviour from bwa.

@whitwham, would it make sense to get ampliconclip to mark a read as unmapped when it has no remaining bases left after clipping?  (Apologies if I'm maligning it and it is infact another novel bwa "feature").

**Comment by whitwham** [comment]
> @whitwham, would it make sense to get ampliconclip to mark a read as unmapped when it has no remaining bases left after clipping? (Apologies if I'm maligning it and it is infact another novel bwa "feature").

Yeah, we discussed this at the time.  I didn't want to override the aligner's/assembler's marking of the read as mapped.

There are a couple of options you can set with **ampliconclip** that might help, _--filter-len_ and _--fail-len_.  Setting _filter-len_ will filter out any read that ends up being below a certain size eg `--filter-len 0` will not write any reads that have no unclipped bases.  The other option, _fail-len_, works in a similar way but marks the read as QC_FAIL instead.  I think **mpileup** would work with that.

Of course, I could just add a _mapped-len_ option that works in a similar way to _fail-len_.

**Comment by daviesrob** [comment]
This looks like it was caused by a [regression in HTSlib](https://github.com/samtools/htslib/commit/a2fdf3b2) which stopped zero-length reads from being removed from the pileup.  I think samtools/htslib#1201 should fix it.

**Comment by delafoy** [comment]
Thanks everyone, 
the work you do for the community is awesome!
