### ISSUE TITLE
bcftools: END (15195) smaller than POS (0)

### ISSUE THREAD

**Issue by cagaser** [samtools/bcftools#1366]
Hello developers, 

We have a VCF file generated by SMOOVE (LUMPY). We then used DUPHOLD to annotate FP SVs. 
The later tool complained about the END (15195) being smaller than POS (4294967296):
```
[W::vcf_parse_info] INFO/END=15195 is smaller than POS at chr17_GL000205v2_random:4294967296
weird variant:Variant(chr17_GL000205v2_random:4294967296 N/<DUP>)
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

This the offending line in the SMOOVE VCF:
```
chr17_GL000205v2_random 0       7317    N       <DUP>   675.05  .       AC=1;AN=2;CIEND=-30,395;CIEND95=-2,244;CIPOS=0,506;CIPOS95=0,355;END=15195;IMPRECISE;PE=6;SR=0;STRANDS=-+:6;SU=6;SVLEN=15195;SVTYPE=DUP   GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:99:675.05:-69,-1,-11:418:340:77:339:76:168:2:55:171:19:0.18
```
We tried to remove this line from the VCF using BCFTOOLS (v1.9) and DUPHOLD managed to complete it's job. 
However, the version 1.10 (and 1.11) did not remove this line but shows instead the warning message: 

```
[W::vcf_parse_info] INFO/END=15195 is smaller than POS at chr17_GL000205v2_random:4294967296
```

Shouldn't bcftools be able to parse the position 0 like the previous version (1.9)? 

Thanks in advance.

**Comment by pd3** [comment]
VCF specification does not allow POS=0 coordinates. As for why the program did not crash previously, that should be considered a lucky coincidence, not a feature. The easy solution is to use awk for removing such records, this should work:
```
cat file.vcf | awk '$2!="0"' > fixed.vcf
```

**Comment by lentil824** [comment]
Hello developers,

In my case, duphold didn't complain anything about the vcf file, but when I tried to use bcftools after the duphold, the error message came out: 
`[W::vcf_parse_info] INFO/END=127373 is smaller than POS at Chr1:662360`

Since the SVTYPE was a TRA, it involved two different chrs (reason of the issue). I had tried the cat/awk solution mentioned above, but it didn't work. The bcftools I have is bcftools-1.12. Any suggestions to get around this error? 

Thanks,
Susan

**Comment by celesteimnskirakira** [comment]
> Hello developers,
> 
> In my case, duphold didn't complain anything about the vcf file, but when I tried to use bcftools after the duphold, the error message came out: `[W::vcf_parse_info] INFO/END=127373 is smaller than POS at Chr1:662360`
> 
> Since the SVTYPE was a TRA, it involved two different chrs (reason of the issue). I had tried the cat/awk solution mentioned above, but it didn't work. The bcftools I have is bcftools-1.12. Any suggestions to get around this error?
> 
> Thanks, Susan

hi Susan,
i have the same problem in pigs genome, could u plz tell me how u solve this question?

**Comment by pd3** [comment]
@celesteimnskirakira Which bcftools/htslib version are you using? If the latest github version, can you please share a snippet of your VCF, the header and the offending record, for us to take a look at?
