### ISSUE TITLE
[bcf_sync] incorrect number of fields (0 != 5) at 0:0

### ISSUE THREAD

**Issue by Carol-Symbiomics** [samtools/bcftools#1369]
Hi everyone! I really hope you can help me cause I've been able to find a solution to this problem although there are many posts out there referring to a similar problem

I'm trying to convert my vcf file v 4.1 (generated by VCFtools) to a BCF format using the most basic command.

`bcftools view pver.14reef.nooutliers.vcf -O b -o pver.14reef.nooutliers.bcf`

but after running the command I'm getting this error
`[bcf_sync] incorrect number of fields (0 != 5) at 0:0`

Could someone please let me know what is wrong? I have bcftools v. 0.1.19-96b5f2294a. But I have not been able to install a newer version on my machine

**Comment by jkbonfield** [comment]
Bcftools 0.1.19 is positively ancient!  It was released in 2013.  We've had over a dozen releases since then.

Please try using a modern version (see the releases link from this github repository) as we do not support the older ones.

**Comment by pd3** [comment]
Please see detailed installation instructions here http://samtools.github.io/bcftools/howtos/install.html or here http://www.htslib.org/

**Comment by jmarshall** [comment]
Also: If you are using Debian, Ubuntu, Fedora, or CentOS, you will be able to install a fairly recent version of bcftools via your OS's usual `apt`/`apt-get` or `dnf`/`yum` package commands. If you're using [Homebrew](https://brew.sh/) or [Conda](https://bioconda.github.io/), you can install the latest bcftools version easily. (There was until recently a problem with conda whereby it would install an older version by default, but this was fixed for htslib/samtools/bcftools last week.)

**Comment by pd3** [comment]
Closing the issue as not relevant to the current code base.
