### ISSUE TITLE
Filter by BED: bcftools merge and bcftools view filter differently

### ISSUE THREAD

**Issue by gabeng** [samtools/bcftools#1374]
Affected versions: 1.9..1.11.0 (from bioconda).

Variants that are located exactly at the boundary or overlapping the boundary of a target region in a BED file are filtered out when using `bcftools merge -R test.bed`. The same variant is retained when `bcftools view -R test.bed` is used.

Example variant in test_1.vcf and test_2.vcf:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG001
10	43595836	rs57003029	AT	A	50	PASS	GT	0/1
```

BED file `test.bed`:
```
10	43595836	43596240
```

This command returns the variant:
`bcftools view -R test.bed test_1.vcf`

This commands does not return the variant:
`bcftools merge -R test.bed test_1.vcf test_2.vcf`

When changing the BED file to
```
10	43595835	43596240
```
`bcftools merge` outputs the variant. 

BTW, `bcftools view` even outputs this variant:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG001
10	43595835	rs57003029	GAT	A	50	PASS	GT	0/1
```

**Comment by pd3** [comment]
Uh, this is caused by `view` pulling in overlapping records while `merge` operating strictly on POS. The behavior cannot be changed easily with merge. I updated the documentation to describe this behavior. Thank you for raising the issue.

**Comment by gabeng** [comment]
Do you know if any other bcftools commands are affected? Any plans to make this consistent across commands in the future?

**Comment by pd3** [comment]
OK, I pushed a temptative fix. Can you please test it and see if it behaves as expected on larger data?
