### ISSUE TITLE
Missing of SNPs with low VAF

### ISSUE THREAD

**Issue by nmc-ei** [samtools/bcftools#1375]
Hi everyone!

I got vcf files by bcftools from rna-seq bam files mapped by star.
$ parallel -j 24 'bcftools mpileup -B -Q0 -Ou --max-depth 100000 -r{} -a FORMAT/AD -f ~/database/GRCh37.fa ~/input/input.bam | bcftools call -mv -Ov -o ~/vcf/{}.vcf.txt' ::: {1..22} X

Let ref and alt be AD right value and left value, I calculated VAFs.
VAF = alt/(ref+alt)

Even in 1 copy chromosomes, there are no SNPs with low VAF(<0.18).

I'm considering about setting of mapping softwere too, however if bcftools has filters control low VAF, please tell me it.

Thank you.

**Comment by pd3** [comment]
I am not sure what the exact question / problem is, are you interested in seeing variants with VAF<0.18? `bcftools call` is a germline variant caller and makes the assumption of sampling from diploid genome, i.e. roughly binomial distribution centered at VAF=0.5. However, you can start with the raw output from `bcftools mpileup` and process it using it a custom script.

**Comment by nmc-ei** [comment]
Thank you very much!!

> are you interested in seeing variants with VAF<0.18?
 Yes. I want to get all sites where 2/more kind of nucleotides are mapped.

I runed 'bcftools mpileup' without 'bcftools call', then vcf files contained <*> on all ALT.
Further, most of the rows have only 1 kind of nucleotide which REF or ALT. 
Can I filter these using only 'bcftools mpileup'?

**Comment by pd3** [comment]
The symbolic <*> alt allele is a placeholder for alleles not seen in the pileup, which allows to represent genotype likelihoods FMT/PL even for non-variant sites. They will be removed if you run through `call -A -m`, leaving out `-v`. Or you could work directly with the raw mpileup output.

**Comment by nmc-ei** [comment]
Thank you very much!!
