### ISSUE TITLE
consensus sequence is shorter than expected

### ISSUE THREAD

**Issue by YanaHrytsenko** [samtools/bcftools#1377]
Hello,
I am trying to get the consensus sequence for a specific sample with BCFtools. The command is as follows:

```
module load BCFtools/1.6-foss-2016b  

ref_seq="Homo_sapiens.GRCh38.dna.chromosome.7.fa.gz"

in_vcf="ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"

out_fa="chromo_7_consensus_seq_for_HG00268.fa"

sample_id="HG00268"

cat ${ref_seq} | bcftools consensus --sample ${sample_id} ${in_vcf} > ${out_fa}
```

This seems pretty straightforward, however, the output from this script is only  39 120 base pairs (in fact, there are two different outputs: one is stored in the <out_fa> and another one (160 639 base pairs long) is just printed to the screen and I am not sure what that second output is), which is wrong, because the typical human chromosome 7 is approximately 170 million base pairs long.
Could you please let me know if this is not the right way to get the consensus sequence or point me in the right direction?
Thank you.

**Comment by pd3** [comment]
Nothing should be printed on screen, the output should be all in `$out_fa`. The version 1.6 is old, there were quite a few fixes since then. Can you retry with the latest version?

**Comment by YanaHrytsenko** [comment]
Hi @pd3 ,
thank you for your reply, I changed to the lates version:

```
module load BCFtools/1.11-iccifort-2019.5.281

ref_seq="Homo_sapiens.GRCh38.dna.chromosome.7.fa.gz"

in_vcf="ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"

out_fa="chromo_7_consensus_seq_for_HG00268.fa"

sample_id="HG00268"

cat ${ref_seq} | bcftools consensus --sample ${sample_id} ${in_vcf} > ${out_fa}
```

However, the issue persists. There are two outputs (one to a specified file and one just to a terminal screen) and the number of base pairs is:
wc -m chromo_7_consensus_seq_for_HG00268.fa 
**39767** chromo_7_consensus_seq_for_HG00268.fa


I am not sure if git can handle attachments of fastq and fast format but if that would be useful I could send you the files. Please advise.
Thank you.

**Comment by pd3** [comment]
OK, can you please create a small test case and send me details by email? The address is on my profile page. Thank you

**Comment by YanaHrytsenko** [comment]
Hi @pd3,
I am putting an email together with a sample test case. However, the sequence file is large even in a compressed format and thus I would need to share it as a google drive link. Do you perhaps have a gmail account instead?
Thank you.

**Comment by pd3** [comment]
Hi @YanaHrytsenko, sorry, I missed this. Yes, I have a gmail account. Can you please send me an email to the address listed on my profile page and we can go from there?

**Comment by YanaHrytsenko** [comment]
@pd3 I am all set :) everything works just fine. Thank you.
