### ISSUE TITLE
Allow --mask to lower-case regions instead of only replacing them with a character

### ISSUE THREAD

**Issue by kpj** [samtools/bcftools#1382]
The new implementation of the `--mark-snv` parameter (see #1381) is very close to another feature which would be useful for us.
Would it be possible to also use it like the `--mask parameter`, i.e. with a bed file which specifies regions to convert to lower/upper case?

An elegant solution might be to allow multiple masking parameters with different "actions". That way, the call `bcftools consensus --mask low_coverage.bed N --mask special_regions.bed lc ...` would replace regions of low coverage with `N` and convert interesting regions to lower case.

Our use case is that we like to mark bases within certain coverage ranges in the output consensus file with lower case letters, while all other bases are in upper case.

**Comment by pd3** [comment]
This is now done. Please try it out!

**Comment by kpj** [comment]
Thanks a lot for this!

I tried it out on a few of my samples, and it works nicely.
I am also very happy to see that `--mask mymask.bed --mask-with Y --mask mymask.bed --mask-with lc` inserts `yyyyyyy...` into the consensus.

I will try it on more samples in the following days!
