### ISSUE TITLE
[W::bcf_hdr_check_sanity] PL should be declared as Number=G

### ISSUE THREAD

**Issue by shbrainard** [samtools/bcftools#1383]
I have a VCF file generated by v2 of TASSEL's GBS pipeline. 

When I convent this file to a .bcf file using bcftools, I get the warning: 

`[W::bcf_hdr_check_sanity] PL should be declared as Number=G
`

The header of this file is: 

```
##fileformat=VCFv4.0
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the reference and alternate alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth (only filtered reads used for calling)">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=3,Type=Float,Description="Normalized, Phred-scaled likelihoods for AA,AB,BB genotypes where A=ref and B=alt; not applicable if site is not biallelic">
```

Reading the v4.2 VCF specifications, it does seem like it should be G, and indeed, the VCF files I generated using Stacks (which are formatted for v4.2) conform to this convention.  Clearly TASSEL has not updated its output scheme since v4.0, and maybe these conventions changed with VCF v4.2?

In any event, I have a sed command:

`sed 's/PL,Number=./PL,Number=G/g' oldFile.vcf > newFile.vcf 
`

That works, but I was wondering if there is any program part of samtools that can be used to arbitrarily edit VCF headers to deal with these kinds of errors, ideally when they are gzipped?

Thanks very much for any advice.

**Comment by pd3** [comment]
Take a look at `bcftools reheader`
