### ISSUE TITLE
Comparing -min-DP in vcftools with filter -i 'FORMAT/DP>10' in bcftools

### ISSUE THREAD

**Issue by shbrainard** [samtools/bcftools#1384]
I have just transitioned from using vcftools to bcftools, and am curious about how my previous methods of filtering translate.

I previously often filtered for average depth:

vcftools --vcf unfiltered.vcf --min-meanDP 10 --out filtered-DP10

I'm unclear if there is a similar command in bcftools.  This command:

bcftools filter -i 'FORMAT/DP>10' unfiltered.bcf.gz -Ov -o filtered-DP10.vcf

Is described as including only sites for which FORMAT/DP>10, which I would interpret to mean *all* individuals at that site have to have a depth greater than 10 to be included.  Is that correct?

If so, is there a reason --min-meanDP was deprecated and if not, is there a way to reproduce its functionality in bcftools?

Thanks!

**Comment by pd3** [comment]
The expression`-i 'FMT/DP>10'` includes sites for which at least one sample has DP>10. If you want the opposite, use the inverse logic `-e 'FMT/DP<=10'`. One can also use functions, for example `-i 'MEAN(FMT/DP)>10'`. Please see  http://samtools.github.io/bcftools/bcftools.html#expressions for more. Best is to run a little experiment and see what happens, e.g.:
```
bcftools query -f '[ %DP]\n' -i 'FMT/DP>10' test.vcf | head
bcftools query -f '[ %DP]\n' -e 'FMT/DP<=10' test.vcf | head
```

**Comment by shbrainard** [comment]
Got it, that's very helpful.

The URL you provided explains the principles of using expressions very clearly.  Is there, however, a complete list somewhere that defines all the functions that can be applied to `FORMAT` fields (e.g., do `MODE()`, or `MEDIAN() `also exist?)

In addition, is it true that as a general rule, functions such as MEAN() will operate on every genotype at each site?  If so, is there a way to subset their application to a defined set of SAMPLE IDs, or a second boolean condition applied to some other FORMAT ID (e.g., "include sites where the mean genotype quality, of genotypes with total read depth > 10, is greater than 20")?  Or, alternatively, can you apply filtering based on one function to a subset of sites identified with a second function (e.g., "exclude sites with a mean DP < 10, if they also have a MAF < 0.05")?

Similarly, I assume that any filtering that doesn't use functions (e.g., `-i 'FMT/DP>10'`) is set by default to include or exclude sites where at least one sample meets the criteria (as in the specific example I originally asked about).  Is there a way to modify that behavior, such that _n_ samples need to meet the criteria in order for the site to be included / excluded?

Thanks again!  This tool seems great, and is clearly much more flexible than vcftools!!

**Comment by pd3** [comment]
Please check the link I sent, it's all there. Just search e.g. for MEDIAN on that page, two bullet points above is discussed how to select samples, N_PASS function then for the last point. Also check a small tutorial here http://samtools.github.io/bcftools/howtos/filtering.html. I hope all the information is there, but if you still find the documentation insufficient, please help us improve it.

**Comment by shbrainard** [comment]
Thanks very much.  I looked through these resources and found them very helpful.

I do have a remaining question about unintuitive results I'm getting when comparing `|` and `||`

In the man page these are described as follows:

> `QUAL>10 |  FMT/GQ>10`   .. true for sites with `QUAL>10` or a sample with `GQ>10`, but selects only samples with `GQ>10`
> `QUAL>10 || FMT/GQ>10`   .. true for sites with `QUAL>10` or a sample with `GQ>10`, plus selects all samples at such sites
 
However, I don't seen any difference in the output from these two commands, which filter for markers with no more than 2 alleles, and genotype depth <= 20: 
```
bcftools filter unfiltered_newHeader.bcf.gz -e 'N_ALT >= 2 | FMT/DP<=20' | grep \#CHROM | tr -dc : | wc -c #672
bcftools filter unfiltered_newHeader.bcf.gz -e 'N_ALT >= 2 || FMT/DP<=20' | grep \#CHROM | tr -dc : | wc -c #672
```
All sample IDs contain a colon, so that is the method I'm using for counting the number of remaining samples.  As I understand the manual, the first command should filter our samples with depth <=20.  I can separately test to confirm that indeed, there are samples which have read depth <20 at many markers:

```
wc -l < unfiltered.bcf.gz #30310
bcftools filter unfiltered.bcf.gz -e 'FMT/DP<=20' | wc -l #116
```

Any advice on how I am misinterpreting `|` and `||` would be appreciated.  Thanks!

**Comment by shbrainard** [comment]
Since the issue I am currently having no longer applies to the original question raised in this issue, and relates to a more general question about filtering out samples instead of sites, I have created a new issue for this problem here: https://github.com/samtools/bcftools/issues/1391#issue-798620000.  Since my initial question in this issue is resolved I'm closing this issue.
