### ISSUE TITLE
N_ALT not work in bcftools filter

### ISSUE THREAD

**Issue by biozzq** [samtools/bcftools#1388]
Dear all,
When I used the following commands to mark the low quality variants, I found the parameter `N_ALT` not work as the following variant (the number of alternative allele is two, thus should be masked as lowQ) has been masked as PASS; If I missed something about this parameter, please tell me. Thank you.

`bcftools-1.11/bin/bcftools filter --threads 4 -r ${chr} -s SnpGap -g 3 -s lowQ -e 'INFO/QD < 2.0 || INFO/FS > 60.0 || INFO/MQRankSum < -12.5 || INFO/ReadPosRankSum < -8.0 || INFO/SOR > 3.0 || INFO/MQ < 40.0 || N_ALT > 1 || TYPE = "indel"' -s miss -e 'F_MISSING >= 0.1' ${dir}/${chr}.vcf.gz -o ${chr}.mark.vcf.gz -O z`

`5       4269    .       C       T,A     1166.35 PASS    AC=1,4;AF=0.001961,0.007843;AN=510;BaseQRankSum=-3.067;......`

Best wishes,
Zheng zhuqing

**Comment by pd3** [comment]
Only one `-i` or `-e` expression can be used, and cannot be combined. What happened is that the second was used instead of the first one. Will update the code to throw an error when this is attempted.

**Comment by biozzq** [comment]
Dear @pd3 

Do you mean that I have used two `-e` expression? I know that we can not use `-i` and `-e` together in one command, but when using two `-e` expression, it did not report me any errors. I also try to add the `F_MISSING >= 0.1` to the first `-e` expression, that is `-s lowQ -e 'INFO/QD < 2.0 || INFO/FS > 60.0 || INFO/MQRankSum < -12.5 || INFO/ReadPosRankSum < -8.0 || INFO/SOR > 3.0 || INFO/MQ < 40.0 || N_ALT > 1 || TYPE = "indel" || F_MISSING >= 0.1'`, the results look OK.

Best wishes,
Zheng zhuqing

**Comment by pd3** [comment]
Yes, it did not report an error but should have. The program simply takes the one seen last. This lack of checking is now fixed.

**Comment by biozzq** [comment]
Thank you very much.
