### ISSUE TITLE
bcftools mpileup --max-depth

### ISSUE THREAD

**Issue by Silvia-lme** [samtools/bcftools#1389]
According to the manual a default for the --max-depth is 250, which mean that only 250 reads per-file are considered at a position.
Please could somebody explain me how it works when I am using one multi-sample bam file (merge file of 130 samples). Does it work with all 130 individuals or it stop when it reach 250 reads at position, doesn't matter that it counted only e.g. first 10 individuals (when each individual have 25 reads at particular position).

**Comment by pd3** [comment]
I guess you already found the answer to your question? From the manual page: 

```
 -d, --max-depth INT
    At a position, read maximally INT reads per input file. Note that the original samtools mpileup
    command had a minimum value of 8000/n where n was the number of input files given to mpileup.
    This means that in samtools mpileup the default was highly likely to be increased and the -d parameter
    would have an effect only once above the cross-sample minimum of 8000. This behavior was problematic
    when working with a combination of single- and multi-sample bams, therefore in bcftools mpileup the user
    is given the full control (and responsibility), and an informative message is printed instead [250] 
```

http://samtools.github.io/bcftools/bcftools.html#mpileup
