### ISSUE TITLE
Regions file does not work with a bcf

### ISSUE THREAD

**Issue by AlistairNWard** [samtools/bcftools#1390]
I have a file test.vcf.gz and converted to a bcf file, so both `test.vcf.gz` and `test.bcf` are identical. If I run the command:

`bcftools view -R test.vcf.gz test.bcf`

I am returned all of the entries in test.bcf, as expected. If, however, I run:

`bcftools view -R test.bcf test.bcf`

the command fails with the following:

![Screen Shot 2021-02-01 at 1 11 11 PM](https://user-images.githubusercontent.com/523111/106500026-5723d880-648f-11eb-8ae4-e08a611ba7ae.png)

The bcf file is indexed. It appears that the `-R` option does not work if provided with a bcf file.

**Comment by pd3** [comment]
Uh, `-R` cannot be used with BCF. However, there is a specialized command just for this, please check `bcftools isec` http://samtools.github.io/bcftools/bcftools.html#isec

**Comment by AlistairNWard** [comment]
@pd3 Is there a reason that BCF files can't be used? The reason that I don't use isec is that speed is important. There is a significant difference in the speed of running:

`bcftools isec A B -n =2 -w 1`

and

`bcftools view -R A B`

The results are identical, but run time is not.

**Comment by daviesrob** [comment]
If you're using `bash`, you can work around this using [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html):

```
bcftools view -R <(bcftools view test.bcf) test.bcf
```

The `<(bcftools view test.bcf)` part will convert the BCF file to VCF, and output it to a pipe that the `-R` option can read.

The code behing the `-R` option already does format detection to spot VCF, so in theory it might not be too hard to make it support BCF natively.

**Comment by AlistairNWard** [comment]
Thanks @daviesrob. We have a similar workaround coded in at the moment, to use the `view -R` command, but convert the BCF to VCF on the fly, so this isn't a critical problem. It just seemed as though it should work with bcf!
