### ISSUE TITLE
Removing samples by FORMAT attributes

### ISSUE THREAD

**Issue by shbrainard** [samtools/bcftools#1391]
The `-e` and `-i` options of the `bcftools filter` command appear, by default, to only allow for including or excluding _sites_.  E.g., `-e 'FMT/DP < 10'` removes sites where any sample has `DP < 10`, and `-e 'MEAN(FMT/DP) < 10'` removes sites where average depth across samples is < 10.

I would like to perform effectively similar filtering commands, but in a way that includes or excludes samples, instead of sites.  E.g., exclude all _samples_ that have `DP < 10` at any _site_, or exclude all samples with an average depth across all sites < 10, or exclude all samples that have a genotype quality of < 20 at 10% of genotyped sites.

Such commands can very easily be written to apply to sites, but there does not seem to be a straightforward way of applying such filtering expressions to samples in `bcftools`.  

One option mentioned in the manual is to use the double `||` operator, as described in the [man page](http://samtools.github.io/bcftools/bcftools.html#expressions).  As described in my [comment](https://github.com/samtools/bcftools/issues/1384#issuecomment-770082770) on a separate issue, however, this does not seem to work as a filtering operation for including or excluding entire columns in a VCF file, but rather only for selecting more or less individual records (e.g., as illustrated in the example on [this tutorial page](http://samtools.github.io/bcftools/howtos/filtering.html)).  In addition, it would therefore seem to have limited functionality (e.g., functions such as `MEAN(FMT/DP) < 10` would still always be evaluated across samples, not sites, when combined with a `||` operator).

The only other method mentioned in the manual is to use the `SMPL` or `s` prefix to functions which evaluate `FORMAT` fields in expressions passed to `filter`.  This also does not appear to work as I would expect.  I'm not sure I understand what it _is_ doing, but it definitely _isn't_ removing columns from the VCF file.  Instead it seems to be using as a metric calculated across sites on a per sample basis as a filtering criteria applied to sites (but I could just be confused):

```
nSites_unfiltered=$(bcftools view -H unfiltered.vcf.gz | wc -l) 
nSamples_unfiltered=$(bcftools query unfiltered.bcf.gz -l | wc -l)

nSites_DPfilter=$(bcftools filter unfiltered.bcf.gz -e 'sMEAN(FORMAT/DP)<5' | bcftools view -H | wc -l)
nSamples_DPfilter=$(bcftools filter unfiltered.bcf.gz -e 'sMEAN(FORMAT/DP)<5' | bcftools query -l | wc -l)

echo "scale=5; $nSites_DPfilter / $nSites_unfiltered" | bc #0.17349 - sites are removed, even though the filter is being applied to samples
echo "scale=5; $nSamples_DPfilter / $nSamples_unfiltered" | bc #1.00000 - no samples removed, despite, again, the filter being applied to samples

nSites_normalDPFilter=$(bcftools filter unfiltered.bcf.gz -e 'MEAN(FMT/DP) < 5' | bcftools view -H | wc -l)
echo "scale=5; $nSites_normalDPFilter / $nSites_unfiltered" | bc #0.83121 - fewer sites removed than the sMEAN filter
```

The `.bcf.gz` passed to these commands is here: https://www.dropbox.com/s/fwj1snabsb763sn/unfiltered.bcf.gz?dl=0
Its `.csi` index file is here: https://www.dropbox.com/s/jzdq6y91nkencmy/unfiltered.bcf.gz.csi?dl=0

In any event, the only option I have been able to come up with that actually excludes or includes entire sample IDs is to extract summary statistics using `bcftools stats`, export the desired statistics from the `PSC, Per-sample counts` table, and perform my own exploratory analysis outside of `bcftools`.  Then I can use `bcftools view -S` to explicitly remove samples by their ID, which I have identified manually as failing some thresholding criteria.  This also is obviously cumbersome, and only works for `FMT` fields that are included in `stats` (e.g., not `GQ` or `PL`).

I am not sure if I am missing some basic functionality of `bcftools`, or if this is more of a feature request.  Any information would be appreciated.

Thanks!

**Comment by pd3** [comment]
To clarify some of the confusion. Filtering cannot remove columns from a VCF. The samples (=columns) are output with the header and any ad-hoc removal of samples would lead to an invalid VCF. One can, however, use the `bcftools filter -S` command to set genotypes of failing samples to missing or ref. There is also the `+setGT` plugin which provides more flexibility as to what should happen with the genotypes that match / don't match the filtering expressions. For more see 
```
$ bcftools +setGT -h

About: Sets genotypes. The target genotypes can be specified as:
           ./.  .. completely missing ("." or "./.", depending on ploidy)
           ./x  .. partially missing (e.g., "./0" or ".|1" but not "./.")
           .    .. partially or completely missing
           a    .. all genotypes
           b    .. heterozygous genotypes failing two-tailed binomial test (example below)
           q    .. select genotypes using -i/-e options
       and the new genotype can be one of:
           .    .. missing ("." or "./.", keeps ploidy)
           0    .. reference allele
           M    .. major allele
           p    .. phased genotype
           u    .. unphase genotype and sort by allele (1|0 becomes 0/1)
Usage: bcftools +setGT [General Options] -- [Plugin Options]
Options:
   run "bcftools plugin" for a list of common options

Plugin options:
   -e, --exclude <expr>        Exclude a genotype if true (requires -t q)
   -i, --include <expr>        include a genotype if true (requires -t q)
   -n, --new-gt <type>         Genotypes to set, see above
   -t, --target-gt <type>      Genotypes to change, see above

Example:
   # set missing genotypes ("./.") to phased ref genotypes ("0|0")
   bcftools +setGT in.vcf -- -t . -n 0p

   # set missing genotypes with DP>0 and GQ>20 to ref genotypes ("0/0")
   bcftools +setGT in.vcf -- -t q -n 0 -i 'GT="." && FMT/DP>0 && GQ>20'

   # set partially missing genotypes to completely missing
   bcftools +setGT in.vcf -- -t ./x -n .

   # set heterozygous genotypes to 0/0 if binom.test(nAlt,nRef+nAlt,0.5)<1e-3
   bcftools +setGT in.vcf -- -t "b:AD<1e-3" -n 0

```

**Comment by shbrainard** [comment]
Thanks very much for the clarification!  I can stop searching in vain for a non-existent method :-)

However, could you please elaborate a little on why removing columns from a VCF file would be problematic?  When you say this would lead to an "invalid VCF", do you mean that fixed fields such as QUAL, and elements of INFO (e.g., AF and DP) would no longer accurately describe a file from which you have arbitrarily removed samples?  This would seem to also be the case with any use of `bcftools view -s ^<list of sample ID>`, which as I mentioned, I have been using in combination with `bcf stats` to remove samples with e.g., high amounts of missing data or low average depth.

Unless `bcftools view -s` is updating fixed fields on the fly, I suppose you are right that after filtering out samples, and before any additional filtering operations, I should update INFO fields.  This seems possible for INFO tags like AF and AC using the `+fill-tags` plugin; I'm not sure if there are other methods for things like INFO/QUAL or INFO/DP.

Thanks also for letting me know about the `+setGT` plugin.  I suppose I could replace failed genotypes with `./.`, and then filter on individuals with a high amount of missingness using `bcftools stats`?  Your comment warning against removal of columns now has me now concerned about this workflow though....

Thanks again for your help in clarifying all this.

**Comment by pd3** [comment]
I would hope that's obvious: the header is output first, before any data is encountered, and it defines the columns that come. Say you then remove a different sample in each row, possibly multiple samples, the columns would no longer match the header.
