### ISSUE TITLE
bcftools consensus -I does not work with MNPs

### ISSUE THREAD

**Issue by jts** [samtools/bcftools#1393]
I am working on a pipeline where I'd like to apply ambiguity codes to a consensus genome under certain conditions. `bcftools consensus -I` works well for SNPs, but does not appear to work for MNPs. Here's a small example:

ref.fa:
```
>ref
ACGTACGT
```

snp.vcf.gz:
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER
ref     3       .       G       C       .       .
```

mnp.vcf.gz:
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER
ref     3       .       GT      CC      .       .
```

`bcftools consensus -f ref.fa -I snp.vcf.gz`:
```
>ref
ACSTACGT
Applied 1 variants
```

`bcftools consensus -f ref.fa -I mnp.vcf.gz`:
```
>ref
ACCCACGT
Applied 1 variants
```

The MNP is successfully applied, but not as ambiguity codes as I'd expect. I could decompose the variant into multiple records but I'd prefer not for this application.

**Comment by pd3** [comment]
Thank you for the issue, this is now supported. Please try it out and let me know in case of problems.

**Comment by jts** [comment]
Thanks Petr! I will test this soon. Can I ask when the next formal release that would appear in conda is planned?

**Comment by pd3** [comment]
I don't about conda, but a next versioned release is imminent.
