### ISSUE TITLE
Filtering using F_PASS and FMT/DP gives inconsistent results

### ISSUE THREAD

**Issue by shbrainard** [samtools/bcftools#1396]
When I filter a VCF file in `bcftools` such that only sites where at least 90% of samples have a depth >= 10 are included, I am returned 8940 sites.  

```
bcftools filter unfiltered.bcf.gz -i 'F_PASS(FMT/DP  >= 10) >= 0.9' -Ob -o filtered.bcf.gz
bcftools view filtered.bcf.gz -H | wc -l #8940 sites remain
```

However when I exclude sites where < 90% of samples have depth >= 10, I get 4454 sites:

```
bcftools filter unfiltered.bcf.gz -e 'F_PASS(FMT/DP>=10) < 0.9' -Ob -o filtered.bcf.gz
bcftools view filtered.bcf.gz -H | wc -l #4454 sites remain
```

This makes me think something is going wrong in the evaluation of these expressions, since to my mind, these should give the same result.

The only thought I had was that maybe missing data in the `FMT/DP` field is messing with these calculation.  In this file, generated with freebayes, the `FMT/DP` of missing genotypes has itself been recorded as missing data (`"."`).  I tried to perform some equivalent filtering operation in `VariantAnnotation` in R, and indeed I get different results depending on whether I replace `NAs` with zeros, or remove missing data from the calculation.  However, neither value is 8940 or 4454:

```
data <- readVcf(file="unfiltered.vcf.bgz")
depth <- geno(data)$DP

# replace NAs with 0
depth[is.na(depth)] <- 0 
DP0.1 <- apply(depth,1,quantile,p=0.1)
DP_filter <- (DP0.1>=10)
sum(DP_filter)  #8953 sites will remains

# don't replace NAs with 0, but remove from quantile calculation
depth <- geno(data)$DP
DP0.1 <- apply(depth,1,quantile,p=0.1,na.rm=T)
DP_filter <- (DP0.1>=10)
sum(DP_filter)  #9196 sites will remains
```

While I am mainly worried about the `-e` and `-i` expressions above not giving the same result, I am also wondering how `bcftools` parses missing values in such expressions, since neither the `-e` nor the `-i` result conforms to either of the options I can simulate in R.  Perhaps relatedly, is there a way to edit the `FMT/DP` attribute of specific genotypes and/or change the way `bcftools` treats missing data when operating on FMT/DP information?

Thanks!

**Comment by pd3** [comment]
This looks like the same problem addressed here https://github.com/samtools/bcftools/issues/1397. Closing the issue now, please reopen if the problem was not resolved by ac7c21d .
