### ISSUE TITLE
filtering on F_PASS(GT="het") gives contradictory results

### ISSUE THREAD

**Issue by shbrainard** [samtools/bcftools#1397]
I want to remove sites from a VCF file with an overabundance or an underabundance of heterozygous genotypes.  I have 8940 markers to start with:

`bcftools view unfiltered.bcf.gz -H | wc -l # 8940
`

When I exclude sites with a frequency of hets > 0.9, this number goes down a bit:

`bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") > 0.9' | bcftools view -H | wc -l #8905
`

When I exclude sites with a frequency of hets < 0.1, suddenly, almost every marker is removed:

`bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") < 0.1' | bcftools view -H | wc -l #9 sites remain
` 

This does not reflect the actual distribution of heterozygous frequencies in this population (validated using ```bcftools stats```).  Indeed, when I perform what to my mind is an equivalent command (i.e., include only sites with a frequency of hets >= 0.1) I get a more reasonable reduction:

`bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") >= 0.1' | bcftools view -H | wc -l #8909 sites remains
`

Additionally confusing to me is that by using `query` I can confirm that the expression `%N_PASS(GT="het")` is being parsed correctly; the command:

`bcftools query -f '%ID %N_PASS(GT="het")\n' unfiltered.bcf.gz
`

returns a list where it is clear that almost every site has 60-80 samples that pass the expression. However:

`bcftools filter unfiltered.bcf.gz -e 'N_PASS(GT="het") < 16' | bcftools view -H | wc -l #9 sites remain
`

does not work (returns only 9 sites), while:

`    bcftools filter unfiltered.bcf.gz -i 'N_PASS(GT="het") >=16' | bcftools view -H | wc -l
`

again returns the correct (I think) 8909 sites.  (Here I have set an explicit threshold of 16 because 0.1 * sample size of this file = 15.9).

I think part of the explanation lies with the `<` operator (see this [related issue](https://github.com/samtools/bcftools/issues/1396#issue-800528649) with using `F_PASS` on `FMT/DP` values), which seems to break whether `-e` or `-i` is used, but in opposite ways.  E.g., consider the apparently nonsensical results generated by these six commands:

```
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") < 0.1' | bcftools view -H | wc -l #9 sites remain
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") < 0.5' | bcftools view -H | wc -l #9 sites remain
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") < 0.9' | bcftools view -H | wc -l #9 sites remain

bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") < 0.1' | bcftools view -H | wc -l #8931 sites remain
bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") < 0.5' | bcftools view -H | wc -l #8931 sites remain
bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") < 0.9' | bcftools view -H | wc -l #8931 sites remain
```

No matter what fraction the `<` compares against, it returns the same number of sites.  When the `>` operator is used on the other hand, the number of sites returned scales reasonably with the fractional threshold used:
```
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") > 0.1' | bcftools view -H | wc -l #31 sites remain
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") > 0.5' | bcftools view -H | wc -l #678 sites remain
bcftools filter unfiltered.bcf.gz -e 'F_PASS(GT="het") > 0.9' | bcftools view -H | wc -l #8905 sites remain

bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") > 0.1' | bcftools view -H | wc -l #8909 sites remain
bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") > 0.5' | bcftools view -H | wc -l #8262 sites remain
bcftools filter unfiltered.bcf.gz -i 'F_PASS(GT="het") > 0.9' | bcftools view -H | wc -l #35 sites remain
```

Any thoughts on these confusing results, and whether I am misusing `F_PASS` in some way, would be appreciated.

**Comment by pd3** [comment]
Hi, thank you for raising the issue. Two general comments that would help to debug the issue:

1) what version of bcftools are you using?
2) rather than giving summary stats of a file that I cannot verify, it would be more helpful to provide a small test case highlighting a single row which was not filtered correctly.

I hope you appreciate how difficult and time consuming it is to deal with bug reports like this.

**Comment by shbrainard** [comment]
Absolutely!  Sorry, I wasn't sure if this as a bug, or if I was doing something obviously wrong.

Version of bcftools: 1.11-1-g87d355e (using htslib 1.11-9-g2264113)

Here is a [problemMarker.vcf.gz](https://github.com/samtools/bcftools/files/5935392/problemMarker.vcf.gz)

Example code:

```
tabix -p vcf problemMarker.vcf.gz
bcftools view problemMarker.vcf.gz -O b -o problemMarker.bcf.gz 
bcftools index problemMarker.bcf.gz

bcftools view -H problemMarker.bcf.gz | wc -l #1 marker
bcftools query problemMarker.bcf.gz -l | wc -l #672 samples

bcftools filter problemMarker.bcf.gz -i 'F_PASS(FMT/DP>=10) > 0.9' | bcftools view -H | wc -l # marker gets included
bcftools filter problemMarker.bcf.gz -e 'F_PASS(FMT/DP>=10) <= 0.9' | bcftools view -H | wc -l # marker gets excluded
```

Thanks so much for your help debugging this!

**Comment by pd3** [comment]
The filtering code was trying to be too smart, wanting to behave intelligently with programs like `query` or `+trio-stats`. This resulted in the odd behavior you observed.. This is now fixed and the negation should work as expected.

Just to record here what changes to expect:

The original behavior of the `query` command can be mimicked as described in the commit message (ac7c21d). However, there is no workaround to reproduce the original behavior if N_PASS or F_PASS should be used with programs like `+trio-stats`, in case when the inner expression contains a range of values. For example, the expression `F_PASS(DP>{10,20})` will include all samples at sites that PASS while previously only the samples that PASS were included.
