### ISSUE TITLE
bcftools consensus: --iupac-code

### ISSUE THREAD

**Issue by LaraFuhrmann** [samtools/bcftools#1400]
Using the parameter `---iupac-code` to report variants with the ambiguous code, I exhibited some unexpected behaviour. 
There have been some other issues with IUPAC codes (see #643), yet not covering this behaviour: 

In a position where 100% of the reads report a `T` and the reference sequence has a `C`, I would expect to have `T` reported in the consensus sequence, but instead `Y` (corresponding to `T` or `C`) is reported.

It this intended behaviour, or a bug?

**Comment by pd3** [comment]
It needs to be clarified that `consensus` work off a VCF file and it does not know about reads. So you need to reframe the issue as either being a `bcftools consensus` or `bcftools mpileup .. | bcftools call` problem.

Also it is not clear what options did you use to run `consensus` with and what the input VCF looks like. Please provide a test case, this question cannot be answered based on the information you've given.

**Comment by LaraFuhrmann** [comment]
Thank you for your fast answer. 

As the VCF-file correctly identifies the variant, we believe it is a consensus problem. 

We created a test case using the following command line to call the consensus:
`bgzip test.vcf`
`bcftools index test.vcf.gz`
`bcftools consensus --output test.amb.fasta --fasta-ref test_reference.fasta --iupac-codes test.vcf.gz`

The resulting consensus reports a `Y` in position 15, although the variant `T` is supported by all of the reads. 

Please let me know if you are having problems accessing the files. 

[test.vcf.gz](https://github.com/samtools/bcftools/files/5931854/test.vcf.gz)
[test_reference.fasta.txt](https://github.com/samtools/bcftools/files/5931849/test_reference.fasta.txt)

**Comment by pd3** [comment]
Thank you for the test case. There are no genotypes in the file, therefore the program operates in the mode of applying all variants onto the reference, replacing the fasta reference base with the ambiguity code formed by REF+ALT. The program does not look at the number of supporting reads at all. For that base to be called `T`, there would have to be a genotype `GT=1/1`.

**Comment by LaraFuhrmann** [comment]
Thank you for your reply. Indeed, setting the genotype GT=1/1 solved the problem for this case and also for the case with two variants at the same position (e.g. ALT=[C,T]). 
But when three variants occur at the same position (e.g. ALT=[C,T,A]) it seems like the last variant is not considered in the iupac-code computation. 

I attached a test case where is a variant at position 4, ALT=C,T,A and in the consensus Y (C or T) is reported. 

We (manually) adapted the genotype in the vcf file in different ways :
`GT:PL	1/3:127,67,73,78` --> M (A or C)
`GT:PL	1/1:127,67,73,78` --> C 
`GT:PL	1/2:127,67,73,78` --> Y (C or T)
`GT:PL	1/2/3:127,67,73,78` --> Y (C or T) 
`GT:PL	0/1/2:127,67,73,78` --> S (G or C)

We used the following commands to call the consensus:: 
`bgzip temp_3variants.vcf`
`bcftools index temp_3variants.vcf.gz`
`bcftools consensus --output test.amb.fasta --fasta-ref ref.fasta --iupac-codes -H A temp_3variants.vcf.gz
`
[ref.fasta.txt](https://github.com/samtools/bcftools/files/5950047/ref.fasta.txt)
[temp_3variants.vcf.gz](https://github.com/samtools/bcftools/files/5950048/temp_3variants.vcf.gz)

**Comment by pd3** [comment]
I just added support for arbitrary ploidy. The IUPAC codes should be now generated for genotypes (e.g. 0/1/2) when `-H I` is given or multiple ALT alleles (e.g. REF=C ALT=T,A). The code should also work for insertions and mulitple base changes.

**Comment by jmarshall** [comment]
@pd3: this fix added a Clang warning which shows that line 558 isn't breaking out of the loop as intended:

```
consensus.c:558:28: warning: result of comparison of constant -127 with
      expression of type 'uint8_t' (aka 'unsigned char') is always false
      [-Wtautological-constant-out-of-range-compare]
                if ( ptr[i]==bcf_int8_vector_end ) break;
                     ~~~~~~^ ~~~~~~~~~~~~~~~~~~~
```

**Comment by pd3** [comment]
@jmarshall This is now fixed, thank you
