### ISSUE TITLE
bcftools mpileup --max-depth and number of samples

### ISSUE THREAD

**Issue by marcticruz** [samtools/bcftools#1401]
I have been running bcftools mpileup --max-depth 1000 using one bam file with 131 samples. When I get the output of bcftools and I use it in vcftools with the flag -min-meanDP, it stops retaining snps when I use the value 9 for this flag. However, when I execute bcftools mpileup --max-depth 23 using one bam file with 3 samples, it  only stops retaining SNPs when I use --min-meanDP 51.  Can anyone explain me why I'm still getting SNPs with up to 50x of mean depth when I execute bcftools mpileup --max depth 23 based on 3 samples? Considering that 23/3 = 7.6, I thought that --max-depth 23  based on 3 samples would filter out any site with mean depth higher than 7.6x. What am I possibly misunderstanding in all this? 

Here is the whole pattern:  

When I use 131 samples with flag --max-depth 7.6x, it retained SNPs with up to 8x of mean depth. When I used 8 samples with the flag --max-depth 7.6x it retained SNP with up to 22x of mean depth. When I used 6 samples based on the flag --max-depth 7.6x it retained SNPs with up to 28x of mean depth. When I used 3 samples based on the flag --max-depth 7.5x, it retained SNPs with up to 50x of mean depth. Why am I getting SNPs with higher depths when I use fewer samples when I'm still using the same equivalent --max-depth in all those cases?

Thanks!

**Comment by pd3** [comment]
I apologize for answering your question with a question, but I can't help but wonder: why don't you actually look for the answer in your data? Select one site that does not make sense to you and post what is the depth distribution across samples at that site.

If it stil does not make sense, then maybe it is a problem with `bcftools --max-depth`, maybe it is a problem with `vcftools  --min-meanDP`.

Are you using the latest version of BCFtools? For now all I can do is to quote the man page:
```
*-d, --max-depth* 'INT'::
    At a position, read maximally 'INT' reads per input file. Note that
    the original *samtools mpileup* command had a minimum value of '8000/n'
    where 'n' was the number of input files given to mpileup. This means that
    in *samtools mpileup* the default was highly likely to be increased and the
    *-d* parameter would have an effect only once above the cross-sample minimum of 8000.
    This behavior was problematic when working with a combination of
    single- and multi-sample bams, therefore in *bcftools mpileup* the user
    is given the full control (and responsibility), and an informative message
    is printed instead [250]
```

**Comment by marcticruz** [comment]
![Screenshot from 2021-02-05 14-57-31](https://user-images.githubusercontent.com/42651614/107133870-453c9e00-68b2-11eb-99c0-a0ffb13172a9.png)
![Screenshot from 2021-02-05 14-41-36](https://user-images.githubusercontent.com/42651614/107133872-45d53480-68b2-11eb-9529-5ade19793236.png)

Hi Petr,  

Thank you so much for your answer. Please find attached the screenshot of the depth for each site across 3 samples. I'm sending the screen shot instead of the file with all the results because the size of the file is 1.1GB. I attached two screen shot, one of them is just for you to see the name of the columns so you can better understand what I will write next.

If I understand correctly, the site in the position 1155 has 55 reads covering it in one of the samples. Since I set up --max-depth 21, I was expecting a maximum of 21 reads covering any given site. Does it make sense to expect that? If it does, why am I getting more than 21 reads covering some sites? Do you know if the sites with -1 are the ones that were not covered by any read?

This analysis was based on 3 separate bam files that were run in bcftools mpileup each at a time, and generated 3 bcf files that I merged afterwards. When I applied vcftools --min-meanDP 7 on this merged file it retained 1,399,921 SNPs. I ran another analysis with the same 3 samples and using the same settings, but I executed bcftools mpileup based on one merged bam file containing 3 samples, generating one bcf file. When I applied vcftools --min-meanDP 7 on this bcf file, it retained 2,977,432 SNPs. Do you know why am I getting this difference in the number of SNPs when I apply those two different approaches? Do you have a preference for one approach over the other?  

Thank you so much for your help!  

Marcos

**Comment by pd3** [comment]
Hi, sorry, your description of the problem is not sufficient to understand the problem. You are not showing the version of bcftools nor commands you used. I hope you appreciate how difficult and time consuming it is to deal with bug reports like this.

It would be more helpful to provide a small test case, a single site, indicating the expected input and output. Also bcftools has its own method of filtering, so whatever vcftools does should not be part of this issue. Better to use `bcftools query` and `awk` to demonstrate.

Regarding how --max-depth works, the fragment of the man page explaining this is shown above.
