### ISSUE TITLE
STRLEN(REF) == 1 && STRLEN(ALT) == 1 do not filter out those multiallelic variants

### ISSUE THREAD

**Issue by biozzq** [samtools/bcftools#1402]
Dear all,

When using following command, i found that those multiallelic sites have not been filter out, e.g. following example. I do not know if I understand the expression of `STRLEN` correctly. Thank you.

`bcftools-1.11/bin/bcftools view -t 1,2,3 -i 'F_MISSING <= 0.1 && STRLEN(REF) == 1 && STRLEN(ALT) == 1' input_snp.vcf.gz -O z -o out.clean.vcf.gz --threads 4`

`1       2176    .       C       T,A     8782.2  PASS`

All the best,
Zheng zhuqing

**Comment by pd3** [comment]
The expressions in use the OR logic and are applied to all items in vectors, so if at least one ALT allele has length 1, the filtering should pass. If you want to filter out sites with multiple alternate alleles, use `N_ALT==1`. 
Please see the full list of recognized expressions here http://samtools.github.io/bcftools/bcftools.html#expressions

**Comment by biozzq** [comment]
Do you mean that the ALT in the above example includes two alleles, and they will be stored in vector, if either of them has length 1, the sites will be pass? 

Thank you very much.

**Comment by pd3** [comment]
Yes, that's correct. For fields with multiple values it is sufficient for any of the values to evaluate as true in the expression.
