### ISSUE TITLE
Are results from  bcftools +fill-tags reporting the p val from HWE exact test?

### ISSUE THREAD

**Issue by brettva** [samtools/bcftools#1403]
It looks like it, but does does not seem explicit in [docs ](https://samtools.github.io/bcftools/howtos/plugin.fill-tags.html), sorry if I missed it. thanks!

**Comment by pd3** [comment]
Yes, it is the implementation of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1199378 and it is implemented in the code here
https://github.com/samtools/bcftools/blob/develop/plugins/fill-tags.c#L491-L500
