### ISSUE TITLE
bcftools +split will fail if sample names contain the "/" character

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1404]
If a sample name contains the `/` character, such as `A/B`, bcftools split will fail with error message:
```
[E::hts_open_format] Failed to open file "./A/B.vcf" : No such file or directory
[init_data] Error: cannot write to "./A/B.vcf": No such file or directory
```
This is mostly the result of the VCF format not restricting sample names from using any weird characters, while UNIX filesystem don't allow `/` character in file names.

One quick solution would be to change this line of code in `split.c`:
```
        for (k=l; k<str.l; k++) if ( isspace(str.s[k]) ) str.s[k] = '_';
```
to
```
        for (k=l; k<str.l; k++) if ( isspace(str.s[k]) || str.s[k] == "/" ) str.s[k] = '_';
```

However, do notice that this fix would work okay for UNIX filesystems, while a similar issue would arise with Windows filesystems with a wider range of characters.

**Comment by pd3** [comment]
Thank you for raising the issue. This is now addressed by 200bbba.

**Comment by freeseek** [comment]
There is a minor regression bug in the last fix. The code:
```
        char *suffix = NULL;
        if ( args->output_type & FT_BCF ) suffix = "bcf";
        else if ( args->output_type & FT_GZ ) suffix = ".vcf.gz";
        else suffix = ".vcf";
```
is missing a `.` before `bcf`, causing the output file names to be incorrect.

**Comment by pd3** [comment]
This is now fixed, thank you.

(Note that the current develop is waiting for https://github.com/samtools/htslib/pull/1327 to be merged)

**Comment by freeseek** [comment]
No need for me to push a new release just for this issue. I have it sorted out on my end.
