### ISSUE TITLE
bcftools call low allele frequency mutation

### ISSUE THREAD

**Issue by merckey** [samtools/bcftools#1411]
Dear samtools team,

I'm using `bcftools call` to exam the possible somatic mutations in tumor samples on specific positions. I did `mpipleup` first and then run `call` to get the final vcf file. However, I found that some sites with low allele frequencies were not included in the vcf. 
```
bcftools mpileup  --fasta-ref ref.fasta \
--regions-file region.bed \
-a "AD,ADF,ADR,DP,SP,INFO/AD,INFO/ADF,INFO/ADR" \
tumor.bam | \ 
bcftools call -A -mv -Ov > variants.vcf
```

If I call it without the `-v` option, I can see that, for example this allele was called as `0/0`.
 `GT:DP:SP:ADF:ADR:AD`
`0/0:0,255,255:246:5:179,5:62,0:241,5`

Is there a way that I can let the caller report it as a variant?
Thank you so much!

**Comment by pd3** [comment]
In principle you coud try to increase the value of `-P`, but that will not help in your case really.

The thing is, mpileup/call is a germline variant caller and observing 241 reference reads and only 5 alternate reads is very very very very unlikely for a genuine heterozygous genotype.

What you can do is to run as `call -mA` and perform a naive somatic variant calling by streaming through a custom script.

**Comment by merckey** [comment]
Thank you for the clarification! Yes, I tried `-P` but it doesn't work. I will use a custom script to extract such variants.

**Comment by YS-HZAU** [comment]
Hello,has your problem solved? Run into the same trouble!

**Comment by pd3** [comment]
Just to cross-reference, this is essentially the same issue https://github.com/samtools/bcftools/issues/1707
