### ISSUE TITLE
ERROR while installing BCFtools

### ISSUE THREAD

**Issue by sekhwal** [samtools/bcftools#1413]
cram/cram_io.c:53:10: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:133: cram/cram_io.o] Error 1
make[1]: Leaving directory '/scratch/mk2282/softwares/bcftools-1.10.2/htslib-1.10.2'
make: *** [htslib-1.10.2/htslib.mk:155: htslib-1.10.2/hts-object-files] Error 2

**Comment by valeriuo** [comment]
Please read the [installation](https://github.com/samtools/htslib/blob/develop/INSTALL) instructions for HTSlib, particularly the bits about how to install **bzip2** on various platforms. Alternatively, you can configure HTSlib to not use **bzip2** by passing the flag `--disable-bz2` to the configure script, but this might make some CRAM files unreadable.

**Comment by sekhwal** [comment]
Hi,
As I start with bcftools: I zipped and indexed the files using the
following commands: However, once I merged using the following command, the
terminal shows "killed". I have a total 90 vcf files.

bgzip -c file1.vcf > file1.vcf.gzbcftools index file1.vcf.gz

bcftools merge `ls *.vcf.gz` -O v > merged.vcf


Thank you,

Manoj
