### ISSUE TITLE
ROH analysis using population specific AF-file and genetic map

### ISSUE THREAD

**Issue by yangyxt** [samtools/bcftools#1417]
I input single-sample VCF files to do ROH analysis for each sample. And got error messages like this:
![image](https://user-images.githubusercontent.com/40780228/108155460-e0870c00-7119-11eb-98d4-ffef8825dc9b.png)

Also, with the known ethnicity of that sample, I input the population-specific allele frequency file, which looks like this(converted from gnomAD):
![image](https://user-images.githubusercontent.com/40780228/108155063-2099bf00-7119-11eb-9661-255ce4c4e960.png)
And the population-specific genetic map file from 1000g, which looks like this(in IMPUTE2 format):
![image](https://user-images.githubusercontent.com/40780228/108155177-5e96e300-7119-11eb-896b-aaa759726550.png)

Since the genetic-map file is only for one contig, so I do ROH run on each contig and hope to combine the results together. Therefore, for a single run on one chromosome, my command looks like this:

`bcftools roh -r chr${contig} --AF-file ${allele_freq_file} --genetic-map ${genetic_map_file} -o output_file input_vcf.gz`

P.S. VCF files are not annotated with AFs since I need to use their raw data format to do other analyses, I need them compatible with other tools. 
P.S.2 VCF files are generated from WES data. Since bcftools using HMM to do the ROH analysis and with given transition probability from the genetic map, I suppose this won't be an issue.

**Comment by yangyxt** [comment]
I found the VCF file does have enough overlapping records with AF-file(according to the log file screenshot pasted above), so what could possibly go wrong, leading to 0 processed lines?

**Comment by pd3** [comment]
This is because --AF-file is expected to have both REF and ALT alleles in the third column, separated by a comma.  I just pushed a check, now the program should exit with an informative error message.

Also noticed that the tutorial has it wrong, will fix that as well https://samtools.github.io/bcftools/howtos/roh-calling.html

Thanks for reporting the issue
https://samtools.github.io/bcftools/howtos/roh-calling.html

**Comment by yangyxt** [comment]
Thx for fixing this. I thought u meant fixed by changing the comma to tab in #1142

**Comment by pd3** [comment]
Ah you are right, that was ambiguous, just edited it to make it clear.
