### ISSUE TITLE
bcftools merge documentation typo

### ISSUE THREAD

**Issue by tbenavi1** [samtools/bcftools#1424]
Hello, 

In the documentation for the merge command the documentation states:  "For example, when merging file A.vcf.gz containing samples S1, S2 and S3 and file B.vcf.gz containing samples S3 and S4, the output file will contain **four** samples named S1, S2, S3, 2:S3 and S4."

However, shouldn't the documentation say **five** samples, or am I misunderstanding something? Thanks for your assistance.

**Comment by pd3** [comment]
No, you are not missing anything, it is a typo. The output file will have 5 samples. Thank you pointing it out.
