### ISSUE TITLE
Creating a consensus for PSMC

### ISSUE THREAD

**Issue by desmodus1984** [samtools/bcftools#1427]
Hi,
I am interested in using PSMC (website https://github.com/lh3/psmc), and the following code seems to be deprecated:
    samtools mpileup -C50 -uf ref.fa aln.bam | bcftools view -c - \
      | vcfutils.pl vcf2fq -d 10 -D 100 | gzip > diploid.fq.gz

I ran: 
samtools mpileup -uf /fs/scratch/PHS0338/data/PSMC.fasta PSMC_sorted.bam | bcftools view -c - \
      | vcfutils.pl vcf2fq -d 10 -D 60 | gzip > PSMC-ref.fq.gz

and got the following warning:
[warning] samtools mpileup option `u` is functional, but deprecated. Please switch to using bcftools mpileup in future.
Error: Could not parse --min-ac -
Use of uninitialized value $l in numeric lt (<) at /apps/bcftools/1.9/bin/vcfutils.pl line 566.
Use of uninitialized value $l in numeric lt (<) at /apps/bcftools/1.9/bin/vcfutils.pl line 566.
[mpileup] 1 samples in 1 input files

The output - PSMC-ref.fq.gz - was only 24 bits.

I am trying to get the fasta file that I need but I am very confused.
I am supposed to use bcftools but it has two options and I don't know which one is the right one that I need.
I see that there are the "bcftools consensus" option and the "call" option. I have a sorted bam file and the fasta reference. In the original code, 1st mpileup followed by view (replaced by call), finally convert with vcfutils.
I am confused with the consensus option, since the call option has consensus caller too.

I will appreciate if you can help me how to generate the file that I need (fasta/fastq).

Thanks;

Juan Pablo

**Comment by pd3** [comment]
I don't know PSMC, sorry, but that recipe is ancient; `bcftools view` was replaced with `bcftools call` and `vcfutils.pl` is not supported. 

The current supported way of variant calling and filtering is described here http://samtools.github.io/bcftools/howtos/variant-calling.html and here http://samtools.github.io/bcftools/howtos/consensus-sequence.html.
