### ISSUE TITLE
bcftools concat --ligate question

### ISSUE THREAD

**Issue by rgcgithub** [samtools/bcftools#1430]
What are the details of the ligation of phased VCFs? The docs say only that "Ligate phased VCFs by matching phase at overlapping haplotypes". Is the choice made on maximal number of matches? Is the overlapping segment taken from the left or right hand VCF? Or is it a 50:50 split?

**Comment by pd3** [comment]
The overlap is defined by the provided VCFs, the program takes whatever it finds in there. Say you have two VCFs with a block of 10 overlapping sites. All 10 sites are used determine whether the phase in the second file matches that in the first file or if the genotypes need to be flipped in the second file.

I hope that clarifies it?
