### ISSUE TITLE
-S filtering produces incorrect output when combined with -i/e

### ISSUE THREAD

**Issue by drhodesbrc** [samtools/bcftools#1435]
If a sample list is provided when doing a query and filtering genotypes, the output data are incorrect if the sample list provided is not in the same order.

```
#Test vcf
##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##INFO=<ID=OLD_CLUMPED,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Filtered basecall depth used for site genotyping">
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=248956422>
#CHROM	POS	ID	 REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample1	Sample2	Sample3	Sample4
1	1001	.	A	T	500	PASS	.	GT:DP	1/1:31	0/0:31	1/0:31	./.:0
1	1002	.	C	G	500	PASS	OLD_MULTIALLELIC=1:1002:C/T/A	GT:DP	./1:31	./0:31	1/1:31./.:0
1	1002	.	C	T	500	PASS	OLD_MULTIALLELIC=1:1002:C/T/A	GT:DP	1/.:31	0/0:31	./1:310/0:0

```
Sample list: 
```
 cat sample_tst 
Sample2
Sample4
Sample1

```

If the bcftools query is separated from sample exclusion we see the correct output
```
bcftools view tst.vcf.gz -S sample_tst | bcftools query -f '%CHROM:%POS-%REF/%ALT[\t%GT]\n' -e 'GT~"\."'
1:1001-A/T	0/0	1/1
1:1002-C/T	0/0	0/0

```
Combining the commands we see incorrect output
```
bcftools query tst.vcf.gz -f '%CHROM:%POS-%REF/%ALT[\t%GT]\n' -S sample_tst -e 'GT~"\."'
1:1001-A/T	0/0	./.
1:1002-C/T	0/0	1/.
```
Now if we use same sample order in -S list
```
cat sample_tst_sorted 
Sample1
Sample2
Sample4

bcftools query tst.vcf.gz -f '%CHROM:%POS-%REF/%ALT[\t%GT]\n' -S sample_tst_sorted -e 'GT~"\."'
1:1001-A/T	1/1	0/0
1:1002-C/T	0/0	0/0

```
A minor point also - the documentation currently lists the following for the -e expression used

> missing genotypes can be matched regardless of phase and ploidy (".|.", "./.", ".") using these expressions
> GT~"\.", GT!~"\."

It might be useful to change this to reflect that the ~ acts as a grep, therefore any missing data will be matched, e.g. half missing 1/. and not just the GTs listed.

**Comment by pd3** [comment]
Uh, this was a good catch, thanks a lot for raising the issue and a great bug report. This is now fixed.

Note that you can filter missing genotypes also using `-e 'GT="mis"'`. I just updated the documentation to reflect that.
