### ISSUE TITLE
ploidy function for diploid

### ISSUE THREAD

**Issue by ap1438** [samtools/bcftools#1436]
currently i am using bcftools-1.4 
i am using the bcftools call function

bcftools call -c -v --ploidy 2 -O v -o var.called.vcf var.raw.vcf

this is the command i am using to call (sample Genome ) rice which is diploid .
but it shows error 

PRE-DEFINED PLOIDY FILES

 * Columns are: CHROM,FROM,TO,SEX,PLOIDY
 * Coordinates are 1-based inclusive.
 * A '*' means any value not otherwise defined.

GRCh37
   .. Human Genome reference assembly GRCh37 / hg19

GRCh38
   .. Human Genome reference assembly GRCh38 / hg38

X
   .. Treat male samples as haploid and female as diploid regardless of the chromosome name

Y
   .. Treat male samples as haploid and female as no-copy, regardless of the chromosome name

1
   .. Treat all samples as haploid

Run as --ploidy <alias> (e.g. --ploidy GRCh37).
To see the detailed ploidy definition, append a question mark (e.g. --ploidy GRCh37?).

I am not able to understand where i am going wrong.
Please suggest me the correct command line 
and help me understand the ploidy function.
the sample is rice i.e. diploid 
suggest command line considring rice plant.

Thanking you for your valuable time and suggestion.

**Comment by pd3** [comment]
This is now possible, specifying `--ploidy 2` explicitly works.

**Comment by ap1438** [comment]
Thanks
