### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by roselucia** [samtools/bcftools#1438]
Hi,
I used bcftools for normalization of indels and splitting multiallelic variants in a vcf. May I ask you which paper to cite, when referring to your programm?

Thanks a lot!

**Comment by jkbonfield** [comment]
There is a list of publications at http://www.htslib.org/doc/#publications.

Maybe @pd3 can advise if there is something specific to normalisation / splitting (I couldn't see anything at first glance), but the latest paper (just published) covers all of bcftools: https://academic.oup.com/gigascience/article/10/2/giab008/6137722

[Petr: I'll add a PR to update the website to include our latest publications.]

**Comment by roselucia** [comment]
Hi @jkbonfield ,

thanks for getting back to me. I thought maybe it is required to maybe use your first paper, as this is often preferred when acknowledging work (Li H, Handsaker B, Wysoker A, Fennell T, Ruan J, Homer N, Marth G, Abecasis G, Durbin R, and 1000 Genome Project Data Processing Subgroup, The Sequence alignment/map (SAM) format and SAMtools, Bioinformatics (2009) 25(16) 2078-9 [19505943])? 
However, I can also cite both papers (the newest one you suggested and the first, as describes above)?

I am looking forward to what your colleague @pd3 says.

Please let me know what paper you would like to be cited. Thanks! 
All the best,
Rose

**Comment by pd3** [comment]
Hi @roselucia, the 2009 paper describes different functionality. Features related to VCF processing, such as normalization and splitting multiallelics, were introduced later, in 2013, so please cite https://academic.oup.com/gigascience/article/10/2/giab008/6137722 instead.

**Comment by roselucia** [comment]
Hi @pd3, thanks a lot for getting back to me! I will cite the paper your recommended instead.
