### ISSUE TITLE
thread function

### ISSUE THREAD

**Issue by aknfa** [samtools/bcftools#1439]
Hello all! 

I am very new to bcftools. I've read the documentation and googled it but I did not understand the function of the **threads** option. Can someone explain to me? How do you decide which integer to put after threads for instance in the merging procedure?

**Comment by valeriuo** [comment]
The option `threads` allows the program (mostly the compression part) to run in multi-threaded mode, which can make it significantly faster. Theoretically, the more threads a program has available to spread its work onto the better, although programs rarely scale linearly with the number of threads and there is a limit imposed by the OS (try `cat /proc/sys/kernel/threads-max` on a Linux flavour). 
The optimal value would be the maximum number of threads after which you see no significant performance improvement (decrease in running time) and depends on the work a program has to do. You can start with 4 threads and record the running time. Then double this number and see how the running time changes. If you cannot do these experiments, try a default of 20. It's a sensible number on most machines.

**Comment by aknfa** [comment]
Thanks a lot for the clear explanation!
