### ISSUE TITLE
Bcftools Csq multiple consequences

### ISSUE THREAD

**Issue by mckeowr1** [samtools/bcftools#1442]
Hello, 
 
I was hoping you could provide a little clarification about the consequence predictions by Bcftools csq. There are some sites that receive multiple consequences ex. `splice_acceptor&3_prime_utr&coding_sequence` or `inframe_insertion&stop_retained`.  

Does this mean that all listed consequences are equally likely at that site? 

Thanks in advance, 

Ryan

**Comment by pd3** [comment]
The program takes all transcripts and determines the effect on amino acid level, the same way VEP operates. It does not do any probabilistic reasoning, merely lists all observed (possible) consequences.

**Comment by mckeowr1** [comment]
Thank you for the clarification!
