### ISSUE TITLE
genotype format "GT" error

### ISSUE THREAD

**Issue by Silvia-lme** [samtools/bcftools#1443]
I am trying to open vcf format (##fileformat=VCFv4.2) in bcftools. bcftools identified the error : "[E::vcf_parse_format] Couldn't read GT data: value not a number or '.' at Scaffold". GT format type in my vcf file was String (##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">) I have changed it to Integer (##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Genotype">) however I got another error "[E::vcf_parse_format] Invalid character '/' in 'GT' FORMAT field at Scaffold". It looks strange to me, in general are allele values separated by  / 
GT format for the first and the second individual is 0/0 in my vcf file. Please could advice me with the this issue. Thanks.

**Comment by pd3** [comment]
GT must be defined as
```
##FORMAT=<ID=GT,Number=1,Type=String>
```
please check the specification here http://samtools.github.io/hts-specs/VCFv4.2.pdf

Apparently the VCF file is not well formatted, but from the error messages it is not clear what exactly is wrong. What version of bcftools are you running? One would hope the most recent version printed also coordinates so you could check visually.

There are few VCF validators out there, for example in https://github.com/vcftools/vcftools/ or https://github.com/cyenyxe/vcf-validator

**Comment by Silvia-lme** [comment]
Thanks for your advice.
I am using bcftools version 1.11. However the inputfile that I have received was produced with the older version (##bcftoolsVersion=1.9+htslib-1.9). Could be this a case? I have a similar problem when I am using filtering option (--remove-indels --max-alleles 2 --min-meanDP) in VCFtools (v. 0.1.17). Filtering works well there however the header of output vcffile is not change (first line of output vcf file is still ##bcftoolsVersion=1.9+htslib-1.9). Why the fileformat of vcf output file is not change to ##fileformat=VCFv4.2? I am using this command: vcftools --bcf inputfile.bcf --remove-indels --max-alleles 2 --min-meanDP 5 --recode -c  > outputfile.vcf. Thanks.

**Comment by pd3** [comment]
No, the version of bcftools should not matter in this case, 1.9 was producing a valid VCF. I am afraid this does not give sufficient information to debug the problem. Please either provide a small test case or try one of the validators, I am unable to help more.
