### ISSUE TITLE
bcftools concat --ligate FIXME, disorder

### ISSUE THREAD

**Issue by astulaaa** [samtools/bcftools#1445]
Hello,
I am trying to merge 3 vcf.gz files using bcftools concat --ligate.
second and third of the files show warning "No BGZF EOF marker; file may be truncated"
what worries me is "FIXME, disorder: chr19:36679181 vs 40001409  [1]" 

What does it mean? how serious is this? and is there any work around?

thanks,
Asta

**Comment by pd3** [comment]
The warning suggests truncated files, so I'd be worried about that, the program may not operate correctly if that's indeed the case. The second problem, can you please verify that the VCFs are sorted? You can run them through `bcftools sort` for example.
