### ISSUE TITLE
bcftools consensus: The fasta sequence does not match the REF allele

### ISSUE THREAD

**Issue by Thyra** [samtools/bcftools#1447]
Hi, I'm trying to build a pseudogenome from a reference FASTA and VCF file containing indels.
The reference chromosomes are at ftp://ftp.solgenomics.net/tomato_genome/assembly/build_4.00/S_lycopersicum_chromosomes.4.00.fa.gz, the VCF file is at ftp://ftp.solgenomics.net/genomes/tomato100/March_02_2020_sv_landscape/variants/BGV006175.ont.v1.0.s.vcf.gz .
When I run bcftools consensus it complains that the reference sequence and ref allele in the VCF don't match but the way I understand it that first first T is supposed to be replaced with that insertion.
Am I completely misunderstanding something here? (I'm using bcftools version v0.12.6)

```
$ wget ftp://ftp.solgenomics.net/tomato_genome/assembly/build_4.00/S_lycopersicum_chromosomes.4.00.fa.gz
$ wget ftp://ftp.solgenomics.net/genomes/tomato100/March_02_2020_sv_landscape/variants/BGV006175.ont.v1.0.s.vcf.gz
$ gunzip *
$ bgzip BGV006175.ont.v1.0.s.vcf
$ bcftools index BGV006175.ont.v1.0.s.vcf.gz
$ bcftools consensus -f S_lycopersicum_chromosomes.4.00.fa BGV006175.ont.v1.0.s.vcf.gz > chromosomes.fa
Note: the --sample option not given, applying all records regardless of the genotype
The fasta sequence does not match the REF allele at SL4.0ch01:1570264:
   .vcf: [T] <- (REF)
   .vcf: [TTATATATATATATATATATATATATATATAATATATATATATATATATATATATATATATATATATA] <- (ALT)
   .fa:  [TGTATATATATATATATATATATATATATAT]GTAATAGCAAATCAATAACTAAAATG
```

**Comment by pd3** [comment]
The version 0.12.6 does not seem like a valid version string, the latest is 1.12.

Your files have several problems which should be addressed first:

1) END tag is incorrect, see for example this warning
```
[W::vcf_parse_info] INFO/END=16301125 is smaller than POS at SL4.0ch01:16301144
```
This can be worked around with simply removing the tags:
```
bcftools annotate -x INFO/END BGV006175.ont.v1.0.s.vcf.gz -o rmme.bcf
bcftools index rmme.bcf
```

2) The REF allele in some cases does not match the fasta reference string:
```
bcftools norm -f S_lycopersicum_chromosomes.4.00.fa rmme.bcf -o /dev/null 
Reference allele mismatch at SL4.0ch01:1762274 .. REF_SEQ:'CG' vs VCF:'CN'
```

In order for `consensus` to work, the REF alleles in the VCF must match the fasta reference exactly.

**Comment by Thyra** [comment]
Thank you for the helpful response Petr! You're right, I obviously messed up something with the version number, I'm using version 1.11. I think I'll get in touch with the authors of the VCF, perhaps they did some pre-processing on the reference chromosomes which leads to these mismatches. I'll close the issue now and re-open in case any problems arise that may have to do with bcftools.
Thanks again and happy Easter!
