### ISSUE TITLE
bcftools call -A for Indels

### ISSUE THREAD

**Issue by arturotorreso** [samtools/bcftools#1454]
I wanted to bring up an example of what I think may be a small issue in bcftools call. This is possibly an extreme case, but I thought it could be worth reporting (unless I'm not understanding something!):

When I run this command: 
bcftools mpileup -A -x -E -pm3 -f $REF -q 0 -Q 0 -Ou $BAM_FILE | bcftools call -m | bcftools norm -Ov -f $REF

I get the following indel at position 854253. which is expected and confirmed in the BAM file. 

Chromosome	854252	.	G	.	285	.	DP=122;ADF=58;ADR=64;AD=122;MQSB=1;MQ0F=0;AN=2;DP4=58,64,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:122:0:58:64:122
**Chromosome	854252	.	GC	G	63	.	INDEL;IDV=107;IMF=0.877049;DP=122;ADF=1,54;ADR=0,52;AD=1,106;VDB=0.835541;SGB=-0.693147;MQSB=1;MQ0F=0;AC=2;AN=2;DP4=1,0,57,64;MQ=60	GT:PL:DP:SP:ADF:ADR:AD	1/1:90,255,0:122:0:1,54:0,52:1,106**
Chromosome	854253	.	C	.	227	.	DP=12;ADF=3;ADR=9;AD=12;MQSB=1;MQ0F=0;AN=2;DP4=3,9,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:12:0:3:9:12
Chromosome	854254	.	C	.	141	.	DP=119;ADF=57;ADR=62;AD=119;MQSB=1;MQ0F=0;AN=2;DP4=57,62,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:119:0:57:62:119

When instead I use the flag -A in bcftools call to show all the alternate alleles: 
bcftools mpileup -A -x -E -pm3 -f $REF -q 0 -Q 0 -Ou $BAM_FILE | bcftools call -m -A | bcftools norm -Ov -f $REF

That indel is now misplaced, indicating the gap at position 854254:

Chromosome	854252	.	G	.	285	.	DP=122;ADF=58;ADR=64;AD=122;MQSB=1;MQ0F=0;AN=2;DP4=58,64,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:122:0:58:64:122
**Chromosome	854252	.	GCC	GC,G	63	.	INDEL;IDV=107;IMF=0.877049;DP=122;ADF=1,54,3;ADR=0,52,12;AD=1,106,15;VDB=0.835541;SGB=-0.693147;MQSB=1;MQ0F=0;AC=2,0;AN=2;DP4=1,0,57,64;MQ=60	GT:PL:DP:SP:ADF:ADR:AD**	1/1:90,255,0,123,174,87:122:0:1,54,3:0,52,12:1,106,15
Chromosome	854253	.	C	.	227	.	DP=12;ADF=3;ADR=9;AD=12;MQSB=1;MQ0F=0;AN=2;DP4=3,9,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:12:0:3:9:12
Chromosome	854254	.	C	.	141	.	DP=119;ADF=57;ADR=62;AD=119;MQSB=1;MQ0F=0;AN=2;DP4=57,62,0,0;MQ=60	GT:DP:SP:ADF:ADR:AD	0/0:119:0:57:62:119

I think the inclusion of that alternative indel, which has very low support, somehow messed up the representation of the true gap, better supported, which is corrected shown without the -A flag as **Chromosome	854252	.	GC	G**.

In both cases the DP field clearly shows that the gap should be at position 854253 (as without the -A flag).

**Comment by pd3** [comment]
The calling is alright, it's the normalization step that confused you. With `-A` there are two deletions in a single record and the normalization cannot left-align and trim the 1bp deletion. Note that the program does in both cases the correct thing, biologically it is not possible to distinguish between
```
# the first case
GCC
G-C

# the second case
GCC
GC-
```
(if we neglect methylation etc)

You could split the multiallelic records into biallelic (`bcftools norm -m -`) and then the normalization should be able to left-align and trim the indel properly.
