### ISSUE TITLE
norm -m- does not split AD subfields in multiallelic site

### ISSUE THREAD

**Issue by xmzhuo** [samtools/bcftools#1457]
norm -m- command did not split the AD subfield

For example: The AD is 32,3,9,0 even after norm -m- command

The input 
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">

chr1    9299796 .       AT      A,TT,<NON_REF>  73.73   .       BaseQRankSum=-0.722;ClippingRankSum=0;DP=48;ExcessHet=3.0103;MLEAC=0,1,0;MLEAF=0,0.5,0;MQRankSum=-1.582;RAW_MQ=168250;ReadPosRankSum=-0.04      GT:AD:DP:GQ:PL:SB       0/2:32,3,9,0:44:99:111,173,943,0,641,979,205,833,706,864:17,15,6,6

bcftools norm -m- target.vcf.gz

output:
chr1    9299796 .       AT      A       73.73   .       BaseQRankSum=-0.722;ClippingRankSum=0;DP=48;ExcessHet=3.0103;MLEAC=0;MLEAF=0;MQRankSum=-1.582;RAW_MQ=168250;ReadPosRankSum=-0.04        GT:AD:DP:GQ:PL:SB       0/0:32,3,9,0:44:99:111,173,943:17,15,6,6
chr1    9299796 .       AT      TT      73.73   .       BaseQRankSum=-0.722;ClippingRankSum=0;DP=48;ExcessHet=3.0103;MLEAC=1;MLEAF=0.5;MQRankSum=-1.582;RAW_MQ=168250;ReadPosRankSum=-0.04      GT:AD:DP:GQ:PL:SB       0/1:32,3,9,0:44:99:111,0,979:17,15,6,6
chr1    9299796 .       AT      <NON_REF>       73.73   .       BaseQRankSum=-0.722;ClippingRankSum=0;DP=48;ExcessHet=3.0103;MLEAC=0;MLEAF=0;MQRankSum=-1.582;RAW_MQ=168250;ReadPosRankSum=-0.04        GT:AD:DP:GQ:PL:SB       0/0:32,3,9,0:44:99:111,205,864:17,15,6,6

**Comment by pd3** [comment]
The program cannot split the subfields because in your VCF it is defined as `Number=.`. For the splitting it would have to be defined as `Number=R`.
