### ISSUE TITLE
INFO/AD considers either forward or reverse reads to be informative

### ISSUE THREAD

**Issue by LaraFuhrmann** [samtools/bcftools#1458]
When comparing total coverage information (obtained from IGV) with the informative read counts in the FORMAT/AD field, we notice that the latter seems to only include either forward or reverse reads. 

For example, consider the [bamfile](https://github.com/samtools/bcftools/files/6270555/important_positions.bam.gz) and [reference](https://github.com/samtools/bcftools/files/6270637/NC_045512.2.fasta.txt). At position 4253 IGV reports the following coverages:
```
NC_045512.2:4.253
Total count: 1531
A : 0
C : 719 (47%, 359+, 360- )
G : 0
T : 812 (53%, 406+, 406- )
N : 0
```
After executing `bcftools mpileup -Ou -f "NC_045512.2.fasta"  --max-depth 1000000 --max-idepth 100000 --annotate INFO/AD important_positions.bam --output important_positions.bcf
`, the corresponding vcf entry looks like:
```
NC_045512.2     4253    .       C       T,<*>   0       .       DP=1531;AD=360,406,0;I16=359,1,406,0,27149,2.05374e+06,30392,2.28541e+06,21600,1.296e+06,24360,1.4616e+06,8924,222340,10096,252060;QS=0.470403,0.529597,0;VDB=0;SGB=-0.693147;RPB=0.984628;MQB=1;MQSB=1;BQB=0.911924;MQ0F=0        PL      255,0,255,255,255,255 
```

As you can see INFO/DP corresponds to the total count of IGV, but INFO/AD only considers the reverse reads to be informative. 

It does not seem obvious to us why this is happening? Is there a good reason for that, or can we deactivate that?

**Comment by pd3** [comment]
if you add `--ignore-overlaps` to the command, does this change anything?

**Comment by LaraFuhrmann** [comment]
Yes, thank you. Adding `--ignore-overlaps` we obtained the INFO/AD values as we would expect.
