### ISSUE TITLE
How DP and DP4 are counted ?

### ISSUE THREAD

**Issue by U201412486** [samtools/bcftools#1460]
Hi,

 When I ran bcftools mpileup and call to get the vcf file,I got DP and DP4 values for every snp site.And I found DP value = the 

rawdepth without UNMAP,SECONDARY,QCFAIL,DUP and anomalous read pairs.Sum DP4 can be smaller than DP because 

low-quality bases are not counted.But I could not find out how the DP4 was counted.

Can you explain this ?

thanks.

**Comment by pd3** [comment]
DP4 excludes in addition low quality reads and bases removed by -q and -Q options.

**Comment by U201412486** [comment]
Thank you for you reply.
  I have an another question.
  `bcftools mpileup [OPTIONS] -f ref.fa in.bam [in2.bam […]]
-C, --adjust-MQ INT
Coefficient for downgrading mapping quality for reads containing excessive mismatches. Given a read with a phred-scaled probability q of being generated from the mapped position, the new mapping quality is about sqrt((INT-q)/INT)*INT. A zero value disables this functionality; if enabled, the recommended value for BWA is 50. [0]`
  Where the -C option tell us the new mapping quality is about sqrt((INT-q)/INT)*INT. when -C is setted to 50, how does it handle the reads whose mapping quality(-q) > 50?
  Thanks a lot.
