### ISSUE TITLE
Trouble filtering based on ID

### ISSUE THREAD

**Issue by Shuwei1024** [samtools/bcftools#1467]
We have a bcf file that we want to filter based on SNP IDs. We created a .txt file listing our snps to be included. 
The snp.txt looks like this:
```
rs916005872
rs544625796
rs909071105
```

We used bcftools to select a subset of our samples, drop the genotypes and include the SNPs from our snp.txt file.
```
bcftools view -S sample_list.txt -G -i 'ID=@snp.txt' input.bcf
```
It subsetted our samples, dropped genotypes and ran perfectly for the first two snps but it crashes at the very end and does not complete the run for the last snp.
```
chr20	113935	rs909071105	G	A	255	PASS   LOG_HM3_BUDDY_08=0;LOG_HM3_DIST_03=6;
```
It just stops here with a few lines missing and we cannot progress any further.

Is there a problem with the '@' function?

Thank you.

**Comment by pd3** [comment]
This looks like a bug, this should work. Is there a chance you could provide a small test case to reproduce the problem?

**Comment by pd3** [comment]
What version of bcftools are you running?

**Comment by Shuwei1024** [comment]
> What version of bcftools are you running?

Sorry, it actually worked. Just very slow and took longer than we expected. Thank you!
