### ISSUE TITLE
missing CURL_OPENSSL_3 (libcurl3)

### ISSUE THREAD

**Issue by ckuenne** [samtools/bcftools#1478]
when running "bcftools view" with the most current version (1.12) i get an error:

bcftools view -Ob -T test.bed GCF_000001405.38.bcf 
bcftools: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by bcftools)

libcurl4 is installed by default in my debian (and also needed by other tools). so i can't downgrade to libcurl3. is there a way to circumvent this?

**Comment by pd3** [comment]
How did you install the program? Will it help if you run the configure script before compiling, as described here?
https://raw.githubusercontent.com/samtools/bcftools/develop/INSTALL

**Comment by ckuenne** [comment]
previously, i had installed with the following, resulting in an error:
```
./configure
make
```

i now switched to this:
```
autoheader && autoconf && ./configure --enable-libgsl --enable-perl-filters
make
```

which did work. thx!

**Comment by jkbonfield** [comment]
Can I just check if this was a build from the tar-ball or a git clone?  The tars (ie official releases) should always be up to date with respect to auto-tools and the configure script, so if you had a problem with that then it indicates we got something wrong.

From git however, it's a different story as `configure` is a generated file and not committed.  Even when you're just doing a git pull to refresh develop there will be times where you'll need to regenerate the configure script.

**Comment by ckuenne** [comment]
i downloaded the tar-ball from here: https://github.com/samtools/bcftools/releases/download/1.12/bcftools-1.12.tar.bz2

**Comment by jkbonfield** [comment]
Ok that's unexpected then.  I see the configure script in the tarball claims to have been generated by autoconf 2.69 which is the version we have on our Ubuntu 18.04 servers.  What does `autoconf --version` say for you?  Also what OS are you building this on?

Maybe there's some package update which is required for curl to work on some latest OS release or something.  It's a little surprising though.  I have to ask, but are you definitely sure you did `./configure; make` the first time and not just `make`?  It does have a vanilla Makefile setup that works (mostly) without autoconf, but it's not unexpected for this to fail on some systems.

**Comment by ckuenne** [comment]
i tried again from scratch using only the configure (without autoheader/autoconf) and this time it worked. i can't trace what went wrong, but i guess i really just missed the configure step last time. my bad, sorry.
