### ISSUE TITLE
Merging VCF files: Unexpected case: 7, HDS

### ISSUE THREAD

**Issue by rsteinfe1** [samtools/bcftools#1481]
Hi,

I get an error when I try to merge multiple VCF files into one. 
I tried to run:
```

bcftools --version
bcftools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

tabix -p vcf Subset1.vcf.gz 
tabix -p vcf Subset2.vcf.gz
bcftools merge -Oz -o test.vcf.gz Subset1.vcf.gz Subset2.vcf.gz
[W::bcf_hdr_merge] Trying to combine "HDS" tag definitions of different types
Unexpected case: 7, HDS
```
I can get rid of the warning, by changing the vcf meta line, but it's not causing the Unexpected case error.
I created a minimalistic reproducible example (see below).

Thanks,
R

[Subset2.vcf.gz](https://github.com/samtools/bcftools/files/6428332/Subset2.vcf.gz)
[Subset1.vcf.gz](https://github.com/samtools/bcftools/files/6428333/Subset1.vcf.gz)

**Comment by pd3** [comment]
The test case nicely highlights what is wrong and confirms that the hint given by the program is indeed correct. In one file the HDS tag is supposed to have one string value whereas in the other it is supposed to have two float values:
```
##FORMAT=<ID=HDS,Number=1,Type=String,Description="Estimated Haploid Alternate Allele Dosage">
##FORMAT=<ID=HDS,Number=2,Type=Float,Description="Estimated Haploid Alternate Allele Dosage">
```
This can't be merged as is. The only option is to modify the headers to have
```
##FORMAT=<ID=HDS,Number=.,Type=String,Description="Estimated Haploid Alternate Allele Dosage">
```
