### ISSUE TITLE
Multiple filters for bcftools query

### ISSUE THREAD

**Issue by tania-k** [samtools/bcftools#1492]
Hello all, 
I am trying to implement multiple filters to be passed through bcftools query but am receiving results that are not as strict as I would like.
I have run GATK on 23 organism strains and am filtering their results for more downstream analysis.

Currently the two main filters in consideration are: -e 'GT="."' -i 'QUAL<1000 
My script reads: 
Script 1. `bcftools query -e 'GT="."' -i 'QUAL<1000' -H -f '%CHROM\t%POS\t%QUAL\t%REF\t%ALT{0}[\t%TGT][\t%DP]\n'`

Reading through, I see that some rows still have a no call = "." but the number has been severely reduced compared to the original vcf file. Is there a certain threshold this filter reaches? That if in a row one strain has a no call versus another row with 18 strains have the no call, the row with one strain no call will remain?

Moving forward, I would like to implement two more filters. Our collaborator calculated standard deviations for the DP values and has given us hard values to filter and consider. 
In this case values between DP >8 and DP < 50. 
I have tried different iterations of this onto the original script above but results have been variable. 
Script 2. `bcftools query -e 'GT="."' -i 'QUAL<1000 && FORMAT/DP>8 && FORMAT/DP<50' -H -f '%CHROM\t%POS\t%QUAL\t%REF\t%ALT{0}[\t%TGT][\t%DP]\n'`

I have attempted with single '&' and double '&&'. My results have varied, where some rows have QUAL scores lower than 1000, DP numbers still have values lower than 8, and values higher than 50. One instance with using single '&' I had rows with a ton of no calls, when before script 1 had that row removed.

If I only have the filter -i 'FORMAT/DP>8' it removed the actual values and not the rows creating a weird and disjointed vcf file. Attached are files for your consideration. (DP_ONLY)

DP_ONLY is the file generated from filtered file to ONLY remove DP reads below 8. 
Just_1000_and_nocalls is the result from script 1.
Try_all_filter is when I have run the analysis using script 2. 

Please let me know if there's a formatting issue or I would need to do this in separate steps? i.e. bcftools query then bcftools view?

[Format_DP_ONLY.Exophiala.Run1.snpEff_CUTOFF.txt](https://github.com/samtools/bcftools/files/6503852/Format_DP_ONLY.Exophiala.Run1.snpEff_CUTOFF.txt)
[Just1000_and_nocalls.Exophiala.Run1.snpEff_CUTOFF.txt](https://github.com/samtools/bcftools/files/6503853/Just1000_and_nocalls.Exophiala.Run1.snpEff_CUTOFF.txt)
[Try_all_filter.Exophiala.Run1.snpEff_CUTOFF.txt](https://github.com/samtools/bcftools/files/6503854/Try_all_filter.Exophiala.Run1.snpEff_CUTOFF.txt)

**Comment by pd3** [comment]
Only one -i or -e expression can be given and they cannot be combined. In the latest version on github this is made clear, an error message is given to notify about this limitation.

If you want to apply multiple filters, this must be done in separate steps (make sure to stream uncompressed BCF from one command to another, e.g. `bcftools view -Ou ... |`).
