### ISSUE TITLE
merging VCF files obtained from IMPUTE2 output

### ISSUE THREAD

**Issue by SNgalaxy** [samtools/bcftools#1493]
Hello,

I started imputation with IMPUTEV2. I know it is an old version but I came this far. Now after converting the IMPUTE2 output to VCF files using SHAPEIT, I need to piece the chromosome chunks back together.

I am using bcftools in merging all the data : (my purpose is to merge all the VCF files and then import in plink file for QC and then making IBS matrix)
$BCFTOOLS merge --merge all vcf_chr1_chunk1.vcf.gz vcf_chr1_chunk2.vcf.gz vcf_chr1_chunk3.vcf.gz-O v > $results_merged_vcf'/Chromosome1.imputed.vcf 

Though the program asks for the index file using 
tabix -p vcf file.vcf.gz

I can not index the file as it needs to be sorted by chromosome. when I try to sort the program mention it can not parse through [---     45000037].
In my VCF file (after converting data from IMPUTE2 output file to VCF file) I have the format below for the imputed variants. How should I run the "bcftool index" for this VCF file?

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1610    2318    2421    
---     45000037        rs140328665:45000037:G:A        G       A       .       PASS    .       GT      0|0
---     45002242        1:45002242:G:A  G       A       .       PASS    .       GT      0|0

Thank you for your help in advance

**Comment by pd3** [comment]
The command `bcftools merge` does something different, for example, it creates a multi-sample VCF from multiple single-sample VCFs. In your case the number of samples does not change and you just want to concatenate chromosomal chunks. For this you want to use `bcftools concat`. This is described in the documentation.
