### ISSUE TITLE
bcftools reheader does not have an option to specify a temporary file when using --fai <file>

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1497]
bcftools reheader creates a temporary file when using the `--fai <file>` option using the following code:
```
    args->rm_tmpfile = strdup("/tmp/bcftools-fai-header-XXXXXX");
    int fd = mkstemp(args->rm_tmpfile);
    if ( fd<0 ) error("Could not open a temporary file for writing: %s\n", args->rm_tmpfile);
```
However, some systems don't have access to the `/tmp/` directory, causing this command to fail. (I have noticed this when running BCFtools within a singularity environment).

bcftools sort also creates temporary files, but it has a slightly different approach:
```
    args->tmp_dir = args->tmp_dir ? strdup(args->tmp_dir) : strdup("/tmp/bcftools-sort.XXXXXX");
    size_t len = strlen(args->tmp_dir);
    if ( !strcmp("XXXXXX",args->tmp_dir+len-6) )
    {
        char *tmp = mkdtemp(args->tmp_dir);
        if ( !tmp ) error("mkdtemp(%s) failed: %s\n",  args->tmp_dir,strerror(errno));
        int ret = chmod(tmp, S_IRUSR|S_IWUSR|S_IXUSR);
        if ( ret ) error("chmod(%s,S_IRUSR|S_IWUSR|S_IXUSR) failed: %s\n", args->tmp_dir,strerror(errno));
    }
    else {
        mkdir_p("%s/",args->tmp_dir);
    }
```
Where `args->tmp_dir` can be set with the `-T, --temp-dir <dir>` option.

I am not sure why bcftools reheader needs to create a temporary file when updating the header, but if this is absolutely necessary it would be helpful to have an option similar to bcftools sort to avoid using the `/tmp/` directory.

**Comment by pd3** [comment]
I added `reheader -T`option. If you encounter any problems, please do let us know
