### ISSUE TITLE
gtcheck Discordance calculation

### ISSUE THREAD

**Issue by clin113jhu** [samtools/bcftools#1500]
I am a bit confused about how the gtcheck (1.12-1-g9aeb1aa) calculates discordance.
Here is the input vcf :

 #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  s1      s2      s3      s4      s5  s6
11      33      v9      C       A       .       PASS    .       GT      0|0     0|0     0|1     0|0     1|1 0|0

If I use the following command to gtcheck against itself,
`bcftools gtcheck -g example.vcf.gz example.vcf.gz`
I get the following output:
![image](https://user-images.githubusercontent.com/44105347/120430503-b3e5c000-c3a9-11eb-83da-1660211705ea.png)

I know that the lower the discordance, the better. However, what does 0.0002 discordance in the first line actually mean? They are the exact same genotype, shouldn't it just be 0?
Also for query : s1 sample : s3, why is the discordance 9.9? Isn't it just 1 since this particular genotype did not match?

It seems like all the matched genotypes are 0.0002 discordance while non-matching genotypes are 9.9 discordance

Can someone please clarify this for me? I'm trying to calculate the concordance rate between two vcf.
Thanks!!

**Comment by pd3** [comment]
The program takes into account the possibility of a genotyping error, try to run with `-e 0`
```
    -e, --error-probability INT        Phred-scaled probability of genotyping error, 0 for faster but less accurate results [40]
```

**Comment by clin113jhu** [comment]
That makes sense now. Thanks!
I'm assuming that if the default -e is 30, then the gtcheck will automatically assume that there is 1 error in every 1000 genotype?

**Comment by pd3** [comment]
Yes, that's the correct interpretation.

**Comment by goeckeritz** [comment]
I thought this issue would be appropriate for a quick question:

Does setting -e 0 still give discordance as the number of mismatches when the tag comparison is PL-vs-PL? Or is this the case only when the tag comparison is GT-vs-GT?
