### ISSUE TITLE
Clarification on GQ field when using bcftools call

### ISSUE THREAD

**Issue by David-Peede** [samtools/bcftools#1502]
Hello! Recently I noticed that bcftools call will only generate GQ fields for variant sites and not invariant sites (homozygous ref) when generating an all sites VCF, and it is unclear to me if invariant sites can have a GQ field or not (page 4 of the VCF file specification leads me to believe you can, but page 10 makes me believe otherwise https://samtools.github.io/hts-specs/VCFv4.3.pdf).

Could someone help clear up my confusion?

Here is the general code I use to generate an all sites VCF:

`bcftools mpileup -f my_ref.fa my_bam.bam | bcftools call -m -Oz -f GQ -o my_vcf.gz`

Thanks in advance for the help!
-Dave

**Comment by pd3** [comment]
The genotype quality is conditioned on the site being variable, so we don't compute those. One could probably calculate a score of some type, but bcftools does not do it.
