### ISSUE TITLE
atomize option to bcftools norm removes FORMAT String tags with Number=A

### ISSUE THREAD

**Issue by briankegerreis** [samtools/bcftools#1503]
I have a VCF that includes a String FORMAT tag like this:
```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=VF,Number=A,Type=Float,Description="Variant Frequency">
##FORMAT=<ID=STR,Number=A,Type=String,Description="String that goes missing">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
chr1    150     .       TAT     CCC     100     PASS    AC=1;AN=2;TYPE=MNP     GT:VF:STR        0/1:0.1:DATA
```
When I do `bcftools norm -a in.vcf`, it removes the STR tag. Is this intended behavior, and am I being cavalier with the FORMAT field? TMI: The reason I'm not using INFO/STR is because this feeds into Illumina's hap.py engine, which adds INFO/TRUTH_FMT and INFO/QUERY_FMT for each variant to the output VCF.

Thanks!

**Comment by pd3** [comment]
Uh, string tags defined as Number=A,R,G are not implemented yet, sorry :-/

**Comment by pd3** [comment]
The support for Number=A,R string annotations has been now added.
