### ISSUE TITLE
bcftools csq did not annotate the consequence.vcf files

### ISSUE THREAD

**Issue by DianeTerry** [samtools/bcftools#1507]
I generated variant calls with bcftools and had no error messages.  Then I ran bcftools csq and it also had no error messages and generated consequence.vcf files for each of the vcfs but bcftools csq did not annotate the consequenc.vcf files.

Below are the commands I used:
bcftools mpileup -d 8000 -Ou -f  /local/projects-t3/DEVINElab/MELT_ref/GRCh38_original/GRCh38_full_analysis_set_plus_decoy_hla.fa 14757.sorted.bam | bcftools call -mv -Ov -o 14757.variantcalls.vcf

bcftools csq -f /local/projects-t3/DEVINElab/MELT_ref/GRCh38_original/GRCh38_full_analysis_set_plus_decoy_hla.fa -g Homo_sapiens.GRCh38.104.gff3.gz 14757.variantcalls.vcf -Ov -o 14757.consequence2.vcf

**Comment by pd3** [comment]
The consequence command looks good. Are there any variants in the VCF file? Do chromosome names in the GFF file match the chromosome names in the VCF, e.g. one has the 'chr' prefix while the other does not?

**Comment by DianeTerry** [comment]
Hi Petr,

There are variants in the variants.vcf and they are in the chr format, see below.  It looks like the GFF file is in the number only format (no chr).  Is there a different GFF file with the chr format I can download?




#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  21738.sorted.bam

chr1    10257   . A C 11.9979 . DP=57;VDB=0.448427;SGB=-0.616816;RPB=0.999243;MQB=0.996974;MQSB=0.235073;BQB=0.2628;MQ0F=0.105263;ICB=1;HOB=0.5;AC=1;AN=2;DP4=11,4,6,0;MQ=21    GT:PL   0/1:45,0,123

chr1    10327   . T C 23.3617 . DP=68;VDB=0.414247;SGB=-0.683931;RPB=0.858374;MQB=0.394875;MQSB=0.571589;BQB=0.632027;MQ0F=0.132353;ICB=1;HOB=0.5;AC=1;AN=2;DP4=5,15,5,8;MQ=22  GT:PL   0/1:57,0,208

chr1    10492   . C T 3.64125 . DP=5;VDB=0.66;SGB=-0.453602;RPB=0.666667;MQB=0.666667;BQB=0.666667;MQ0F=0.2;ICB=1;HOB=0.5;AC=1;AN=2;DP4=0,3,0,2;MQ=28   GT:PL   0/1:34,0,60

chr1    11409   . A G 5.04598 . DP=27;VDB=0.269029;SGB=-0.692717;MQSB=1;MQ0F=0.851852;AC=2;AN=2;DP4=0,0,11,12;MQ=0 GT:PL   1/1:33,69,0

chr1    12807   . C T 19.1757 . DP=33;VDB=0.0737997;SGB=-0.692914;RPB=0.0309138;MQB=0.905462;MQSB=0.585378;BQB=0.369405;MQ0F=0.727273;AC=2;AN=2;DP4=2,1,15,10;MQ=2 GT:PL   1/1:46,47,0

chr1    13079   . C G 32.2454 . DP=7;VDB=0.0170667;SGB=-0.590765;RPB=1;MQB=1;MQSB=0;BQB=1;MQ0F=0.285714;AC=2;AN=2;DP4=1,0,1,4;MQ=12     GT:PL   1/1:59,10,0

chr1    13418   . G A 39.4101 . DP=30;VDB=0.00453739;SGB=-0.691153;RPB=0.616901;MQB=0.0925878;MQSB=1;BQB=0.998851;MQ0F=0.3;ICB=1;HOB=0.5;AC=1;AN=2;DP4=9,1,18,0;MQ=12   GT:PL   0/1:73,0,17

Diane Terry (shes/her/hers)
PhD Candidate
Molecular Medicine
University of Maryland School of Medicine
Baltimore, Maryland
HSFIII 3130
________________________________

**Comment by pd3** [comment]
The gff file could be modified by a trivial perl one line command 
```
cat file.gff | perl -pe 's/^([0-9]+)/chr$1/'
```

However, I modified the program to automatically detect such differences between naming convention in the gff and the fasta file. 

Please try it out and let me know if you spot any problems.

**Comment by pd3** [comment]
I am glad that you managed to solve the problem. I am curious why the modified software did not work. Were you able to get the latest clone from github, compile it (http://samtools.github.io/bcftools/howtos/install.html) and the latest version still did not work?

**Comment by DianeTerry** [comment]
No, sorry still new to bioinformatics.  I will get the latest clone and try it (probably tomorrow as doing wet labwork right now).

Diane Terry (shes/her/hers)
PhD Candidate
Molecular Medicine
University of Maryland School of Medicine
Baltimore, Maryland
HSFIII 3130
________________________________

**Comment by DianeTerry** [comment]
The new version has to be installed by our IT department.  When I get it and try it I will let you know.

Diane Terry (shes/her/hers)
PhD Candidate
Molecular Medicine
University of Maryland School of Medicine
Baltimore, Maryland
HSFIII 3130
________________________________

**Comment by b-math** [comment]
Hello,

I experienced the problem in this issue:
no variants were emitted when having the "chr" representation in the .vcf and just numbers in the .gff file. Changing the gff file with the perl code you mentioned above did the trick. Btw. your code only changes chr1-22, not chrX and Y ;)

Best regards
Barbara
