### ISSUE TITLE
custom expression using F_PASS / N_PASS for +fill-tags plugin

### ISSUE THREAD

**Issue by edg1983** [samtools/bcftools#1509]
I'm currently using bcftools v1.12 and I would like to annotate my VCF with fraction and number of calls passing certain criteria.
For this, I'm trying to use the F_PASS and N_PASS expressions like they are used with `-i` or `-e`

So something like
```
bcftools +fill-tags \
input.vcf.gz \
-Oz -o output.stats.vcf.gz \
-- -t 'F_PASS=F_PASS(GQ >= 10 && DP >=6)'
```

However, this does not work since the expression is not recognized 
`Error: the expression not recognised`

Is it possible to implement this kind of expression or you have other suggestions on how to achieve a similar result?

Thanks!

**Comment by pd3** [comment]
The support for this type of expressions was limited. The commit 5dd3b41 extends the possibilities somewhat, but it is likely not everything one can think of is going to work now. Please try it out and let us know in case of problems.
