### ISSUE TITLE
bcftools merge issue

### ISSUE THREAD

**Issue by userzxyz** [samtools/bcftools#1510]
Hello,

I have used `bcftools` to merge multiple `vcf` files. I have five` vcf` files with 20 samples in each file. I merged these five vcf files using:
`bcftools merge file_1.vcf.gz file_2.vcf.gz file_3.vcf.gz file_4.vcf.gz file_5.vcf.gz  > merged.vcf`

I have noticed some weird issues in the merged file. The `GT` calls for all the samples from file_1.vcf.gz are changed to `./.:.:.:.:.:.:.:.` for most of the loci that I checked. Can you please help figure out why the calls are changed to `./.:.:.:.:.:.:.:.` after `merge` step? Thank you!

**Comment by pd3** [comment]
What is most likely happening is that there are sites in file X not present in file Y, thus missing genotypes are filled in instead. This is expected behavior. If this is not what is happening, more information would be needed, ideally a small test case to reproduce the problem.
