### ISSUE TITLE
bcftools mpileup: supply REF and ALT alleles in the -R option?

### ISSUE THREAD

**Issue by rcheng** [samtools/bcftools#1515]
bcftools mpileup accepts a list of given sites, which is good. In case the REF and ALT alleles are known at these sites, it will be desirable to provide the REF and ALT and genotypes are called using the given allele information. For example,
chr1    49758   .       A       .       9.69683 .       DP=2;SGB=-0.00267373;RPB=1;MQB=1;MQSB=1;BQB=1;MQ0F=0;AN=2;DP4=0,1,1,0;MQ=30     GT:DP   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:2   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
bcftools treats the ALT allele as missing, and this site will be excluded if we want biallelic SNPs only; however, the ALT allele is known and this site is biallelic. In addition, PL can be calculated if bcftools accepts the ALT allele.

In a given model organism such HS rats, REF/ALT alleles are often known at a list of sites of interest and we may be only interested in these sites. Maybe, such functionality is already available but I don't know it. Or, is it possible to add this option?

**Comment by pd3** [comment]
The alleles can be forced at the `bcftools call` step via the `-C alleles` and `-T` options. For example:
```
bcftools query -f'%CHROM\t%POS\t%REF,%ALT\n' alleles.vcf | bgzip -c > als.tsv.gz
tabix -s1 -b2 -e2 als.tsv.gz
bcftools mpileup .. | bcftools call -C alleles -T als.tsv.gz 
```

**Comment by rcheng** [comment]
Yes! That seems to work. Thank you!

**Comment by rcheng** [comment]
I've been testing the -C and -T options. But the result is not as expected (see below for example: at position 35129 the ALT allele is not replaced by C as given in the -T option). Is there anything wrong in my code or files? Thank you!

# commands
fls=$(ls bams/*_mkDup.bam)
bcftools mpileup --no-version -a FORMAT/DP -q 13 -Q 13 \
      --threads 15 \
      -R chr01.rsv.gz \
      -C alleles \
      -T chr01.tsv.gz \
      -f rn6.fa \
      -O v \
      $fls | \
bcftools call --no-version -m \
      --threads 15 \
      -C alleles \
      -T chr01.tsv.gz \
      -O z \
      -o chr01_smtl.vcf.gz

# first few lines of chr01.rsv.gz
chr1    4441
chr1    4785
chr1    34506
chr1    35129
chr1    35130
chr1    35132

# first few lines of chr01.tsv.gz
chr1    4441    C,T
chr1    4785    A,G
chr1    34506   A,C
chr1    35129   T,C
chr1    35130   C,T
chr1    35132   T,C

# position 35129 in chr01_smtl.vcf.gz
chr1    35129   .       T       .       477.939 .       DP=18;MQSB=0;MQ0F=0;AN=24;DP4=10,2,0,0;MQ=44    GT:DP   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   0/0:1
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   0/0:1
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   0/0:1   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   ./.:0   0/0:1   ./.:0   ./.:0   ./.:0
   ./.:0   ./.:0   ./.:0

**Comment by pd3** [comment]
Will it help if you add `call -A, --keep-alts` option?

**Comment by rcheng** [comment]
Yes! It seems to work. Thank you!

(We could set the -A option to default if given the -C and -T options. By the way, I am not sure why not all sites (~2%) supplied by the -C and -T options are taken; however, it is already pretty good.)

**Comment by pd3** [comment]
Is it possible that the missing sites have no coverage? Try the `call -i, --insert-missed` option

**Comment by rcheng** [comment]
Many thanks!

The -A and -C options seem to work well. Not sure if the -i option works as
expected (e.g. assign missing to the sites or still uses read information)
so I proceed without it.

Sincerely,
Riyan Cheng

**Comment by pd3** [comment]
The `-i` option assigns missing genotypes to sites with no coverage when there is no read information available.
