### ISSUE TITLE
bcftools consensus: conditionally apply IUPAC codes?

### ISSUE THREAD

**Issue by charlesfoster** [samtools/bcftools#1516]
Hi,

I am shifting some of our pipelines from `ivar` to `bcftools`. However, one feature that I miss is the conditional incorporation of IUPAC ambiguities depending on variant allele frequency (VAF, but referred to as ALT_FREQ below because of the VCF's tags) (https://andersen-lab.github.io/ivar/html/manualpage.html#autotoc_md19). Ideally, I would like to mimic ivar's result of applying a variant if it is above a certain VAF, but, if it falls below the VAF threshold, applying an IUPAC ambiguity instead. 

Consider the following variants:

REGION | POS | REF | ALT | ALT_QUAL | REF_DP | ALT_DP | TOTAL_DP | ALT_FREQ
-- | -- | -- | -- | -- | -- | -- | -- | --
NC_045512.2 | 11744 | G | A | 59 | 199 | 23 | 222 | 0.103604
NC_045512.2 | 28473 | C | T | 66 | 52 | 7 | 59 | 0.118644

If I use `ivar` with the following command, I get an 'R' (A or G) at 11744 and a 'Y' (C or T) at 28473, and all variants occurring at a VAF >= 0.9 are called as the correct variant:

`samtools mpileup -A -d 0 -Q 0 -B --reference $REF $BAM | ~/miniconda3/envs/COVID_Pipeline/bin/ivar consensus -p $PREFIX -q 20 -m 10 -t 0.9`

If I use the following `bcftools` consensus command, I get a G at 11744 and a C at 28473 because the variants occur at a VAF < 0.9, and  all other variants are incorporated as IUPAC ambiguities, even if they occur at a VAF of 1:

`bcftools consensus --iupac-codes -p $PREFIX -f $REF --mark-del '-' -m $MASK  -i 'FORMAT/ALT_FREQ >= 0.90 & FORMAT/ALT_QUAL >= 20 & INFO/DP >= 10' $PREFIX.vcf.gz`

The **desired** outcome would be for all variants occurring at a VAF > 0.90 to be called as the correct variant, and all variants occurring at a VAF < 0.9 to be called as IUPAC ambiguities. Is this possible?

Version info:
bcftools 1.12-73-gc95bb12
Using htslib 1.12-53-gbfb2df1

Thanks,
Charles

**Comment by pd3** [comment]
Alas, this is currently not possible. You could, however, use the plugin `bcftools +setGT` to force homozygous genotypes where you need and use IUPAC codes for the rest.

This request is similar to https://github.com/samtools/bcftools/issues/1488.

**Comment by charlesfoster** [comment]
Thanks for the suggestion. I first tried setting the variants that I want to NOT be represented as IUPAC codes to a genotype of 1/1 with `bcftools +setgt`:

`bcftools +setGT $PREFIX.vcf.gz -- -t q -i 'GT="1" && FORMAT/ALT_FREQ >= 0.9' -n 'c:1/1'`

I'm not sure if that's the correct way to go about it, but, in any case, I got the following output:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##source=iVar
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FILTER=<ID=FAIL,Description="Result of p-value > 0.05">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=REF_DP,Number=1,Type=Integer,Description="Depth of reference base">
##FORMAT=<ID=REF_RV,Number=1,Type=Integer,Description="Depth of reference base on reverse reads">
##FORMAT=<ID=REF_QUAL,Number=1,Type=Integer,Description="Mean quality of reference base">
##FORMAT=<ID=ALT_DP,Number=1,Type=Integer,Description="Depth of alternate base">
##FORMAT=<ID=ALT_RV,Number=1,Type=Integer,Description="Depth of alternate base on reverse reads">
##FORMAT=<ID=ALT_QUAL,Number=1,Type=Integer,Description="Mean quality of alternate base">
##FORMAT=<ID=ALT_FREQ,Number=1,Type=Float,Description="Frequency of alternate base">
##contig=<ID=NC_045512.2>
##bcftools_pluginVersion=1.12-73-gc95bb12+htslib-1.12-53-gbfb2df1
##bcftools_pluginCommand=plugin setGT -- nCoV_454.vcf.gz -t q -i 'GT="1" && FORMAT/ALT_FREQ >= 0.9' -n c:1/1; Date=Mon Jul  5 10:12:32 2021
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
todo: increasing ploidy
```

Presumably it's failing because this viral sample is not diploid, and bcftools was designed for diploid organisms? In any case, I manually changed all of the 'good' variants to a genotype of 1/1, and all the 'bad' variants to 0/1. I then re-ran the consensus step like so:

```
bcftools consensus -p $PREFIX -f ${REF} --mark-del '-' -m $MASK --iupac-codes -i 'FORMAT/ALT_QUAL >= 20 & INFO/DP >= 10' mytest.vcf.gz > mytest.con.fasta
```
I thought that only the 0/1 genotype variants would end up with IUPAC codes, but instead _all_ variants did. Evidently I'm interpreting the solution wrong.

The method that ended up working for me was to use two rounds of `bcftools consensus`:

1. `bcftools consensus` with the normal reference genome using only the variants with a variant allele frequency >= 0.9, no coverage mask, no `--iupac-codes` option
2. `bcftools consensus` with the 'preconsensus' genome from step 1 using only the variants with a variant allele frequency < 0.9, coverage mask included, `--iupac-codes` option included

The end result is a consensus genome with high-frequency variants implemented as the variants themselves, and low-frequency variants implemented as IUPAC codes.

**Comment by pd3** [comment]
Ah, I did not realize you were working with haploid genotypes and using the REF+ALT columns, rather than FORMAT/GT, to set the consensus. Currently the `+setGT` plugin cannot increase the ploidy, but this can be fixed. The suggested solution would then require the inverse, enforcing heterozygous genotypes 0/1 in places where IUPAC codes should be applied. Would that make sense?

**Comment by charlesfoster** [comment]
I think that would make sense, assuming the steps would be the following:

(1) Call variants to get a VCF file
(2) Using a version of `+setGT` that can 'diploidise' VCF files, set the genotypes for 'bad' variant to 0/1 and 'good' variants to 1/1. Not sure if it can be done in a single step, but:
```
bcftools +setGT mytest.vcf.gz -- -t q -i 'GT="1" && FORMAT/ALT_FREQ < 0.9' -n 'c:0/1'
bcftools +setGT mytest.vcf.gz -- -t q -i 'GT="1" && FORMAT/ALT_FREQ >= 0.9' -n 'c:1/1'
```
(3) Call a consensus with the iupac codes option:
```
bcftools consensus -p $SAMPLE -f ${REF} --mark-del '-' -m $MASK --iupac-codes -i 'FORMAT/ALT_QUAL >= 20 & INFO/DP >= 10' mytest.vcf.gz > mytest.con.fasta
```

**Comment by pd3** [comment]
The increased ploidy is now supported.

Regarding the consensus command, you'll need to replace `-I, --iupac-codes` with `-H I`. The first applies REF+ALT columns regardless of the genotypes, the latter works with sample genotypes.

**Comment by charlesfoster** [comment]
I cloned the changes, rebuilt `bcftools`, and gave it a go:

```
bcftools +setGT mytest.vcf.gz -- -t q -i 'GT="1" && FORMAT/ALT_FREQ < 0.9' -n 'c:0/1' | \
bcftools +setGT -o mytest.setGT.vcf.gz -- -t q -i 'GT="1" && FORMAT/ALT_FREQ >= 0.9' -n 'c:1/1'
tabix -p vcf mytest.setGT.vcf.gz
bcftools consensus -p test_ -f ${REF} --mark-del '-' -m $MASK -H I -i 'FORMAT/ALT_QUAL >= 20 & INFO/DP >= 10' mytest.setGT.vcf.gz > mytest.con.fasta
```
The analysis worked a treat, with variants with a VAF <0.9 being represented by IUPAC codes and variants >=0.9 VAF being represented by the variant. The only issue now is some probably variants not being called in the first place, but that's a separate issue I'll investigate further, and I'll start a new Github issue if need be. Thanks!
