### ISSUE TITLE
FILTER exact match can‘t work as expected

### ISSUE THREAD

**Issue by sssimonyang** [samtools/bcftools#1519]
I have a vcf file downloaded from TCGA.
```
$ grep -v '#' test.vcf
chr1    54490   rs141149254     G       A       .       panel_of_normals        DB;ECNT=2;HCNT=1;MAX_ED=4;MIN_ED=4;NLOD=0.602;TLOD=4.50       GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:PGT:PID:QSS:REF_F1R2:REF_F2R1  0/0:4,0:0.00:0:0:.:0|1:54486_T_C:76,0:4:0       0/1:0,2:1.00:0:2:0.00:0|1:54486_T_C:0,62:0:0
chr1    591356  rs28863004      C       G       .       germline_risk;panel_of_normals  DB;ECNT=1;HCNT=2;MAX_ED=.;MIN_ED=.;NLOD=0.903;TLOD=4.22       GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1  0/0:4,0:0.00:0:0:.:122,0:2:2    0/1:1,3:0.667:0:3:1.00:29,65:0:1
```
I want get the records with FILTER=`panel_of_normals`, not just containing `panel_of_normals`. For example, preserve the first one and discard the second one above.
In [bcftools manual](http://samtools.github.io/bcftools/bcftools.html#expressions), it says 
```
FILTER="A"          .. exact match, for example "A;B" does not pass
```
so I use this command 
```
$ bcftools view -i 'FILTER="panel_of_normals"' test.vcf | grep -v '#'
```
It turns out that this command output all records containing `panel_of_normals`, not exact match. The output of this command is totally same as `FILTER~"panel_of_normals"`.

I am wondering where I did wrong or the bcftools has bug in this point.
Thank for you helping!

**Comment by pd3** [comment]
You are probably using an outdated version of bcftools? This works with the latest version:
```
bcftools view -H rmme.vcf -i 'FILTER="panel_of_normals"'
1	1000	.	G	A	.	panel_of_normals	.

bcftools view -H rmme.vcf -i 'FILTER~"panel_of_normals"'
1	1000	.	G	A	.	panel_of_normals	.
1	1000	.	G	A	.	germline_risk;panel_of_normals	.
```
