### ISSUE TITLE
Segfault in mendelian plugin when passing incomplete trio

### ISSUE THREAD

**Issue by ASLeonard** [samtools/bcftools#1520]
Hi,
This is probably not a common use case, so may just be a usage error.

Running `bcftools +mendelian vcf -t missing,father_ID,child_ID` with say only 2 samples (mother/child or father/child) will sometimes work fine and sometimes result in a segfault. I couldn't pin down why the segfault only seems to happen with some vcfs, but the offending line is [here](https://github.com/samtools/bcftools/blob/3f0d5488490a4a90f1dfd17672404e08245268eb/plugins/mendelian.c#L514), where `bcf_hdr_int2id` is called on a nonexistent sample (passed as "missing" in the command line for option '-t').

I am again unsure why this works sometimes and not others, but by replacing the `bcf_hdr_int2id` calls directly with mother/father/child allows the program to complete. I feel like all cases with only 2 names *should* segfault, as the respective code in htslib is `#define bcf_hdr_int2id(hdr,type,int_id) ((hdr)->id[type][int_id].key)`.

Using 
```
bcftools 1.12-1-g9aeb1aa-dirty
Using htslib 1.12-1-g9672589-dirty
```

Thanks,
Alex

**Comment by pd3** [comment]
Thank you for the bug report, this is now fixed.
