### ISSUE TITLE
Average depth across samples for one variant

### ISSUE THREAD

**Issue by wym0072003** [samtools/bcftools#1521]
Hi,

Can you please give an example of how to use bcftools to get the average depth across samples for each variant?
I have tried ' bcftools  query -f 'MEAN(%DP)\n' top-sample.vcf.gz', but it doesn't work, please give a short example how I should format the command line. Thanks in advance.

Best,

Yiming

**Comment by pd3** [comment]
The expressions supported by `format -f` are different from those used by the `-i/-e` filtering expressions, please see the full list here http://samtools.github.io/bcftools/bcftools.html#query

However, with the latest updates to `+fill-tags` (https://github.com/samtools/bcftools/commit/2e3f8c8131964216f61eda89ab582423ee2a77d4), you should be able to do something like this:
```
bcftools +fill-tags -Ou file.vcf -- -t 'MEAN_DP:1=int(sum(DP))' | bcftools query -f'%MEAN_DP\n'
```

**Comment by wym0072003** [comment]
Thanks very much!

**Comment by wym0072003** [comment]
> The expressions supported by `format -f` are different from those used by the `-i/-e` filtering expressions, please see the full list here http://samtools.github.io/bcftools/bcftools.html#query
> 
> However, with the latest updates to `+fill-tags` ([2e3f8c8](https://github.com/samtools/bcftools/commit/2e3f8c8131964216f61eda89ab582423ee2a77d4)), you should be able to do something like this:
> 
> ```
> bcftools +fill-tags -Ou file.vcf -- -t 'MEAN_DP:1=int(sum(DP))' | bcftools query -f'%MEAN_DP\n'
> ```

Error parsing "--tags MEAN_DP:1=int(sum(DP))": the tag "MEAN_DP:1=int(sum(DP))" is not supported
Seemed doesn't work, should I update my bcftool? From my understand, the command adds a column of 'MEAN_DP' in INFO, could you please further explain how 'MEAN_DP:1=int(sum(DP))' works, seems it only gets the SUM of the depths of all samples literally.

Best,

Yiming

**Comment by pd3** [comment]
That was a typo, the example was taken from the commit message and edited, sorry. It should be `avg(DP)`, not `sum(DP)`, of course. Yes, you need 1.13 or newer code from github.
