### ISSUE TITLE
bcftools failed to normalize a certain INDEL position

### ISSUE THREAD

**Issue by BinglanLi** [samtools/bcftools#1524]
Bcftools norm failed to recognize a specific multiallelic INDEL position.

Commands:
```
bcftools norm -m+ -c ws -f ref.fna input.vcf
```

Lines in the input.vcf to be normalized
```
chr13	48037795	rs746071566	GGGAGTC	G	.	PASS	Variant_A	GT	./.
chr13	48037801	rs746071566	G	GGAGTCG	.	PASS	Variant_B	GT	./.
```

Expected normalized output
```
chr13	48037782	rs746071566	AGGAGTC	A,AGGAGTCGGAGTC	.	PASS	Variant_A,Variant_B	GT	./.
```

Actual output from the bcftools
```
chr13	48037782	rs746071566	A	AGGAGTC	.	PASS	Variant_B	GT	./.
chr13	48037795	rs746071566	G	GGGAGTC	.	PASS	Variant_A	GT	./.
```

What is actually going on with the bcftools normalization in this case?

**Comment by pd3** [comment]
The output looks rather odd. Can you please check what version of bcftools you are using and try with the latest github version please?  Also, to reproduce the bug, we need to know which reference genome is this.

**Comment by BinglanLi** [comment]
They were the v1.12 and v1.11 that I tried. It turned out that REF allele information was wrong. The REF allele doesn't match the reference genome ([NCBI GenBank GRCh38](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna)). The Once I fixed the alleles. Bcftools yielded the expected results.
