### ISSUE TITLE
bcftools view -p 1.1 meets error

### ISSUE THREAD

**Issue by shangyf-stu** [samtools/bcftools#1533]
Dear sir or madam,
I am sorry to interrupt you.
I am running a tool, which uses bcftools, the command is as follows
`samtools mpileup -d 100000 -L 100000 -q 10 -r chr1:1-50000000 -uf /ref/hg19_random.fa /test/data/ILMN01T.chr.bam | bcftools view -p 1.1 -vcg ->/raw_ILMN01T.vcf`

Unfortunately, I meet an error
`[E::hts_open_format] fail to open file '1.1'
Failed to open 1: No such file or directory
[mpileup] 1 samples in 1 input files` 

Could you give me some suggestions? 
And I really don't understand parameter -p,  if you can give me some examples, it will be helpful.

best,
Shang

**Comment by pd3** [comment]
The command you show is deprecated (a long time). Please upgrade to the latest version and do variant calling as described here  http://samtools.github.io/bcftools/howtos/variant-calling.html
