### ISSUE TITLE
bcftools stats --af-bins only output one bin

### ISSUE THREAD

**Issue by lanxianmei** [samtools/bcftools#1537]
Hi,

I want to count snp number distribution according to AF, my command as follow:
bcftools stats --split-by-ID --af-bins 0.1,0.5,1 vcf.gz

but I only got one bin result for each group:
     50 # AF    [2]id   [3]allele frequency     [4]number of SNPs       [5]number of transitions        [6]number of transversions      [7]number of indels     [8]repeat-consistent    [9]repeat-inconsistent  [10]not applicable
     51 AF      0       0.050000        2137720 1532882 604838  498643  0       0       498643
     52 AF      1       0.050000        6208189 3966005 2242184 641174  0       0       641174

what I set wrong?

**Comment by pd3** [comment]
I think this is what is happening: the command uses either AC/AN to estimate the frequencies or FMT/GT when AC,AN is not present. However, by default the sample fields are dropped to speed up parsing of large VCFs. Can you try to add the `-s -` option?

**Comment by lanxianmei** [comment]
Thanks, it works! Great!
