### ISSUE TITLE
bcftools gtcheck discordance error by factor 10 ?

### ISSUE THREAD

**Issue by StefanReuscher** [samtools/bcftools#1538]
I have been using bcftools gtcheck to do pairwise combination of samples, array vs. sequencing. If I run without -e 0 it seems the discordance rates are off by a factor of ten:

This is bcftools 1.12 via bioconda. Non of the files have a PL tag present.

```
without -e 0

bcftools gtcheck  --no-HWE-prob -p geno1,geno1,geno2,geno2,.... -g file.bcf anotherfile.bcf

#DC	[2]Query Sample	[3]Genotyped Sample	[4]Discordance	[5]-log P(HWE)	[6]Number of sites compared
DC	geno1 geno1 2.071227e+04	0.000000e+00	269011
DC	geno2	geno2	7.270713e+05	0.000000e+00	268677
...

with -e 0

bcftools gtcheck  -e 0 --no-HWE-prob -p geno1,geno1,geno2,geno2,.... -g file.bcf anotherfile.bcf

#DC	[2]Query Sample	[3]Genotyped Sample	[4]Discordance	[5]-log P(HWE)	[6]Number of sites compared
DC	geno1 geno1	2086	0.000000e+00	269011
DC	geno2	geno2	73411	0.000000e+00	268677
...

```

**Comment by pd3** [comment]
I don't understand what is the problem? With `-e 0` every mismatch is considered as a hard mismatch. With the default (`-e 40`), there is a non-zero probability that the mismatch is due to a genotyping error, hence the discordance is different. In both cases the relative difference between geno1 and geno2 (geno2-vs-geno2 / geno1-vs-geno1) is 35x, the outcome is consistent.

Note that the discordance scores are not comparable across different VCFs. They can be used safely only to compare the relative difference between samples within the same VCF and similar number of accessible sites.

**Comment by StefanReuscher** [comment]
Thanks for clarifying that. So -e 40 will modify the hard mismatches by taking into account sequencing or other errors. But in the first example I get more discordant sites (column [4]) than total sites compared (column [6]) for geno2.  As I understand it, that cannot be.  7.27e+05 = 727.000. If numbers were lower by a factor of 10 it would make more sense.

I might get wrong numbers here because I compare across files and they contain 10 mio. and 0.5. mio. SNPs, respectively and I am only looking at the overlap. Would it make more sense to make a single file with the overlap only and then compare within this ?

**Comment by pd3** [comment]
You have it reversed. With `-e 0` you should get the exact number of discordant sites, which is lower. For example, `2086 < 269011`

**Comment by StefanReuscher** [comment]
Exactly, when I add `-e 0` the results make sense. Exact number of mismatches. I am happy.

It is the first example I dont understand. This would be without `-e`, so defaulting to `-e 40`. Suddenly I have 10 times as many mismatches.

It will take me bit, but I want to retry this comparing within a file and with PL tags present. I usually remove PL from my data.

**Comment by pd3** [comment]
The discordance value is equal to the number of discordant genotypes only with `-e 0`. Otherwise it is just a score of a sort, with a vague probabilistic meaning. In that case it should not, and cannot, be interpreted as the number of discordant genotypes.

**Comment by StefanReuscher** [comment]
Ahh, that makes more sense. As I said, I compare two very unequal sets here, I can understand if numbers become very large or small. I will restrict myself to `-e 0`  which is informative enough and close the issue.

You had at least 4 bioinfomaticians at the company puzzled with this. Maybe consider writing a warning in the documentation or the tool itself.

Also thank you for bcftools. Most of the times it works like a charm for anything bcf related !
