### ISSUE TITLE
bcftools csq bitmask error

### ISSUE THREAD

**Issue by MWendorff** [samtools/bcftools#1539]
Hi again,

I am sorry but as we are currently running bcftools on a huge file we are facing a lot of rare errors currently.

This time it is about a multiallelic mutation, where the bitmask for the second alternativ mutation is pointing to ALL consequences.

The part from the csq:
3       10285845        3_10285845_TAGAG_T;3_10285845_TAGAGAG_T TAGAGAG TAG,T   715     PASS    AC=1,1;AF=7.588e-05,2.529e-05;AN=4;AQ=460,715;QD=8.51;BCSQ=stop_lost&frameshift|GHRL|ENST00000422159|protein_coding|-|91L*>91K|10285845TAGAGAG>TAG,stop_lost&frameshift|GHRL|ENST00000446937|protein_coding|-|40L*>40K|10285845TAGAGAG>TAG,3_prime_utr|GHRL|ENST00000335542|protein_coding,3_prime_utr|GHRL|ENST00000430179|protein_coding,3_prime_utr|GHRL|ENST00000449238|protein_coding,3_prime_utr|GHRL|ENST00000437422|protein_coding,3_prime_utr|GHRL|ENST00000287656|protein_coding,3_prime_utr|GHRL|ENST00000457360|protein_coding,3_prime_utr|GHRL|ENST00000439975|protein_coding,3_prime_utr|GHRL|ENST00000429122|protein_coding,inframe_deletion&stop_retained|GHRL|ENST00000422159|protein_coding|-|90SL*>90*|10285845TAGAGAG>T,inframe_deletion&stop_retained|GHRL|ENST00000446937|protein_coding|-|39SL*>39*|10285845TAGAGAG>T    GT:AB:AD:DP:FT:GQ:RNC:SBPV:BCSQ 0/1:0.444444:8,10,0:18:PASS:99:..:0.2312,.:699050       0/2:0.516129:16,0,15:31:PASS:99:..:0.446,.:11184810

The TBCSQ output: bcftools query -f '[%GT %BCSQ %TBCSQ\n]' tmp/subset_csqProblem3_csq.bcf.gz 

0/1 699050 .    stop_lost&frameshift|GHRL|ENST00000422159|protein_coding|-|91L*>91K|10285845TAGAGAG>TAG,stop_lost&frameshift|GHRL|ENST00000446937|protein_coding|-|40L*>40K|10285845TAGAGAG>TAG,3_prime_utr|GHRL|ENST00000335542|protein_coding,3_prime_utr|GHRL|ENST00000430179|protein_coding,3_prime_utr|GHRL|ENST00000449238|protein_coding,3_prime_utr|GHRL|ENST00000437422|protein_coding,3_prime_utr|GHRL|ENST00000287656|protein_coding,3_prime_utr|GHRL|ENST00000457360|protein_coding,3_prime_utr|GHRL|ENST00000439975|protein_coding,3_prime_utr|GHRL|ENST00000429122|protein_coding
0/2 11184810 .  stop_lost&frameshift|GHRL|**ENST00000422159**|protein_coding|-|91L*>91K|10285845TAGAGAG>TAG,stop_lost&frameshift|GHRL|ENST00000446937|protein_coding|-|40L*>40K|10285845TAGAGAG>TAG,3_prime_utr|GHRL|ENST00000335542|protein_coding,3_prime_utr|GHRL|ENST00000430179|protein_coding,3_prime_utr|GHRL|ENST00000449238|protein_coding,3_prime_utr|GHRL|ENST00000437422|protein_coding,3_prime_utr|GHRL|ENST00000287656|protein_coding,3_prime_utr|GHRL|ENST00000457360|protein_coding,3_prime_utr|GHRL|ENST00000439975|protein_coding,3_prime_utr|GHRL|ENST00000429122|protein_coding,inframe_deletion&stop_retained|GHRL|**ENST00000422159**|protein_coding|-|90SL*>90*|10285845TAGAGAG>T,inframe_deletion&stop_retained|GHRL|ENST00000446937|protein_coding|-|39SL*>39*|10285845TAGAGAG>T

I tried it with version:
bcftools 1.13-3-g89a566b
Using htslib 1.13-3-gd16bed5

I attach a small bcf file containing the two mutations (without consequences).
It would be great if you could solve this issue.

Best
Mareike
[subset_csqProblem3.bcf.gz](https://github.com/samtools/bcftools/files/6900594/subset_csqProblem3.bcf.gz)

**Comment by MWendorff** [comment]
I used:

bcftools csq -p a --ncsq 128 -f Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -O b -o subset_csqProblem3_csq.bcf.gz -g Homo_sapiens.GRCh38.100.gff3.gz subset_csqProblem3.bcf.gz

The gff file is from http://ftp.ensembl.org/pub/release-100/gff3/homo_sapiens/

**Comment by pd3** [comment]
Thank you for the bug report! I believe this is now fixed by 0522cc3, please try it out and let me know if you spot any problems.

**Comment by MWendorff** [comment]
Thanks a lot. It is working now.
