### ISSUE TITLE
bug in "annotate" when there are multiple "ALT" variants

### ISSUE THREAD

**Issue by silvia-s** [samtools/bcftools#154]
Hi there,
I noticed a bug in the "annotate" function, which I was using to include information from a .vcf file to another one. In particular, when there are two variants in the field "ALT", of which only one has a corresponding value in the new field that I want to add from another .vcf file, that value is reported but it is not possible to figure out which of the two alterations does it correspond to.
I would propose instead of writing only one value (e.g. ";NEWFIELD=10") to write a "." for the missing one and to separate the values by "," such that the order would help the user. For instance:

#CHROM  POS  ID  REF  ALT  (...)  INFO
1  10060  .  C  A,T (...)  NEWFIELD=.,10;

Could anyone please fix that? Thank you in advance!

**Comment by pd3** [comment]
This is now resolved by a4ff92eb, thanks.
