### ISSUE TITLE
`bcftools norm` combines multi-allelics in an inconsistent manner

### ISSUE THREAD

**Issue by hjeremyli** [samtools/bcftools#1542]
Hello, I observed that `bcftools` can combine multi-allelics in an incorrect manner in the `-m +any` mode. 

Here is a starting set of genotypes for a single individual at a site with five alternate alleles:

```
chr1	242241910	rs887894000	T	C	.	LOWCONF	.	GT:RC:AC:GP:DS	0/1:0:0:0.463513,0.50543,0.031057:0.567544
chr1	242241910	rs1210639780	T	TAC	.	LOWCONF	.	GT:RC:AC:GP:DS	0/0:0:0:0.67587,0.293959,0.0301705:0.3543
chr1	242241910	rs1210639780	T	TATAC	.	LOWCONF	.	GT:RC:AC:GP:DS	0/1:0:0:0.368407,0.499557,0.132036:0.763629
chr1	242241910	rs1210639780	T	TATATAC	.	LOWCONF	.	GT:RC:AC:GP:DS	0/0:0:0:0.819853,0.174856,0.00529109:0.185438
chr1	242241910	rs1210639780	T	TATATATAC	.	PASS	.	GT:RC:AC:GP:DS	0/0:0:0:0.913965,0.0847229,0.00131162:0.0873462
```

To my eye, this should be interpreted as a genotype of `TATAC` on one haplotype and `C` on the other haplotype. Running `bcftools norm -m both` yields combined records consistent with this interpretation:

```
chr1	242241910	rs887894000	T	C	.	LOWCONF	.	GT:RC:AC:GP:DS	0/1:0:0:0.463513,0.50543,0.031057:0.567544
chr1	242241910	rs1210639780	T	TAC,TATAC,TATATAC,TATATATAC	.	LOWCONF	.	GT:RC:AC:GP:DS	0/2:0:0:0.913965,0.293959,0.0301705,0.499557,.,0.132036,0.174856,.,.,0.00529109,0.0847229,.,.,.,0.00131162:0.3543
```

but running `bcftools norm -m +any` yields the following, 

```
chr1	242241910	rs887894000;rs1210639780	T	C,TAC,TATAC,TATATAC,TATATATAC	.	LOWCONF	.	GT:RC:AC:GP:DS	0/3:0:0:0.913965,0.50543,0.031057,0.293959,.,0.0301705,0.499557,.,.,0.132036,0.174856,.,.,.,0.00529109,0.0847229,.,.,.,.,0.00131162:0.567544
```

which indicates that the genotype at that site is `0/3`, or `T` on one haplotype and `TATAC` on the other haplotype, which is inconsistent with the other two representations above. This would seem to be a bug. 

I am using `bcftools` version `1.12-57-g0c2765b`. Any advice here would be greatly appreciated.

**Comment by hjeremyli** [comment]
Wondering if you have any feedback here @pd3

**Comment by pd3** [comment]
This is now fixed. Thanks for the bug report.

**Comment by hjeremyli** [comment]
Thanks!
