### ISSUE TITLE
plot-vcfstats error

### ISSUE THREAD

**Issue by ketkijoshi278** [samtools/bcftools#1543]
Hello,
I use the following command.
 bcftools stats chr1.vcf.gz > test.vchk
followed by 
plot-vcfstats -p outdir test.vchk
But its showing error.
the error:
Parsing bcftools stats output: test.vchk
Plotting graphs: python plot.py
Traceback (most recent call last):
  File "plot.py", line 53, in <module>
    import matplotlib as mpl
ModuleNotFoundError: No module named 'matplotlib'
The command exited with non-zero status 256:
        python plot.py

 at /home/kxj190026/anaconda3/envs/chip-seq/bin/plot-vcfstats line 99.
        main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /home/anaconda3/envs/chip-seq/bin/plot-vcfstats line 287
        main::plot(HASH(0x55a9a5d69e80)) called at /home/anaconda3/envs/chip-seq/bin/plot-vcfstats line 69
Can anyone please help me out with this?
Thank You.

**Comment by pd3** [comment]
You need to have matplotlib installed (http://matplotlib.org), this is what the script uses for plotting graphs
