### ISSUE TITLE
plot-vcfstats

### ISSUE THREAD

**Issue by ketkijoshi278** [samtools/bcftools#1544]
Hello everyone,
Can anyone tell me how to use plot-vcfstats for many input files.
I have vcf files for chr1 to chr22. I have generated test.vchk file for each chr using bcftools stats chr1.vcf > test.vchk command
I now want to use plot-vcfstats for all of these files so that i can get a one graph  for all the chromosomes.
Can anyone please help me out with this?

**Comment by pd3** [comment]
```
plot-vcfstats -m file1.vchk file2.vchk ... > merged.vchk
plot-vcfstats  -p outdir merged.vchk
```
