### ISSUE TITLE
How can I change variant positions in a VCF file?

### ISSUE THREAD

**Issue by arouna4** [samtools/bcftools#1545]
Hello,

I would like to update the variant position in my VCF file.
I used bcftools annotate with the command :
- **_`bcftools annotate -a Map.txt -h Map.hdr -c CHROM,POS Variants.vcf`_**
by providing the new position (POS) to the **Map.txt file**.
in the **Map.hdr**, I provide the name of the header of the two columns which are  CHROM	POS.

but I got an error message: **Could not parse Mappe3.hdr: CHROM	POS**

Please, could anyone tell me what I am doing wrong and how to apply the right setting in order succesfully to change the position?

Sincerely,

**Comment by pd3** [comment]
This is now possible using
```
bcftools annotate -c CHROM,POS,~POS
```
where the first column is the original position and the second is the new position.
