### ISSUE TITLE
roh documentation and support for run-roh.pl to run without allele frequency file

### ISSUE THREAD

**Issue by FatihSarigol** [samtools/bcftools#1549]
Hi,

Is `roh` supposed to calculate an RG line for every time there is a heterozygous SNP (passing thresholds) breaking the run of homozygosity? It doesn't do that for me. When I looked this up online, I saw some posts asking similar question because it is not clear in the how-to: 
https://samtools.github.io/bcftools/howtos/roh-calling.html

Other thing is about `run-roh.pl` which does not run without allele frequency file, while normal `roh` can. Is there a way to make it run too? It has an option `--roh-args` using which I tried to incorporate the `--AF-dflt 0.4` flag but nothing worked. 

Thanks

**Comment by pd3** [comment]
The program is attempting to do something more sophisticated and runs a probabilistic HMM model described in the manual page http://samtools.github.io/bcftools/bcftools.html#roh. In other words, a single heterozygous variant does not necessarily have to break an roh region.

You are correct that the script does not allow to run without the allele frequency file. The script is short and is just a front-end to `bcftools roh`, you can always run the commands manually.

**Comment by FatihSarigol** [comment]
thanks!
