### ISSUE TITLE
improving the way new fields are added to the "INFO" column

### ISSUE THREAD

**Issue by silvia-s** [samtools/bcftools#155]
Hi there,
Would it be possible to set a new name for a field when importing the information from a .vcf file to another one with the "annotate" function? I mean, if I want to insert for instance the new field "TC" into "INFO" but there is already a "TC" field in the receiving file, I would have two options: over-write it or append it.
Why not including a feature that would let me decide a new name for the field that has to be imported? For example, instead of writing in the options "-c INFO/TC", it would be helpful something like "-c INFO/TC=INFO/NEWNAME" or "-c INFO/TC_as_INFO/NEWNAME".
Thank you for your help!

**Comment by jmarshall** [comment]
Related to a desire for flexible filtering in #118.
