### ISSUE TITLE
bcftools stats comparing two bcf files

### ISSUE THREAD

**Issue by wbsimey** [samtools/bcftools#1550]
I know this is not an issue with bcftool, but about my inability to figure out how to uses 'stats'. If this is the wrong venue to post, where should I go for help? Thanks.

Hello, I am trying to follow the bcftools documentation for 'bcftools stats' to compare the intersection and the complements between two or more bcf files.

FROM Man page:
bcftools stats [OPTIONS] A.vcf.gz [B.vcf.gz]

I have tried many combinations of listed options but I cannot generate a stats file. There are no examples to follow for this kind of analysis.

The following are a few combination that I have tried:

bcftools stats -S Nl_Nb_n96_1-pop_HW_noG_flt_QUAL20-DP12.bcf Nl_Nb_n96_2pops_HW_flt_QUAL20-DP12.bcf
bcftools stats -S Nl_Nb_n96_1-pop_HW_noG_flt_QUAL20-DP12.bcf Nl_Nb_n96_2pops_HW_flt_QUAL20-DP12.bcf -o stats_file.stats
bcftools stats -s sample_list_stats-txt
bcftools stats Nl_Nb_n96_1-pop_HW_noG_flt_QUAL20-DP12.bcf Nl_Nb_n96_2pops_HW_flt_QUAL20-DP12.bcf
bcftools stats -S sample_list_stats-txt
bcftools stats -s Nl_Nb_n96_1-pop_HW_noG_flt_QUAL20-DP12.bcf Nl_Nb_n96_2pops_HW_flt_QUAL20-DP12.bcf
bcftools stats -S Nl_Nb_n96_1-pop_HW_noG_flt_QUAL20-DP12.bcf Nl_Nb_n96_2pops_HW_flt_QUAL20-DP12.bcf > 2pop_v_1pop_stats.stats

I. ultimately, would like to generate venn diagrams of the overlap of many bcftools mpileup runs.
Thanks in advance.

**Comment by pd3** [comment]
Best is probably to use first `bcftools isec` to generate the sets, then run `bcftools stats` individually on each.
