### ISSUE TITLE
Error in installation in macOS: clang: error: no input files

### ISSUE THREAD

**Issue by edfajardo** [samtools/bcftools#1554]
For some reason, during installation of either samtools (samtools-1.13) or bcftools (bcftools-1.13), the config.mk file has errors when defining the LDFLAGS and CPPFLAGS variables in macOS (10.14.6 Mojave).  In both cases, a semicolon is added at the end of the path.  When you look at the messages sent to the STDOUT during ./configure, the relevant faulty line reads in my system:

./configure
### relevant line in the messages sent to STDOUT:
configure: running /bin/sh ./configure --disable-option-checking 'LDFLAGS=-L/usr/local/opt/openssl@1.1/lib;' 'CPPFLAGS=-I/usr/local/opt/openssl@1.1/include;' --cache-file=/dev/null --srcdir=.

As a result, the *make* step that follows throws an error that reads something like this:

gcc -Wall -g -O2 -fvisibility=hidden -I. -I/usr/local/opt/openssl@1.1/include; -c -o kfunc.o kfunc.c
clang: error: no input files
/bin/sh: -c: command not found

What is happening is that the call to gcc ends at the (incorrectly written) semicolon, thus it finds no files to compile and issues the clang error: no input files.  Then it attempts to execute what it thinks is the next instruction: -c -o kfunc.o kfunc.c.  Obviously, this last instruction makes no sense to the shell, which complains saying -c: command not found and ending the process. 

Examination of the config.mk file shows that, indeed, the CPPFLAGS and LDFLAGS variables have a semicolon at the end.  

To bypass the problem, you can re-run the configure step but now giving the values of CPPFLAGS and LDFLAGS as inputs (the values are taken from the ./configure messages on the screen so you would have to initially run ./configure with no inputs to get the correct path):

./configure LDFLAGS=-L/usr/local/opt/openssl@1.1/lib CPPFLAGS=-I/usr/local/opt/openssl@1.1/include

This solves the problem.  Now make (and make install) will complete successfully.  

Of course, this is a workaround but a more permanent solution is to correct the relevant piece of code in the *configure* script so that people can install in a mac in a straightforward manner (I attempted to fix it but it is a large file and I could not find the rogue line).
 
As mentioned above, I had this problem when installing on a mac running Mojave 10.14.6.  Installing on a Linux machine running CentOS 7.9 completed without a hitch.

**Comment by jmarshall** [comment]
Check for rogue `$CPPFLAGS` and `$LDFLAGS` variables in your environment, e.g., with `env|grep FLAGS` (or with `set` in place of `env`, but _configure_ shouldn't be picking up these values if they are not exported).

Note that for htslib/samtools/bcftools, openssl is not needed on macOS. So there is no need to point the build processes for these packages at your brewed installation of openssl.

**Comment by pd3** [comment]
I believe this is now solved? Closing the issue.
