### ISSUE TITLE
bcftools mpileup failed to detect a multi-allelic SNP in target sequencing 

### ISSUE THREAD

**Issue by kinfoon** [samtools/bcftools#1555]
Hi, everyone. We encountered a problem when using bcftools mpileup to detect a multi-allelic SNP in target sequencing.  We used igv and visually confirmed the existence of multiple alleles and sequencing depth over 1000X at the same chromosomal position. The fractions of different alleles were higher than 10%. The pipeline of data processing was as follows:
1. Clean FASTQ was aligned to human hg38 genome sequence using BWA.
2. Optical duplication and multiple-mapped reads were remove using the lastest version of samtools. 
3. Base qualities were recalibrated using GATK 4.1.3.
4. SNV was then called using bcftools mpileup and call. 

I'm confused why this happened, as our analysis pipeline was expected to detect somatic mutations, but our target sequencing with alternative frequency higher than 10% failed to be detected. 

We tried to lower the filter cutoff of base quality and reads of alternative alleles, but had no success. 

Could anyone help with this matter? Please tell me how I can upload the FASTQ data to provide further information?

Thank you!

**Comment by pd3** [comment]
Upload somewhere a slice of the BAM file and the reference (if non-human) and provide the commands to reproduce the problem, including the version of bcftools you are running and the position of the variant you are expecting to see.

**Comment by kinfoon** [comment]
Hi, Petr,

Thanks for reply! 

Our data have been uploaded to pcloud:
https://u.pcloud.link/publink/show?code=kZICWKXZNm9CHAnaHwbK1WYEgTmWCBSUckbV#folder=10247947147&tpl=publicfoldergrid

bcftools mpileup  -r chr20:32761954-32761954 -Ou -f /home/genome/databank/GATK/hg38/Homo_sapiens_assembly38.fasta NovaS01009-UKXR214075JX-21422001-A288V1hg38-PM2-0A-PM1-21R31250/aligned_uniqmapped_sorted_TargetSeq.bam | bcftools call -mv -Ob -o out.bcf

IGV confirmed that the position has four different alleles. 

Thanks!

**Comment by pd3** [comment]
The caller can work with diploid genomes only. If you expect more than two alleles in sample, you can use `mpileup` to generate a raw VCF output without genotypes and then process it using a custom script. Alternatively, you can add the `-A` option to preserve all alleles in the output (but the genotypes and genotypes likelihoods will be always at most diploid):
```
bcftools mpileup  -a AD -r chr20:32761954-32761954 -Ou -f $ref8 $bam | bcftools call -mvA
```
In the command I also added the `-a AD` option to output also the counts for each allele.
