### ISSUE TITLE
bcftools call -C alleles -  issue: Fixme? Cannot constrain to 1-th allele

### ISSUE THREAD

**Issue by gabeng** [samtools/bcftools#1557]
I am trying to genotype samples at given sites, but run into an issue with `bcftools 1.13`. 
My command is:
```
bcftools mpileup -O u -f GRCh37.fa -R regions.bed input.bam | \
  bcftools call -A -O v -C alleles -m -i -T als.tsv.gz > problematic-variant.vcf
```
The output of which is:
```
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
Fixme? Cannot constrain to 1-th allele (CT). VCF=C,T,G,A        TAB=C,CT
```
And the resulting `problematic-variant.vcf` is empty. 

My `als.tsv.gz` looks like this:
```
5       55662540        C,CT
```
`bcftools mpileup` outputs at this position:
```
5       55662540        .       C       T,G,A   0       .       DP=278;I16=119,...
```

Is there any way to create a VCF that contains a call for the indel from `als.tsv.gz`?

**Comment by pd3** [comment]
Thanks for the bug report! With the latest github version this should now work. Please try it out and let me know in case of problems.

**Comment by gabeng** [comment]
Thank you for the quick fix! I just confirmed on my side that the issue is resolved.
