### ISSUE TITLE
bcftools +contrast segfaults if -0/--control-samples or -1/--case-samples option is missing

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1562]
```
$ echo -e  "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO" | bcftools +contrast
Segmentation fault (core dumped)
```

As there is no check for the presence of mandatory options `-0/--control-samples` and `-1/--case-samples`, the binary crashes when it hits:
```
        str_list = hts_readlist(str, is_file, &nlist);
```
And `str` is still set as a `NULL` pointer if either `-0/--control-samples` or `-1/--case-samples` is missing.

**Comment by pd3** [comment]
Thanks for the bug report, this is now fixed.
