### ISSUE TITLE
bcftools -S stats generates wrong nRefHom/nNonRefHom counts

### ISSUE THREAD

**Issue by superbsky** [samtools/bcftools#1564]
I have two samples in one VCF file but receiving different nRefHom/nNonRefHom PSC counts when I run `bcftools -S stats` specifying one or two samples in `-S` parameter.

**One:**
PSC	[2]id	[3]sample	[4]nRefHom	[5]nNonRefHom	[6]nHets	[7]nTransitions	[8]nTransversions	[9]nIndels	[10]average depth	[11]nSingletons	[12]nHapRef	[13]nHapAlt[14]nMissing
PSC	0	first1_g6-b4-s1	**1779872	0**	431375	337937	93438	0	0.0	431375	0	0	2206

**Two:**
PSC	[2]id	[3]sample	[4]nRefHom	[5]nNonRefHom	[6]nHets	[7]nTransitions	[8]nTransversions	[9]nIndels	[10]average depth	[11]nSingletons	[12]nHapRef	[13]nHapAlt[14]nMissing
PSC	0	first1_g5-b1-s1	1733853	39739	437727	373683	103783	0	0.0	317429	0	0	2134
PSC	0	first1_g6-b4-s1	**1738627	41245**	431375	370160	102460	0	0.0	312583	0	0	2206

The difference between nRefHom suggests that nNonRefHom sites count for this column instead. I am not familiar with the C programming language and could not figure out how exactly these columns are calculated. Is there a chance that in the case of two samples, reference sites are calculated differently?

**Comment by pd3** [comment]
That shouldn't be the case. Can you show the exact commands that you are using and check if you are getting these results also with the latest version of bcftools? A test case to reproduce the problem would be very helpful.

**Comment by superbsky** [comment]
bcftools --version
bcftools 1.13
Using htslib 1.13
Copyright (C) 2021 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[merged_lifted_id.vcf.gz](https://github.com/samtools/bcftools/files/7041116/merged_lifted_id.vcf.gz)
[one.vcf.gz](https://github.com/samtools/bcftools/files/7041119/one.vcf.gz)
[two.vcf.gz](https://github.com/samtools/bcftools/files/7041120/two.vcf.gz)

bcftools view -s first1_g6-b4-s1 -Oz two.vcf.gz > one.vcf.gz

bcftools stats -s first1_g6-b4-s1,first1_g5-b1-s1 two.vcf.gz | grep ^PSC
PSC	0	first1_g6-b4-s1	**1738627	41245**	431375	370160	102460	0	0.0	312583	0	0	2206
PSC	0	first1_g5-b1-s1	1733853	39739	437727	373683	103783	0	0.0	317429	0	0	2134

bcftools stats -s first1_g6-b4-s1 one.vcf.gz | grep ^PSC
PSC	0	first1_g6-b4-s1	**1738627	41245**	431375	370160	102460	0	0.0	472620	0	0	2206

but the same single sample from the same upstream processing produces:

bcftools stats -s first1_g6-b4-s1 vcf/merged_lifted.vcf.gz | grep ^PSC
PSC	0	first1_g6-b4-s1	**1779872	0**	431375	337937	93438	0	0.0	431375	0	0	2206

I am not sure what the difference is because I see it only for the FORMAT column.

**Comment by superbsky** [comment]
Sorry I think that it is our upstream analysis issue and bcftools performs correctly on the current data.
