### ISSUE TITLE
gVCF output

### ISSUE THREAD

**Issue by wbsimey** [samtools/bcftools#1571]
Hello, I would like to use some of the GATK4 BQSR tools with my bcftools mpileup/call output to generate a denovo "know-sites" file. I see that both `mpileup` and `call` have a `-g` option for adding "gVCF blocks of homozygous REF calls". The `-O` option ( b|u|z|v) does not include a gVCF option. Would the output of a mpileup | call analysis produce a GATK4 compatible gVCF file?

For e.g., would the following produce a .gVCF formatted output?
`bcftools mpileup -Ou -g -B -C 50 -a QS -a AD -a DP -R Chr_list.txt --threads 64 -f Draft3_ref.fasta *.bam 2>logs/mpileup_call-R_list_2pops_HW_output_090521.log | bcftools call -mv -g -G pop_map.txt -Oz -a GQ --threads 64 -o Neo96-2pops_HW-a_QS_AD_DP_GQ.gVCF 2>>mpileup_call-r_list_2pops_HW_output_090521.log`

Alternatively, are there bcftools pipelines to generate denovo "know-sites" lists?

**Comment by pd3** [comment]
The `-O` option only controls the way VCF is stored, not the VCF itself. 

The `mpileup -g` indeed produces a gVCF file, but it expects a list of numeric values which are interpreted as the minimum DP per gVCF block. Alternatively, there is the `bcftools +gvcfz` plugin that allows to create gVCF blocks using other criteria.

And is the output GATK4 compatible? I don't know what GATK requires, but the output conforms to VCF specification, so I would expect the answer is yes.

**Comment by wbsimey** [comment]
Thank you pd3! I will report back on the `+gvcfz` plugin and the `-g` option.  Should I use the `-g` option for both `mpileup `and `call`? Or just `mpileup`?

**Comment by pd3** [comment]
Ah, right, above I just wanted to point out that `-g` needs arguments. As for where it is needed: both `mpileup -g` and `call -g` can be given, but just `call -g` is sufficient. If `-g` is used only with `mpileup`, then one can get different gVCF blocks, unless `call -A` is given, due to presence of uncalled alleles in the pileup.
