### ISSUE TITLE
after latest pull, make install fails

### ISSUE THREAD

**Issue by comatosejones** [samtools/bcftools#1573]
vcfstats.c: In function ‘main_vcfstats’:
vcfstats.c:1888:36: error: ‘BCF_SR_TARGETS_OVERLAP’ undeclared (first use in this function)
 1888 |         bcf_sr_set_opt(args->files,BCF_SR_TARGETS_OVERLAP,targets_overlap);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~
vcfstats.c:1888:36: note: each undeclared identifier is reported only once for each function it appears in
vcfstats.c:1894:36: error: ‘BCF_SR_REGIONS_OVERLAP’ undeclared (first use in this function)
 1894 |         bcf_sr_set_opt(args->files,BCF_SR_REGIONS_OVERLAP,regions_overlap);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:137: vcfstats.o] Error 1

**Comment by pd3** [comment]
The latest commits in bcftools/develop require this pull request to be merged in htslib https://github.com/samtools/htslib/pull/1327, which should happen very soon.

**Comment by erikbgithub** [comment]
@pd3 Hi. How can I increase the likelihood for a stable build for my scripted system installation? Does it work (most of the time) if I always checkout `master` before building? It seems like `develop` is the default branch when I clone, right?

**Comment by pd3** [comment]
It is very rare for bcftools develop to be out of sync of htslib develop. If you grab the latest github version now, it works again.

**Comment by erikbgithub** [comment]
Appreciating the idea and the care you guys put into keeping everything in sync. I don't want to be a pressure point for people who basically provide software development work for free to me, though. So I would be more at peace, if I can use a more stable branch (like the standard release branch) or tag (like `latest`) for my automated tooling.

**Comment by pd3** [comment]
If you want to be sure that they are in sync, then the `master` branch is safe to use.
I'll close the issue as it should be resolved now.

**Comment by jmarshall** [comment]
The usual way to avoid breakage in this scenario is to make **both** htslib and bcftools changes as pull requests, and only merge the dependent bcftools one after the htslib one has been merged.

See for example samtools/htslib#1325 and samtools/samtools#1485.

**Comment by comatosejones** [comment]
thank you!
