### ISSUE TITLE
Expose compression level in scatter and split plugins

### ISSUE THREAD

**Issue by cwhelan** [samtools/bcftools#1574]
It would be very helpful if the scatter and split plugins could expose a compression level parameter for their output files. 

This can have a pretty big impact on run time -- in a test on a very large gzipped VCF, I was able to get a ~30% reduction in runtime (133 minutes vs 185 minutes) for a scatter task by replacing `bcftools +scatter -O z` with a simple cyvcf2 script that set compression level 3 on the output files.

For other tools you can pipe uncompressed output to `bcftools view` to change the compression level but there's no way to do this for `+scatter` and `+split`, which are creating multiple file outputs.

**Comment by pd3** [comment]
This is now possible with all bcftools commands and plugins that support the `-O, --output-type` option, The compression level of the compressed formats ('b' and 'z') can be set by appending a number between 0-9, e.g.
```
-O b3
```

To optimize further, if the output format does not have to be a VCF.gz but can be a BCF, the latter should also be more efficient.

I hope this helps

**Comment by cwhelan** [comment]
That's awesome, thanks for the quick turnaround!

**Comment by pd3** [comment]
Declared as such now, thanks 863ec47
