### ISSUE TITLE
bcftools error

### ISSUE THREAD

**Issue by ketkijoshi278** [samtools/bcftools#1575]
Hello,
I am trying to run bcftools But its showing error for me.
The command use:
bcftools annotate -x ID,INFO/DP,FORMAT/DP /work2/08259/kjoshi/stampede2/files/*.vcf
[E::bcf_hdr_parse] Could not parse the header, sample line not found
Segmentation fault
I checked the vcf files but they have the sample line:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG00105 HG00107 HG00115 HG00132 HG00145 HG00157 HG00181 HG00308 HG00365 HG00371 HG00379 HG00380 HG01789 HG01790 HG01791 HG02215 NA06985 NA07346 NA11832 NA11840 NA11881 NA11918 NA12005 NA12156 NA12234 NA12760 NA12762 NA12776 NA12813 NA18488 NA19092 NA19141 NA19143 NA19144 NA19153 NA19159 NA19184 NA19201 NA19206 NA19210 NA19214 NA20514 HG00096 HG00097 HG00099 HG00100 HG00101 HG00102 HG00103 HG00104 HG00106 HG00108 HG00109 HG00110 HG00111 HG00112 HG00114 HG00116 HG00117 HG00118 HG00119 HG00120 HG00121 HG00122 HG00123 HG00124 HG00125 HG00126 HG00127
Can anyone help me out with this?
Thank you.

**Comment by pd3** [comment]
Most likely some of the fields are not tab-delimited? The error message should be improved.
