### ISSUE TITLE
23andme convert to VCF. Could not parse header when comparing the converted VCF files using bcftools

### ISSUE THREAD

**Issue by Susan-Huang830531** [samtools/bcftools#1577]
I tried to compare two sets of data in VCF format using the "bcftools isec -p" command. One data was converted from 23andme format to the VCF format using the samtools and the bcftools:

```
cat hg19.fa | sed 's/>chr/>/g' > hg19.23andme.fa
./samtools faidx hg19.23andme.fa -o hg19.23andme
./bcftools convert -c ID,CHROM,POS,AA --tsv2vcf FILE -f pathway -s newfile -o file1
```

After the conversion, I found that the chromosome columns aren't the same for the two data. So I use cut and paste commands and vi to edit this column. These headers and columns of the two files are now in the same format and order. This is what the header looks like for file1 and file2:

```
#CHROM   POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  GENOTYPE
```

After gzip and indexing these two files, I tried to run the command "bcftools isec -p". But it gives the error message:

```
[W::bcf_hdr_parse] Could not parse header line: "#CHROM\t POS\t ID\t REF\t ALT\t QUAL\t FILTER\t INFO\t FORMAT\t GENOTYPE\t"
[E::bcf_hdr_parse] Could not parse the header, sample line not found
Failed to open file1: could not parse header
```

**Comment by pd3** [comment]
This seems to be the same problem as in https://github.com/samtools/bcftools/issues/1575. Most likely the line is not separated by tabs but contains spaces.

There is a pull request in htslib https://github.com/samtools/htslib/pull/1328 ready to be merged which should give a more informative error message in future.
