### ISSUE TITLE
bcftools can't filter Condel score in VCF file

### ISSUE THREAD

**Issue by lmanchon** [samtools/bcftools#1579]
see attachment (it's a little gzipped vcf)

bcftools failed with:
bcftools filter -e 'INFO/Condel<0.49' SNVs_only_gnomad_VEP-annotated.vcf.gz
[filter.c:2278 filters_init1] Error: the tag "Condel" is not defined in the VCF header

[SNVs_only_gnomad_VEP-annotated.vcf.gz](https://github.com/samtools/bcftools/files/7183803/SNVs_only_gnomad_VEP-annotated.vcf.gz)

**Comment by pd3** [comment]
The program complains that the annotation is not defined in the header, what is unclear?

For your specific case, check this https://samtools.github.io/bcftools/howtos/plugin.split-vep.html

**Comment by lmanchon** [comment]
ok, I didn't know this plugin, thank you.
