### ISSUE TITLE
trio-dnm plugin - what does the confidence score mean?

### ISSUE THREAD

**Issue by kittysher** [samtools/bcftools#1583]
Hi. I am calling de novo mutations on my vcfs using the trio-dnm plugin, and can't find any more information about the DNM format column in the output file. All I can see in the header is "De-novo mutation score, bigger values = bigger confidence". I then see in the software description:
```
# Same as above plus extract a list of significant DNMs using the bcftools/query command
   bcftools +trio-dnm -P file.ped file.bcf -Ou | bcftools query -i'DNM>10' -f'[%CHROM:%POS %SAMPLE %DNM\n]'
```
What does "significant" in this context mean? Is 10 always the value to filter for? 

Many thanks for your help,
Kitty

**Comment by pd3** [comment]
The value of 10 is just an example, the problem of filtering is a complex one. 
Note that `trio-dnm` is deprecated, please use `trio-dnm2` in the latest release instead. In that new version you can start with filtering events with score above -10 or -8 (in log space).
