### ISSUE TITLE
Feature Request: bcftools annotate + Minimum overlap required as a fraction of the database/variant

### ISSUE THREAD

**Issue by lindenb** [samtools/bcftools#1588]
Hi all,

unless I'm wrong there is no option in `bcftools annotate` to specify the "**Minimum overlap** required as a fraction of the annotation database" or the "Minimum overlap required as a fraction of the variant" , just like `bedtools intersect` https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html

Those options would be useful when using a VCF containing CNV/structural variants and we want to annotate them with a database of known CNVs: a simple overlap is not enough to peek the annotation. e.g: a small deletion and a very large CNV are not the same variation.

I would be happy to implement this, but it's not clear to me where the test should be applied in a vcfannotate.c

P.

**Comment by pd3** [comment]
This is now supported via the option `--min-overlap`

**Comment by lindenb** [comment]
@pd3  thank you so much !
