### ISSUE TITLE
AND logic for mpileup --rf / --ff? 

### ISSUE THREAD

**Issue by gevro** [samtools/bcftools#1599]
Hi,
There is no documentation of how to do the above. And it also seems to give different results if you set --ff multiple times or try --ff Flag1,Flag2. I think this is a bug.

**Comment by pd3** [comment]
The support for the filtering was now added, see the new mpileup read filtering options
```
    --ls, --skip-all-set    ..  skip reads with all of the FLAG bits set
    --ns, --skip-any-set    ..  skip reads with any of the FLAG bits set
    --lu, --skip-all-unset  ..  skip reads with all of the FLAG bits unset
    --nu, --skip-any-unset  ..  skip reads with any of the FLAG bits unset
```

These existing synonymous options continue to function but their use is discouraged
```
    --rf, --incl-flags STR|INT  Required flags: skip reads with mask bits unset
    --ff, --excl-flags STR|INT  Filter flags: skip reads with mask bits set
```

**Comment by gevro** [comment]
Thank you! When will this be put in a new release and added to the manual?

Also, how is it used exactly? Do you specify multiple flag separated by commas or do you put them all as one summed number?

**Comment by pd3** [comment]
I don't know when the next versioned release will happen, not too long hopefully. In the meantime you can install the program from source as described here http://samtools.github.io/bcftools/howtos/install.html.

Each option can be given only once, multiple comma-separated string flags or one integer can be given.
