### ISSUE TITLE
cram files for bcftools mpileup + call

### ISSUE THREAD

**Issue by dtzhu337** [samtools/bcftools#1602]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
samtools 1.9

 #### Please describe your environment.
Linux 2.6.32-696.16.1.el6.x86_64

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I got a set of cram files as the results of exome sequencing. 
Then all the cram files were performed joint calling, and the whole genome was divided into several fragments as well, using the code as the following. 
$ bcftools mpileup -Ou -I -f ./hg38_v0_Homo_sapiens_assembly38.fasta -r {region} -b ./{path/to/cram/file/list}| bcftools call -vmO z -o ./out/path/region.vcf.gz

Then the vcf.gz was piped into plink to create plink binary files. However, when I did the missingness in plink, the results showed high missingness among all the samples. The missingness (of variants) for samples is around ~60%. The overall genotyping rate is ~0.33

The cram files were generated from exome array, and the average genotyping rate should be above 98%. Since cram files don't contain the reference file, I was just wondering if the bcftools call didn't call the variant if the site stays the same with the reference genome, thus causing the high missingness among the samples. 

Any ideas to check this issue or is it something I can fix with the modification of the code?

Thank you

**Comment by dtzhu337** [comment]
Hi jkbonfield,

Thank you very much for the information. I should reply sooner back to you. I just did a small test on only 20 samples, but the genotyping rate was still low, ~ 40%. I have updated to the latest version, 1.14. So I think that's the information our data carry. Thank you.


> Firstly bcftools 1.9 is pretty old. Please upgrade. There have been significant changes to the most recent versions of bcftools mpileup.
> 
> I'm sorry I'm not familier with plink and what "missingness" means. Is this doing comparison to a known truth set and reporting a false negative rate? If so, an example of a specific case which you think should be called and is not would be useful.
> 
> The lack of a reference shouldn't cause a problem. If bcftools cannot decode the CRAM due to a missing reference it will complain. The fact it hasn't presumably means it either doesn't need one (referenceless encoding) or it has fetched it from somewhere.

**Comment by jkbonfield** [comment]
Closing this as if I'm interpreting the reply correctly, it sounds like this is an inherent property of the data and not an issue with software.
