### ISSUE TITLE
Couldn't make consensus sequence from phased haplotype

### ISSUE THREAD

**Issue by Sakurasugar02** [samtools/bcftools#1603]
My research is to reveal the sequence of chemical receptor genes from non-human primates. Now I am stuck in the problem that how to get the sequence from phased haplotype. 
I conducted the Haplotyprcaller by GATK to phase the heterozygous sites. 
java -jar /usr/local/bin/picard.jar CreateSequenceDictionary \
                                                	        R=Mmul_depth.fasta \
                                                	        O=Mmul_depth.dict
      		gatk --java-options "-Xmx4g" HaplotypeCaller -R Mmul_depth.fasta -I Mmul_Mmul_depth_rmd.bam -O hc_Mmul_depth.g.vcf.gz -ERC GVCF

		gatk --java-options "-Xmx4g" GenotypeGVCFs -R Mmul_depth.fasta -V hc_Mmul_depth.g.vcf.gz -O gen_Mmul_depth.vcf.gz

To get the consensus sequence then I used bcftools consensus.
bcftools consensus -H 1pIu gen*.vcf.gz -f ref.fasta > H1_phased.fasta

But I got the results still have the IUPAC code which some sites were phased by Haplotypecaller.
Did I conduct the wrong option? Or is there better tool to phase the haplotype for non-human primates?

**Comment by pd3** [comment]
The title suggests there is some misunderstanding. Are you perhaps confusing "calling" with "phasing"? I am not sure. In any case, I don't think GATK can output phased VCFs. There are algorithms to perform phasing but I am only familiar with methods that require a large panel of phased reference haplotypes (e.g. Eagle2), which is not available in your case.

In this situation what you can do is to make `bcftools consensus` always pick the alternate allele regardless of the phase by providing the `-H A` option.
