### ISSUE TITLE
Renaming Tags in INFO columns 

### ISSUE THREAD

**Issue by shafiqnoa** [samtools/bcftools#1605]
Hi,
I have two data set with non-overlapping samples which I wanted to merge. Before that, I need to carry out post imputation QC. However, in one data set INFO scores were presented as RD2 which does not allow the pipeline to work. I am wondering if there is a way to rename one of the tags in the INFO column but the following command is not working:

bcftools annotate -c INFO/RD2:=INFO/INFO -a 22.vcf.gz -Oz -o 22_anno.vcf.gz

Is there a way to rename tag/s?

**Comment by pd3** [comment]
There is the `--rename-annots` option which allows renaming annotations listed in the file. I just pushed a commit which allows to do that directly on the command line:
```
bcftools annotate -c INFO/NEW:=INFO/OLD input.vcf
```
