### ISSUE TITLE
Merging 9700 gVCFs using bcftools merge -g

### ISSUE THREAD

**Issue by dalmiaa** [samtools/bcftools#1610]
Hi,

I am part of the Genomics England consortium and am working with about 30K patients from the rare diseases wing of the project and am preparing to perform both a kinship analysis and a haplotyping analysis. For ±20K patients, the GEL data consists of genotyping VCFs, but for the remainder ±10K patients, I am attempting to use the genomic VCFs to genotype and merge the 500K SNPs in the Infinium Exome Core 24-v1 genotyping array.

My command is as follows 
`bcftools merge -l gvcf_file_list -R bed_file -g fast_file -o merged.vcf -Ov`

I am expecting a joint VCF with my 500K SNPs and while, so far, the output looks OK [it is still running], I was wondering if this is the best way to go about it or if you advise a different route?

**Comment by pd3** [comment]
The command looks okay to me. Is there some concern in particular you're unsure about?

**Comment by dalmiaa** [comment]
Thanks for the reply, Petr. I was worried about two/three things:
1. How the FT field is concluded to give PASS/other filters since I did not use the -f tag during the merge
2. Is it okay to pipe in Strelka2 VCFs into bcftools
3. How bcftools handles multiple blocks that overlap the same SNP

**Comment by dalmiaa** [comment]
Sorry for not being clear enough. 

I meant in the "FILTER" field in the merged output - how does it decide to "PASS" a site or does it just pipe in everything from the source file and passes it? I would later like to do sample/site level filtering for high genotype quality. 

Thank you for answering the other 2 questions.

**Comment by pd3** [comment]
The merge of FILTER can be controlled using the `-F` option:
```
    -F, --filter-logic x|+            Remove filters if some input is PASS ("x"), or apply all filters ("+") [+]
```

**Comment by pd3** [comment]
This seems resolved, closing the issue. Please reopen if not
