### ISSUE TITLE
getting VAF from vcf file

### ISSUE THREAD

**Issue by elifozcelik** [samtools/bcftools#1612]
Hi, when I tried this command that is posted here: 
bcftools +fill-tags a2_111_30qualityAD_sorted.vcf -- -t VAF

I got this error: Error parsing "--tags VAF": the tag "VAF" is not supported

How do I fix it, thanks.

**Comment by pd3** [comment]
You will probably need to update bcftools, this feature was added in 1.13, now we are on 1.14.
