### ISSUE TITLE
Symbolic alleles not supported when using consensus

### ISSUE THREAD

**Issue by solemnla** [samtools/bcftools#1615]
Hi, when I was using bcftools consensus (bcftools/1.12), I met an error 
```
>chr19:1048895-1049005
Warning: ignoring overlapping variant starting at chr19:1048889
Warning: trimming variant starting at chr19:1049005
Symbolic alleles other than <DEL>, <*> or <NON_REF> are currently not supported, e.g. < at chr19:1049005.
Please use filtering expressions to exclude such sites, for example by running with: -e 'ALT~"<.*>"'
```

It showed that the symbolic allele at chr19:1049005 is not supported. But when I look into the unzipped .g.vcf.gz file, it seems that this position has nothing special.
```
chr19	1048984	.	C	<NON_REF>	.	.	END=1048984	GT:DP:GQ:MIN_DP:PL	0/0:31:52:31:0,52,1177
chr19	1048985	.	C	<NON_REF>	.	.	END=1048985	GT:DP:GQ:MIN_DP:PL	0/0:31:81:31:0,81,1215
chr19	1048986	.	C	<NON_REF>	.	.	END=1048994	GT:DP:GQ:MIN_DP:PL	0/0:31:72:29:0,72,1080
chr19	1048995	.	G	<NON_REF>	.	.	END=1049004	GT:DP:GQ:MIN_DP:PL	0/0:30:60:28:0,60,900
chr19	1049005	.	G	<NON_REF>	.	.	END=1049006	GT:DP:GQ:MIN_DP:PL	0/0:27:51:27:0,51,765
chr19	1049007	.	T	<NON_REF>	.	.	END=1049008	GT:DP:GQ:MIN_DP:PL	0/0:25:39:25:0,39,585
chr19	1049009	.	A	<NON_REF>	.	.	END=1049009	GT:DP:GQ:MIN_DP:PL	0/0:25:42:25:0,42,630
chr19	1049010	.	G	<NON_REF>	.	.	END=1049012	GT:DP:GQ:MIN_DP:PL	0/0:24:45:23:0,45,675
chr19	1049013	.	A	C,<NON_REF>	877.06	.	DP=24;ExcessHet=3.0103;MLEAC=2,0;MLEAF=1.00,0.00;RAW_MQandDP=86400,24	GT:AD:DP:GQ:PL:SB	1/1:0,23,0:23:69:891,69,0,891,69,891:0,0,7,16
chr19	1049014	.	C	<NON_REF>	.	.	END=1049014	GT:DP:GQ:MIN_DP:PL	0/0:23:45:23:0,45,675
chr19	1049015	.	T	<NON_REF>	.	.	END=1049026	GT:DP:GQ:MIN_DP:PL	0/0:19:42:15:0,42,630
chr19	1049027	.	T	<NON_REF>	.	.	END=1049031	GT:DP:GQ:MIN_DP:PL	0/0:15:39:14:0,39,585
```

I have no idea why the error occured.

**My code:**
```
cat 1049005.fa | bcftools consensus xxx.cram.out.g.vcf.gz
```

The .g.vcf.gz file was from gatk HaplotypeCaller, which should includes all variants in the sample genome.

The fasta file is like:
```
>chr19:1048895-1049005
GCCAGTACGGGATCCCTGAACCATGGAATTTTCCTTTTCGGAGGAGCTACTGGTGCGGACCTCGGCCCCCCAAGAGTCCAGCCCCTTGCCCCACCCCGCTGGACCCAAAGG
```
(The start position of fasta has been modified from 0-based to 1-based.)

**Comment by pd3** [comment]
I am not able to reproduce the problem with the latest version. Can you please try if upgrading resolves the problem? Added a test based on your case 094a058.

**Comment by solemnla** [comment]
I think the error is not caused by bcftools.
Unzipping and zipping the g.vcf file from gatk haplotypeCaller can solve the problem.
There might be some problems in the way gatk bgzip a file while generating the file.

**Comment by solemnla** [comment]
> I am not able to reproduce the problem with the latest version. Can you please try if upgrading resolves the problem? Added a test based on your case [094a058](https://github.com/samtools/bcftools/commit/094a05862156946a7b118974f9ebd849c57a18f1).

Thanks a lot for the test. I used bcftools/1.14 this time and the error still occurs.
`Currently Loaded Modulefiles:
 1) bcftools/1.14   2) samtools/1.14 `

My test files:
fake.fasta
`>chr19:1048895-1049005`
`GCCAGTACGGGATCCCTGAACCATGGAATTTTCCTTTTCGGAGGAGCTACTGGTGCGGACCTCGGCCCCCCAAGAGTCCAGCCCCTTGCCCCACCCCGCTGGACCCAAAGG
`
fake.g.vcf
`##fileformat=VCFv4.2`
`##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">`
`##reference=file://some/path/human_g1k_v37.fasta`
`##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">`
`##ALT=<ID=NON_REF,Description="gVCF block">`
`##contig=<ID=1,assembly=b37,length=249250621>`
`chr19	1048985	.	C	<NON_REF>	.	.	END=1048985	GT:DP:GQ:MIN_DP:PL	0/0:31:81:31:0,81,1215`
`chr19	1048986	.	C	<NON_REF>	.	.	END=1048994	GT:DP:GQ:MIN_DP:PL	0/0:31:72:29:0,72,1080`
`chr19	1048995	.	G	<NON_REF>	.	.	END=1049004	GT:DP:GQ:MIN_DP:PL	0/0:30:60:28:0,60,900`
`chr19	1049005	.	G	<NON_REF>	.	.	END=1049006	GT:DP:GQ:MIN_DP:PL	0/0:27:51:27:0,51,765`
`chr19	1049007	.	T	<NON_REF>	.	.	END=1049008	GT:DP:GQ:MIN_DP:PL	0/0:25:39:25:0,39,585`
`chr19	1049009	.	A	<NON_REF>	.	.	END=1049009	GT:DP:GQ:MIN_DP:PL	0/0:25:42:25:0,42,630`
`chr19	1049010	.	G	<NON_REF>	.	.	END=1049012	GT:DP:GQ:MIN_DP:PL	0/0:24:45:23:0,45,675`
`chr19	1049013	.	A	C,<NON_REF>	877.06	.	DP=24;ExcessHet=3.0103;MLEAC=2,0;MLEAF=1.00,0.00;RAW_MQandDP=86400,24	GT:AD:DP:GQ:PL:SB	1/1:0,23,0:23:69:891,69,0,891,69,891:0,0,7,16`
`chr19	1049014	.	C	<NON_REF>	.	.	END=1049014	GT:DP:GQ:MIN_DP:PL	0/0:23:45:23:0,45,675`

Then
`bgzip fake.g.vcf`
`tabix fake.g.vcf.gz`
`cat fake.fasta | bcftools consensus fake.g.vcf.gz`

**Comment by solemnla** [comment]
> I am not able to reproduce the problem with the latest version. Can you please try if upgrading resolves the problem? Added a test based on your case [094a058](https://github.com/samtools/bcftools/commit/094a05862156946a7b118974f9ebd849c57a18f1).

I tried your test files and there is no error showing up.

**Comment by pd3** [comment]
The provided fasta was shorter than the span of the variants in the VCF. The problem is now fixed and should work as expected. Thank you for reporting the issue!

**Comment by solemnla** [comment]
> The provided fasta was shorter than the span of the variants in the VCF. The problem is now fixed and should work as expected. Thank you for reporting the issue!

Thank you so much for your quick response and the fix!
