### ISSUE TITLE
Why is reheader not functioning properly while trying to rename some samples in a .vcf.gz file?

### ISSUE THREAD

**Issue by fierytortilla** [samtools/bcftools#1616]
I am trying to use the reheader tool from bcftools in order to rename some samples in a .vcf.gz file, but it does not work, and is giving some pretty strange errors. Before trying to rename my samples, I set up a text file called samples_names_dummy.txt file, which has the .vcf.gz's original sample names (and their pertinent replacements), each separated by a space and written line by line (as dictated by the manual https://samtools.github.io/bcftools/bcftools.html#reheader).

But when I run the command `bcftools reheader -s samples_names_dummy.txt test_file.vcf.gz`, I get outputs like this: `QG</B?%=߷???4???ʏF????l???ϻ?7?jyu\Aҹm???Zw???B}?4?ɸ!?!?H?c?e??!m?)??Z???@?B?BC%`, and then my terminal screen clears, and a new line is entered with `1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c`.

When I check my test_file.vcf.gz afterwards, the sample names are not changed. I am completely uncertain as to what exactly the error is. I have tried converting the .vcf.gz file into a .bcf file to get it to work (using `bcftools view -O u -o test_file.bcf test_file.vcf.gz`), but it yields the same output as before. Has anyone seen this kind of error before, and can recommend a solution to it?

**Comment by fierytortilla** [comment]
Ok I got it working now, I just needed to set an output file in the command line, like `bcftools reheader -s samples_names_dummy.txt -o output.vcf.gz  test_file.vcf.gz`.

**Comment by pd3** [comment]
The program outputs the modified file in the same format that was on input. In your case it was a compressed VCF, so on output you'll se a compressed binary stream. There are multiple ways how to display the result on the screen, for example:
```
bcftools reheader -s smpl.txt input.vcf.gz | bcftools view
bcftools reheader -s smpl.txt input.vcf.gz | gunzip -c
bcftools reheader -s smpl.txt input.vcf.gz | zless
```
