### ISSUE TITLE
convert --gensample2vcf

### ISSUE THREAD

**Issue by xiw588** [samtools/bcftools#1618]
I am trying to convert gen.gz to vcf.gz by using the following command 
bcftools convert --gensample2vcf genotype.QC.chr22.gen.gz,genotype.QC.chr22.samples -Oz -o

But I got the following error message. Can anyone help me with this? 
Could not parse REF in CHROM:POS_REF_ALT id: 22:16876292:C:T 16876292 C T

Thank you! 

Best regards,

**Comment by pd3** [comment]
The documentation says that the second column is expected to be formatted as "CHROM:POS_REF_ALT" but what is found is "CHROM:POS:REF:ALT"
```
*-G, --gensample2vcf* 'prefix' or 'gen-file','sample-file'::
    convert IMPUTE2 output to VCF. The second column must be of the form
    "CHROM:POS_REF_ALT" to detect possible strand swaps; IMPUTE2 leaves the
    first one empty ("--") when sites from reference panel are filled in. See
    also *-g* below.
```

**Comment by pd3** [comment]
I believe this is resolved, closing the issue now.

Cross referencing with an issue #1620 related to this.
