### ISSUE TITLE
bcftools convert --hapsample2vcf don't output rsid

### ISSUE THREAD

**Issue by lanxianmei** [samtools/bcftools#1620]
Hi,

     I use bcftools convert --hapsample2vcf to convert  HAP/SAMPLE to vcf, the command is as follow:
     bcftools convert --hapsample2vcf <haps-file>,<sample-file> -O z -o outfile

     It's good the convert success. But no rsid in the output vcf. I have them in the raw hap file.
     if I add --vcf-ids , I got id like : CHROM:POS_REF_ALT

     How can I set the parameter ?

thank you for any help!

**Comment by pd3** [comment]
This should be fixed now, please try it out and let me know in case of problems.

**Comment by lanxianmei** [comment]
How should I test? Download the code in ZIP format? But how to install? Give me some advise. Many thanks.

**Comment by pd3** [comment]
Please see installation instructions here http://samtools.github.io/bcftools/howtos/install.html

**Comment by lanxianmei** [comment]
Sorry I try more than once ,but can not work it out.
make sure that I use **--hapsample2vcf** not **--gensample2vcf** because my input file is **.hap** format

**the error is :**
$ bcftools convert --hapsample2vcf haps_file,sample_file
Could not determine CHROM in the second column of haps_file: chr18:65950_G_T rs28786173 65950 G T      0 1 1 1 1 1 1 1 1 1
I try to set the second column to chr18 or 18 also fail

**haps_file**
chr18:65950_G_T rs28786173 65950 G T      0 1 1 1 1 1 1 1 1 1
chr18:84627_C_A rs12457467 84627 C A      0 1 1 1 1 1 1 1 1 1
chr18:92127_A_G rs79971566 92127 A G      1 0 0 1 1 0 0 1 1 0
chr18:115408_G_T rs78080343 115408 G T      0 0 0 1 1 0 0 1 1 0
chr18:120465_C_T rs78119892 120465 C T      1 0 0 1 1 0 0 1 1 0
chr18:154473_G_A rs146805053 154473 G A      1 1 1 1 1 1 1 1 1 1

**sample_file**
ID_1 ID_2 missing father mother sex
0 0 0 D D D
A1191380 A1191380 0 0 0 2
A1675002 A1675002 0 0 0 2
A1552108 A1552108 0 0 0 1
A1025670 A1025670 0 0 0 1
A1294613 A1294613 0 0 0 1

**The version bcftools 1.3 can work out but no rsid**
$bcftools convert --hapsample2vcf haps_file,sample_file
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=chr18,length=2147483647>
##bcftools_convertVersion=1.3+htslib-1.3
##bcftools_convertCommand=convert --hapsample2vcf haps_file
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A1191380	A1675002	A1552108	A1025670	A1294613
chr18	65950	.	G	T	.	.	.	GT	0|1	1|1	1|1	1|1	1|1
chr18	84627	.	C	A	.	.	.	GT	0|1	1|1	1|1	1|1	1|1
chr18	92127	.	A	G	.	.	.	GT	1|0	0|1	1|0	0|1	1|0
chr18	115408	.	G	T	.	.	.	GT	0|0	0|1	1|0	0|1	1|0
chr18	120465	.	C	T	.	.	.	GT	1|0	0|1	1|0	0|1	1|0
chr18	154473	.	G	A	.	.	.	GT	1|1	1|1	1|1	1|1	1|1
Number of processed rows: 	6

Looking forward to your reply!

**Comment by pd3** [comment]
The option `--vcf-ids` must be given for the VCF ID column to be filled in

**Comment by lanxianmei** [comment]
yes it work after add --vcf-ids option ,many thanks.

**Comment by mazayayumna** [comment]
Hello! could you show me the example command with --vcf-ids please?
I use **"bcftools convert --hapsample2vcf --vcf-ids example.hap, example.samples -o example.vcf"**
But it does not work with error **[E::hts_open_format] Failed to open file "--vcf-ids.hap.gz" : No such file or directory
Could not read: --vcf-ids.hap.gz**

But it worked without --vcf-ids but same case, the .vcf has '.' as ID. Please correct my command if it's wrong.
Thank you!

**Comment by pd3** [comment]
Your command has several issues. There is a space between `example.hap, example.samples` and it should follow immediately after `--hapsample2vcf`. A working command looks for example like this:
```
bcftools convert  --vcf-ids --hapsample2vcf test/convert.hs.gt.ids.hap,test/convert.hs.gt.samples
```

Please open a new issue next time.
