### ISSUE TITLE
Can bcftools mpileup output multiple hits of the same read?

### ISSUE THREAD

**Issue by caozhichongchong** [samtools/bcftools#1625]
Hi,

I'm using `bcftools mpileup` and `bcftools call` to call SNPs from bam files generated by bowtie2 -a.
I found that the vcf only outputs one hit for each read, even though it has multiple (perfect) hits to the reference.
How can I output all mapping loci of this read in the reference?
The code I'm using:
`bcftools mpileup --threads 40 -a FMT/ADF,FMT/ADR,FMT/AD -Ou -d3000 -A -f input.fasta input.sorted.bam | bcftools call -Ov -A  -c --threads 40 > output.vcf`
Thank you!

Anni

**Comment by pd3** [comment]
I may not understand the problem well. Do you mean if `mpileup` can include reads with 'secondary' flag set? If that is the question then yes, it can, by overriding the default filtering flags settings: 
```
 --ff, --excl-flags STR|INT  Filter flags: skip reads with any of the bits set  [UNMAP,SECONDARY,QCFAIL,DUP]
```

**Comment by caozhichongchong** [comment]
Thank you so much for your fast reply!

I tried `--ff UNMAP,QCFAIL,DUP` and `mpileup ` outputs all 'secondary' hits, including those that are not best hits (not the best score). 
I'm wondering whether `mpileup ` can output all and only the 'best hits'?

Thanks again!
Anni

**Comment by pd3** [comment]
No, mpileup will output everything it sees. You can (and in fact should) filter the VCF afterwards. See e.g.
http://samtools.github.io/bcftools/howtos/filtering.html
http://samtools.github.io/bcftools/bcftools.html#expressions

**Comment by caozhichongchong** [comment]
I see. 

If I understand it correctly, 
`mpileup` default setting outputs only the primary hit (one even though there might be multiple best hits),
and `--ff UNMAP,QCFAIL,DUP` outputs all hits (primary and secondary) without filtering the alignment score.
Then I should filter the VCF afterwards no matter what setting I choose.

Thank you!
Anni
