### ISSUE TITLE
BCFTOOLS error when excluding more than one sample 

### ISSUE THREAD

**Issue by vappiah** [samtools/bcftools#1627]
I have this vcf data which I extracted from 1000 genomes project . When I write a command to exclude one sample it works fine. But when I specify more than one sample I get the error below 
Error: exclude called for sample that does not exist in header: "^HG00103". Use "--force-samples" to ignore this error. 

Here is a command that works  _bcftools view -s ^HG00096 -Oz -o subset444.vcf.gz all.snps_indels.vcf.gz_ 

Here is the one that displays an error _bcftools view -s ^HG00096,^HG00103 -Oz -o subset444.vcf.gz all.snps_indels.vcf.gz_ 

Attached is the data I used and I look forward to your advice. Thanks
[all.snps_indels.vcf.gz](https://github.com/samtools/bcftools/files/7706563/all.snps_indels.vcf.gz)

**Comment by vappiah** [comment]
Hi All, I found the solution.

When excluding more than one samples , you still have to use only one ^ in the command. Here is the command that worked for me
bcftools view -s ^HG00096,HG00103 -Oz -o subset444.vcf.gz all.snps_indels.vcf.gz

I will suggest an example is shown in the bcftools  documentation so that this confusion is avoided. Thanks

I will close the issue now.

**Comment by pd3** [comment]
The documentation has been updated.
