### ISSUE TITLE
csq chokes on GFF with invalid CDS phase information

### ISSUE THREAD

**Issue by pd3** [samtools/bcftools#1628]
I am opening this issue on behalf of mjchenjojo:

Using the latest version of bcftools (1.14) the following csq command
```
bcftools csq  -f all.chrs.con -g MSU7_Csq.gff3 test_chr1.vcf
```

fails with the following error:
```
Parsing MSU7_Csq.gff3 ...
Warning: GFF chromosome "ChrUn" not part of the reference genome
Error: GFF3 assumption failed for transcript LOC_Os01g01010.1, CDS=7136: phase!=len%3 (phase=0, len=371).
       Use the --force option to proceed anyway (at your own risk).
```

A test file is provided offline, the GFF file was downloaded from the official website of Rice.

Note that the same error was reported in #1078 (but no further details were provided).

**Comment by pd3** [comment]
Upon inspection, the first error is caused by missing phase information. The code implicitly assumes phase=0 which soon leads to problems
```
Chr1    MSU_osa1r7  CDS 3449    3616    .   +   .   ID=CDS:cds1;Parent=transcript:LOC_Os01g01010.1
Chr1    MSU_osa1r7  CDS 4357    4455    .   +   .   ID=CDS:cds2;Parent=transcript:LOC_Os01g01010.1
...
```
This problem can be avoided by extending bcftools/csq to ignore the phase column and not perform sanity checks when the phase information is missing.

**Comment by pd3** [comment]
Then there is another problem. The GFF is not consistent and for some transcripts does include the phase information which leads to the following error
```
Error: GFF3 assumption failed for transcript ChrUn.fgenesh.mRNA.2, CDS=3151: phase!=len%3 (phase=2, len=139).
     Use the --force option to proceed anyway (at your own risk).
```

Looking at the GFF it seems the file was edited (it contains multiple `Parent` attributes) and its phase information does not match the expected pattern
```
ChrUn   MSU_osa1r7  mRNA    2314    4368    .   -   .   ID=transcript:ChrUn.fgenesh.mRNA.2
ChrUn   MSU_osa1r7  CDS 4230    4368    10.96   -   0   ID=CDS:cds291322;Parent=transcript:ChrUn.fgenesh.mRNA.2;Parent=ChrUn.fgenesh.gene.2
ChrUn   MSU_osa1r7  CDS 3151    3521    22.93   -   1   ID=CDS:cds291323;Parent=transcript:ChrUn.fgenesh.mRNA.2;Parent=ChrUn.fgenesh.gene.2
ChrUn   MSU_osa1r7  CDS 2986    3001    -2.38   -   0   ID=CDS:cds291324;Parent=transcript:ChrUn.fgenesh.mRNA.2;Parent=ChrUn.fgenesh.gene.2
ChrUn   MSU_osa1r7  CDS 2314    2900    37.31   -   1   ID=CDS:cds291325;Parent=transcript:ChrUn.fgenesh.mRNA.2;Parent=ChrUn.fgenesh.gene.2
```
Is there an independent source to verify the validity of the GFF information?

**Comment by mjchen-st** [comment]
> 

Hi,
ChrUn and ChrSy can be ignored.
And I don't know how to "extending bcftools/csq". I can't understand what you mean? 
Use the --force option ? but there is no cds information in the output result.

**Comment by pd3** [comment]
The extending part has to be done in the code, this I just pushed in the commit e63c00e

**Comment by pd3** [comment]
I believe this issue is resolved now. Please shout if not
