### ISSUE TITLE
Annotating VCF files using tab-delimited tables.

### ISSUE THREAD

**Issue by niruchennagiri-claritas** [samtools/bcftools#163]
I am trying to annotate a VCF file with annotations from a tab-delimited file. The first few lines of the line are shown below:
##INFO=<ID=ResConnAF,Number=A,Type=Float,Description="Allele	Frequency,	ALT>
#CHROM	POS	INFO
chr1	69511	ResConnAF=0.0652
chr1	861368	ResConnAF=0.0870
chr1	865528	ResConnAF=0.0109
chr1	865694	ResConnAF=0.0109
chr1	866511	ResConnAF=0.0543
chr1	871215	ResConnAF=0.0109
chr1	871334	ResConnAF=0.6304
chr1	874455	ResConnAF=0.0109

I am running the command 
~/bcftools/bcftools annotate -a ResConn.freq.pos.txt -c INFO/ResConnAF myVCF.vcf
I have tried a few variations of passing in -c but none of it worked. I get the error:
The tag "ResConnAF" is not defined in ResConn.freq.pos.txt

How exactly can I run this?
Thanks for your help.

**Comment by pd3** [comment]
I am closing this issue, please reopen in case of troubles.
