### ISSUE TITLE
Inconsistent variant type between query and VCF

### ISSUE THREAD

**Issue by lsslssl** [samtools/bcftools#1630]
I'm pretty new to samtools/bcftool and variant calling. I'm not sure if I did anything wrong or missed anything. Just in case I'll go from the very beginning:

First I created a sorted bam file `sample.sorted.bam` using:
`bwa mem ref.fasta sample_r1.fq sample_r2.fq > sample.sam;
samtools view -S -b sample.sam > sample.bam;
samtools sort -O bam -o sample.sorted.bam sample.sam`

Then a VCF file `sample.vcf.gz`:
`bcftools mpileup -Ou -f ref.fasta sample.sorted.bam | bcftools call -m -a GQ | bcftools norm -f ref.fasta -Oz -o sample.vcf.gz; bcftools index sample.vcf.gz`

Next, a query file `sample.query.txt` (including CHROM, POS, and TYPE) :
`bcftools query  -f '%CHROM\t%POS\t%TYPE\n' sample.vcf.gz > sample.query.txt`

**Here comes the problem**:

After checking the `sample.query.txt` file, I noticed that certain loci occur twice and their types are always `REF`, example:
> NODE_5_length_2960_cov_46.969476	2046	REF
NODE_5_length_2960_cov_46.969476	2046	REF

But when I go back to the VCF file `sample.vcf.gz`, it seems one of them is an `INDEL`:

> NODE_5_length_2960_cov_46.969476	2046	.	T	.	284.59	.	DP=155;MQSBZ=0.568796;FS=0;MQ0F=0;AN=2;DP4=102,33,0,0;MQ=59	GT	0/0
NODE_5_length_2960_cov_46.969476	2046	.	T	.	25.1406	.	**INDEL**;IDV=10;IMF=0.0645161;DP=155;VDB=3.7954e-33;SGB=-0.670168;RPBZ=1.04988;MQBZ=0.262613;MQSBZ=0.568796;SCBZ=-0.457816;FS=0;MQ0F=0;AN=2;DP4=105,38,8,2;MQ=59	GT	0/0

**Question 1:**
In a VCF file, if a locus is an indel, then, for example, it either is like:
> REF  ALT
>  A    ATCC

indicating an insertion of `TCC`, or like:

> REF      ALT
>  CGGA   C

indicating a deletion of `GGA`. But why in the example above, in the VCF file, the locus 2046 when annotated as an INDEL, under ALT it is a dot `.`? Is there any problem here?

**Question 2:**
When extracting the information from VCF, why does the type of the second 2046 turn into "REF" instead "INDEL" as how it's like in the VCF?

Please let me know if there's anything that is not clear or any files are needed. Thank you!

**Comment by pd3** [comment]
Either run `call -mv` or `call -mA`, that should help understand it; `mpileup` outputs for indel positions also a SNV positions (in case there are no reads with a single nucleotide variation, it will be just `<*>`). These alternate alleles get removed unless `call -A` is given. Normally you'd call with `-v` which leaves in only possible variants.
