### ISSUE TITLE
bcftools isec: Segmentation fault when using filters

### ISSUE THREAD

**Issue by gabeng** [samtools/bcftools#1632]
`bcftools 1.14` 

`sites-a.vcf.gz` contains a variant with `AF = 0.0099`
The following command creates a Segmentation fault:
```
bcftools isec -p test -i'AF>0.09' sites-a.vcf.gz sites-b.vcf.gz
```
This command does not create a Segmentation fault (note that all variants from the datasets are now included):
```
bcftools isec -p test -i'AF>0.009' sites-a.vcf.gz sites-b.vcf.gz
```
You can create other scenarios with `-e` instead of `-i` creating Segmentation faults. Similar filtering works with other commands like `bcftools view` etc. Attached are sample files.
I was able to work around the issue with merging and filtering files, but it would be nice if the filter option in the `isec` command would work.

[filter.zip](https://github.com/samtools/bcftools/files/7789840/filter.zip)

**Comment by pd3** [comment]
This is now fixed. Thank you for the bug report.
