### ISSUE TITLE
QS field From VCF?

### ISSUE THREAD

**Issue by OmBibo** [samtools/bcftools#1633]
I would like to ask regarding a value reported in vcf output after SNP calling process through mpileup. 

My question is that what is the meaning of a value called "QS", which states "Auxiliary tag used for calling" from its description. I think it seems like the variant frequency of base type in a certain position, but the value is not equal when compared to IGV allele count. Or is that a variant frequency that is corrected by the error rate from raw fastq reads? How it is computed?

Please any clarification!?

Thank you,

**Comment by pd3** [comment]
It's not variant allele counts, those are the AD tags and can be added with `-a AD`. The QS tag is the sum of qualities for each observed base, see also the output of
```
bcftools mpileup -a \?
```

**Comment by numpde** [comment]
Could you please state _precisely_ what is QS?
