### ISSUE TITLE
A way to suppress INFO records, or to have them behind a comment (`#`)

### ISSUE THREAD

**Issue by krassowski** [samtools/bcftools#1634]
Currently `gtcheck` prints a tab-separated table preceded by some comments and a few INFO lines:

https://github.com/samtools/bcftools/blob/0d04159437d12de6f9c672c18347c60591e3f458/vcfgtcheck.c#L793-L806

This is annoying to parse in common tabular data packages like `pandas` because they only allow to set one character for comment (so here `#`) but do not allow to pre-filter the `INFO` lines and these lines break tokenizer; this means that we have to pre-process/grep each file to remove these lines manually before loading the results.

Could `gtcheck` receive a `--quiet` flag, the same way `csq` has one which would hide the `INFO` lines? Alternatively, could the INFO lines start from `#` too?

**Comment by krassowski** [comment]
In a way this is a recent regression as the INFO lines were introduced unconditionally in https://github.com/samtools/bcftools/commit/71733134941cc3809bccd80f82d618d4e52a18dd last year.

**Comment by pd3** [comment]
If you don't like the output, you'll have to create a wrapper to process it to your liking. It can be as simple as running
```
bcftools gtcheck ..  | grep -v ^INFO
```
I am afraid your use case is not a sufficient reason to modify the behavior and add new option.

**Comment by krassowski** [comment]
Fair enough, thanks for the reply and maintaining bcftools!
