### ISSUE TITLE
Add soft filter by region

### ISSUE THREAD

**Issue by yjqiu** [samtools/bcftools#1635]
I would like to add soft filter based on regions from a bed file. However, with -R options. the sites outside the region will be removed. With expression, it will only work for a single region instead of multiple regions.

**Comment by pd3** [comment]
This is now supported, please check the new `--mask-file` option

**Comment by yjqiu** [comment]
Thanks for the support! Just to confirm, I didn't see the option in 1.14. Is it only in the GitHub for now?

**Comment by pd3** [comment]
Yes, only in git for now, http://samtools.github.io/bcftools/howtos/install.html
