### ISSUE TITLE
Merge into existing VCF file

### ISSUE THREAD

**Issue by williamthistle** [samtools/bcftools#1637]
Let's say I have 2 VCF files: one of which contains records for many samples, and one of which contains records for only a single sample. I want to merge these files, but I don't really want to create a third output file because of disk space concerns (as I'll then have two large files, one of which contains records for N samples and one of which contains records for N + 1 samples). Of course, I can replace the first large file with the second one after merging is complete, but temporarily, I'll be taking up way more disk space than I'd like (this is an issue because I'm running this merging on the cloud where I have to pay for additional storage for my job). Ideally, I'd like to merge my second VCF file INTO my first VCF file so that my first VCF file is updated with records from the second VCF file. This would be much more space efficient for my situation. I've looked at the concat option but I don't think that's really what I'm looking for here.

Let me know if there's a solution for this issue that I'm missing! Thank you!

**Comment by pd3** [comment]
That's not possible and would be very difficult to implement, sorry to bring bad news. VCF/BCF is not a database, just a file.
