### ISSUE TITLE
bcftools merge for VCFs with chromosome-spanning SVs.

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#1638]
I have a use-case where I have many (potentially thousands) of VCFs, each with the exact same set of structural variants. 
Some of the variants are very large--perhaps spanning almost an entire human chromosome.
I think that these are causing problems.
Based on my understanding of a quick view of the code, bcftools merge accumulates variants contained within one of these chromosome spanning variants until a new higher end is reached.
Is that what happens with default arguments? If so, is there a simple change to make to prevent this (especially for non-GVCF inputs)?
If the answer is to use another tool, that's fine too.

**Comment by pd3** [comment]
That's probably correct. It would be good to extend the program to be able to handle this, we definitely want to support it. Any chance you could provide a simplified test case to see the exact circumstances when is this happening?

**Comment by pd3** [comment]
Actually, looking at the code I don't think that should be a problem at all. If you can find a good example to demonstrate the exact nature of the problem, that would be helpful.

**Comment by brentp** [comment]
I tried to generate variants that demonstrate (and tried again just now), but haven't been able to do so. I'll close this for now and re-open if I can get a test-case. Thanks for following up.
