### ISSUE TITLE
Error and generally confusion docs wrt "variables calculated on the fly" for expressions

### ISSUE THREAD

**Issue by travc** [samtools/bcftools#164]
The section in the docs about "variables calculated on the fly" under EXPRESSIONS has some problems...

Current text:

> variables calculated on the fly if not present: number of alternate alleles; number of samples; number of alternate alleles; minor allele count (similar to AC but is always smaller than 0.5); frequency of alternate alleles (AF=AC/AN); frequency of minor alleles (MAF=MAC/AN); number of alleles in called genotypes
> 
> N_ALT, N_SAMPLES, AC, MAC, AF, MAF, AN

The second "number of alternate alleles" is an error... should be "count of alternate alleles" I think.
But that is still pretty opaque.

What exactly is "minor allele"?  Is it all the alleles other than the most frequent one (should be IMO)?  Is MAC the sum of the minor alleles, just the most frequent of the minor alleles, or just the least frequent (the answer should be the sum IMO)?

As for that confusing part of the docs...
I'd suggest making a list with a symbol (N_ALT, N_SAMPLES, ect.) and it's definition as the elements.

**Comment by BaxW** [comment]
I still find this section of the documentation confusing. How can MAC be "always smaller than 0.5" if it is a count?

**Comment by pd3** [comment]
The wording needs to be fixed. Obviously, 0.5 is supposed to refer to allele `frequencies`, integer numbers to `counts`, AF vs AC.
