### ISSUE TITLE
Only == and != operators are supported for ID

### ISSUE THREAD

**Issue by Shicheng-Guo** [samtools/bcftools#1640]
I am trying to use bcftools to filter and receive some specific SNPs with "TJP2" pattern. 

`bcftools view -i'ID ~ "TJP2"' UKB.phecode.v2021Q4.WES450.chr9.TJP2.burden_masks.vcf.gz --Oz -o TJP2.vcf.gz`

However, bcftools report: Only == and != operators are supported for ID

I am wondering why bcftools don't support this function. 

Thanks. 

Shicheng

**Comment by pd3** [comment]
No special reason, it just has not been done yet. Thanks for the issue, it is now supported.
