### ISSUE TITLE
`bcftools sort` uses the hard coded `/tmp` folder instead of using `$TMPDIR` on UNIX systems

### ISSUE THREAD

**Issue by ThomasHickman** [samtools/bcftools#1642]
It is generally accepted that UNIX tools should use the temporary directory specified by the environment variable `$TMPDIR`, falling back to `/tmp` if this is not defined. However, it looks like `bcftools sort` does not do this by default: `init_tmp_prefix` (called to initialise the temporary file prefix when `--temp-dir` is not defined in `vcfsort.c`) hard codes the path `/tmp/bcftools.XXXXXX` to use to store temporary files: https://github.com/samtools/bcftools/blob/95760eb6b890432be1a5ff6a35b31741ba36cb8c/reheader.c#L165
This can cause problems when running scripts that use `bcftools sort` in contexts where `/tmp` should not be used to store large files.

**Comment by pd3** [comment]
This is now supported, thanks for the issue
