### ISSUE TITLE
Counts plugin seems to only be counting the number of lines in my VCF file

### ISSUE THREAD

**Issue by rice-in-the-wind** [samtools/bcftools#1646]
Hi, my apologies if this is a trivial issue I am new to this.

I am currently attempting to figure out how to count the total number of SNPs in some VCF files. I am inputting `bcftools plugin counts [file name]` to do so. Doing this returned an SNP count number and a site count number that were identical to eachother, and these numbers were also equal to the total number of lines in my VCF files (not including some header lines in each file). Is there something that I am missing in my input?

**Comment by rice-in-the-wind** [comment]
Hi, mostly I am curious if the site count is supposed to be equal to the SNP count that is returned, and how the SNP count actually works. I manually inserted an extra line into my file that had the reference allele (so no SNPs at all) to see what would happen after I noticed the site count and SNP count were identical to the number of lines in my file. The output still returned a number that seemed to be identical to the number of lines in my file. I wasn't sure if that was supposed to be happening, especially since the new test line I put in didn't actually have an SNP

**Comment by rice-in-the-wind** [comment]
@pd3 Hi, mostly I am curious if the site count is supposed to be equal to the SNP count that is returned, and how the SNP count actually works. I assumed the site count would return the total number of sites in the chromosome. I manually inserted an extra line into my file that had the reference allele (so no SNPs at all) to see what would happen after I noticed the site count and SNP count were identical to the number of lines in my file. The output still returned a number that seemed to be identical to the number of lines in my file. I wasn't sure if that was supposed to be happening, especially since the new test line I put in didn't actually have an SNP present at that site. The manual only said the command counted sites and SNPs but not how, so I was curious to know what is supposed to be happening

**Comment by pd3** [comment]
I don't know what version of bcftools are you using, but the counts should match your intuition. That is, the number of sites is the number of lines, the number of SNPs is the number of SNPs, etc. For example:
```
$ cat test.vcf
##fileformat=VCFv4.2
##contig=<ID=1>
##reference=ref.fa
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	30001	.	C	.	.	.	.
1	30002	.	C	T	.	.	.
1	30003	.	C	CT	.	.	.

$ bcftools +counts test.vcf
Number of samples: 0
Number of SNPs:    1
Number of INDELs:  1
Number of MNPs:    0
Number of others:  0
Number of sites:   3
```

**Comment by rice-in-the-wind** [comment]
I am currently on 1.1.11, so maybe that could be why? I'm noticing an issue with not being able to write an output file when I put `-o [file name]` behind that command too. I'll see if I can update

**Comment by pd3** [comment]
Yes, we are at 1.14, definitely a good idea to update
http://samtools.github.io/bcftools/howtos/install.html

Closing the issue now as it is due to an old version.
