### ISSUE TITLE
vcfcnv.c breakage due to `read_AF()` change

### ISSUE THREAD

**Issue by jmarshall** [samtools/bcftools#1647]
_vcfroh.c_ has a `read_AF` function, which is also used from _vcfcnv.c_. The latter source file has its own declaration for this function:

```c
int read_AF(bcf_sr_regions_t *tgt, bcf1_t *line, double *alt_freq);

static void cnv_next_line(args_t *args, bcf1_t *line)
{
    …
    args->nonref_afs[args->nsites-1] = read_AF(args->files->targets,line,&alt_freq)<0 ? args->nonref_af_dflt : alt_freq;
    …
}
```
&nbsp;
411f50b6e63af7b47c416ad51c9f44ad6c105157 (which landed in 1.12) added a fourth parameter to this function's definition in _vcfroh.c_. Depending on the platform's calling conventions, the effect of this on the unchanged invocation in `cnv_next_line()` would be somewhere between catastrophic and an incorrect error message if
`tgt->nals < 2` is true.

This mismatch would have been caught if both source files used the same declaration of `read_AF` from a header file…

**Comment by jmarshall** [comment]
(Note also that `args_t` refers to different types in the two source files.)

**Comment by jmarshall** [comment]
(Note also that `args_t` refers to different types in the two source files, so some refactoring would be necessary to resolve this.)

**Comment by pd3** [comment]
This is now fixed, thanks for reporting the bug.
