### ISSUE TITLE
Unexpected behaviour for +fixref plugin

### ISSUE THREAD

**Issue by OriolRV** [samtools/bcftools#1654]
Hi everyone!

I am trying to swap my REF and ALT alleles in my SNP array VCF according to the reference genome. I have tried mode "flip" and mode "id" but with neither of them I'm achieving a perfect result, although all my files seem to be fine (i.e. they have the same snp ID) and should work. I have created some small files to reproduce the apparent bug.

First of all, I tried the "-m flip" mode like this:  bcftools +fixref small_array.vcf.gz -O z -o flip.vcf.gz -- -f small_reference.fa -m flip

The output is:

#SC, guessed strand convention
SC	TOP-compatible	0
SC	BOT-compatible	0
#ST, substitution types
ST	A>C	0	0.0%
ST	A>G	1	20.0%
ST	A>T	1	20.0%
ST	C>A	0	0.0%
ST	C>G	0	0.0%
ST	C>T	0	0.0%
ST	G>A	2	40.0%
ST	G>C	0	0.0%
ST	G>T	0	0.0%
ST	T>A	0	0.0%
ST	T>C	0	0.0%
ST	T>G	1	20.0%
#NS, Number of sites:
NS	total        	5
NS	ref match    	1	20.0%
NS	ref mismatch 	4	80.0%
NS	flipped      	0	0.0%
NS	swapped      	3	60.0%
NS	flip+swap    	0	0.0%
NS	unresolved   	1	20.0%
NS	fixed pos    	0	0.0%
NS	skipped      	0
NS	non-ACGT     	0
NS	non-SNP      	0
NS	non-biallelic	0

When I check the files, SNP chr9_10631295 hasn't changed (that's fine because it is the same as in the reference). From the other 4 SNP that need to we swapped, only 3 change; but SNP chr9_10593511 doesn't change. I checked that line and the only explanation is because one of the samples has missing data, which is explained in the documentation as "flip REF/ALT columns and GTs for non-ambiguous SNPs and ignore the rest". Am I right? Is there any reason of why the program should not change sites where 1 sample has missing data?

Since I also have a reference VCF panel, I decided to try the "-m id" option:  bcftools +fixref small_array.vcf.gz -O z -o id.vcf.gz -- -f small_reference.fa -m id -i small_panel.vcf.gz

The output is:

#SC, guessed strand convention
SC	TOP-compatible	0
SC	BOT-compatible	0
#ST, substitution types
ST	A>C	0	0.0%
ST	A>G	1	20.0%
ST	A>T	1	20.0%
ST	C>A	0	0.0%
ST	C>G	0	0.0%
ST	C>T	0	0.0%
ST	G>A	2	40.0%
ST	G>C	0	0.0%
ST	G>T	0	0.0%
ST	T>A	0	0.0%
ST	T>C	0	0.0%
ST	T>G	1	20.0%
#NS, Number of sites:
NS	total        	5
NS	ref match    	1	20.0%
NS	ref mismatch 	4	80.0%
NS	flipped      	0	0.0%
NS	swapped      	0	0.0%
NS	flip+swap    	0	0.0%
NS	unresolved   	5	100.0%
NS	fixed pos    	0	0.0%
NS	skipped      	0
NS	non-ACGT     	0
NS	non-SNP      	0
NS	non-biallelic	0

In this case, although 1 of the sites is "ref match", all 5 sites are considered "unresolved". When looking into the files, none of my alleles is swapped. Do you know what might be the problem here?

My version of bcftools is 1.12 and I'm attaching all the files used in the example:

[fixref.tar.gz](https://github.com/samtools/bcftools/files/8025428/fixref.tar.gz)

**Comment by pd3** [comment]
The reason for the omitted site is different, not a missing genotype. It's because the REF/ALT are in this case A/T and there are two possible explanations what might have gone wrong. The reference allele in the fasta file is T, so it is easy to set REF=T and ALT=A. However, it is not clear what to do with homogyzous genotypes such as 0/0. Is the underlying biological reality A/A or T/T? It could be that the real genotype is A/A, hence the error was made in assignment of the REF allele but the VCF was formatted consistently to match the incorrect REF. Or the real genotype could be T/T, hence the error was made in assigning the REF allele, but the VCF is correct in that the actual genotype is the reference homozygote.

I guess there could be a new option that asks to flip the alleles assuming the VCF is consistent otherwise.

**Comment by OriolRV** [comment]
Hi @pd3!

Thank you for your answer! I'm afraid I'm not following you, though.

If for a given position in a reference genome the nucleotide is T, then that is the REF allele in a VCF generated with that same reference genome. I used the plugin to check this "concordance" between my reference genome and my reference panel, and all REF alleles are the ones present in the reference genome.

Now, in my study panel, that comes from a SNP array (therefore, it might have alleles swapped), I have that same given position, but the REF allele is the other allele, so I want it to be swapped. Since I consider that the fasta reference genome, the reference panel and the study panel are right, then a GT of 0/0 that needs to be swapped should become 1/1, right?

With that in mind, both modes ("-m flip" using the reference fasta genome and "-m id" using the reference panel) should work with all positions in my study panel. You say "I guess there could be a new option that asks to flip the alleles assuming the VCF is consistent otherwise" and I guess this refers to the -m id mode, which is the one skipping all my sites. Does the -m flip failure have the same explanation?

Thank you!

**Comment by pd3** [comment]
Yes, I understand what you want in this situation. The complications come from the seemingly insane (but well motivated) TOP/BOT strand convention. What can happen is that the VCF is a mixture of genotypes and REF/ALT alleles flipped back and forth, so this tool aspired not to increase the confusion and only modify sites that can be resolved unambiguously. In hindsight maybe this was a too conservative approach. A new option to control the behavior seems like the best solution now.

**Comment by OriolRV** [comment]
Hi @pd3,

Sorry for the delay, I wanted to check some things before answering you. I understand your explanation about the TOP/BOT strand convention for the -m flip mode. What about the -m id option? Do you know why is it not working at all right now?

And yes, I agree that an option to control the behavior and "force" the program to swap all alleles based on a reference VCF that is correct would make sense. Do you know when will it be available?

Thank you!

**Comment by pd3** [comment]
The `-m id` option was written with dbSBP rs ids in mind. This has been now generalized to support arbitrary string ids.
Also a new `-m flip-all` was added for flipping any sites, including ambiguous A/T and C/G pairs.
