### ISSUE TITLE
1.15 release?

### ISSUE THREAD

**Issue by colin-nolan** [samtools/bcftools#1656]
There has been a number of useful changes/fixes since `1.14` that we're benefitting from (thanks to SAM and others for your continued support of bcftools/htslib!). It would be great if there was a `1.15` release so we could move from a random dev build, back to one with a friendly, safe sounding name. 

Do you have any plans to mint a new tag? It's not clear what the cadance is for official releases...

**Comment by jkbonfield** [comment]
Nominally they're every 3 months, but they often slip to 4+.

However we're progressing and all 3 of htslib, samtools and bcftools should be getting a new release in the next week or two.

**Comment by colin-nolan** [comment]
Many thanks James - we'll keep an eye out!
