### ISSUE TITLE
error of plugin setGT 

### ISSUE THREAD

**Issue by ncccwa** [samtools/bcftools#1657]
I am using bcftools v1.19. The  setGT plugin with an option -i 'sMAX(FMT/GP) < 0.9' gives an error, "sMAX is not defined in the VCF header". However, the same command works with bcftools v.1.13. Thanks.

**Comment by pd3** [comment]
Are you sure it's 1.19? The latest version is 1.14. You probably meant 1.9? The feature was added later.
