### ISSUE TITLE
error libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fanchen26222** [samtools/bcftools#1658]
I have installed the bcftools software by conda （conda install bcftools）, but, when I performed " bcftools --help", the error exists " libopenblas.so.0: cannot open shared object file: No such file or directory". 
cat /proc/version
The  Linux version 2.6.32-642.el6.x86_64 (mockbuild@x86-033.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Wed Apr 13 00:51:26 EDT 2016
Would you give me some suggestions how to install and use this software? please. Thanks.

**Comment by jmarshall** [comment]
Conda's bcftools package enables the `polysomy` command, so depends on the GNU Scientific Library, which in turn can be configured to use various flavours of BLAS. This error indicates that you have ended up with the wrong flavour of BLAS, which is conda/conda#7548. (Perhaps the environment you were installing bcftools into already had the other flavour of BLAS installed for the benefit of other packages.)

To work around this, create your environment or install bcftools as follows:

```
conda create -n myenv bcftools "conda-forge::blas=*=openblas"

# …or…

conda install bcftools "conda-forge::blas=*=openblas"
```

(As people are wont to report such issues here, it can be useful to have an answer here. Or if bcftools were to add information about third-party binary packaging to its INSTALL or README, this would be useful to add to an eventual bioconda entry.)

**Comment by jkbonfield** [comment]
While conda environments solve many woes, this is surely still a conda bug.

The fact remains it installed a broken version of a tool.  If it had a dependency clash, it should report it and refuse to install.  I'd still suggest reporting it upstream.  The more people who report such things the more likelihood there is of them fixing the relevant dependency files.

My gut feeling regarding conda though is it shouldn't be in our INSTALL file.  It's a totally different environment and people reading INSTALL are really those who are compiling from source.  Infact the whole point of Conda is that you don't need to be grubbing through source packages on GitHub yourself. 

We could however open a ticket on bioconda with corrections, but it's not something I'm familier with as I try to avoid conda like the plague frankly!  The only time I've ever found it useful is when the upstream package is so messy that dependencies become unwieldy to do by hand.

**Comment by jmarshall** [comment]
Of course it is a conda issue, and I pointed to the relevant report.

You are right that INSTALL is mostly about building from source. OTOH it's not uncommon to have pointers to third-party binaries in projects' READMEs, and doing so in these projects (for perhaps a [subset of these](https://twitter.com/jomarnz/status/1492093675404419072)) would not be unhelpful for htslib/samtools/bcftools users.

**Comment by fanchen26222** [comment]
Thank you very much, I have  successfully installed bcftools as follows: 
conda create -n myenv bcftools "conda-forge::blas=*=openblas" and run it. 
I am very grateful for your valuable advice and enthusiastic help.
With Best Regards
