### ISSUE TITLE
Maximum number of samples supported by VCF/BCF spec and BCFTools

### ISSUE THREAD

**Issue by WimSpee** [samtools/bcftools#1664]
Dear BCFTools developers. 

I am wondering if there is any hard limitation of the number of samples than can be stored in a multi-sample VCF/BCF file. 

Or if there is maybe a limit to the number of samples that BCFTools can read/subset from a single multi-sample VCF/BCF file. 
Or merged without collapsing overlapping variants from multiple smaller multi-sample BCF files. 

I understand that memory usage and CPU time probably goes up when reading very large VCF files. 
But that can be be dealt with by storing and reading data e.g. per chromosome.  And anyway bcftools streams trough the variants. 

I am just wondering if there is no hard limit anywhere in e.g. an array type of the number of sample columns/genotypes/genotype attributes. 
Or what you maybe have seen as the largest number of samples stored in a VCF/BCF file that could still be read via BCFTools. 

e.g. would it be possible to store a 10K WGS variant table in a BCF file and read/parse that via BCFTools?
e.g. would it be possible to store a 100K WES variant table in a BCF file and read/parse that via BCFTools?
e.g. would it be possible to store a 1M small targeted variant panel table in a BCF file and read/parse that via BCFTools?

Thank you for your thoughts on this.

**Comment by pd3** [comment]
The number of samples should fit in 24-bits which allows up to 16,777,216  samples. With this many samples one might also hit the maximum BCF row length, the genotype data (GT, PL, etc) must fit into 4,294,967,295 bytes (uint32_t).

**Comment by WimSpee** [comment]
Thank you for looking into this. Those are impressive numbers!
