### ISSUE TITLE
about GT’ calculation

### ISSUE THREAD

**Issue by yuanjianwen-gif** [samtools/bcftools#1665]
I am using bcftools to call A to G transition in mRNA  with RNAseq data， instead of snp at genomics ，and notice that there are mutations annotated 0/0 genotype but with high edited frequency (like DP4_alt = 50 , DP4_total = 200 ).  It is really confusing what matters for genotype likehood calculation. Or it is not reasonable to use bctools to call mutation in mRNA

**Comment by pd3** [comment]
The program `bcftools call` assumes diploid or haploid genotypes and is not intended for detection of somatic mutations / RNA editing. For that, I recommend running like this
```
bcftools mpileup -a AD ... | bcftools call -mA ...
```
ignoring GTs and postprocessing the output using a custom script based on AD depths. The mathematical model of `call -mv` (described here http://samtools.github.io/bcftools/call-m.pdf) cannot detect mosaic variants well.
