### ISSUE TITLE
speeding up bcftools mpileup and call

### ISSUE THREAD

**Issue by sjfleck** [samtools/bcftools#1666]
Hello,
I'm trying to create a VCF file for a single individual. With older versions of samtools/bcftools (v0.1.19), I used this command:

samtools mpileup -C 50 -uf ref.fa aln.bam | bcftools view -c - | vcfutils.pl vcf2fq | gzip > diploid.fq.gz

And this step never took TOO long, but I was mapping paired-end illumina reads onto a reference to create the SAM/BAM file. This time, I'm using a BAM file created by mapping ONT reads onto a reference. Since "vcfutils.pl vcf2fq" is no longer supported with newer versions, I'm just stopping at the VCF creation step using the latest versions (v1.14 ...I see now that v1.15 was released yesterday, but I don't have it yet). 

The problem that I'm having is that the VCF is taking a VERY long time to be made. I tried multithreading, but I'm not sure how much it actually helped. I also didn't know which variant caller to use, so I'm running this command a few different ways to compare the results later. Unfortunately, I haven't been able to have a single run finish. Here are the commands:

(A.)  original calling method 
bcftools mpileup -C 50 -Ou --threads 16 -f $GENOME aln.sorted.bam | bcftools call --threads 16 -c -Ov -o aln.sorted.original_call.vcf
(B.) original calling method, output variant sites only
bcftools mpileup -C 50 -Ou --threads 16 -f $GENOME aln.sorted.bam | bcftools call --threads 16 -cv -Ov -o aln.sorted.original_call.variant_sites.vcf
(C.) alternative model for multiallelic and rare-variant calling
bcftools mpileup -C 50 -Ou --threads 16 -f $GENOME aln.sorted.bam | bcftools call --threads 16 -m -Ov -o aln.sorted.alt_call.vcf
(D.) alternative model for multiallelic and rare-variant calling, output variant sites only
bcftools mpileup -C 50 -Ou --threads 16 -f $GENOME aln.sorted.bam | bcftools call --threads 16 -mv -Ov -o aln.sorted.alt_call.variant_sites.vcf

My first run timed out at 48 hours (we can ask for up to 72 hours of run time on my university's cluster). Only (A.) had started and had a partially complete VCF file of over 100GB in size. 

While that was still running, I submitted another job. I reversed the order of the commands, making (D.) start first. I also increased the number of threads for bcftools mpileup and bcftools call to 32. The job failed this morning after 60 hours (today is our monthly maintenance downtime, so I couldn't run it for longer than this). The resulting VCF was much smaller. I'm not sure if it made less progress or if this is just the difference between the "-mv" option and the "-c" options. I imagine just the "-v" option alone would result in much smaller VCF files.

Ultimately, I'm asking if there is a way to speed up this process. I saw some talk of the "-r, --regions" to split the job among subsets of contigs/scaffolds/chromosomes. Can this also be merged with the "bcftools merge" command? The description makes it seem like it can merge A VCF with sample 1 and a VCF with sample 2 into a VCF with samples 1 & 2.

But can it also combine:
(a.) a VCF with contig 1-50 for sample 1
(b.) a VCF with contig 51-100 for sample 1 

into:
(c.) a VCF with contigs 1-100 for sample 1?

Thanks for any help and recommendations you can give for speeding this process up
-Steve

**Comment by pd3** [comment]
Multithreading is used only for BGZF compression/decompression so will probably have marginal effect on calling.

Since you are working with ONT reads, try to run with `bcftools mpileup --config ont`. If the performance is still poor, it would help if you could identify a problematic region where 0.19 is significantly faster than 1.15 and share it with us for debugging.

**Comment by jkbonfield** [comment]
Multi-threading makes no major difference currently to mpileup.  It multi-threads the BAM decoding, and if the output is bgzipped it threads the encoding, but the bottleneck is the mpileup/call functions.

For ONT, I would strongly recommend using the `-X ont` option.  This unfortunately (for now) disables indel detection, but it was found to be very unreliable on the ONT data we tested and it was also the dominant cause for slow downs.  See the mpileup usage statement for a description of what this changes:

```
Configuration profiles activated with -X, --config:
    1.12:        -Q13 -h100 -m1 -F0.002
    illumina:    [ default values ]
    ont:         -B -Q5 --max-BQ 30 -I [also try eg |bcftools call -P0.01]
    pacbio-ccs:  -D -Q5 --max-BQ 50 -F0.1 -o25 -e1 --delta-BQ 10 -M99999
```

If you still want indels, then you can experiment with the other options.  Disabling BAQ is a must for performance (-B), and most of the other options are minor minodifications to improve accuracy.  The `-I` is the indel disable step.

I wouldn't advise the use of `-C 50`.  This appears to be a legacy meme reproduced widely, but my evaluations showed it to generally be detrimental.

If you wish to do your own multi-threading equivalent, note that it is possible to divide the genome into approximately equal sized chunks (or even just unequal - one per chromosome) and run bcftools mpileup / call in parallel.  The results can then be joined with `bcftools concat`.  I'm sure there must be wrapper scripts out there that automate this, but I'm not aware of them off the top of my head.

**Comment by sjfleck** [comment]
Thank you both for such a quick responses. I will use the "--config ont" option and remove the "-C 50" option.

I will also try to run everything together first, but if I still get a time out error, I'll try the "-r, --regions" option and combine the results using "bcftools concat" (and not "bcftools merge"). 

I will submit the new jobs tonight after our monthly downtime is over. I'll respond again when I have results and hopefully close the issue. Thanks!
