### ISSUE TITLE
`concat` with process substitution

### ISSUE THREAD

**Issue by aryarm** [samtools/bcftools#1667]
Is it possible to pipe multiple files to `concat` through process substitution?

Theoretically, it should be possible to `concat` streams since the input files must be sorted, right?

**Comment by pd3** [comment]
Theoretically yes, but the program also works for overlapping VCFs, therefore this is not supported.

**Comment by aryarm** [comment]
ok, thanks! My use case is that I have multiple files that I'd like to `concat` but they are quite large, so I don't want to have to write them to the file system uncompressed. Being able to pipe the files with process substitution would save time spent compressing and uncompressing the files, so it would be nice if there was a way to implement this feature.

But I can understand if it isn't possible, given the current way the code is written.

Thanks again for creating such a useful piece of software!
