### ISSUE TITLE
bcftools stats to compare two vcf files

### ISSUE THREAD

**Issue by repeatpipettor** [samtools/bcftools#1673]
Hello, 

I am trying to use bcftools stats (v1.9) to compare two VCF files. One VCF contains SNPs that were imputed, and the other VCF contains the same SNPs that were directly genotyped by whole-genome sequencing. To evaluate the quality of imputation in the first VCF, I would like to use the outputs in the table mentioned in [this issue](https://github.com/samtools/bcftools/issues/1200#issuecomment-613311515), particularly the dosage r-squared.

However, I do not see this table anywhere in the output. Do the VCF files have to contain any particular flags in order for bcftools to be able to calculate these metrics?

I ran the following:
`bcftools stats imp.vcf.gz wgs.vcf.gz > imp_vs_wgs.stats`

Thank you.

**Comment by pd3** [comment]
In the default mode the program only checks sites but not samples. To force also checking of genotype fields, run with `-s -`. 
(I know that's rather unintuitive, sorry.)

**Comment by alexlenail** [comment]
How would one compute bcftools stats between all samples in one file and all samples in another file, supposing the samples in each of the files had different names (but a subset of them have a 1:1 mapping I'm searching for)
