### ISSUE TITLE
Consensus sequence from GATK haplotypecaller

### ISSUE THREAD

**Issue by Sakurasugar02** [samtools/bcftools#1682]
My research is to reveal the sequences of chemical receptor genes from non-human primates. Now I am trying to obtain the consensus sequences from GATK haplotypecaller. Everything seems fine after we figured out how to filter the variants and get phased sequences by bcftools consensus. But we find a new problem is that some regions without mapped reads still have consensus sequences results and I found that the consensus sequences are the same as reference which means theses sequences are not from reads but from the reference. How can I fix the problem and get the real sequences from my data.

**Comment by pd3** [comment]
Formulated like this, the question seems to ask the impossible: if you don't have any reads in the region, what exactly do you expect to see?

By default the VCF is interpreted as a record of changes that have to be applied to the reference sequence in order to obtain the (hopefully) real biological sequence. You can also use the `-a, --absent CHAR` option to "mask" characters for which there is no evidence in the VCF with a custom character.

**Comment by Sakurasugar02** [comment]
> Formulated like this, the question seems to ask the impossible: if you don't have any reads in the region, what exactly do you expect to see?
> 
> By default the VCF is interpreted as a record of changes that have to be applied to the reference sequence in order to obtain the (hopefully) real biological sequence. You can also use the `-a, --absent CHAR` option to "mask" characters for which there is no evidence in the VCF with a custom character.

Thank you very much. I will try the -a option to conduct the bcftools consensus again.

**Comment by Sakurasugar02** [comment]
> Formulated like this, the question seems to ask the impossible: if you don't have any reads in the region, what exactly do you expect to see?
> 
> By default the VCF is interpreted as a record of changes that have to be applied to the reference sequence in order to obtain the (hopefully) real biological sequence. You can also use the `-a, --absent CHAR` option to "mask" characters for which there is no evidence in the VCF with a custom character.

I tried samtools mpileup and bcftools call to make the vcf file. When I make the consensus sequence by bcftools consensus -a, it works very well. Thank you for the advice! It is really helpful.
