### ISSUE TITLE
Need to know the number of samples which are homozygotes and heterozygotes

### ISSUE THREAD

**Issue by kvn95ss** [samtools/bcftools#1683]
Hello, I have a huge vcf file which I've obtained after joint-genotyping using GATK. I need to find out how many individuals have a variant in homozygous or heterozygous state. The plugin ```fill-tags``` gives me this info, though it tells how many alleles are present. For heterozygotes its not an issue since the number of alleles would be equal to the number of individuals, but for homozygous allele counts I would like to divide the counts by 2. So far I tried -

```bcftools query -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%QUAL\t%FILTER\tAC_Hom='%AC_Hom/2';AC_Het=%AC_Het\n in.vcf > count.vcf'```

But it prints out ```/2``` with the AC_Hom values.

Are arithematic operation possible when using ```query``` ?

**Comment by pd3** [comment]
The `query` command does not support that, but can be achieved very easily by post-processing, e.g. through awk:
```
bcftools query -f'%AC_Hom\n' | awk '{print $1/2}'
```
