### ISSUE TITLE
bcftools call --ploidy using

### ISSUE THREAD

**Issue by WangWaud** [samtools/bcftools#1688]
Hi,I'm now using bcftools to call SNPs in wheat(ploidy 6).The problem is I don't know how to use the option "--ploidy " in bcftools call.I have seen bcftools(1) Manual Page and imitated its format,but sill can't figure it out.It would be very grateful if you can give me some advice.Very Thanks!

The command is "bcftools mpileup -Ou -f ${genome} -S bamlist ZM895_FRAS220033950-2r.sorted.bam ZM-Rbuk_FRAS220033948-2r.sorted.bam ZM-Sbuk_FRAS220033949-2r.sorted.bam | bcftools call -mv -o raw.vcf"

# error and warning
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Failed to open -: unknown file type

# bamlist 
ZM895_FRAS220033950-2r.sorted.bam       6
ZM-Rbuk_FRAS220033948-2r.sorted.bam     6
ZM-Sbuk_FRAS220033949-2r.sorted.bam     6

**Comment by pd3** [comment]
Unfortunately, bcftools does not work with ploidy bigger than 2, so is not suitable for wheat.

Please use freebayes instead https://github.com/freebayes/freebayes
