### ISSUE TITLE
bcftools norm atomize option split phased variant to unphased variant

### ISSUE THREAD

**Issue by Beomman-Han** [samtools/bcftools#1689]
When I used bcftools norm atomize option, phased variants with multiple alternative alleles were split to unphased variant.

Phased variant with multi-alt-allele before bcftools norm :
```
chr1    4064483 .       G       C,T     190     PASS    SNVHPOL=2;MQ=49 GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL:PS 2|1:79:9:14:5:0,7,7:0,6,1:0,1,6:-29.3:PASS:254,127,106,127,0,106:4064470
```

Unphased variant after bcftools norm : 
```
chr1    4064483 rs111214133     G       C       190.0   PASS    SNVHPOL=2;MQ=49;SNP;HET;VARTYPE=SNP;dbSNPBuildID=132;ANN=C|intergenic_region|MODIFIER|LINC01346-LINC01777|LINC01346-LINC01777|intergenic_region|LINC01346-LINC01777|||n.4064483G>C||||||        GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL:PS .|1:79:9:7:5:0,7:0,6:0,1:-29.3:PASS:254,127,106:4064470
chr1    4064483 rs111214133     G       T       190.0   PASS    SNVHPOL=2;MQ=49;SNP;HET;VARTYPE=SNP;dbSNP138_ID=rs201052409;dbSNPBuildID=132;ANN=T|intergenic_region|MODIFIER|LINC01346-LINC01777|LINC01346-LINC01777|intergenic_region|LINC01346-LINC01777|||n.4064483G>T||||||        GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL:PS 1/.:79:9:7:5:0,7:0,1:0,6:-29.3:PASS:254,127,106:4064470
```

I expected that GT of G>T variant would be "1|."  not "1/.". When I investigated other phased variants with multiple alt allele, all phased variants were split to one phased variant and one unphased variant. How bcftools norm command split phased variants with multiple alternative allele?

I used bcftools-1.15 version and here is my command.
```sh
bcftools norm -Ov -a --atom-overlaps . ${input_vcf} > ${out_vcf}
```

Any help would be appreciated.

**Comment by pd3** [comment]
Thank you for the bug report, this is now fixed.
