### ISSUE TITLE
Plugin af-dist

### ISSUE THREAD

**Issue by makine1000** [samtools/bcftools#1692]
Hi,

I'm following the instructions at https://samtools.github.io/bcftools/howtos/plugin.af-dist.html to check if my vcf-files have potential strand issues after conversion from hg38 -> 19. I can't find explanation for the columns in the example table and what is actually plotted in the figure. I first thought that the last column shows the number of markers falling in each of the bins (columns 2 and 3) after HWE test. This is not apparently the case since the numbers don't add up to the total number of markers in my vcf.  The last column is not either a probability since in the figure y-axis is 0->1.

Any help would be appreciated.

**Comment by pd3** [comment]
The program checks non-reference genotypes (i.e. not necessarily all markers are looked at), calculates how likely it is to observe the 0/1 or 1/1 genotype given the allele frequency (the former is `2*AF*(1-AF)`, the latter is `AF*AF`), and then outputs the counts across the probability bins. Obivously, one wants to see few unlikely genotypes.

Does this make sense?
