### ISSUE TITLE
bcftools fill-tags not filling AC_Hemi as expected

### ISSUE THREAD

**Issue by kvn95ss** [samtools/bcftools#1693]
Hello,

I'm using ```bcftools +fill-tags input.vcf -Ou -o count_test.vcf -- -t all``` to count the number of alleles in homozygous and heterozygous state. For all of chrX variants, I was expecting ```AC_Hemi``` field to contain the alleles, however the alleles are listed under ```AC_Hom```. 

Here is a sample output for one variant.

```chrX    10671   .       C       T       1970.99 PASS    AC=2;AF=0.0142857;AN=140;DP=2844;ExcessHet=0.0157;FS=0;InbreedingCoeff=0.6419;MLEAC=3;MLEAF=0.021;MQ=51.68;QD=25.36;SOR=1.28;VQSLOD=3.66;culprit=FS;NS=70;MAF=0.0142857;AC_Het=0;AC_Hom=2;AC_Hemi=0;HWE=0.00719424;ExcHet=1       GT:AD:DP:GQ:PGT:PID:PL:PS       1|1:0,45:45:99:1|1:10671_C_T:2006,135,0:10671  etc etc```

Could it be, that since the genotype is ```1|1```, it is being counted under ```AC_Hom```?

**Comment by pd3** [comment]
That's most certainly the case. If is was a male chrX genotype, `1` rather than `1|1`, it would have increased the `AC_Hemi` counter instead of `AC_hom`.

**Comment by mirgin01** [comment]
Hello!
I'm working on the same topic as the original post. I want to ensure I understand how the AC_hemi is populated. 
With _If is was a male chrX genotype_ how does the tool know if the variant in chrX is from a male or a female? or do you mean that the variants in crhX will always be annotated in AC_hom? Does the calculation take into consideration if the variant is not in a PAR region? 
Thanks in advance!
