### ISSUE TITLE
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by eudesbarbosa** [samtools/bcftools#1698]
Hello. I'm having some issue installing and running `bcftools` after the most recent release (v1.15). And pinning the package to the previous version doesn't help. 

Anyone faced something similar? Any hints on how to proceed?

Error:
```
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```

**Dependency difference**
...works (from previous [log](https://github.com/samtools/bcftools/files/8450175/works.log)):
```
2022-03-03T14:32:50.9725381Z + gsl 2.7 he838d99_0 conda-forge/linux-64 3MB
```
...breaks (from current [log](https://github.com/samtools/bcftools/files/8450176/breaks.log)):
```
2022-03-23T09:01:56.7405052Z + gsl 2.7.1 hd82f3ee_0 pkgs/main/linux-64 2MB
```
...also forcing `gsl ==2.7` or `gsl ==2.7.0` just leads to a different error message ([log](https://github.com/samtools/bcftools/files/8450190/also_breaks.log)):
```
bcftools: symbol lookup error: /usr/share/miniconda/envs/__setup_conda/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv
```

**Comment by pd3** [comment]
This is a problem with conda installation. Apparently the program was compiled with `--enable-libgsl` but the dependency on libgsl is not met on your system. I cannot help with conda (failed many times trying to install something myself), but bcftools is easy to obtain and compile from source: http://www.htslib.org/download/

**Comment by eudesbarbosa** [comment]
@pd3 , thank you for the quick reply. I will transfer the issue to conda people.

**Comment by swvanderlaan** [comment]
This issue remains (https://www.biostars.org/p/9480029/#9573995). Is there no way of solving this through `conda` that anyone is aware of?

**Comment by jkbonfield** [comment]
It's a perennial conda issue.  I see the question you posted to biostars has already been answered, but this is a closed issue here already.

Generally, for issues like this which aren't bugs specifically with our software and are instead errors caused by using prebuilt binaries supplied elsewhere with configuration problems, it's best to seek help on either conda-specific forums or biostars before raising (or resurrecting) issues here.

**Comment by blake-bowen** [comment]
installing via conda-forge instead of bioconda solved the issue for me: 
`micromamba install bcftools -c conda-forge`

**Comment by jkbonfield** [comment]
This is still a conda issue, and will forever remain a conda issue.  There isn't anything we can do to fix other vendors packaging of our tools short of taking it on ourselves, which isn't something we have time to do.

Please raise conda specific issues in the various conda githubs (likely bioconda here), or on general sites like biostars.

**Comment by pjgreer** [comment]
I know this is closed, but another possible hack/workaround:

At issue is the conda install is linking to the v25 library directly. With the 27 library release the so.25 file no longer exists.

So If you have installed the library via apt-get, search for the library file in /usr

`find /usr -name libgsl.so* -print`

This will find the library here:

`/usr/lib/x86_64-linux-gnu/libgsl.so`
`/usr/lib/x86_64-linux-gnu/libgsl.so.27 `
`/usr/lib/x86_64-linux-gnu/libgsl.so.27.0.0`

So a fix that worked for me is to generate a symbolic link for the so.25 library from the .so file. 

`sudo ln -s /usr/lib/x86_64-linux-gnu/libgsl.so /usr/lib/x86_64-linux-gnu/libgsl.so.25`

This made bcftools work for me, but may break in future update.

**Comment by SuqingLi** [comment]
Hey, guys, I found a simple way to solve it. 
bcftools can be run in the conda base env, but if you install it in a custom env, it can't work, either by conda install or source install. So I install bcftools in the base env first, and then make a soft link (ln -s) of it to replace the bcftools in my custom env.

**Comment by OlivierCoen** [comment]
> sudo ln -s /usr/lib/x86_64-linux-gnu/libgsl.so /usr/lib/x86_64-linux-gnu/libgsl.so.25

worked for me too! thanks!

**Comment by jmarshall** [comment]
Linking random libraries to the _libgsl.so.25_ filename the executable is expecting is bad advice. The reason they have different soversions is that they are incompatible.

You are better off setting up your conda channels properly so that this is fixed once and for all.
