### ISSUE TITLE
bcftools vs varscan (samtools)

### ISSUE THREAD

**Issue by ibseq** [samtools/bcftools#1699]
hi all, 
what is the difference between the variants called by bcftools call and varscan, which still generates mpileup using samtools?

thanks
ibseq

**Comment by pd3** [comment]
I don't know about `varscan`, but most certainly both use different algorithms. For the `bcftools` methods please see http://samtools.github.io/bcftools/howtos/publications.html. I don't know if anyone has done callset comparison.
