### ISSUE TITLE
Separate INS and DEL events in bcftools merge results

### ISSUE THREAD

**Issue by ahishsujay** [samtools/bcftools#1704]
Hi, 

I apologize if this question has already been asked, but I needed some clarification and inputs on the merge I am performing. I'm currently merging insertions and deletions for ~40 samples and while performing this I noticed instances where there are deletions happening at a particular site for a few samples but at the same time insertions happening at the same site for other samples (and vice-versa). Here's an example I found in my merged VCF: 
```
chr10	6408	DEL79395-sample1;DEL90355-sample2;INS94796-sample3	AC	A,ACCC	.	PASS	END=6409;ChrB=chr10;StartB=11151;EndB=11151
```

To reiterate, there seems to be a deletion event at POS=6408 on chr10 for sample1 and sample2 while an insertion event at the same position for sample3. I was wondering if there is a way where they can be separated into separate annotations of insertion and deletion, possibly like this? 
```
chr10	6408	DEL79395-sample1;DEL90355-sample2	AC	A	.	PASS	END=6409;ChrB=chr10;StartB=11151;EndB=11151
chr10	6408	INS94796-sample3	AC	ACCC	.	PASS	END=6409;ChrB=chr10;StartB=11151;EndB=11151
```

Thank you, I appreciate it!

**Comment by pd3** [comment]
Best way to address this is to extend htslib VCF interface.
