### ISSUE TITLE
No functional bcftools plugins were found error

### ISSUE THREAD

**Issue by audreyrosemary** [samtools/bcftools#1705]
I have installed and configured bcftools via the Cygwin terminal, ran the mpileup command for a genome assembly file generating .vcf file in the home directory, but when I tried to call the SNPs via `bcftools +counts my.var.vcf ` I got a message stating that:
```
 plugin directory /usr/local/bin/bcftools/plugins .. No such file or directory
counts:
        dlopen   .. No such file or directory

The bcftools plugin "counts" was not found or is not functional in
        BCFTOOLS_PLUGINS="/usr/local/bin/bcftools/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -l" or "bcftools plugin -lvv" for a list of available plugins.

Could not load "counts".
```
When trying to see the plugins using the command  `bcftools plugin -l` I get the message:
```
No functional bcftools plugins were found in
        BCFTOOLS_PLUGINS="/usr/local/bin/bcftools/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -l" or "bcftools plugin -lvv" for a list of available plugins.

```
I tried to make sure that the pathway is correct for the plugins so I exported the path from the original source and plugins folder using  `export BCFTOOLS_PLUGINS="/cygdrive/c/users/hp/bcftools/plugins"` but I get again when trying to see if bcftools can recognize the plugins the same message:
```
No functional bcftools plugins were found in
        BCFTOOLS_PLUGINS="/cygdrive/c/users/hp/bcftools/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -l" or "bcftools plugin -lvv" for a list of available plugins.
```
I can definitely see the count plugin in the plugins original source folder from the bcftools source code and I also made sure that it includes the` #include "bcftools.h"` line as well in the file. I would appreciate it if you could help me with this urgent issue. I don't understand why the plugins are not detected. Thank you very much!

**Comment by pd3** [comment]
Can you give more detail, which version of bcftools are you running and how did you install the program? 
I don't have a Windows machine so can't give more advice than what is described in the installation instructions here https://raw.githubusercontent.com/samtools/bcftools/develop/INSTALL

**Comment by whitwham** [comment]
I did a new install of Cygwin on a Windows 10 machine.  I built htslib and bcftools from a git clone and then installed them using make install.

I get this:

> $ bcftools +counts my.vcf
/usr/local/libexec/bcftools/counts.cygdll:
        dlopen   .. No such file or directory
counts:
        dlopen   .. No such file or directory
>
> The bcftools plugin "counts" was not found or is not functional. The environment variable BCFTOOLS_PLUGINS is not set
and no usable plugins were found in /usr/local/libexec/bcftools.
>
> Could not load "counts".

The counts.cygdll is definitely there. 
> $ ls -l /usr/local/libexec/bcftools/counts.cygdll -rwxr-xr-x 1 Andy None 77087 May  6 12:05 /usr/local/libexec/bcftools/counts.cygdll

I will investigate further.

**Comment by whitwham** [comment]
I think I have found my mistake. So `cygcheck /usr/local/libexec/bcftools/counts.cygdll` gave:

> C:\cygwin64\usr\local\libexec\bcftools\counts.cygdll
cygcheck: track_down: could not find cyghts-3.dll

So `dlopen` looks like it was failing because it couldn't find **cyghts-3.dll**, the htslib library.  It could not find it because I had forgotten to install htslib.

So after installing htslib (just using `make install`) I got this:

> $ bcftools +counts -v ./test/plugin1.vcf
Number of samples: 2
Number of SNPs:    4
Number of INDELs:  9
Number of MNPs:    0
Number of others:  0
Number of sites:   14

**Comment by whitwham** [comment]
No updates from @audreyrosemary  so I am going to close it.

**Comment by sagitaninta** [comment]
Hi, I am experiencing the exact same thing in my server. So I was trying to use the +fill-tags plugin and this happened:
```
./bcftools +fill-tags
fill-tags:
	dlopen   .. fill-tags: cannot open shared object file: No such file or directory

The bcftools plugin "fill-tags" was not found or is not functional in
	BCFTOOLS_PLUGINS="/home/mdn487/bcftools/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -l" or "bcftools plugin -lvv" for a list of available plugins.

Could not load "fill-tags".
```

But I got no error in my install and the plugin was actually there:
```
ls plugins/
ad-bias.c          af-dist.so         color-chrs.c   dosage.c            fill-tags.c   frameshifts.c   GTsubset.so      indel-stats.c   missing2ref.c       remove-overlaps.so  split.c       trio-dnm2.so         variantkey-hex.c
ad-bias.mk         allele-length.c    color-chrs.mk  dosage.so           fill-tags.so  frameshifts.so  guess-ploidy.c   indel-stats.so  missing2ref.so      scatter.c           split.so      trio-stats.c         variantkey-hex.so
ad-bias.so         allele-length.so   color-chrs.so  fill-AN-AC.c        fixploidy.c   GTisec.c        guess-ploidy.so  isecGT.c        parental-origin.c   scatter.so          split-vep.c   trio-stats.so
add-variantkey.c   check-ploidy.c     contrast.c     fill-AN-AC.so       fixploidy.mk  GTisec.mk       gvcfz.c          isecGT.mk       parental-origin.so  setGT.c             split-vep.so  trio-switch-rate.c
add-variantkey.so  check-ploidy.so    contrast.so    fill-from-fasta.c   fixploidy.so  GTisec.so       gvcfz.so         isecGT.so       prune.c             setGT.so            tag2tag.c     trio-switch-rate.so
af-dist.c          check-sparsity.c   counts.c       fill-from-fasta.mk  fixref.c      GTsubset.c      impute-info.c    mendelian2.c    prune.so            smpl-stats.c        tag2tag.so    variant-distance.c
af-dist.mk         check-sparsity.so  counts.so      fill-from-fasta.so  fixref.so     GTsubset.mk     impute-info.so   mendelian2.so   remove-overlaps.c   smpl-stats.so       trio-dnm2.c   variant-distance.so
```

What happened? How can I make bcftools read the plugin?

**Comment by jlchen5** [comment]
In order to use the BCFtools plugins, this environment variable must be set and point to the correct location:
```bash
export BCFTOOLS_PLUGINS=/path/to/bcftools/plugins
```
