### ISSUE TITLE
filter the mutation of control 

### ISSUE THREAD

**Issue by hanguojun007** [samtools/bcftools#1709]
Hi, I have 140 samples with 40 control and 100 case. I processed the 140 samples togather, so the VCF file contain some mutation of control . When I want filter these mutation , I find the `filter` function, but it seems not work best. I have filter the control one by one. I have tried the `filter -i 'GT[@controlsample]="RR"|GT[@controlsample]="mis"'` , it can not work as what i want. I have use 'GT[control1]="RR"|GT[control1]="mis"'` then 'GT[control2]="RR"|GT[control2]="mis"'` ... So , if I am right, hopefully you can improve the code.
Thanks!

**Comment by pd3** [comment]
The command was not intended for this, please check the `+contrast` plugin
