### ISSUE TITLE
plot-roh.py 

### ISSUE THREAD

**Issue by mushalallam** [samtools/bcftools#1710]
Hi, 
plot-roh.py script only dealing with "0/0", "0/1", "1/1" genotype restricted by line number 307,
my VCF files have genotypes like "0|1","1|0", "1|1", so the script usually crash in line 310 because of these genotypes:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/plot-roh.py", line 310, in <module>
    if x[0] != x[1]: dsg = 1
IndexError: list index out of range

any suggestions or help?
Many thanks

**Comment by pd3** [comment]
This is now fixed, thank you for the report.
