### ISSUE TITLE
bcftools call -T fails to genotype multiple alleles at the same locus

### ISSUE THREAD

**Issue by haochenz96** [samtools/bcftools#1711]
Hi,

Thanks for writing and maintaining such an amazing tool. Think this might relate to #1555, but my goal is slightly different in that I am enabling the `-T` option of bcftools to call give allelles. Specifically, for each of our samples, we are interested in knowing if **two alternative alleles** coexist (we already know they coexist in a few samples) and get their ALT/REF counts. 
- Particularly, even if only one exists, we want to get `REF=N, ALT=0` for the other allele. 

But given my command:
```
bcftools mpileup \
            -Ou \
            -R {params.PANEL_AMPLICON} \
            -f {params.REF_GENOME} \
            --annotate FORMAT/AD,FORMAT/DP,INFO/AD \
            -d 100000 \
            {input.SC_BAM} | \
        bcftools call \
            --keep-alts \
            -C alleles \
            -T {input.CANDIDATE_ALLELE} \
            --multiallelic-caller \
            -Ov - | \
        bgzip -c > {output.SC_MPILEUP_VCF} && \
        tabix {output.SC_MPILEUP_VCF}
```
The output VCFs for **all samples** seem to contain only either one of the two alternative alleles. What's the quickest way to address this?

**Comment by pd3** [comment]
I just tested and don't see anything wrong. What version of bcftools are you using? Can you try with the latest version and if it still does not work, can you provide a small test case to reproduce the problem?

**Comment by haochenz96** [comment]
I ran the latest version bcftools v1.15.1. 

I uploaded files in my test case here: https://mskcc.box.com/s/42t4bfhr3yyzzjfy4jkeubgd3qffg7r4. Let me know if you can access it. My test script is included with all the inputs and outputs. A locus of interest is chr12-25398284, where there are 2 distinct alternate alleles (split) in the candidate alleles file (`als.tsv.gz`) provided for genotyping. But in the output (*mpileup.vcf.gz), there is only a single record for that locus which is the first of the 2 alternate alleles. 

I think the fact that I provided a candidate alleles with multiallelic sites split as biallelic might be the issue here?

**Comment by pd3** [comment]
Thank you for the test case. Two things need to be changed for this to work. First, merge multiple SNV alleles into a single multiallelic site, so for example
```
12	25398284	C,A
12	25398284	C,T
```
should become
```
12	25398284	C,A,T
```

Then add the `-A` option 
```
bcftools mpileup -Ou -f ref.fa file.bam | bcftools call -mA -C alleles -T als.tsv.gz
```

For your test case this gives
```
bcftools mpileup -f ref.fa file.bam -r 12:25398284 -a AD | bcftools call -mA -C alleles -T als.txt | bcftools query -f '%CHROM:%POS %REF %ALT \t [ %AD]\n'
12:25398284 C T,A 	  0,108,2
```

I hope this solves the problem?

**Comment by haochenz96** [comment]
Sorry for my super delayed response. I just tested and this worked perfectly for my purpose! Thank you! 

However, I encountered another issue with memory while running the above command on a particular case, and have opened another issue here #1790.

Thanks again for your help!
