### ISSUE TITLE
undefined symbol: cols_split

### ISSUE THREAD

**Issue by HuairenZhang** [samtools/bcftools#1713]
I would like to run bcftools +split-vep for an annotated vcf. I firstly installed the plugins from git, and then set the BCFTOOLs_PLUGINS path. However, when I was running bcftools +split-vep, it says no functional plugin was found. Then when I run bcftools +split-vep -vv, it says undefined symbol: cols_split. Do you know what I could do with this? Thank you.
btw, it will be really helpful if you know how to run split-vep for the annotations in the ANN field instead of the CSQ field. Thank you.

**Comment by pd3** [comment]
This is must be caused by version mismatch. Are you sure you are running the matching binary of bcftools? For example, can you show output of:
```
cd bcftools-latest-checkout-from-github
git pull
make
./bcftools +split-vep
```
This should print the usage page.
