### ISSUE TITLE
Isec unnecessarily requires targets to be set if complement/nfiles aren't

### ISSUE THREAD

**Issue by ASLeonard** [samtools/bcftools#1718]
As a follow up to #1716, using isec to get all the intersections 
```
bcftools isec -o test.sites vcfs/*gz
```
results in an error 
```
One of the options --complement, --nfiles or --targets must be given with more than two files
```
However, the `--targets` option doesn't make as much sense to me, as that is specifying positions to consider, rather than a form of an intersection operation (complete/nfiles). 

Commenting out [this line](https://github.com/samtools/bcftools/blob/3e7fae95c538ec429b0dcad43a622c79842c5d7a/vcfisec.c#L637) which throws the error if targets isn't set allows the program to work just fine, so not sure if there is a deeper design rationale my simple case misses, or if that is a safe restriction to remove?

**Comment by pd3** [comment]
Uh, I cannot remember how it appeared there, can't find a notice in the commit messages. Wouldn't the option allow to "intersect" multiple files by regions at once? Although this is certainly was not the purpose of the program. 

With the line commented out, the program most likely accidentally follows the logic of `-n +1`. Perhaps this should be the default behavior when neither `-n` nor `-C` is given.

**Comment by ASLeonard** [comment]
I'm not sure I follow. As far I understand the `--complement/--nfiles` flags are specifying *how to intersect*, while `--targets` specifies *which coordinates* to intersect, and so they don't appear to be directly related.

The behaviour I want is the example originally stated, to find all intersections across all files, but running
```
bcftools isec -o test.sites vcfs/*gz
```
throws the error about `--complement, --nfiles or --targets`

However, if I run 
```
bcftools isec -t 1,2,3,4,5,6,7,8,9,10...<all contigs in my file> -o test.sites vcfs/*gz
```

that works fine to generate all intersections across all files (the `-n +1` behaviour). So that logic is set anyway, but I just have to manually provide all contigs as targets, which should be redundant.

I rarely use regions/targets, so there may be a powerful approach to generate specific intersections through those flags I'm unaware of, but that should surely be set through `-C/-n` anyway?

**Comment by pd3** [comment]
The option should be not required anymore. Thanks for the bug report.
