### ISSUE TITLE
Missing contig issue with --insert-missed

### ISSUE THREAD

**Issue by Diwadkar** [samtools/bcftools#1728]
Hello,

I am trying to run the following command to extract SNP positions (bed) from RNA-Seq bam files for chrX.

This is the command I am using:
bcftools mpileup -Ov --annotate DP,AD,INFO/AD -q 10 -f genome_chrX.fa -r X -b sortedbam_list.txt | bcftools call -m --constrain alleles -T SNPs.bed --skip-variants indels --insert-missed > Result_chrX.vcf

However, I get the following error:
[E::vcf_format] Invalid BCF, CONTIG id=-1 not present in the header
[tgt_flush_region] Error: failed to write to -

The command runs perfectly when I remove --constrain alleles + --insert-missed but then it does not output all positions in -T file SNPs.bed. There are no "-1" chromosome entries in the bed file so I am not sure what contig id = -1 means exactly.

Further, when I output the mpileup, it does include the following in its header:
##contig=<ID=X,length=156040895>

How can I resolve this error?

**Comment by Diwadkar** [comment]
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##bcftoolsVersion=1.15.1+htslib-1.15.1
##bcftoolsCommand=mpileup -Ou --annotate FORMAT/AD,FORMAT/DP,INFO/AD -f ../../build/chrX/Homo_sapiens.GRCh38.dna_rm.chromosome.X.fa -r X -b GM07345_bamlist.txt
##reference=file://../../build/chrX/Homo_sapiens.GRCh38.dna_rm.chromosome.X.fa
##contig=<ID=X,length=156040895>
##ALT=<ID=*,Description="Represents allele(s) other than observed.">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of raw reads supporting an indel">
##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of raw reads supporting an indel">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">
##INFO=<ID=RPBZ,Number=1,Type=Float,Description="Mann-Whitney U-z test of Read Position Bias (closer to 0 is better)">
##INFO=<ID=MQBZ,Number=1,Type=Float,Description="Mann-Whitney U-z test of Mapping Quality Bias (closer to 0 is better)">
##INFO=<ID=BQBZ,Number=1,Type=Float,Description="Mann-Whitney U-z test of Base Quality Bias (closer to 0 is better)">
##INFO=<ID=MQSBZ,Number=1,Type=Float,Description="Mann-Whitney U-z test of Mapping Quality vs Strand Bias (closer to 0 is better)">
##INFO=<ID=SCBZ,Number=1,Type=Float,Description="Mann-Whitney U-z test of Soft-Clip Length Bias (closer to 0 is better)">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">
##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths (high-quality bases)">
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total allelic depths (high-quality bases)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
##bcftools_callVersion=1.15.1+htslib-1.15.1
##bcftools_callCommand=call -m --keep-alts --constrain alleles -T NA07345_SNPs.bed -Ov; Date=Wed Jun  1 16:15:32 2022
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	 Treated_S8_chrX_sorted.bam

**Comment by Diwadkar** [comment]
[NA07345_SNPs.txt](https://github.com/samtools/bcftools/files/8858095/NA07345_SNPs.txt)

**Comment by Diwadkar** [comment]
The bed file:
[NA07345_SNPs.txt](https://github.com/samtools/bcftools/files/8858098/NA07345_SNPs.txt)

The vcf header from the mpileup:
[NA07345_mpileup_header.txt](https://github.com/samtools/bcftools/files/8858112/NA07345_mpileup_header.txt)

**Comment by pd3** [comment]
Thank you for the test case. The problem here is that the bed file contains a sequence name (`chrX`) which is not in the VCF header, there only `X` is present. The program could be made smarter and insert any missing sequences automatically, but considering how rare is the case, best if you just fix the bed file (`sed 's,^chr,,'`).

Another problem, unrelated to this issue, is that the bed file is not formatted as it should be. The command requested `-C allleles` but there are no alleles in the bed file present. Please check the `-T, --targets-file` description in the manual page http://samtools.github.io/bcftools/bcftools.html#common_options.
