### ISSUE TITLE
fill additional VCF tags (AD,AB, DP) per sample using non conventional FORMAT or INFO field

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#1731]
Hi,

I want to add FORMAT/AD field , FORMAT/AB (allele balance), FORMAT/DP and INFO/DP fields in my structural variation trio VCF I produced using sniffles. The reference read number and alternate read numbers are denoted using DR and DV respectively in the FORMAT area. A downstream analysis tool I am trying to use specifically uses AD,AB and DP fields. Can this be done in any way (probably using the new expression functions in +fill-tags)?

Regards,
Prasun

**Comment by pd3** [comment]
AB and DP could be done, but not AD, as that's defined as Number=A tag and the tool can do only Number=1 tags currently. For the former you could do something like
```
bcftools +fill-tags in.vcf -- -t 'FORMAT/VAF:1=float(smpl_sum(DV) / (DR + smpl_sum(DV)))'
bcftools +fill-tags in.vcf -- -t 'FORMAT/DP:1=DR + smpl_sum(DV)'
```
I don't know how AB is defined, so in the above example showed the fraction of variant alleles instead

**Comment by pd3** [comment]
You'll need to use the latest version, this was added only in 1.15

**Comment by prasundutta87** [comment]
Thanks a lot! I will update my version and try again!

**Comment by prasundutta87** [comment]
It has worked @pd3 ! Thanks a lot for your help! :-)
