### ISSUE TITLE
Two vcf files for bcftools consensus

### ISSUE THREAD

**Issue by OZTaekOppa** [samtools/bcftools#1732]
Hi,

I have a naive question about running the bcftools consensus step. 

After generating two vcf files (SNP vcf and SV vcf) from LongPhase (https://github.com/twolinin/longphase), I am about to generate a haplotype fasta file using the bcftools consensus step. 

According to the LongPhase, it generated these files.

-rw-rw---- 1 XXXX Q4840RW 95685361746 Jun 8 14:31 LPhs_BrahMP_Result.bam (from longphase haplotag)
-rw-rw---- 1 XXXX Q4840RW 150895991 Jun 8 13:23 LPhs_BrahMP_SV.vcf (from longphase phase: PacBio long read)
-rw-rw---- 1 XXXX Q4840RW 1879656315 Jun 8 13:23 LPhs_BrahMP.vcf (from longphase haplotag: Illumina PE reads)

And, the bcftools consensus requires a vcf file. 
bcftools consensus -i -s NA001 -f in.fa in.vcf.gz > out.fa

Q1: Does bcftools accept both phased vcf files (SNP and SV) or only a single vcf file? Is there any alternative way I can use both phased vcf files?

Q2: Can I use for dipplod option as the below?
bcftools consensus -i -s NA001 -f in.fa in.vcf.gz 1 R > out1.fa (Primary)
bcftools consensus -i -s NA001 -f in.fa in.vcf.gz 2 A > out2.fa (Alternative)

Q3: Is there any option that I can use the LPhs_BrahMP_Result.bam (phased.bam from LongPhase)?

Looking forward to your reply!

Thanks.

**Comment by pd3** [comment]
Hi,

A1: the program accepts only one VCF file on input. You'd have to merge the files first into one VCF, e.g. using `bcftools merge`

A2: the command line you are showing would not work. The switch `-i` requires an argument and not sure what you are trying to do with `1 R` and `1 A`. If you run the program without arguments  (`bcftools consensus`), it will print a usage page. Maybe you were trying to do `bcftools consensus -H 1 -s NA001 -f in.fa in.vcf.gz` and `.. -H 2 ..` instead?

A3: the program does not work with alignment files (bam)
