### ISSUE TITLE
bcftools annotate does not add new field to INFO

### ISSUE THREAD

**Issue by TedBrookings** [samtools/bcftools#1733]
I've run into what looks like a regression introduced in release 1.14 (our scripts work for 1.13 and earlier, and fail for 1.14 and later). But possibly the method of invoking `bcftools annotate` has changed?
I'm attempting to use a tab-delimited annotation file to add a field to `INFO`. The original task uses more of `annotate`'s capabilities, but I've made a stripped down small data set and simple command (e.g. the supplied VCF already has the new field in the header). I attached a zip file with the VCF, annotations file, and its index. This is the command:
<code>
bcftools annotate -a evidence_annotations.tab.gz -c CHROM,POS,REF,ALT,EVIDENCE test.vcf.gz
</code>
Versions 1.13 and earlier add `EVIDENCE` to `INFO`, and versions 1.14 and later don't.
[test_files.tar.gz](https://github.com/samtools/bcftools/files/8870758/test_files.tar.gz)

**Comment by pd3** [comment]
This is now fixed, thank you for the bug report and for the test case. Please let me know if you spot anything odd.
