### ISSUE TITLE
Problems filtering based on the TGP `INFO/VT`

### ISSUE THREAD

**Issue by David-Peede** [samtools/bcftools#1737]
Hello, 

I am trying the filter the phase three release of the 1000 genomes project using the `INFO/VT` field (listed below), but am having some trouble.

> ##INFO=<ID=VT,Number=.,Type=String,Description="indicates what type of variant the line represents">

Here is the code I am running on each chromosome (which the VCF files were downloaded from here http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/):
`for CHR in {1..22}; do
sbatch -J ${CHR}_tgp_filter -N 1 -n 4 -t 1:00:00 --mem=2G -o logs/${CHR}_tgp_filter-%A.out -e logs/${CHR}_tgp_filter-%A.err --mail-type=ALL --mail-user=david_peede@brown.edu --wrap="module load bcftools/1.13 gsl/2.5 gcc/8.3 perl/5.24.1; bcftools view -m2 -M2 -i 'INFO/VT="SNP"' -Oz -o tgp_biallelic_snps_chr${CHR}.vcf.gz /users/dpeede/data/data/modern_genomes/1000genomes/ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr${CHR}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
done`

and here is the error message I am getting:
> [filter.c:2887 filters_init1] Error: the tag "SNP" is not defined in the VCF header

I imagine the issue is arising because of the `Number=.` part of the `INFO` field entry that allows for any arbitrary value, but am unsure how to fix it.

**Comment by pd3** [comment]
This has nothing to do with bcftools but with the way you are submitting your job, notice the incorrect use of embedded quotes. If you run the same command directly on the command line it will work, but what you are passing to bcftools is `... -i'INFO/VT=SNP'` instead of `... -i'INFO/VT="SNP"'`

**Comment by David-Peede** [comment]
Ahhh I see, sorry for the trivial mix-up, and thanks for the help!
