### ISSUE TITLE
Understanding consistant sites for +Mendelian plugin

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#1738]
Hi,

While using the +Mendellian plugin in bcftools v1.14 using the following command: `bcftools +mendelian -m + --trio Mother,Father,Proband input_GQ20_snpeff.vcf -O v -o output_GQ20_snpeff.vcf`, I am getting sites such as (only put a few examples here):

GTs: ./. 0/1 0/1
GTs: 0/1 ./. 0/0
GTs: ./. ./. 0/0
GTs: 0/0 ./. 0/1
GTs: 1/1 ./. 0/1
GTs: ./. ./. 0/1

Why do these sites come up? A straigtforward solution is to remove any sites that has missing in them and I am already doing that. But, I just wanted to understand the logic behind selecting these sites as Mendelian consistant sites. If I could pointed towards the correct script where the Mendellian condition is applied, that would be great. 

Regards,
Prasun

**Comment by prasundutta87** [comment]
Any update on this query?

**Comment by pd3** [comment]
Hi, sorry for the delay about this.

The code as it is currently written does not allow to distinguishes well between genotypes that are 'consistent' and have 'missing information but are not inconsistent'. I want to create a new version of the plugin that takes these nuances into account. The usage would look like this
```
-m, --mode [+acdeEgmM]   Output mode, the default is `-m c`. Multiple modes can be combined, drop modes
                         take precedence
                             a .. add INFO/MERR annotation with the number of inconsistent trios
                             c .. print counts, a text summary with the number of errors per trio
                             d .. delete genotypes in inconsistent trios (set to "./.")
                             e .. list sites with at least one erroneous trio
                             E .. drop sites with at least one erroneous trio
                             g .. list sites with at least one good trio (i.e. non-missing and consistent)
                             m .. list sites with missing genotypes in at least one trio
                             M .. drop sites with missing genotypes in at least one trio
```
Also the output format would change to list counts for these various cases. Can you please let me know if this would cover your request, here and in #1729?

**Comment by prasundutta87** [comment]
Hi @pd3 , 

Thanks a lot for this. It covers both my requests. Thanks a lot!

Regards,
Prasun

**Comment by prasundutta87** [comment]
Thanks a lot @pd3. Has it by any chance updated in the latest version? I use conda, but will try to install a specific version if required.

**Comment by pd3** [comment]
No, this is not in a versioned release yet. You'll need to compile from source. But that is not difficult
http://samtools.github.io/bcftools/howtos/install.html

**Comment by prasundutta87** [comment]
Great! Thanks a lot for sharing this link @pd3 !!

**Comment by prasundutta87** [comment]
Hi @pd3! Thank you so much for the updated plugin and sorry for getting back so late. I became busy with some other work. I have now tested the tool and works perfectly in two example trios I tried it on. There was another trio where the sum of ngood, nmerr and nfail is not equal to the total number of variants (SVs in my case) in the input VCF file. I am trying to find out where are the extra variants coming from. 

 Its trivial, but naming erroneous sites as inconsistant can be helpful, just becasue the good sites are called consistant.

I think overall the new functionality is extremely helpful, and does help in reducing downstream steps to get the desired output. Thanks a lot for this!

**Comment by pd3** [comment]
Let me know if you can find out the reason for the apparent count inconsistency. Could it be because multiple trios in the file happen to increment several counters simultaneously?

I prefer to leave the naming as is because "consistent" can refer to complete trios as well as to trios with partially missing genotypes.
