### ISSUE TITLE
bcftools +fixref -- -m ref-alt -d [Enhancement]

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1743]
I am trying to use the +fixref plugin to fix a VCF after a liftOver operation. I have two issues.

The first issue relates to the following code:
```
    else if ( args.mode==MODE_REF_ALT ) // only change the REF/ALT column, leave the genotypes as is
    {
        if ( ir==ia ) return ret;
        if ( ir==ib ) { args.nswap++; return set_ref_alt(&args,rec,int2nt(ib),int2nt(ia),0); }
        if ( ir==revint(ia) ) { args.nflip++; return set_ref_alt(&args,rec,int2nt(revint(ia)),int2nt(revint(ib)),0); }
        if ( ir==revint(ib) ) { args.nflip_swap++; return set_ref_alt(&args,rec,int2nt(revint(ib)),int2nt(revint(ia)),0); }
        error("FIXME: this should not happen %s:%"PRId64"\n", bcf_seqname(args.hdr,rec),(int64_t) rec->pos+1);
    }
```
puzzles me as I do not want to alleles to be flipped, only swapped. Second, in the case of some rare A/T and C/G SNPs, none of the above conditions is satisfied but even if I use the `--discard` option, the program still fails rather than discarding a site that could not be resolved.

The second issue relates to the fact that when a swapping occurs, I want some INFO or FORMAT fields to change. I don't expect +fixref to understand what I want to change, but since I don't know what variants were swapped, it becomes impossible to make the change after running the plugin. It would be useful if +fixref had an option to add an INFO field recording what change was made (none, swap, flip, flip+swap) or two binary info fields (for swap and flip).

**Comment by pd3** [comment]
Mmm, the naming is not the best. The difference between the 'flip' and 'ref' modes is mostly that the first modifies the genotypes while the latter only REF+ALT columns. I am happy to rename and possibly add additional modes if good testing data is provided. The current modes come from documented cases where the reason for the discrepancies was understood.

**Comment by freeseek** [comment]
I think the `ref-alt` mode should only swap and not `flip` the alleles. If the current behavior needs to be preserved, then maybe a `swap` mode could be added that only swaps alleles. The use case I have in mind here for keeping a record of which alleles were swapped (and flipped) is when the user would want to liftOver [GWAS-VCF](https://github.com/MRCIEU/gwas-vcf-specification) summary statistics files from GRCh37 to GRCh38. Some alleles needs to be swapped after a liftOver operation as different references do not need to match at common SNPs. It is great that `+fixref` also swaps the genotypes, but sometimes other INFO/FORMAT fields fields need to be addressed. In the case of GWAS-VCF the `ES` FORMAT field also needs to change sign when a swap occurs. Rather than having `+fixref` provide a general framework for modifying INFO/FORMAT fields after a swap, it would be helpful to know which markers were swapped and allow the user to modify the output VCF manually using that information.

**Comment by pd3** [comment]
This is now added: the new mode `-m swap` and the `INFO/FIXREF` annotation describing what has changed. Please let me know if you spot any problems.
