### ISSUE TITLE
bcftools filter soft-filter overwrites the FILTER field instead of adding one.

### ISSUE THREAD

**Issue by yangyxt** [samtools/bcftools#1749]
I tried the bcftools filter with -s "STRING" argument. But the STRING entirely overwrites the FILTER field, instead of adding a FILTER tag. Pls consider making this function.

**Comment by pd3** [comment]
There is the option `-m`, have you tried running with `-m +`?
```
-m, --mode [+x]                "+": do not replace but add to existing FILTER; "x": reset filters at sites which pass
```
