### ISSUE TITLE
vcf2sex bad call

### ISSUE THREAD

**Issue by boboppie** [samtools/bcftools#175]
Dear Petr,

We have tried to run vcf2sex on my VCFs using -g and -n respectively. The genders of all samples are known. We compare the results with our genders, quite a few of them don't match. We also notice that if we set -n > 500 (roughly), all samples will be called F, < 500, all called M. Could you please share some ideas?     

``` bash
% bcftools +vcf2sex sample1.vcf.gz -- -n 500
```

Bw,
Fengyuan

**Comment by iiiir** [comment]
i always get M, regardless what are the command i used. e.g. for the genome in a bottle variant call of NA12878 (as well as all members of my in-house variant call for NA12878 trio):
$ bcftools +vcf2sex NA12878_GiaB_NIST_RTG_v0_2.hg19.vcf.gz
NA12878 M
$ bcftools +vcf2sex NA12878_GiaB_NIST_RTG_v0_2.hg19.vcf.gz -- -n 5000
NA12878 M
$ bcftools +vcf2sex NA12878_GiaB_NIST_RTG_v0_2.hg19.vcf.gz -- -vg
# [1]DBG        [2]Region       [3]Sample       [4]HET fraction [5]nHet [6]nHom [7]nMissing
NA12878 M       0.500000

**Comment by pd3** [comment]
It works for me:

    $bt +vcf2sex NIST_RTG_PlatGen_merged_highconfidence_v0.2_Allannotate.vcf.gz -- -vn 2
    X:53797835    NA12878  ploidy=2
    X:104187228   NA12878  ploidy=2
    NA12878	F	1.000000

It looks like your VCF does not give enough clues to determine the sex. Can you show the output of

    bcftools +vcf2sex file.vcf.gz -- -v

and the genotypes at those sites? For example:

    bcftools query -f '%CHROM %POS [ %GT]\n' -r X:104187228 file.vcf.gz

**Comment by iiiir** [comment]
Thanks for the reply and I apologize for the delay response.

It *works* for GRCh37 based VCF files:
$ bcftools +vcf2sex ../../../GIAB/GiaB_NIST_RTG_v0_2.vcf.gz -- -vn 2
X:53797835      NA12878 ploidy=2
X:104187228     NA12878 ploidy=2
NA12878 F       1.000000

but *fails* for hg19 based VCFs:
$ bcftools +vcf2sex NA12878_GiaB_NIST_RTG_v0_2.hg19.vcf.gz -- -vn 2
NA12878 M       0.500000
$ bcftools +vcf2sex NA12878_plantinum_v0.7.vcf.gz -- -v
NA12878 M       0.500000

Is this a bug?

Thanks,

Shuoguo

**Comment by pd3** [comment]
No, it is not a bug. You'll need to supply hg19 version of `--ploidy`.
