### ISSUE TITLE
NS, AC, AN and AF provided by bcftools (plugin fill-tags) in VCF file

### ISSUE THREAD

**Issue by NextGenBioinformatics** [samtools/bcftools#1758]
Hi there,

I am working with some VCF files with some tags in the INFO provided by bcftools (plugin fill-tags).

I was wondering if you could help me understand how the values of NS, AC, AN and AF are calculated by bcftools (plugin fill-tags) please?

1) Does NS (number of samples with data) refer to the number of samples with genotype "0/1" or "1/1"?

2) Does AC (allele count in genotypes) refer to the number of "1" in the genotypes "0/1" and "1/1"?

3) Does AN (total number of alleles in called genotypes) refer to the number of "0" and "1" in all three genotypes namely "0/0", "0/1" and "1/1"?

4) Should be AF (allele frequency) calculated as AF = AC/AN where AC is allele count in genotypes and AN is total number of alleles in called genotypes? Or should another formula used AF=AC/(number of samples 2)? Usually AN is not equal to (number of samples 2) due to missing alleles in the GT field.

5) I see some INFO tags in VCF files generated by bcftools (plugin fill-tags) where AF=AC/(number of samples * 2) rather than AF = AC/AN is used? why is that? In addition, NS and AN provided by bcftools (plugin fill-tags) seem not using the above-mentioned definitions if I look at the genotypes manually?

Many thanks,

Kind regards,

Tom

**Comment by pd3** [comment]
1. The number of samples with data means literally that, i.e. all samples with non-missing genotypes, including 0/0 (but not ./.)
2. For each ALT allele AC contains their count. For example, the genotype 1/2 would result in AC=1,1
3. I am guessing your question is really about terminology. The answer is yes, for example two genotypes "0/1"  and "0" consist of three alleles so AN=3 in this case
4. AF refers to the allele frequency in the population or, more narrowly, in the VCF. So AF=AC/AN. These two pairs of genotypes 0/0 + 1/1 and 0/1 + 0/1 will generate the same AF=0.5
5. I believe you are wrong, the plugin calculates AF=AC/AN 

Please refer also to the VCF specification http://samtools.github.io/hts-specs/VCFv4.3.pdf
