### ISSUE TITLE
Test case `fill-tags  -t 'FORMAT/DP:1=int(smpl_sum(FMT/AD))'` fails on ARM

### ISSUE THREAD

**Issue by jmarshall** [samtools/bcftools#1759]
Running `make test` on an ARM platform produces the following test failure (twice):

```
test_vcf_plugin:
    /home/johnm/bcftools/bcftools +fill-tags --no-version /tmp/…/fill-tags-AD.vcf.gz -- \
        -t 'FORMAT/DP:1=int(smpl_sum(FMT/AD))' | grep -v ^##bcftools_

    The outputs differ:
	/home/johnm/bcftools/test/fill-tags-AD.3.out
	/home/johnm/bcftools/test/fill-tags-AD.3.out.new

9c9
< chr1	10153	.	AC	A	.	.	AD=3,1	AD:DP	10,1:11	.:.	.:.
---
> chr1	10153	.	AC	A	.	.	AD=3,1	AD:DP	10,1:11	.:0	.:0
```

The difference comes down to this float to int conversion:

https://github.com/samtools/bcftools/blob/435d80bfc8a31fd78298f084a6ffd0143166d5fd/plugins/fill-tags.c#L324

For the `.`/`0` fields in question, `src[j]` is a NAN. ~~I am not sure what flavour of NAN, other than that it is neither `bcf_float_missing` nor `bcf_float_vector_end` — so it is probably an actual arithmetic NAN from whatever calculations are involved in `int(smpl_sum(…))`.~~

* On x86-64, `dst[j]` receives the value -2147483648 from casting this NAN, which is printed as MISSING
* On aarch64, `dst[j]` receives the value 0 from casting this NAN, which is printed as a literal zero

This code should handle NANs more carefully; perhaps the `smpl_sum(…)` method needs to special case an empty sample or similar as `bcf_float_missing`, and the _fill-tags.c_ code needs to translate `bcf_float_missing` to `bcf_int32_missing` specially and only use the cast on finite values.

**Comment by jmarshall** [comment]
Hmmm… turns out `func_smpl_sum()` **is** setting it as missing (via `bcf_double_set_missing()`), so the _fill_tags.c_ code needs to check for `bcf_double_is_missing_or_vector_end()`.

**Comment by junaruga** [comment]
Just note. Here is the actual commit on the develop branch.
https://github.com/samtools/bcftools/commit/0676ccfb710778129f0337aa4ea3fa014f7c97fb
