### ISSUE TITLE
no depth distribution

### ISSUE THREAD

**Issue by fersall** [samtools/bcftools#1761]
I am running this command `bcftools stats -d 1,10000, 1 data.bcf > data_dp`. It works as normal and it produces the output but when I inspect the output file it contains all statistics but depth information. It only has the headers "DP, Depth distribution"

**Comment by pd3** [comment]
Does the file contain the INFO/DP tag?

**Comment by SusiJo** [comment]
Hi there,
We are working on a pipeline and having a similar issue: We are using `bcftools stats` on WES/WGS `vcf` files and it's not reporting any depth distribution values even though the DP field exists in the vcf file (within the FORMAT tag).
The only way to make bcftools report something is by using `-s-`.  Is this how this is supposed to work?
When using the parameter `--depth INT,INT,INT` we also do not get any depth distribution values. 
Could you explain a bit more in detail how this parameter is working and what it depends on or if we are not using this the right way?

**Comment by pd3** [comment]
Ah yeah, this is a bit counterintuitive and would benefit from improvements of the code, or the documentation at least. 

What is happening is that by default the program avoids parsing of sample fields and collects just summary stats. That's for speed, parsing VCFs with many samples is expensive. The `-s -` option needs to be present to parse samples as well. This is counterintuitive, but when this was pointed out for the first time, it was already too late to change the default. 

Now when the INFO/DP is not present and FMT/DP is not parsed, the program cannot collect the depth distribution.
