### ISSUE TITLE
bcftools call PL/GT mismatch

### ISSUE THREAD

**Issue by lexflagelgencove** [samtools/bcftools#1765]
We see strange output from `bcftools call` in certain contexts where the PL doesn't match GT. E.g.:

```
GT:PL	0/0:31,0,31
```

Attached is a small showcase that will produce the example above from a low coverage copy of the human 1000 genome project sample HG00404. After unzipping the source code below run:

`./1.produce.PL.GT.mismatch.sh`

This is a site with 2x coverage, one read matching ref and one alt, and the PL (`31,0,31`) favors het, but the GT field comes out `0/0`, which is unexpected given the PL. 

These results were produced using bcftools 1.15.1 (with htslib 1.15.1).

[bcftools-call-PL-missmatch-GT-bug-showcase.zip](https://github.com/samtools/bcftools/files/9223230/bcftools-call-PL-missmatch-GT-bug-showcase.zip)

**Comment by lexflagelgencove** [comment]
@pd3 can perhaps comment if this is expected behavior.

**Comment by pd3** [comment]
One supporting read is usually not enough to make a confident call, variant calling is a compromise between sensitivity and specificity. One can make the calling more sensitive by increasing the `-P` prior. For example, the heterozygous genotype from your example will be recovered with `bcftools call -P 0.005`
