### ISSUE TITLE
output BCFtools mpileup gives abnormal values

### ISSUE THREAD

**Issue by GeertsManon** [samtools/bcftools#1767]
Hi, 

I have run bcftools mpileup on a list of bam files (n = 27) and the output is really weird. 
It gives something like this: 

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	KEA001	KEA003	KEA004	KEA005	KEA006
?uP     C7<*>!!!!
%                ?
 1A!!!!?uQ      C7<*>!!!!
%                        ?
 1A!!!!?uR      C7<*>!!!!
%                        ?
 1A!!!!?uS      C7<*>!!!!
%                        ?
 1A!!!!?uT      C7<*>!!!!
%                        ?
 1A!!!!?uU      C7<*>!!!!

This is happening when I'm using the full list of bam files but also on single individuals. Also when removing the '-r CHR' I get this weird output. I have run samtools check on all my bam files and seems ok. I have worked with bcftools mpileup quite a lot already. This is the first time I see this. Any idea what is going wrong? 
I have put my script in attachement. 

Thanks in advance for the feedback!

[mpileup.atools.txt](https://github.com/samtools/bcftools/files/9240672/mpileup.atools.txt)
t

**Comment by jkbonfield** [comment]
Is that really what it gives you, or have you processed it in some way (I don't see how mpileup could omit chr, pos, etc fields)?  It wasn't clear from your script as you seem to be going on to calling, so obviously this isn't the final output from that.

If it's failing on single individual files, then try just a single SAM record to see if you can narrow it down.  It may be something obvious in the SAM data itself, such of out-of-range quality values.  We'd need to see a record basically - you can change all the identifying fields such as names and sequence, as this looks to be a quality value thing.

**Comment by GeertsManon** [comment]
Thanks for the quick reply!
I had a look at the cigar string of my soft clipped SAM file and I saw this

samtools view nDNA/KEA001.markdup.filtered.bam | awk '{ print $7 }' | sort | uniq -c
88952574 =
      1 CM044232.1
      2 CM044239.1
      1 CM044243.1
      1 CM044245.1
      1 CM044246.1
      1 CM044251.1
      1 CM044256.1
      2 CM044257.1
      3 JAMBPB010000031.1

For some reason, something wrong is happening here and I suppose this the cause of the error. But why this happens, is still unclear to me. I will try to figure it out. 
Thank again!

**Comment by GeertsManon** [comment]
Thanks for the quick reply!

I've tested it on just two SAM records and I got the same output. 
I've converted the two SAM records into text file and added it as attachement. 
Anything that looks suspicious to you? 

[KEA001.nDNA.head.txt](https://github.com/samtools/bcftools/files/9241340/KEA001.nDNA.head.txt)

**Comment by jkbonfield** [comment]
I added 2 lines of SQ header and `bcftools mpileup` gives me meaningful output.

```
$ cat _.sam
@SQ	SN:CM044232.1	LN:10000
@SQ	SN:CM044251.1	LN:10000
E100042608L1C041R04000939695	2211	CM044232.1	81	21	114H36M	CM044251.1	1987128	0	CCCCCCCCCCAACCCCCACCCCCCCCCCCCACCCCC	FDFFF+F<FE7:::@CF0FCDFE;E7C-3E*?40E)	SA:Z:CM044251.1,1987084,+,131M19S,60,1;	XA:Z:CM044232.1,+296,114S36M,2;CM044232.1,+180,125S25M,0;CM044249.1,+28216469,125S25M,0;	MC:Z:94M2D56M	MD:Z:10C25	PG:Z:MarkDuplicates	RG:Z:E100042608L01	NM:i:1	AS:i:31	XS:i:26
E100042608L1C013R00602420277	83	CM044232.1	7283	28	7M1D143M	=	7291	-143	ACCCTAACCTAACCCTAACCCTAGGATATCGTTGGGTTAAGGGGAACTTTAATCTTAGCTCATACCCTTAACCTTAAATAGAATTTAATGCGTTTCCTCTCCCTGAACCTAAACATAACCTTCAGTGTCTTCAGCTGCTTATCAAAAACT	GGGGGGGGGGGGGGGGGGGGGFHGGGGGGGGGGGGGGGHGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGIGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG	MC:Z:42S108M	MD:Z:7^C33A109	PG:Z:MarkDuplicates	RG:Z:E100042608L01	NM:i:2	AS:i:138	XS:i:124

$ cat _.fa
>CM044232.1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
CCCCACCCCCATCCCCCACCCCCCCCCCCCACCCCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

$ bcftools mpileup --fasta-ref _.fa -a "FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,INFO/AD,INFO/ADF,INFO/ADR,FORMAT/DV,FORMAT/DP4,FORMAT/DPR,INFO/DPR" -Q15 _.sam|egrep -A6 '^#CHROM'
[warning] tag DV functional, but deprecated. Please switch to `AD` in future.
[warning] tag DP4 functional, but deprecated. Please switch to `ADF` and `ADR` in future.
[warning] tag DPR functional, but deprecated. Please switch to `AD` in future.
[warning] tag INFO/DPR functional, but deprecated. Please switch to `INFO/AD` in future.
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
[mplp_func] Skipping because 7282 is outside of 240 [ref:0]
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	_.sam
CM044232.1	81	.	C	<*>	0	.	DP=1;ADF=1,0;ADR=0,0;AD=1,0;DPR=1,0;I16=1,0,0,0,37,1369,0,0,21,441,0,0,0,0,0,0;QS=1,0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	0,3,21:1:0:0:1,0,0,0:1,0:0,0:1,0:1,0
CM044232.1	82	.	C	<*>	0	.	DP=1;ADF=1,0;ADR=0,0;AD=1,0;DPR=1,0;I16=1,0,0,0,35,1225,0,0,21,441,0,0,1,1,0,0;QS=1,0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	0,3,21:1:0:0:1,0,0,0:1,0:0,0:1,0:1,0
CM044232.1	83	.	C	<*>	0	.	DP=1;ADF=1,0;ADR=0,0;AD=1,0;DPR=1,0;I16=1,0,0,0,37,1369,0,0,21,441,0,0,2,4,0,0;QS=1,0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	0,3,21:1:0:0:1,0,0,0:1,0:0,0:1,0:1,0
CM044232.1	84	.	C	<*>	0	.	DP=1;ADF=1,0;ADR=0,0;AD=1,0;DPR=1,0;I16=1,0,0,0,37,1369,0,0,21,441,0,0,3,9,0,0;QS=1,0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	0,3,21:1:0:0:1,0,0,0:1,0:0,0:1,0:1,0
CM044232.1	85	.	A	C,<*>	0	.	DP=1;ADF=0,1,0;ADR=0,0,0;AD=0,1,0;DPR=0,1,0;I16=0,0,1,0,0,0,37,1369,0,0,21,441,0,0,4,16;QS=0,1,0;SGB=-0.379885;FS=0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	21,3,0,21,3,21:1:1:0:0,0,1,0:0,1,0:0,0,0:0,1,0:0,1,0
CM044232.1	86	.	C	<*>	0	.	DP=1;ADF=0,0;ADR=0,0;AD=0,0;DPR=0,0;I16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;QS=0,0;MQ0F=0	PL:DP:DV:SP:DP4:ADF:ADR:AD:DPR	0,0,0:0:0:0:0,0,0,0:0,0:0,0:0,0:0,0
```

Piping this into `bcftools call` doesn't generate anything meaningful as the depth is too low to call, but I also note you have an error in your script:

`bcftools call --threads 36 -mv -V indels -Ob -f GQ -o $prefix.combined/Cg.$tool.$CHROMOSOME.called.SNP.vcf.gz $prefix.combined/Cg.$tool.$CHROMOSOME.vcf.gz`

When I run this I get:

```
Unknown skip category "-f" (-S argument must be "snps" or "indels")
```

You need to pay close attention to the mesages being reported by the tools, and quote them here when reporting errors.

**Comment by GeertsManon** [comment]
Jup, found my mistake. 
used -Ob instead of -Oz. 
Sorry. 
Thanks anyway!
