### ISSUE TITLE
bcftool failed with Strelka vcf format

### ISSUE THREAD

**Issue by lmanchon** [samtools/bcftools#1769]
I used Strelka Workflow to call variants and i have 2 files: somatic.snvs.vcf.gz and somatic.indels.vcf.gz
then i want to add some fieds and it failed with:

bcftools +fill-tags somatic.snvs.vcf.gz -Oz -o test.vcf.gz -- -t AF,AN,AC,AC_Hom,AC_Het,VAF,NS
Could not read FORMAT/AD annotation at chr1:3682336

i use bcftools-1.14
thank you --

**Comment by pd3** [comment]
The FORMAT/AD tag is required to create the VAF annotation. The error has been now turned into a warning and the message made more informative. Thank you for the report.
