### ISSUE TITLE
bcftools norm parameters

### ISSUE THREAD

**Issue by NextGenBioinformatics** [samtools/bcftools#1774]
Hello,

I wonder if "bcftools norm -m -any" is functionally equivalent to
"bcftools norm -m -both" in terms of splitting multiallelic sites into
biallelic records please?

If not, what is the difference?

Many thanks

**Comment by pd3** [comment]
It should not make any difference for splitting I believe, only for the inverse operation of merging. There the former allows to combine snv with indel variants while the latter only snvs with snvs and indels with indels.
