### ISSUE TITLE
i686: 2 failures on v1.15.1

### ISSUE THREAD

**Issue by junaruga** [samtools/bcftools#1776]
I got 2 failures on the bcftools version 1.15.1 with htslib 1.15.1 and gcc 12.1.1 on Fedora 38 (Fedora rawhide) i686 (Intel 32-bit) CPU.

```
+ ./configure --build=i686-redhat-linux-gnu --host=i686-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/bcftools-1.15.1/.package_note-bcftools-1.15.1-1.fc38.i386.ld' --prefix=/usr --with-htslib=system --enable-perl-filters --enable-libgsl '--with-bcf-plugin-path=/usr/local/libexec/bcftools:$(plugindir)'
...
+ /usr/bin/make -O -j2 V=1 VERBOSE=1
...
+ make test
...
test_vcf_convert_hs2vcf:
	/builddir/build/BUILD/bcftools-1.15.1/bcftools convert --3N6 -G /builddir/build/BUILD/bcftools-1.15.1/test/convert.gs.gt.ids.3N6.gen,/builddir/build/BUILD/bcftools-1.15.1/test/convert.gs.gt.samples | grep -v ^##
	Non-zero status 1
.. failed ...
test_vcf_convert_hs2vcf:
	/builddir/build/BUILD/bcftools-1.15.1/bcftools convert --3N6 -G /builddir/build/BUILD/bcftools-1.15.1/test/convert.gs.gt.ids.3N6.gen,/builddir/build/BUILD/bcftools-1.15.1/test/convert.gs.gt.samples -Ou | /builddir/build/BUILD/bcftools-1.15.1/bcftools view | grep -v ^##
	Non-zero status 1
		Failed to read from standard input: unknown file type
		
.. failed ...
```

**Comment by daviesrob** [comment]
Does Fedora still support i686?  I couldn't find any sign of Fedora images for that platform.

Anyway, I managed to reproduce this on a VM running i686 Debian.  The very small patch in #1777 should fix it.

**Comment by junaruga** [comment]
> Does Fedora still support i686? I couldn't find any sign of Fedora images for that platform.

I don't see i686 on the Fedora container (docker) images now.
https://registry.fedoraproject.org/repo/fedora/tags/

However the i686 is still one of the CPU architectures in Fedora's building system. You can see it below. That's why I found the issue, and reported here.
https://koji.fedoraproject.org/koji/buildinfo?buildID=2047278

However [on our mailing list 1 week ago](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/EWA372NELEK45KGZ4AJO5GTX7IFAU5W4/#EWA372NELEK45KGZ4AJO5GTX7IFAU5W4) I found that Fedora is working in a process not to support i686 according to the change document below. Here is the [change document](https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
).

> Anyway, I managed to reproduce this on a VM running i686 Debian. The very small patch in https://github.com/samtools/bcftools/pull/1777 should fix it.

Thanks!
