### ISSUE TITLE
Keep FILTER column values for each sample when merging vcfs

### ISSUE THREAD

**Issue by Biojenifer** [samtools/bcftools#1779]
Hi!

I was wondering if it is possible to keep all FILTER column values when merging several vcfs. As an example, when merging these vcfs:

```
sampleA.vcf:

1       1786381 .       C       T       .       clustered_events;haplotype;orientation

sampleB.vcf

1       1786381 .       C       T       .      germline

sampleC.vcf

1       1786381 .       C       T       .       PASS
```

I would expect something like this:

```
merged.vcf

1       1786381 .       C       T       .       clustered_events;haplotype;orientation;germline;PASS
```

Do you know how can I achieve it?
Thanks!

**Comment by pd3** [comment]
This is the default behavior, except PASS cannot be combined with other filters. It's always `PASS`, `.` or something else.
If you need to indicate PASS somehow, you'd have to use a substitute filter name.
