### ISSUE TITLE
Bcftools isec GT aware

### ISSUE THREAD

**Issue by Rashesh7** [samtools/bcftools#1782]
Hello,

Is there a way to run bcftools isec with taking genotypes into consideration?
I want to compare multiple VCF files and check even in the same variant call, how many have a shift from heterozygous to homozygous. 

I am running "bcftools isec -p Unique -n-1 -c none $FILE1 $FILE2 $FILE3 ...."  currently. But it just checks for the exact Alt allele. I know vcf-compare has an option for comparing genotypes "--cmp-genotypes ". Is there something similar that I can use? 

Many Thanks,
Rashesh

**Comment by pd3** [comment]
I wonder if the `GTisec` or `GTsubset` plugins would help. I did not write these so can't really tell.
