### ISSUE TITLE
-i and -e are not complement when I use query subcommand

### ISSUE THREAD

**Issue by takosa** [samtools/bcftools#1783]
I noticed the result of

`bcftools query -i 'FMT/DP>=20' -f '[%CHROM %POS %SAMPLE\n]'  input.vcf`

and 

`bcftools query -e 'FMT/DP<20' -f '[%CHROM %POS %SAMPLE\n]'  input.vcf`

are not complement.

This occur if only I specified %SAMPLE but %FORMAT tags, so I can avoid it by specifying other %FORMAT tags but it is a little inconvenient and confusing.

I think this is because the process is skipped by the code shown below when I use `-e` and the condition is met in some samples.
If only %SAMPLE is specified, not %FMT/DP, etc., the flag BCF_UN_FMT is not set. When I use `-i`, this checking and skipping do not occur.

https://github.com/samtools/bcftools/blob/12088c0887d2c680ae55240d806d089659d61dca/vcfquery.c#L146

The simple solutions I think is to omit the above code or to change the code below to set the flag.

https://github.com/samtools/bcftools/blob/12088c0887d2c680ae55240d806d089659d61dca/convert.c#L1304

However, I'm not sure how this change will affect the rest of the code.

Thank you,

**Comment by pd3** [comment]
Can you provide a specific example to demonstrate the behavior please?

**Comment by takosa** [comment]
I explain the issue by using this example vcf file named `input.vcf`.

```
##fileformat=VCFv4.1
##contig=<ID=1,assembly=test,length=100>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2
1	10	snp1	G	C	.	.	.	GT:DP	0/0:10	0/1:20
1	20	snp2	G	C	.	.	.	GT:DP	0/0:10	0/1:20
1	30	snp3	G	C	.	.	.	GT:DP	0/0:10	0/1:20
```

I ran `bcftools query` command and this is the outputs.

```
$ bcftools query -i 'FMT/DP>=20' -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample2
snp2 sample2
snp3 sample2
$ bcftools query -e 'FMT/DP<20'  -f '[%ID %SAMPLE\n]' input.vcf # no outputs
$ bcftools query -i 'FMT/DP<20'  -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample1
snp2 sample1
snp3 sample1
$ bcftools query -e 'FMT/DP>=20'  -f '[%ID %SAMPLE\n]' input.vcf # no outputs
```

However, I think the outputs should be like this.

```
$ bcftools query -i 'FMT/DP>=20' -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample2
snp2 sample2
snp3 sample2
$ bcftools query -e 'FMT/DP<20'  -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample2
snp2 sample2
snp3 sample2
$ bcftools query -i 'FMT/DP<20'  -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample1
snp2 sample1
snp3 sample1
$ bcftools query -e 'FMT/DP>=20'  -f '[%ID %SAMPLE\n]' input.vcf
snp1 sample1
snp2 sample1
snp3 sample1
```

In addition, if I add DP tag in my query, the outputs is like this. The number of rows are changed even though I don't change the filtering option.

```
$ bcftools query -e 'FMT/DP<20'  -f '[%ID %SAMPLE %DP\n]' input.vcf
snp1 sample2 20
snp2 sample2 20
snp3 sample2 20
```

Thank you for your consideration.

**Comment by pd3** [comment]
I see. It's probably an older version of bcftools, there were some bugs fixed over the time. The latest gives the expected output:
```
$ cat rmme.vcf
##fileformat=VCFv4.1
##contig=<ID=1,assembly=test,length=100>
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	smpl10	smpl20
1	10	.	G	C	.	.	.	DP	10	20

$ bcftools query -f '[%SAMPLE %DP\n]' rmme.vcf -i 'FMT/DP>=20' 
smpl20 20

$ bcftools query -f '[%SAMPLE %DP\n]' rmme.vcf -e 'FMT/DP>=20' 
smpl10 10

$ bcftools query -f '[%SAMPLE %DP\n]' rmme.vcf -e 'FMT/DP<20' 
smpl20 20

$ bcftools query -f '[%SAMPLE %DP\n]' rmme.vcf -i 'FMT/DP<20' 
smpl10 10

```

**Comment by takosa** [comment]
Thank you for your help.
I think I use latest version and outputs is like this.
I don't know, but something seems wrong...

```
$ cat rmme.vcf
##fileformat=VCFv4.1
##contig=<ID=1,assembly=test,length=100>
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	smpl10	smpl20
1	10	.	G	C	.	.	.	DP	10	20

$ bcftools --version
bcftools 1.16-6-gfd9470e
Using htslib 1.16-10-g6366029
Copyright (C) 2022 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ bcftools query -f '[%SAMPLE\n]' rmme.vcf -i 'FMT/DP>=20'
smpl20

$ bcftools query -f '[%SAMPLE\n]' rmme.vcf -e 'FMT/DP>=20'

$ bcftools query -f '[%SAMPLE\n]' rmme.vcf -e 'FMT/DP<20'

$ bcftools query -f '[%SAMPLE\n]' rmme.vcf -i 'FMT/DP<20'
smpl10
```

**Comment by pd3** [comment]
I was able to reproduce the problem now
```
$ bcftools query -f '[%SAMPLE %DP\n]' rmme.vcf -e 'FMT/DP>=20'
smpl10 10
$ bcftools query -f '[ %SAMPLE\n]' rmme.vcf -e 'FMT/DP>=20'
```

**Comment by pd3** [comment]
I believe the bug is now fixed by https://github.com/samtools/bcftools/commit/f4dee4bf7555b49fe4cc5be7f2f96fe526a49109
