### ISSUE TITLE
adding a custom FORMAT field; confusion about -s arg

### ISSUE THREAD

**Issue by stevekm** [samtools/bcftools#1784]
I am trying to add some custom FORMAT fields to a .vcf file, programmatically. 

There is a lot of documentation on how to add fields to a vcf with `bcftools`;

- [https://samtools.github.io/bcftools/howtos/annotate.html][1]
- [https://samtools.github.io/bcftools/bcftools.html#annotate][2]
- [https://github.com/samtools/bcftools/issues/810][3]

Based on some of the examples shown there, it seems that you can add a FORMAT field like this;

    # Create a test VCF
    VCF=test.vcf
    echo -e '##fileformat=VCFv4.2' > "${VCF}"
    echo -e '##INFO=<ID=DP,Number=1,Type=Integer,Description="Read depth">' >> "${VCF}"
    echo -e '##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic Depths of REF and ALT(s) in the order listed">' >> "${VCF}"
    echo -e '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">' >> "${VCF}"
    echo -e '##contig=<ID=1,length=248956422,assembly=hg38>' >> "${VCF}"
    echo -e '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsmpl1\tsmpl2' >> "${VCF}"
    echo -e '1\t16648016\t.\tG\t.\t.\t.\tDP=10\tGT:AD\t0/0:1\t0/0:1' >> "${VCF}"
    
    # pull off the header, add new header entry for field "FL_VF" that we want to add
    grep '##' "${VCF}" > header
    echo '##FORMAT=<ID=FL_VF,Number=1,Type=Float,Description="Variant frequence (AD/DP)">' >> header
    
    # create annotation table
    ANNOT_FLVF=annot.FLVF.txt
    printf '#CHROM\tPOS\tREF\tALT\tFL_VF\n' > "${ANNOT_FLVF}"
    bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t.\n' "${VCF}" >> "${ANNOT_FLVF}"
    bgzip -c "${ANNOT_FLVF}" > "${ANNOT_FLVF}".gz
    tabix -p vcf "${ANNOT_FLVF}".gz
    
    # looks like this;
    $ cat annot.FLVF.txt
    #CHROM  POS     REF     ALT     FL_VF
    1       16648016        G       .       .

    # apply the annotation to the original vcf
    VCF_FLVF=updated.FLVF.vcf
    bcftools annotate \
    --header-lines header \
    --annotations "${ANNOT_FLVF}".gz \
    -c CHROM,POS,REF,ALT,FORMAT/FL_VF \
    --output "${VCF_FLVF}" \
    --output-type v \
    -s smpl1 \
    "${VCF}"

    # output looks like this;
    $ grep -v '##' updated.FLVF.vcf | cut -f 9-
    FORMAT  smpl1   smpl2
    GT:AD:FL_VF     0/0:1:. 0/0:1:.

This works, and appears to give the desired output; adding the field `FL_VF` to the `FORMAT` column, and assigning a blank value of `.` for each sample.

However, my confusion comes from the requirement of using this arg: `-s smpl1`

The documentation for `bcftools` describes the "sample" args like this;

       -s, --samples [^]<list>        comma separated list of samples to annotate (or exclude with "^" prefix)
       -S, --samples-file [^]<file>   file of samples to annotate (or exclude with "^" prefix)

Based on this description, and since we are using a .vcf file with multiple samples, it would seem like you would either want to omit this arg, or use it with the full list of samples in the vcf. However neither of those actually works. If you omit `-s`, or use `-s smpl1,smpl2` instead, you get this error:

    Incorrect number of values for FL_VF at 1:16648016

The same applies for using the `-S` arg. 

My confusion stems from the requirement to include one sample, and only one sample, with the `-s` arg, in order to get the desired result. Is this some kind of bug? The error message of "`Incorrect number of values`" suggests that in the `bcftools query`, I should be outputting the `FL_VF` column with a different number of values, but I have tried different combinations of that as well and it still did not work. In this case, I am only adding a dummy value to all samples, so this works, but in future situations I might need to add a custom value for each sample in the new FORMAT field. It would be helpful to have a clear example of how to do something like that, since that situation seems to be mostly overlooked in the documentation as far as I can tell.

-----
Using 
```
bcftools --version
bcftools 1.9
Using htslib 1.9
```

  [1]: https://samtools.github.io/bcftools/howtos/annotate.html
  [2]: https://samtools.github.io/bcftools/bcftools.html#annotate
  [3]: https://github.com/samtools/bcftools/issues/810

**Comment by stevekm** [comment]
Also, another reason I think this should be considered a bug, is that it breaks programmatic .vcf updates. You should not be required to hard-code in one single sample ID from the source vcf file into the `bcftools` command for it to work. I want to integrate this method into an automated workflow, and now I have to come up with extra steps in order to introspect the vcf file and pull out one single sample ID, then pass it to `bcftools annotate`. 

The default behavior should be that, with `-s`/`-S` omitted, the FORMAT field should be output for all samples in the vcf.

**Comment by pd3** [comment]
I just tested with the most recent version of bcftools (1.16) and everything works as expected.

The `-s/-S` option is needed to indicate which samples should be annotated when there are multiple sample columns in the tab delimited file, just like in a VCF. (In principle this could be also used to enforce a specific order of samples if different from the order in the VCF, but I just checked the reordering is not currently supported, I'll open a separate issue for that.)

It is not true that it breaks programmatic VCF updates, one can easily generate a file with all samples using `bcftools query -l` and in the latest version 1.16 the `-s/-S` option is not needed.

**Comment by stevekm** [comment]
> It is not true that it breaks programmatic VCF updates, one can easily generate a file with all samples using bcftools query -l 

In my testing of this, it suffered from the same problem; if the samples list contained more than 1 sample, `bcftools annotat -S samples.txt ... ` breaks with the same error. Is that not the case on version 1.16?

**Comment by stevekm** [comment]
Also it appears that the latest version of `bcftools` on `conda` is 1.15? https://anaconda.org/bioconda/bcftools

**Comment by pd3** [comment]
The annotation file must have as many columns for that field as there are sample fields you're requesting to fill in, obviously.

Bioconda is not maintained by us, please see here how to install from the source http://samtools.github.io/bcftools/howtos/install.html. But there were no significant changes in `annotate` between versions 1.15 and 1.16.
