### ISSUE TITLE
bcftools query cannot accurately match the INFO tag sharing a common prefix with other INFO tags

### ISSUE THREAD

**Issue by yangyxt** [samtools/bcftools#1787]
I tried to run 
`bcftools query -f '%AC-controls_and_biobanks\n' <vcf>`
but failed to get the field "AC-controls_and_biobanks", Instead I get value from INFO field "AC" concatenated with "-controls_and_biobanks"

How can I deal with this Issue? To ask bcftools recognize the full pattern? 

Thanks!

**Comment by pd3** [comment]
The tag names cannot contain the minus sign `-`, so the program does not attempt to interpret the whole string as a tag name.
You may try to rename the annotation with `bcftools annotate --rename-annots`, although I am not 100% if it will work when the annotation is invalid.
