### ISSUE TITLE
cannot plot using bcftools stats output 

### ISSUE THREAD

**Issue by niantao** [samtools/bcftools#179]
Hi,

I have generated vchk file using bcftools stats, and then plot-vcfstats could recognise the format and gave me some error like this?

Can you please to see if you can help on this?

Thanks,
###### 

Plotting graphs: python plots/plot.py
  File "plots/plot.py", line 32
    if x.ndim != 1: raise ValueError, "smooth only accepts 1 dimension arrays."
                                    ^
SyntaxError: invalid syntax
The command exited with non-zero status 256:
    python plots/plot.py

 at bcftools/plot-vcfstats line 77
    main::error('The command exited with non-zero status 256:\x{a}\x{9}python plots/pl...') called at bcftools/plot-vcfstats line 270
    main::plot('HASH(0x912818)') called at bcftools/plot-vcfstats line 66
######

**Comment by amitgsir** [comment]
Hi,

I am trying to compare two vcf files (with Indel information)..

I generated the stats (file.stats) files using the two vcf files. But getting the error while using the plot-vcfstats to make the plots.

My problem looks similar to the above one, but have no idea how to correct it.

Pleas have a look.
Thanks.


amit@eonediag02:/data2/users/amit/Indel_Analysis/DongA_Exome_Data1/concordance$ /home/amit/Applications/bcftools-1.2/plot-vcfstats -p plots/ file.stats
Parsing bcftools stats output: file.stats
Plotting graphs: python plots/plot.py
Traceback (most recent call last):
  File "plots/plot.py", line 284, in <module>
    ax1.set_ylim(min(2,min(row[2] for row in dat))-0.3,0.3+max(2.2,max(row[2] for row in dat)))
ValueError: min() arg is an empty sequence
The command exited with non-zero status 256:
        python plots/plot.py

 at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 78.
        main::error("The command exited with non-zero status 256:\x{a}\x{9}python plots/pl"...) called at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 271
        main::plot(HASH(0xc98018)) called at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 67


Amit

**Comment by amitgsir** [comment]
Sorry, looks like this thread is closed.
I made a new issue.
