### ISSUE TITLE
Contigs issue

### ISSUE THREAD

**Issue by AndreaAguadoM** [samtools/bcftools#1792]
Hello! I am trying to use bcftools in order to merge some files that I am interested in. When trying to wxecute the following line: bcftools merge --no-index -m none -o output2/intermediate_output/merged.vcf -l output2/intermediate_output/merge_list.txt, I get the following error: 
[W::vcf_parse] Contig 'NC_045512.2' is not defined in the header. (Quick workaround: index the file with tabix.)
All my files were created using MN908947.3 as reference, and all the vcf files follow the following structure: 

##fileformat=VCFv4.2
##reference=MN908947.3
##source=iVar
##contig=<ID=MN908947.3,length=29903
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=REF_DP,Number=1,Type=Integer,Description="Depth of reference base">
##FORMAT=<ID=REF_RV,Number=1,Type=Integer,Description="Depth of reference base on reverse reads">
##FORMAT=<ID=REF_QUAL,Number=1,Type=Integer,Description="Mean quality of reference base">
##FORMAT=<ID=ALT_DP,Number=1,Type=Integer,Description="Depth of alternate base">
##FORMAT=<ID=ALT_RV,Number=1,Type=Integer,Description="Depth of alternate base on reverse reads">
##FORMAT=<ID=ALT_QUAL,Number=1,Type=Integer,Description="Mean quality of alternate base">
##FORMAT=<ID=ALT_FREQ,Number=1,Type=Float,Description="Frequency of alternate base">
##bcftools_filterVersion=1.14+htslib-1.14
##bcftools_filterCommand=filter --output AND01774.filtered.vcf.gz --output-type z --include 'FORMAT/ALT_FREQ >= 0.75' AND01774.vcf.gz; Date=Mon Aug 1 13:41:21 2022
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT AND01774
MN908947.3 241 . C T . PASS DP=1373 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:1373:741:35:1
MN908947.3 913 . C T . PASS DP=3389 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:4:2:35:3384:2022:35:0.998525
MN908947.3 3037 . C T . PASS DP=1697 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:1697:939:35:1
MN908947.3 3267 . C T . PASS DP=2391 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2:0:34:2389:854:35:0.999164
MN908947.3 4080 . G T . PASS DP=3815 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:3:2:36:3811:2125:35:0.998952
MN908947.3 5178 . C T . PASS DP=2782 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:4:2:35:2778:1734:35:0.998562
MN908947.3 5388 . C A . PASS DP=3786 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3786:1334:35:1
MN908947.3 5986 . C T . PASS DP=2102 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:2102:695:35:1
MN908947.3 6954 . T C . PASS DP=1678 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:1678:1030:35:1
MN908947.3 6968 . C T . PASS DP=1789 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:7:6:35:1782:1138:35:0.996087
MN908947.3 11287 . GTCTGGTTTT G . PASS DP=4069 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:4050:2553:35:3391:0:20:0.833374
MN908947.3 11296 . T G . PASS DP=302 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:302:153:35:1
MN908947.3 14408 . C T . PASS DP=3490 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:1:0:36:3489:1588:35:0.999713
MN908947.3 14676 . C T . PASS DP=3222 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:1:0:21:3221:1181:35:0.99969
MN908947.3 15279 . C T . PASS DP=3359 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3359:1379:35:1
MN908947.3 16176 . T C . PASS DP=4094 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2:1:36:4092:1942:35:0.999511
MN908947.3 16887 . C T . PASS DP=5490 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:14:6:35:5476:2210:35:0.99745
MN908947.3 21764 . ATACATG A . PASS DP=2061 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2043:860:35:1848:0:20:0.896652
MN908947.3 21990 . TTTA T . PASS DP=873 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:847:498:34:656:0:20:0.751432
MN908947.3 23063 . A T . PASS DP=678 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:678:409:35:1
MN908947.3 23271 . C A . PASS DP=3098 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3096:1296:35:0.999354
MN908947.3 23403 . A G . PASS DP=2889 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:2889:1770:35:1
MN908947.3 23604 . C A . PASS DP=2867 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:2867:1103:35:1
MN908947.3 23709 . C T . PASS DP=3149 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3148:1906:35:0.999682
MN908947.3 24506 . T G . PASS DP=2341 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:2341:876:35:1
MN908947.3 24914 . G C . PASS DP=3301 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3300:2017:35:0.999697
MN908947.3 27972 . C T . PASS DP=2786 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2:1:32:2784:1475:35:0.999282
MN908947.3 28048 . G T . PASS DP=2712 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:2712:1575:35:1
MN908947.3 28095 . A T . PASS DP=1933 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:25:12:35:1908:1144:35:0.987067
MN908947.3 28111 . A G . PASS DP=2282 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2:1:36:2280:1141:35:0.999124
MN908947.3 28270 . TA T . PASS DP=2258 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:2229:1083:35:1984:0:20:0.878654
MN908947.3 28280 . GAT CTA . PASS DP=1898 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:1898:991:35:1
MN908947.3 28881 . GG AA . PASS DP=521 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:521:303:35:1
MN908947.3 28883 . G C . PASS DP=541 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:541:307:35:1
MN908947.3 28977 . C T . PASS DP=569 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:569:356:35:1
MN908947.3 29589 . T C . PASS DP=3069 GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ 1:0:0:0:3069:1575:35:1

I do not know where my error is, so if someone could help me I would be really thankful!

**Comment by pd3** [comment]
The program gives an informative message, apparently there is a chromosome name in the VCF body ('NC_045512.2') which was not defined in the header. It also offers you a workaround: compress the files and index them. This can be done in two ways:
```
# 1
bgzip -c file.vcf > file.vcf.gz
tabix file.vcf.gz   

# 2
bcftools view -o file.vcf.gz file.vcf
bcftools index file.vcf.gz
```
Note that using the `--no-index` is risky in that it can lead to problems when the files contain chromosomes in different order. It is intended for expert use and generally its use is discouraged
```
*--no-index*::
    the option allows to merge files without indexing them first. In order for this
    option to work, the user must ensure that the input files have chromosomes in
    the same order and consistent with the order of sequences in the VCF header.
```

**Comment by lr192** [comment]
Nice, the  problem was solved.
