### ISSUE TITLE
bcftools split-vep keeps removing columns after INFO and also not assigning the vep headers

### ISSUE THREAD

**Issue by amy-houseman** [samtools/bcftools#1793]
Ignore, I figured it out. 

If anyone wants to keep the FORMAT column and make each part of it into a column, you can use:

bcftools +split-vep input.vcf -f '\t%CHROM\t%ID\t%POS\t%REF\t%ALT\t%CSQ[\t%GT][\t%GQ][\t%DP][\t%MIN_DP][\t%AD][\t%VAF][\t%PL][\t%MED_DP]\n' -d  -A tab  > output.vcf

**Comment by pd3** [comment]
There seems to be a misunderstanding in how the program operates. Basically it can work in two main modes and can output either a custom format text file or a VCF.

For the text output one provides the `-f` option with a formatting expression similar to `bcftools query` (see http://samtools.github.io/bcftools/bcftools.html#query, http://samtools.github.io/bcftools/bcftools.html#expressions, and http://samtools.github.io/bcftools/howtos/query.html). Here one has to list explicitly all fields that should be printed. (Note that also expressions like `bcftools -f '%INFO %FORMAT\n'` are supported.)

For the VCF output one provides the `-c` option. The usage page contains examples of both output types, for example
```
   # Extract Consequence, IMPACT and gene SYMBOL of the most severe consequence into
   # INFO annotations starting with the prefix "vep". For brevity, the columns can
   # be given also as 0-based indexes
   bcftools +split-vep -c Consequence,IMPACT,SYMBOL -s worst -p vep file.vcf.gz
   bcftools +split-vep -c 1-3 -s worst -p vep file.vcf.gz

   # Similar to the above but use the text output of the "bcftools query" format
   bcftools +split-vep -s worst -f '%CHROM %POS %Consequence %IMPACT %SYMBOL\n' file.vcf.gz
```

See also http://samtools.github.io/bcftools/howtos/plugin.split-vep.html
