### ISSUE TITLE
ERROR: INFO is not defined in the header

### ISSUE THREAD

**Issue by captaintiny** [samtools/bcftools#1794]
I am trying to merge a group of VCF files using BCF tools. All my files are compressed and indexed using bgzip and tabix respectively. 
The command I used was: `bcftools merge -o B1Ten.vcf -O v *vcf.gz`

But I got the repeated error message: `[W::vcf_parse] INFO 'SIFTINFO' is not defined in the header, assuming Type=String`

This info does seem to be in my header, however. 
`##INFO=<ID=SIFTINFO,Number=.,Type=String,Description="SIFT information. Format: Allele|Transcript|GeneId|GeneName|Region|VariantType|Ref_Amino_Acid/Alt_AminoAcid|Amino_position|SIFT_score|SIFT_median|SIFT_num_seqs|Allele_Type|SIFT_prediction">`

I have looked at other issues raised here, and compared the structure of my info tag to what seems to be the correct one in other comments, and they look the same. I have also checked the header of some of the VCF files using `bcftools view -h` and it is being displayed there. I have no idea why the merge code will not run. Please help!

**Comment by pd3** [comment]
I am assuming this problem was marked as resolved because some of the files did not have the SIFTINFO annotation declared in the header after all?
