### ISSUE TITLE
error on indexing a vcf.gz with bcftools

### ISSUE THREAD

**Issue by miniwatsa** [samtools/bcftools#1796]
I have a vcf I compressed with bcftools bgzip into a vcf.gz. I've tested it with htsfile subset.vcf.gz and get this:

unknown BGZF-compressed data

I'm trying to run  bcftools index - subset.vcf.gz and I get this:

[E::hts_hopen] Failed to open file subset.vcf.gz
[E::hts_open_format] Failed to open file "subset.vcf.gz" : Exec format error
Could not read subset.vcf.gz

Can you tell me what might be wrong? Why did bgzip make a "unknown" data file? What does that mean exactly?

Thank you very much - I appreciate the help.

**Comment by pd3** [comment]
It's impossible to tell really, we can just see it's not a compressed VCF. Try `zless subset.vcf.gz`, maybe that will help to debug the problem. The real question is, how was the file produced in the first place..

**Comment by pd3** [comment]
I'll close this issue as this is does not seem to be a problem with bcftools but with the underlying data.
