### ISSUE TITLE
[Enchancement] Make `+split-vep` plugin to output header when parsing annotated VCF file?

### ISSUE THREAD

**Issue by Z-Zen** [samtools/bcftools#1798]
> The plugin [split-vep](http://samtools.github.io/bcftools/howtos/plugin.split-vep.html) allows to extract fields from structured annotations such as INFO/CSQ created by bcftools/csq or VEP.

With this plugin, it is possible to extract the header in a separate file.

It is also possible to extract all the fields at the same time.

The problem is that when extracting the fields, we don't get the header included, only the output of the extraction.

I was wondering if its possible to ask an enhancement to include the header of such extraction otherwise one would need to perform such tasks manually.

Thank you in advance.

**Comment by pd3** [comment]
Not sure what you mean, can you be more specific?

For text output, one can run
```
$ bcftools +spit-vep -l file.vcf
0	Allele
1	Consequence
2	IMPACT
3	SYMBOL
4	Gene
...
```
For VCF output, one can get the header  with
```
$ bcftools +split-vep -c Consequence,IMPACT,SYMBOL file.vcf | bcftools view -h
...
##INFO=<ID=Consequence,Number=.,Type=String,Description="The Consequence field from INFO/CSQ">
##INFO=<ID=IMPACT,Number=.,Type=String,Description="The IMPACT field from INFO/CSQ">
##INFO=<ID=SYMBOL,Number=.,Type=String,Description="The SYMBOL field from INFO/CSQ">
...
```

**Comment by pd3** [comment]
I see. Just added a new `-H, --print-header` option to print the header. It works the same way as `bcftools query -H`.
