### ISSUE TITLE
Filter normalized vcf

### ISSUE THREAD

**Issue by krukanna** [samtools/bcftools#1803]
Hello, 
I got vcf after normalizing and I would like to filter items for a specific TAG which is MAX_AF. The problem is that according to the assumed condition, one variant should be filtered out and the other should not. However, this is incorrect, because information about first variant is lost. The ideal solution for me is: if one of the lines fails the condition, both remain. I will present an example:

```
chr1    5949343 rs140032819     T       TACACACACACACACACAC     3752.86 PASS    AC=1;AF=0.5;AN=2,MAX_AF=0.2494      GT:AD:DP:GQ:PL       1/0:0,3:12:97:1002,429,381
chr1    5949343 rs140032819     T       TACACACACACACACACACACAC 3752.86 PASS    AC=1;AF=0.2;AN=2;MAX_AF=0.0428     GT:AD:DP:GQ:PL       0/1:0,9:12:97:1002,158,97
```
I set up filter:
`bcftools filter -e 'INFO/MAX_AF>0.06'`

Thanks for help

**Comment by pd3** [comment]
There isn't a single command or option for this, but it can be done in two steps:
```
bcftools query -f'%CHROM\t%POS\n' -e 'INFO/MAX_AF>0.06' file.bcf | sort -k1,1d -k2,2n | uniq > sites.txt
bcftools view -R sites.txt file.bcf -o output.bcf
```

**Comment by krukanna** [comment]
thank you for help
