### ISSUE TITLE
bcftools stats can not correctly read the vcf

### ISSUE THREAD

**Issue by xyz0o** [samtools/bcftools#1804]
I have filtered my vcf file through several steps using bcftools filter, but I cannot read the stats of the final file
```
# The command line was: bcftools stats  Dmon.RD.vs.chrom.masked.ref.TE.normalized.decomposed.balance.SnpGap.nonSnp.PASS.vcf.gz
#
# Definition of sets:
# ID    [2]id   [3]tab-separated file names
ID      0       Dmon.RD.vs.chrom.masked.ref.TE.normalized.decomposed.balance.SnpGap.nonSnp.PASS.vcf.gz
[E::bcf_calc_ac] Incorrect AN/AC counts at X_chromosome:1323961
```

following a previous thread, I tried to get around this error with this command:
`bcftools annotate -x INFO/AN Dmon.RD.vs.chrom.masked.ref.TE.normalized.decomposed.balance.SnpGap.nonSnp.PASS.vcf.gz -r X_chromosome:1323961 | bcftools stats`

although I didn't really understand where the problem is?
```
bcftools query Dmon.RD.vs.chrom.masked.ref.TE.normalized.decomposed.balance.SnpGap.nonSnp.PASS.vcf.gz -r X_chromosome:1323961 -f'%POS\t%REF\t%ALT\t%AC\t%AN\n'
1323961 C       A,T     1,8     10,10
```

the stats result is basically 0 for everything! sorry if my question is primitive but I have no idea where the problem could be?
![image](https://user-images.githubusercontent.com/77616805/195335733-b31b5273-444e-4e8f-a4d7-515b5c6f06da.png)

bcftools 1.16
Using htslib 1.16

**Comment by pd3** [comment]
INFO/AN must be defined as Number=1 in the header and must have one value in the data lines

**Comment by xyz0o** [comment]
Thank you sir, as I checked in the header, it is defined as Number=1
![image](https://user-images.githubusercontent.com/77616805/195553722-841fd49d-560c-4a8d-b1f0-50feacff605f.png)

about the value, I am not sure if I understood you correctly. but I checked the vcf file that I've got after normalization and the bcftools stats reads it without error. 
![image](https://user-images.githubusercontent.com/77616805/195551567-14d6bad9-aa87-4401-9ccf-4aefe4f2a208.png)

the headers order is like this
![image](https://user-images.githubusercontent.com/77616805/195528361-666809ae-874f-4c1b-9898-cf42eb0b0674.png)

but after decompose, filter balance, filter SNPGap, filter nonSNP and subset passes, the final vcf is no longer readable which is weird because the format should not have been changed. here is how it looks like which is exactly the same as the first file
![image](https://user-images.githubusercontent.com/77616805/195529008-30233138-c41b-45bc-8150-ec9dccaeb611.png)
 so I don't understand what has changed?
p.s. the same chromosome number and ID: 192 exists in the first vcf file with the same values
![image](https://user-images.githubusercontent.com/77616805/195554380-0aa5e7db-7f56-4150-ade1-f1ce5bc6a038.png)

**Comment by pd3** [comment]
Above you showed that the query command returns two values (10,10) for AN at that position
```
bcftools query file.vcf.gz -r chr:1323961 -f'%POS\t%REF\t%ALT\t%AC\t%AN\n'
1323961 C       A,T     1,8     10,10
```
This  does not correspond to the screenshots you showed now. This cannot be solved without a test case, sorry.

**Comment by xyz0o** [comment]
could it be the way I index the file to check the query? I use tabix to index the vcf.gz.
and do you mean you would need my vcf file to check that? I can provide it to you if the size does not matter, it is 288M

**Comment by pd3** [comment]
No, this would not be a problem with indexing.

There is not much to go with here. You say there is a pipeline with multiple steps involved but show just a few screenshots of something. I suggest that you check the integrity of the intermediate VCF at each step. After you identify the one that fails, create a test case (a small VCF sufficient to trigger the error) attach it here together with the exact command necessary to reproduce the problem.

**Comment by xyz0o** [comment]
first we check that the stats works on the susbset file
`bcftools stats  subset.snp.normalized.vcf.gz`

```
# SN    [2]id   [3]key  [4]value
SN      0       number of samples:    5
SN      0       number of records:    7
SN      0       number of no-ALTs:    0
SN      0       number of SNPs: 6
SN      0       number of MNPs: 0
SN      0       number of indels:     1
SN      0       number of others:     0
SN      0       number of multiallelic sites:   2
SN      0       number of multiallelic SNP sites:       1

```

then decompose the primitive alleles:

`bcftools view --threads 16 subset.snp.normalized.vcf.gz | vcfallelicprimitives --keep-info --keep-geno -t decomposed |bcftools sort -O z > subset.snp.normalized.decomposed.vcf.gz`


```
 bcftools stats  subset.snp.normalized.decomposed.vcf.gz

# Definition of sets:
# ID    [2]id   [3]tab-separated file names
ID      0       subset.snp.normalized.decomposed.vcf.gz
[E::bcf_calc_ac] Incorrect AN/AC counts at X_chromosome:998

```

```
bcftools query -r X_chromosome:998 -f '%POS\t%REF\t%ALT\t%AC\t%AN\n' subset.snp.normalized.decomposed.vcf.gz
998     T       TG,TT   4,6  10,10
```
[subset.snp.normalized.vcf.gz](https://github.com/samtools/bcftools/files/9776738/subset.snp.normalized.vcf.gz)

**Comment by pd3** [comment]
Then the problem was introduced by `vcfallelicprimitives` and should be reported elsewhere. As I explained above, the AN tag must have only one value, specifically `AN=10`, not `AN=10,10`.

Note that you attached `subset.snp.normalized.vcf.gz`, not `subset.snp.normalized.decomposed.vcf.gz`

**Comment by xyz0o** [comment]
true, sorry I didn't realize vcfallelicprimitives is part of another package:)
