### ISSUE TITLE
Segfaults in bcftools

### ISSUE THREAD

**Issue by DrYak** [samtools/bcftools#1805]
I have a pair of BAM files:
 - an alignement but untrimmed one
 - and same alignment but after trimming primers with "ivar trim"
 
 I try to call the consensus using bcftools and the first step of the pipe chain:
 ```bash
 bcftools mpileup --threads 1 -Ou -f references/NC_045512.2.fasta --max-depth 10000 --max-idepth 10000 --annotate FORMAT/AD,FORMAT/DP,INFO/AD REF_aln_trim.bam
 ```
 - works with the first file
 - Segfaults with the trimed file.
 
 This was tested reproducibly with versions 1.13, 1.15.1 and 1.16 installed from bioconda.
 
 Woud you like that I provide you both bam files so you could try to pin-point the source of the problem?

**Comment by pd3** [comment]
Hi, yes, we'll need a small test case to reproduce the problem, bam slices and the reference. Thank you

**Comment by DrYak** [comment]
[link to our uni's nextCloud sharing service](https://polybox.ethz.ch/index.php/s/AdmMrqFPsya6Ush)

 - NC_045512.2.fasta : SARS-CoV-2 reference we used
 - REF_aln.bam & .bai : direct output of bwa, sorted and indexed by samtools
   - ^--: the one that works
 - REF_aln_trim.bam & .bai : trimmed with "ivar trim", sorted and indexeded by samtools
   - ' -: the one that segaults.

**Comment by DrYak** [comment]
For reference:
 - [the snakemake rule that trimms](https://github.com/cbg-ethz/V-pipe/blob/302e422315832e768d6c2743d2dd85b14e8c2462/workflow/rules/primerstrim.smk#L64)
 - [the snakemake rule that calls consensus](https://github.com/cbg-ethz/V-pipe/blob/302e422315832e768d6c2743d2dd85b14e8c2462/workflow/rules/consensus.smk#L49)
  - the first command of the pipeline, mpileup, segfaults
  - the next command errors out complain about badly formatted input.

**Comment by pd3** [comment]
This is now fixed. Thank you for the test case.
