### ISSUE TITLE
bcftools query -f "%VKX" misses a safety check and causes a segmentation fault

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#1806]
The following reproduces the segmentation fault:
```
$ (echo "##fileformat=VCFv4.2"
echo "##contig=<ID=chr15,length=101991189>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "chr15\t23065293\t.\tG\t.\t.\t.\t.") | \
  bcftools query -f "%VKX"
Segmentation fault (core dumped)
```
What is going on is that the conversion function in `convert.c` for VKX:
```
static void process_variantkey_hex(convert_t *convert, bcf1_t *line, fmt_t *fmt, int isample, kstring_t *str)
{
    uint64_t vk = variantkey(
        convert->header->id[BCF_DT_CTG][line->rid].key,
        strlen(convert->header->id[BCF_DT_CTG][line->rid].key),
        line->pos,
        line->d.allele[0],
        strlen(line->d.allele[0]),
        line->d.allele[1],
        strlen(line->d.allele[1]));
    ksprintf(str, "%016" PRIx64 "", vk);
}
```
does not have a safety check and it attempts to access `line->d.allele[1]` even when this pointer is `NULL`. This is contrast with the conversion function in `convert.c` for ALT:
```
static void process_alt(convert_t *convert, bcf1_t *line, fmt_t *fmt, int isample, kstring_t *str)
{
    int i;
    if ( line->n_allele==1 )
    {
        kputc('.', str);
        return;
    }
    if ( fmt->subscript>=0 )
    {
        if ( line->n_allele > fmt->subscript+1 )
            kputs(line->d.allele[fmt->subscript+1], str);
        else
            kputc('.', str);
        return;
    }
    for (i=1; i<line->n_allele; i++)
    {
        if ( i>1 ) kputc(',', str);
        kputs(line->d.allele[i], str);
    }
}
```
which properly checks whether `line->n_allele==1` instead and indeed:
```
$ (echo "##fileformat=VCFv4.2"
echo "##contig=<ID=chr15,length=101991189>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "chr15\t23065293\t.\tG\t.\t.\t.\t.") | \
  bcftools query -f "%ALT"
.
```

**Comment by pd3** [comment]
@freeseek I don't know much about variantkey and how it should handle sites with no ALT allele. Is it acceptable to just skip the ref-only sites?

**Comment by freeseek** [comment]
Not that I need this, but I think it is okay to still convert sites with no ALT allele. The following replacement code would actually work fine:
```
static void process_variantkey_hex(convert_t *convert, bcf1_t *line, fmt_t *fmt, int isample, kstring_t *str)
{
    const char *alt = NULL;
    size_t sizealt = 0;
    if ( line->n_allele>1 ) {
        alt = line->d.allele[1];
        sizealt = strlen(line->d.allele[1]);
    }
    uint64_t vk = variantkey(
        convert->header->id[BCF_DT_CTG][line->rid].key,
        strlen(convert->header->id[BCF_DT_CTG][line->rid].key),
        line->pos,
        line->d.allele[0],
        strlen(line->d.allele[0]),
        alt,
        sizealt);
    ksprintf(str, "%016" PRIx64 "", vk);
}
```
It does not trigger any warnings from valgrind. And not sure why `process_variantkey_hex()` does not just compute `strlen()` itself. It seems like it would have been better to perform that computation inside the function rather than requiring two additional inputs.

By the way, this function is a life saver when converting VCFs to PLINK format, as PLINK1.9 allocates memory to read the variant table in a way that it is proportional to the longest variant ID string in the table, so it is important to have a way to generate IDs of limited length.

**Comment by pd3** [comment]
OK, I did it this way, hope it will work. Thanks
