### ISSUE TITLE
Precedence for sample and missingness filters

### ISSUE THREAD

**Issue by merondun** [samtools/bcftools#1807]
This is perhaps working as intended, but it has dramatic downstream consequences so I think it perhaps deserves further emphasis in the manual, if intended. 

When using `bcftools view` on a VCF and drawing a subset of samples with `--samples-file`, simultaneously while applying a genotype filtering expression, e.g. `-e 'F_MISSING>0.02'`, the expression is applied *before* the samples are subset, in contrast to other tools like plink etc which take the subset of samples and then apply missingness. 

I have confirmed this on any VCF with bcftools v1.8, 1.12, and 1.16, so I doubt it is necessarily a bug, but regardless, for those of us who bundle many filters into a single `bcftools view` command, this could cause huge impacts (see below with a single chromosome, removing >1.5M sites in the total sample dataset, vs the 3.1M in our analysis-set. 

```
GROUP=Canorus
CHR=chr_1

bcftools view --samples-file ${GROUP}.list -e 'F_MISSING>0.02' ${CHR}.IF-GF-MM1.vcf.gz | wc -l
1,558,088
bcftools view --samples-file ${GROUP}.list ${CHR}.IF-GF-MM1.vcf.gz | bcftools view -e 'F_MISSING>0.02' | wc -l
3,149,509
```

This may relate to the below documentation under `--samples`, but perhaps adding a caveat about expressions would be worthwhile as well. 

> Note that in general tags such as INFO/AC, INFO/AN, etc are not updated to correspond to the subset samples.

**Comment by pd3** [comment]
This is actually mentioned in the documentation here, but I understand it can be easily overlooked
https://github.com/samtools/bcftools/blob/4cfa4c81bfc3ed4bf8b007c615e1da26b5e41869/doc/bcftools.txt#L3271-L3277

Just added a word about this in the usage page.
