### ISSUE TITLE
bcftools annotate --collapse all -c +ID does not annotate anything in 1.16

### ISSUE THREAD

**Issue by danilovkiri** [samtools/bcftools#1808]
[Archive.zip](https://github.com/samtools/bcftools/files/9852666/Archive.zip)

Hi.

When upgrading from bcftools 1.11 to bcftools 1.16 I noticed a completely erroneous behaviour.
Running bcftools 1.11
```
bcftools annotate --collapse all -c +ID -a ./dbsnp-155-split.vcf.gz -r chrM ./sample.gatk_annotatedM.vcf.gz --output-type z -o sample.annotatedM_1.11.vcf.gz --threads 16
```
behaves as expected populating ID field in the VCF entries with unknown (`.`) ALT allele and uncalled or HOM-REF genotypes.

Running the same command using bcftools 1.16 results in zero HOM-REF entries annotated with ID from the external annotation resource.

For instance, the source entry
```
chrM	1943	.	A	.	24.76	.	AN=50;DP=3039	GT:AD:DP:RGQ	0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0:3038,1:3039:4
```
is annotated by bcftools 1.11 as 
```
chrM	1943	rs1556422584	A	.	24.76	.	AN=50;DP=3039	GT:AD:DP:RGQ	0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0:3038,1:3039:4
```
while annotation by bcftools 1.16 results in no ID field annotation
```
chrM	1943	.	A	.	24.76	.	AN=50;DP=3039	GT:AD:DP:RGQ	0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0:3038,1:3039:4
```

This behaviour is reproducible in all canonical chromosomes, haploid and diploid genotypes (as well as other genotype ploidy values). I also noticed the same behavior in bcftools v1.15.1.

The test files are supplied in an archive with file names stored as used in the provided command.

**Comment by pd3** [comment]
This is actually not a bug. Variant IDs are attached to a variant, not to a position. For example, the position chrM:73 is associated with rs869183622 for A>C and with rs869183622 for A>G. When ALT is empty, the program would not know which ID to use. If you want to force an ALT allele, you could run as
```
bcftools annotate -c +ID,+ALT -a annots.bcf in.bcf -o out.bcf
```
However, note that filling in ALT alleles is currently not without problems: annotations with variable number of values (i.e. defined as Number=G, Number=R, or Number=A) are currently not updated in this operation.

**Comment by danilovkiri** [comment]
Well, if it is not a bug, then I'll try to ask again: why two different versions of bcftools behave differently when executed identically. The program, as you say, knew how to do it up until v1.14, but does not know now.

Besides, note your example `rs869183622 for A>C and with rs869183622 for A>G` — its the same rsID. rsIDs exist even when no variation is present in the same way HOM-REF genotypes exist.

Aannotating positions rather than alleles is necessary in some cases. It was possible to do this, but now this functionality disappeared. I know that rsIDs are associated variants, but since dbSNP build 153 multiple colocated rsIDS have been merged to represent a locus rather than a specific allele change.

**Comment by pd3** [comment]
My quick assessment was completely wrong, sorry. This is now fixed and the command should work now
```
bcftools annotate --pair-logic any -c +ID -a annots.id.vcf.gz annotate.id.vcf.gz
```
