### ISSUE TITLE
erro:nohup: ignoring input and redirecting stderr to stdout Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid Failed to open -: unknown file type.

### ISSUE THREAD

**Issue by beaufor** [samtools/bcftools#1815]
nohup bcftools mpileup -Ou BoneMarrow_62016.bam -f genome.fa | bcftools call -mv -o BoneMarrow_62016_1.vcf &

erro:nohup: ignoring input and redirecting stderr to stdout Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid Failed to open -: unknown file type.
what's the reason?

**Comment by pd3** [comment]
`nohup` should not be used like this, please see an explanation here https://github.com/samtools/bcftools/issues/942

**Comment by beaufor** [comment]
oh! yes,thanks Petr!
