### ISSUE TITLE
norm --rm-dup exact seems to break vcf order

### ISSUE THREAD

**Issue by ASLeonard** [samtools/bcftools#1816]
Perhaps it is accepted behaviour, but removing duplicates with `bcftools -d exact` can take in a sorted vcf and output an unsorted vcf. I would naively expect, since this is only removing variants, that the sortedness would be preserved.

Here is an example of the coordinates in out-of-sort order. I can provide a subset of the vcf causing the issues if this is unexpected behaviour. Otherwise a `bcftools sort` does fix this.

```
HER     2529563 
HER     2489440
...
HER     40721356   
HER     40720078
```

This was done using the current head for bcftools/htslib.

Best,
Alex

**Comment by pd3** [comment]
Can you please show the full command and provide a small test case to reproduce the problem?

**Comment by ASLeonard** [comment]
Ah apologies, I misread a previous part of the pipe as `bcftools view -a` but was `bcftools norm -a`, so the sortedness was lost during that intermediate step when a large MNP was decomposed. I checked for completeness, and sorting the input before `bcftools norm --rm-dup exact` maintains sorted output, so this was just a mistake on my end.
