### ISSUE TITLE
The inconsistent results between bcftools merge + view and bcftools merge

### ISSUE THREAD

**Issue by NextGenBioinformatics** [samtools/bcftools#1820]
Hi there,

My task is to merge a number of VCF files and only retain the variants that have passed all the filters and I used the following two methods:

1) Two step method:

```
bcftools merge -l vcf_list.txt -m both -Oz -o vcf_merged.vcf.gz
bcftools view -f PASS vcf_merged.vcf.gz -Oz -o vcf_merged.pass.vcf.gz
```

2) One step method:

`bcftools merge -f PASS -l vcf_list.txt -m both -Oz -o vcf_merged.pass.2.vcf.gz`

I would expect the two result files, vcf_merged.pass.vcf.gz and vcf_merged.pass.2.vcf.gz to be exactly the same. However, there is considerable discrepancy between the two files.

Could you please help with what happens here and which method should be used for this purpose?

Many thanks,

Tom

**Comment by pd3** [comment]
The best way to understand the differences is to identify one such site and check what filters are set in all input files.
The  `merge -f PASS` command (option 2) would filter sites before merging. So not only all FILTER values should be unset, but also some input lines would not be considered. The `merge + view -f PASS` commands (option 1) would first merge everything and filter everything that has FILTER column set on output.

**Comment by NextGenBioinformatics** [comment]
Thanks for the comments.

I run the following three command lines:

1) bcftools merge -f PASS -l vcf_list.txt -Oz -o vcf_merged.pass.1.vcf.gz
2) bcftools merge -f PASS -F + -l vcf_list.txt -Oz -o vcf_merged.pass.2.vcf.gz
3) bcftools merge -f PASS -F x -l vcf_list.txt -Oz -o vcf_merged.pass.3.vcf.gz

I expect option 2 and option 3 to give different results as they use different strategies (x for any and + for all), but surprisingly, all of the three options produce the same number of variants. Am I missing something here? Many thanks
