### ISSUE TITLE
bcftools merge -F option

### ISSUE THREAD

**Issue by NextGenBioinformatics** [samtools/bcftools#1821]
Hello,

I run the following three command lines:

1) bcftools merge -f PASS -l vcf_list.txt -Oz -o vcf_merged.pass.1.vcf.gz

2) bcftools merge -f PASS -F + -l vcf_list.txt -Oz -o vcf_merged.pass.2.vcf.gz

3) bcftools merge -f PASS -F x -l vcf_list.txt -Oz -o vcf_merged.pass.3.vcf.gz

I expect option 2 and option 3 to give different results as they use different strategies (+ for all and x for any), but surprisingly, all of the three options produce the same number of variants. My understanding is that "-F +" will only output the variants that have passed the filters in all samples listed in the file "vcf_list.txt" while "-F x" will output the variants that have passed the filters in at least one sample listed in the file "vcf_list.txt". Is this right? Am I missing something here?

Many thanks

Tom

**Comment by pd3** [comment]
Your understanding is not correct. The option is about carrying over the FILTER annotation from source files to the output file, not about filtering (removing) sites.
