### ISSUE TITLE
Modify vcf INFO using bcftools +split

### ISSUE THREAD

**Issue by LeoVincenzi** [samtools/bcftools#1822]
Hello everyone, I'm trying to perform some computations using DP and AD fields in my vcf file obtained by bcftools. Since this variant calling was implemented inside another tool that I used (MutMap), it has taken two alignments as input. So, now I have a multi-sample vcf that I want to split into the two samples in it. The problem is that the DP field in the vcf (DP=7) is considering both samples and when I split the vcf with `bcftools +split` it remains the same in both the separated vcfs.
I'm trying to perform the SNP-index computation in the two samples, which means I should do AD/DP, but the DP in the splitted vcf is wrong since it still considers the other sample. 

Do you have any suggestions on how can I split the vcf and also carry the right modification in the output vcf?

Thanks for your attention.

**Comment by pd3** [comment]
Does your VCF has INFO/DP and FORMAT/AD? If that's the case, you can fill in FORMAT/DP with the `+fill-tags` plugin
```
bcftools +fill-tags input.vcf -- -t 'FORMAT/DP:1=int(smpl_sum(FORMAT/AD))'
```

**Comment by pd3** [comment]
I believe this is resolved by the suggestion above, reopen if not.
