### ISSUE TITLE
Bcftls 1.16 able to add F_MISSING tag?

### ISSUE THREAD

**Issue by ra23mik** [samtools/bcftools#1823]
I tried adding the F_MISSING tag using bcftools 1.16. When I run this command:
bcftools +fill-tags input.vcf.gz -- -t 'F_MISSING' | bcftools view -i 'INFO/F_MISSING<0.25' -Oz -o output.vcf.gz

I get the following error:
Error parsing "--tags F_MISSING": the tag "F_MISSING" is not supported

I know this command runs fine using bcftools 1.15. However, version 1.15 gives complications with other packages I use in my snakefile. Do you maybe know alternatives for how to add F_MISSING using bcftls 1.16?

**Comment by pd3** [comment]
It works for me. Can you check that the right version of the plugin is picked up?
```
bcftools +fill-tags --version
```

**Comment by ra23mik** [comment]
I installed bcftools in a newly created conda env using ```conda install -c bioconda bcftools``` as indicated  on https://anaconda.org/bioconda/bcftools 

When I type bcftools ```bcftools +fill-tags --version```:
bcftools 1.9 using htslib 1.9
plugin at 1.9 using htslib 1.9

**Comment by pd3** [comment]
So I guess that answers your question, doesn't it? This feature was added only later. Please see here how to install the latest version from the source code http://samtools.github.io/bcftools/howtos/install.html

**Comment by ra23mik** [comment]
Indeed the issue was that I was not installing the most recent version of Conda.
I solved it by changing the .condarc file to solelely include:
```channels:
    - conda-forge
    - bioconda
    - defaults```
The order is crucial as well.
