### ISSUE TITLE
except variant not be called

### ISSUE THREAD

**Issue by user-tq** [samtools/bcftools#1825]
I want to call out the variant on 'chr20  57429619 '，A->G

for this i try
```
samtools view bqsr.bam   "chr20:57429609-57429629" -b -o bqsr_chr20_57429609_57429629.bam
bcftools mpileup --fasta-ref hg19.fa  bqsr_chr20_57429609_57429629.bam  |bcftools call   -mv -o raw.vcf
```

[raw.vcf.zip](https://github.com/samtools/bcftools/files/10080402/raw.vcf.zip)
[bqsr_chr20_57429609_57429629.bam.zip](https://github.com/samtools/bcftools/files/10080388/bqsr_chr20_57429609_57429629.bam.zip)

**Comment by pd3** [comment]
The caller does the correct job of not calling the variant, only 7% of the 179 reads have the alternate allele and they are on reads with soft clips. If you really really want to see variants like this, you can run the command like this
```
bcftools mpileup -Ou -a AD -f ref.fa aln.bam | bcftools call -mA
``` 
and then post-process the output VCF based on allelic depth counts (the AD tag).

**Comment by user-tq** [comment]
I'm sorry to bother you.Recently,I encountered a similar problem. After checking, I think the reason why it was not detected is not soft-clips.One possible reason is that AF is too low,But it is unrealistic to expect higher AF in blood samples.I plan to combine the results of ```mutect2``` and ```samtool```,But I found that none of them had detected this variant.I wonder if there is any way to understand some details of call variant and the reason why it is not be called as variant.This always makes me worry about whether there is any hidden danger.
thanks in advance.
[bqsr_chr12_25398270_25398300.bam.zip](https://github.com/samtools/bcftools/files/10350619/bqsr_chr12_25398270_25398300.bam.zip)
my cmd
```
# for chr12 25398285 C A
samtools view  bqsr.bam    "chr12:25398270-25398300" -b -o bqsr_chr12_25398270_25398300.bam
bcftools mpileup -f hg19.fa  bqsr_chr12_25398270_25398300.bam |bcftools call   -mv -o raw.vcf
```
![image](https://user-images.githubusercontent.com/72878144/210735466-9fb88959-e386-4bff-afc0-cba74d8fd346.png)

**Comment by pd3** [comment]
It's the same thing as before: the screenshot shows only 2% of the reads have the variant which cannot be called as a heterozygous variant.
