### ISSUE TITLE
Please make NM tag optional.  Major speed regression.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#1826]
Bcftools 1.16 mpileup is around half the speed of 1.15.  This is entirely due to the addition of `bam_aux_nm` in https://github.com/samtools/bcftools/commit/e9d22b1f5d24e0ceb2d613d9c390171d713d4252.

A small test region on some Illumina data showed:

bcftools 1.15:  14.1s
bcftools 1.16: 26.1s

My understanding is it's being called once per base, per read.  Fetching an NM tag is an expensive operation as it has to scan through the full aux tag list per read.  The more tags we have, the slower it'll get.

Furthermore the implementation of this, if it doesn't find an NM tag, is then to go through the full CIGAR string and compute a value.  Given the CIGAR string length is proportional to both sequence length and sequence accuracy, this means it will be very time consuming on the long read technologies.  The proportionality of this to sequence length, coupled with it being called for every base in the sequence, makes this function O(N^2) complexity if NM doesn't exist, although other slow downs with long-read data may not make it the bottleneck there.  (I would also question the validity of NM scoring for long reads anyway as a global score over the entire read isn't nearly so useful as a local regional stat.)

If this is to be kept, then I recommend caching the NM tag value so it is fetched / computed for the first base we visit in the sequence and then reused for all subsequent bases.  If this is a complex thing to do, then in the short term it should simply be made optional so we don't have this regression in develop, or take it out of the main branch again (it's flagged as experimental so is presumably a work in progress).

**Comment by pd3** [comment]
Ah, that's right. This is used by NMBZ and NM tags, and the intention was to use a localized version to make this useful also for long reads. For now I'll make this switched off by default and cache the values.
