### ISSUE TITLE
feature request: split multiallelic sites to haploid genotypes

### ISSUE THREAD

**Issue by nathanLauHKGI** [samtools/bcftools#1827]
[NA24149-LIB1.Mito.single.vcf.gz](https://github.com/samtools/bcftools/files/10112140/NA24149-LIB1.Mito.single.vcf.gz)
Dear Sir/Madam

I am using GATK Mito WDL and got the following variant (Please also find attached vcf.gz file)

chrM    10933   .       C       CGG,CGGGGGGGGGGGGGGGGGG .       mt_many_low_hets        DP=6728;ECNT=5;MBQ=30,25,20;MFRL=444,384,425;MMQ=60,60,60;MPOS=10,12;OCM=0;POPAF=2.4,2.4;RPA=1,3,19;RU=G;STR;TLOD=17.09,7.59    GT:AD:AF:DP:F1R2:F2R1:SB        0/1/2:6273,88,57:0.004902,0.005769:6418:2300,40,40:3601,35,5:998,5275,145,0

I use bcftools to split the variant into two SNV, with bcftools command,

bcftools norm -m -both --fasta-ref /home/ec2-user/reference/Homo_sapiens_assembly38.fasta -Oz -o output.vcf.gz input.vcf.gz

then I have,

chrM    10933   .       C       CGG     .       mt_many_low_hets        DP=6728;ECNT=5;MBQ=30,25;MFRL=444,384;MMQ=60,60;MPOS=10;OCM=0;POPAF=2.4;RPA=1,3;RU=G;STR;TLOD=17.09     GT:AD:AF:DP:F1R2:F2R1:SB        0/1/0:6273,88:0.004902:6418:2300,40:3601,35:998,5275,145,0
chrM    10933   .       C       CGGGGGGGGGGGGGGGGGG     .       mt_many_low_hets        DP=6728;ECNT=5;MBQ=30,20;MFRL=444,425;MMQ=60,60;MPOS=12;OCM=0;POPAF=2.4;RPA=1,19;RU=G;STR;TLOD=7.59     GT:AD:AF:DP:F1R2:F2R1:SB        0/0/1:6273,57:0.005769:6418:2300,40:3601,5:998,5275,145,0

As you can see, instead of GT = 0/1, i have GT = 0/1/0 and 0/0/1, am i missing something?
Thank you for your help. Kind regards,

**Comment by pd3** [comment]
The splitting feature is not intended to split multiploid genotypes into diploid or haploid genotypes, but for splitting multiallelic sites, preserving the ploidy. (By the way, why diploid genotype would be desirable for mitochondria, rather than haploid?)

I can mark this as a feature request for a new option, but unlikely to be addressed anytime soon I am afraid.
