### ISSUE TITLE
Replace REF/ALT IUPAC allele with monomorph HOM_ALT allele in IUPAC consensus sequence of set of samples.

### ISSUE THREAD

**Issue by WimSpee** [samtools/bcftools#1828]
Dear BCFTools developers, 

Thank you for the already very useful BCFTools consensus functionality. 

When given the below REF and ALT alleles in sequence, and the genotypes of these 3 samples, it makes most sense to use the ALT allele of base 3 in the IUPAC sequence produced by `bcftools consensus`. Since it is monomorph HOM_ALT in 3 the samples of interest.  The REF allele is never observed in the samples of interest. This is the most correct consensus sequence for these 3 samples.  

|sequence|	base 1|	base 2|	base 3|	base 4|	base 5|	base 6|	base 7|	base 8|
|----------|----------|----------|----------|----------|----------|----------|----------|----------|
|reference|	A|	A|	C|	C|	T|	T|	G|	G|
|ALT|	G|	G|	T|	T|	C|	C|	A|	A|
|sample 1|	0/0|	0/1|	1/1|	0/0|	0/1|	0/0|	1/1|	0/0|
|sample 2|	0/0|	0/0|	1/1|	0/0|	1/1|	0/0|	0/0|	0/0|
|sample 3|	0/0|	0/1|	1/1|	0/0|	1/1|	0/0|	1/1|	0/0|
|correct consensus|	A|	R|	**T**|	C|	Y|	T|	R|	G|
|current consensus|	A|	R|	**R**|	C|	Y|	T|	R|	G|

Current consensus is made using bcftools 1.12. 

For the ALT allele it is already implemented that it is not used in the sample set IUPAC sequence, if that allele is not in the genotypes of any sample in the set. See base 1,4,6 and 8.  The same should hold true for the REF allele on base3. 

Not including the REF allele in the IUPAC for monomorph HOM_ALT variants makes most sense for the consensus sequence I think. 
And also would be useful for downstream purposes that depend on the most accurate consensus sequence of a group of samples (e.g. diverse types multiple sequence analysis and assay design etc.)

Thank you for looking into this.

**Comment by pd3** [comment]
This has been now addressed by changing the behavior of the `-I, --iupac-codes` option and by adding the options `-s, --samples` and `-S, --samples-file`. The original behavior where IUPAC codes are determined solely from REF and ALT columns can be achieved by running with `-s -`.

Please try it out and let me know if there are any problems.

**Comment by JorisBenschop** [comment]
@pd3  just a quick note on potential typo:
https://github.com/samtools/bcftools/commit/9958cf464ae76bb741b22641bdb4a93e4cf50ef1
Line 269 of consensus.c mentions "--sample", should this be "--samples"?

**Comment by WimSpee** [comment]
@pd3 Thank you very much for picking this up and the quick implementation!  
It's very useful for us and I think also other BCFTools users.

**Comment by pd3** [comment]
Indeed, it should be `--samples`, thank you. Note the original version, `--sample`, still works for backward compatibility, only it's not advertised.

**Comment by WimSpee** [comment]
@pd3 I installed the latest bcftools 1.17 dev version that has the commit linked to this ticket. 

I see some expected but also unexpected changes.

**Expected:**
When using --iupac-codes some of the IUPACS in the consensus are now replaced by normal a/c/t/g nucleotides marked in lowercase. Because these are monomorph HOM_REF probably in the test samples of interest. 

**Unexpected:**
When not using --iupac-codes there are now y/s/w/k/m IUPACS in the consensus. On these locations there used to be the ALT allele of the variants. 

It looks like --iupac-codes now somehow always is TRUE? Even when --iupac-codes is not used on the bcftools consensus CLI?

We prefer the old behavior of when --iupacs == FALSE that the alternative allele is used in the consensus sequence.

**Comment by pd3** [comment]
@WimSpee I believe this is due to the change in the default behavior as explained above https://github.com/samtools/bcftools/issues/1828#issuecomment-1346699319 and in the usage page
```
-s, --samples LIST     Comma-separated list of samples to include, "-" to ignore samples and use REF,ALT
```

**Comment by WimSpee** [comment]
@pd3 Thank you for the information. Via adding `-s -` we can now also get the expected sequence with just the alternative alleles.

The `-I, --iupac-codes` now only seems to change the output when used in combination with  `-s -` .  By default IUPACs are already created when creating the consensus sequence for a set of samples. Adding `-I, --iupac-codes` does not change that output. 

I also didn't get at first that `-s -` changes output when **not** using `-I, --iupac-codes`

Thanks again for the functionality and the help here in this ticket.
