### ISSUE TITLE
[feature request] DIST tag indicates distance to nearest 5' and 3' neighbor.

### ISSUE THREAD

**Issue by StefanReuscher** [samtools/bcftools#1829]
Hi All,

I have started using the somewhat new plugin variant-distance to great success. Thanks for adding this. 

For my work it would be really helpful if we could add the option to calculate both the 5' and 3' distance to the nearest neighbor, so the `DIST `tag would look like `DIST=50/100` or similar. This way, we could tell, if a variant has "clean" flanks on at least one side. 

Do you think that might be a useful addition for the general user base ?

Best Regards,

Stefan

**Comment by pd3** [comment]
A new option `-d, --direction fwd|rev|nearest|both` has been added to control the behavior

**Comment by StefanReuscher** [comment]
Thanks ! You guys do awesome work !
