### ISSUE TITLE
Instructions at samtools.github.io/bcftools predate 1.x releases

### ISSUE THREAD

**Issue by jmarshall** [samtools/bcftools#183]
The instructions at http://samtools.github.io/bcftools/ were last updated in June, before the bcftools 1.0 release and the creation of http://www.htslib.org/.  They recommend a developer build via cloning all three git repositories; but now that we have easily-built releases, for non-hardcore-informatics people it would be better to point to http://www.htslib.org/download and the release tarballs there.

**Comment by pd3** [comment]
The man page has been updated, cheers.
