### ISSUE TITLE
bcftools norm --atomize does not split up a SNP followed by an insertion

### ISSUE THREAD

**Issue by 0xaf1f** [samtools/bcftools#1832]
I have a variant record that looks like

```
1       3552597   .       C       GGGG
```

Following `bcftools norm --atomize ...` (v1.16), it remains the same. I suppose this is an odd case, as the expected output for making them independent records would be the somewhat unintuitive

```
1       3552597   .       C       G
1       3552597   .       C       CGGG
```

I think it's a sensible expectation. I am trying to make a SNP matrix for a phylogenetic tree and this sample is not getting grouped with others that just have the C->G SNP when I do `bcftools merge`.

**Comment by pd3** [comment]
That's a fair point, addressed now by https://github.com/samtools/bcftools/commit/1f50f07a65ecc2e6137bda4d5d3df41b0900cdaf. Thanks for the issue
