### ISSUE TITLE
Some questions about multi-sample variant calling

### ISSUE THREAD

**Issue by Abieskawa** [samtools/bcftools#1839]
Hi all,
Here is a population data I want to do variant calling: a pair of parents (coverage: 39x and 9x) and 192 samples (lower than 9x).I want to do variant calling by grouping these 194 samples. After aligning with bwa-mem, I did sort and index them and filter unmapped and secondary alignment (it seems bcftools pileup cannot input without filtering these reads) and bgzip them (bcftools tells me to bgzip them). And now I got 194 gzipped files. Here is my questions: 
1. Is it appropriate to use the recommend code on man page with "bcftools call -G" change like this:
`bcftools mpileup --bam-list bcftools_input.txt --threads 16 -d (8000/194=41) -f $REF -I -a AD | \
bcftools call --threads 16 -m -v -Oz \
-G (group file name)
-o (outputfile name) \
--regions Chromosome names -V indels`
BTW, I only want snps here. I just want to save my storage space since I am using local computer. 

2.  Is it appropriate to use -d (8000/194=41) in this example?

**Comment by pd3** [comment]
You don't need to pre-filter the alignments, `bcftools mpileup` will exclude unwanted reads on the fly.
Regarding the depth, it's better not to limit it, go with the default in your case.
Note the threading options only help with compression/decompression of the bams/vcfs, so they may have smaller effect than you'd expect. But it is a good idea to add `bcftools mpileup ... -Ou |` to prevent the conversion from internal BCF representation to VCF text representation and back when streaming to `bcftools call`.
