### ISSUE TITLE
Wrong genotypes if duplicate sample names

### ISSUE THREAD

**Issue by eturro** [samtools/bcftools#184]
If a VCF file has a duplicate sample name, you get a warning and the duplicate is removed from the header. However, the genotype column that is removed is the right-most one corresponding to the last sample, not the duplicate sample. E.g.:

$ zcat file1.vcf.gz  | grep -v "^##"
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE	SAMPLE	SAMPLE3
1	1394663	.	AC	A	99	PASS	DP=100	GT	0/1	0/1	0/0

$ bcftools view file1.vcf.gz | grep -v "^##"
[W::bcf_hdr_add_sample] Duplicated sample name 'SAMPLE'. Skipped.
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE	SAMPLE3
1	1394663	.	AC	A	99	PASS	DP=100	GT	0/1	0/1

SAMPLE3 has the 0/1 genotype instead of the correct 0/0 genotype

Also wrong when individual sample names are specified with -s:

$ bcftools view -H -s SAMPLE3 file1.vcf.gz
[W::bcf_hdr_add_sample] Duplicated sample name 'SAMPLE'. Skipped.
1	1394663	.	AC	A	99	PASS	DP=100;DP=99;AC=1;AN=2	GT	0/1

**Comment by pd3** [comment]
This is now addressed by https://github.com/samtools/htslib/commit/21fbc8bed7cced0d609c6f65002649d3206318e6, cheers.
