### ISSUE TITLE
No VAF value output from +fill-tags despite no error message and VAF header output

### ISSUE THREAD

**Issue by shadihames** [samtools/bcftools#1841]
I've used bcftools +fill-tags a lot previously to add VAF values to VCFs from different mutation callers. I've had no issues before so I don't think it's anything wrong with my installation. However, I'm having a problem adding VAF to VCFs from VarScan2. The AD value is included already. When I run the command I don't get any error message and a file is output. VAF is included in the header but none of the thousands of variants have VAF in the FORMAT column.

Command:

`bcftools +fill-tags input.vcf -o output.vcf -- -t VAF`

Header output:
> ##FORMAT=<ID=VAF,Number=A,Type=Float,Description="The fraction of reads with alternate allele (nALT/nSumAll)">
##bcftools_pluginVersion=1.16+htslib-1.16
##bcftools_pluginCommand=plugin fill-tags -o output.vcf -- input.vcf -t VAF; Date=Tue Jan  3 11:01:58 2023

Example of FORMAT column in output VCF:
> GT:GQ:DP:RD:AD:FREQ:DP4 0/0:.:102:98:4:3.92%:73,25,4,0  0/1:.:111:98:13:11.71%:77,21,13,0

**Comment by shadihames** [comment]
Is it because there's only 1 value in the AD tag?

**Comment by pd3** [comment]
You should show also the definition of AD and the number of ALT alleles at that line.

VAF is computed for variant sites from AD, which should be defined as Number=R. If there is only one value, the `-t VAF` will not try to use DP. With the tags I see are available in your VCF and assuming the first AD value is in fact the number of alternate reads, you could do
```
bctools +fill-tags in.vcf -- -t 'FMT/VAF:1=float(ssum(FMT/AD[:0-])/FMT/DP)'
```
This should fill in the fraction of variant reads vs all reads.

Use this with caution and check sanity of the results - this may silently fail and produce incorrect output as I made some assumptions about your VCF.

**Comment by shadihames** [comment]
Thanks for the recommendations.

Here's the AD, DP and RD header lines:
> ##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">

For the variant I've used as an example, there's only 1 ALT allele. 

The command you suggested outputs VAF results, I will make sure to sanity check the results. I'm not very familiar with VarScan2 but I believe that AD is the number of alternate reads, and RD contains the number of reference reads rather than the standard AD format containing both. I will have a play around with the file. Thanks for the help.

**Comment by pd3** [comment]
If AD is defined as shown above and the site has one alternate allele, then VarScan2 produces incorrect output, there should be two values. Maybe try to raise an issue in VarScan2.

**Comment by shadihames** [comment]
Yeah I thought the same thing, the output doesn't match the header desription. I didn't run these myself they're the TCGA VCFs so I figured all should be good with them, but I'll do some digginng. Thanks.

**Comment by pd3** [comment]
If you are going to use the workaround suggested above, please note I just pushed a commit https://github.com/samtools/bcftools/commit/be18428bd2cd8f6ef2a297e945cf3f7157154bda that highlights and fixes some problems related to the use of incorrect vector lengths in arithmetic expressions.
