### ISSUE TITLE
setGT problem with phased genotypes

### ISSUE THREAD

**Issue by VLoegler** [samtools/bcftools#1844]
Hi, 

I'm using setGT to change half missing genotypes (./1) to fully missing genotypes. The problem is that I have some phased genotypes (ex: 0|.   2|.) and setGT doesn't handle these one. 

Here is the command I used:

`bcftools +setGT -- -t ./x -n .`

The possibility to have `-t .|x` would be very useful.

**Comment by pd3** [comment]
The usage page suggests that both phased and unphased half-missing genotypes are supported
```
./x  .. partially missing (e.g., "./0" or ".|1" but not "./.")
```
however, it turns out this is not the case. The bug is now fixed, thanks for reporting the issue.
