### ISSUE TITLE
get genotype probabilities (GP) from PL values in vcf file

### ISSUE THREAD

**Issue by Silvia-lme** [samtools/bcftools#1845]
I used samtools mpileup to generate PL (the phred-scaled genotype likelihoods). I need to generate vcf/or Beagle file with genotype probabilities (GP). I have found that the script vcf2gen_v1.1.pl will calculate genotype probs from GL or PL, but I cannot find it. Is there some script available that will do the same job?
Thanks.

**Comment by pd3** [comment]
There is the plugin `tag2tag` that can do this:
```
About: Convert between similar tags such as GL,PL,GP or QR,QA,QS.
Usage: bcftools +tag2tag [General Options] -- [Plugin Options]
Options:
   run "bcftools plugin" for a list of common options

Plugin options:
       --GP-to-GL           convert FORMAT/GP to FORMAT/GL
       --GP-to-GT           convert FORMAT/GP to FORMAT/GT by taking argmax of GP
       --GL-to-PL           convert FORMAT/GL to FORMAT/PL
       --PL-to-GL           convert FORMAT/PL to FORMAT/GL
       --QR-QA-to-QS        convert FORMAT/QR,QA to FORMAT/QS
   -r, --replace            drop the source tag
   -t, --threshold <float>  threshold for GP to GT hard-call [0.1]

Example:
   bcftools +tag2tag in.vcf -- -r --gp-to-gl
```
Hope this helps

**Comment by Silvia-lme** [comment]
Thank you so much! I didn't know about the plugin tag2tag, which is very useful to convert between similar tags.
However I need to convert PL to GP, which is not among plugin’s options. Is there some other plugin that can do that?
Please advise. Thanks.

**Comment by Silvia-lme** [comment]
Could you please add plugin option in oposite way:
--GL-to-GP           convert FORMAT/GL to FORMAT/GP

Many thanks.

**Comment by pd3** [comment]
I just pushed the commit https://github.com/samtools/bcftools/commit/38792f87170cd9b3dfc1f46de8b3786ed97fd3e9 that makes the conversion from GL to GP possible, as well as all the other combinations. Please try it out and let me in case of problems.

**Comment by Silvia-lme** [comment]
Thank you so much for this update! It's very helpful.
Please could you advice which Plugin option I have to use for conversion from GL to PL?
Is it --ORI-to-NEW Convert from source tags FORMAT/GL,PL,GP to FORMAT/GL,PL,GP,GT\n"
Thanks

**Comment by pd3** [comment]
Uh, if the usage page is not clear enough, maybe you can help me to draft a better description. Would this make it clearer?
```
     --ORI-to-NEW         Convert from source tag ORI (one of GL,PL,GP) to NEW (GL,PL,GP,GT)
```
or maybe?
```
     --X-to-Y         Convert from source tag X (one of GL,PL,GP) to Y (GL,PL,GP,GT)
```

**Comment by Silvia-lme** [comment]
I think that usage page is clear enough, just plugin --PL-to-GP in unrecognized option in my case. "tag2tag: unrecognized option '--PL-to-GP'"
I only re-wrote tag2tag.c file in plugins folder. Do I need to do something else to activate plug +tag2tag? Thanks

**Comment by pd3** [comment]
Yeah, you need to compile the plugin (`make`) and copy to a directory where bcftools can see it. See the http://samtools.github.io/bcftools/bcftools.html#plugin documentation, specifically search for the BCFTOOLS_PLUGINS variable. Running `bcftools plugin -lvv 2>&1 | less` will tell you where is the program currently looking for plugins.
