### ISSUE TITLE
Possible to get consensus sequence of all samples in  a vcf by one line command?

### ISSUE THREAD

**Issue by WeiCSong** [samtools/bcftools#1847]
Hi bcftools developer,
   I'm using bcftools consensus to get consensus sequence of all samples in a vcf. Currently I have to write a for loop with -sample option to get one fasta file for each sample, which hit the I/O limitation of computer cluster and slow down the program (I processed multiple vcf in parallel). Is it possible to use one line command to generate one large fasta file, containing sequences corresponded to all samples in the vcf? This would be more friendly for parallel computing. Thanks in advance for your help!

**Comment by pd3** [comment]
No, this is not possible and there is no plan to support that, it would be problematic to implement that. How many samples does your VCF have? Maybe you could run first the plugin `+split` to create single sample VCFs, then run consensus on each separately.

**Comment by WeiCSong** [comment]
> No, this is not possible and there is no plan to support that, it would be problematic to implement that. How many samples does your VCF have? Maybe you could run first the plugin `+split` to create single sample VCFs, then run consensus on each separately.

Thanks for the suggestion! I'll try this solution.
