### ISSUE TITLE
bcftools filter based on AD for called genotype

### ISSUE THREAD

**Issue by pontushojer** [samtools/bcftools#1849]
I want to be able to filter variants to a minimum allele depth (AD) for the called genotype. Say that I have a variant with three alleles, GT 0/2 and corresponding AD 12,1,6. If I use something like `-e 'sMIN(AD) < 2'` this would exclude this variant since the first alt, which is not called has too low AD (1 in this case). 

Is there any efficient way to take the genotype into account here? I could do something like `-e 'GT~"0/2" && (AD[0:0] < 2 || AD[0:2] < 2)'` but then I would have to create conditions for every possible genotype.

If there is no easy way to do this, would you consider adding some expression that could evaluate across sample genotypes instead of just samples? Something like `gMIN` or `SMPLGT_MIN` to evaluate the minimum value across samples while considering  genotypes.

**Comment by pd3** [comment]
Alas, we don't have a tool for this. It's difficult to come up with a good language to support general queries of such type. The suggestion `gMIN` or `SMPLGT_MIN` is a good try but it's too tied to this specific use case. I am open to suggestions.

**Comment by pontushojer** [comment]
I see. How about something for accessing the allele index? Something like GT[0:0] to get the first allele index in the genotype for the first sample. This would be similar to how it is array elements like `AD` but for the GT string that would the be split into an array containing the called allele indexes. 

Then one could to something like `- 'AD[0:[GT[0:0]] < 2 || AD[0:[GT[0:1] < 2'` to filter diploid calls in they way I need.

**Comment by pd3** [comment]
I just added a limited support for this, let's see how it goes. It can be used as
```
FORMAT/AD[GT] > 10        .. require support of more than 10 reads for each allele
FORMAT/AD[0:GT] > 10      .. same as above, but in the first sample
sSUM(FORMAT/AD[GT]) > 20  .. require total sample depth bigger than 20
```
Internally this creates a N-dimensional vector where N is the number of unique alleles in the genotype.  So currently it is not possible to query only one of the alleles, I believe such use case would be very rare.
