### ISSUE TITLE
bcftools convert: change formatting of usage message

### ISSUE THREAD

**Issue by jmarshall** [samtools/bcftools#185]
For `bcftools convert`, neither the usage display nor the man page nor the ensuing error message mentions that one of the `-g`, `-G`, `--tsv2vcf`, `--hapsample2vcf`, `-H`, `-h` options **must** be used.  If you don't use any of them there is no specific error message, you just get the usage display which doesn't say what the problem is.

Also the formatting of the usage display makes it unclear that these options take option arguments:
```
GEN/SAMPLE options (input/output from IMPUTE2):
   -G, --gensample2vcf         <prefix>|<gen-file>,<sample-file>
   -g, --gensample             <prefix>|<gen-file>,<sample-file>
       --tag <string>          tag to take values for .gen file: GT,PL,GL,GP [GT]
```
Unlike `--tag <string>` which is formatted clearly, `<prefix>|<gen-...` is lined up with the other descriptions and appears to the uninitiated to be... a synopsis of GEN/SAMPLE format or something.

----

The user on whose behalf this issue is being filed expected that the following would convert a BCF file to VCF:

    bcftools convert -O v -o bar.vcf foo.bcf

but all she could get out of `bcftools convert` was a usage display with no indication of what it didn't like.  She reported frustration with this.  The usage's _About_ says "Converts VCF/BCF to other formats and back", but it's probably unclear to non-maintainers that "other formats" here is intended to mean "foreign non-[VB]CF formats".

This suggests that an alternative to adding an error message might be to have absence of foreign format options mean to convert between flavours of VCF/BCF.  Then the command line above would do what this user was expecting -- `bcftools view` is the full-featured tool for VCF↔︎BCF conversions, but there's probably no reason why `convert` couldn't do simple conversions too, as some uninitiated users may expect.

**Comment by pd3** [comment]
The program now converts also between VCF and BCF similarly to `bcftools view`.

**Comment by jmarshall** [comment]
The formatting of the usage display for `-G, --gensample2vcf ` / `-g, --gensample` remains unclear.

**Comment by pd3** [comment]
I do not intend to change the formatting. In my opinion it is more readable the way it is. It's open for discussion of course, comments are welcome from others.

**Comment by jmarshall** [comment]
Then let's leave the issue open for discussion.
