### ISSUE TITLE
converting genotypes to missing in different samples in different site

### ISSUE THREAD

**Issue by mgrzy** [samtools/bcftools#1850]
Hi,

I am trying to calculate imputation accuracy. For that purpose I want to mask some small fraction of know genotypes, impute and then compare imputed set with true values. For example, suppose I have 5 samples: A, B, C, D and E and I would like to mask (convert to missing) first site (variant) in sample A and B, then fifth site in D and E, and so on... I would like to keep genotypes for rest sample in given site, so if in site one A and B will be masked, I would like to keep genotypes for C,D,E. 

Is there any clever way to do it with bcftools?

Best,
Marcin

**Comment by mgrzy** [comment]
Thank you for quick response. I will deal with it in other way in that case.
It will be great if it will be possible to add such option in future build of bcftools.

**Comment by pd3** [comment]
This is now supported
