### ISSUE TITLE
view -U dropped sites with called genotypes

### ISSUE THREAD

**Issue by BinglanLi** [samtools/bcftools#1851]
Hi,

I am hoping to get some clarification or answer here. `bcftools view -U` excludes sites without a called genotype. In other words, only sites with all missing/uncalled genotypes will be dropped. Is this correct?

I am seeing the following puzzling output from bcftools.

```
$bcftools -v
bcftools 1.16
Using htslib 1.16
Copyright (C) 2022 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$bcftools view -H g6pd_154535277.vcf | cut -f1-15
chrX	154535277	.	T	C	-10	.	AC=17247,20;AF=0.088,0.0001015;AN=197056;AS_QUALapprox=0|1474020|1614;AS_VQSLOD=16.1351,11.983;AS_YNG=Y,G;QUALapprox=85	GT:FT:GQ:RGQ	0/0:.:40:.	0/0:.:40:.	0/1:.:48:85	0/0:.:40:.	0/0:.:40:.	0/0:.:40:.

$bcftools view -H -U g6pd_154535277.vcf | cut -f1-15
(empty output)

$bcftools view -H -u g6pd_154535277.vcf | cut -f1-15
chrX	154535277	.	T	C	-10	.	AC=0;AF=0.088,0.0001015;AN=0;AS_QUALapprox=0|1474020|1614;AS_VQSLOD=16.1351,11.983;AS_YNG=Y,G;QUALapprox=8GT:FT:GQ:RGQ	0/0:.:40:.	0/0:.:40:.	0/1:.:48:85	0/0:.:40:.	0/0:.:40:.	0/0:.:40:.
```

This is a dataset with about 100K samples. I cannot print out the whole output. The dataset has 94 missing genotypes (`./.`) and the rest were called genotypes (`0/0`, `0/1`, or `1/1`). 

I am wondering why this would happen to my dataset.

**Comment by pd3** [comment]
Yes, that's puzzling. The `-u` option should select only sites with all genotypes missing and the `-U` option should select everything but sites with all genotypes missing. Can you please provide a toy VCF with the full header to debug the problem? I was not able to reproduce it.

**Comment by pd3** [comment]
Uh, yes, that explains it. The reason is that, when available, the INFO/AN,AC tags are used to determine missingness to avoid expensive parsing of sample fields. I updated the man page to describe this caveat. In the test file you provided there is another issue, the AC tag is incorrect also in that it has two values although there is only one alternate allele.
To recalculate, run
```
bcftools +fill-tags in.bcf -Ou -- -t AN,AC | bcftools view -u
```
Thanks for the issue, I believe this should solve it.
