### ISSUE TITLE
The problem of bcftools isec.

### ISSUE THREAD

**Issue by 915813786** [samtools/bcftools#1852]
I have a problem with isec function.I totally have 13 populations for vcf files, but when I tried to use the isec function to calculate the unique SNP of a certain population, I found that the result did not exist（unique snp equal 0）

my commond: bcftools isec -n~0010000000000 -c all -p dir 1.bcf.gz 2.bcf.gz 3.bcf.gz 4.bcf.gz 5.bcf.gz 6.bcf.gz 7.bcf.gz 8.bcf.gz 9.bcf.gz 10.bcf.gz 11.bcf.gz 12.bcf.gz 13.bcf.gz --threads 16 

Because I call the snp with the best practice method of gatk, I suspect that it may lead by the 13 populations of joint call, probably because there is no correct filtering process.

**Comment by pd3** [comment]
Can't really help with an issue stated like this, sorry. You'd need to provide a test case that demonstrates that the program is not working as expected.
