### ISSUE TITLE
bcftools consensus Error: Could not parse --haplotype I, expected numeric argument

### ISSUE THREAD

**Issue by thomlmarshall** [samtools/bcftools#1855]
Hi I'm attempting to run bcftools consensus and wanting to print the IUPAC code for all genotypes (command and error message below):

bcftools consensus --sample {1} --haplotype I --absent N --missing N --include '\''TYPE="snp" || TYPE="ref"'\''

Error: Could not parse --haplotype I, expected numeric argument

This is my first time using the consensus tool so I'm a bit unfamiliar with it and would appreciate any insight as to what would be causing this error. 

Thanks!

**Comment by pd3** [comment]
This should work, which version of bcftools are you using?
```
bcftools --version
```
Please see here for instructions how to update http://samtools.github.io/bcftools/howtos/install.html
