### ISSUE TITLE
Split multi-allelic sites

### ISSUE THREAD

**Issue by adrian-keda** [samtools/bcftools#1858]
Hi,

I have to use TCGA data for some analysis. I want to split multi-allelic sites first, but when I run bcftools the following error appears:

  Error: wrong number of fields in FMT/AD at 13:19042593, expected 31167, found 20778

It seems that bcftools is expecting more information for the samples' AD, as it expects 3 times the number of samples (10389). I need these values for some posterior filters.

Thanks for your help!

[test.txt](https://github.com/samtools/bcftools/files/10707984/test.txt)

**Comment by pd3** [comment]
The tag FORMAT/AD is defined as `Number=R`, therefore it expects one number for each allele. At that site there are three alleles, but the VCF contains only two, for example
```
bcftools query test.txt -t 13:19042593 -f '[%CHROM\t%POS\t%REF,%ALT\t%AD\n]' | awk '$5!="."'  | head -3
13	19042593	T,C,A	23,10
13	19042593	T,C,A	8,8
13	19042593	T,C,A	19,15
```
You could work around this by modifying the expected number of AD tag fields in the header to `Number=.`, or if the error is consistent, `Number=A`. This can be done with `bcftools reheader`.
Ideally this would be fixed at the VCF producer's end.
