### ISSUE TITLE
BCFTOOLS consensus -H not applying all variants provided

### ISSUE THREAD

**Issue by IsaacDiaz026** [samtools/bcftools#1859]
Hello,

I am trying to generate two haplotypes for a genome assembly using a set of 1.3 million phased heterozygous SNPs.
I used the following commands:

bcftools consensus -H 1pIu -f $REFERENCE $VCF > haplotype1.fasta
bcftools consensus -H 2pIu -f $REFERENCE $VCF > haplotype2.fasta

For haplotype1 the command reports "Applied 662830 variants"
While for haplotype 2 it reports "Applied 638664 variants"

I am using bcftools/1.16. I have confirmed that there are no overlapping variants, and all SNPs are phased. What would cause half of the SNPs not to be included?

**Comment by pd3** [comment]
I can see how the message is misleading. For any selected haplotype about half of heterozygous genotypes carry the reference allele. Therefore about half, but importantly not exactly half, of the heterozygous genotypes will be considered "variant" in that haplotype and the rest will match the reference allele an the variant will not be "applied". I hope it makes more sense now?
