### ISSUE TITLE
Allele-specific information is not annotated in an allele-specific way

### ISSUE THREAD

**Issue by hbeale** [samtools/bcftools#186]
When my annotation source contains allele-specific information:
##INFO=<ID=exac_AF,Number=A,Type=Float,Description="ExAC allele frequency, for each ALT allele if any, in the same order as listed in the range (0,1)">
chr20   1108122 rs6514113       C       T,G     3.2547e+07      PASS    ...;exac_AF=0.089,8.132e-06;...

and I have a variant with only one of the alleles:
chr20   1108122 rs6514113       C       T       431.77  PASS    

If I annotate it:
/tools/bcftools/1.1/bin/bcftools annotate -a $annoSource  -c INFO/exac_AF --output $annoOutput $vcfToAnno

the result contains info on both alleles:
chr20   1108122 rs6514113       C       T       431.77  PASS    ...;exac_AF=0.089,8.132e-06

but I would like only the relevant info, like this:
chr20   1108122 rs6514113       C       T       431.77  PASS    ...;exac_AF=0.089

I'm using BCFTools Version: 1.1 (using htslib 1.1).

Thanks!

**Comment by pd3** [comment]
This should be resolved by a4ff92e
