### ISSUE TITLE
add caller name in INFO tag

### ISSUE THREAD

**Issue by lmanchon** [samtools/bcftools#1861]
--Hi,

i want to know if it's possible to add the caller name to INFO tag using bcftool annotate and how to ?

thank you --

**Comment by pd3** [comment]
It is possible with the `-m, --mark-sites` option, It was intended for marking sites present in the `-a` file, but one can misuse it and run
```
bcftools annotate -m CALLER_NAME -a file.bcf file.bcf
```

I am thinking it is easy and worthwhile to modify the command to allow just
```
bcftools annotate -m TAG file.bcf
```

**Comment by pd3** [comment]
This is now done
