### ISSUE TITLE
xargs parallelisation & [E::bgzf_uncompress] Inflate operation failed

### ISSUE THREAD

**Issue by aLaine1** [samtools/bcftools#1864]
Note : This question might be more of a "htslib" one.

Hello, I've been working on large scale analysis for some days now and I seem to come across a recurring issue and I can't figure out a way around it.

As I'm working with a large number of VCF files and I have access to enough computing power, I'm trying to use the parallel fonctionnality of xargs.

The command I'm trying to run it the following : 
```
head -100 Burden/BlockList.txt | xargs -I {} -n1 -P32 sh -c "bcftools annotate -R 'Burden/Peaks_to_blocks-20Samples.bed' -x ^FORMAT/GT -Ou 'input_{}.vcf.gz' | bcftools filter -i 'INFO/AF[0]<0.01' -O z -o output_{}.vcf.gz"
```
A strange behavior seems to occur in some instances : 

```
 STDERR [E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible, or in() / out() returned an error
 STDERR [E::bgzf_read_block] Invalid BGZF header at offset 102785006
```
While trying to understand the issue, I tried to run less jobs at a time (by reducing the value of -P parameter of xargs) and it seems like the error doesn't show, so my initial hypothesis would be either a memory or storage issue, but I'm not really sure of what is happening during the "bgzf_uncompress" step.

Strangely enough, when the entire job finishes I end up without any missing output, and none of my outputs are corrupted, so I'm really wondering what is happening...

Do you have any clue ?
Thank you

**Comment by pd3** [comment]
This looks like an issue with the system, not bcftools. Try `strace -f` and `dmesg` (or equivalent) and check if the system reports any I/O related problems.
