### ISSUE TITLE
The depth calling by bcftools is not consistent with true depth

### ISSUE THREAD

**Issue by leon945945** [samtools/bcftools#1866]
Hi, I took use of bcftools to call SNP/Indels, but when I checked the genotype information given by bcftools with IGV, I found the genotype and depth are inconsistent with that given by IGV. 

**The genotype information of bcftools:**
> chr1    1303762 .       T       A       192.044 PASS    MQSBZ=2.13809;FS=0;MQ0F=0;VDB=0.966795;SGB=-0.692067;RPBZ=-0.799755;MQBZ=-0.0854699;BQBZ=0.55842;SCBZ=0;DP=74;AC=1;AN=4;DP4=9,4,0,0;MQ=42       GT:PL:DP:SP:ADF:ADR:AD:SCR      0/0:0,39,255:13:0:9,.:4,.:13,.:1

**The information give by IGV:**
![图片](https://user-images.githubusercontent.com/61004157/219551626-02b2274d-4296-43d0-b729-b2892480baa5.png)

As we can see, bcftools said this site was "0/0", had 13 "T" and no "A", but the true situation is that it had 30 "T" and 13 "A" in IGV. This site had no improperly mapped reads. Lots of sites existed the inconsistent situation, what makes the large difference?

**the bcftools commands I used:**
`bcftools mpileup -O b -m 3 -q 30 -Q 0 -a AD,ADF,ADR,DP,SP,SCR -f ${reference} $bam --output $output`
`bcftools merge sample1.bcf sample2.bcf -o merge.bcf`
`bcftools call -m -v -O b --ploidy 2 -o $output $bcf`
`bcftools filter -g 3 -G 10 -e "(TYPE='snp' && (QUAL < $qual || GT~'\.' || FMT/DP>2*$DP || FMT/DP<0.2*$DP || MQBZ < -(3.5+4*(FMT/DP)/QUAL) || RPBZ > (3+3*(FMT/DP)/QUAL) || RPBZ < -(3+3*(FMT/DP)/QUAL) || FORMAT/SP > (40+(FMT/DP)/2) || SCBZ > (2.5+(FMT/DP)/30))) || (TYPE='indel' && (IDV < 2 || IMF < 0.02+(($qual+1)/($qual+31))*(($qual+1)/($qual+31))/4 || FMT/DP > ($DP/2) * (1.7 + 12/($qual+20)) || MQBZ < -(5+(FMT/DP)/20) || RPBZ+SCBZ > 9))" -o $output $bcf`

Hope for your reply.

**Comment by pd3** [comment]
Apparently some reads were filtered, the minimum MQ was set to 30 in your command, also by default duplicate and supplementary reads are ignored. If you look in the header you'll find that INFO/DP shows the number of raw reads while FORMAT/DP and FORMAT/AD show the number of reads after filtering.

**Comment by leon945945** [comment]
My carelessness, that's the point, thanks very much.
