### ISSUE TITLE
Feature request: bcftools convert --hapsample

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#187]
The conversion from VCF/BCF to WTCCC style haps/sample format would be quite useful to have.  To my knowledge, there is no other program that does this, and I do find myself using an old custom perl script to do this every once in a while.  This would also allow IMPUTE2 to WTCCC haplotypes format conversion through BCF.

**Comment by wkretzsch** [comment]
PS I could give this a shot if nobody else is planning on implementing it.

**Comment by pd3** [comment]
It may take a while, so yes, it would be great if you could do it. Do let me know if you have any questions, I am happy to help.

**Comment by wkretzsch** [comment]
ok, it'll take a few weeks until I get around to it.

**Comment by wkretzsch** [comment]
My changes are addressed with this pull request https://github.com/samtools/bcftools/pull/197
