### ISSUE TITLE
Problem when trying to split a VCF file into SNP and indel

### ISSUE THREAD

**Issue by ana-carolina-sa** [samtools/bcftools#1872]
Hello, 

I am running bcftools-1.17 using Windows subsystem for Linux and I am trying to split a VCF file into SNPs and indels. 

Here is the code I have been using:

``
bcftools index 1001genomes_snp-short-indel_only_ACGTN.vcf.gz
``
``
bcftools view -v snps 1001genomes_snp-short-indel_only_ACGTN.vcf.gz -Oz -o 1001genome_SNPs.vcf.gz
``

The last command initially seems to work, but after a few minutes I receive the following message:

``
^Z[1]+  Stopped        
         bcftools view -v snps 1001genomes_snp-short-indel_only_ACGTN.vcf.gz -Oz -o 1001genome_SNPs.vcf.gz
``
Would you have a suggestion on why this is happening? I searched online, but could not find the answer.

I also attached a screenshot of the terminal. 
![split_snps_indels_bcftools_ubuntu](https://user-images.githubusercontent.com/79209566/221243064-b52616fc-106c-4f32-8083-29e578a8454e.png)
Thank you in advance,

**Comment by pd3** [comment]
It seems you pressed ctrl+z, or copy and pasted something that generated that key stroke, which paused the job. If you want to re-enable the process, you can either type `fg` to let it run in the foreground or `bg` to let it run in the background.

This is a basic shell usage question unrelated to bcftools. You should be able to find the answer immediately if you just searched online for `^Z[1]+ Stopped`. In fact the very first result google returns is a link to https://unix.stackexchange.com/questions/109536/if-you-z-from-a-process-it-gets-stopped-how-do-you-switch-back-in
