### ISSUE TITLE
bcftools roh is suitable for vcf files called with a ploid level of 4? 

### ISSUE THREAD

**Issue by fisherman2023** [samtools/bcftools#1873]
Recently, I am doing runs of homozygosity identification analysis for polyploid species. In my opinion, bcftools is developed for diploids, however, when I give a vcf file called with a ploidy level of 4, it works well. So, I want to know if the results are reliable. Thanks very much!

**Comment by pd3** [comment]
The math of RoH really assumes diploid genotypes, see the model here http://samtools.github.io/bcftools/bcftools.html#roh.

Although it may print something and even get certain polyploid cases right, I wouldn't trust the results in general.
