### ISSUE TITLE
INFO and FORMAT columns tags

### ISSUE THREAD

**Issue by irbinveliz** [samtools/bcftools#1874]
Hello everyone! I am trying to call genotype likelihoods from my BAM files. I want to have the INFO column with the tags NS and AF and the FORMAT column with the tags GT:DP:AD:GQ:GL. 

I am using bcftools version 1.11 and this is what I am running:

`bcftools mpileup -d 1000 -Ov -a 'INFO/NS,INFO/AF,FORMAT/GT,FORMAT/DP,FORMAT/AD,FORMAT/GQ,FORMAT/GL' -f $reference $input | bcftools call -mv -Ov -o $output `

However I get the message:
`Could not parse tag "INFO/NS" in "INFO/NS,INFO/AF..."`

I have tried to change the argument -a but it doesn't fix this message.

When I run:
`bcftools mpileup -d 1000 -Ov -f $reference $input | bcftools call -mv -Ov -o $output`
It works but I get GT and PL in the FORMAT column. 

This is an example of one file:
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	BOR_059_Tmontana`
`uce-2_consensus	624	.	G	GGCCCGAT	228	PASS	INDEL;IDV=15;IMF=0.75;DP=20;VDB=0.542123;SGB=-0.688148;MQ0F=0;AC=2;AN=2;DP4=0,5,0,15;MQ=60	GT:PL	1/1:255,6,0`

I want to have the tags as specified at the beginning in order to filter the variants using an R package called SNPfiltR. I have seen that the plugin "tag2tag" can transform the PL to GL but I was wondering if there was a way to call GL instead of PL directly when running bcftools call.

Thank you in advance!

**Comment by pd3** [comment]
First of all, please update your bcftools installation, we are at 1.17 now. Next, to check which optional tags are available in your version, run `bcftools mpileup -a \?` and `bcftools call -a \?`. Additionally, the plugin fill-tags can add more, the list of available tags can be printed with `bcftools +fill-tags -- -l`
