### ISSUE TITLE
bcftools filter query

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#1876]
Hi,

Just wanted to know the best practice here while using filtering VCF records while combining metrics from INFO and FORMAT fields.

In the first case, I wish to remove monomorphic records and any record where there is a missing value and does not have a PASS and I am using this after I perform some genotype filtering:

`bcftools filter -e "FMT/GQ<$2" --set-GTs .|bcftools filter -e 'AC==0 || AC==AN || GT[*] = "./." || %FILTER!="PASS"'`

In the second case, I am trying to remove  monomorphic records, does not have a PASS and remove any record where there is 90% missingness. 

`bcftools filter -Ov -o temp.vcf -e 'AC==0 || AC==AN || %FILTER!="PASS"' || 'F_MISSING > 0.9' `

Is it better to use the expressions separately and not perform the filtering like I have performed?

Regards,
Prasun

**Comment by pd3** [comment]
They can be combined. I haven't tested, but this should work
```
bcftools view -e 'AC==0 || AC==AN || FMT/GQ<20 || FMT/GT="mis"'
```

As a side note, when streaming from one bcftools command to another, include `-Ou` for efficiency.

**Comment by prasundutta87** [comment]
Thanks a lot for this and the suggestion. @pd3 ! I will try this out!
