### ISSUE TITLE
ukb - Merging Y chromosome VCF file having different number of samples

### ISSUE THREAD

**Issue by SHASANKsp** [samtools/bcftools#1884]
Hello everyone,

I am new to GWAS analysis and am using the ukb-imputed WGS data. I have converted the BGEN files of all the chromosomes to VCF format and now wanted to merge all the vcf files.

Was trying to merge using bcftools "concat" but in the case of Y chromosome it has only male samples which throws an error: "unequal number of samples" while trying to merge.

Also, I am assuming that bcftools "merge" wouldn't work as it would give an error of duplicate samples.

I would be grateful if anyone can kindly help me find a way to merge Y chromosome vcf file with other vcf files. 

Thank you.

**Comment by pd3** [comment]
Indeed, concatenating will not work if the input VCFs do not have the same samples or the samples are not in the same order. Therefore the first step will be to add the missing female samples in the VCF. This could be done by creating an empty VCF which consists just of an header and the female samples on the `#CHROM` line. Then it should be possible to run
```
bcftools merge chrY-male-samples.vcf.gz empty-female-samples.vcf.gz -o chrY-all-samples.bcf
```
In the next step you'll need to enforce the same sample ordering as in the other chromosomes, for example as
```
bcftools query -l chrX.vcf.gz > samples.txt
bcftools view -S samples.txt chrY-all-samples.bcf -o chrY-all-samples-sorted.bcf
```
If all the steps above work as expected, it should be possible to concatenate the result.
