### ISSUE TITLE
WRONG reference alleles

### ISSUE THREAD

**Issue by SC-Duan** [samtools/bcftools#1885]
Hi,
I used bcftools to merge two vcf files, I found the REF and ALT were exchanged  for some SNPs . Is it correct?
When I annotate SNPs using ANNOVAR, it says "WARNING: 7806 exonic SNPs have WRONG reference alleles specified in your input file!".
Thank you!

**Comment by pd3** [comment]
No, that should never happen, more likely the input files were already broken. If you believe `bcftools merge` is responsible, please provide a small test case to reproduce the problem.

**Comment by pd3** [comment]
Sorry, did not mean to close, pressed the wrong button

**Comment by SC-Duan** [comment]
Thank you!
