### ISSUE TITLE
merge without updating AN and AC

### ISSUE THREAD

**Issue by Dongmeng-wang** [samtools/bcftools#1887]
Hi, I was trying to merge a few VCF files with the same AC and AN for each SNP but different samples. I was wondering if it's possible to merge these files without updating AC and AN, just like `--no-update` for `bcftools view`? Thank you so much for your help.

All the best,
Diana

**Comment by pd3** [comment]
It does not really make sense to leave AC and AN unchanged as these tags have a well defined meaning reserved by the VCF specification. Say there are two input files with equal number of samples, then merging them must double the AN count. Also, assuming both files have INFO/AN, which of the two values would you like to see on the output when you say "unchanged"?

Having said that, one can use the option `-i, --info-rules TAG:METHOD` and use for example `min` or `max` for METHOD. If only one of the input files had the AN annotation, then the value will be carried over to the output this way.

**Comment by Dongmeng-wang** [comment]
Hi, thank you so much for your reply. I'll make it more clear. I have 300 individuals; some have repeated visits, and the number of visits is different. Some of them visited 2 times and others may visit up to 5 times. I have an original VCF file including these 300 individuals, and now I'm trying to get a merged VCF with all the visits of these individuals, and the sample ID will be `indvidual_number`. So in this case I don't want to change any INFO from the original file because the unique individuals in the merged file are still 300. It may still not make sense to you to get a VCF file with repeated individuals, but I'm doing a longitudinal analysis, which requires the sample ID in the VCF file to be the same as the sample ID  in the covariate files.

I have tried to only keep the INFO in one file and remove the INFO of the rest files with `bcftools annotate -x INFO`, and then merge these files with `bcftools merge --info-rules AN:max,AC:max`. However, the AN and AC in the output file are still updated.  For example :
`zcat HRC_r1.1_MM_chr3_2MZ.B38_QCed_MAF0.01.RNASeqID.908.3.vcf.gz| less`
3       18519   3:18519_G/A     G       A       .       PASS    AF=0.0584416;MAF=0.0584416;R2=0.87701;AN=616;AC=36 
`zcat HRC_r1.1_MM_chr3_2MZ.B38_QCed_MAF0.01.RNASeqID.908.7.vcf.gz| less`
3       18519   3:18519_G/A     G       A       .       PASS    .      
`bcftools merge --info-rules AN:max,AC:max HRC_r1.1_MM_chr3_2MZ.B38_QCed_MAF0.01.RNASeqID.908.3.vcf.gz HRC_r1.1_MM_chr3_2MZ.B38_QCed_MAF0.01.RNASeqID.908.7.vcf.gz | less`
3       18519   3:18519_G/A     G       A       .       PASS    AF=0.0584416;MAF=0.0584416;R2=0.87701;AN=634;AC=36

Could you give me a clue about what might be wrong with the code? Thank you so much for your help.

All the best,
Diana

**Comment by Dongmeng-wang** [comment]
Hiya, the code works after I updated bcftools to the latest version. Thanks for your help! 

All the best,
Diana

**Comment by pd3** [comment]
Oh, good. I was going to suggest that it might be better to create a custom tag, for example `INDIV_AN/AC`, to avoid the danger of programs recalculating `AN/AC` to conform to VCF specification.
