### ISSUE TITLE
bcftools norm that gives "split multiallelics" uses the input tags for new output lines

### ISSUE THREAD

**Issue by cpenkett** [samtools/bcftools#189]
Hi devs,

I'm normalising a VCF file to have alternate alleles on separate lines like this:

% bcftools norm -m -any -O z test_18.gz > test_18.norm.gz

But the output lines then have the wrong tags such as AD being 1,15,11 even though there is only one alternate allele in the new line.

Original file:

% zcat test_18.gz | grep -v ^# | awk 'length($4) == 1 && $5 ~ /,/' | head -1
18    542409    rs56895150,rs35667938    G    GA,GAA    147.00 PASS CIGAR=1M1I,1M2I;RU=A,A;REFREP=10,10;IDREP=11,12;MQ=0;MQRankSum=0;BaseQRankSum=0;ReadPosRankSum=0 GT:GQ:GQX:DPI:AD    1/2:153:153:39:1,15,11

becomes this:

% zcat test_18.vcf.norm.vcf.gz | awk '$2 == 542409'
18    542409    .    G    GA    147    PASS CIGAR=1M1I;RU=A;REFREP=10;IDREP=11;MQ=0;MQRankSum=0;BaseQRankSum=0;ReadPosRankSum=0GT:GQ:GQX:DPI:AD 1/0:153:153:39:1,15,11
18    542409    .    G    GAA    147    PASS CIGAR=1M2I;RU=A;REFREP=10;IDREP=12;MQ=0;MQRankSum=0;BaseQRankSum=0;ReadPosRankSum=0GT:GQ:GQX:DPI:AD 0/1:153:153:39:1,15,11 

Notice that other fiels like GQ, and SNP quality are the same for both lines which can't be right.

AD format line in VCF file is this.

##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed. For indels this value only includes reads which confidently support each allele (posterior prob 0.999 or higher that read contains indicated allele vs all other intersecting indel alleles)">

Thanks,
Chris

**Comment by pd3** [comment]
Hi,
yes, the program does not change the qualities, but that is intended. This feature focuses on genotypes and genotype likelihoods, sorry to disappoint you.

**Comment by mcshane** [comment]
If the FORMAT/AD line were labelled as `Number=R` rather than `Number=.` then bcftools would have the information needed to split up that field as you're wanting. GQ and QUAL are calculated by things not encoded in the VCF, so not really possible to recalculate when splitting.
