### ISSUE TITLE
bcftools concensus -H for non-diploid/polyploids?

### ISSUE THREAD

**Issue by peterdfields** [samtools/bcftools#1892]
Hi,

I was just wondering if there is any way to apply `bcftools concensus` in order to output distinct haplotypes with IUPAC codes for for unphased sites when dealing with non-diploid data? Specifically, when I set `-H 3` or `-H 4` the approach works fine, but if I try `-H 3pIu` or `-H 4pIu` I get an error like the following:
 `Error: Could not parse --haplotype 4pIu, expected numeric argument`
Maybe there's a simple fix to allow the same behavior as `-H 1pIu or 2pIu`?

**Comment by pd3** [comment]
This is now supported. Thanks for the issue

**Comment by peterdfields** [comment]
@pd3 thank you for the modification!
