### ISSUE TITLE
convert vcf to gvcf

### ISSUE THREAD

**Issue by AndressaOL** [samtools/bcftools#1896]
I have vcfs files from wgbs bam files. I would like to know if is possible to use bcftools to convert vcfs to gvcfs. 
input:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  bcell_SG50
NC_052532.1     14886   .       C       G       0       PASS    NS=1:DP=10      GT:GQ:DP        0/1:0:10
NC_052532.1     14956   .       G       T       0       PASS    NS=1:DP=10      GT:GQ:DP        0/1:0:10
NC_052532.1     14957   .       C       T,Y     0       PASS    NS=1:DP=10:GU=T/C       GT:GQ:DP        1/2:0:10
NC_052532.1     15109   .       A       G,R     0       PASS    NS=1:DP=20:GU=A/G       GT:GQ:DP        1/2:0:20
NC_052532.1     16181   .       A       G,R     0       PASS    NS=1:DP=8:GU=A/G        GT:GQ:DP        1/2:0:8
NC_052532.1     16194   .       C       R       0       PASS    NS=1:DP=8:GU=A/G        GT:GQ:DP        0/1:0:8
NC_052532.1     16506   .       T       C,Y     0       PASS    NS=1:DP=6:GU=T/C        GT:GQ:DP        1/2:0:6

Thanks for your support.

**Comment by pd3** [comment]
Not sure what exactly you mean, but the short answer is no: gVCF contains additional information that cannot be recovered from a VCF you're showing.
