### ISSUE TITLE
Appropriate citation version and format for current variant call file format specification

### ISSUE THREAD

**Issue by vlaufer** [samtools/bcftools#1897]
Apologies for using the issue format to ask this. 

I think that based on reading Samtools documentation that it is preferred that we cite BCFv2 is this correct? In addition, if we do so, is it preferred that we cite the specification document itself or a Samtools/bcftools publicatiion (e.g. as at https://www.htslib.org/doc/#publications)? The context is for a review manuscript, so I would like to have the most up to date recommendation i can get.

Thank you for your great work.

**Comment by pd3** [comment]
From what you write I am not sure which of the formats are you after. For VCF this paper http://www.ncbi.nlm.nih.gov/pubmed/21653522, for BCF probably https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3198575/ and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7931820/. For both it might good to include also the URL http://samtools.github.io/hts-specs/. Hope this helps
