### ISSUE TITLE
bcftools csq with ucsc gff3

### ISSUE THREAD

**Issue by marissa97** [samtools/bcftools#1898]
Hallo, I want to find the functional consequences for the variants in vcf file. I have been using bcftools csq, however the problem is, that I want to use ucsc and have been using gff3 from Ensemble. I could not find the gff3 from ucsc, only gtf. Can you maybe give me some suggestions ? Thank you

**Comment by pd3** [comment]
The two file formats are not worlds apart, but it depends. Don't know if your GTF contains all the necessary information, see the documentation to check the required GFF structure here: 

https://github.com/samtools/bcftools/blob/e3dda270c44ebd0781f1e825aeafa117bc885049/doc/bcftools.txt#L1314-L1342

**Comment by marissa97** [comment]
The gtf structure is quite different, there is no Parent-structure in ucsc-gtf. I tried to used ncbi gff3 now, with a slightly different format, it still does not work. I used ncbi gff3 from following link: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000001405.25/ 
(Download > Refseq only > gff)

**Comment by pd3** [comment]
Please check if you are working with the latest version of bcftools and if you think there is a problem, please provide a small VCF test case to reproduce the problem. I believe the program should be able to parse NCBI's GFF.

**Comment by marissa97** [comment]
I am using bcftools 1.10.2 
Here is a sub-set of a test file:

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	9440
chr1	977330	rs2799066	T	C	5202.06	.	AC=2;AF=1;AN=2;BaseQRankSum=-1.607;DB;DP=167;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;MQRankSum=0;QD=31.34;ReadPosRankSum=-0.523;SOR=0.609	GT:AD:DP:GQ:PL:VF:GQX	1/1:1,165:166:99:5216,455,0:0.993976:99
chr1	981931	rs2465128	A	G	8099.06	.	AC=2;AF=1;AN=2;DB;DP=247;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=33.61;SOR=0.843	GT:AD:DP:GQ:PL:VF:GQX	1/1:0,241:241:99:8113,715,0:1:99
chr1	982994	rs10267	T	C	4726.06	.	AC=2;AF=1;AN=2;DB;DP=140;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=33.76;SOR=0.844	GT:AD:DP:GQ:PL:VF:GQX	1/1:0,140:140:99:4740,420,0:1:99
chr1	984302	rs9442391	T	C	4414.06	.	AC=2;AF=1;AN=2;DB;DP=157;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=30.23;SOR=0.693	GT:AD:DP:GQ:PL:VF:GQX	1/1:0,146:152:99:4428,437,0:0.960526:99
chr1	987200	rs9803031	C	T	4439.06	.	AC=2;AF=1;AN=2;DB;DP=131;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=34.15;SOR=0.966	GT:AD:DP:GQ:PL:VF:GQX	1/1:0,130:130:99:4453,390,0:1:99
chr1	990280	rs4275402	C	T	7236.06	.	AC=2;AF=1;AN=2;DB;DP=193;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=25.36;SOR=1.931	GT:AD:DP:GQ:PL:VF:GQX	1/1:0,190:190:99:7250,570,0:1:99
chr1	1269554	rs307377	T	C	9079.06	.	AC=2;AF=1;AN=2;BaseQRankSum=1.19;DB;DP=302;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;MQRankSum=0;QD=32.2;ReadPosRankSum=0.948;SOR=0.878	GT:AD:DP:GQ:PL:VF:GQX	1/1:2,280:282:99:9093,797,0:0.992908:99
chr1	1635004	rs874516	T	C	2781.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-0.193;DB;DP=205;ExcessHet=3.0103;FS=1.714;MLEAC=1;MLEAF=0.5;MQ=55.75;MQRankSum=-6.805;QD=13.64;ReadPosRankSum=-0.231;SOR=0.849	GT:AD:DP:GQ:PL:VF:GQX	0/1:96,108:204:99:2789,0,2663:0.529412:99
chr1	1635749	rs1136997	C	A	3878.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=2.34;DB;DP=234;ExcessHet=3.0103;FS=6.52;MLEAC=1;MLEAF=0.5;MQ=54.07;MQRankSum=-4.721;QD=17.24;ReadPosRankSum=0.361;SOR=1.086	GT:AD:DP:GQ:PL:VF:GQX	0/1:95,130:225:99:3886,0,2369:0.577778:99
chr1	1636044	rs1059822	G	A	3076.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=0.93;DB;DP=221;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.5;MQ=50.77;MQRankSum=-8.235;QD=14.18;ReadPosRankSum=-0.035;SOR=0.71	GT:AD:DP:GQ:PL:VF:GQX	0/1:108,109:217:99:3084,0,2912:0.502304:99`

I used following code: `bcftools csq -f hg19GenRef.fa -g genomic_chr.gff3 test.vcf -Ov -o testInfo.vcf -pR`

This is the logs:
`Parsing genomic_chr.gff3 ...
ignored: chr1	RefSeq	region	1	249250621	.	+	.	ID=NC_000001.10:1..249250621;Dbxref=taxon:9606;Name=1;chromosome=1;gbkey=Src;genome=chromosome;mol_type=genomic DNA
ignored: chr1	BestRefSeq	pseudogene	11874	14409	.	+	.ID=gene-DDX11L1;Dbxref=GeneID:100287102,HGNC:HGNC:37102;Name=DDX11L1;description=DEAD/H-box helicase 11 like 1 (pseudogene);gbkey=Gene;gene=DDX11L1;gene_biotype=transcribed_pseudogene;pseudo=true
ignored: chr1	BestRefSeq	transcript	11874	14409	.	+	.ID=rna-NR_046018.2;Parent=gene-DDX11L1;Dbxref=GeneID:100287102,Genbank:NR_046018.2,HGNC:HGNC:37102;Name=NR_046018.2;gbkey=misc_RNA;gene=DDX11L1;product=DEAD/H-box helicase 11 like 1 (pseudogene);pseudo=true;transcript_id=NR_046018.2
[csq.c:729 gff_id_parse] Could not parse the line, "Parent=transcript:" not present: chr1	BestRefSeq	exon	11874	12227	.	+	.	ID=exon-NR_046018.2-1;Parent=rna-NR_046018.2;Dbxref=GeneID:100287102,Genbank:NR_046018.2,HGNC:HGNC:37102;gbkey=misc_RNA;gene=DDX11L1;product=DEAD/H-box helicase 11 like 1 (pseudogene);pseudo=true;transcript_id=NR_046018.2`

and no output ..

**Comment by pd3** [comment]
You'll need to update to the latest version 1.17. There was an update to GFF parsing code which, I tried, works with https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000001405.25/

**Comment by pd3** [comment]
Just to confirm, I was able to reproduce the problem now, previously most likely ended up testing a different GFF file.

**Comment by pd3** [comment]
I just pushed a commit which should make parsing of your GFF possible. Please try it out

**Comment by marissa97** [comment]
Hey! Sorry for the late reply, i just have time to try it today. I installed bcftools through http://www.htslib.org/download/. How can I tested your commit? I have clone your repositories as written http://samtools.github.io/bcftools/howtos/install.html , however it still calls the bcftools from the first download.

**Comment by pd3** [comment]
If your clone is in `/path/to/bcftools-git-clone` and the compilation was successful, there will be a bcftools binary in that directory. You can run it as `/path/to/bcftools-git-clone/bcftools`.

**Comment by marissa97** [comment]
Hello, now i am getting a new error message:

```
Parsing /home/marissa/Downloads/genomic_chr.gff3 ...
Warning: Ignoring transcript with unknown biotype .. chr1	BestRefSeq	transcript	11874	14409	.	+	.	ID=rna-NR_046018.2;Parent=gene-DDX11L1;Dbxref=GeneID:100287102,Genbank:NR_046018.2,HGNC:HGNC:37102;Name=NR_046018.2;gbkey=misc_RNA;gene=DDX11L1;product=DEAD/H-box helicase 11 like 1 (pseudogene);pseudo=true;transcript_id=NR_046018.2
Warning: The GFF contains features with duplicate id .. chr1	RefSeq	cDNA_match	1588825	1588948	.	-	.	ID=f3da58d96790abfb3974185d5b339f6d;Target=NM_001787.3 92 215 +;consensus_splices=32;exon_identity=0.993858;for_remapping=2;gap_count=2;identity=0.907621;idty=1;matches=2751;num_ident=2751;num_mismatch=3;pct_coverage=90.8611;pct_coverage_hiqual=90.8611;pct_identity_gap=99.3858;pct_identity_ungap=99.8911;product_coverage=0.91323;rank=1;splices=32
Note: truncated transcript rna-NM_001306072.3 with incomplete CDS (this is very common)
Error: CDS overlap in the transcript rna-NM_001172437.2: 94292646-94293825 and 94293825-94294994, is this intended (e.g. ribosomal slippage)?

       Use the --force option to override (at your own risk).
```

When i use --force:

```
Parsing /home/marissa/Downloads/genomic_chr.gff3 ...
Warning: Ignoring transcript with unknown biotype .. chr1	BestRefSeq	transcript	11874	14409	.	+	.	ID=rna-NR_046018.2;Parent=gene-DDX11L1;Dbxref=GeneID:100287102,Genbank:NR_046018.2,HGNC:HGNC:37102;Name=NR_046018.2;gbkey=misc_RNA;gene=DDX11L1;product=DEAD/H-box helicase 11 like 1 (pseudogene);pseudo=true;transcript_id=NR_046018.2
Warning: The GFF contains features with duplicate id .. chr1	RefSeq	cDNA_match	1588825	1588948	.	-	.	ID=f3da58d96790abfb3974185d5b339f6d;Target=NM_001787.3 92 215 +;consensus_splices=32;exon_identity=0.993858;for_remapping=2;gap_count=2;identity=0.907621;idty=1;matches=2751;num_ident=2751;num_mismatch=3;pct_coverage=90.8611;pct_coverage_hiqual=90.8611;pct_identity_gap=99.3858;pct_identity_ungap=99.8911;product_coverage=0.91323;rank=1;splices=32
Note: truncated transcript rna-NM_001306072.3 with incomplete CDS (this is very common)
Warning: GFF contains overlapping CDS rna-NM_001172437.2: 94292646-94293825 and 94293825-94294994.
Indexed 67150 transcripts, 767984 exons, 691224 CDSs, 0 UTRs
Warning: 33328 warnings were supressed, run with `--verbose 2` to see them all
Calling...
Error: the fasta reference does not match the VCF REF allele at chr1:111957501 .. fasta=C vcf=*
```

I used fasta ref from ncbi as well hg19.

**Comment by pd3** [comment]
Unfortunately this does not give enough information, it also confuses me that you're showing an annotated line, so where the error comes from? Can you please provide a small test case, the reference, GFF and the VCF, best in a separate issue?

**Comment by pd3** [comment]
Best if you can provide a link for us to download? As a last resort you could use a temporary storage, for example somewhere like https://wetransfer.com/

**Comment by pd3** [comment]
I've got the test data, thank you. Can you show also the exact command you are running?

**Comment by pd3** [comment]
Okay, I misunderstood: you were getting an error only when the `--force` option was not given but it worked otherwise.

That was the expected behavior because at the time of writing the code I did not have enough GFFs to test overlapping coding exons within the same transcript. Therefore the program would exit with an error and give a hint for the user to check manually if this was due to a ribosomal slippage. (This is usually part of the GFF annotation file.)

There is a new commit now https://github.com/samtools/bcftools/commit/a8249495a6b8360bb8a0e447da0cc0a372a98a46 which makes overlapping CDS into a warning instead of an error.

I consider this problem fully resolved now, please open a new issue if anything else crops up.

**Comment by marissa97** [comment]
No, I get an error without `--force` as well

**Comment by pd3** [comment]
Then please show what the output looks like. I only see the ouput without the `--force` option and I was not able to reproduce the error with your data myself.

**Comment by marissa97** [comment]
It works now! Thank you for your cooperation and support!
