### ISSUE TITLE
query INFO field with ID containing special characters

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#190]
I am trying to query a VCF file with a "dbNSFP_GERP++_NR" INFO field. I am trying the command:
bcftools query -f '%INFO/dbNSFP_GERP++_NR\n' input.vcf.gz
However, I get the error:
Error: no such tag defined in the VCF header: INFO/dbNSFP_GERP
My understanding is that "+" is considered an arithmetic operator (see http://samtools.github.io/bcftools/bcftools.html#expressions). However I don't see "+" as not allowed in the VCF specification (see http://samtools.github.io/hts-specs/VCFv4.2.pdf).
Is there a way to specify to bcftools that the "+" is part of the ID, or is this considered like breaking the VCF standard?

**Comment by pd3** [comment]
Hi, the '+' character is not supported in VCF tag names by bcftools. The upcoming version of the VCF specification corrects its mistake and makes the definition more strict by the regular expression: `^[A-Za-z_][0-9A-Za-z_.]*`.

The draft of VCFv4.3 is now available on
http://samtools.github.io/hts-specs
