### ISSUE TITLE
Another random failure on windows CI.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#1902]
This one is a different location.  These two runs were done locally under MINGW/MSYS64, and I haven't seen it fail in this way via AppVeyor.  That doesn't mean it won't, as it's another stochastic failure.

```
test_vcf_merge:
        C:/msys64/home/jkbon/bcftools/bcftools merge --no-version --force-samples C:/msys64/tmp/P9azsWao0l/mer
ge.LPL.a.bcf C:/msys64/tmp/P9azsWao0l/merge.LPL.b.bcf C:/msys64/tmp/P9azsWao0l/merge.LPL.c.bcf

        The outputs differ:
                C:/msys64/home/jkbon/bcftools/test/merge.LPL.1.out
                C:/msys64/home/jkbon/bcftools/test/merge.LPL.1.out.new
                        13c13
                        < 1     30001   .       C       CA,CC,CG        .       .       .       GT:PL:GL:AD:DF
:DD     0/1:10,0,10,.,.,.,.,.,.,.:10,0,10,.,.,.,.,.,.,.:1,2,.,.:0.1,0.2,.,.:1,.,.       0/2:10,.,.,0,.,10,.,.,
.,.:10,.,.,0,.,10,.,.,.,.:1,.,2,.:0.1,.,0.2,.:.,1,.     0/3:10,.,.,.,.,.,0,.,.,10:10,.,.,.,.,.,0,.,.,10:1,.,.,
2:0.1,.,.,0.2:.,.,1
                        ---
                        > 1     30001   .       C       CA,CC,CG        .       .       .       GT:PL:GL:AD:DF
:DD     0/1:10,0,10,.,.,.,.,.,.,.:10,0,10,.,.,.,.,.,.,.:1,2,.,.:0.1,0.2,.,.:.   0/2:10,.,.,0,.,10,.,.,.,.:10,.
,.,0,.,10,.,.,.,.:1,.,2,.:0.1,.,0.2,.:.,1,.     0/3:10,.,.,.,.,.,0,.,.,10:10,.,.,.,.,.,0,.,.,10:1,.,.,2:0.1,.,
.,0.2:.,.,1
.. failed ...
```

I repeated "make check" immediately after the failure and that time it worked fine.

There is also no documentation on what DF and DD tags are.  I can't find them in the VCF spec, nor in bcftools.txt, nor even doing a grep through the source code.  What are these tags?  How *should* they be merged?

I've not noticed this fail on linux, but given it's a random chance on windows and we don't know the cause, it could perhaps still happen.

**Comment by pd3** [comment]
All tags are defined in the header and the definitions there contain everything what is needed to understand what the merge operation should do (i.e. Number and Type fields). The VCF specification lists only reserved tags and people use custom tags all the time for their unique analyses, this is perhaps a bit different from SAM.

Unfortunately, I am unable to reproduce the error on my machines and also don't have any warnings from valgrind either.

**Comment by jkbonfield** [comment]
All well and good being in the header, but the use of a randomly generated tmp dir unfortunately meant I couldn't inspect them.  I've tried reproducing this 100x now in a loop with an explicitly specified test output dir, so the results don't get nuked, and it worked 100 times. Sigh.

I'm just seeing randomness somewhere and don't know why.  Is any of this data randomly generated so potentially different on every invocation of the tests?  (I know it is elsewhere, which is what I suspect is causing sporadic failures in develop atm.)  If so then it may explain random glitches like this.

Note I think the test harness is also possibly discarding some error messages.  I just now broke my running tests because I modified the test.pl to put in some other debugging and when I did make check it rebuilt the executables again (I assume some commit-hash is getting coded into a header file somewhere), and in doing so briefly broke the running tests.  However the test there that failed just failed with a diff.  There was absolutely no complaint about missing executable, bus error, or any other number of potential failings.  It simply generated a zero length output.  I'm 99% sure I wasn't rebuilding anything when I got the error reported in this issue, but it concerns me that the test harness is hiding error messages from us.  There may have been a more obvious reason for the error that we're not seeing.

**Comment by pd3** [comment]
No, there is no randomness in the algorithm or the tests here. The merging code is complex, possibly something is accessing memory location it shouldn't, but would expect valgrind to pick this up.

The critical subroutine `_cmd3`. It is not trying to hide anything, but I can imagine some messages may get lost when a shell command with pipes is passed https://github.com/samtools/bcftools/blob/60c65eb96e3179953489ecd8d2b7454d62206e3f/test/test.pl#L1004

**Comment by jkbonfield** [comment]
Maybe it's just something broken in msys64 then.  It wouldn't surprise me as it's pretty clunky. :/

**Comment by pd3** [comment]
This appears to be solved.
