### ISSUE TITLE
[E::bgzf_read_block] bcftools 

### ISSUE THREAD

**Issue by emilyn16** [samtools/bcftools#1905]
Hello,
I am currently working on gvcf files that were generated using elprep and am trying to merge them into one gvcf file. 
Before I can merge these files, I had to bgzip my vcf files using: `bcftools view -Oz -o sample.vcf`
Then I had to index them using: `bcftools index sample.vcf.gz`
I was able to bgzip all samples. There was only one sample I was unable to index. 
When I try to index using this command: `bcftools index PhDW_Efish.maxfilter150.vcf.gz`
I get this error:
index: the input is probably truncated, use -f to index anyway: `PhDW_Efish.maxfilter150.vcf.gz`
I then run this command: `bcftools index -f PhDW_Efish.maxfilter150.vcf.gz`
Then I get this error: 
[E::bgzf_read_block] Failed to read BGZF block data at offset 13399006 expected 7960 bytes; hread returned 3088
index: failed to create index for "PhDW_Efish.maxfilter150.vcf.gz"

**Comment by pd3** [comment]
The error message suggests that something went wrong while compressing the file. I don't know if it's just a typo, but the command as you show it would overwrite the input file. It should look like this:
```
bcftools view -o output.vcf.gz input.vcf
```
Try to redo the command, the indexing step shouldn't give any errors. Although the `-f` option is suggested by the error message, it is unlikely to help. The integrity of the input and output file can be verified by visually checking the last line of the file, for example as
```
bcftools view file.vcf | tail -2
```

As a side note, in most recent versions of bcftools it is not necessary to state the output type with `-Oz` if the file type can be guessed from the file name suffix.

**Comment by emilyn16** [comment]
Thanks I reran it and it worked! I did forget to add my output file names as well in the example I gave.
