### ISSUE TITLE
plugin +mendelian2 not recognizing options correctly when using .ped file inputs

### ISSUE THREAD

**Issue by jrharting** [samtools/bcftools#1906]
trying out the new +mendelian2 package, I am wondering of some options are not specified?

```
$ bcftools +mendelian2 myvariants.bcf -P trios.ped
mendelian2: invalid option -- 'P'
```

does this line need a "P"? https://github.com/samtools/bcftools/blob/master/plugins/mendelian2.c#L791

If you then try and use the long form `--ped`, I get some error about missing "-t" options, perhaps a carry-over from the `+mendelian[1]` package?

```
$ bcftools +mendelian2 myvariants.bcf --ped trios.ped
Expected three sample names with -t
```
https://github.com/samtools/bcftools/blob/develop/plugins/mendelian2.c#L439

```
$ bcftools --version
bcftools 1.17
Using htslib 1.17
Copyright (C) 2023 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

my ped file looks like:
```
FAM1    2212    2209    2188    1
FAM1    2298    2209    2188    1
FAM1    2215    2209    2188    1
FAM1    2217    2209    2188    2
FAM1    2187    2209    2188    2
FAM1    2189    2209    2188    1
FAM1    2209    0       0       1
FAM1    2188    0       0       2
```

**Comment by pd3** [comment]
Hopefully this should be now fixed, please try it out

**Comment by jrharting** [comment]
Thanks!  Just built and tried it out briefly -- looks like its working now.
