### ISSUE TITLE
Symbols not found commit 8e008d84d66e076d7827480af2afa85aaa467d32

### ISSUE THREAD

**Issue by richardbrownsb** [samtools/bcftools#191]
I have the following error message for this commit on make:

vcfconvert.c:1018:22: warning: implicit declaration of function 'bcf_sr_get_header' is invalid in C99 [-Wimplicit-function-declaration]
    bcf_hdr_t *hdr = bcf_sr_get_header(args->files,0);
                     ^
vcfconvert.c:1018:16: warning: incompatible integer to pointer conversion initializing 'bcf_hdr_t *' with an expression of type 'int' [-Wint-conversion]
    bcf_hdr_t *hdr = bcf_sr_get_header(args->files,0);
               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vcfconvert.c:1041:16: warning: incompatible integer to pointer conversion initializing 'bcf_hdr_t *' with an expression of type 'int' [-Wint-conversion]
    bcf_hdr_t *hdr = bcf_sr_get_header(args->files,0);
               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib tsv2vcf.c -o tsv2vcf.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib vcfcnv.c -o vcfcnv.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib HMM.c -o HMM.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib vcfplugin.c -o vcfplugin.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib consensus.c -o consensus.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib ploidy.c -o ploidy.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib version.c -o version.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib ccall.c -o ccall.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib em.c -o em.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib prob1.c -o prob1.o
gcc -c -g -Wall -Wc++-compat -O2  -I. -I../htslib kmin.c -o kmin.o
gcc -g -Wall -Wc++-compat -O2 -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o version.o ccall.o em.o prob1.o kmin.o  ../htslib/libhts.a -lpthread -lz -lm -ldl 
Undefined symbols for architecture x86_64:
  "_bcf_sr_get_header", referenced from:
      _main_vcfconvert in vcfconvert.o
      _gvcf_to_vcf in vcfconvert.o
ld: symbol(s) not found for architecture x86_64

Is the function 'bcf_sr_get_header' defined? I could't find it with grep. On reverting to previous commit, problem resolved

Cheers

**Comment by pd3** [comment]
Probably incompatible versions of htslib and bcftools? Please check here how to get the latest version of both packages: http://samtools.github.io/bcftools/

**Comment by pd3** [comment]
I believe this is resolved, please reopen if not.
