### ISSUE TITLE
bcftools merge unexpected output

### ISSUE THREAD

**Issue by biorococo** [samtools/bcftools#1910]
I've found an unexpected output when merging gVCF files using bcftools v1.17.

I have 3 individuals with following gVCF block/variants:

SAMPLE1
chr20	64249835	.	T	<NON_REF>	0	.	END=64249837	GT:GQ:MIN_DP:PL	0/0:50:54:0,162,1610
chr20	64249838	.	T	<NON_REF>	0	.	END=64251648	GT:GQ:MIN_DP:PL	0/0:50:68:0,216,2150
SAMPLE2
chr20	64249835	.	T	<NON_REF>	0	.	END=64250066	GT:GQ:MIN_DP:PL	0/0:50:38:0,114,1130
chr20	64250067	.	T	<NON_REF>	0	.	END=64250067	GT:GQ:MIN_DP:PL	0/0:21:47:0,21,1160
SAMPLE3
chr20	64249835	.	T	<NON_REF>	0	.	END=64249836	GT:GQ:MIN_DP:PL	0/0:50:28:0,84,830
chr20	64249837	.	T	<NON_REF>	0	.	END=64250066	GT:GQ:MIN_DP:PL	0/0:50:38:0,117,1160

Using the following merge command:
bcftools merge SAMPLE_1_test.vcf.gz  SAMPLE_2_test.vcf.gz  SAMPLE_3_new.vcf.gz --gvcf reference.fasta

I get the following result:
chr20	64249835	.	T	<NON_REF>	0	.	END=64249836	GT:GQ:MIN_DP:PL	0/0:50:54:0,162,1610	0/0:50:38:0,114,1130	0/0:50:28:0,84,830
chr20	64249837	.	T	<NON_REF>	0	.	.	GT:GQ:MIN_DP:PL	./.:.:.:.	0/0:50:38:0,114,1130	0/0:50:38:0,117,1160
chr20	64249838	.	T	<NON_REF>	0	.	END=64250066	GT:GQ:MIN_DP:PL	0/0:50:68:0,216,2150	0/0:50:38:0,114,1130	0/0:50:38:0,117,1160

It looks like bcftools is failing to extract info from last position of gVCF block as position 64249837 is reported in all three samples but having "./.:.:.:." reported for SAMPLE_1 in the merge VCF output.

Any help on this would be appreciated. Thanks!

**Comment by pd3** [comment]
Thank you for the bug report and the test case. Hopefully this should be fixed by https://github.com/samtools/bcftools/commit/2f482de4754ce09eadbdf60b865dc22e9c2e4076, please try it out.
