### ISSUE TITLE
bcftools merge error

### ISSUE THREAD

**Issue by Seanduu** [samtools/bcftools#1912]
After generating a few VCF files using cnvnator, I would like to merge them to a single one:
`for i in `ls *.vcf`;do bgzip $i;done`
`for i in `ls *.vcf.gz`;do bcftools index $i;done`
And then:
`bcftools merge -l vcf.list --force-samples >merged.vcf.gz`

It throws errors like:
[E::bgzf_read_block] Failed to read BGZF header at offset 60448

What is wrong?

**Comment by pd3** [comment]
One of the input files is truncated. You can verify by running `bcftools view -o /dev/null input.vcf`, this operation should give no errors.
