### ISSUE TITLE
Could not parse the "#CHROM.." line, either FORMAT is missing or spaces are present instead of tabs: 	#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT

### ISSUE THREAD

**Issue by sandra-biology** [samtools/bcftools#1913]
Prior to running annotation of a VCF file, I want to view its header. I am using bcftools view -h myVCFfile.vcf
When I run this command, I get the following:

[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*04:03:01 length=15246"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*07:01:01:01 length=16110"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*07:01:01:02 length=16120"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*08:03:02 length=13562"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*09:21 length=16039"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*10:01:01 length=13501"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*11:01:01 length=13921"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*11:01:02 length=13931"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*11:04:01 length=13919"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*12:01:01 length=13404"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*12:17 length=11260"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*13:01:01 length=13935"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*13:02:01 length=13941"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*14:05:01 length=13933"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*14:54:01 length=13936"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:01:01:01 length=11080"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:01:01:02 length=11571"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:01:01:03 length=11056"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:01:01:04 length=11056"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:02:01 length=10313"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:03:01:01 length=11567"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*15:03:01:02 length=11569"
[W::bcf_hrec_check] Invalid contig name: "HLA-DRB1*16:02:01 length=11005"
[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either FORMAT is missing or spaces are present instead of tabs:
	#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT

Failed to read from ppmi.july2018.chr3.subset41513_042323_copy.vcf: could not parse header

I tried editing the header (original file unchanged) by removing commas in config lines. What should I do to get it to parse header?

**Comment by pd3** [comment]
Please check the VCF specification which gives all necessary details about the format https://samtools.github.io/hts-specs/VCFv4.3.pdf
