### ISSUE TITLE
Allele specific annotations

### ISSUE THREAD

**Issue by hbeale** [samtools/bcftools#192]
Hi--

In a case where the annotation source file has a polyallelic annotation (that is defined in the header with Number=A), multiple values are added to the annotated file, which only contains the more common allele.

Is this avoidable?

Here's an example:

ANNOTATION SOURCE FILE
Header 
(the text didn't show up in preview, so I've attached an image)
![header_def](https://cloud.githubusercontent.com/assets/54659/5783729/8ea2f54e-9d7a-11e4-9b50-fb0b09a66081.png)

Record:
chr20   1108122 rs6514113       C       T,G     3.2547e+07      PASS    AC=10984...AC_SAS=297,0;exac_AF=0.089,8.132e-06; 

ANNOTATION COMMAND
bcftools annotate -a $annoSource  -c INFO/exac_AF --output $annoOutput $vcfToAnno

ANNOTATED VCF
chr20   1108122 rs6514113       C       T       431.77  PASS    AC=1...exac_AF=0.089,8.132e-06   GT:AD:DP:GQ:PL  0/1:23,14:37:99:460,0,787

Thanks!

**Comment by pd3** [comment]
Hi, this should fix it. Please let me know in case of problems.
