### ISSUE TITLE
How to interpret output of plot-vcfstats?

### ISSUE THREAD

**Issue by SheaCheng2000** [samtools/bcftools#1921]
Hi!

Recently I am using `plot-vcfstats` to evaluate our QC pipeline. This is the output of QC result vcf (chromosome22 of 1500 WGS data). I am wondering how to interpret if the QC is good or not? Or is there any guideline to do it?
[summary.pdf](https://github.com/samtools/bcftools/files/11486842/summary.pdf)

For example, in the figure of tstv_by_qual, I see the ts/tv of highest and lowest qual is not at the normal range. Does it mean these variants are false positve so that I should filter these variants?
![tstv_by_qual 0](https://github.com/samtools/bcftools/assets/103805882/5d085bce-0d37-4cc7-9cbb-355557df00db)

Thanks a lot!
Shea

**Comment by pd3** [comment]
Overall the callset looks good. The lowest quality bins have lower ts/tv which is expected as they are low quality. They are enriched for false positives and should be removed. Perhaps counterintuitively, also the highest quality bins can have many false positives, even though they may appear as good calls with strong evidence. These are usually mapping artifacts related to segmental duplications and other repeats. If you look at these in more detail, you'll most likely find they have unusually high depth.
Hope this helps!

**Comment by SheaCheng2000** [comment]
Got it! Thanks!
