### ISSUE TITLE
threshold for calling SNPs

### ISSUE THREAD

**Issue by meatpie-jucie** [samtools/bcftools#1923]
Hello.

I am trying SNP calling with bcftools mpileup now.
How can I adjust the threshold for detecting mutations? Also, I would like to know what the default threshold for calling SNPs (%) is.

thank you.

**Comment by Lilu-guo** [comment]
The manual says MaqQ defaults to 0, but in my usage, the specified parameter -q did not work as expected.

**Comment by pd3** [comment]
There is the `bcftools call -m --prior` parameter which makes the calling more sensitive. Please check this comment and the thread https://github.com/samtools/bcftools/issues/1707#issuecomment-1114799459, I hope it will help to clarify.

@Lilu-guo I take it is a typo and you mean mapping quality, MapQ, or MQ for short. The documentation is correct in that input reads are not filtered by mapping quality by default. Note that there are more variables that enter the calculation, and there are heuristics such as BAQ (per-Base Alignment Quality), that can adjust the values on input. 

I hope this helps!
