### ISSUE TITLE
Error: FORMAT/AD is required with the -G option, mpileup must be run with "-a AD" or "-a QS"

### ISSUE THREAD

**Issue by Banthandor** [samtools/bcftools#1924]
Hi,

When I run the following command:

bcftools mpileup --max-depth 99999999 \
 -a AD,QS,DP \
 --gvcf 10 \
 -Ou \
 --min-MQ 20 \
 --min-BQ 20 \
 -f reference.fna \
 --bam-list bams.txt | \
 bcftools call -m \
 --gvcf 10 \
 -a GQ \
 --group-samples groups.txt \
 -Oz - > out.gvcf.gz

The following error occurs: Error: FORMAT/AD is required with the -G option, mpileup must be run with "-a AD" or "-a QS"
This is unexpected, because I did run mpileup with -a AD and QS. I tried running the same code with only -a AD, and only -a QS, but this doesn't change anything.

**Comment by pd3** [comment]
In your command you put the `-a` option twice, once as `-a AD,QS,DP` and then as `-a GQ`. The option parsing is not additive in most cases and the last replaces the first without a warning.
