### ISSUE TITLE
how to exclude weird primary reads when calling variants

### ISSUE THREAD

**Issue by leon945945** [samtools/bcftools#1932]
Hi, I saw some fragmented primary reads carrying a bunch of variants, the alignment length is only 4kb with 22kb read length (reads in red box), and those reads have several supplementary reads, which indicates fragmentary alignment of those reads.

I'm wondering why the alignment is so fragmentary of those reads?

In my opinion, those weird primary reads would interfere variants calling, can `bcftools mpileup` exclude those weird primary reads or other methods to implement it?

Thanks very much.
![图片](https://github.com/samtools/bcftools/assets/61004157/1b8e282f-1628-4d48-86c3-792b15e1ca02)

**Comment by pd3** [comment]
The first question I cannot answer, don't know what mapper have you used, and better to ask it in the forum dedicated to that mapper.

Regarding how to filter these, `bcftools mpileup` has only the following options
``` 
  -q, --min-MQ INT        Skip alignments with mapQ smaller than INT [0]
  --ignore-RG         Ignore RG tags (one BAM = one sample)
  --ls, --skip-all-set STR|INT  Skip reads with all of the bits set []
  --ns, --skip-any-set STR|INT  Skip reads with any of the bits set [UNMAP,SECONDARY,QCFAIL,DUP]
  --lu, --skip-all-unset STR|INT  Skip reads with all of the bits unset []
  --nu, --skip-any-unset STR|INT  Skip reads with any of the bits unset []
```
and none of them is helpful in your case unfortunately.
