### ISSUE TITLE
The difference between samtools mpileup and bcftools mpileup

### ISSUE THREAD

**Issue by fjptwenger** [samtools/bcftools#1934]
The same in_bam file, the depth  in the output files of the two tools is very large, is there any difference in depth statistics between the two tools?
```
bcftools mpileup -Ou  KIE.dedup.bam -f hg19.fa  -R KIE.bed  >KIE.mplieup
samtools mpileup -f hg19.fa -l .KIE.bed  KIE.dedup.bam  >KIE2.mplieup
```
samtools ： Version: 1.14 
bcftools: Version: 1.9

bcftools output: 

![image](https://github.com/samtools/bcftools/assets/25705121/ff818d35-7279-45b4-b440-5bdc0e0959e6)

samtools output:
![image](https://github.com/samtools/bcftools/assets/25705121/3adc6e5e-3d02-4d7d-bb0b-3ff860e0a696)

**Comment by jkbonfield** [comment]
Take a look at the options for both tools and you'll see lots of differences in various filtering rules.  Eg `--min-BQ 13` for samtools, vs `--min-BQ 1` for bcftools.  There will likely be many more such things.

Note the two commands really are serving different purposes so aren't directly comparable.  Samtools mpileup is basically a presentation of the data reference base by reference base: transposing rows and columns basically from your classic alignment view.  Bcftools mpileup is a totally different beast in that it's the first stage of a two-stage variant caller.  As such it has all sorts of different filtering requirements, and many additional tags such as `I16`, whose sole purpose is to be consumed by `bcftools call`.

**Comment by jkbonfield** [comment]
The max depth limit will clearly change things!  However it's unlikely to be the only thing.  As I say, you'd need to go through all the options carefully and compare.
