### ISSUE TITLE
DP filter not working?

### ISSUE THREAD

**Issue by dianacornejo** [samtools/bcftools#1935]
I'm unsure if this is the case. I'll try to explain as best I can here. So I'm writing a pipeline to do QC of exome data which consist of steps for left normalizing, splitting multiallelic variants and then filtering based on allele depth (DP), genotype qualityt (GQ) and allelic balance for heterozygotes. Then I gather some statistics using `bcftools stats` where I'm seeing that there are some genotypes that remain with low DP even when I have set them to missing. 

This is the code 

```
bcftools norm --threads 8 -m-any "~{vcfFile}" |\
bcftools norm --check-ref w -f "~{refhg38}" -Ou|\
bcftools annotate -x ID -I +'%CHROM:%POS:%REF:%ALT' -Ob > "~{file_prefix}.norm.vcf.gz"

bcftools stats -v -s- "~{file_prefix}.norm.vcf.gz" > "~{file_prefix}.norm.stats"

bcftools filter -Oz -o "~{file_prefix}.norm.filtered.vcf.gz" -S . \
          -i '(TYPE="snp" & FMT/DP >= 8 & ((FMT/GT="RR" & FMT/GQ >= 20) |  
          (FMT/GT="RA" & FMT/GQ >= 20 & ((FORMAT/AD[*:1])/(FORMAT/DP))>=0.15) | 
          (FMT/GT="AA" & FMT/GQ >= 20))) | 
          (TYPE="indel" & FMT/DP >= 10 & FMT/GQ >= 20 & ((FMT/GT="RR") | 
          (FMT/GT="RA" & ((FORMAT/AD[*:1])/(FORMAT/DP))>=0.2) | 
          (FMT/GT="AA")))' "~{vcfFile}"

bcftools stats -v -s- "~{file_prefix}.norm.filtered.vcf.gz" > "~{file_prefix}.norm.filtered.stats"

bcftools +fill-tags "~{file_prefix}.norm.filtered.vcf.gz" -Oz -o \
          "~{file_prefix}.norm.filtered.tagged.vcf.gz" -- -t F_MISSING,AC,AF,AN

bcftools filter -i 'F_MISSING<=0.10 & AC!=0' -Oz -o \
          "~{file_prefix}.norm.filtered.tagged.AC.vcf.gz"  \
          "~{file_prefix}.norm.filtered.tagged.vcf.gz" 

   bcftools stats -v -s- "~{file_prefix}.norm.filtered.tagged.AC.vcf.gz"  > "~{file_prefix}.norm.filtered.tagged.AC.stats" 
```
And this is what I'm seeing in the stats in the ~{file_prefix}.norm.stats , ~{file_prefix}.norm.filtered.stats and the  ~{file_prefix}.norm.filtered.tagged.AC.stats. The norm.stats should be the original data in which just the normalization was done, the second one norm.filtered.stats, I should be seeing some genotypes set to missing and in the last one I've applied the F_missing and the AC filter. These are the first 8 lines of the .stats output. Is this the correct behavior and I'm just not understanding something or there's something wrong. Thanks in advance and please let me know if something is unclear. 

**"~{file_prefix}.norm.stats"**

```
# DP	[2]id	[3]bin	[4]number of genotypes	[5]fraction of genotypes (%)	[6]number of sites	[7]fraction of sites (%)
DP	0	0	37949631	0.297263	0	0.000000
DP	0	1	6344543	0.049697	0	0.000000
DP	0	2	32658629	0.255818	0	0.000000
DP	0	3	13689744	0.107233	0	0.000000
DP	0	4	64016998	0.501451	0	0.000000
DP	0	5	23727551	0.185860	0	0.000000
DP	0	6	63034742	0.493757	0	0.000000
DP	0	7	126845394	0.993591	0	0.000000
DP	0	8	39914820	0.312656	0	0.000000
```

**"~{file_prefix}.norm.filtered.stats"**

```
# DP	[2]id	[3]bin	[4]number of genotypes	[5]fraction of genotypes (%)	[6]number of sites	[7]fraction of sites (%)
DP	0	0	37949631	0.297263	0	0.000000
DP	0	1	6344543	0.049697	0	0.000000
DP	0	2	32658629	0.255818	0	0.000000
DP	0	3	13689744	0.107233	0	0.000000
DP	0	4	64016998	0.501451	0	0.000000
DP	0	5	23727551	0.185860	0	0.000000
DP	0	6	63034742	0.493757	0	0.000000
DP	0	7	126845394	0.993591	0	0.000000
DP	0	8	39914820	0.312656	0	0.000000
```
**"~{file_prefix}.norm.filtered.tagged.AC.stats"**

```
# DP	[2]id	[3]bin	[4]number of genotypes	[5]fraction of genotypes (%)	[6]number of sites	[7]fraction of sites (%)
DP	0	0	38386	0.000337	0	0.000000
DP	0	1	53824	0.000473	0	0.000000
DP	0	2	644895	0.005670	0	0.000000
DP	0	3	446831	0.003928	0	0.000000
DP	0	4	4045733	0.035568	0	0.000000
DP	0	5	1898259	0.016688	0	0.000000
DP	0	6	7280298	0.064004	0	0.000000
DP	0	7	22573484	0.198453	0	0.000000
DP	0	8	7783234	0.068426	0	0.000000
```

**Comment by pd3** [comment]
The expression is quite complex. Can I suggest that you first do a little bit of debugging by splitting the expression into smaller chunks and verify manually that what comes out makes sense? For example, you could do
```
bcftools view -i 'F_PASS( expr_to_include_things_I_want_to_see )>0.9' | bcftools view -i ' expr_to_include_what_should_have_been_filtered'
```
and then report if you find anything that does not match the expectation.

However, as I am writing this it occurred to me that even if the expression is valid, the first thing to check is the assumption that setting genotypes to missing would really exclude their depth from `bcftools stats`. That's actually not the case, the program increments the depth counters regardless of their genotype
https://github.com/samtools/bcftools/blob/4d0d262b020386b940ec7f60f636097fa1d4cc3a/vcfstats.c#L1102-L1116

Unfortunately currently we don't have the functionality to reset also the accompanying information with `bcftools filter -s`.

**Comment by pd3** [comment]
I believe this can be considered solved, please shout if not
