### ISSUE TITLE
bcftools view:  Error: cannot use arithmetic operators to compare strings and numbers

### ISSUE THREAD

**Issue by Shruti-BioCode** [samtools/bcftools#1939]
Hi,
I am trying to filter the vcf for DP, QUAL and GQ and sort the vcf file and got the error
Error: cannot use arithmetic operators to compare strings and numbers

The command : 
```
 bcftools filter -i 'FORMAT/DP>=5' -R $hConf_reg $vcffile >temp
```
Can someone help to the correct command?
Thanks!

**Comment by pd3** [comment]
The command looks okay, look for the answer in the header: FORMAT/DP should be defined as Type=Integer in the VCF. Is it really?

**Comment by Shruti-BioCode** [comment]
Thanks, indeed that was the issue, all are Type=String!
