### ISSUE TITLE
bcftools sort -T TMPDIR must be unique

### ISSUE THREAD

**Issue by microfuge** [samtools/bcftools#1944]
Hi,

First of all, apologies for a question which must be obvious to experienced users. 

I am using bcftools sort  `v1.11` and when not specifying the `-T` a unique dir is created in `/tmp` by bcftools, e.g `Writing to /tmp/bcftools-sort.mMwAqa`. Whereas, when specifying the tmpdir with `-T`, it is the user who has to specify the unique directory name.  My naive assumption was that using `-T /scratch`, bcftools will create a unique directory in `/scratch` just like it does for tmp. 

On our hpc, I tried `bcftools-sort -T /scratch` and temporary bcf files  were created with, in `scratch` . 

* If the same user runs two different bcftools sort `-T /scratch` commands the files overwrite one another?
* If two different users run bcftools sort, then permission issues prevent overwriting the files from two runs. 

Following was the solution provided by our system administrator 

```
#create a tmpdir in /scratch with a unique name 
mytemp=$(mktemp -d -p /scratch bcftools.XXXXXXXXXXXX)
#specify the tmpdir to bcftools
bcftools sort -T ${mytemp} ...
```
I think that the easier default behavior would be the user needs to just specify a directory and bcftools take care of the creation of unique directory creation in that tmpdir. 
Thanks!

**Comment by pd3** [comment]
If you want to change the temp directory, run the command as
```
bcftools sort -T /scratch/bcftools.XXXXXX
```
The 6 X's will be replaced with a unique string. I will extend the man page to make this clear.
