### ISSUE TITLE
Where is the bcftools plugin directory in conda?

### ISSUE THREAD

**Issue by MarieCoutelier** [samtools/bcftools#1946]
Hi, 

I apologize if the question was asked before, I looked it up here and in Biostars and could not find my answer. 

I would like to use the bcftools split-vep plugin. 
I first got the following error : 
```
(basicNGS) bcftools +split-vep

No functional bcftools plugins were found. The environment variable BCFTOOLS_PLUGINS is not set.

Could not load "split-vep".
```

So, I understand I need to set the variable BCFTOOLS_PLUGINS. But I can not find the bcftools plugin folder after installing bcftools with conda. 

Alternatively, I tried compiling bcftools again from git as described here: 
https://samtools.github.io/bcftools/howtos/install.html

But I get the following error when running make: 
```
(nonCodVar) bcftools$ make
echo '#define BCFTOOLS_VERSION "1.17-56-g402de74a"' > version.h
gcc -g -Wall -O2 -I. -I../htslib   -c -o main.o main.c
gcc -g -Wall -O2 -I. -I../htslib   -c -o version.o version.c
cd ../htslib && make hts-object-files
make[1]: Entering directory `/network/lustre/iss02/stevanin-durr/spatax/OUTILS/Resources/htslib'
gcc -g -Wall -O2 -fvisibility=hidden  -I.  -c -o hts.o hts.c
hts.c:46:18: fatal error: lzma.h: No such file or directory
 #include <lzma.h>
                  ^
compilation terminated.
make[1]: *** [hts.o] Error 1
make[1]: Leaving directory `/network/lustre/iss02/stevanin-durr/spatax/OUTILS/Resources/htslib'
make: *** [../htslib/hts-object-files] Error 2
```

I still tried to provide the plugin folder path from this clone to the BCFTOOLS_PLUGINS variable but I get the following error: 
```
(basicNGS) bcftools +split-vep

No functional bcftools plugins were found in
	BCFTOOLS_PLUGINS="/network/lustre/iss02/stevanin-durr/spatax/OUTILS/Resources/bcftools/plugins".

- Is the plugin path correct?

- Run "bcftools plugin -lv" for more detailed error output.

Could not load "split-vep".

```

The content of the folder is as follows: 
```
(basicNGS) ls /network/lustre/iss02/stevanin-durr/spatax/OUTILS/Resources/bcftools/plugins
ad-bias.c         af-dist.mk        color-chrs.c   dosage.c            fill-tags.c   frameshifts.c  GTsubset.mk     indel-stats.c  missing2ref.c      scatter.c     split-vep.c   trio-switch-rate.c
ad-bias.mk        allele-length.c   color-chrs.mk  fill-AN-AC.c        fixploidy.c   GTisec.c       guess-ploidy.c  isecGT.c       parental-origin.c  setGT.c       tag2tag.c     variant-distance.c
add-variantkey.c  check-ploidy.c    contrast.c     fill-from-fasta.c   fixploidy.mk  GTisec.mk      gvcfz.c         isecGT.mk      prune.c            smpl-stats.c  trio-dnm2.c   variantkey-hex.c
af-dist.c         check-sparsity.c  counts.c       fill-from-fasta.mk  fixref.c      GTsubset.c     impute-info.c   mendelian2.c   remove-overlaps.c  split.c       trio-stats.c

```

So there seems to be a split-vep file, but .c and not .so as I undertsand it should be. 

Could someone either help me to 
- find the appropriate plugin folder from my conda environnement? 
- fix the lzma.h missing issue (I'm not admin of my computer, I can't run any sudo install
- or help me find any way to use the split-vep plugin? :-)

Thanks a lot!

Marie

**Comment by jmarshall** [comment]
Ideally conda's relocation rewriting would handle the bcftools executable's burnt-in plugin path, but it does not. Probably the right environment variable setting for use with your conda `bcftools` will be

```sh
# (Do this when the conda environment contains bcftools is activated)
export BCFTOOLS_PLUGINS=$CONDA_PREFIX/libexec/bcftools
```
