### ISSUE TITLE
convert --hapsample loosing phase

### ISSUE THREAD

**Issue by droeatumn** [samtools/bcftools#1947]
When I use 1.17 or 1.17-56-g402de74a to run `convert --hapsample` on a phased bcf, the hap output looks like
   19:171762_T_C 19:171762_T_C 171762 T C 0* 0* 0* 0* 1* 0* 0* 0*...

I tried 1.3.1, following a suggestion in issue #730 (https://github.com/samtools/bcftools/issues/730), and it fixed the issue
    19 19:171762_T_C 171762 T C 0 0 0 0 1 0 0 0 0 0

I don't have a file I can share, but hopefully it is easy to recreate.

**Comment by pd3** [comment]
It is not clear what the input data looks like, unfortunately the issue cannot be addressed as it is stated now. Please provide a small test case with the full command line to understand what exactly is the problem.

**Comment by droeatumn** [comment]
I think this is an issue with SHAPEIT5. Submitted an issue there. https://github.com/odelaneau/shapeit5/issues/41
