### ISSUE TITLE
bcftools merge with gVCF blocks

### ISSUE THREAD

**Issue by jordilc** [samtools/bcftools#195]
Hi, 
I want to use bcftools merge with files with gVCF blocks, but if one of the files has an SNP where the other file has a gVCF block, bcftools doesn't merge them properly. An example:

File 1:
18	7447502	.	C	T	228	PASS	DP=12;VDB=0.985771 ...
18	7447775	.	T	.	.	LowQual	END=7447781	GT	0/0
18	7447783	.	T	.	.	LowQual	END=7447803	GT	0/0

File 2:
18	7447472	.	C	A	228	PASS	DP=14;VDB=0.346151 ...
18	7447777	.	T	G	190	PASS	DP=9;VDB=0.904845 ...

Merged file:
18	7447502	.	C	T	228	PASS	VDB=0.985771 ...
18	7447775	.	T	.	.	LowQual	END=7447781;AN=2	GT	0/0	./.
18	7447777	.	T	G	190	PASS	VDB=0.904845 ...
18	7447783	.	T	.	.	LowQual	END=7447803;AN=2	GT	0/0	./.

I think the expected result should be split the gVCF block into two blocks, with the SNP between them:
18	7447502	.	C	T	228	PASS	VDB=0.985771 ...
18	7447775	.	T	.	.	LowQual	END=7447776;AN=2	GT	0/0	./.
18	7447777	.	T	G	190	PASS	VDB=0.904845 ...
18	7447778	.	T	.	.	LowQual	END=7447781;AN=2	GT	0/0	./.
18	7447783	.	T	.	.	LowQual	END=7447803;AN=2	GT	0/0	./.

**Comment by pd3** [comment]
Unfortunately, merging of gVCFs is not supported yet, partly because I am not sure about the logic of the operation. For example, when merging normal records, filters behave differently from what you proposed: a site can have FILTER=PASS only if it is not filtered in any of the files. I don't have much experience with gVCF and don't know what behaviour is expected / most useful.

**Comment by dwaggott** [comment]
Were there any ideas on this subsequent to #244 ? Doing a gvcf merge is a great poor man's synthetic joint caller.

I've got several hundred whole genome gvcf's that need merging. My first rather clunky approach is:

1.  determine the union of all variable sites across the cohort
2.  extract those sites from each gvcf using convert i.e.  `bcftools convert --gvcf2vcf -R all_variable_sites.bed`
3. merge the resulting vcf's

**Comment by pd3** [comment]
There is an initial version of gVCF merging in https://github.com/pd3/bcftools. However, it is not ready for production use yet.

**Comment by mcshane** [comment]
The gVCF merging code is now on the develop branch
