### ISSUE TITLE
Is QUAM affected by the minimum mapping quality or base quality?

### ISSUE THREAD

**Issue by nmc-ei** [samtools/bcftools#1951]
Hello,

Is QUAM affected by the minimum mapping quality or base quality?
In other words, is the value of QUAL in the vcf file sufficient to evaluate the quality of the variant without using the -q or -Q options?

**Comment by Lilu-guo** [comment]
Is there a clear answer to this question now？
In addition, I found that if the specified value -q below 30, it does not work.
For example, when using -q 20, it still uses 30 as the threshold; and when using -q 40 (greater than 30), it uses 40 normally.
