### ISSUE TITLE
bcftools norm -m + still disregards phasing for some cases

### ISSUE THREAD

**Issue by sjellerstrand** [samtools/bcftools#1953]
The merging would disregard phasing, adding the support for it now. Please try it out. Thank you for the issue.

_Originally posted by @pd3 in https://github.com/samtools/bcftools/issues/1893#issuecomment-1486957349_

Hej!
I would like to re-open this issue. It seems that merging still diregards phasing for some cases. I am using the latest source code and have checked out  the commit 796594f before running the following code. I made a test case for each possbile combination in a tri-allelic situation.

Input:
```
##fileformat=VCFv4.2
##contig=<ID=CADDXX010001401.1>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Phased genotypes">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  s1      s2      s3      s4      s5      s6      s7      s8      s9      s10     s11     s12     s13     s14     s15     s16
CADDXX010001401.1       41886   .       G       A       .       .       .       GT      0|0     0|0     0|0     0|0     0|1     0|1     0|1     0|1     1|0     1|0     1|0     1|0     1|1     1|1     1|1  1|1
CADDXX010001401.1       41886   .       G       T       .       .       .       GT      0|0     0|1     1|0     1|1     0|0     0|1     1|0     1|1     0|0     0|1     1|0     1|1     0|0     0|1     1|0  1|1
```
Command:
```
bcftools norm input.vcf.gz -m +any
```
Output:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=CADDXX010001401.1>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Phased genotypes">
##bcftools_normVersion=1.17-60-gb7b2a32+htslib-1.17-dirty
##bcftools_normCommand=norm -m +any input.vcf; Date=Mon Jul  3 17:33:28 2023
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  s1      s2      s3      s4      s5      s6      s7      s8      s9      s10     s11     s12     s13     s14     s15     s16
CADDXX010001401.1       41886   .       G       A,T     .       .       .       GT      0|0     0|2     2|0     2|2     0|1     2|1     2|1     2|1     1|0     1|2     1/2     1/2     1|1     1|1     1|1  1|1
```
I was myself having issues with case s11. I would have expected both s11 and s12 result  in 1|2 instead of 1/2.
However, looking at the other examples, I would have further expected s14 to result in 1|2 instead of 1|1, and s15 to result in 2|1 instead of 1|1.

Thanks for your time, and looking forward to hear back from you!

Simon

**Comment by pd3** [comment]
Mmm, here it actually makes sense to unphase the genotypes, as clearly the input demands something impossible: it claims that the same DNA molecule has A and T at the same position. The phasing cannot be reconciled and is wrong in the input data.

I am not sure if the program is that smart or it's a lucky outcome, but it cannot be blamed for the decision it made.
