### ISSUE TITLE
Filtering vcf based on the numbers of samples that should have "alt" genotypes.

### ISSUE THREAD

**Issue by Axze-rgb** [samtools/bcftools#1958]
Hello, this is crossposted from biostar, I found a workaround, but I am just curious to understand why this command doesn't work. 

I link the thread here: https://www.biostars.org/p/9568820/

So, why this command?

`bcftools view -i 'GT[0-3]="alt" & GT[4-10]="ref"' merged_snps_only.bcf.gz`

Doesn't return me a vcf with the first 3 samples having an alt GT, and the last seven ones having ref GT? It returns an empty vcf. 

Feel free to lock this thread if you think it's not the right place to ask this question (after all, I found a workaround + the one suggested by Pierre). 

Thanks

**Comment by pd3** [comment]
The symbol `&` in the filtering expression requests that the condition must be satisfied within one sample. Use `&&` instead.

Note there is also the plugin `bcftools +contrast` which might is also suitable for tasks like this
