### ISSUE TITLE
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by jesus2397** [samtools/bcftools#1965]
Hi! I `m trying to use medaka in conda for polishing some contings but the next error appears:

**bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory**

The library bcftools is already installed.

Can anyone help me?

**Comment by pd3** [comment]
I am closing the issue as it looks like a problem with the distribution, not bcftools. Please shout if not
