### ISSUE TITLE
bcftools view to filter based on FREQ field.

### ISSUE THREAD

**Issue by chunxuan-hs** [samtools/bcftools#1967]
I would like to use bcftools to filter records based on FREQ in the INFO column, but the ouput is a bit complicated and I am not sure how to do it properly. 

An example is shown bellow (annotated with snpsift)
`FREQ=GENOME_DK:0.05556,.,0.9444,.|GnomAD:0.3163,.,0.6837,.|KOREAN:0.1405,0,0.8595,0|SGDP_PRJ:0.0181,0.002262,0.9751,0.004525|TOMMO:0.1327,.,0.8673,.|dbGaP_PopFreq:0.0779,.,0.9221,.`

I would like to filter based on GnomAD, like freq of alt < 0.2 . The tricky thing is that there are four value, the first is always the freq of ref, 0.3163;  the alt represented in the record has a freq of 0.6837; the two  "." means other variants are not found for this sample.  

Note the position of "." and freq of alt in could be different, i.e, `0.1327,.,.,0.8673` is also possible, depeding on the order of the alt in the dbspn database.

How should I write the expression?  Many thanks!

**Comment by pd3** [comment]
If `snpsift` used the same format as VEP or `bcftools csq`, you could use the `bcftools +split-vep` plugin. However, as that's not the case, perhaps most convenient is to take advantage of the custom perl filtering functionality. When compiles wiht perl support (see the `./configure --enable-perl-filters && make` step in INSTALL), one can use expressions like this:
```
-i 'perl:misc/demo-flt.pl; perl.severity(INFO/CSQ) > 10'
``` 

Please see an example here https://github.com/samtools/bcftools/blob/develop/misc/demo-flt.pl
