### ISSUE TITLE
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by swajid** [samtools/bcftools#1976]
Running bcftools ~1.9~ (this is the PLINK version)
Getting the following error on new server after a new install.

`bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

Any suggestions?

libcrypto.so.1.1 is installed under /lib

`export LD_LIBRARY_PATH=<lib path>` has been added to the script, same issues but less errors messages this time.

**Comment by jkbonfield** [comment]
We normally see these through use of mixed conda environments caused incompatible (and old) versions of tools being installed.  I believe newer conda packages have this issue fixed.

Please set your channel config to use bioconda before conda-forge (see https://bioconda.github.io/), and consider using a new environment.  Failing that, you may be able to explicitly specify the version being installed to force an up to date package.

**Comment by pd3** [comment]
I am closing the issue as it looks like a problem with the distribution, not bcftools. Please shout if not
