### ISSUE TITLE
[E::vcf_parse_format] Invalid character 'i' in 'CN' FORMAT field at chrM:1

### ISSUE THREAD

**Issue by jingydz** [samtools/bcftools#1979]
$ bcftools merge -l subset_vcfsac -Oz -o merge.subset_vcfsac.vcf.gz;  tabix -p vcf merge.subset_vcfsac.vcf.gz
[W::vcf_parse_format] Extreme FORMAT/CN value encountered and set to missing at chrM:1
[E::vcf_parse_format] Invalid character 'i' in 'CN' FORMAT field at chrM:1

**Comment by pd3** [comment]
You are not showing any data, so I have to guess. Most likely the tag `CN` is of a numeric type, as declared in the VCF header, but the data line at the position chrM:1 contains a non-numeric value.

**Comment by BioLaoXu** [comment]
I'm having the same problem, I suspect it's the CN value is inf causing this error, my vcf file is from cnvnator, maybe there is a problem with my cnvnator calculation.

```
1       16101   CNVnator_dup_1  N       <DUP>   .       PASS    END=18800;SVTYPE=DUP;SVLEN=2700;IMPRECISE;natorRD=inf;natorP1=0.000629695;natorP2=5.97142;natorP3=83.4386;natorP4=1.59282e+06;natorQ0=0.651741    GT:CN     ./1:Inf
1       25001   CNVnator_dup_2  N       <DUP>   .       PASS    END=27400;SVTYPE=DUP;SVLEN=2400;IMPRECISE;natorRD=inf;natorP1=0.0121297;natorP2=55.0477;natorP3=77393.1;natorP4=1.01183e+07;natorQ0=0.991525      GT:CN     ./1:Inf
```
