### ISSUE TITLE
Filtering indels

### ISSUE THREAD

**Issue by lt11** [samtools/bcftools#1982]
Dear authors,

While I was filtering a vcf to grab only its indels I noticed that the output also reports "indels" that are longer than 50 bp. Is this an expected behaviour? Shouldn't variants longer than 50 bp be classified as "other"?

Thanks for your help.

Best regards,

Lorenzo

**Comment by pd3** [comment]
No, it shouldn't, I don't see why, insertions and deletions can be of any length.
The program classifies records as follows
```
ACGT A    .. deletion
A ACGT    .. insertion
A <INS>   .. other
A <DEL>   .. other
```
