### ISSUE TITLE
bcftools isec to extract unique snps 

### ISSUE THREAD

**Issue by Nikhilgunala** [samtools/bcftools#1983]
I want to extract unique SNPs in a single vcf file (IA.vcf.gz)  compared with other 19 vcf files by following the command 

bcftools isec -c snps  -C IA.vcf.gz  502.vcf.gz 505.vcf.gz 90.vcf.gz 91.vcf.gz 93.vcf.gz 93.vcf.gz 98.vcf.gz DM.vcf.gz Dw.vcf.gz IA.vcf.gz  LE.vcf.gz MT.vcf.gz P10.vcf.gz PI34vcf.gz PI.vcf.gz PI3.vcf.gz PL.vcf.gz PLYGma-PI.vcf.gz R2.vcf.gz R.vcf.gz -p new100IACunique 

I'm I doing it right  

please help me 

thanks

**Comment by Nikhilgunala** [comment]
@pd3 can you please clarify

**Comment by pd3** [comment]
Yes, this should give you sites present in the first file but not in the rest. One thing to note, the program operates on site level,that is does not care about genotypes. For example, if there was a site with GT=0/0 in all files but the first has GT=0/1, this is biologically a novel SNV but would not be printed. Also note the `-c snps` option makes the program disregard differences between, say, `REF=C ALT=T` vs `REF=C ALT=A`.
