### ISSUE TITLE
urgent: error during consensus generation by applying variants

### ISSUE THREAD

**Issue by Cricetinae-hamster** [samtools/bcftools#1986]
Hello!
I'm trying to incorporate variants, but all the heterozygous sites are also being reported as follows: "Warning: ignoring overlapping variant starting at: .......", along with all overlapping variants. The command line I've used is bcftools consensus --mark-ins lc --mark-del CHAR -H A -s my_sample -f - VCF.vcf.gz >> out3.fa
Could you please look into it as soon as feasible?

**Comment by pd3** [comment]
It is just a warning, not an error. The program says there are some variants that overlap, it does not know which one to apply to the consensus, and resolves the problem by applying the first and ignoring the second. One should first do some variant filtering, typically there are many false positives.
