### ISSUE TITLE
bcftools annotate fail to mark sites by bed file

### ISSUE THREAD

**Issue by ruslan-abasov** [samtools/bcftools#1989]
Hi,

I am using bcftools 1.18. I want to mark sites, that overlaps regions in bed file 

vcf:
[test.vcf.gz](https://github.com/samtools/bcftools/files/12497677/test.vcf.gz)

bed:
[test.bed.gz](https://github.com/samtools/bcftools/files/12497687/test.bed.gz)

bcftools annotate  -a test.bed.gz --mark-sites +TAG -c CHROM,FROM,TO test.vcf.gz:

chr1	10611	.	C	G	.	.	.	GT	1/1
chr1	10623	.	T	C	.	.	.	GT	1/1
chr1	10647	.	A	G	.	.	.	GT	0/1
chr1	10671	.	G	C	.	.	.	GT	0/1
chr1	10676	.	A	G	.	.	.	GT	0/1
chr1	10705	.	A	G	.	.	.	GT	0/1
chr1	10729	.	G	C	.	.	.	GT	0/1
chr1	10734	.	A	G	.	.	.	GT	0/1
chr1	10751	.	C	G	.	.	.	GT	0/1
chr1	10758	.	G	C	.	.	.	GT	0/1

bcftools annotate  -a test.bed.gz --mark-sites -TAG -c CHROM,FROM,TO test.vcf.gz:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test
chr1	10611	.	C	G	.	.	TAG	GT	1/1
chr1	10623	.	T	C	.	.	TAG	GT	1/1
chr1	10647	.	A	G	.	.	TAG	GT	0/1
chr1	10671	.	G	C	.	.	TAG	GT	0/1
chr1	10676	.	A	G	.	.	TAG	GT	0/1
chr1	10705	.	A	G	.	.	TAG	GT	0/1
chr1	10729	.	G	C	.	.	TAG	GT	0/1
chr1	10734	.	A	G	.	.	TAG	GT	0/1
chr1	10751	.	C	G	.	.	TAG	GT	0/1
chr1	10758	.	G	C	.	.	TAG	GT	0/1

same command, but with bcftools 1.17:

bcftools annotate -a test.bed.gz --mark-sites +TAG -c CHROM,FROM,TO test.vcf.gz

chr1	10611	.	C	G	.	.	.	GT	1/1
chr1	10623	.	T	C	.	.	TAG	GT	1/1
chr1	10647	.	A	G	.	.	TAG	GT	0/1
chr1	10671	.	G	C	.	.	TAG	GT	0/1
chr1	10676	.	A	G	.	.	.	GT	0/1
chr1	10705	.	A	G	.	.	.	GT	0/1
chr1	10729	.	G	C	.	.	.	GT	0/1
chr1	10734	.	A	G	.	.	.	GT	0/1
chr1	10751	.	C	G	.	.	.	GT	0/1
chr1	10758	.	G	C	.	.	.	GT	0/1

bcftools annotate -a test.bed.gz --mark-sites -TAG -c CHROM,FROM,TO test.vcf.gz

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test
chr1	10611	.	C	G	.	.	TAG	GT	1/1
chr1	10623	.	T	C	.	.	.	GT	1/1
chr1	10647	.	A	G	.	.	.	GT	0/1
chr1	10671	.	G	C	.	.	.	GT	0/1
chr1	10676	.	A	G	.	.	TAG	GT	0/1
chr1	10705	.	A	G	.	.	TAG	GT	0/1
chr1	10729	.	G	C	.	.	TAG	GT	0/1
chr1	10734	.	A	G	.	.	TAG	GT	0/1
chr1	10751	.	C	G	.	.	TAG	GT	0/1
chr1	10758	.	G	C	.	.	TAG	GT	0/1

**Comment by pd3** [comment]
Thank you for the issue and the test case, this should be fixed now in https://github.com/samtools/bcftools/commit/40aa67d13365e2177d507d96dd97b6745503bf7b

**Comment by tuncayseker** [comment]
Hello.

This is introduced in the 1.18 version and <=1.17 versions are ok.

Thank you
