### ISSUE TITLE
 bcftools mpileup and call with large bam files 

### ISSUE THREAD

**Issue by dosshra** [samtools/bcftools#1991]
Hello
I am about to call variants in about 200 bam files each about  the size of 100GB. I will need 20 TB just to store them in one place.  Since currently I do not have this volume, I was thinking to generate gvcf files for each sample and then merge them. Alternatively, I can split the bam files to the 14 chromosomes and then call variants for each chromosome separately.  Another option is to work in batches of samples and merge their VCF flies later.  Which is the preferred method  in terms of time, memory usage and accuracy?
Thank you

**Comment by pd3** [comment]
The common practice is to call variants per genomic region and concatenate the results. As for splitting by sample, there it depends what variation are you after: rare or population-level variation.

Generally, calling samples in a pooled way makes the calling more robust (fewer false positives) but less sensitive. On the other hand, calling single samples individually is most sensitive but brings problems with indel ambiguity when merging the results into a single multi-sample VCF. A compromise approach to get the best out of both worlds is to call with `bcftools call --group-samples` option, which evaluates indels in a pooled way but allows to use HWE assumption on sample groups or even call single sample.

**Comment by dosshra** [comment]
Thank you for the comprehensive explanation. I think in my case of a selfer spices, wheat HWE does not hold.  Does the problem with calling single samples applied only to indels but not to SNP? 
Thank you

**Comment by pd3** [comment]
Merging SNPs is easy
