### ISSUE TITLE
bcftools view problem

### ISSUE THREAD

**Issue by MattHegarty431** [samtools/bcftools#1995]
Hi,

I'm trying to extract a region from a VCF file using bcftools view, however no matter what I do it only extracts the whole chromosome, not the region. The chromosome name is farily complex (i.e. not just "chr1"). The command line I'm using is:

bcftools view -r 'gi|417531910|ref|NC_019471.1|,length=62722625':51709128-51711551 input.vcf.gz > output.vcf

Genome used for the VCF is the Oar_3.1 sheep reference. 

Any help appreciated!

Matt

**Comment by jmarshall** [comment]
(Crossposted [at biostars](https://www.biostars.org/p/9574622/) and answered there.)

**Comment by pd3** [comment]
I am closing the issue as it is answered elsewhere. If not resolved, please shoutl
