### ISSUE TITLE
Question about isec output

### ISSUE THREAD

**Issue by bioinfoMMS** [samtools/bcftools#1997]
Hello,

I have a question about the output of bcftools isec when comparing more than two vcf files. My command is:

bcftools isec -p output -n+2 A.vcf.gz B.vcf.gz C.vcf.gz D.vcf.gz

I get the following output:

0000.vcf  
0001.vcf  
0002.vcf  
0003.vcf

I want to confirm that these output files contain each sample's SNPs that are not in one or more of the other samples? For instance, the SNPs in 0000.vcf are the SNPs from A.vcf.gz after the SNPs shared in two or more of the vcf files are removed. If this is the case, is there a way to just get the list of SNPs that are shared in two or more of the files? 

Thank you in advance,
Maddy

**Comment by pd3** [comment]
What you write sounds like the opposite of what the command is actually doing: giving `-n +2`  will discard variants which are not present in at least two files, please see the usage page
```
-n, --nfiles [+-=~]INT     Output positions present in this many (=), this many or more (+),
                                         this many or fewer (-), the exact (~) files
```
If you want the program to output a list of variants, not a VCF, just leave out the `-p` option to obtain an output like follows
```
bcftools isec -n +1 a.vcf.gz b.vcf.gz
2	3188209	GA	G	01
2	3199812	G	GTT,GT	10
```

**Comment by bioinfoMMS** [comment]
Ok so to confirm,

 0000.vcf would be the SNPs from A.vcf.gz that were found in two or more of the vcf files?

**Comment by pd3** [comment]
Yes

**Comment by zuyan413** [comment]
and 0001.vcf would be the SNPs from B.vcf.bz?

**Comment by pd3** [comment]
Yes. The program writes a README.txt file which describes the outputs. For example
```
$ bcftools isec -n +1 -p rmme a.vcf.gz b.vcf.gz
$ cat rmme/README.txt 
This file was produced by vcfisec.
The command line was:	bcftools isec  -n +1 -p rmme a.vcf.gzb.vcf.gz

Using the following file names:
rmme/0000.vcf	for stripped	a.vcf.gz
rmme/0001.vcf	for stripped	b.vcf.gz
```
