### ISSUE TITLE
bcftools does not appear to handle SIGPIPE gracefully

### ISSUE THREAD

**Issue by anderspitman** [samtools/bcftools#1999]
To reproduce:

`bcftools view <vcf with more than 5 lines> | head -n 5`

After head finishes processing 5 lines and exits, bcftools will attempt to continue writing to the pipe and receive `SIGPIPE` from the OS, and exit with code 141. This breaks scripts that use `set -eo pipefail`.

Background info:

https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q

https://github.com/samtools/samtools/issues/1567

http://www.pixelbeat.org/programming/sigpipe_handling.html

**Comment by pd3** [comment]
I don't understand what is the problem. This seems to work alright
```
$ cat test.sh
#!/bin/bash
set -eo pipefail
bcftools view test.vcf | head -1
echo "done"

$ ./test.sh
##fileformat=VCFv4.2
done
```

**Comment by pd3** [comment]
I believe this is resolved, please complain if not
