### ISSUE TITLE
question: maintaining source information on bcftools concat

### ISSUE THREAD

**Issue by zeeev** [samtools/bcftools#2002]
When concatenating multiple VCF files (multi-sample) is it possible to annotate the source of the variant as in info field, especially where there is overlap between callers?

something like:
```
SOURCE=DeepVariant,GATK...
```

Any other suggestions on a merging pipeline would be very welcome. Trying to avoid duplicate records or FN/FP merges. 

```
bcftools norm --multiallelic - {multiple.vcfs in parallel from different callers}
bcftools concat -O b -a -d all {multiple.vcfs}
```

**Comment by pd3** [comment]
Interesting use case. The primary purpose of the program is to join files that were split by region for parallel processing, it was not intended for merging callsets this way and there are no plans to add the feature you requesting. 

What you could do instead is to add these annotations after the fact, using `bcftools annotate`..?
