### ISSUE TITLE
Can you filter for private 1/1 genotype?

### ISSUE THREAD

**Issue by Axze-rgb** [samtools/bcftools#2004]
Hello, view command has -x to select site where the non reference allele is unique to a given sample list. But what if I want to do the same think but to identify private 1/1 instead of 0/1 sites? Thanks 

It's of course not difficult to do in a panda dataframe but I was curious to know if bcftools could do it.

**Comment by pd3** [comment]
Such filtering can be done using filtering expressions such as
```
bcftools view -i'GT="ra"'
bcftools view -i'GT="aa"'
```
Please see here for more http://samtools.github.io/bcftools/bcftools.html#expressions
