### ISSUE TITLE
[Feature Request] Index multiple files at once

### ISSUE THREAD

**Issue by rickymagner** [samtools/bcftools#2006]
Hi,

This feature request is pretty straightforward, and hopefully not too hard to implement. If anyone more familiar with the codebase wants to suggest a solution, I'd be happy to try implementing it myself.

Goal: Allow `bcftools index` to index multiple files, in succession, e.g. `bcftools index -t file1.vcf.gz file2.vcf.gz`. Currently (version 1.18) the tool runs without error in this way, but only indexes the first file provided. Maybe it's also possible to even parallelize the process?

Hopefully this just means adding a loop somewhere!

**Comment by pd3** [comment]
This would have to be added in `vcfindex.c`, but to be honest I am not convinced it is worth it. The same effect can be achieved with a simple shell one-liner or a script. The code would become unnecessarily messier, considering various branches, such as reading the data from stdin.  As a separate point, parallelization is usually not a good idea for I/O intensive tasks.
