### ISSUE TITLE
Duplicate sample error with reheader

### ISSUE THREAD

**Issue by sethsh7** [samtools/bcftools#2009]
I have two samples R244 and R244B, I want to remove R244 and change R244B->R244.

First I remove the sample with view:
`bcftools view -s ^R244 my.vcf.gz`
Then I create a two column tab delimited file in the format R244B\tR244 with every sample:
`bcftools reheader --samples name_map.txt my.vcf.gz`
This completes successfully but then any command on the resulting file is met with:
`[E::bcf_hdr_add_sample_len] Duplicated sample name 'R244'`
Pulling the sample list line out of the VCF manually shows only one instance of R244 with all changed names in the correct places and the correct number of samples.

Any ideas?

**Comment by pd3** [comment]
I am unable to reproduce the error:
```
$ cat test.vcf
##fileformat=VCFv4.2
##contig=<ID=1>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	R244	R244B
1	2	.	G	A	.	.	.	.	.	.

$ bcftools view -s  ^R244 test.vcf -o test2.vcf
$ bcftools query -l test2.vcf
R244B

$ echo -e 'R244B\tR244' > test.txt
$ bcftools reheader -s test.txt test2.vcf | bcftools query -l
R244
```
Maybe you are trying to reheader the original file by mistake? That would give the same error message you are showing.
