### ISSUE TITLE
Split-vep error with version 1.12 and 1.18

### ISSUE THREAD

**Issue by GACGAMA** [samtools/bcftools#2010]
Hi everyone!

I'm trying to expand an anotated VEP (vep 109) vcf file. This file was also filtered using filter_vep

When I do:

`bcftools +split-vep -f '%CHROM\t%POS\t%REF\t%ALT\t%CSQ\n' -d -A tab $MYVCF `

In bcftools 1.12 I get the error: 
Segmented core (fault)

In bcftools 1.18 I get the error:

`[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either the fields are incorrect or spaces are present instead of tabs:`

If I use: 
`bcftools +split-vep -l $MYVCF `

In bcftools 1.12 I get the correct info, in 1.18 I get:

`[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either the fields are incorrect or spaces are present instead of tabs:`

If I bgzip the file, tabix index it, in bcftools tools 1.12 the first command works fine.

vcf (reproducible in conda bcftools 1.18 and stand-alone 1.12

[Example3.vep.txt](https://github.com/samtools/bcftools/files/12823183/Example3.vep.txt)

**Comment by pd3** [comment]
The VCF file has incorrect header line. It reads
```
#CHROM	POS	GENE	REF	ALT	QUAL	FILTER	INFO	FORMAT
```
but must be
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT
```
Please check the VCF specification https://samtools.github.io/hts-specs/VCFv4.3.pdf
