### ISSUE TITLE
bcftools mpileup Illumina-1.3+ encoding

### ISSUE THREAD

**Issue by gangxuehzau** [samtools/bcftools#2013]
hello，

I see the quality scores expected by samtools mpileup as follow:

 -6, --illumina1.3+ Assume the quality is in the Illumina 1.3+ encoding.

While how do I specify **llumina1.8**  encoding?

Thanks

**Comment by pd3** [comment]
This option is ages old and was introduced to fix some faulty BAMs at that time. No new data should require its use, correctly formatted files are interpreted according to the BAM/CRAM specification
