### ISSUE TITLE
bcftools concat doesn't work !

### ISSUE THREAD

**Issue by jefflllyyy** [samtools/bcftools#2017]
Hello, I have two VCF files, each with 100 sample columns, and the sample columns are the same, but their SNPs are different. How can I merge the two VCF files to obtain all the SNPs from these two VCF files? Can I use the command bcftools concat -D -a 1.vcf 2.vcf -o total.vcf to merge them?

**Comment by pd3** [comment]
If the files are indexed, then yes, it should work. If it does not, you'll need to provide more details, for example the error message printed by the program...
