### ISSUE TITLE
bcftools mpileup error: rcns_set_reads todo: unknown cigar operator 3

### ISSUE THREAD

**Issue by webbchen** [samtools/bcftools#2018]
Good evening, all

I've aligned RNA-seq reads to a humongous reference plant genome and would like to call variants from these.
The bam files can only be indexed with csi type indices, not with .bai indices. (may or may not be relevant)
Samtools quickcheck highlighted no issues with alignment files.

bcftools package is installed through conda.
```
bcftools --version
bcftools 1.18
Using htslib 1.18
Copyright (C) 2023 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
When I ran:
```
bcftools mpileup \
/path/to/sample13-1.sorted.bam \
-f /path/to/ref/ref.fasta \
-a "FORMAT/AD" \
 --indels-2.0 \
--indel-bias 0.75 \
 -L 2000 \
-q 20 \
-m 5 \
--threads 12  \
| bcftools call \
--ploidy 2 \
--threads 12 \
-m \
-v  \
-Ob \
-o /path/to/variants/sample13-1.snps.vcf.gz
```
I get the following error very swiftly to which I found no hint anywhere to where it comes from and how to get rid of it:
```
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
rcns_set_reads todo: unknown cigar operator 3
```
What is going wrong?

Many thanks,

AWebb

**Comment by webbchen** [comment]
Update:
It seems to be the "--indels-2.0" setting which upsets things. Although I have used it before, but on much smaller genomes, with genomic reads aligning.

AWebb

**Comment by pd3** [comment]
I just pushed a commit that should fix the error, it is caused by unhandled cigar operator N. This should be considered a tentative fix, at the moment I don't have good data to test this on.
