### ISSUE TITLE
pludgin "+fill-tags" doesn't work with deletions

### ISSUE THREAD

**Issue by carolynzy** [samtools/bcftools#2019]
Hi there,  

I have some vcf files converted from bed files. I found the index of positions have some discrepencies or small errors with different sources, e.g. produced by different softwares with the same samples. So I would like to use `bcftools annotate -x "INFO/END"` and `bcftools +fill-tags`  to reannotate the INFO/END field. 

However, I found it worked with insertions but not with deletions, as in both cases, the command set the END equal to the START.  I looked into the C code, but I have no experience with C actually so I couldn't figure out what would be the problem. 

So I attached a small example file here [test2.txt](https://github.com/samtools/bcftools/files/12909576/test2.txt) for you to reproduce the probelm. If you help to fix this, I would really appreciate!

Kind regards,

Yang

**Comment by pd3** [comment]
What do you expect  to happen in case of insertions? If we have, say, POS=1 REF=C ALT=CTTT, then POS=2 is not affected by the change, END=1 is correct.
