### ISSUE TITLE
Unexpected handling of missing genotypes in convert --gensample

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#202]
It appears that `bcftools convert --gensample` converts missing genotypes to the probability triplet `1 0 0`.  This means that it sets all missing sites to REF/REF.  I find this quite unexpected.  The shapeit documentation states that missing genotypes should be coded as `0 0 0` (https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#gensample). 

On the other hand, I find no reference to how to code missing genotypes in the Oxford .gen file spec (http://www.stats.ox.ac.uk/~marchini/software/gwas/file_format.html).  In fact that spec states that the triplet needs to sum to 1.

However, `qctool` seems to filter out sites with triplets set to `0 0 0` when using the `-snp-missing-rate` flag to filter out sites with missing genotypes.

So, it seems the de-facto way to code missing genotypes is `0 0 0`.  An alternative would be `0.333 0.333 0.333`.  However, I think `1 0 0` is definitely wrong and should be changed.

What do people think?

**Comment by wkretzsch** [comment]
PS I am happy to take a shot at changing this when I get a little time, if there is agreement that this change should be made.

**Comment by pd3** [comment]
I added this, thank you.
