### ISSUE TITLE
bcftools norm Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Rohit-Satyam** [samtools/bcftools#2020]
Hi @pd3 
I was trying to split the multiallelic variants using `bcftools norm` but I keep on getting an error. I got the VCF from [here](https://ngs.sanger.ac.uk/production/malaria/Resource/34/Pf7_vcf/) and subset it for region `Pf3D7_03_v3:365177-366948` to test it on a small dataset.

```
bcftools norm --multiallelics -any --old-rec-tag OLD_CLUMPED --atomize -o bcftools.normalized.gatk.vcf Pf3D7_03_v3.pf7.vcf.gz
Segmentation fault (core dumped)
```

**Comment by pd3** [comment]
Thank you for the bug report, this is now fixed
