### ISSUE TITLE
plot-vcfstats error

### ISSUE THREAD

**Issue by Seif-el-din** [samtools/bcftools#2024]
So, hi. I have been facing a problem with the plot-vcfstats function and was hoping anyone could help.

When I run the function, the following error message pops up:

`Plotting graphs: python3 plot.py
/home/seif_el_din/Mapping/plot.py:234: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  cm  = mpl.cm.get_cmap('autumn')
Neither pdflatex or tectonic were found in your PATH, impossible to create a PDF at /usr/bin/plot-vcfstats line 112.
        main::error("Neither pdflatex or tectonic were found in your PATH, impossi"...) called at /usr/bin/plot-vcfstats line 1934
        main::create_pdf(HASH(0x5584c2466d28)) called at /usr/bin/plot-vcfstats line 73`

So like what should I do to resolve this issue? Should I download some package or what?
Thank you in advance.

**Comment by pd3** [comment]
Hi, this has been addressed a while ago, https://github.com/samtools/bcftools/issues/1878 and https://github.com/daviesrob/bcftools/commit/3298b7c7ba6b98de3b3fe7d448b88ef77b0b0118

Please use the latest version which can be obtained here
https://github.com/samtools/bcftools/blob/develop/misc/plot-vcfstats

**Comment by Seif-el-din** [comment]
Sorry, seems like I missed that issue. Thanks a lot!

**Comment by pd3** [comment]
If you follow the link above, on the github there is the link 'raw' which allows to download the file directly: https://raw.githubusercontent.com/samtools/bcftools/develop/misc/plot-vcfstats

**Comment by sussiegu99** [comment]
Hi, I also have the same problem.

I tried this 
wget https://github.com/samtools/bcftools/blob/develop/misc/plot-vcfstats
 wget https://raw.githubusercontent.com/samtools/bcftools/develop/misc/plot-vcfstats

the following error message pops up:
--2024-11-01 09:26:17--  https://github.com/samtools/bcftools/blob/develop/misc/plot-vcfstats
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
Unable to establish SSL connection.

I don't know how to address it .What can I do? Thank you in advance.
