### ISSUE TITLE
If I put two adjacent small variants together, will it be divided into two variants by "bcftools norm"?

### ISSUE THREAD

**Issue by tanger-code** [samtools/bcftools#2027]
Hi.
If I put two adjacent small variants  together, will it be represented separately when it's normalized?
For example, if I have 2 SNPs:
```
chrom     pos     ref    alt
chr1      100     A      G
chr1      102     C      T
```
And I represent them jointly like this：
```
chrom   pos     ref     alt
chr1    100     ANC     GNT
```
When I use `bcftools norm` command, will it be divided into two variants?

**Comment by pd3** [comment]
If and only if you run with the `-a, --atomize` option, then yes :)
