### ISSUE TITLE
bcftools does not recognize some INFO fields

### ISSUE THREAD

**Issue by meritxellop** [samtools/bcftools#203]
Hi devs,

I want to normalize a vcfFIle (test.vcf)  that looks OK according to vcf-validator (vcftools v.0.1.12):

% vcf-validator test.vcf
The header tag 'reference' not present. (Not required but highly recommended.)

However, bcftools (v.0.2.0-rc8) does not recognize some INFO fields:

% bcftools view -H test.vcf | head
[W::vcf_parse] INFO 'LEN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CANCER' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VARFREQ' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VARSCANPVAL' is not defined in the header, assuming Type=String
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03

What is the problem? Find vcfFile content below

% cat test.vcf
##fileformat=VCFv4.1 
##fileDate=20150121 
##source=TCGA
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id"> 
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position"> 
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type"> 
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138"> 
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant"> 
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call"> 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03

**Comment by mp15** [comment]
Has GitHub stripped out some of your post or is that how it's meant to look?  The lines:
##contig=
##INFO= 
Seems incomplete, they should be defining the sequence your VCF was mapped to and the nature of the INFO fields. bcftools is behaving properly in this instance, it's outputting only the body of your VCF because you specified -H and the lines starting with [W::vcf_parse] INFO are only warnings written to stderr that your VCF is in fact not valid.

**Comment by meritxellop** [comment]
GitHub has stripped out my post. How can I provide the content of the test.vcf?

**Comment by meritxellop** [comment]
##fileformat=VCFv4.1 
##fileDate=20150121 
##source=TCGA
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id"> 
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position"> 
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type"> 
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138"> 
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant"> 
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call"> 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03

**Comment by tommycarstensen** [comment]
I have no problems with bcftools1.1 on the VCF you posted. Current release as of today is 1.2. You are using v.0.2.0-rc8.

**Comment by mp15** [comment]
Curious I could not reproduce your error with 0.2.0-rc8:
$ mkdir tmpst
$ cd tmpst
$ git clone git@github.com:samtools/htslib.git
$ cd htslib
$ git checkout 0.2.0-rc8
$ git clone git@github.com:samtools/bcftools.git
$ cd bcftools
$ git checkout 0.2.0-rc8
$ make

Then
$ tmpst/bcftools/bcftools view -H test.vcf | head
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=0.0015
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=0.0059
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=0.0096
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.4;VARSCANPVAL=0.0068
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=0.0063

**Comment by meritxellop** [comment]
I have tried version 1.0 and 1.2. Same error!

% cat test.vcf 
##fileformat=VCFv4.1 
##fileDate=20150121 
##source=TCGA
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id"> 
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position"> 
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type"> 
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138"> 
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant"> 
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call"> 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03


% bgzip test.vcf # v.1.2
% tabix -p vcf test.vcf.gz # v.1.2
% bcftools view -H test.vcf.gz # v.1.2
[W::vcf_parse] INFO 'LEN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CANCER' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VARFREQ' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VARSCANPVAL' is not defined in the header, assuming Type=String
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03

**Comment by mp15** [comment]
$ cat test.vcf
##fileformat=VCFv4.1
##fileDate=20150121
##source=TCGA
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id">
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position">
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type">
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138">
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant">
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=1.5e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=5.9e-03
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=9.6e-03
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.40;VARSCANPVAL=6.8e-03
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=6.3e-03
$ bgzip test.vcf 
$ tabix -p vcf test.vcf.gz
$ bcftools view -H test.vcf.gz
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=0.0015
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=0.0059
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=0.0096
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.4;VARSCANPVAL=0.0068
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=0.0063

Tried again and once again could not reproduce, I suspect this means it's either a problem with your platform or environment.  Could you give us a bit more detail on what you're running this on? It is curious that SAMPLE and CANCER's definitions are recognised but the rest aren't, perhaps something to do with them being defined as strings and the rest not being so.  Just to exclude a version mismatch issue with HTSLIB, could you try downloading: https://github.com/samtools/bcftools/releases/download/1.2/bcftools-1.2.tar.bz2 and see if that works?

**Comment by meritxellop** [comment]
SAMPLE is recognized, but CANCER is not:

[W::vcf_parse] INFO 'CANCER' is not defined in the header, assuming Type=String

Sure, I can try to download https://github.com/samtools/bcftools/releases/download/1.2/bcftools-1.2.tar.bz2 to check if it works

**Comment by meritxellop** [comment]
Problem solved. In the original test.vcf file, the line terminators of the unrecognized fields CANCER, etc. were not unix fileformat. 

I have corrected that and tried with all versions of bcftools mentioned.
Fields are happily recongized now. Thanks a lot and sorry for the inconveniences.

% bcftools view -H test.vcf.gz
9	10353	.	A	C	50	PASS	SAMPLE=TCGA-GN-A262-06A;LEN=1;CANCER=SKCM;VARFREQ=0.39;VARSCANPVAL=0.0015
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-43-3920-01A;LEN=1;CANCER=LUSC;VARFREQ=0.59;VARSCANPVAL=0.0059
9	10380	.	G	T	50	PASS	SAMPLE=TCGA-55-1596-01A;LEN=1;CANCER=LUAD;VARFREQ=0.43;VARSCANPVAL=0.0096
9	10440	.	C	T	50	PASS	SAMPLE=TCGA-CN-5365-01A;LEN=1;CANCER=HNSC;VARFREQ=0.4;VARSCANPVAL=0.0068
9	10503	.	G	C	50	PASS	SAMPLE=TCGA-BH-A18R-01A;LEN=1;CANCER=BRCA;VARFREQ=0.43;VARSCANPVAL=0.0063
