### ISSUE TITLE
bcftools mpileup: interpreting AD (Allelic depth) annotation

### ISSUE THREAD

**Issue by rmurray2** [samtools/bcftools#2031]
I'd like to get the nt count at each position from a bcf file (exactly like [this](https://github.com/samtools/bcftools/issues/992) question) 

The posted solution is: `bcftools mpileup --annotate FORMAT/AD`. I tried using `--annotate` and passing the output to `bcftools call`, but I'm not entirely clear about the what the allelic depth field means in the resulting bcf file. Here are a couple of bcf file entries with only the relevant info shown: 

**example 1:**

    REF=G
    ALT=C,A,<*>
    DP=111
    AD=109,1,1,0

Question 1: Does this mean that the nucleotide counts at this position are G:109; C:1; A:1; T:0 ? 
Question 2: What does <*> mean? 

**example 2:** 

    REF=G
    ALT=C,T,A
    DP=122
    AD=118,2,1,1

Question #3: Does this mean the nucleotide counts are G:118; C:2; T:1; A:1 ?  

Thanks!

**Comment by pd3** [comment]
That is correct. The symbolic star allele `<*>` is a placeholder for alleles not observed in the data which allows to represent genotype likelihoods of non-reference genotypes.

See also the VCF specification https://samtools.github.io/hts-specs/VCFv4.3.pdf
