### ISSUE TITLE
bcftools 1.19 annotate not working with "." and "+" modifiers for adding TAG fields

### ISSUE THREAD

**Issue by epsalazarf** [samtools/bcftools#2038]
Hi,

So I recently updated bcftools to the latest version (1.19) and found out that my annotations scripts are not working as intended anymore. If I try the following command:

`bcftools annotate -a ref.vcf.gz -c .+ID input.vcf.gz`

I get the message: `The tag ".+ID" is not defined in ref.vcf`, taking the modifiers  ("." to replace missing IDs, "+" to not replace present IDs) literally as a field name.

But according to the [bcftools annotate](https://samtools.github.io/bcftools/howtos/annotate.html) documentation, this is the correct usage and the same command works perfectly in the previous 1.18 version.

Has this behavior been modified (for which I couldn't find documentation) or is it a bug?

**Comment by pd3** [comment]
There is no such release as 1.19. Maybe you are running 1.9 by mistake?
