### ISSUE TITLE
--ploidy 2 function not working? 

### ISSUE THREAD

**Issue by officialnaturalist** [samtools/bcftools#2053]
I am not able to generate variants for my diploid organism. The script I ran looks something like this: 

`bcftools call --threads 10 --ploidy 2 -m -v -o ../vcf/CapricornB1_11_S11_variants.vcf CapricornB1_11_S11_raw.bcf
`

I don't get any errors, but I don't get any files generated either. The output of this code is:

`PRE-DEFINED PLOIDY FILES

 * Columns are: CHROM,FROM,TO,SEX,PLOIDY
 * Coordinates are 1-based inclusive.
 * A '*' means any value not otherwise defined.

GRCh37
   .. Human Genome reference assembly GRCh37 / hg19

GRCh38
   .. Human Genome reference assembly GRCh38 / hg38

X
   .. Treat male samples as haploid and female as diploid regardless of the chromosome name

Y
   .. Treat male samples as haploid and female as no-copy, regardless of the chromosome name

1
   .. Treat all samples as haploid

Run as --ploidy <alias> (e.g. --ploidy GRCh37).
To see the detailed ploidy definition, append a question mark (e.g. --ploidy GRCh37?).`

I feel like I probably don't know how to use the ploidy function? Do I have to generate a ploidy file??

**Comment by pd3** [comment]
This looks like a bug fixed two years ago by https://github.com/samtools/bcftools/commit/5105724d8b05a82094cbc0f461dba2539f9a4a50. Note the bug only prevented from explicitly stating `--ploidy 2`, but it is the default setting and does not need to be given explicitly
