### ISSUE TITLE
MAF Filtering - difference between two approaches

### ISSUE THREAD

**Issue by nirav572** [samtools/bcftools#2054]
Hi, what's the difference between the two approaches to filter for variants above a certain MAF threshold?

`bcftools view -q 0.01` v/s `bcftools -i 'MAF>0.01'`?
Also, do they compute the MAF value, or look for it in tag info?

Thank you!

**Comment by alanmejiamaza** [comment]
Adding something to the thread. 
It seems that -q 0.01:minor, excludes <=0.01 based on minor allele. the MAF is not doing anything,using bcftools/1.14 (conda env).
I'd add another question.

If I need to exclude >0.01 MAF using bcftools, what is the command?
bcftools -q 0.01:major test.vcf > test2.vcf ; this doesnt work on my end

Any help?

**Comment by pd3** [comment]
Both use the same underlying htslib's `bcf_calc_ac()` function which sets AC,AN from existing INFO tags or, when absent, from GT fields. They should give the same results.
