### ISSUE TITLE
bcftools 1.19 - consensus - different warnings for overlapping variants

### ISSUE THREAD

**Issue by salvatoreloguercio** [samtools/bcftools#2058]
Hello,

I am running _bcftools consensus_ on a series of genomic regions (fasta), by applying variants from a single subject and getting IUPAC codes as output ( _-s <subject> -H I_ ).

For overlapping variants, now I am getting two kinds of warnings -
1) "_The site chr[..]:[..] overlaps with another variant, skipping..._"
and
2) "_Warning: ignoring overlapping variant starting at chr[..]:[...]_"

More specifically, suppose I have two regions - _chr1:100-200_, and _chr1:300-400_ (just using these small coords as example):
- _bcftools consensus_ run on the first region will output only warnings of type 1).
- when running _consensus_ on the second region, I get the warning 2) for positions belonging to the first region (chr1:100-200), then the usual warning 1) for positions within the actual region being processed (chr1:300-400).

In this example, the vcf used for both regions would be the same and have variants spanning both intervals (_chr1:100-400_).

I am used to the warning 1) since previous versions of _bcftools_, but kind of confused by the warning 2) - since it considers earlier variants.

Just wondering if you have an explanation for this behavior - hopefully not a bug?

**Comment by pd3** [comment]
The two warnings are emitted from two slightly different contexts. The code is a bit opaque, so it's hard to tell without seeing specific examples, but the difference should be harmless.
