### ISSUE TITLE
view options -s and -x slow when combined

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#209]
It seems, that for 2000 samples doing:
| bcftools view -s $sampleID -x

Is *much* slower than doing:
| bcftools view -s $sampleID \
| bcftools view -s $sampleID -x

The commands also yield different results. Can the underlying algorithm be changed, so the sampleID filtering is carried out before the filtering of private variants? This is the behaviour I was expecting. If not possible, then I will close this issue and make a pull request on the documentation instead.

**Comment by mcshane** [comment]
Hi Tommy,

Your second example there is not going to give you what you are after. `-x` is selecting alleles private to the subset (subset being defined by the `-s` or `-S` options). In your second case you have selected your one sample, then are looking for sites private to that sample without considering any other samples - that command is essentially finding non-REF sites in the selected sample.

The command is slow, but can be a bit faster if you AC and AN are in the INFO column of your 2000 sample VCF. Queries like this may be better suited to GQT and BGT.
