### ISSUE TITLE
Inverse consensus VCF

### ISSUE THREAD

**Issue by mbhall88** [samtools/bcftools#2096]
Hi,

I have applied the variants from a VCF to a reference with `bcftools consensus` and was wondering if you know of a way to get the "inverse VCF" - i.e. the VCF that would return the consensus sequence back to the original reference? The REF and ALT would be swapped, but the POS will obviously change.

It would nice to have this as an optional output to `bcftools consensus` if that is within scope?

**Comment by pd3** [comment]
What is the motivation for the request? 

There is currently no plan to support that, but it should not be difficult to write a script that takes the chain file produced with `-c` and the fasta file and converts it to a VCF. If it's well written, I am happy to include it among bcftools/misc scripts.

**Comment by mbhall88** [comment]
The motivation is that I have applied some variants to a reference and then I want to call variants with respect to the other genome and need the "truth" VCF - i.e. the variants we expect to find.

It ended up being a reasonably easy script to write, as you say. Though I didn't use (or know about) the chain file. Is there somewhere that documents the chain file and its format?

**Comment by pd3** [comment]
The format is documented fore example here https://genome.ucsc.edu/goldenPath/help/chain.html
