### ISSUE TITLE
bcftools sort problem?

### ISSUE THREAD

**Issue by SZ-qing** [samtools/bcftools#2103]
I have a vcf file where the chromosome numbers are not in order, 
so I want to sort the chromosomes in order to build an index using tabix. 
but there is a problem where the `POS` columns start counting from `1 `after using the `sort `function, which leads to a disorder in the RSPOS information.
Command line: 
`bcftools sort --temp-dir ./tmp/ GCF_000001405.39.renamed.vcf -o GCF_000001405.39.renamed.sorted.vcf `

Before sort data: 
![image](https://github.com/samtools/bcftools/assets/85827219/8e20f560-0c0b-4c5f-9f1f-f32b80608c30)   

After sort data:
![image](https://github.com/samtools/bcftools/assets/85827219/5c26ac51-ac54-4293-b3ed-fb83c7ff8505)

My bcftools version is : **1.18-15-g21755519 (using htslib 1.18)**

**Comment by pd3** [comment]
Uh, that's very odd indeed. Can you share a test case to reproduce the problem, please?

**Comment by SZ-qing** [comment]
> Uh, that's very odd indeed. Can you share a test case to reproduce the problem, please?

VCF file was from dbSNP database (version is b155): 
`wget  https://ftp.ncbi.nih.gov/snp/archive/b155/VCF/GCF_000001405.39.gz`
The chromosome ID inside this file is in `Refseq` format, and I need to convert it to regular format such as `1, 2, 3`, etc., so I downloaded the corresponding conversion data from [NCBI,](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001405.39/) and used `bcftool annotate` to do the ID conversion, and at this time, all the POS information is normal: 
`bcftools annotate --rename-chrs processed_id_data.txt GCF_000001405.39.gz -o GCF_000001405.39.renamed.vcf`  
**processed_id_data.txt:**
![image](https://github.com/samtools/bcftools/assets/85827219/7a434982-1d26-4101-97ad-4d8e835b43e4)
**GCF_000001405.39.renamed.vcf:**  
![image](https://github.com/samtools/bcftools/assets/85827219/beaf3225-7bd3-4e8d-a654-ff3bfb96815b)

The next step is to sort using bcftool sort:   
`bcftools sort --temp-dir ./tmp/ GCF_000001405.39.renamed.vcf -o GCF_000001405.39.renamed.sorted.vcf`
**GCF_000001405.39.renamed.sorted.vcf:** 
![image](https://github.com/samtools/bcftools/assets/85827219/2fefc80a-3548-4a67-996a-f1e044870b83)

At this point the POS information has been encoded from 1.

**Comment by SZ-qing** [comment]
> Uh, that's very odd indeed. Can you share a test case to reproduce the problem, please?

I'm very sorry, I found that there are multiple `pos` info corresponding to the same `RS id` in these dbSNP data, 
so bcftool is fine, thanks!
