### ISSUE TITLE
bcftools split vep miss variant without allele frequency when using -f to print gnom_af 

### ISSUE THREAD

**Issue by liuhankui** [samtools/bcftools#2104]
bcftools +split-vep vep.vcf -s worst -f "%CHROM %POS %REF %ALT\n"

chr18 12312939 G C
chr18 12312971 C T
chr18 12314310 G C

bcftools +split-vep vep.vcf -s worst -f "%CHROM %POS %REF %ALT %gnomADg_AF\n"

chr18 12312939 G C 0.800479
chr18 12314310 G C 0.790057

--------------------------
miss chr18 12312971

**Comment by pd3** [comment]
Assuming you are using a recent version of the plugin (1.18+), you can provide the option `-X, --keep-sites`.

I updated the documentation to emphasize that unlike `bcftools query -f`, the plugin `bcftools +split-vep -f` drops lines where all queried VEP fields are empty
```
-x, --drop-sites      Drop sites without consequences after -s is applied (the default with -f)
-X, --keep-sites      Do not drop sites without consequences (the default without -f)
```

I hope this helps

**Comment by liuhankui** [comment]
-X, a nice option, thanks a lot!
