### ISSUE TITLE
Computation of INFO tags in bcftools +fill-tags

### ISSUE THREAD

**Issue by nirav572** [samtools/bcftools#2107]
When utilizing `bcftools +fill-tags`, is the computation of various INFO tags performed every time the command is executed, or only when INFO columns are empty?

For instance, if I reduce the dataset to fewer samples and wish to recalculate AC/AF/AN, what would be the best way to go about it?

Some clarification regarding this would be helpful on the documentation page as well.
Thank you!

**Comment by pd3** [comment]
If you are removing samples using `bcftools view --samples` , then INFO/AC and INFO/AN are updated automatically. The rest (INFO/AF) will be updated only with `bcftools +fill-tags` and there is no speed penalty if it simultaneously updates also AC,AN again.

**Comment by nirav572** [comment]
Thank you!
