### ISSUE TITLE
How can bcftools filter samples with large fraction of missing site?

### ISSUE THREAD

**Issue by Neo-xbx-00** [samtools/bcftools#2112]
Hi,
 I'd like to use bcftools to filter my SNP dataset, and I wonder how bcftools remove samples with  large fraction of missing site?

**Comment by pd3** [comment]
If I understand the query correctly, it is asking how to remove sites with large number of missing genotypes.

Something like this should work:
```
bcftools view -e 'F_PASS(GT=="mis") > 0.9'
```
