### ISSUE TITLE
Feature Request: Add REF to gvcf convert

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#212]
Thanks for implementing gvcf support. A few gvcf requests:

1. Is it possible to add the REF allele to the broken blocks during gvcf2vcf conversion?

2. Is it possible to apply the position filtering `-R` after the blocks are broken? Currently it returns every position within a block that intersects with one of the regions. My use case was extracting dbsnp positions. See below.

3. Performance. It's very slow relative to the other snappy functions. Any recommendations?

```
bcftools convert --gvcf2vcf tmp.gvcf -O z -R dbsnp142.vcf.gz > tmp_dbsnp142.vcf.gz
```

**Comment by mcshane** [comment]
1. was added in cd1ebd1119aabf5b099983f88e978bac6190ad7f

2. You could use -R before expansion as you have then pipe into another view with -T like:

```
bcftools convert --gvcf2vcf tmp.gvcf -O u -R dbsnp142.vcf.gz | bcftools view -O z -T dbsnp142.vcf.gz > tmp_dbsnp142.vcf.gz
```
Does that work for you?
