### ISSUE TITLE
Filtering using file.txt for specific fields

### ISSUE THREAD

**Issue by GACGAMA** [samtools/bcftools#2126]
Hi
I would like to know if it is possible to filter a field by a file list.
For example, let's say I have a VEP annotated file with the CSQ field "Feature", which is the transcript ID.
If I have a file.txt with thousands of transcript IDs of interest, how could I filter my VCF using this list?

For example:

`
bcftools +split-vep -c Feature:String file.vcf.gz -i 'Feature=@file.txt'
`

Where file txt is a simple list of IDs

```
ENST0000000001
ENST0000000002
ENST0000000003
ENST0000000004
ENST0000000005
```

If this is not possible, how could it be implemented?

**Comment by pd3** [comment]
It is possible and should work.
