### ISSUE TITLE
can't add the VAF tag

### ISSUE THREAD

**Issue by boutrys** [samtools/bcftools#2127]
when I try to add the VAF tag I get an error
```
$BCFTOOLS +fill-tags ${OUTPUT_DIR}/vt.vcf.gz -Oz -o ${OUTPUT_DIR}/vt_filltag.vcf.gz -- -t FORMAT/VAF
```

My log looks like that 
```
/work/gr-fe/sboutry/tools/bcftools/install/bin/bcftools +fill-tags /work/gr-fe/sboutry/excalibur/input/11_12_23_gvcf_FVH/pre_annot/vt.vcf.gz -Oz -o /work/gr-fe/sboutry/excalibur/input/11_12_23_gvcf_FVH/pre_annot/vt_filltag.vcf.gz -- -t FORMAT/VAF
Warning: cannot add the VAF/VAF1 annotations, the required FORMAT/AD tag is missing at chr1:1.
         (This warning is printed only once.)
[E::bgzf_read_block] Failed to read BGZF block data at offset 35614981522 expected 1566 bytes; hread returned -1
/var/spool/slurmd/job20149529/slurm_script: line 45: 3094594 Bus error               (core dumped) 
```
Anyone has an idea ?

Thanks so much in advance

Simon

**Comment by pd3** [comment]
Which version of bcftools are you running? The program should just print a warning and skip sites which do not have FORMAT/AD tag present. If you are getting the error with the latest, can you provide a small test case, as I am not able to reproduce the problem on my data.

**Comment by boutrys** [comment]
Hello @pd3 , no idea why it crashed last week, since this weekend it is going as expected and skip sites which do not have FORMAT/AD tag present.

Thanks for your answer anyway, I'll close the issue 

Have a good day
