### ISSUE TITLE
A bug when bcftools trims alternate alleles not seen in subset

### ISSUE THREAD

**Issue by idadoudou** [samtools/bcftools#213]
When I trimmed the alternate alleles not seen in subset, the GT:AD:DP:GQ:PL of one sample will change from ./.:.:.:.:. to ./.:.:.:.:198 at the trimmed site. The number can be not 198 but other else such as 176. I think it is a bug.

$bcftools version
bcftools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.

**Comment by mcshane** [comment]
Hi. Sorry for the slow response. Do you still have the original record lying around to reproduce?
