### ISSUE TITLE
DIfference between "Absent", "Missing" and "Deletion" in bcftool consensus

### ISSUE THREAD

**Issue by Nagaemory** [samtools/bcftools#2134]
Hi all,

  I would like to know what are the options actually means and difference among them in bcftool consensus parameters

  Absent (--a)
  Missing (--M)
  Deletion (-mark-del)

Thanks

**Comment by pd3** [comment]
Mmmm, it is disappointing if the usage page is not clear enough
```
-a, --absent CHAR              Replace positions absent from VCF with CHAR
-M, --missing CHAR             Output CHAR instead of skipping a missing genotype "./."
    --mark-del CHAR            Instead of removing sequence, insert character CHAR for deletions
```

Absent from VCF = the position is not present in the VCF
Missing genotype = the genotype is set to missing ("." or "./."). 
Deletion = REF allele is longer than ALT allele, for example REF=CTT and ALT=C

Please read the VCF specification https://samtools.github.io/hts-specs/VCFv4.3.pdf
