### ISSUE TITLE
Difference between --atom-overlaps and --multi-overlaps

### ISSUE THREAD

**Issue by alexvasilikop** [samtools/bcftools#2142]
Could someone briefly explain the difference between these two options?

Thanks a lot

**Comment by pd3** [comment]
It's a bit confusing, isn't it.

The option `--multi-overlaps` is tied to the `--multiallelics` option. This one splits multiallelic sites into biallelic sites, for example the row `AA > A,CC` will be split into two rows `AA>A` and `AA>CC`. 

On the other hand, the option `--atom-overlaps` is ties to the `--atomize` option. This one breaks a complex allele into its atomic constituents, for example the row `AA>CC` will be split into two rows `A>C` and `A>C`. 

In both cases the program has to decide what to put in when heterozygous genotypes are split. For the `--atomize` case, see the example in the manual page
```
    # Before atomization:
    100  CC  C,GG   1/2

    # After:
    #   bcftools norm -a .
    100  C   G      ./1
    100  CC  C      1/.
    101  C   G      ./1

    # After:
    #   bcftools norm -a '*'
    #   bcftools norm -a \*
    100  C   G,*    2/1
    100  CC  C,*    1/2
    101  C   G,*    2/1
```  

Analogously for the `--multiallelics` case.

**Comment by alexvasilikop** [comment]
I assume that the dot then means something unknown but by definition different than 1 since otherwise it would not appear as a variant. From what I understand when splitting multiple alleles then default option is to use another alternative allele in the biallelic site and not the reference for comparison. 

In any case: it seems that multi-allelics --multi-overlaps is the option I am looking for> I am looking to perform both splitting (of any type of ALT variant) when they exist into single .ALT variants and subsequently normalization. Would this be the options below. It is not clear to me that if splitting is done then normalization would also be performed.

```bcftools sort -O v "!{sample_id}.single_sample.vcf" | \
    bcftools norm -m-any --multi-overlaps 0 --fasta-ref "!{ref_name}" --threads "!{num_threads}" -O v - | \
    bcftools sort -O v -o "${OUTPUT}```

**Comment by pd3** [comment]
Variants are normalized after splitting. (Note there were some improvements in the latest release 1.20 to handle simultaneous atomization and splitting of multiallelics.)

Regarding 'both' and 'any', it is described in the manual page http://samtools.github.io/bcftools/bcftools.html#norm
```
If only SNP records should be split or merged, specify snps; if both SNPs and indels should be 
merged separately into two records, specify both; if SNPs and indels should be merged into a 
single record, specify any.
```
