### ISSUE TITLE
norm doesn't normalize <DUP> symbolic variants

### ISSUE THREAD

**Issue by davmlaw** [samtools/bcftools#2145]
I raised an issue as #1919 "norm doesn't normalize symbolic variants" but it was closed after only fixing ```<DEL>``` - so there's no open issue for all of the other symbolic variants which are still affected.

```<DUP>``` is the next most common indel I guess so I've attached a normal VCF (which is normalized) and a symbolic representation of the same variant (which is not) as a test case:

[bcftools_norm.zip](https://github.com/samtools/bcftools/files/14832122/bcftools_norm.zip)

```
bcftools norm norm_dup_grch38.vcf -f /data/annotation/fasta/GCF_000001405.39_GRCh38.p13_genomic.fna.gz
```

The explicit alt one gets left aligned:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
NC_000001.11	117395877	.	G	GGATTACA	.	PASS	.
Lines   total/split/realigned/skipped:	1/0/1/0
```

**Comment by pd3** [comment]
This is now supported.
