### ISSUE TITLE
the question about bcftools view

### ISSUE THREAD

**Issue by jingydz** [samtools/bcftools#2147]
##Command
bcftools view -S sample.lst --force-samples -f PASS xxx.vcf.gz -Oz -o xxx.sample.vcf.gz --threads 4

The first error is:
[main_vcfview] Error: cannot write to xxx.sample.vcf.gz

Then I rerun it used the same command, I got the result file xxx.sample.vcf.gz. However, it appears to be incomplete.

The second error is:
[E::bgzf_uncompress] Inflate operation failed: 3
[E::bgzf_read_block] Invalid BGZF header at offset 11637101857
tbx_index_build failed: xxx.vcf.gz

Next, I ran the command tabix -p vcf xxx.sample.vcf.gz to create an index for the result file.

The third error is:
gzip: xxx.sample.vcf.gz: invalid compressed data--crc error
gzip: xxx.sample.vcf.gz: invalid compressed data--length error

Can anyone help me resolve this issue?

**Comment by pd3** [comment]
The first error suggests that the program is unable to create the output file.  It is not clear from your report when that happens, if there is an error with permissions (likely not, given the third error) or if quota was exceeded (is there enough space to write out the file?)

The second error suggests that the input file is truncated or corrupted. Try running `bcftools view -o /dev/null -Ou xxx.vcf.gz` to see if that might be the case.
