### ISSUE TITLE
about the bcftools mpileup setting

### ISSUE THREAD

**Issue by cnxiaobo94** [samtools/bcftools#2148]
Hi, 

I used bcftools for PSMC analysis data processing, using the following command line:
>>>
bcftools mpileup -C50 -Ou -I -R ${INDEL} -f ${REF} ${s}.rehead.bam --threads 56 | bcftools call -c -Ov --threads 56 | ${vcfutils} vcf2fq -d 6 -D 36 | gzip > ${s}.C50.fq.gz

But when using -C50 or not, I got different results (see picture). I wonder if I need to set this parameter at this step (mpileup)?
![psmc_test](https://github.com/samtools/bcftools/assets/67302941/a2c916fc-62f9-410d-a75d-db7632c68262)

Looking forward to your reply! thanks!

Best,
Bo

**Comment by pd3** [comment]
The argument -C is a heuristics to downgrade mapping quality of reads with excessive mismatches
```
*-C, --adjust-MQ* 'INT'::
    Coefficient  for  downgrading mapping quality for reads containing
    excessive mismatches. Given a read with a phred-scaled probability q of
    being generated from the mapped position, the new mapping quality is
    about sqrt((INT-q)/INT)*INT. A zero value (the default) disables this functionality.
```

Your pipeline does not contain a variant filtering set and as such will be heavily enriched for false positives. Variant filtering is a bit of a black magic, please check for a few tips here http://samtools.github.io/bcftools/howtos/variant-calling.html
