### ISSUE TITLE
bcftools annotate with duplicate vcf records

### ISSUE THREAD

**Issue by zd1** [samtools/bcftools#215]
Dear bcftools developers, 

I was trying to annotate a VCF with the variants released by the COSMIC VCF. I had an issue with duplicate rows. For example, in COSMIC, at 10:123279674, there are the following entries 

10	123279674	COSM1139349	G	A	.	.	GENE=FGFR2_ENST00000457416;STRAND=-;CDS=c.758C>T;AA=p.P253L;CNT=3
10	123279674	COSM1152152	G	C	.	.	GENE=FGFR2_ENST00000457416;STRAND=-;CDS=c.758C>G;AA=p.P253R;CNT=2
10	123279674	COSM49170	G	C	.	.	GENE=FGFR2;STRAND=-;CDS=c.758C>G;AA=p.P253R;CNT=7
10	123279674	COSM537801	G	A	.	.	GENE=FGFR2_ENST00000357555;STRAND=-;CDS=c.491C>T;AA=p.P164L;CNT=3
10	123279674	COSM537802	G	A	.	.	GENE=FGFR2;STRAND=-;CDS=c.758C>T;AA=p.P253L;CNT=3
10	123279674	COSM537803	G	A	.	.	GENE=FGFR2_ENST00000351936;STRAND=-;CDS=c.758C>T;AA=p.P253L;CNT=3
10	123279674	COSM915504	G	C	.	.	GENE=FGFR2_ENST00000357555;STRAND=-;CDS=c.491C>G;AA=p.P164R;CNT=1
10	123279674	COSM915505	G	C	.	.	GENE=FGFR2_ENST00000351936;STRAND=-;CDS=c.758C>G;AA=p.P253R;CNT=2

I have two entries of G>C at this locus in my VCF and I'd like to have the CNT number from the COSMIC VCF, after running bcftools annotate as below
bcftools annotate -a ${cosmic}   -c INFO myvcf.gz

I got CNT=2 for one of my entry and CNT=7 for another, whereas there are 2,7,1,2 in the COSMIC vcf.  

This looks to me that they are randomly matched when there exists duplicates in VCFs. 
Is there any other way to control this? Is it possible to aggregate the input VCF, eg. taking the sum of CNT? 

Many thanks, 
Zhihao

**Comment by pd3** [comment]
Hi Zhihao,
sorry for the delay in replying. Unfortunately, this is quite a specific task, not something that could be easily added. Can I offer this work around instead: use `bcftools query -f'%POS %CNT\n'` to output the counts, sum up using an awk one-liner, then fill in back again using `bcftools annotate`?
Petr

**Comment by zd1** [comment]
Thanks Petr. In the end I did resolve this in a hacky way, similar to what you suggested here. So no worries, I don't have this problem anymore. 

Best, 
Zhihao

**Comment by pd3** [comment]
Cool, thanks.
