### ISSUE TITLE
Feature Request: Allow for matching on INFO fields using annotate

### ISSUE THREAD

**Issue by ejgardner-insmed** [samtools/bcftools#2151]
Hello,

Currently, annotate only allows for matching additional fields with the '~' operator for the ID and POS columns. I was wondering if it was possible to allow for matching on additional INFO fields? As an example, I have an annotation that is transcript-specific. Thus a single variant sometimes has two scores, one for the 1st overlapping transcript, the second (or more) for the nth transcript (tsv format):

```
CHROM POS REF ALT SCORE ENST
chr1 10 A T 0.1 ENST1
chr1 10 A T 0.4 ENST2
```

and I have a variant that is annotated to intersect the 1st transcript (vcf format):

```
#CHROM POS ID REF ALT FILTER INFO
chr1 10 . A T . PASS ENST=ENST1
```

Thus, when running a command like (note the '~'):

```
bcftools annotate -o annotated.vcf -a score.tsv.gz -c 'CHROM,POS,REF,ALT,SCORE,~ENST' input.vcf
```

I would expect the annotation to be:

```
chr1 10 . A T . PASS ENST=ENST1;SCORE=0.1
```

I hope this makes sense!

**Comment by awgymer** [comment]
Can this be made to work with a bedfile as the annotation source?
