### ISSUE TITLE
Minor bug with `index -m 0`.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#2153]
My own comment from #2008

> I managed to get both a .csi and a .tbi file that were totally identical except for filename! I think perhaps bcftools is just bugged here, and it is infact already writing tbi (assuiming vcf.gz of course, as tbi wouldn't work on bcf).

I was unable to reproduce this when doing my PR to resolve that issue, but I just reproduced it again by accident and it's more nuanced than I reported before.

`bcftools index -m 0 foo.vcf.gz` writes a tabix index to foo.vcf.gz.csi.  Running `tabix foo.vcf.gz` writes a byte identical index to foo.vcf.gz.tbi.  This is a minor buglet where the index command ought to name the output accordingly.   It's very minor, but something to add to the list.

**Comment by pd3** [comment]
Fixed, thank you
