### ISSUE TITLE
High quality reads determined?

### ISSUE THREAD

**Issue by jalalsiddiqui** [samtools/bcftools#2154]
When I run the variant caller, I get AD= high quality reads supporting a read and DP=raw read coverage.

The code I run is:

bcftools mpileup files/{filename}.bam \
-R ../vcf_ref/Homo_sapiens_assembly38.dbsnp138.common.noalt.vcf \
--fasta-ref ../ref_index/hg38.fasta.gz \
-a FORMAT/AD \
-Ou --threads {} | bcftools call -c -o files{filename}.sort.bam.mpileup.call.common.dbsnp.vcf --threads {}

Is there a cutoff for what is a high quality read and what is not?

Thanks,

Jalal

**Comment by pd3** [comment]
Please check the usage and manual page of the program, there are various quality cutoffs applied. For example, entire reads are not excluded by default (--min-MQ) even when mapping quality is 0. However, there is a cutoff for minimum base quality (--min-BQ).
