### ISSUE TITLE
[W::bcf_calc_ac] Incorrect number of AC fields at Chrxx:xxxxx. (This message is printed only once.)

### ISSUE THREAD

**Issue by leeleeleeaaaaaaaaaalee** [samtools/bcftools#2159]
Hi, 

Thank you for inventing this tool for effective genomic analysis. However, I have encountered some issues on it. I attempted to use bcftools for subsetting 300 samples from my raw vcf, which carries 500 samples. Here is the code trying to reach that purpose: `bcftools view -S "sample_list.txt" "vcf_passed.vcf.gz" | bgzip -c > "vcf_passed_subset.vcf.gz"`. I did receive the result and the subsetted vcf also looks fine, but followed by an error message:`[W::bcf_calc_ac] Incorrect number of AC fields at Chrxx:xxxxx. (This message is printed only once.).`

May I know if it is fine and how I can solve the problem. Thanks!!

**Comment by pd3** [comment]
This is a common problem with VCFs broken in a very specific way, please check the description of this problem and how to fix in the FAQ here http://samtools.github.io/bcftools/howtos/FAQ.html#incorrect-nfields
