### ISSUE TITLE
Erroneous ROH output

### ISSUE THREAD

**Issue by snakesch** [samtools/bcftools#2169]
Dear Petr and team,

I was working on runs of homozygosity of vcfs of a consanguineous family the other day and noticed an error with the tool output.

bcftools version: bcftools 1.19-69-g466ceae-dirty; Using htslib 1.19.1-31-g0cc34b3
Command used: bcftools roh --AF-file /paedyl01/disk1/louisshe/ref/hg38/full_hg38_with_alt/hg38_gnomad40_genome_EAS.no_header.sorted.txt.gz --genetic-map /paedyl01/disk1/louisshe/ref/hg38/full_hg38_with_alt/genetic_map_hg38_chr15.txt NM138A_deletion_split_allelic.g.vcf.gz

I believe there is no problem with the command and related files as the tool did not raise any error. 

ST      NM138A  chr15   23020557        0       99.0
ST      NM138A  chr15   23020646        0       99.0
ST      NM138A  chr15   23022679        0       99.0
ST      NM138A  chr15   23026802        0       99.0
ST      NM138A  chr15   23027416        0       99.0
ST      NM138A  chr15   23027530        0       99.0
ST      NM138A  chr15   23028041        0       99.0
ST      NM138A  chr15   23030213        0       99.0
ST      NM138A  chr15   23032789        0       99.0
ST      NM138A  chr15   23035457        0       99.0
ST      NM138A  chr15   23062386        0       99.0
ST      NM138A  chr15   23065126        0       81.9
ST      NM138A  chr15Number of lines overlapping with --AF-file/processed: 23233/622
Number of lines filtered/no AF/no alt/multiallelic/dup: 0/267/22304/0/40
        23066447        0       65.2

Obviously, there is something wrong with the output as the output and log messages appear to have mixed.

Much appreciated if you could look into this issue. Thanks!

Louis

**Comment by pd3** [comment]
It's just the way unix stdout and stderr are printed on the screen. A random article which explains the concept https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/
