### ISSUE TITLE
bcftools view -S data size vcf

### ISSUE THREAD

**Issue by hitwbt** [samtools/bcftools#2170]
Hi, may I ask why when I use **bcftools view -S 1.txt FAM596.vcf.gz -Oz > NA19919.vcf.gz** command to filter the vcf of NA19919 samples, the output single sample vcf (1.16G) is bigger than the original three sample vcf (1.13G), shouldn't it be equal to one-third of the FAM596.vcf.gz?

**Comment by pd3** [comment]
Possibly, it depends how big are the mandatory columns (CHROM-INFO) compared to the FORMAT fields. Why don't you look in the output file and compare it with the input file? Also it matters if you are comparing uncompressed files or compressed files - compression can wipe out differences when the input is easily compressible (low-entropy).
