### ISSUE TITLE
What is meant by 'but will not attempt to fix PL or other fields'?

### ISSUE THREAD

**Issue by swvanderlaan** [samtools/bcftools#2178]
This is part of a given VCF file.

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##filedate=20240316
##phasing=full
##contig=<ID=chr21>
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated Alternate Allele Frequency">
##INFO=<ID=MAF,Number=1,Type=Float,Description="Estimated Minor Allele Frequency">
##INFO=<ID=AVG_CS,Number=1,Type=Float,Description="Average Call Score">
##INFO=<ID=R2,Number=1,Type=Float,Description="Estimated Imputation Accuracy (R-square)">
##INFO=<ID=ER2,Number=1,Type=Float,Description="Empirical (Leave-One-Out) R-square (available only for genotyped variants)">
##INFO=<ID=IMPUTED,Number=0,Type=Flag,Description="Marker was imputed">
##INFO=<ID=TYPED,Number=0,Type=Flag,Description="Marker was genotyped">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DS,Number=A,Type=Float,Description="Estimated Alternate Allele Dosage : [P(0/1)+2*P(1/1)]">
##FORMAT=<ID=GP,Number=G,Type=Float,Description="Estimated Posterior Probabilities for Genotypes 0/0, 0/1 and 1/1">
##FORMAT=<ID=HDS,Number=.,Type=Float,Description="Estimated Haploid Alternate Allele Dosage">
##mis_pipeline=michigan-imputationserver-1.8.0-beta4
##mis_imputation=minimac-v4.1.6
##mis_phasing=eagle-2.4
##mis_panel=apps@topmed-r3@1.0.0
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT Sample1
chr21 10000086 rs1212015615 C T . . IMPUTED;AF=9.29487e-05;MAF=9.29487e-05;AVG_CS=0.999907;R2=0.144921 GT:HDS:GP:DS 0|0:0,0:1,0,0:0
chr21 10000373 . C T . . IMPUTED;AF=1.28205e-06;MAF=1.28205e-06;AVG_CS=0.999999;R2=0.00199872 GT:HDS:GP:DS 0|0:0,0:1,0,0:0
chr21 10000658 rs1371342363 T C . . IMPUTED;AF=1.92308e-06;MAF=1.92308e-06;AVG_CS=0.999998;R2=0.00299808 GT:HDS:GP:DS 0|0:0,0:1,0,0:0
chr21 10000752 . T C . . IMPUTED;AF=0.000458333;MAF=0.000458333;AVG_CS=0.999542;R2=0.178302 GT:HDS:GP:DS 0|0:0,0:1,0,0:0
```

I want to sort, index, and normalize my VCF files to make sure all alleles are matching the reference (b38) and any multi-allelic is split in bi-allelics, and all SNPIDs are of the form chr:bp:ref:alt. So my command is:

```
{bcftools} sort "{input_file}" -Oz -o  "{sorted_input_file}" 
{bcftools} index -t "{sorted_input_file}" 

{bcftools} view "{sorted_input_file}" | \\
    {bcftools} norm -m-any --check-ref wx -f {reference_data} | \\
        {bcftools} annotate --set-id '%CHROM:%POS:%REF:%ALT' | \\
            {bcftools} norm --rm-dup both | \\
                {bcftools} +fill-tags -Oz > "{output_file}"
{tabix} -f -p vcf "{output_file}"
```

I am struggling with the interpretation of the manual under `--check-ref` and therefore what to do.

> what to do when incorrect or missing REF allele is encountered: exit (e), warn (w), exclude (x), or set/fix (s) bad sites. The w option can be combined with x and s. Note that s can swap alleles and will update genotypes (GT) and AC counts, but will not attempt to fix PL or other fields.

My questions:

1. What do you mean with '_but will not attempt to fix PL or other fields._'? When I apply it to the above VCF file, will it only change `GT` and not `HDS:GP:DS` or anything else in the `INFO` column? 
2. Presumably it will correctly note the `REF` and `ALT` alleles? 
3. And with `--check-ref w` it will only warn me, but do nothing? 
4. What do people usually do when dealing with ±6000-10000 variants that are flagged with `--check-ref w` per >1+ million variants per chromosome? I am inclined to do `--check-ref wx` and forget about those variants, but open to suggestions and guidance. 

Thanks!

**Comment by pd3** [comment]
1. Say the REF and ALT allele are swapped in your VCF and the program swaps them back. Should the corresponding values for allele counts, genotype likelihoods etc change as well? The program will do no such thing
2. Perhaps. It depends what is the reason for the REF mismatches in the first place
3. In the warning mode it will not modify REF
4. Throw away the VCF unless you really understand what you are working with, there should be no mismatching REF alleles unless something went wrong in the upstream processing! There is the plugin `+fixref` but use that at your own risk https://samtools.github.io/bcftools/howtos/plugin.fixref.html
