### ISSUE TITLE
Number of missing genotypes in bcftools stats

### ISSUE THREAD

**Issue by mufernando** [samtools/bcftools#2183]
Hi,

How does `bcftools stat` compute number of missing genotypes per sample when presented with a "GATK" VCF (which encodes missingness in the DP field)?

Thanks,

Murillo

**Comment by pd3** [comment]
I am guessing your question is related to the bizarre GATK decision discussed also here https://github.com/samtools/hts-specs/issues/756?

Missing genotypes are recognized by GT=. or GT=./., not by the DP or any other field. The assertion made in GT can come from various experiments where DP may not even be defined. 

Note there are the `-i/-e` filtering options and the `+setGT` plugin (http://samtools.github.io/bcftools/howtos/plugin.setGT.html) which can be used to control which genotypes should be counted.
