### ISSUE TITLE
Apart from the header, bcftools mpileup did not output any other content

### ISSUE THREAD

**Issue by dongaoqian** [samtools/bcftools#2189]
Hello, I encountered an issue while using bcftools. 
The problem is that when I use bcftools mpileup, the output file only contains a header starting with '#', but no other content.
 I have referred to issues #1336 and #2069, checked my BAM file, and tried removing the -v option, but none of these solutions have resolved my problem. Here is the command I am using:
`/share/home/stu_dongaoqian/miniconda3/envs/GAEP/bin/bcftools mpileup -r Chr10A -a SP -f ../genome.fa var_calling_output.markdup.bam | /share/home/stu_dongaoqian/miniconda3/envs/GAEP/bin/bcftools call -m -f GQ -o var_calling_output.Chr10A.vcf`
My bcftools version is 1.9. 
The content of my output file is as follows (with some chromosomes and contigs omitted in the middle):
![image](https://github.com/samtools/bcftools/assets/145655565/a3df24aa-272b-490c-89d9-277185b8b9f5)
![image](https://github.com/samtools/bcftools/assets/145655565/7ec292d4-099c-406b-9b12-2d9c7f055d60)

Looking forward to your response!

**Comment by dongaoqian** [comment]
The output of checking my BAM file according to #2069 is as follows: (samtools view var_calling_output.markdup.bam Chr10A | less)，sorry, I don't know why I can't upload files. So，I can only display my BAM file in this way.

SRR23891451.193666211   113     Chr10A  1       0       151M    =       60885302        60885301        AAGATATGGTAATCGAATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGAC A<-A<AAAJFAF7FFJAJJJFJFF-JFFJFJJJJJF<JJAFJJJFFAFAJ7FA-AFJJAJJFF-AAAFFJJFJJFFFJFAA-JJJJJFA7JJ<JJFJFAAFF-JAF<<FJJJJJJFJJJJJJFFJJJJJJFJFJAFFJFJFFJJJJFFF-A NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,-60885302,151M,0;Chr10E,-35404132,151M,2;Chr10B,-55594745,151M,3;Chr10C,-57919232,151M,3;Chr10F,-25923861,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5363
SRR23891451.182525645   129     Chr10A  16      0       151M    =       60885317        60885301        AATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAAC AAFFFJJJJJJJJJFJJJJAJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJFJJFJFFJJJ<AAJJJJJJJJJFFJFJFJFJFJFFJJJJ-JJFJJ<FJF-7-FFJFFJFFJJJ<JAJ--F<<<JJFJFFFAFJJFAFF7-<7<AJ7AF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885317,151M,0;Chr10E,+35404147,151M,2;Chr10B,+55594760,151M,3;Chr10F,+25923876,151M,3;Chr10C,+57919247,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5478
SRR23891451.182337362   65      Chr10A  20      0       151M    =       60885321        60885301        TAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTT AAFFFJJJJJJJJJJJJFJJJJFJJJJJJAJJJJJJJJJJJJJFJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJFF7FAJJJAFJJFJJJFJJJFJJJJFJFJ7F<AJF7<FJFFJJJ<<FAJAA<AJJFF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885321,151M,0;Chr10E,+35404151,151M,2;Chr10F,+25923880,151M,3;Chr10C,+57919251,151M,3;Chr10B,+55594764,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5828
SRR23891451.464229124   65      Chr10A  31      0       151M    =       60885332        60885301        CAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACAATTCAAATATGTGT AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFJJJJJJJFJ< NM:i:1  MD:Z:137T13     AS:i:146        XS:i:146        XA:Z:Chr10A,+60885332,151M,1;Chr10E,+35404162,151M,3;Chr10B,+55594775,151M,3;Chr10C,+57919262,151M,3;Chr10F,+25923891,151M,3;   MQ:i:0  MC:Z:151M       ms:i:6131
SRR23891451.405480363   129     Chr10A  33      0       151M    =       60885334        60885301        GGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTG AAAFFJJJJJJJFJJJJJJJJJJJJJJJJJJJJAJFFJJJJJJJJAFFJFJJAJFJJFJJJJJJFJJJFJFJFFJJJJJJJJJJJJJJJFFJJJJJAJFJFJFFJF--AJFJJJJJJJJAFJF<FFFJJJJJFAFFA7JFJJJJAA-<-7- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885334,151M,0;Chr10E,+35404164,151M,1;Chr10B,+55594777,151M,2;Chr10C,+57919264,151M,2;Chr10F,+25923893,151M,2;   MQ:i:0  MC:Z:151M       ms:i:5675
SRR23891451.242621486   129     Chr10A  40      0       151M    =       60885341        60885301        ACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAAT AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJFJJJFJJJJJJJJFJFJFJJJFJJJJJJJFJJJJJJJJJJJFJJJJJJJJJJJ<JJFJJJJFFJJJJFJJJJJJJJJAJJFAFFJJFFJFJAJJJA7AAJJJJJ-<A NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885341,151M,0;Chr10E,+35404171,151M,1;Chr10B,+55594784,151M,2;Chr10C,+57919271,151M,2;Chr10F,+25923900,151M,2;   MQ:i:0  MC:Z:151M       ms:i:5929
SRR23891451.323276298   65      Chr10A  78      6       151M    =       78      0       NGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTT #AAFFJJFFFJJJJJJJJJJJJJJJJFJJJJJJFFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJF<JFJJJJJJJJJJJJJJJJJJJJJJJJFJJJJ7A<<FAFJJJJJFFFF-AJ)7AJFJJJJJJJAJF NM:i:1  MD:Z:0T150      AS:i:150        XS:i:145        XA:Z:Chr10B,+55594822,151M,2;Chr10A,+60885379,151M,2;Chr10F,+25923938,151M,3;Chr10C,+57919309,151M,3;Chr10E,+35404209,151M,4;   MQ:i:6  MC:Z:151M       ms:i:5841
SRR23891451.323276298   129     Chr10A  78      6       151M    =       78      0       NGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTT #AAFFJJFFFJJJJJJJJJJJJJJJJFJJJJJJFFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJF<JFJJJJJJJJJJJJJJJJJJJJJJJJFJJJJ7A<<FAFJJJJJFFFF-AJ)7AJFJJJJJJJAJF NM:i:1  MD:Z:0T150      AS:i:150        XS:i:145        XA:Z:Chr10A,+60885379,151M,2;Chr10B,+55594822,151M,2;Chr10C,+57919309,151M,3;Chr10F,+25923938,151M,3;Chr10E,+35404209,151M,4;   MQ:i:6  MC:Z:151M       ms:i:5841
SRR23891451.215624919   113     Chr10A  108     6       151M    =       108     0       GTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTTATAATCTATCCTCAGGATGGAAAGGCCGTT JFJFAFJJFFJAJJFFAJFFJJJ7JFJJFJJJAJFJFFJJAJJJJFJFJJJJJJJJFJJJJJJJJJJJFJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA NM:i:0  MD:Z:151        AS:i:151        XS:i:146        XA:Z:Chr10A,-60885409,151M,1;Chr10B,-55594852,151M,1;Chr10E,-35404239,151M,2;Chr10C,-57919339,151M,3;Chr10F,-25923968,151M,3;   MQ:i:6  MC:Z:151M       ms:i:6017
SRR23891451.215624919   177     Chr10A  108     6       151M    =       108     0       GTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTTATAATCTATCCTCAGGATGGAAAGGCCGTT JFJFAFJJFFJAJJFFAJFFJJJ7JFJJFJJJAJFJFFJJAJJJJFJFJJJJJJJJFJJJJJJJJJJJFJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA NM:i:0  MD:Z:151        AS:i:151        XS:i:146        XA:Z:Chr10A,-60885409,151M,1;Chr10B,-55594852,151M,1;Chr10E,-35404239,151M,2;Chr10C,-57919339,151M,3;Chr10F,-25923968,151M,3;   MQ:i:6  MC:Z:151M       ms:i:6017
SRR23891451.646642506   65      Chr10A  110     6       151M    =       110     0       CCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTTATAATCTATCCTCAGGATGGAAAGGCCGTTAT AAFFFJJJJJJFJJJJJJJJJFJJJJJJJJJJJJFJJJJJJJJJJJJJJJJFJJJJJJJJJJFJJAJJJFF<JJAAAJFJFJJJJJJJJJJJJJJJJJJJJJJJJFFAJJJJJJ7F7FFJJFFFJFJJFJJJFJJF7AFFJFJAF<FFJJJ NM:i:0  MD:Z:151        AS:i:151        XS:i:146        XA:Z:Chr10B,+55594854,151M,1;Chr10A,+60885411,151M,1;Chr10E,+35404241,151M,2;Chr10F,+25923970,151M,3;Chr10C,+57919341,151M,3;   MQ:i:6  MC:Z:151M       ms:i:5905
SRR23891451.646642506   129     Chr10A  110     6       151M    =       110     0       CCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTTATAATCTATCCTCAGGATGGAAAGGCCGTTAT AAFFFJJJJJJFJJJJJJJJJFJJJJJJJJJJJJFJJJJJJJJJJJJJJJJFJJJJJJJJJJFJJAJJJFF<JJAAAJFJFJJJJJJJJJJJJJJJJJJJJJJJJFFAJJJJJJ7F7FFJJFFFJFJJFJJJFJJF7AFFJFJAF<FFJJJ NM:i:0  MD:Z:151        AS:i:151        XS:i:146        XA:Z:Chr10A,+60885411,151M,1;Chr10B,+55594854,151M,1;Chr10E,+35404241,151M,2;Chr10F,+25923970,151M,3;Chr10C,+57919341,151M,3;   MQ:i:6  MC:Z:151M       ms:i:5905
SRR23891451.509986442   113     Chr10A  132     8       151M    =       132     0       ATAGCAACTGAGATCATGACTTGTCATATTTGAACATTTCAAATATGTGTTGTGTGAATGGTGCAGGCCGGGCATCATGGGCCACTGGATGTGCTTTATAATCTATCCTCAGGATGGAAAGGCCGTTATATTTGACTCCTTGCGGGACATC -7--F7-<<JJJFFFFAA7JJFFFA-FJ<A-FAAF<JJJJJJ<7JJJJJJFAAJJJJFJJJFFJJF-FJJJJJFJFFJAFAJJJJJJ<JFJJFJJJJJJFFJFFFFJJFJFJJJFJJJJJJF<-JJJJJJJJJJJJJJJJJJJJFFFFAAA NM:i:1  MD:Z:150A0      AS:i:150        XS:i:145        XA:Z:Chr10A,-60885433,151M,2;Chr10B,-55594876,151M,3;Chr10E,-35404263,151M,3;Chr10F,-25923992,141M10S,3;Chr10C,-57919363,141M10S,3;     MQ:i:8  MC:Z:151M       ms:i:5424

**Comment by dongaoqian** [comment]
I'm sorry, I don't know why I can't upload picture. I can only display my BAM file in this way.
The output of checking my BAM file according to #2069 is as follows: (samtools view var_calling_output.markdup.bam Chr10A | less)

SRR23891451.193666211   113     Chr10A  1       0       151M    =       60885302        60885301        AAGATATGGTAATCGAATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGAC A<-A<AAAJFAF7FFJAJJJFJFF-JFFJFJJJJJF<JJAFJJJFFAFAJ7FA-AFJJAJJFF-AAAFFJJFJJFFFJFAA-JJJJJFA7JJ<JJFJFAAFF-JAF<<FJJJJJJFJJJJJJFFJJJJJJFJFJAFFJFJFFJJJJFFF-A NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,-60885302,151M,0;Chr10E,-35404132,151M,2;Chr10B,-55594745,151M,3;Chr10C,-57919232,151M,3;Chr10F,-25923861,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5363
SRR23891451.182525645   129     Chr10A  16      0       151M    =       60885317        60885301        AATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAAC AAFFFJJJJJJJJJFJJJJAJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJFJJFJFFJJJ<AAJJJJJJJJJFFJFJFJFJFJFFJJJJ-JJFJJ<FJF-7-FFJFFJFFJJJ<JAJ--F<<<JJFJFFFAFJJFAFF7-<7<AJ7AF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885317,151M,0;Chr10E,+35404147,151M,2;Chr10B,+55594760,151M,3;Chr10F,+25923876,151M,3;Chr10C,+57919247,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5478
SRR23891451.182337362   65      Chr10A  20      0       151M    =       60885321        60885301        TAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTT AAFFFJJJJJJJJJJJJFJJJJFJJJJJJAJJJJJJJJJJJJJFJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJFF7FAJJJAFJJFJJJFJJJFJJJJFJFJ7F<AJF7<FJFFJJJ<<FAJAA<AJJFF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885321,151M,0;Chr10E,+35404151,151M,2;Chr10F,+25923880,151M,3;Chr10C,+57919251,151M,3;Chr10B,+55594764,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5828

**Comment by dongaoqian** [comment]
I'm sorry, I don't know why I can't upload picture. I can only display my BAM file in this way.
The output of checking my BAM file according to #2069 is as follows: (samtools view var_calling_output.markdup.bam Chr10A | less)

SRR23891451.193666211   113     Chr10A  1       0       151M    =       60885302        60885301        AAGATATGGTAATCGAATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGAC A<-A<AAAJFAF7FFJAJJJFJFF-JFFJFJJJJJF<JJAFJJJFFAFAJ7FA-AFJJAJJFF-AAAFFJJFJJFFFJFAA-JJJJJFA7JJ<JJFJFAAFF-JAF<<FJJJJJJFJJJJJJFFJJJJJJFJFJAFFJFJFFJJJJFFF-A NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,-60885302,151M,0;Chr10E,-35404132,151M,2;Chr10B,-55594745,151M,3;Chr10C,-57919232,151M,3;Chr10F,-25923861,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5363
SRR23891451.182525645   129     Chr10A  16      0       151M    =       60885317        60885301        AATATAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAAC AAFFFJJJJJJJJJFJJJJAJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJFJJFJFFJJJ<AAJJJJJJJJJFFJFJFJFJFJFFJJJJ-JJFJJ<FJF-7-FFJFFJFFJJJ<JAJ--F<<<JJFJFFFAFJJFAFF7-<7<AJ7AF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885317,151M,0;Chr10E,+35404147,151M,2;Chr10B,+55594760,151M,3;Chr10F,+25923876,151M,3;Chr10C,+57919247,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5478
SRR23891451.182337362   65      Chr10A  20      0       151M    =       60885321        60885301        TAAGTTTTGAGCAGGAATGTACATATATGAGGCCATGATGAAGATCCGGGAAAATGGGTGTCTCATGGCCGCCCACCAGTTTTGGTAAGTCCCAAAGATACTTGGAACATATATAGCAACTGAGATCATGACTTGTCATATTTGAACATTT AAFFFJJJJJJJJJJJJFJJJJFJJJJJJAJJJJJJJJJJJJJFJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJFF7FAJJJAFJJFJJJFJJJFJJJJFJFJ7F<AJF7<FJFFJJJ<<FAJAA<AJJFF- NM:i:0  MD:Z:151        AS:i:151        XS:i:151        XA:Z:Chr10A,+60885321,151M,0;Chr10E,+35404151,151M,2;Chr10F,+25923880,151M,3;Chr10C,+57919251,151M,3;Chr10B,+55594764,151M,3;   MQ:i:0  MC:Z:151M       ms:i:5828

**Comment by pd3** [comment]
This requires a test case to reproduce and debug the problem. This script can be used to create a small slice of the bam and the reference https://github.com/pd3/mpileup-tests/blob/main/misc/create-bam-test

**Comment by dongaoqian** [comment]
Thank you for your reply. This is a small portion of the BAM file I extracted using this script.
[slice.tar.gz](https://github.com/samtools/bcftools/files/15447275/slice.tar.gz)

**Comment by pd3** [comment]
Thank you for the test case. The cause of the problem is that all reads are silently filtered because they have the PAIRED flag set, but not PROPER_PAIR. The program has the option to work with these anyway
```
-A, --count-orphans     Include anomalous read pairs, i.e. with flag PAIRED but not PROPER_PAIR
```
I just pushed a commit which clarifies what anomalous read pairs are, as this was not described anywhere.

Hopefully this resolves the problem!

**Comment by dongaoqian** [comment]
Thank you for your help,It has indeed solved my problem!
