### ISSUE TITLE
Clarification on -e 0 flag and interpretation of discordance with PL-vs-PL and GT-vs-GT

### ISSUE THREAD

**Issue by goeckeritz** [samtools/bcftools#2194]
Hi Petr, 

I know you are probably sick of the amount of questions you get about this.. but I was hoping you might be able to clarify something for me. 

Does setting -e 0 still give discordance as the number of mismatches when the tag comparison is PL-vs-PL? Or is this the case only when the tag comparison is GT-vs-GT? I only ask because on the actual documentation for v1.18 mentions it's GT-vs-GT only, but in a few issues (#1500, #1538, #1556) where you say to use -e 0, you don't mention the GT-vs-GT caveat (although, #1538 does mention there is no PL flag, so maybe you found it unnecessary to mention it?). Not sure what comparison #1500 is using, but maybe GT-vs-GT as well?

Nevertheless there must be some differences... I'm using bcftools v 1.18, and ran the same command on the same files except for adding -u GT,GT for one run. 

Here's the output for the command NOT specifying -u GT,GT:
```
# This file was produced by bcftools (1.18+htslib-1.18), the command line was:
# 	 bcftools gtcheck  -e 0 --pairs-file MMaryPotter_588983_pairs.txt MMaryPotter_588983_normalized.vcf.gz
# and the working directory was:
# 	 /cluster/home/cgoeckeritz/bwa/moms/vcfs
#
INFO	Time required to process one record .. 0.000012 seconds
INFO	sites-compared	4668035
INFO	sites-skipped-no-match	0
INFO	sites-skipped-multiallelic	0
INFO	sites-skipped-monoallelic	95700933
INFO	sites-skipped-no-data	0
INFO	sites-skipped-GT-not-diploid	0
INFO	sites-skipped-PL-not-diploid	0
INFO	sites-used-PL-vs-PL	4668035
INFO	sites-used-PL-vs-GT	0
INFO	sites-used-GT-vs-PL	0
INFO	sites-used-GT-vs-GT	0
# DC, discordance:
#     - query sample
#     - genotyped sample
#     - discordance (either an abstract score or number of mismatches, see -e/-u in the man page for details; smaller is better)
#     - negative log of HWE probability at matching sites (rare genotypes matches are more informative, bigger is better)
#     - number of sites compared (bigger is better)
#DC	[2]Query Sample	[3]Genotyped Sample	[4]Discordance	[5]-log P(HWE)	[6]Number of sites compared
DC	MMaryPotter_588983	MMaryPotter_588983_e10	73101	8.157442e+05	418011
DC	MMaryPotter_588983	MMaryPotter_588983_e11	22664	3.052378e+05	176404
DC	MMaryPotter_588983	MMaryPotter_588983_e12	45417	4.417438e+05	253187
DC	MMaryPotter_588983	MMaryPotter_588983_e13	23776	3.859070e+05	212432
DC	MMaryPotter_588983	MMaryPotter_588983_e14	24004	3.412114e+05	188169
DC	MMaryPotter_588983	MMaryPotter_588983_e15	9440	1.432794e+05	83224
```

Here's the output for the command SPECIFYING -u GT,GT:
```
# This file was produced by bcftools (1.18+htslib-1.18), the command line was:
# 	 bcftools gtcheck  -e 0 -u GT,GT --pairs-file MMaryPotter_588983_pairs.txt MMaryPotter_588983_normalized.vcf.gz
# and the working directory was:
# 	 /cluster/home/cgoeckeritz/bwa/moms/vcfs
#
INFO	Time required to process one record .. 0.000014 seconds
INFO	sites-compared	4668035
INFO	sites-skipped-no-match	0
INFO	sites-skipped-multiallelic	0
INFO	sites-skipped-monoallelic	95700933
INFO	sites-skipped-no-data	0
INFO	sites-skipped-GT-not-diploid	0
INFO	sites-skipped-PL-not-diploid	0
INFO	sites-used-PL-vs-PL	0
INFO	sites-used-PL-vs-GT	0
INFO	sites-used-GT-vs-PL	0
INFO	sites-used-GT-vs-GT	4668035
# DC, discordance:
#     - query sample
#     - genotyped sample
#     - discordance (either an abstract score or number of mismatches, see -e/-u in the man page for details; smaller is better)
#     - negative log of HWE probability at matching sites (rare genotypes matches are more informative, bigger is better)
#     - number of sites compared (bigger is better)
#DC	[2]Query Sample	[3]Genotyped Sample	[4]Discordance	[5]-log P(HWE)	[6]Number of sites compared
DC	MMaryPotter_588983	MMaryPotter_588983_e10	268029	2.178834e+06	863343
DC	MMaryPotter_588983	MMaryPotter_588983_e11	97082	9.452473e+05	364457
DC	MMaryPotter_588983	MMaryPotter_588983_e12	165365	1.313656e+06	527507
DC	MMaryPotter_588983	MMaryPotter_588983_e13	160542	1.293031e+06	512678
DC	MMaryPotter_588983	MMaryPotter_588983_e14	115485	9.736051e+05	390567
DC	MMaryPotter_588983	MMaryPotter_588983_e15	59720	4.560722e+05	188022
```

I just can't seem to wrap my head around how I have the same number of sites compared noted after INFO for each run, but then suddenly have different [6]Numbers of sites compared in the actual output below.

Could you help me understand what is happening here? REALLY appreciate your time. Been scratching my head for some time now.

Kindly,
Charity

**Comment by pd3** [comment]
Only with GT-vs-GT one gets the actual number of mismatches in that version. However, this has been reworked and in the latest version the DC output was replaced with DCv2. The new version prints the number of matching genotypes always, regardless of the GT vs PL tag combination or if `-e 0` is given or not.  I hope this helps!

**Comment by goeckeritz** [comment]
It does, thanks Petr!

**Comment by pd3** [comment]
@goeckeritz It turns out there was a bug in the latest code, the number of matching genotypes was not caclulated properly with PL. This should be fixed in https://github.com/samtools/bcftools/commit/ed09a821d5224ce41429639e1c308f5c7337f857
