### ISSUE TITLE
Renaming .vcf.gz file using mv command and now bcftools won't recognise

### ISSUE THREAD

**Issue by kiran-lee** [samtools/bcftools#2197]
I renamed a .vcf.gz file using the mv command. Now bcftools "Failed to read from x.vcf.gz: unknown file type".
How can I rectify this?

**Comment by pd3** [comment]
The program does not care about the file names, so likely the problem is something else. Use other standard unix commands to verify what is inside the file, eg
```
$ ls -l x.vcf.gz
$ zless x.vcf.gz
```
