### ISSUE TITLE
Undefined header [W::vcf_parse] INFO 'PR' is not defined in the header, assuming Type=String

### ISSUE THREAD

**Issue by aainaGit** [samtools/bcftools#2198]
I am trying to rename chromosomes in a vcf file I received from Dartseq but I keep getting the below error. How do I fix this 

unix command line code- bcftools annotate --rename-chrs chromosomes.txt bimbo312.vcf.gz -Oz -o renamebimbo312.vcf.gz

Error- [W::vcf_parse] INFO 'PR' is not defined in the header, assuming Type=String

When i zcat the vcf file, I see the following   PR;DP=0	GT:AD:DP:GQ:PL

**Comment by pd3** [comment]
You need to update the VCF header, please see the question answered here http://samtools.github.io/bcftools/howtos/FAQ.html#undefined-tag
