### ISSUE TITLE
bcftools concat --allow-overlaps produces output VCF with contigs out of order

### ISSUE THREAD

**Issue by TedBrookings** [samtools/bcftools#2200]
When concatenating two VCFs where one has no variants on a contig, that contig can get pushed to the end of the file. e.g.
```
header="##fileformat=VCFv4.2\n##contig=<ID=chr1,length=1000>\n##contig=<ID=chr2,length=1000>\n##contig=<ID=chr3,length=1000>\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "$header\nchr1\t1\t.\tA\tC\t.\t.\t.\nchr3\t1\t.\tG\tT\t.\t.\t." \
    | bcftools view --write-index=tbi -o vcf1.vcf.gz
echo -e "$header\nchr2\t1\t.\tG\tT\t.\t.\t." \
    | bcftools view --write-index=tbi -o vcf2.vcf.gz

bcftools concat -a vcf1.vcf.gz vcf2.vcf.gz
```
output:
```
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=1000>
##contig=<ID=chr2,length=1000>
##contig=<ID=chr3,length=1000>
##bcftools_viewVersion=1.20+htslib-1.20
##bcftools_viewCommand=view --write-index=tbi -o vcf1.vcf.gz; Date=Thu May 30 13:48:45 2024
##bcftools_concatVersion=1.20+htslib-1.20
##bcftools_concatCommand=concat -a vcf1.vcf.gz vcf2.vcf.gz; Date=Thu May 30 13:48:45 2024
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    1       .       A       C       .       .       .
chr3    1       .       G       T       .       .       .
chr2    1       .       G       T       .       .       .
```

**Comment by pd3** [comment]
That is not a bug and should never be a problem. The chromosomes can appear in arbitrary order in the input files, the program uses the order encountered in the first file.

**Comment by nh13** [comment]
@pd3 the order on the input files are `chr1`, `chr2`, and `chr3` in both inputs (in the header), so with the `--allow-overlaps` option, shouldn't the output also be that order?  Or perhaps I am misunderstanding what the `--allow-overlaps` does in this case?

Alternatively, is there a `bcftools` tool that merges multiple sorted VCFs from the same sample (without re-sorting)?

**Comment by pd3** [comment]
The order of chromosomes in the body is not guaranteed and can be different from the order of chromosomes listed in the header. What matters are the data lines. The option `--allow-overlaps` aims to solve a different problem: normally one concatenates disjoint chromosome blocks; Sometimes, however, one wishes to join overlapping blocks.  

In your example, when the reader encounters chr1 and chr3 in the first file, it cannot know if chr2 will follow or not, therefore it outputs chr3 first. Technically it is possible to make the program smarter, it could use the index to enforce the header order throughout the body. However, I am not convinced it would bring anything useful. The VCF specification does not guarantee the ordering, so it's just aesthetics. What is the motivation for your inquiry?

**Comment by TedBrookings** [comment]
In our motivating case we're concatenating a SNP VCF into an INDEL VCF (a situation listed in the documentation). Both of the input VCFs are sorted (contig name and position), and a downstream tool (not a bcftools tool) threw an exception because the output is not sorted. This is a pretty common set of operations. I think that at a minimum the documentation should be updated to explicitly indicate that `--allow-overlaps` will not guarantee that the contig names are sorted, although I would also think it would be preferable if the tool did maintain the sorting.

**Comment by pd3** [comment]
I am afraid this is a problem of the downstream tool. It should not insist on chromosomes being in a specific order, the VCF specification does not mandate that.
