### ISSUE TITLE
How to count number of haplotypes and haplotype frequency from phased vcf files?

### ISSUE THREAD

**Issue by Arline13** [samtools/bcftools#2201]
Hello,

I'm pretty new in bioinformatic analysis

I have a phased vcf files that I create with beagle tools in linux and now I want to count number of uniq haplotypes and frequency of haplotypes from my phased vcf files

I tried to find script using whatshap tools, bcftools, beagle but I can't find tutorial

Can someone help me for this?

Thanks in advance

Arline

**Comment by pd3** [comment]
We don't have a function to do that. To be honest, I am not even sure what kind of metric to use, ie when can be two overlapping haplotypes considered identical. It sounds like the PBWT algorithm developed by Richard Durbin might be a good place to start.
