### ISSUE TITLE
Ability to skip nonvariant records within a trio for mendelian2 plugin

### ISSUE THREAD

**Issue by ASLeonard** [samtools/bcftools#2204]
I was collecting some mendelian error rate stats on a multi-sample VCF containing fairly diverged trios. One "issue" I noticed was that many trios would have homozygous-reference genotypes for all three members of **that** trio. Since the samples could be fairly diverged, sometimes up to half of the "ngood" variants are these technically mendelian-consistent but otherwise incredibly boring records. 

I tried adding a flag and if statement to skip any variants where there was no variation within **that** trio, and that seemed to work, placing this 

```
if ( args->filter_reference && mom==1 && dad==1 && kid1==1 && kid2==1) continue;
```

right before 

https://github.com/samtools/bcftools/blob/f313599887a647df4b35b0799cb154c050c722c4/plugins/mendelian2.c#L651

The current behaviour is perhaps the most valid, but not necessarily the most useful for some purposes, so curious for additional thoughts.

Best,
Alex

**Comment by pd3** [comment]
Yes, this is a good idea. I am adding this as a separate counter `ngood_alt`.
