### ISSUE TITLE
[Solved] bcftools merge Failed to open *vcf.gz: could not load index

### ISSUE THREAD

**Issue by DLCrawford** [samtools/bcftools#2205]
Error: with bcftools merge, "could not load index"
This is an old issue that had a mixture of solutions.  
The simplest solution that worked for me was
  BGZIP > new directory
 bgzip file.vcf > merge/file.vcf
 In a merge directory with bgzip *.vcf.gz files
REMOVE bgzip index *.gzi
Remove *.vcf.gz.gzi, which was created by bpzip.
 
INDEX
bcftools index -t *.vcf.gz

  MERGE
bcftools merge 1.vcf.gz 2.vcf.gz 3.vcf.gz -Oz -o 1_2_3_merged_vcf.gz

**Comment by pd3** [comment]
Thank you
