### ISSUE TITLE
Possible isec memory leak

### ISSUE THREAD

**Issue by sandra-selfdecode** [samtools/bcftools#2206]
Hello, I think `bcftools isec` might have a memory leak. I ran a script 3 times today that was having an error in the step after I ran `isec`, and even though it was the same command with the same files in the same docker container running on the same instance type, the memory profile was very different across runs.

The command was `bcftools isec -c none -w1 -Oz /app/input.bcf /app/ref_variants.bcf -p /app/isec --threads $THREADS`
The below image shows the cpu and memory profiles for the 3 runs. I included the cpu so you can see the matching cpu profiles, and how the memory profiles are very different. That script was the only thing running so I'm not sure why they were so different.

![image](https://github.com/samtools/bcftools/assets/87330552/d99cc760-85a2-4f82-ab30-0ddda9bf7ed9)

**Comment by pd3** [comment]
Thank you for the issue. The indirect evidence is likely to have a different explanation. You can test with valgrind, for example, to make sure (`valgrind bcftools isec ...`). In any case, we'd need a small test case to reproduce the leak, or the output from valgrind at least. Also, please make sure you are using the latest version of bcftools to rule out known bugs that have been already fixed.
