### ISSUE TITLE
Speeding up bcftools merge for large number of vcf files with identical variant records containing sample genotypes.

### ISSUE THREAD

**Issue by rajwanir** [samtools/bcftools#2207]
Hello,

I am trying to merge a large number of vcf files (~96,000) that contain genotypes for different samples in each file. Each file contain genotypes at identical variant set (~770,000).

Executing a simple merge (command below) takes > 48 hours. 

`ls *.vcf.gz | bcftools merge -m none --file-list -  --output $output_vcf --output-type z 
`
I understand I could use the `--threads` option to speed the compression. Is that all? To give a bit of context, these vcfs are coming from array genotyping and not sequencing. The variants in each file is identical. The info fields aren't very informative. All I am looking for writing that common variant set along with genotypes for all the samples. Is bcftools overkill for this since it might be doing alot more to ensure variants are correct before merging and also computing the info fields?

Any suggestions or advice greatly appreciated. Thank you.

**Comment by pd3** [comment]
If all files have identical variants and performance is an issue, writing a custom script or program should indeed be faster for this simple task. I am afraid that within bcftools there is no other way to speed things up. And yes, threads only helps with de/compression.
