### ISSUE TITLE
CSQ annotation - should be frameshift

### ISSUE THREAD

**Issue by JakeHagen** [samtools/bcftools#2212]
Hello

I annotated this variant chr7-74711106-CAAG-CT with bcftools csq v1.20. For all transcripts it is giving me `inframe_deletion&splice_region` as the consequence. I think this should be a frameshift variant. Is there something I am not understanding, or could this be a bug?

Thank you
Jake

**Comment by pd3** [comment]
At a cursory glance yes, however it really depends on the sequence context and the gene model. More information is needed to debug this. Can you share a small test case to reproduce the problem please? It can be created for example like this
```
/path/to/bcftools-dir/test/csq/make-csq-test -f ref.fa -g genes.gff -o test -p  74711106-CAAG-CT -t TRANSCRIPT_ID
```

**Comment by JakeHagen** [comment]
Thank you for looking at this. Attached is the test case created with the command
```
../bcftools-1.20/test/csq/make-csq-test -f ./genome.hg38rg.fa -g ./ensembl/Homo_sapiens.GRCh38.112.gff3.gz -o test -p 74711106-CAAG-CT -t ENST00000573035
```

[bcftools_csq_test_7-74711106-CAAG-CT.tar.gz](https://github.com/user-attachments/files/15914834/bcftools_csq_test_7-74711106-CAAG-CT.tar.gz)

**Comment by pd3** [comment]
Thank you for the test case. I can confirm this was a bug, and it should be fixed now by https://github.com/samtools/bcftools/commit/a05480ccc32a4ab5dd9b7a732040f9f9f5742a24, please try it out

**Comment by JakeHagen** [comment]
Yep it is now being reported as `frameshift&splice_region` 
Thank you
