### ISSUE TITLE
snp number issue

### ISSUE THREAD

**Issue by fan040** [samtools/bcftools#2221]
Hello, I used the bcftools stats command to make statistics on the vcf file and found that the number of SNPS in two locations was inconsistent, I would like to ask the reason.

![image](https://github.com/samtools/bcftools/assets/166574153/df8b0c22-71da-4a1d-9605-f15eaabe2194)
![image](https://github.com/samtools/bcftools/assets/166574153/ae979300-95ea-4c3e-a700-6841ead8579e)

**Comment by pd3** [comment]
It's because of multiallelic sites. Substitution types can be incremented multiple times at the same site, but will be counted only once as a SNP site.

Try
```
(echo "##fileformat=VCFv4.2"; 
 echo "##contig=<ID=chr1>"; 
 echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"; echo -e "chr1\t10000\tx\tA\tC,T\t.\t.\t.") |
 bcftools stats
```
