### ISSUE TITLE
bcftools convert --tag bug

### ISSUE THREAD

**Issue by Banthandor** [samtools/bcftools#2222]
when I use bcftools convert --threads 72 -g outfile --3N6 --tag PL infile, the outputted fields are not in PHRED scale but float.
It seems the --tag option is overridden and it output genotype probabilities no matter what.

Many thanks in advance.

Cheers,
Sam

**Comment by pd3** [comment]
The option `--tag` controls the input values. On output are always output genotype probabilities as floats, which is what IMPUTE2 would consume. This works as intended.
