### ISSUE TITLE
how to use plot-roh.py to draw the plot by using the "bcftools roh" output

### ISSUE THREAD

**Issue by lxwgcool** [samtools/bcftools#2223]
Hi, 

I am trying to plot the results by using the tool "run-roh.pl" and the raw output from "bcftools roh". 

I got the error below:
```
No GT lines found in input file. Was it generated using the run-roh.pl script?
This script is unable to process the raw output of "bcftools roh",
the output of the following query may need to be added to the roh result.

bcftools query -f'GT\t%CHROM\t%POS[\t%SAMPLE\t%GT]\n' in.bcf
```

My input did come from "bcftools roh" (The original vcf did not come with the "GT" in caption field).  May I know how to convert the raw output from "bcftools roh" to make it be usable by "run-roh.pl"  for visualization? 

Thanks
Xin

**Comment by pd3** [comment]
The error message suggests that the output of the command shown above must be added to the raw `bcftools roh` ouput, in order for the visualization to work. The script https://github.com/samtools/bcftools/blob/develop/misc/run-roh.pl  would run the exact same command. You can add for example like this:
```
bcftools query -f'GT\t%CHROM\t%POS[\t%SAMPLE\t%GT]\n' in.bcf >> raw-bcftools-roh-output.txt
```
