### ISSUE TITLE
bcftools call only sometimes outputs the `INFO/HWE` and `INFO/G3` fields

### ISSUE THREAD

**Issue by hjeremyli** [samtools/bcftools#2226]
Hi, I'm running a bcftools mpileup + call pipeline on a set of low coverage samples and am noticing that only a subset of the emitted VCF records have the `INFO/HWE` and `INFO/G3` fields:

The command being run: 

```
$ bcftools mpileup -d 10000000 -f ../refgenome/genome.fasta.gz testmerge.bam -q 30 -Q 30 --skip-any-set DUP,QCFAIL,UNMAP  -Oz -I --threads 8  -a AD,DP -Ou | bcftools call -v -c -Oz -o testcall.vcf.gz
```

And an example of two output records; the former with the HWE and G3 flags, and the latter without 

```
1       55505266        .       G       T       999     .       DP=164559;VDB=0.457631;SGB=1501.41;RPBZ=1.32084;MQBZ=0.0139371;MQSBZ=-0.245266;BQBZ=-0.864272;SCBZ=-0.117168;MQ0F=0;AF1=0.014047;G3=0.972737,0.0255304,0.00173303;HWE=0.0145177;AC1=187;DP4=143636,10619,795,127;MQ=60;FQ=999;PV4=2.16846e-13,0.457974,1,1
1       55505333        .       G       A       999     .       DP=282816;VDB=0.0421741;SGB=-1302.55;RPBZ=1.26729;MQBZ=0.00253936;MQSBZ=0;BQBZ=0.413382;SCBZ=-0.0525597;MQ0F=0;AF1=0.000141429;AC1=2;DP4=256257,14104,78,7;MQ=60;FQ=999;PV4=0.215042,1,1,1
```

For my purposes, I would like to obtain HWE p values as well as the ML genotype frequencies for all called sites -- is there a way to do this?

**Comment by hjeremyli** [comment]
Hi @pd3 , do you have an idea of what's going on here?

**Comment by pd3** [comment]
This is done by the following code https://github.com/samtools/bcftools/blob/5e7ea8a09725601ac7bd55ad5a5ecf818ffc6947/ccall.c#L156-L161

The program adds this annotation only when it is possible to calculate the HWE P-value and it is significant. I note this code fragment was not changed since the original implementation.
