### ISSUE TITLE
There could be a mistake in bcftools/mpileup_bench/get_data.sh

### ISSUE THREAD

**Issue by zengxiaofei** [samtools/bcftools#2232]
Dear developers,

Thank you for providing such a useful tool!

I think there could be a mistake in `bcftools/mpileup_bench/get_data.sh`

```bash
echo "Getting PacBio $reg"
samtools view -o pacbio_50x.bam --write-index -@8 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/ChineseTrio/HG005_NA24631_son/NIST_BGIseq_2x150bp_100x/GRCh38/HG005_GRCh38_BGIseq-2x150-100x_NIST_20211126.bam $reg

echo "Getting BGI $reg"
samtools view -o bgi_100x.bam --write-index -@8 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/ChineseTrio/HG005_NA24631_son/PacBio_CCS_15kb_20kb_chemistry2/GRCh38/GIAB_5mC_CpG/HG005.GRCh38.deepvariant.haplotagged.bam $reg
```

According to the URLs, the output file name for the first command should be `bgi_100x.bam`, while the output file name for the second comamnd should be `pacbio_50x.bam`.

I'm not sure whether this will have any impact on the conclusions and parameters on `-X bgi` (https://github.com/samtools/bcftools/pull/2045#issuecomment-1851851530).

Best regards,
Xiaofei

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two months.

**Comment by pd3** [comment]
Was this closed purely for the reason of not being commented on? If the problem persists, please leave this open. It just means we are very busy.

**Comment by zengxiaofei** [comment]
Thanks for your reply!
