### ISSUE TITLE
Manual typo in bcftools call -g 

### ISSUE THREAD

**Issue by michtrofimov** [samtools/bcftools#2233]
-g, --gvcf INT
output also gVCF blocks of homozygous REF calls. The parameter INT is the minimum per-sample depth required to include a site in the non-variant block.

Apparently INT is the maximum per-sample depth threshold. Please check

**Comment by pd3** [comment]
It is really minimum depth per block. However, the documentation is not correct here, it should be the same as for `mpileup --gvcf`
```
*-g, --gvcf* 'INT'[,...]::
    output gVCF blocks of homozygous REF calls, with depth (DP) ranges
    specified by the list of integers. For example, passing '5,15' will
    group sites into two types of gVCF blocks, the first with minimum
    per-sample DP from the interval [5,15) and the latter with minimum
    depth 15 or more. In this example, sites with minimum per-sample
    depth less than 5 will be printed as separate records, outside of
    gVCF blocks.
```
I will push a documentation update shortly

**Comment by pd3** [comment]
Updated: https://github.com/samtools/bcftools/commit/ec9021d7a085429c62eb81b18e6373047065d8cc
