### ISSUE TITLE
Change GVCFBlocks (+gvcfz) and header

### ISSUE THREAD

**Issue by raphaelbetschart** [samtools/bcftools#2238]
Hi, I'm trying to change the band resolution of my gvcf files. I would like to produce blocks with GQ values from 0-1, 1-10, 10-20, and am using this command.
```
bcftools +gvcfz -g 'PASS:GQ>=0 & GQ<1; PASS:GQ>=1 & GQ<10; PASS:GQ>=10 & GQ<20'
```
This seems to work, but the header is not getting updated (still the same entries in `##GVCFBlock`). How can I update the headers with the correct GVCFBlock entries?

**Comment by pd3** [comment]
The `gvcfz` plugin does not care about the `##GVCFBlock` comment lines, those were produced with a different program. If you care about them, you'd have to use `bcftools reheader -h hdr.txt` with manually updated lines.

**Comment by raphaelbetschart** [comment]
Thanks!
