### ISSUE TITLE
setGT plugin bug when filtering with FMT/DHFFC or FMT/DHBFC

### ISSUE THREAD

**Issue by olivia-gc** [samtools/bcftools#2241]
Hello, 

I am trying to set specific genotypes to missing using bcftools +setGT on a multi-sample vcf. I believe there have been similar bugs reported for this plugin. Would it be possible to help fix this? 

Here are examples of my inconsistent results: 
my file looks like this where the first genotype has the alternative allele and the second one is reference:
> DEL_6 . . GT: . . :DHFFC:DHBFC:DHSP 0/1: . . :1.375:1.22222:2    0/0: . . :0.9375:0.833333:0

When I try to filter by DHFFC threshold only on the genotypes with alt, the reference also goes to missing: 
`bcftools +setGT test11del.vcf.gz  -- --target-gt 'q' --new-gt '.' --include 'GT="alt" && DHFFC > 0.7' | bcftools view -H | less -S `
> DEL_6 . . GT: . . :DHFFC:DHBFC:DHSP ./.: . . :1.375:1.22222:2    ./.: . . :0.9375:0.833333:0 

and the opposite is true when I try to apply only to ref genotypes:
`bcftools +setGT test11del.vcf.gz  -- --target-gt 'q' --new-gt '.' --include 'GT="0/0" && DHFFC > 0.7' | bcftools view -H | less -S`
> DEL_6 . . GT: . . :DHFFC:DHBFC:DHSP ./.: . . :1.375:1.22222:2    ./.: . . :0.9375:0.833333:0 

similar problem when using 'exclude' instead of 'include'
`bcftools +setGT test11del.vcf.gz  -- --target-gt 'q' --new-gt '.' --exclude 'GT="0/0" && DHFFC > 0.7' | bcftools view -H | less -S`
> DEL_6 . . GT: . . :DHFFC:DHBFC:DHSP 0/1: . . :1.375:1.22222:2    0/0: . . :0.9375:0.833333:0

`bcftools --version`
> bcftools 1.19
> Using htslib 1.18

Any help is appreciated, 
Thank you!

**Comment by pd3** [comment]
As decribed in the documentation, the program makes a distinction between `&` and `&&`
```
FMT/DP>10  & FMT/GQ>10 .. both conditions must be satisfied within one sample
FMT/DP>10 && FMT/GQ>10 .. the conditions can be satisfied in different samples
```
Have you tried that? I believe it should solve your problem.

http://samtools.github.io/bcftools/bcftools.html#expressions
http://samtools.github.io/bcftools/howtos/filtering.html
