### ISSUE TITLE
Plugin +mendelian2 reports missing samples incorrectly

### ISSUE THREAD

**Issue by allytrope** [samtools/bcftools#2242]
Given a VCF containing samples 101, 102, and 103, the following seems to works:
`bcftools +mendelian2 test.vcf.gz -p 101,102,103`

However, if I run the command instead to include an arbitrary sample for the child not in the VCF like so:
`bcftools +mendelian2 test.vcf.gz -p 0,102,103`, then it actually reports that the mother is missing: `The sample is not present: 103`.

In reverse, if the mother is actually the missing one, it instead reports that the child id is missing.

The missing father does work as expected though,

**Comment by pd3** [comment]
Thank you for reporting the bug, it is fixed now. Note the problem was only the error message, the program was assigning the family members correctly in the calculation

**Comment by allytrope** [comment]
Great! Thanks for fixing it!
