### ISSUE TITLE
`bcftools merge` seg faults on some NIST samples

### ISSUE THREAD

**Issue by rickymagner** [samtools/bcftools#2243]
Hi,

I wanted to use `bcftools merge` to combine some VCFs from NIST. In particular, I took the [HG002](https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/), [HG003](https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG003_NA24149_father/NISTv4.2.1/GRCh38/), and [HG004](https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG004_NA24143_mother/NISTv4.2.1/GRCh38/) truth VCFs from NIST and tried running

```
bcftools merge HG002.vcf.gz HG003.vcf.gz HG004.vcf.gz -o merged.vcf.gz
```

Each time, it would seg fault at the same location (the last written entry is somewhere in the middle of chr1). I tried isolating just that location around a few thousand bases, and the tool ran successfully. I later tried to run the merge on just chr2 variants, and it seg faulted again.

I don't know if the error is the files themselves or the tool, but in any case a more helpful error message at least would be great.

My versions are:
```
> bcftools --version
bcftools 1.18-10-gbe695393
Using htslib 1.17-48-gf4a3b99
Copyright (C) 2023 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pd3** [comment]
Thank you for raising the issue. I just ran with the latest version 1.20 and did not find any issue. Can you please try that? I am unable to reproduce the problem.

**Comment by rickymagner** [comment]
Thanks for getting back to me on this. I upgraded to 1.20 and it worked now, so it must've been fixed in a newer version (or something was wrong with my install). Thanks!
