### ISSUE TITLE
bcftools isec questions

### ISSUE THREAD

**Issue by gevro** [samtools/bcftools#2248]
Hi,
bcftools isec -n default qualifier is not defined. Of these, [+-=~], is the default +, -, =, or ~?

Also, is there documentation defining the output files? i.e. 0000, 0001, etc.

Thanks

**Comment by pd3** [comment]
It depends on the other arguments and inputs. If there are two input files and no other options, the program is run in a Venn-diagram like mode. Otherwise `-n +` mode is used.
