### ISSUE TITLE
bcftools mpileup --indels-cns segfault with long insertion

### ISSUE THREAD

**Issue by kpalin** [samtools/bcftools#2249]
Attached is a sample sam file with two (fake) reads containing 1050bp insertion which segfaults `bcftools mpileup --indels-cns` on version 1.20 (installed from conda). It's a bit of a show stopper since these seqfaults occur every few 10Mbp of human nanopore WGS.

```shell
$ bcftools --version
bcftools 1.20
Using htslib 1.20
Copyright (C) 2024 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ bcftools mpileup   -X ont-sup-1.20 --fasta-ref chm13v2.0_maskedY_rCRS.fa    -Ov  sample.bam  >/dev/null 
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
Segmentation fault (core dumped)
```
[sample_sam.gz](https://github.com/user-attachments/files/16558199/sample_sam.gz)

**Comment by jkbonfield** [comment]
The sample file appears to be empty.  Could you please re-send it.  Thanks

**Comment by kpalin** [comment]
Sorry. Next attempt here: [sample_sam.gz](https://github.com/user-attachments/files/16579496/sample_sam.gz)
