### ISSUE TITLE
bcftools mpileup throws a Segmentation fault error if given an empty vcf file

### ISSUE THREAD

**Issue by stefmldk** [samtools/bcftools#2250]
Dear developers
When bcftools is used with the command:
bcftools mpileup -I -f {reference} -R {vcf_file} {bam_file}
it returns a "Segmentation fault" if the vcf file is empty (not considering the header)

An empty vcf file is not an unlikely scenario if bcftools is used in a pipeline - for instance if the vcf file represents variants in the Y-chromosome and we are dealing with a female. It would therefore be better if bcftools simply produced zero output but without throwing an error.

Thank you for your hard work!

**Comment by pd3** [comment]
Thank you for the issue, this is now fixed
