### ISSUE TITLE
target file required for bcftools roh analysis

### ISSUE THREAD

**Issue by vivekruhelaIIITD** [samtools/bcftools#2259]
Hello,

I am running the bcftools roh analysis using the following command:

` bcftools roh --AF-file AF.txt -o bcftools_roh.txt -G30 input.vcf.gz`

Here I am providing AF externally using AF.txt (format: CHR\tPOS\tREF,ALT\tAF). But I am not getting any output but it is saying a target file is required. I didn't find anything related to the target file in the documentation. I want to check ROH for the whole vcf, not for a specific region. 

![image](https://github.com/user-attachments/assets/62e4d4ae-bed2-4dbc-9c05-c72624e85037)

Can you please suggest how to perform bcftools ROH analysis. Thanks.

**Comment by pd3** [comment]
As shown here http://samtools.github.io/bcftools/howtos/roh-calling.html  in Example 2, you need to compress and index the file
```
$ bgzip AF.txt
$ tabix -s1 -b2 -e2 AF.txt.gz
$  bcftools roh --AF-file AF.txt.gz -o bcftools_roh.txt -G30 input.vcf.gz
```
