### ISSUE TITLE
Compiling on Centos 7.9 requires adding '-std=gnu99' to CFLAGS

### ISSUE THREAD

**Issue by Gullumluvl** [samtools/bcftools#2262]
Hi,

I could not compile bcftools until I add this flag to the `./configure` command.

In details, I am on a CentOS 7.9.2009 server with `gcc` version `4.8.5 20150623 (Red Hat 4.8.5-44)`.

I download and extracted htslib-1.20 and bcftools-1.20 alongside; in bcftools folder, I ran:

    autoreconf
    ./configure --enable-libgsl --enable-perl-filters --prefix=$HOME/.local CFLAGS='-g -Wall -O2 -std=gnu99'
    make
    make test

As a side note, on my server it is also necessary to call `configure` with `LDFLAGS='-Wl,-rpath=/usr/local/lib'` so that the libgsl.so files are found at run-time.

I am not familiar with generating Makefiles for multiple platforms, but would it make sense to have it set automatically?

**Comment by jkbonfield** [comment]
CentOS 7 is end-of-life already and out of support, hence it has a rather out of date compiler.  The current gcc is version 14, so 4.8 is ancient.

That said, we do require a C99 compatible compiler.  You can do `./configure CC="gcc -std=gnu99"`.  We ought to clearly state this in the INSTALL file as a prerequisite, but given this system version is no longer maintained by the vendor I'm not sure if it is time well spent auto-detecting it as all currently supported OSes we're aware of are already C99 compliant (it is, afterall, a 25 year old standard!).

**Comment by Gullumluvl** [comment]
Makes sense. We will indeed probably move to a newer OS at some point. Thanks!
