### ISSUE TITLE
Permanent configuration of BCFTOOLS_PLUGINS path

### ISSUE THREAD

**Issue by gevro** [samtools/bcftools#2268]
Hi,
Is there a way to configure this permanently within the bcftools path, for example in a config file? As opposed to defining this environment variable each time.

Or making a default search path that at least includes the 'plugins' directory present in the same directory as the bcftools binary.

**Comment by gevro** [comment]
Thanks so much. I think it would be helpful if it at least also searched the path of the binary.

**Comment by jkbonfield** [comment]
Finding the path of a binary is non-trivial.  See https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe/1024937#1024937 for the full horror.  So this isn't viable.

**Comment by pd3** [comment]
The way the question is phrased and since a config file was suggested as a possible solution, it makes me think you might be asking something more trivial: one can set the environment variable via .bashrc or .profile.

**Comment by gevro** [comment]
Yes, that works too. Thanks.
