### ISSUE TITLE
Pipe into bcftools view with region specification

### ISSUE THREAD

**Issue by gevro** [samtools/bcftools#2269]
Hi,
With bcftools 1.20, it seems that piping into bcftools view doesn't work if the view function is also run with a region specified. It causes bcftools view to think that the region is the input file rather than the piped in data.

**Comment by gevro** [comment]
Actually, nevermind, I think the issue is that piping into bcftools view means that the piped in VCF does not yet have an index, which then prevents the downstream view command from having an index by which to retrieve the region. Not sure what a work-around could be for this, probably no way around this.

**Comment by pd3** [comment]
You can use the `-t/-T` options. While `-r/-R` use the index to jump regions, `-t/-T` go through the entire stream and drop sites outside the regions.
