### ISSUE TITLE
Plugin writing question and bcf_int32_vector_end

### ISSUE THREAD

**Issue by travc** [samtools/bcftools#227]
More of a question than an issue...

I'm writing a simple plugin which outputs AN and AC for multiple subsets of sample (part of calculating population based stats like Dxy).  I'm basing it on dosage.c, though it is significantly simpler.  So far so good... it seems to be working.

However, this block of code keeps hitting the "vector_end" condition, and I don't know if that indicates some sort of problem or not.  

    for( i=0; i<n_pops; ++ i){
        an[i] = 0;
        memset(ac[i], 0, sizeof(int)*n_allele);
        for( j=0; j<pops_n[i]; ++j ){
            for( k=pops[i][j]*ploidy; k<pops[i][j]*ploidy+ploidy; ++k ){
                if( ptr[k]==bcf_int32_missing ){
                    fprintf(stderr,"\tint32 missing\n");
                }else if( ptr[k]==bcf_int32_vector_end ){
                    fprintf(stderr,"\tvector_end\n");
                }else if( ptr[k]==bcf_gt_missing || bcf_gt_is_missing(ptr[k]) ){
                    //fprintf(stderr,"\tgt missing\n");
                }else{
                    ++an[i];
                    ++ac[i][bcf_gt_allele(ptr[k])];
                }
            }
        }
    }

I'm wondering what exactly hitting "vector_end" indicates.
I think I'm indexing properly, but am not 100% sure... `pops[i][j]` (sample 'j' in pop 'i') set using:

    khash_str2int_get(hdr_samples, sample_ids[i][j], &(pops[i][j]))

**Comment by pd3** [comment]
Hi, the vector_end byte is present only when there are samples with different ploidy in the record. For example, in the record "0 0/0" you should find only one ("0/e 0/0").  So most likely there is a bug in your code if you are getting it a lot.

**Comment by travc** [comment]
Thanks.
