### ISSUE TITLE
How to correct VCF header with extra space/tab in it

### ISSUE THREAD

**Issue by desmodus1984** [samtools/bcftools#2270]
Hi,

I have genotyped samples from bisulfite sequencing.
I want to filter sites and get only biallelic SNPs but the header was built wrong.
there is an extra space or extra tab.
#CHROM	POS	ID	REF	**ALT		QUAL**	FILTER	INFO	FORMAT	V02055.bsg

As you can see, this wrong header causes the file to be either incompatible or unreadable by other tools like bcftools or even VCFtools - since the latest only uses VCFv4.2 and the output is VCFv4.4.

For example:
`bcftools view -m2 -M2 -v snps V02055.bsg.vcf.gz -o V02055.bsg.biallel.vcf.gz
`
[W::vcf_parse] Contig 'NW_022882922.1' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::vcf_parse_format] Number of columns at NW_022882922.1:4990 does not match the number of samples (1 vs 2)
Error: VCF parse error

Is is possible to fix this error? I was suggested to use annotate but it seems to need a header, and I don't know how to fix this when the problem is that extra space/tab.

Thanks.

**Comment by pd3** [comment]
You can use the `reheader` command to fix the header. For example
```
# extract the broken header using standard unix commands
zcat broken.vcf.gz | grep ^# > hdr.txt

# edit the header and fix it using your favourite editor (it must be capable of tab vs space distinction)
vi hdr.txt

# replace the header
bcftools reheader -h hdr.txt broken.vcf.gz > fixed.vcf.gz 
```
