### ISSUE TITLE
split-vep AF

### ISSUE THREAD

**Issue by andrew2k** [samtools/bcftools#2279]
Dear Bcftools team,

I am trying to use the +split-vep plugin in order to parse a VEP vcd file (bcftools 1.19).
The plugin seems to work well, but I often don't get any value in the AF column. Have you any idea why ?

This is the command I used:
bcftools +split-vep vep_output.ann.vcf.gz -f '\t%CHROM\t%ID\t%POS\t%REF\t%ALT\t%CSQ[\t%GT][\t%GQ][\t%DP][\t%AD][\t%PL]\n' -H -d  -A tab > output_vep.tsv

Thx a million.

**Comment by pd3** [comment]
The question is confusing, the `+split-vep` command you show does not request the AF values to be printed. Assuming it is just a typo, the question still cannot be answered without seeing the VCF. The most likely explanation is that the variants in the VCF don't have the AF values filled in...?
