### ISSUE TITLE
`bcftools merge` behavior with FILTER field

### ISSUE THREAD

**Issue by rronen** [samtools/bcftools#228]
Sorry, can't seem to find in the docs the strategy for FILTER on merge. 

With INFO fields I use `--info-rules` (which are great), and for FILTER I'd like to do something like OR operation (i.e., if any of the inputs have PASS the output should have PASS).

Is it possible to specify this somehow? (If not it would be a great additional feature)

**Comment by dheerajbobbili** [comment]
Hi, 
Is this feature implemented ?? It would be very useful.

Regards,
Dheeraj.

**Comment by pd3** [comment]
Here is the description from the usage page:

     -F, --filter-logic <x|+>       remove filters if some input is PASS ("x"), or apply all filters ("+"). The default is to apply all filters

I hope this helps.

**Comment by mcshane** [comment]
Reopening until this is merged into the main repo.

**Comment by stevendavis** [comment]
Are there any stable releases or branches with the --filter-logic functionality?

**Comment by adfdb** [comment]
The last versioned release was on Apr 22, so the answer is no.

However, you should be aware that a versioned release is not the same thing as a stable release. That's just an illusion, there are many unfixed bugs, just check the history of commits. I recommend taking the latest github version.
