### ISSUE TITLE
`--output-type u --write-index=tbi` writes csi index 

### ISSUE THREAD

**Issue by fellen31** [samtools/bcftools#2284]
Hi, 

While `--output-type v --write-index=tbi` gives an error:

```
[E::bcf_idx_init] Indexing is only supported on BGZF-compressed files
```

`--output-type u/b --write-index=tbi` results in a csi index. 

A csi index is also created while writing uncompressed BCF output, even though the manual states "Can be used only for compressed BCF and VCF output.".

1. Could `--output-type u/b --write-index=tbi` result in an error instead of a csi index, if tbi is not supported?
2. Could/should I use the csi index that is output together with an uncompressed BCF? 

Thanks!

**Comment by pd3** [comment]
The BCF format can be indexed only with csi. The tbi format is used to index bgzf-compressed VCFs. Therefore, please try this instead
```
--output-type z --write-index=tbi
```
