### ISSUE TITLE
Bcftools merge

### ISSUE THREAD

**Issue by desmodus1984** [samtools/bcftools#2285]
Hi,
I am planning to do variant calling with DeepVariant, and I plan to merge the vcfs later for doing population analysis.
My question is, should I set DeepVariant to produce a Vcf file or a gVCF files for later merging?
Or either will work for merging.

Thanks;

**Comment by pd3** [comment]
Either can be merged. However, the difference is that gVCF contains information for all positions in the genome with coverage. When merging multiple samples, the program will be able to tell when to put in a missing genotype `./.` (no coverage in the sample) or the hom ref genotype `0/0` (no variant in the sample).
