### ISSUE TITLE
bcftools concat segfault if VCF files contain only headers

### ISSUE THREAD

**Issue by dpryan79** [samtools/bcftools#2286]
It seems that `bcftools concat` will segfault if the files it's combining have only headers:

```
$ bcftools concat -d exact -a -o combined.vcf.gz -O b --threads 1 bar.vcf.gz foo.vcf.gz
Checking the headers and starting positions of 2 files
Segmentation fault (core dumped)
```

I'll attach a header-only VCF file that can be easily used for testing (just copy it to bar.vcf.gz)
[foo.vcf.gz](https://github.com/user-attachments/files/17145288/foo.vcf.gz)

**Comment by pd3** [comment]
Thank you for the test case, I can confirm it is reproducible. It is something that may need to be addressed in htslib.

**Comment by dpryan79** [comment]
@pd3 Thanks, that's the feeling I got when I ran it through valgrind. I honestly wasn't sure whether it made more sense to make the issue here or with htslib, since I imagine it's harder to reproduce on that repo.

**Comment by pd3** [comment]
This will be fixed by https://github.com/samtools/htslib/pull/1845
