### ISSUE TITLE
error while using the plot-vcfstats to make the plots

### ISSUE THREAD

**Issue by amitgsir** [samtools/bcftools#229]
Hi,

I am trying to compare two vcf files (with Indel information)..

I generated the stats (file.stats) file using the two vcf files. But getting the error while using the plot-vcfstats to make the plots.

Please have a look.
Thanks.

amit@eonediag02:/data2/users/amit/Indel_Analysis/DongA_Exome_Data1/concordance$ /home/amit/Applications/bcftools-1.2/plot-vcfstats -p plots/ file.stats
Parsing bcftools stats output: file.stats
Plotting graphs: python plots/plot.py
Traceback (most recent call last):
File "plots/plot.py", line 284, in 
ax1.set_ylim(min(2,min(row[2] for row in dat))-0.3,0.3+max(2.2,max(row[2] for row in dat)))
ValueError: min() arg is an empty sequence
The command exited with non-zero status 256:
python plots/plot.py

at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 78.
main::error("The command exited with non-zero status 256:\x{a}\x{9}python plots/pl"...) called at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 271
main::plot(HASH(0xc98018)) called at /home/amit/Applications/bcftools-1.2/plot-vcfstats line 67

Amit

**Comment by lifernan** [comment]
I solved this by adding a check for the length of the dat variable for plot_tstv_by_qual. In plot_vcfstats, changing the line "if plot_tstv_by_qual" to "if plot_tstv_by_qual and len(dat)>2:"
