### ISSUE TITLE
Is BCFtools norm guaranteed to maintain sort order? 

### ISSUE THREAD

**Issue by davidjakubosky** [samtools/bcftools#2290]
Hello, wondering if the output of bcftools norm can be guaranteed to maintain sort order
 - is it necessary to sort after bcftools norm 
 - is there any risk of a very large multi-allelic getting split to positions out of its window/out of sort with rest of VCF? 
 
Would appreciate guidance, looking to avoid unnecessary sorting

**Comment by pd3** [comment]
Realigned lines are resorted within a window of 1000bp, which is the default of `-w, --site-win`. There would have to be a 1kb repeat in the genome with just the right indel for that to happen. It did not happen to me yet, and it should not go unnoticed - the indexing step would complain.  So probably OK
