### ISSUE TITLE
Filtering out indels but keeping invariant sites

### ISSUE THREAD

**Issue by ja-Reeve** [samtools/bcftools#2299]
I'm having some issues trying to remove indels from my data. I want to keep invariant sites (all genotypes match the reference) and SNPs. There seems to be two ways to do this in the manual:

1. Comparing the REF and ALT alleles in the VCF record, by setting the -v option:
`bcftools view -v snps,ref input.vcf.gz > noIndel.vcf`

2. Using the INFO tag to select "snps" and "ref": 
`bcftools view --include 'TYPE="snp" || TYPE="ref"' input.vcf.gz > noIndel.vcf`

Option 1 doesn't keep invariant (ref) sites, but removes indels. Option 2 keeps invariants and also some indels.
This indel issue with option 2 was posted on biostars ([https://www.biostars.org/p/9563500/](https://www.biostars.org/p/9563500/)), which seems to suggest something is not matching the VCF 4 format... 

Am I coding something wrong, or is there some underlying issue in how indels are being reported in the VCF?

**Comment by pd3** [comment]
It should be possible to remove indels easily with 
```
bcftools view -e 'type="indel"'
```
