### ISSUE TITLE
bcftools stats always gives summary of total data even when subset was ordered 

### ISSUE THREAD

**Issue by hoosier060** [samtools/bcftools#230]
Hi bcftools team,

I learned the stat function is handy and great in summarizing the data.
But when I tried for a subset of the data, on the first page of the summary pdf output, instead of providing counts by variant types of 'the subset' I designated, bcftools always give summary of the total data.
Is it meant to be this way and should I subset the data first then run stats?

My command was:
bcftools stats -F hg19.fasta -S subset var.vcf.gz > subset_stats.out

If I missed something or, there is a way to make 'stats' to output summary for 'the subset', could you help me getting it, please?

Thank you!

**Comment by mcshane** [comment]
The summary stats (SN) numbers are counting stats based on mostly on the site information in the VCF and this doesn't change for the subset. To get the behaviour you're after you can do the subset first, strip out sites which are no longer polymorphic and then do the stats. e.g.

```
bcftools view -Ou -aUS subset var.vcf.gz | bcftools stats -F hg19.fasta > subset_stats.out
```
