### ISSUE TITLE
bcftools call empty output with -o

### ISSUE THREAD

**Issue by niederhuth** [samtools/bcftools#2301]
I am running bcftools mpileup & call on some pacbio data (before you ask, I cannot share any data, not even screenshots. It is proprietary). here is my command:

`bcftools mpileup --threads 8 -Ou --seed 1 --annotate FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SCR,FORMAT/NMBZ,FORMAT/QS,FORMAT/SP,FORMAT/SCR,INFO/AD,INFO/ADF,INFO/ADR,INFO/BQBZ,INFO/FS,INFO/IDV,INFO/IMF,INFO/MQ0F,INFO/MQBZ,INFO/NM,INFO/NMBZ,INFO/RPBZ,INFO/SCBZ,INFO/SCR,INFO/SGB,INFO/VDB --config pacbio-ccs -f genome.fa input.bam -Ou | bcftools call --threads 8 --multiallelic-caller --annotate FORMAT/GQ,FORMAT/GP,INFO/PV4 --ploidy 2 --variants-only --output-type v`

If I run it the command as is. It will output variants just fine to the screen. If I use -o or --output to specify the output file, It will run and exit without throwing any errors and giving completely empty output. Not even a header. I have tried it on both AWS and our own servers with the same issue. I have been using v1.2, but just updated to 1.2.1 and am testing. 

DeepVariant can call the entire dataset just fine. I'm at my wits end as to what is going on.

**Comment by niederhuth** [comment]
I should also note that on some occaisions it has produced output, but then randomly stops not even halfway through the data, with no error message.

**Comment by pd3** [comment]
> I have been using v1.2, but just updated to 1.2.1 and am testing.

Is this a typo? We are at version 1.21

**Comment by niederhuth** [comment]
Yes, a typo and the latest version corrected the issu.
