### ISSUE TITLE
Convert missing single dot to "./."?

### ISSUE THREAD

**Issue by bbimber** [samtools/bcftools#2303]
Hello,

The single dot can indicate a missing genotype; however, some tools like beagle do not parse this correctly. Is there a way to convert these? I was hoping setGT would do this, but I am not having any luck. Should this or something like it work?

```
bcftools +setGT $VCF -o test.vcf -- -t '.' -n './.'
```

**Comment by pd3** [comment]
This is now possible with
```
bcftools +setGT test.vcf -- -t . -n c:./.
```

**Comment by bbimber** [comment]
thank you!

**Comment by Sreelekshmi-291** [comment]
Hi,
I tried the above command to convert the "." to "./.", but the single dot remains.
`bcftools +setGT sample.vcf.gz -- -t . -n c:./. | bcftools view -Oz -o sample.modified.vcf.gz`

<img width="1841" height="654" alt="Image" src="https://github.com/user-attachments/assets/71204b04-f927-465b-83e5-84bad4701d65" />

Please notice the highlighted part.

Is there any other way to do this?

Thank you

**Comment by Sreelekshmi-291** [comment]
I have been using an older version of bcftools, updating it to the latest version solved the issue for me.
Thanks
