### ISSUE TITLE
Heterozygocity missing

### ISSUE THREAD

**Issue by cottonrnr** [samtools/bcftools#2304]
Hello,

I am using "bcftools call --ploidy 1 -m -o test_vcf test_bcf " to call variants for individuals of a F2 population. Derived vcf didn't show any heterozygous sites, which is not right. The code worked before, but not now. How to fix this issue?

Thanks!

**Comment by pd3** [comment]
Mmm, when you specified `--ploidy 1` you explicitly told the program to consider only haploid genotypes, in the VCF notation eg `1` instead of `0/1`. If you drop the option, you should hopefully start seeing heterozygous genotypes.

**Comment by cottonrnr** [comment]
Thanks Peter. It worked after removing the ploidy parameter.
