### ISSUE TITLE
  cannot plot using bcftools stats output

### ISSUE THREAD

**Issue by gsarah** [samtools/bcftools#232]
My issue is exactly identical as the closed one #179
I had the problem on my server on which the installed version is the 1.1. I then install the latest version (1.2) and use it and got exactly the same error.

Thanks
###### 

Plotting graphs: python plots/plot.py
  File "plots/plot.py", line 62
    if x.ndim != 1: raise ValueError, "smooth only accepts 1 dimension arrays."
                                    ^
SyntaxError: invalid syntax
The command exited with non-zero status 256:
    python plots/plot.py

 at /homedir/sarah1/bin/plot-vcfstats line 78
    main::error('The command exited with non-zero status 256:\x{a}\x{9}python plots/pl...') called at /homedir/sarah1/bin/plot-vcfstats line 271
    main::plot('HASH(0x255dc00)') called at /homedir/sarah1/bin/plot-vcfstats line 67

**Comment by gsarah** [comment]
Sorry, I was not polite, so I say "Hi" now ;)

**Comment by mcshane** [comment]
See also #229 and #238.

**Comment by snashraf** [comment]
was this issue solved ? 
getting same error ..

Plotting graphs: python plot.py
  File "plot.py", line 63
    if x.ndim != 1: raise ValueError, "smooth only accepts 1 dimension arrays."
                                    ^
SyntaxError: invalid syntax
The command exited with non-zero status 256:
	python plot.py

**Comment by pd3** [comment]
Could you please send me the output of `bcftools stats` so that I can check what's going on? My email is on the profile page. Thanks

**Comment by Adrianzo** [comment]
At 2015 OP stated "I then install the latest version (1.2) ".

I've had the same with bcftools 1.3, updating to latest version (1.5) solved it. This should be closed now :+1:
