### ISSUE TITLE
bcftools view -m 2 -M 2 referencePanel.vcf.gz（SV and SNP）

### ISSUE THREAD

**Issue by SunWinner01** [samtools/bcftools#2320]
Hello, sorry to bother you. Currently, I’m using the command `bcftools view -m 2 -M 2 --threads 4 -Ob -o referencePanel.22.bcf referencePanel.vcf.gz` to process my data. My file `referencePanel.vcf.gz` contains a combination of SNPs and structural variant (SV) data, with SV information included among the SNPs. However, after running this command, I noticed that there was no change in the resulting file. I’d like to ask if this is normal, as I have the following questions:

1. Does `bcftools view -m 2 -M 2` have no effect on SV data?
2. What kind of SNPs would not pass the filter using the command `bcftools view -m 2 -M 2`?
3. In my file, the REF and ALT columns of the SNP data are composed solely of one of the letters A, G, C, or T.

These are all my questions. I look forward to your reply! Thank you so much, and I wish you all the best.

**Comment by SunWinner01** [comment]
[example.vcf.gz](https://github.com/user-attachments/files/17802389/example.vcf.gz)
Hello, this is part of the content of my file. I hope you can use the commands I provided to process my files. I want to know why nothing changes in the result file. hope to get your reply @pd3

**Comment by SunWinner01** [comment]
I already understand what's going on. Thank you @pd3

**Comment by pd3** [comment]
I looked at your data and I don't really see a problem, the program seems to be doing exactly what it is supposed to do: leave in biallelic records, which is what you have in the VCF. What did you expect to see?

**Comment by SunWinner01** [comment]
OK Thank you for your reply. I already understand my results. The operation is very correct. @pd3
