### ISSUE TITLE
bcftools merge missing GT information

### ISSUE THREAD

**Issue by poddarharsh15** [samtools/bcftools#2326]
I’m using bcftools merge to combine VCFs from several samples with the following command:

`bcftools merge -m none --force-samples -l "$MERGED_VCF_LIST" -Oz -o "$MERGED_VCF" --threads "$THREADS"  `

However, I’m having trouble understanding which variants in the merged VCF are shared across samples and which are present in only one sample. Could you please take a look at my test results and provide some insights on how to interpret this or if I’m missing any steps? [merging SVs using WES data, `dysgu` SV caller used for Variant Calling]

Thank you!

Best,
Harsh

[top_300_rows_with_header.txt](https://github.com/user-attachments/files/17960420/top_300_rows_with_header.txt)

**Comment by pd3** [comment]
Mmm, I am sorry but I don't understand what you're asking. Are you trying to filter variants by the presence in multiple samples? Or are you simply not liking the missing genotypes?

**Comment by poddarharsh15** [comment]
Hi @pd3 
Sorry for not explaining it better earlier. I am trying to calculate the Allele Frequency (AF) or population frequency for the presence of each variant in my dataset to filter out variants present in more than 10% of the cohort. Currently, I’m working with 438 WES samples and structural variants detected using `dysgu`.
The challenge is that some information is missing in the merged VCF file due to the multi-sample format. Could you please suggest a better approach to accurately calculate AF or population frequency for filtering these variants? Any insights or tools you recommend would be highly appreciated.

Thanks in advance!

**Comment by pd3** [comment]
If the input VCF don't carry the genotype information for the sites you are interested in, than there is not much one can do. You could assume that the missing sites are in fact reference genotypes and pass the option
```
-0  --missing-to-ref              Assume genotypes at missing sites are 0/0
```
However, variants/genotypes can be missing from multiple reason: low coverage or calls that lack confidence.

Sorry I can't help more

**Comment by poddarharsh15** [comment]
Hi @pd3 

Thank you so much for your suggestion! I really appreciate it. I wanted to ask for one last piece of advice. I’ve been using a command to calculate Minor Allele Frequency (MAF) and Allele Frequency (AF) , based on a sample file. Would you recommend calculating the frequency of each variant per sample as the best practice? Or is there a more robust approach I should consider?

`bcftools +fill-tags all_cohort.vcf.gz -Oz -o dv_unsolved_udp_cohrt.tagged.vcf.gz -- -t AN,AC,NS,AF,MAF -S sample_names.tsv`

**Comment by pd3** [comment]
I am sorry, but I don't understand the question entirely. Allele frequency is calculated from the samples, by definition, I see no other way. The plugin `+fill-tags` is a good choice.
