### ISSUE TITLE
bcftools merge remove the phase of half-missing genotypes

### ISSUE THREAD

**Issue by Han-Cao** [samtools/bcftools#2331]
Hi,

I am using bcftools 1.21 and found `bcftools merge` cannot correctly output phased half-missing genotypes.

For half-missing input:
```
0|.    1|.    .|0    .|1
```
`bcftools merge` output:
```
0/.    1/.    .|0    .|1
```
It seems a bug when the second haplotype is missing. Could you check this?

Many thanks,
Han

**Comment by pd3** [comment]
This is now fixed.
