### ISSUE TITLE
Cannot filter by %CHROM

### ISSUE THREAD

**Issue by dridk** [samtools/bcftools#235]
Don't know what's wrong... 

bcftools filter -e '%CHROM=chr1' file.vcf.gz
Return : 
[filter.c:1298 filters_init1] Error: the tag "INFO/%CHROM" is not defined in the VCF header

So, it's not defined.. But Each line start by the chromosome name. 
and using a query, it works  : 
bcftools query -f "%CHROM"  file.vcf.gz

**Comment by dridk** [comment]
From a a mailing lists , I found : 
    
    CHROM and POS are not supported with -i/-e. I deliberately haven't added
    support for this as it makes more sense to use the -r/-R/-t/-T options
    for performance reasons.

So, yes it should be use for performance reason... Should be precise somewhere.. For exemple, add example with Chromosome filtering .

**Comment by dridk** [comment]
So, at the end, I didn't find an easy way to remove chromosomes ... 
I can only select chromosome, but not exclude. 
I propose you add in filter , a command "-inverse" , which return the non-filtering values.

**Comment by mcshane** [comment]
Depending on exactly what you want to do, you could use:

`bcftools view -t ^chr1 file.vcf.gz`

to exclude `chr1` from a VCF file. Or 

`bcftools view -t ^chr1,chr20 file.vcf.gz`

to remove `chr1` and `chr20`.

If you want to do further filtering with `bcftools filter`, you can pipe it like

`bcftools view -Ou -t ^chr1 file.vcf.gz | bcftools filter -e EXPR`

**Comment by dridk** [comment]
oh!! I didn't know " ^ " symbol  works as an exclude action ! Thanks !!
