### ISSUE TITLE
Does bcftools merge really need an index?

### ISSUE THREAD

**Issue by johanneskoester** [samtools/bcftools#236]
Hi,
currently, bcftools merge seems to require an index, even if I do not specify a region. From the code and also from my intuition, I cannot see why this should be necessary.
Shouldn't the index requirement only occur when specifying a region?
Each reader should process line by line in the simple case, shouldn't it?

Thanks,
Johannes

**Comment by pd3** [comment]
The index is necessary: if the VCFs contain multiple chromosomes, they can be listed in different order. Also the presence of index makes it clear that files passed a basic sanity check already: their coordinates are sorted.

**Comment by johanneskoester** [comment]
I see. I have a case where I know that the order is the same, and I want to pipe several bcfs into the merge command. Since the index is not necessary there, do you think a modification of the code is feasible, or does the merge algorithm rely heavily on the index? I would be happy to provide a pull request for some kind of --is-sorted functionality.

**Comment by johanneskoester** [comment]
I have created two corresponding pull requests to allow for that functionality:
https://github.com/samtools/bcftools/pull/252
https://github.com/samtools/htslib/pull/203

Any suggestions or comments are welcome.

Thanks!
