### ISSUE TITLE
[request] autotools instead of manually written makefile

### ISSUE THREAD

**Issue by kotoroshinoto** [samtools/bcftools#240]
or perhaps a cmake CMakeLists.txt
up to you whether to do it at all or which to do. Just a suggestion

**Comment by kotoroshinoto** [comment]
ditto for samtools itself

**Comment by jmarshall** [comment]
We use autoconf to generate a configure script in [htslib](https://github.com/samtools/htslib), and will have autoconf-generated configure scripts in [samtools](https://github.com/samtools/samtools) and bcftools in the future.

We prefer the current system of makefiles to an automake-generated one or a CMake build system.  Is there something concrete you think htslib/samtools/bcftools would gain by using automake or cmake?

**Comment by kotoroshinoto** [comment]
out of source builds are not required, but nice to be able to do. As I said, its up to you whether to do it at all. It also allows easier and more standard options for setting prefixes for make install etc. (not that we couldn't do it via environment variable setting if your makefile provided for it).

**Comment by jmarshall** [comment]
Indeed, we will be supporting out-of-source-tree builds when the configure scripts land.  Both this and prefix options etc are properties of a `configure` script; they do not require automake or cmake.

**Comment by kotoroshinoto** [comment]
well not strictly, though you often do find such used together. I cobbled together something when trying to deal with the problem tophat introduced for itself when it decided to package the older version of samtools to avoid conflicts. (suppose I could have had their make system softlink samtools directory into the out of source build, but that would have defeated the purpose). I read your makefile and put together my best estimation for what Makefile.am would need to compile properly. It seems to have worked just fine, but I don't know if it would be useful to you for the current version of samtools, given you probably reorganized the source tree when you split bcftools out and created htslib

**Comment by kotoroshinoto** [comment]
https://github.com/kotoroshinoto/tophat/commit/238ecb12e1d5a1f178d00f5451f7a51ada26f811

perhaps this may be of use, perhaps not.
