### ISSUE TITLE
gvcf2vcf not filling in REF allele correctly

### ISSUE THREAD

**Issue by mcshane** [samtools/bcftools#243]
When fixing #242 noticed that `gvcf2vcf` is just copying the REF allele from the beginning of the block. Command needs to take a reference fasta as input to fill in REF correctly.

**Comment by jmarshall** [comment]
There is a `-f`/`--fasta-ref` option that fills in `args.ref_fname` and `args.ref` for  `convert --tsv2vcf`.  So that can be reused for `--gvcf2vcf` (and possibly some of the code refactored and moved to `destroy_data()` etc).

**Comment by ryhui** [comment]
Hello, I just found out that this is fixed with uncompressed vcf output. If I use -Ou or -Ob, the REF allele is still copied from the beginning of the block.

**Comment by gtbil** [comment]
The issue [ryhui](https://github.com/ryhui) indicated is still a problem. The workaround is to write to VCF rather than BCF.

**Comment by pd3** [comment]
The BCF output is now fixed, finally. Thanks for reporting the bug, better to open a new issue next time, commenting on closed issues gets easily overlooked.
