### ISSUE TITLE
bcftools plugin problem

### ISSUE THREAD

**Issue by eberdan** [samtools/bcftools#247]
Hello,
I have bcftools and the htslib both correctly installed and compiled (I have run make test for both).  I can run the command "bcftools plugin"  and I get the normal help screen.  However, when I use the command "bcftools plugin -l" I get the error "No functional bcftools plugins were found. The environment variable BCFTOOLS_PLUGINS is not set."  I get the same error if I try to use any of the plugins.   I have set the LD_LIBRARY_PATH and it appears when I type env.  Here is the pertinent line from the env output:

LD_LIBRARY_PATH=/datana2/berdan/apps/samtools/bcftools-1.2/htslib-1.2.1:/home/berdan/apps/lib

Another strange thing is to run bcftools without typing ./bcftools (from the bctools directory) I have to add both bcftools and samtools to my PATH file.  I am not sure why.   I have the same problem with samtools.   

Any suggestions are appreciated!

**Comment by jmarshall** [comment]
If this is bcftools **1.2**, you need to set `$BCFTOOLS_PLUGINS` for it to see any plugins at all.  For you, this will probably be

    export BCFTOOLS_PLUGINS=/datana2/berdan/apps/samtools/bcftools-1.2/plugins

This will be changing in the next release (see bea7d08f1947df750acf2577dbe827b1a43f549b): the supplied plugins will be installed with `make install` and bcftools should find them automatically, and you can add directories to BCFTOOLS_PLUGINS to search for any other plugins you might have.

**Comment by eberdan** [comment]
That fixed the problem.  Thanks!

**Comment by jmarshall** [comment]
> Another strange thing is to run bcftools without typing ./bcftools (from the bctools directory) I have to add both bcftools and samtools to my PATH file. I am not sure why. I have the same problem with samtools.

I'm not sure what you're describing, but I don't think it's related to bcftools.  I suspect you've just encountered the fact that `$PATH` [doesn't contain `.` (the current directory)](http://unix.stackexchange.com/questions/65700/is-it-safe-to-add-to-my-path-how-come).
