### ISSUE TITLE
bcftools view -G should remove FORMAT header lines

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#248]
Running `bcftools view -G input.bcf` drops all columns past the INFO column.  However, the headers are not updated to reflect this change.  I'll write a pull request for this, but I thought I'd put it here so I don't forget.

**Comment by mcshane** [comment]
Thanks Winni. Pull request would be welcome. There is some similar code in vcfannotate.c.

**Comment by wkretzsch** [comment]
I have submitted pull request #251 that fixes this issue.
