### ISSUE TITLE
plugin compilation on Mac depends on libhts.so

### ISSUE THREAD

**Issue by noporpoise** [samtools/bcftools#249]
The `Makefile` specifies that plugin `.so` files depend on `../htslib/libhts.so`, which isn't built by htslib on a Mac. This causes plugins to be recompiled every time `make` is run. 

I'm not sure why it doesn't cause an error since a dependency of the target is missing.

**Comment by jmarshall** [comment]
An alternative approach is to not link the plugins against libhts, but instead to link bcftools with `‑rdynamic`.
