### ISSUE TITLE
Strange behaviour of bcftools norm: Leftaligned insertions sequence modification

### ISSUE THREAD

**Issue by meritxellop** [samtools/bcftools#250]
I have found an unusual behaviour of bcftools norm in leftaligning insertions that coincides with the reference genome (the reference genome has the exact same sequence than the insertion in the positions following the preceding nucleotide, used as an anchor to annotate the insertion). In these cases, after leftaligning, not only the position of the insertion is modified, but also the insertion sequence (see case below, where insertion CAG in position 132547072 is modified). What is going on in these cases?

Thanks

&> bcftools norm -m-both -O v -f hsapiens_v37.unmasked.fa input.vcf.gz input.vcf.gz

##fileformat=VCFv4.1 
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20150121 
##source=TCGA
##reference=NCBI37
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id">
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position">
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type">
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138">
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant">
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call">
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=M,length=16569,assembly=b37>
##bcftools_normVersion=1.2+htslib-1.2.1
##bcftools_normCommand=norm -m-both -O v -f /project/devel/moliva/Kaviar/fastas/hsapiens_v37.unmasked.fa prova2.vcf
##bcftools_normCommand=norm -m-both -O v -f /project/devel/moliva/Kaviar/fastas/hsapiens_v37.unmasked.fa input.vcf.gz
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
12	132547068	.	G	GGCA	.	.	SAMPLE=TCGA-A6-2680-01A;LEN=3;CANCER=CRC;VARFREQ=0.74;VARSCANPVAL=6.6e-11
12	132547068	.	G	GGCA	.	.	SAMPLE=TCGA-AG-3901-01A;LEN=3;CANCER=CRC;VARFREQ=0.35;VARSCANPVAL=0.0013
12	132547068	.	G	GGCA	.	.	SAMPLE=TCGA-CJ-5682-01A;LEN=3;CANCER=KIRC;VARFREQ=0.36;VARSCANPVAL=3.3e-05
Lines total/modified/skipped:	3/1/0

where

&> zcat input.vcf.gz

##fileformat=VCFv4.1 
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20150121 
##source=TCGA
##reference=NCBI37
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Samples id">
##INFO=<ID=LEN,Number=1,Type=Integer,Description="Variant end position">
##INFO=<ID=CANCER,Number=1,Type=String,Description="Cancer type">
##INFO=<ID=DBSNP138,Number=0,Type=Flag,Description="Flag presence dbSNP 138">
##INFO=<ID=VARFREQ,Number=1,Type=Float,Description="Frequency variant">
##INFO=<ID=VARSCANPVAL,Number=1,Type=Float,Description="Significance somatic mutation call">
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=M,length=16569,assembly=b37>
##bcftools_normVersion=1.2+htslib-1.2.1
##bcftools_normCommand=norm -m-both -O v -f /project/devel/moliva/Kaviar/fastas/hsapiens_v37.unmasked.fa prova2.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
12	132547068	.	G	GGCA	.	.	SAMPLE=TCGA-A6-2680-01A;LEN=3;CANCER=CRC;VARFREQ=0.74;VARSCANPVAL=6.6e-11
12	132547068	.	G	GGCA	.	.	SAMPLE=TCGA-AG-3901-01A;LEN=3;CANCER=CRC;VARFREQ=0.35;VARSCANPVAL=1.3e-03
12	132547072	.	G	GCAG	.	.	SAMPLE=TCGA-CJ-5682-01A;LEN=3;CANCER=KIRC;VARFREQ=0.36;VARSCANPVAL=3.3e-05

**Comment by mcshane** [comment]
Hi,

norm is working as expected here. 

The `12/132547068/G/GGCA` insertion looks like:
```
REF:TCAG---GCAGCAG
ALT:TCAGGCAGCAGCAG
```
while the `12/132547072/G/GCAG` insertion looks like:
```
REF:TCAGGCAG---CAG
ALT:TCAGGCAGCAGCAG
```
which because of the repeat is equivalent to:
```
REF:TCAGG---CAGCAG
ALT:TCAGGCAGCAGCAG
```
and
```
REF:TCAG---GCAGCAG
ALT:TCAGGCAGCAGCAG
```
