### ISSUE TITLE
Strange behaviour of bcftools view: INFO field value gets trimmed

### ISSUE THREAD

**Issue by meritxellop** [samtools/bcftools#253]
An INFO field value gets trimmed when using bcftools view (DBSNP142=00 becomes DBSNP142=0)
Why is that? 

> zgrep -v '#' a.lite.vcf.gz
21	9411601	rs557151743	T	C	.	.	DBSNP142=00
21	9411602	rs368646645	T	C	.	.	DBSNP142=10
21	9411607	rs539763752	A	C	.	.	DBSNP142=00
21	9411608	rs71220654	TG	TCGTCTATT,TTGTCTATG	.	.	DBSNP142=20
21	9411609	rs76676778	G	T	.	.	DBSNP142=20
21	9411617	rs370592152	A	G	.	.	DBSNP142=00
21	9411618	rs141221894	C	T	.	.	DBSNP142=20
21	9411635	rs374207079	C	T	.	.	DBSNP142=20
21	9411645	rs71235074	A	G	.	.	DBSNP142=10
21	9411689	rs541834812	G	A	.	.	DBSNP142=00
21	9411710	rs555311353	C	A	.	.	DBSNP142=00

> bcftools view -H  a.lite.vcf.gz
21	9411601	rs557151743	T	C	.	.	DBSNP142=0
21	9411602	rs368646645	T	C	.	.	DBSNP142=10
21	9411607	rs539763752	A	C	.	.	DBSNP142=0
21	9411608	rs71220654	TG	TCGTCTATT,TTGTCTATG	.	.	DBSNP142=20
21	9411609	rs76676778	G	T	.	.	DBSNP142=20
21	9411617	rs370592152	A	G	.	.	DBSNP142=0
21	9411618	rs141221894	C	T	.	.	DBSNP142=20
21	9411635	rs374207079	C	T	.	.	DBSNP142=20
21	9411645	rs71235074	A	G	.	.	DBSNP142=10
21	9411689	rs541834812	G	A	.	.	DBSNP142=0
21	9411710	rs555311353	C	A	.	.	DBSNP142=0

**Comment by meritxellop** [comment]
I just figured out what was happening: INFO field DBSNP142 was defined as an integer instead of a string. I guess that is why 00 was converted to 0. I edited the header and problem solved.

**Comment by mcshane** [comment]
OK. Good that it is solved. Thanks.
