### ISSUE TITLE
Variant annotation into INFO field using bcftools

### ISSUE THREAD

**Issue by holtgrewe** [samtools/bcftools#255]
Is it possible to use `bcftools annotate` for annotating variants from dbSNP, COSMIC, ... VCF files into the `INFO` field of the annotated VCF file?

I know that I can copy over the dbSNP or COSMIC ID from the database VCF file to the annotated field using `bcftools annotate IN.vcf.gz -a dbSNP.vcf.gz -c ID`. However, is it also possible to write the ID into a new info field?

This appears to be possible for non-VCF annotation files, though.

**Comment by pd3** [comment]
This is not possible directly, sorry. However, you can easily create an annotation file as described in this howto https://github.com/samtools/bcftools/wiki/HOWTOs#annotate-from-bed

The annotation file itself can be created by running

    bcftools query -f'%CHROM\t%POS\t%ID\n' | bgzip -c > annot.tab.gz
