### ISSUE TITLE
bcftools v1.2 help compiling with polisomy

### ISSUE THREAD

**Issue by santiagorevale** [samtools/bcftools#259]
Hi John,

I was trying to compile latest version of bcftools (1.2) with polisomy but an error appeared and broke the compilation. Logs for the "make" command are at the end of the post.

I know it is related on how to reference to the GSL library repository but I don't know how to do this. I've seen that issue 222 indicates this is solved. Could you point me in the right direction?

I have compiled and test succesfully GSL v1.16 manually. I added the appropiate paths to the environmental variables PATH (bin), LD_LIBRARY_PATH and LD_RUN_PATH (lib), C_INCLUDE_PATH and CPLUS_INCLUDE_PATH (include), but it still doesn't find gsl

I'm performing the installation on a CentOS 5.5. I'm compiling with gcc version 4.7.4.

By the way, only bcftools should be compiled with USE_GPl=1, right?

Any help would be really appreciated.

Best,
Santiago

$ make clean && make USE_GPL=1 HTSDIR=/home/adminrig/Software/htslib-1.2.1/src
rm -f test/*.o test/*~ test/test-rbuf
rm -f plugins/*.so plugins/*.P plugins/*.dSYM
rm -f gmon.out *.o *~ bcftools version.h plugins/*.so plugins/*.P
rm -rf *.dSYM plugins/*.dSYM test/*.dSYM
echo '#define BCFTOOLS_VERSION "1.2"' > version.h
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src main.c -o main.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfindex.c -o vcfindex.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src tabix.c -o tabix.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfstats.c -o vcfstats.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfisec.c -o vcfisec.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfmerge.c -o vcfmerge.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfquery.c -o vcfquery.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcffilter.c -o vcffilter.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src filter.c -o filter.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfsom.c -o vcfsom.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfnorm.c -o vcfnorm.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfgtcheck.c -o vcfgtcheck.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfview.c -o vcfview.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfannotate.c -o vcfannotate.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfroh.c -o vcfroh.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfconcat.c -o vcfconcat.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfcall.c -o vcfcall.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src mcall.c -o mcall.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcmp.c -o vcmp.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src gvcf.c -o gvcf.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src reheader.c -o reheader.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src convert.c -o convert.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfconvert.c -o vcfconvert.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src tsv2vcf.c -o tsv2vcf.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfcnv.c -o vcfcnv.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src HMM.c -o HMM.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src vcfplugin.c -o vcfplugin.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src consensus.c -o consensus.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src ploidy.c -o ploidy.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src version.c -o version.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src ccall.c -o ccall.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src em.c -o em.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src prob1.c -o prob1.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src kmin.c -o kmin.o
gcc -c -g -Wall -Wc++-compat -O2 -DUSE_GPL  -I. -I/home/adminrig/Software/htslib-1.2.1/src polysomy.c -o polysomy.o
gcc -g -Wall -Wc++-compat -O2 -DUSE_GPL -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o version.o ccall.o em.o prob1.o kmin.o  polysomy.o /home/adminrig/Software/htslib-1.2.1/src/libhts.a -lpthread -lz -lm -ldl -lgsl -lcblas
/usr/bin/ld: cannot find -lgsl
collect2: error: ld returned 1 exit status
make: *** [bcftools] Error 1

**Comment by jmarshall** [comment]
> gcc -g -Wall -Wc++-compat -O2 -DUSE_GPL -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o version.o ccall.o em.o prob1.o kmin.o polysomy.o /home/adminrig/Software/htslib-1.2.1/src/libhts.a -lpthread -lz -lm -ldl -lgsl -lcblas
**/usr/bin/ld: cannot find -lgsl**

Usually you would install GSL in one of the usual places so that everything would find it without needing `LD_LIBRARY_PATH` etc to be set.

The linker can't find `-lgsl`, so you would need to add a `-L` option pointing at the right place or add the right directory to `LIBRARY_PATH`.  (`LD_LIBRARY_PATH` is used by the runtime loader to open shared libraries, but `LIBRARY_PATH` is used by the linker during compilation.)

**Comment by santiagorevale** [comment]
Thanks, John. I'm not good compiling C software.

Now I have a new error: instead of requesting -lgsl it request -lcblas. Isn't cblas part of the gsl package? In the lib folder I have the following files (and links):

libgsl.a
libgslcblas.a
libgslcblas.la
libgslcblas.so -> libgslcblas.so.0.0.0
libgslcblas.so.0 -> libgslcblas.so.0.0.0
libgslcblas.so.0.0.0
libgsl.la
libgsl.so -> libgsl.so.0.17.0
libgsl.so.0 -> libgsl.so.0.17.0
libgsl.so.0.17.0
pkgconfig

Is it a naming problem? Should I rename libgslcblas to libcblas?

Thanks again for your time.

**Comment by jmarshall** [comment]
[Further question reposted as #263]
