### ISSUE TITLE
bcftools v1.2 help compiling with polisomy (continued)

### ISSUE THREAD

**Issue by santiagorevale** [samtools/bcftools#263]
Hi John,

Sorry for opening a new issue, but the previous ticket (259) was closed and remained that way even after I posted a comment.

After including GSL library path to the LIBRARY_PATH environment variable (along with the others: PATH (bin), LD_LIBRARY_PATH and LD_RUN_PATH (lib), C_INCLUDE_PATH and CPLUS_INCLUDE_PATH (include)), compilation still crashes.

This time, instead of requesting -lgsl it request -lcblas. Isn't cblas part of the gsl package? In the GSL lib folder I have the following files (and links):

libgsl.a
libgslcblas.a
libgslcblas.la
libgslcblas.so -> libgslcblas.so.0.0.0
libgslcblas.so.0 -> libgslcblas.so.0.0.0
libgslcblas.so.0.0.0
libgsl.la
libgsl.so -> libgsl.so.0.17.0
libgsl.so.0 -> libgsl.so.0.17.0
libgsl.so.0.17.0
pkgconfig

Is it a naming problem? Should I rename libgslcblas to libcblas?

Thanks again for your time.

**Comment by jmarshall** [comment]
This is not really a bcftools issue*.  Problems building these tools in particular environments would be better posted to the [samtools-devel mailing list](https://lists.sourceforge.net/lists/listinfo/samtools-devel), where lots of people can help you, or discussed with your local system administrators.

In any case:  see the [GSL documentation](http://www.gnu.org/software/gsl/#related).  To use the default CBLAS library supplied with GSL you should probably change the bcftools Makefile to say

    GSL_LIBS = -lgsl -lgslcblas

<small>* Except insofar as when we add a `configure` script, it could check for libgsl / libcblas and advise appropriately.</small>
