### ISSUE TITLE
DTD problem with manpage xml file

### ISSUE THREAD

**Issue by kotoroshinoto** [samtools/bcftools#270]
cd doc && a2x -adate="2015-06-02 03:45 EDT" -aversion=1.2+ --doctype manpage --format manpage bcftools.txt
a2x: ERROR: "xmllint" --nonet --noout --valid "/UCHC/HPC/Gooch/biotoolmodules/samtools/bcftools/src/bcftools/doc/bcftools.xml" returned non-zero exit status 4
Makefile:165: recipe for target 'doc/bcftools.1' failed
make: *** [doc/bcftools.1] Error 1

tried running command manually 

-bash-4.1$ "xmllint" --nonet --noout --valid "/UCHC/HPC/Gooch/biotoolmodules/samtools/bcftools/src/bcftools/doc/bcftools.xml"
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/UCHC/HPC/Gooch/biotoolmodules/samtools/bcftools/src/bcftools/doc/bcftools.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
/UCHC/HPC/Gooch/biotoolmodules/samtools/bcftools/src/bcftools/doc/bcftools.xml:5: validity error : Validation failed: no DTD found !
<refentry lang="en">
                   ^

**Comment by pd3** [comment]
Hi,
this looks like a problem with your asciidoc installation. Anyway, there should be no need to run a2x, as the doc/bcftools.html in your distribution should correspond to the doc/bcftools.txt template and the doc/bcftools.1 man page.

**Comment by dbrawand** [comment]
I have the same problem on a clean ubuntu 14.04 install (VM).
Samtools and htslib compile fine.
