### ISSUE TITLE
enhancement: make it possible to filter out samples that don't hold a non-reference allele

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#275]
It would be cool, if it was possible to filter out samples, that don't hold a non-reference allele for a single (or multiple) variants. For example I would only want samples 2 and 3 printed if the genotypes for 2 variants were as follows.

sample1 0/0 0/0
sample2 0/0 1/1
sample3 1/1 1/1

The loop could be broken in the case that all samples hold a non-reference allele. Does the bcftools architecture allow this to be easily implemented?

**Comment by FrankFeng** [comment]
Hi @tommycarstensen ,

Maybe you could try with `--min-ac 1' like this:
```
bcftools view --min-ac 1 <in.vcf.gz>
```

**Comment by pd3** [comment]
In order to produce a valid VCF, this cannot be done when VCF is output. However, with the `query` command it is now possible, see dd30ebfa65d58828866cc36d218acc9a94a5347d
