### ISSUE TITLE
Can someone please explain why plugin +dosage prints non-standard VCF header?

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#277]
Hi, 
The `dosage` plugin prints a non-standard `#CHROM` line to the output VCF.  For example:

    printf("#[1]CHROM\t[2]POS\t[3]REF\t[4]ALT");

Why are the column numbers included here?

**Comment by pd3** [comment]
This output is not a VCF but a plain text file. There is no special reason for the column numbering, it's a convenience adopted from similar textual outputs used by bcftools: if there are many columns, it helps to `awk` and `cut` relevant fields.

**Comment by wkretzsch** [comment]
Ok, thanks.

**Comment by wangfan860** [comment]
hello, i'm wonder in `bcftools +dosage` function, it looks like the output only contains [1]CHROM\t[2]POS\t[3]REF\t[4]ALT and samples' dosage. Is there a way to keep some column (eg,. ID, INFO) in the output file? thank you so much!
