### ISSUE TITLE
Viterbi training fails in bcftools roh

### ISSUE THREAD

**Issue by gtamazian** [samtools/bcftools#278]
I tried to perform Viterbi training for HMM transition probability estimation using the `-V` option in **bcftools roh**. However, it failed with the following error: *fixme: state 1 not observed*. From the source code (the function **flush_viterbi** in **vcfroh.c**), it seems that either this error message was accidentally left in the code or the code is still to be modified.

**Comment by pd3** [comment]
This should be fixed in 3ba5f38ced4e3938348fa231a2f3d794ee43bc5a, thank you for reporting the bug.
