### ISSUE TITLE
bcftools norm -m + merge_format_numeric assertion failed

### ISSUE THREAD

**Issue by kauralasoo** [samtools/bcftools#282]
Hi,

I am trying to use bcftools norm to merge multiple overlapping biallelic variants into a single multiallelic one. However, when I try to run
```
bcftools norm -m+ sample.vcf.gz > multi.vcf
```
I get the following error message:
> bcftools: vcfnorm.c:1398: merge_format_numeric: Assertion `nvals2==lines[i]->n_allele || nvals2==lines[i]->n_allele*(lines[i]->n_allele+1)/2' failed.
> Aborted

I suspect that there might be something wrong with my VCF file, but there are not many details in the error message. What might be the cause of this error and what would be the easiest way to identify the offending line in the VCF file?

I'm happy to send the VCF file by e-mail.

Best,
Kaur

**Comment by mcshane** [comment]
Hi Kaur. Thanks for reporting the issue, could you send the VCF (at least with a section with the relevant lines) for us to debug?

**Comment by kauralasoo** [comment]
Hi Shane,

Sorry for the delay. Here is a minimal VCF file that will reproduce the issue:

##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GP,Number=G,Type=Float,Description="Genotype Probabilities">
##FORMAT=<ID=GC,Number=1,Type=Float,Description="GenCall score">
##FORMAT=<ID=IA,Number=1,Type=Float,Description="Intensity of the A Allele">
##FORMAT=<ID=IB,Number=1,Type=Float,Description="Intensity of the B Allele">
##FORMAT=<ID=BAF,Number=1,Type=Float,Description="B Allele Frequency">
##FORMAT=<ID=LRR,Number=1,Type=Float,Description="Log R Ratio">
##FORMAT=<ID=PQ,Number=1,Type=Integer,Description="Phasing Quality (bigger is better)">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phase Set">
##contig=<ID=11,length=2147483647>
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=IMP2,Number=3,Type=Float,Description="IMPUTE2 scores: exp_freq_a1, info, certainty">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1	sample_2
11	48245184	rs7120775	C	G	.	PASS	AC=9;AN=62;IMP2=0.171,0.984,0.995	GT:GP:GC:IA:IB:BAF:LRR:PS	0|0:1,0,0:0.7902:1.837:0.012:0.0005:-0.057:61395	0|0:1,0,0:0.7902:1.78:0.019:0.0033:-0.0997:61395
11	48245184	.	C	G	.	PASS	AC=9;AN=62;IMP2=0.171,0.984,0.995	GT:LRR:BAF:IA:IB:GC:PS	0/0:-0.057:0.0005:1.837:0.012:0.7902:61395	0/0:-0.0997:0.0033:1.78:0.019:0.7902:61395

Best,
Kaur

**Comment by tommycarstensen** [comment]
I have the same problem with version 1.2. This command fails with the same error message:
bcftools norm -m +any triallelic.1000156.vcf.gz

File with 2 biallelic VCF records for sample NA12878 is here:
www.tommycarstensen.com/triallelic.1000156.vcf.gz

**Comment by mcshane** [comment]
Thanks both for the test cases.

@tommycarstensen your problem is already fixed on the develop branch.

@kauralasoo your test case is fixed by 942fbd20eb523c8898b93227a9cd8592a66979a3. Please let us know if it does not work in any other cases.

**Comment by dheerajbobbili** [comment]
Hi,

I am getting this error message. Is there a way to merge irrespective of INFO field and FORMAT field ??
merge_format_genotype: Assertion `ngts==ngts2' failed.
