### ISSUE TITLE
Filter positions with missing ALT

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#283]
I'd like to filter out positions that have no ALT i.e.

`bcftools view -i 'ALT[0]!="."' tmp.vcf`
`bcftools view -i 'ALT[*]!="."' tmp.vcf`
`bcftools view -i 'ALT!="."' tmp.vcf`

The results don't seem to be filtered. It works fine if supplement ALT for ID. Ideas?

**Comment by dwaggott** [comment]
This is still possible using built in `-m` flag.

`bcftools view -m 2 tmp.vcf`

**Comment by pd3** [comment]
This should work with recent github versions(https://github.com/samtools/bcftools/commit/8cc5c49ad979f58d718b917543393b44a59dc1f6):

    bcftools view -i 'ALT!="."' tmp.vcf

**Comment by mcshane** [comment]
This does appear to work with the latest develop. Please reopen if it doesn't work for you.
