### ISSUE TITLE
bcftools view option equivalent to awk '$5 != "<X>"'

### ISSUE THREAD

**Issue by sjackman** [samtools/bcftools#288]
Is there a `bcftools view` option that is equivalent to `awk '$5 != "<X>"'`?

**Comment by mcshane** [comment]
(requires the develop branch)
```
bcftools view -e 'ALT="<X>"' test/mpileup.vcf
```
or
```
bcftools view -e 'ALT~"<X>"' test/mpileup.vcf
```
if you want to match any allele in the ALT column.

**Comment by sjackman** [comment]
Thanks! Is there a stable release expected any time soon? Perhaps the milestone for this issue could be tagged `1.3`.

**Comment by sjackman** [comment]
Is there similarly an equivalent command to extract all the C>U (ref = C and alt = U) sites?

**Comment by sjackman** [comment]
`bcftools view -i 'REF="C" && ALT~"T" test/mpileup.vcf`

**Comment by sjackman** [comment]
`bcftools view -e 'ALT="<X>"'` worked just fine for me with bcftools 1.2. Why do you think it requires the develop branch?

**Comment by mcshane** [comment]
You're right. The recent change I had in mind was if you want to query for `ALT="."`
