### ISSUE TITLE
asciidoc xmllint xsltproc

### ISSUE THREAD

**Issue by jwhsanger** [samtools/bcftools#289]
Hi Guys,

I have just noticed that there is an install dependency on asciidoc, xmllint and xsltproc which dont appear to be standard libraries (on Ubuntu at least) and which need installing separately. This adds complication for users that dont have root access. Additionally the the make tests pass without indicating these libraries are required for the install. 

Was this intentional? I have to admit this is the first package that has failed to install due to missing documentation dependences so this maybe more normal than I think.

**Comment by pd3** [comment]
The man page and the html document is shipped together with the asciidoc template, so there should be no need to run asciidoc. That was the idea, anyway. This should work: `touch doc/bcftools.1 && make install`.
