### ISSUE TITLE
norm split multiallelic error

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#290]
It only happens when I use `-m -`, ideas?

```
bcftools norm -f GRCh37.fa -m - test.vcf > test2.vcf

bcftools: vcfnorm.c:385: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted
```

[test.vcf](https://gist.github.com/55bfcc61531e406fb9ac)

**Comment by pd3** [comment]
The VCF has incorrect number of AO fields, the tag is defined as Number=A, but fewer values are present. The vcf-validator complains:
`1:10177 .. FORMAT tag [AO] expected different number of values (expected 2, found 1)`

**Comment by dwaggott** [comment]
Thanks, I'll file a ticket with the tool.

Is the vcf-validator available for use? 

Beyond malformed, I'm regularly running into files where a single row is truncated.

**Comment by pd3** [comment]
Latest htslib versions check for missing eof gbzf block (https://github.com/samtools/htslib/commit/58358e1514a1d7317a5f8296c1837685a19a467d), the file has to be compressed for this.

The vcf-validator comes with the vcftools package (https://github.com/vcftools/vcftools/blob/master/perl/vcf-validator).
