### ISSUE TITLE
Identify positions where the most likely genotype is 1/1 (hom alt) for any sample

### ISSUE THREAD

**Issue by sjackman** [samtools/bcftools#291]
I created a VCF.gz file using `samtools mpileup -vf foo.fa a.bam b.bam c.bam …`. I'd now like to use `bcftools view` to identify positions where the most likely genotype is homozygous alternate (1/1) for any of the samples.

I'm trying to identify sights of C-to-U RNA editing, so I'm looking for positions where REF is C, ALT is T, and the most likely genotype is T/T.

My question is probably really basic, and so I apologize in advance. I wasn't able to figure out the answer from the documentation. Thank you for your help.

**Comment by pd3** [comment]
Would this do? `bcftools view -i'PL[2]<PL[1] & PL[2]<PL[0] & REF="C" & ALT~"T"'`. Alternatively, you could query the genotypes instead, by putting GT="1/1" in the query.

By the way, typically only some of the transcripts are edited, so searching for homs only would be too restrictive. This is true in the case of A-to-I type of RNA editing, not sure about C-to-U.

**Comment by sjackman** [comment]
I came up with a solution that looks like this:
```sh
samtools mpileup -vf ref.fa foo.bam |bcftools call -mv |vcf-to-tab |grep -c '\tC\t.*T/T'
```

Can the last the `vcf-to-tab` and `grep` be replaced with `bcftools view`?

**Comment by sjackman** [comment]
How do I filter out genotype calls that are low quality for a particular sample, and replace those low-quality genotypes with say `./.`?

**Comment by sjackman** [comment]
How do I replace heterozygous genotype calls with `./.`?

**Comment by pd3** [comment]
The `filter` command can replace with "." rather than "./.", if that's enough:

    bcftools filter -S . -e 'FMT/GT="0/1" || FMT/GT="1/0"'

RE the editing, check also for the complements, that the editing can occur on the non-reference strand.

**Comment by sjackman** [comment]
Thank you. That was very helpful. To use the above filter you must first select only biallelic sites:
`bcftools view -m2 -M2 -v snps |bcftools filter -S . -e 'FMT/GT="0/1" || FMT/GT="1/0"' |bcftools view -a |bcftools view -Oz -m2`

**Comment by sjackman** [comment]
I also found this filter very useful to select only sites and genotypes with quality at least 50.

`bcftools filter -S . -e 'QUAL < 50 || FMT/GQ < 50' $< |bcftools view -a |bcftools view -m2 -Oz`

Is there a way to accomplish this filter with fewer pipes?

**Comment by sjackman** [comment]
For the curious, here's my pipeline to call and filter high-quality biallelic SNVs:

```sh
samtools mpileup -vf x.fa a.bam b.bam c.bam >x.vcf.gz
bcftools call -mvf GQ,GP -Oz x.vcf.gz >x.gt.vcf.gz
bcftools filter -S . -e 'QUAL < 50 || FMT/GQ < 50' x.gt.vcf.gz |bcftools view -a |bcftools view -m2 -M2 -v snps -Oz >x.gt.qual.vcf.gz
```

**Comment by sjackman** [comment]
To filter only homozygous SNV add `-e 'FMT/GT="0/1" || FMT/GT="1/0"` to the filter.
