### ISSUE TITLE
An error message: bcftools norm 

### ISSUE THREAD

**Issue by yangjunhuicq** [samtools/bcftools#293]
hi, dear all
  I encountered a error when using bcftools norm to split multi-allelic variants calls into separate lines. 
  My workflow is: First, GATK HaplotypeCaller is used to call variants for each sample, so I have 3 VCF files.   Second, vcf-merge is used to merge the 3 VCF files, so I have a total vcf named merge.vcf.   Third, bgzip is used to compress merge.vcf and tabix is used to index merge.vcf.gz.   Finally, bcftools norm is used to split multi-allelic variants calls into separate lines in merge.vcf.gz.
  The first three steps successed. The last step failed and reported the following error:
        bcftools norm -m -both -o snp.merged_s.vcf snp.merged.vcf.gz
        bcftools: vcfnorm.c:706: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
        Aborted
  
  I also tested the above workflow using SAMtools mpileup and bcftools instead of GATK HaplotypeCaller for variants calling in the first step, and all steps successed.

  I further tested another workflow: GATK HaplotypeCaller is used to call variants for one sample, so I have one VCF file for this sample.   Then, bgzip is used to compress sample1.vcf and tabix is used to index sample1.vcf.gz.   Finally, bcftools norm is used to split multi-allelic variants calls into separate lines in sample1.vcf.gz.   It successed.

  I tried to find the reason but felt difficult. Is there anyone can help?
  Thanks very much.

**Comment by pd3** [comment]
Hi, you should use `bcftools merge` rather than `vcf-merge`. The error you are getting probably comes from incorrect number of values in Number=A or Number=R type of tags. The assert should be replaced with an error message, you are not the first one to encounter it, sorry.

**Comment by yangjunhuicq** [comment]
Thank you very much, pd3. I tried bcftools merge, and it succeeded! 
Then, I have another question: what is the difference between bcftools merge and vcf-merge?

**Comment by pd3** [comment]
vcf-merge is an older version written in perl. It is much slower and not developed any more. Glad this helped, closing the issue now.
