### ISSUE TITLE
bcftools annotate problem for FORMAT

### ISSUE THREAD

**Issue by hurleyLi** [samtools/bcftools#294]
Hi, I was trying to add annotations to existing vcf files. It works fine with INFO field, but when it came to FORMAT, it always through out errors : The tag "FMT/BAR" is not defined in anno.tab.gz

for trial runs, I used the same tabixed tab-delimitated annotation files anno.tab.gz for adding INFO and FORMAT
```
$ zcat anno.tab.gz
chrM	194	194	AA	11
chrM	195	195	AA	22
chrM	196	196	AA	33
chrM	310	310	BB	44
```
The header file I used for adding INFO is:
```
$ cat header.info.txt
##INFO=<ID=FOO,Number=1,Type=String,Description="Some description">
##INFO=<ID=BAR,Number=1,Type=Integer,Description="Some description">
```
The command is:
```
bcftools annotate -a anno.tab.gz -h header.info.txt -c CHROM,FROM,TO,FOO,BAR test.vcf
```
And it worked fine. 

The header file I used for adding FORMAT is:
```
$ cat header.format.txt
##FORMAT=<ID=FOO,Number=1,Type=String,Description="Some description">
##FORMAT=<ID=BAR,Number=1,Type=Integer,Description="Some description">
```
The command is:
```
bcftools annotate -a anno.tab.gz -h header.format.txt -c CHROM,FROM,TO,FMT/FOO,FMT/BAR test.vcf
```
But it returned with this error:
```
The tag "FMT/FOO" is not defined in anno.tab.gz
```
I'm using bcftools 1.2
Any help would be very appreciated!

Thanks!
This is my first post at GitHub, by the way
Cheers!

Hurley

**Comment by pd3** [comment]
Hi Hurley, 

FORMAT fields can be currently carried over only from a VCF. Sorry for the uninformative error message.

Petr

**Comment by BJWiley233** [comment]
I am assuming this is still true?

**Comment by pd3** [comment]
It is possible now, see for example the test included with bcftools source distribution:
```
bcftools annotate -a test/annotate15.tab.gz -h test/annotate15.hdr -s SAMPLE2 -c CHROM,FROM,TO,FMT/FOO,BAR test/annotate15.vcf
```

**Comment by BJWiley233** [comment]
Thanks.  I came back to this few days later.  I completely forgot the header and got same error message and could figure out why.  The error message really is informative if you just don't have a header.

**Comment by pd3** [comment]
I extended the error message, hopefully that will prevent future confusion.
