### ISSUE TITLE
bcftools norm error?

### ISSUE THREAD

**Issue by mikecho95** [samtools/bcftools#303]
Trying to clean up a file with lots of multiallelics with no support for an allele, e.g:
REF A  ALT T,C  where all genotypes are 0/2.
Thought norm should handle this but it exits with this error: 
bcftools norm myFile.bcf -m - 

bcftools: vcfnorm.c:739: split_info_string: Assertion `ret>0' failed.

**Comment by mcshane** [comment]
I'm not able to reproduce this. It will likely have something to do with what INFO tags you have in that record. Could you send a full example record for which this is failing? Also, what version of bcftools are you using?

**Comment by mikecho95** [comment]
Thanks.  Version: 1.2 (using htslib 1.2.1)
I have a small file which fails - can I send it to you?

**Comment by jmarshall** [comment]
> can I send it to you?

Yes please — @mcshane's email address is in his profile and/or mine is [here](https://github.com/samtools/samtools/blob/develop/test/vcf-miniview.c#L5).

**Comment by mcshane** [comment]
Your INFO/ReqIncl tag is not correct in the header based on how you are using it the the body of the VCF. Instead of `Number=.,Type=String` it should be `Number=0,Type=Flag`.
```
##INFO=<ID=ReqIncl,Number=0,Type=Flag,Description="Site was required to be included in the VCF">
```
Why ReqIncl was parsed without error should be raised as a separate issue in htslib. And/or hts-specs as to whether `Number=.` should explicitly exclude 0 length values and then `bcf_get_info_values` should probably return -1 for a clash between types defined in the header and encountered in the VCF record and the vcfnorm assert should be changed to an error to indicate this error.

**Comment by mikecho95** [comment]
Thanks Shane.

**Comment by roozbeh73** [comment]
I have exactly the same issue when running bcftools norm. Is there anyway I could check for such errors? I used vcf-validator but it does not complain about anything in the VCF file.

**Comment by pd3** [comment]
Any chance you could narrow the bug down and provide a small test case to reproduce the error?

**Comment by wavefancy** [comment]
I have the same problem when I run the bcftools norm:

bcftools norm -m - --check-ref e -f /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta bug.test.vcf.gz >out.bug.test.vcf.gz
bcftools: vcfnorm.c:685: split_format_string: Assertion `ret>0' failed.

#The test file can be found below:
https://www.dropbox.com/s/3v468f3augejowk/bug.test.vcf.gz?dl=0

# bcftools version:
bcftools -v
bcftools 1.5
Using htslib 1.

Thanks much for the help.

Best regards,
Wallace

**Comment by wavefancy** [comment]
> I'm not able to reproduce this. It will likely have something to do with what INFO tags you have in that record. Could you send a full example record for which this is failing? Also, what version of bcftools are you using?

This can be reproduced by below test vcf:
https://www.dropbox.com/s/3v468f3augejowk/bug.test.vcf.gz?dl=0

#bcftools -v
bcftools 1.5
Using htslib 1.5

Thanks much for the help.

**Comment by pd3** [comment]
This is now fixed via 3a40844. Thank you for providing the test case.

**Comment by rashmijain20** [comment]
Hello, I am getting the same issue when running bcftools norm.

[W::bcf_hdr_check_sanity] PL should be declared as Number=G
Assertion failed: (nvals_ori>0), function merge_info_numeric, file vcfnorm.c, line 965.
Abort trap: 6

Please help me to solve this issue.

Thanks for your help!

Rashmi

**Comment by pd3** [comment]
You are most likely using an older version of bcftools, please try with the newest version http://samtools.github.io/bcftools/howtos/install.html.

In any case, the cryptic error message gives a useful hint: the FORMAT/PL tag is not declared as Number=G in the header, it is very likely this is the cause of the problems downstream.

**Comment by rashmijain20** [comment]
Thank you for the answer, I downloaded a new version and there is no more error.

Regards,
Rashmi
________________________________
