### ISSUE TITLE
bcftools make error

### ISSUE THREAD

**Issue by lgershony** [samtools/bcftools#304]
Hi there,

I managed to install htslib 1.2 (and a folder for it was created in the samtools 1.2 folder) and samtools is running for generating and sorting/indexing bam files, but when I try to run variant calling it tells me "bcftools command not found"

I've been trying to install bcftools 1.2 but keep getting the same error message "Makefile:173: recipe for target 'bcftools' failed". 

Any help will be much appreciated!

Thanks!

**Comment by jmarshall** [comment]
It would appear that bcftools compilation had already failed.  You would need to look at the messages from the compiler preceding the make error messages to track down what has happened.

Problems like this with building these tools in particular environments are probably easier to solve by posting to the [samtools-devel mailing list](https://lists.sourceforge.net/lists/listinfo/samtools-devel), where lots of people can help you, or by discussing them with your local system administrators, who can look at the error messages directly.

**Comment by jmarshall** [comment]
No further feedback provided.  Hopefully the problem has been resolved, or this can be reopened (or posted to the mailing list) with a more complete error log.
