### ISSUE TITLE
bcftools consensus bug

### ISSUE THREAD

**Issue by bioprog** [samtools/bcftools#306]
Hi,
I'm pretty sure this is a bug resulting from something like a for loop in consensus.c where something is not checked/done after the last iteration.

I have a reference sequence that ends with a couple of "N"s. Exactly 1 read covers ALL sites of that N region (and some sites before the N region). No other read reaches into that N region.

Note: The situation was set up by me with test data on purpose to do some checks on bcftools' consensus behaviour.

When you call the consensus, bcftools fills the sites within the N region with the the nucleotide of that 1 read which covers it.

However at the LAST position it puts an N into the consensus instead of the nucleotide from the read (a T in my case).
When I check the output of 'bcftools call' via 'bcftools view', I see that the scores are all the same in that N region sites (as expected because they are all subject to the same conditions [i.e. 1 read covering the site ... oh and the quality of every base is the same in my test data]). It's only that last position which gets assigned an N in the consensus instead of the read base.

**Comment by pd3** [comment]
Hi,
any chance you could provide a small test case? From your description it is not clear whether the problem lies on the calling side or on the consensus side.

**Comment by bioprog** [comment]
Alright here's an example:

$ cat tmp_ref.fasta
>myseq_contig1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNCCTCGGAAACTCTTAATGGCACATAAACGACCGAATCAATGACTCACCTT
TGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAATCCAAGGTCT
CAGACCACTTCGGACCGAGATGCTTCGCATNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

$ cat reads.fastq
@left_overhang
ACGTACGACTGACTGAGCGGGCGCATCTATTGCATTCGATCGGAACGATCGATCGACAGCGACTAGCATCCCTCGGAAACTCTTAATGGCACATAAACGA
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@read71_171
CCTCGGAAACTCTTAATGGCACATAAACGACCGAATCAATGACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAA
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@read91_191
ACATAAACGACCGAATCAATGACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAATCCAAGGTCTCAGACCACTT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@read111_211
GACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAATCCAAGGTCTCAGACCACTTCGGACCGAGATGCTTCGCAT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@right_overhang
TCCAAGGTCTCAGACCACTTCGGACCGAGATGCTTCGCATCCGAGTATCTCGGCAAAGTTATAGGCGTGGGGGCTACGCTCCAAGGCGTTATTTACTTAT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

The 3 reads in the middle match the reference with 100% identity at the positions indicated (the read "@read71_171" matches from 71 to 171 ... etc ...).
71 is where the non-N-region starts. 211 (name of the 3rd read: "@read111_211") is where the non-N-region ends.
Thus those 3 reads span the non-N-region.

Now to the 2 "overhang" reads:

The LAST 30 bases of the read "@left_overhang" match the FIRST 30 bases of "@read71_171" (thus the first 30 bases of the non-N-region). So the first 70 bases of that read overlap the N-region at the start of the reference.

The FIRST 40 bases of "@right_overhang" match the LAST 40 bases of the non-N-region. So the last 60 bases of that read overlap the N-region at the end.

Now the commands (You can just copy them into a script and execute it, it will show you the consensus in the terminal [assuming you have copied the reads and the reference into the according filenames beforehand]):
bwa index tmp_ref.fasta
bwa mem tmp_ref.fasta reads.fastq > tmp.sam
samtools view -h tmp.sam | samtools mpileup -B -vf tmp_ref.fasta - | bcftools call -Mm -Oz -o calls.vcf.gz -
bcftools tabix -f calls.vcf.gz
bcftools consensus -f tmp_ref.fasta calls.vcf.gz

This results in a consensus sequence that shows you "N"s in the regions, where I want to have the bases of the overhangs.
But the overhangs get SOFT-CLIPPED (you can see it in the CIGAR string in the tmp.sam file).

So I just modify that tmp.sam file via a script and do the following:
I replace the CIGAR strings from 70S30M ("@left_overhang") and 40M60S ("@right_overhang") to 100M. Furthermore I change the start position (column 4 in tmp.sam) of "@left_overhang" from 71 to 1 (The start of "@right_overhang" stays the same).

The resulting tmp_edited.sam file looks like this:

@SQ	SN:myseq_contig1	LN:270
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem tmp_ref.fasta reads.fastq
left_overhang	0	myseq_contig1	1	60	100M	*	0	0	ACGTACGACTGACTGAGCGGGCGCATCTATTGCATTCGATCGGAACGATCGATCGACAGCGACTAGCATCCCTCGGAAACTCTTAATGGCACATAAACGA	JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ	NM:i:0	MD:Z:30	AS:i:30	XS:i:0
read1_101	0	myseq_contig1	71	60	100M	*	0	0	CCTCGGAAACTCTTAATGGCACATAAACGACCGAATCAATGACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAA	JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ	NM:i:0	MD:Z:100	AS:i:100	XS:i:0
read21_121	0	myseq_contig1	91	60	100M	*	0	0	ACATAAACGACCGAATCAATGACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAATCCAAGGTCTCAGACCACTT	JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ	NM:i:0	MD:Z:100	AS:i:100	XS:i:0
read41_141	0	myseq_contig1	111	60	100M	*	0	0	GACTCACCTTTGTCCGAGTCTCTAACCGTTTAAGGTGAATTAACATACCGGGGAGGTGAATCCAAGGTCTCAGACCACTTCGGACCGAGATGCTTCGCAT	JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ	NM:i:0	MD:Z:100	AS:i:100	XS:i:0
right_overhang	0	myseq_contig1	171	60	100M	*	0	0	TCCAAGGTCTCAGACCACTTCGGACCGAGATGCTTCGCATCCGAGTATCTCGGCAAAGTTATAGGCGTGGGGGCTACGCTCCAAGGCGTTATTTACTTAT	JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ	NM:i:0	MD:Z:40	AS:i:40	XS:i:0

If I call the consensus pipeline as above (only replacing "samtools view -h tmp.sam" by "samtools view -h tmp_edited.sam") I get the desired result: The bases in the N-region are the bases of the read. EXCEPT for the last position.

**Comment by pd3** [comment]
Thank you for the example! I just pushed a commit which should fix it f2ced39
