### ISSUE TITLE
all variants skipped in bcftools roh

### ISSUE THREAD

**Issue by zd1** [samtools/bcftools#307]
Dear bcftools developers, 

I had a problem with running roh sub module as I had all variants skipped.

here is an example variant

    1	897325	.	G	C	2965	PASS	FILTS;1000Genomes_AF=0.859225	GT:GL:GQ:NR:NV	1/1:-256,-21.02,0:100:78:71

I don't have AC nor AN in the INFO but I have "1000Genomes_AF".  I tried a few options because of this: (1) make a variant list as suggested by the documentation 
 bcftools query -f'%CHROM\t%POS\t%REF,%ALT\t%INFO/TAG\n' file.vcf | bgzip -c > freqs.tab.gz
and then use --AF-file or (2) use --AF-TAG 1000Genomes_AF. 

Either case I had this variant skipped according to the message 
"Number of lines: total/processed: 64216/0"

Could you advise how to solve this problem?

Thank you, 

Zhihao

**Comment by pd3** [comment]
Hi Zhihao,
by default, the program uses PL likelihoods. Either you can go with GT field via the -G option (e.g. `-G 30`) or convert GLs to PLs using `bcftools +tag2tag in.vcf -- -r --gl-to-pl`.

**Comment by zd1** [comment]
Hi Petr, thanks very much for your reply. Yes, this solves the problem. 

Best, 
Zhihao
