### ISSUE TITLE
"bcftools view  --exclude-types indels foo.vcf" does not exclude INDEL records...

### ISSUE THREAD

**Issue by pishotta** [samtools/bcftools#310]
Doesn't exclude snps either, and the exclude option (or -V) doesn't work elsewhere.  E.g.
"chr1    12479   .       GCCC    .       40.7744 .       INDEL;IDV=1 GT:PL   0/0:0" fails to
drop.  Am I missing something?

**Comment by pishotta** [comment]
Figured it out.  The "INDEL" in the INFO section indicates that the position was "considered" as an indel, but may not have been called as such. The --exclude-types option does not test that field, however, but looks at the genotype actually called and excludes on that basis, so you can get INDEL in the info field when the exclude option is actually properly filtering out called INDELs (based on genotyping).  Confusing, but not bcftools' fault.

**Comment by jmarshall** [comment]
There's an opportunity for documentation improvement here; currently there's no hint that this might be based on something other than INFO saying `INDEL`:

> **-V, --exclude-types** _snps_|_indels_|_mnps_|_other_
>    comma-separated list of variant types to exclude

(And **snps** etc should be bold not italic as they are not [metasyntactic](https://en.wikipedia.org/wiki/Metasyntactic_variable).)
