### ISSUE TITLE
filter on FORMAT fields doesn't work for type Float

### ISSUE THREAD

**Issue by mfoll** [samtools/bcftools#312]
Hi,

Here here a fake simple vcf file showing the problem: TEST3 and TEST4 format fields are the same but one is declared integer and the other float. They contain the same value.
```
##fileformat=VCFv4.1
##INFO=<ID=TEST1,Number=1,Type=Integer,Description="Test1">
##INFO=<ID=TEST2,Number=1,Type=Float,Description="Test2">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=TEST3,Number=1,Type=Integer,Description="Test3">
##FORMAT=<ID=TEST4,Number=1,Type=Float,Description="Test4">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2
chr1	1	.	A	T	100	.	TEST1=10;TEST2=10	GT:TEST3:TEST4	0/1:10:10	0/1:30:30
chr1	2	.	A	T	100	.	TEST1=50;TEST2=50	GT:TEST3:TEST4	0/1:20:20	0/1:40:40
```
Filtering on these values give different results. The result is correct when filtering on FORMAT/TEST3<25:
```
##bcftools_filterVersion=1.2-108-gd4d42ca+htslib-1.2.1-193-gb82f5ef
##bcftools_filterCommand=filter -S . -i FORMAT/TEST3<25 bug.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2
chr1	1	.	A	T	100	PASS	TEST1=10;TEST2=10	GT:TEST3:TEST4	0/1:10:10	./.:30:30
chr1	2	.	A	T	100	PASS	TEST1=50;TEST2=50	GT:TEST3:TEST4	0/1:20:20	./.:40:40
```
but incorrect for FORMAT/TEST4<25:
```
##bcftools_filterVersion=1.2-108-gd4d42ca+htslib-1.2.1-193-gb82f5ef
##bcftools_filterCommand=filter -S . -i FORMAT/TEST4<25 bug.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2
chr1	1	.	A	T	100	PASS	TEST1=10;TEST2=10	GT:TEST3:TEST4	0/1:10:10	0/1:30:30
chr1	2	.	A	T	100	PASS	TEST1=50;TEST2=50	GT:TEST3:TEST4	0/1:20:20	0/1:40:40
```

This doesn't happen for INFO field, where filtering on TEST1 or TEST2 give the same correct results.

**Comment by jmarshall** [comment]
So the difference between TEST3 and TEST4 appears to come down to: when `tok->idx < 0`, `filters_set_format_float` doesn't set `tok->nsamples` to anything (leaving it as 0) whereas `filters_set_format_int` does…  …which would appear to be a bug in `filters_set_format_float()`.

**Comment by pd3** [comment]
Yes, that's the correct fix. Thanks for reporting the bug.

**Comment by mfoll** [comment]
Thanks, it works perfectly. Such a responsive support is greatly appreciated!
