### ISSUE TITLE
Incorrect filter name being added to FILTER column with bcftools filter

### ISSUE THREAD

**Issue by Takadonet** [samtools/bcftools#317]
Having issue with some bcf.gz files generated from samtools mpileup/bcftools call where value for FILTER column is not being added correctly. It seems to depend on what you need your flag.

So the following two commands will add 'HWE' instead of their respectful names
i.e
bcftools filter -s 'coverage' -i 'DP>=30' mpileup.bcf.gz -O b > results.bcf.gz
bcftools filter -s 'c' -i 'DP>=30' mpileup.bcf.gz -O b > results.bcf.gz

with following entries.

gi|873258195|gb|CP012021.1|     1       .       G       .       71.9944 HWE     DP=14;etc
gi|873258195|gb|CP012021.1|     2       .       T       .       71.9944 HWE     DP=14;etc

However, if i use the same command with 'beer' as the filter name it works!
i.e
bcftools filter -s 'beer' -i 'DP>=30' mpileup.bcf.gz -O b > results.bcf.gz

with following entries.
gi|873258195|gb|CP012021.1|     1       .       G       .       71.9944 beer    DP=14;etc
gi|873258195|gb|CP012021.1|     2       .       T       .       71.9944 beer     DP=14;etc

Input file @ https://www.dropbox.com/s/2g2iyf72ezs3vkq/mpileup.bcf.gz?dl=0

It works correctly if input file is vcf.

**Comment by Takadonet** [comment]
Issue above is one of many cases where it seems that the hashing of the column and ID is off.  Hope it will resolve all of them with a single fix.

**Comment by pd3** [comment]
Hi, this is caused by incorrect handling of string dictionary in BCF headers: The tags in BCF are represented as pointers to this dictionary, when BCF is modified multiple times (some tags removed, other added), new tags may have incorrect IDs assigned. I'll post here once it is fixed. Thanks for reporting the bug and the test case.

**Comment by pd3** [comment]
This fixes the issue https://github.com/pd3/htslib/commit/6876a073607a66b9cc4f49cd164b2624d8efe219

**Comment by Takadonet** [comment]
Sweet, Will give it a try right now

**Comment by Takadonet** [comment]
Works. Thanks for the fix. Any plan to merge into main branch(s)?
