### ISSUE TITLE
Dropping alternative alleles for complex VCF records with view --trim-alt-alleles

### ISSUE THREAD

**Issue by chapmanb** [samtools/bcftools#319]
When using `bcftools view --trim-alt-alleles` to remove extra alleles from FreeBayes output, some complicated cases end up dropping all alternative alleles and not correctly adjusting the genotype. These are quite complex records from calling low frequency variants, but seem to be valid. Here is a small example with three records. The second is the problem record and the first and third are manually edited derivatives that work:

https://gist.github.com/chapmanb/45cd8f41dec9a1adc1f4
```
$ bcftools view --trim-alt-alleles drop_during_trim.vcf
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##bcftools_viewVersion=1.2+htslib-1.2
##bcftools_viewCommand=view --trim-alt-alleles drop_during_trim.vcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SRR1528791
chr7    142459798       .       CCATCTCTCTGCCCA CCATCTCTCTCCCCG .       .       AC=2;AN=2       GT      1/1
chr7    142459798       .       CCATCTCTCTGCCCA .       .       .       AN=2    GT      2/2
chr7    142459798       .       CCATCTCTCTGCCCA CCATCTCTCTCCCCG .       .       AC=2;AN=2       GT      1/1
```
Both the first and third example have  a single alternative allele dropped. The last one is a duplicate, but removing middle alleles also fixes it although I haven't been able to come up with an example from scratch that will fail. I'd be happy for any suggestions or thoughts on debugging further. Thanks much.

**Comment by mcshane** [comment]
This is a problem in htslib where the bcf_remove_alleles function is using an int bitmask to store which alleles need removing. You have more than 32 alleles so bad things are happening.

**Comment by chapmanb** [comment]
Brilliant, thanks so much Shane.
