### ISSUE TITLE
how to remove duplicate positions with different genotypes

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#323]
Is it possible to remove duplicate positions regardless of ALT allele and GT? This is coming up in a pipeline and I didn't have much luck with `bcftools norm -D c all tmp.vcf.gz`.

Thanks!

**Comment by mcshane** [comment]
Does `bcftools norm -d any tmp.vcf.gz` do what you need? (option is only on develop at the moment)

**Comment by jmarshall** [comment]
Please re-open if there is still an issue in the current release/**develop**.  Does `-d any` help?

**Comment by pd3** [comment]
I believe the message printed by the program is correct.

**Comment by tommycarstensen** [comment]
Thanks Petr. Let's keep this ticket closed then. Have a nice weekend!
