### ISSUE TITLE
concat removing duplicate positions

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#324]
I guess this is a feature request. It would be helpful if `concat` could:

(a) had the option to ignore sample names. I'm using `concat` to add data from a generic vcf which requires constant reheadering and duplicating of large files for compatability.

(b) had the option to use `bcftools concat -aD --collapse all important.vcf generic.vcf` to remove duplication positions regardless of ALT and GT.

**Comment by mcshane** [comment]
For (b), as with #323, there is the option `-d all`, which maybe already does what you want?

**Comment by dwaggott** [comment]
Should, but would help if I can avoid intermediate files. I can pipe `bcftools concat` to `bcftools norm -d all`, right?

**Comment by jmarshall** [comment]
Yes, piping should be fine here.
