### ISSUE TITLE
bcftools roh viterbi training error: fixme: state 2 not observed

### ISSUE THREAD

**Issue by cgrossen** [samtools/bcftools#328]
I am trying to run Viterbi training for the estimation of transition probabilities (bcftools roh) as follows:
bcftools roh -m $chr.map.roh -s $sample $data.$chr.vcf --viterbi-training

and get the error message:
fixme: state 2 not observed

I am using the most recent version, so the one after the fix to this issue: https://github.com/samtools/bcftools/issues/278

Any hint to where I may be doing something wrong would be very much appreciated.

**Comment by vagheesh** [comment]
There are several options you could try

(A) turn off the viterbi training. Depending on the amount of autozygosity there is in the data you might never transition and it might error out

(B) are you correctly evaluating the allele frequencies? Is that a multi sample VCF? You'll need at least 10 or more samples from a population for the method tonwork

**Comment by cgrossen** [comment]
Thank you for your advice.

A) When turning off viterbi, there is indeed no transition to autozygosity at all (stays in state 0 throughout the entire chromosome). This is surprising because between 84% and 98% of the loci are homozygous. I would rather have expected the opposite.
I tried different map lengths, so don't think that rather low marker density (1-2 per 100kb) should be a problem?

B) Yes it is a multi sample VCF with 15 individuals.

**Comment by pd3** [comment]
Hi, is there any chance you could share a small test case? There is an email on my profile page.
