### ISSUE TITLE
Subset of samples doesn't work using "bcftools query"

### ISSUE THREAD

**Issue by kevinrue** [samtools/bcftools#331]
Hi,
@wkretzsch As suggested, I am re-posting from the other thread, please reply here.

On this simple VCF `test.vcf`:

```
##fileformat=VCFv4.1
##contig=<ID=chr1,length=135006516>
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=TEST2,Number=1,Type=Integer,Description="Test3">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1 sample2
chr1    1       .       A       T       100     .       AN=4;AC=2       GT:TEST2        0/1:10  0/1:30
chr1    2       .       A       T       100     .       AN=4;AC=1       GT:TEST2        0/0:20  0/1:40
```

when I run:
```
bcftools view -s sample1 test.vcf
```
As I expect, I see the AN and AC being updated (sample1 has only 2 calls, with ALT alleles 1 and 2 present once and absent respectively):
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1
chr1    1       .       A       T       100     .       AN=2;AC=1       GT:TEST2        0/1:10
chr1    2       .       A       T       100     .       AN=2;AC=0       GT:TEST2        0/0:20
```

However, when I perform the same operation using `bcftools query`:
```
bcftools query -s sample1 -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/AC\t%INFO/AN\n' test.vcf
```
the sample subsetting does not seem to work (again, I repeat: no warning message). The AC and AN (last two columns, in that order) match the information corresponding to the full original file, instead of the desired subset:
```
chr1    1       A       T       2       4
chr1    2       A       T       1       4
```

What I would expect is that the `query` command first subsets the original VCF, and then tabulates the information for the subset of sample.

Thanks for telling me if my command is wrong, or if it is an software bug.

Best,
Kevin

**Comment by pd3** [comment]
`query` does not recalculate the tags, it just prints what's in the VCF and strips unwanted samples. You'll have to stream through `view` first:

     bcftools view -s xxx file.vcf | bcftools query -f'etc'

**Comment by wkretzsch** [comment]
I can replicate the problem and @pd3's solution.  Perhaps it might be worthwhile to add a sentence to the `bcftools query` documentation that `bcftools query` does not recalculate tags?

**Comment by kevinrue** [comment]
I think that would be useful.

Thanks!
