### ISSUE TITLE
isec suppress vcf output

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#334]
feature request: I'd like to run isec but only need the sites.txt file for QC. An option to suppress writing the vcf/bcf would be useful.

**Comment by pd3** [comment]
This prints only list of sites, what options are you using?

     bcftools isec -n =2 a.vcf.gz b.vcf.gz
     bcftools isec -C a.vcf.gz b.vcf.gz

**Comment by dwaggott** [comment]
Oh right, that works perfectly. If the `-p` is not included stdout is just the sites.txt file. Might want to make that a bit more explicit in the docs.

A nice little bonus would be if the counts per intersection slice were included. i.e. `cut -f 6 sites.txt | sort | uniq -c`
