### ISSUE TITLE
order of operations? --sample --genotype 

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#335]
1. Does the sample subsetting happen before the row filtering by type i.e. het/hom? Querying a single sample in a multisample vcf gives all types of variants.

   `bcftools view -s 3_68_10_03  -g het tmp.bcf`

2. Also, is it possible to query homo_ref vs homo_allt?

**Comment by dwaggott** [comment]
I checked and the sample filtering seems to happen after the het filtering. Is it possible to change the order? or is this intended outcome?

**Comment by mcshane** [comment]
If you want the sample filtering before the het filtering, just do:
```
bcftools view -Ou -s 3_68_10_03 tmp.bcf | bcftools view -g het
```

**Comment by dwaggott** [comment]
Sigh, I guess that was obvious after the order was clarified. Thanks as always!
