### ISSUE TITLE
bcftools call output INFO/AD,FORMAT/AD with Number=R+1 values, Not Number=R values

### ISSUE THREAD

**Issue by wangyugui** [samtools/bcftools#338]
the type of  INFO/AD,FORMAT/AD is Number=R.
so for 1 alt allele(such as A->T), it will output 2 int values.
But now it output 3 values  and the 3th value is 0.

this problem will happen when for the last source

**Comment by mcshane** [comment]
Thanks for the bug report. Should be fixed now.

**Comment by wangyugui** [comment]
the problem is fixed in my case.
thanks for this patch.
