### ISSUE TITLE
bcftools concat option --allow-overlaps only works with VCF compressed by bgzip

### ISSUE THREAD

**Issue by mfoll** [samtools/bcftools#340]
Uncompressed VCF don't work. It might be an expected behaviour but it's not explicit from the manual.

**Comment by pd3** [comment]
Whenever multiple VCFs are read simultaneously, they must be indexed and therefore also compressed.

**Comment by mfoll** [comment]
Thanks for hint, now I see what is behind this in the manual:
> Un-indexed VCF and BCF and streams will work in most, but not all situations.
