### ISSUE TITLE
Discussion: Moving bcftools to semantic versioning

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#341]
I saw @mcshane talk about the next minor version release 1.3. It feels to me like these release numbers are pretty arbitrary.  I thought I'd put out the idea of moving Bcftools to semantic versioning as described [here](http://semver.org/).  

Semantic versioning has been heavily adopted in the fast moving Ruby community because it separates bug fixes from API changes.  In this way users can grab a release that has all the newest bug fixes, but no new features that might introduce new bugs.  The downside is that it requires the maintenance of several branches.  Since release 1.2 we have seen old features brake after the introduction of new features (I might be wrong on this, @mcshane?), and important bug fixes to 1.2 intermingled with the addition of new features (again, I might be wrong, but that has been my sense).  This is a problem that I think semantic versioning could help address. 

What do people think?

**Comment by jmarshall** [comment]
Indeed.  We are familiar with the concept, and do name upcoming versions according to the underlying ideas (perhaps not as formally as promoted in that overly-formal description).

There is an additional constraint that we've so far been able to adhere to: it is (at present) clearer for users if samtools/htslib/bcftools version numbers increase in lockstep.

I believe you are mistaken about old features breaking in general; if you have specific instances in mind, please raise those.

**Comment by wkretzsch** [comment]
Ok, this ended up being a long post.  The one sentence summary is: We need a "stable release + bug fixes" branch if we want to be able to trust analyses done with Bcftools.  

> Since release 1.2 we have seen old features brake after the introduction of new features (I might be wrong on this, @mcshane?), and important bug fixes to 1.2 intermingled with the addition of new features (again, I might be wrong, but that has been my sense)

So I should have done my research before I made the assertions before.  However, after research, I still stand by them. I searched all Bcftools issues for the string "1.2", and then I started inspecting issues from the most recent first.  I stopped looking at issues after I found the second example described below, which was the eighth issue I looked at:

#### Example 1: issue #336 
Description: *bcftools norm -m-both lost some record after about 1K records*

Here a user complains about a command that worked in `bcftools 1.2 (using htslib 1.2.1)`, but that does not work in a recent `develop` branch: `bcftools 1.2-157-g8deae27; Using htslib 1.2.1-226-g1e5c377`

#### Example 2: issue #309 
Description: *failure to parse mulitple regions passed with -r*

Here a user points out a regression that, according to @jmarshall, was introduced by a new feature in samtools/htslib#171.


### Analysis

In both examples a regression was found by users in the `develop` branch, and the bug fix was made onto the `develop` branch. In the first example it is unclear whether the regression was due to a feature addition.  However, in the second example the regression is clearly due to a recent feature addition on the `samtools/htslib develop` branch.

In the current system, if a user wants the most recent bug fixes, they have no choice but to use the `develop` branch, which is also where new features are committed to.  There is no branch for grabbing just the 1.2 features with all bug fixes.  In fact, the lack of a stable + bug fixes branch is the reason why I do not recommend using Bcftools to most potential users, even though I think Bcftools is a great tool.

I know it may well be a pain to support another set of branches, but I see no way around it if we as researchers want confidence in analyses done using Bcftools while the tool is still under such heavy development.

**Comment by jmarshall** [comment]
Yes, your question was really a request: _I would like you to do a 1.2.1 bug fix release_.

We are a small team and in general we would like to focus on one stream of development.  We're open to the idea of bug fix releases (cf htslib 1.2.1), but prefer to have regular smallish releases from **develop** — similar to what the Picard folks have always done, for example.

To be sure, both 1.2 and especially the upcoming 1.3 have not been as smallish or as quick as we would like.  We hope to improve on that in future releases.

Both of your examples have already been fixed, so will not represent a regression in 1.3 compared to 1.2.  People building **develop** need to expect it to be broken in some aspects from time to time; actual tagged releases are held to higher standards.

**Comment by wkretzsch** [comment]
> Yes, your question was really a request: I would like you to do a 1.2.1 bug fix release.

My apologies, my thinking on this was a bit unclear when I opened the issue.  

Here is what I would like to see: For the most recent minor release to have a bugfixes only branch.  For example: `1.2` gets a `1.2-bugs` branch and a `develop` branch.  The idea would be that any bug that is found in `1.2-bugs` would be fixed on `1.2-bugs` first, and then, if possible, fixed in `develop`.  Part of a new minor release would be to merge the `bugs` branch into `develop`. So for example, `1.2-bugs` is merged into `develop`, a tag `1.3` is created at `develop`, and a branch is created called `1.3-bugs` at that tag.  `1.2-bugs` would then no longer be updated.  This would allow the minor releases to mature as new bugs are found, while minimizing the changes that could introduce new bugs.

I understand the team is small.  Maybe a good alternate policy in the mean time is: "Make the change on the `develop` branch, and then also on the `bugs` branch, but only if you feel like it".  I would certainly be willing to make my changes in both places for my pull requests.
