### ISSUE TITLE
bcftools query duplicate lines not in bedfile

### ISSUE THREAD

**Issue by dbackenroth** [samtools/bcftools#342]
Hi-

I'm using bcftools query to extract allele frequencies from the 1000 genomes vcf files.  I'm getting many duplicate lines for positions with copy number genotypes (e.g., CN0, CN2) (even though they're not in my bedfile).  Here's my command:

bcftools query -R sample2.bed -f "%CHROM\t%POS\t%REF\t%ALT\t%INFO/AFR_AF\n" ../Data/1000Genomes/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

Here's  by bedfile, sample2.bed:
1	533197	533198	533198
1	568708	568709	568709
1	664009	664010	664010
1	693730	693731	693731
1	713976	713977	713977
1	713978	713979	713979
1	714001	714002	714002
1	714018	714019	714019

Here's the output I get from bcftools (note the multiple results for position 668630 and 713044, which are not in my bedfile above):

Tue Oct 27 13:05:02 Trash > bcftools query -R sample2.bed -f "%CHROM\t%POS\t%REF\t%ALT\t%INFO/AFR_AF\n" ../Data/1000Genomes/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
1	533198	C	T	0.1838
1	568709	A	G	0.4002
1	668630	G	<CN2>	0.0015
1	693731	A	G	0.208
1	668630	G	<CN2>	0.0015
1	713044	C	<CN0>,<CN2>	0,0.0303
1	713977	C	T	0.0098
1	668630	G	<CN2>	0.0015
1	713044	C	<CN0>,<CN2>	0,0.0303
1	713979	C	G	0
1	668630	G	<CN2>	0.0015
1	713044	C	<CN0>,<CN2>	0,0.0303
1	714002	C	G	0
1	668630	G	<CN2>	0.0015
1	713044	C	<CN0>,<CN2>	0,0.0303
1	714019	A	G	0.3971

The index file, ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz.tbi, is in the same directory as the vcf.  

Thanks,
Daniel

**Comment by pd3** [comment]
Hi, it seems that you hit the common problem of -R/-T, please see the description here http://samtools.github.io/bcftools/bcftools.html
