### ISSUE TITLE
calculate and output AF using AC and AN

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#345]
Is it possible to output AF using AC and AN? You can generate the values via expressions but I see no way to output as an INFO tag or annotation. Sorry if I missed something obvious.

**Comment by pd3** [comment]
Hi, I just added this functionality into the `fill-tags` plugin

      # add only AF
      bcftools +fill-tags file.vcf  -- -t AF

      # add all tags the plugin supports
      bcftools +fill-tags file.vcf

**Comment by dwaggott** [comment]
Awesome!

**Comment by dwaggott** [comment]
Not sure what happened, but I can't seem to get the plugins operational. 

BCFTOOLS_PLUGINS is set and everything looks "ok" using `bcftools plugin -lv`

LD_LIBRARY_PATH is set and running `ldd fill-tags.so` shows 
`libhts.so.1 => /srv/gsfs0/projects/ashley/apps/bcftools/htslib/libhts.so.1 (0x00007fdb92125000)`

Trying to run a plugin gives me:
 `No functional bcftools plugins were found in         BCFTOOLS_PLUGINS="/srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins/"`

Ideas?

**Comment by pd3** [comment]
Can you please provide full command lines and outputs? What is the output of `bcftools +fill-tags -v`?

**Comment by dwaggott** [comment]
Seems to work

```
$ bcftools +fill-tags -v
/srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins//fill-tags.so:
        dlopen   .. ok
        init     .. ok

About:   Run user defined plugin
Usage:   bcftools plugin <name> [OPTIONS] <file> [-- PLUGIN_OPTIONS]
         bcftools +name [OPTIONS] <file>  [-- PLUGIN_OPTIONS]

VCF input options:
   -e, --exclude <expr>        exclude sites for which the expression is true
   -i, --include <expr>        select sites for which the expression is true
   -r, --regions <region>      restrict to comma-separated list of regions
   -R, --regions-file <file>   restrict to regions listed in a file
   -t, --targets <region>      similar to -r but streams rather than index-jumps
   -T, --targets-file <file>   similar to -R but streams rather than index-jumps
VCF output options:
   -o, --output <file>         write output to a file [standard output]
   -O, --output-type <type>    'b' compressed BCF; 'u' uncompressed BCF; 'z' compressed VCF; 'v' uncompressed VCF [v]
Plugin options:
   -h, --help                  list plugin's options
   -l, --list-plugins          list available plugins. See BCFTOOLS_PLUGINS environment variable and man page for details
   -v, --verbose               print debugging information on plugin failure


$ bcftools-dev plugin +fill-tags -v  SWGR_v1.0_snvs_small_indels_shuffled_hg19.vcf.gz 
plugin directory /srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins/ .. ok
/srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins//+fill-tags.so:
        dlopen   .. /srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins//+fill-tags.so: cannot open shared object file: No such file or directory
+fill-tags:
        dlopen   .. +fill-tags: cannot open shared object file: No such file or directory

No functional bcftools plugins were found in
        BCFTOOLS_PLUGINS="/srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins/".

- Is the plugin path correct?

- Are all shared libraries, namely libhts.so, accessible? Verify with
   on Mac OS X: `otool -L your/plugin.so` and set DYLD_LIBRARY_PATH if they are not
   on Linux:    `ldd your/plugin.so` and set LD_LIBRARY_PATH if they are not

- If not installed systemwide, set the environment variable LD_LIBRARY_PATH (linux) or
DYLD_LIBRARY_PATH (mac) to include directory where *libhts.so* is located.

- Run "bcftools plugin -lv" for more detailed error output.

Could not load "+fill-tags".

```
log:
https://gist.github.com/1e323893edbb72e2035d

**Comment by dwaggott** [comment]
I striped the `+` off the plugin and I'm getting results. Let's see.

**Comment by dwaggott** [comment]
Hmm, the results don't include any additional tags. This vcf only has an `AN` and `AC` info tag and no FORMAT genotypes. Does it calculate the AF based on the INFO tags or the genotypes?

`bcftools-dev plugin fill-tags -v  wellderly.vcf.gz  > tmp.vcf.gz`

Specifying just the AF tag results in error:


```
$ bcftools-dev plugin fill-tags -v wellderly.vcf.gz -- -t AF  > tmp.vcf
plugin directory /srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins/ .. ok
/srv/gsfs0/projects/ashley/apps/bcftools/bcftools/plugins//fill-tags.so:
        dlopen   .. ok
        init     .. ok
Unknown tag "AF" in "AF"
```

**Comment by pd3** [comment]
The `bcftools +PluginName` notation is an abbreviation for `bcftools plugin PluginName`, so the `+` was interpreted as part of the file name. I expanded the docs a little to point out this difference.

The error message is a bit confusing (as usual, sorry). What it meant to say was that the `--tags AF` option could not be parsed because the AF tag is not recognised by the version of the plugin you are running. Either a different version of the plugin is being picked up (does the path name printed above point to the newest version?) or the source code does not have the AF addition (the change was made on a different branch and is not in the main repo yet, the new version can be downloaded directly https://raw.githubusercontent.com/pd3/bcftools/bugfixes/plugins/fill-tags.c).

**Comment by dwaggott** [comment]
Ah right. The plugin from that branch ran when slotted into the main dev branch. The output however didn't include any new tags. Are the genotypes required? All I have is INFO/AC and INFO/AN.

I'm assuming you can't output the on the fly filter variables `N_ALT, N_SAMPLES, AC, MAC, AF, MAF, AN` through `bcftools query`, correct?

**Comment by dwaggott** [comment]
Testing on another file that had genotypes worked until it hit a segfault. The row it breaks on doesn't seem special i.e. AC=1, AN=906 including 1 `./.`

**Comment by dwaggott** [comment]
This crazy line causes the segfault.
https://gist.github.com/82b6656b5d5a5cb2e50e

**Comment by pd3** [comment]
That's right, it uses the genotype fields to calculate the values and `query` currently does not calculate the on the fly variables. Thanks for the segfault case.

**Comment by dwaggott** [comment]
Thanks again, closing. 

p.s. plus 1 for adding the ability to generate calculated output i.e. AF=AC/AN
