### ISSUE TITLE
bcftools call error: "ref alleles not compatible"

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#346]
I am using a recent version of the develop branch:
````
bcftools --version
bcftools 1.2-159-gf6831b5
Using htslib 1.2.1-246-g2e4226f-dirty
````

When I run 
````
bcftools call -m -C alleles -T X.sites.vcf X.gls.vcf 1>/dev/null
````
on [these two files](https://gist.github.com/wkretzsch/f1a5a99569438beebf8f), I get the error message
````
Note: Neither --ploidy nor --ploidy-file given, assuming all sites are diploid
The reference alleles are not compatible at X:60003 .. . vs A
````

The first message is fine, but the second one is confusing, as both the sites and gls VCF have the reference allele "A".  Am I misunderstanding this error message?

**Comment by jaredo** [comment]
Hey Winni,

I think when using `call`, the targets file needs to be a tsv like the one detailed at then end of this section:

http://samtools.github.io/bcftools/bcftools.html#common_options

Note issue #239 , we found this tsv also needs to be bgzipped/tabixed.

cheers,

Jared

**Comment by wkretzsch** [comment]
Hey Jared,
Thanks! That makes perfect sense and works for me.

Winni

**Comment by pd3** [comment]
I extended the documentation and added a check into htslib to prevent future errors like this.
