### ISSUE TITLE
Weird results from vcf2sex plugin on HRC panel

### ISSUE THREAD

**Issue by Santy-8128** [samtools/bcftools#347]
Hi Petr,

I ran the vcf2sex plugin on the Haplotype Reference Consortium panel and got weird results (only 36 male samples estimated out of ~32,000 samples). My command line was as follows. Any obvious reasons for such weird results ? Because of large size and privacy issues, I cannot share the data. Not sure how to create a minimal working example either. Any help would be greatly appreciated ?

bcftools +vcf2sex X.noGT.MAC5.bcf -- -g PL > RESULTS
 
When using the vcf2sex plugin to guess (-g) sex from PL values, is there any minor AF cutoff that we should use ? Or is it okay to use all variants to estimate sex? I mean, would a lot of low frequency variants bias the results towards female ?

I also looked at issue #175 but did not find much on using PLs. Thanks for your help.

Regards,
Santy.

**Comment by pd3** [comment]
Hi Santy,
I think this https://github.com/pd3/bcftools/commit/4dcd67df5cc79efd2b1e129879ffd10ba0027402 should fix the issue (the updated plugin can be download directly from [here](https://raw.githubusercontent.com/pd3/bcftools/4dcd67df5cc79efd2b1e129879ffd10ba0027402/plugins/vcf2sex.c)).
If it does not help, try to run with the `-v` option to check the counts in PAR vs non-PAR regions. This should also help to identify possible issues with using different reference build and/or chr naming convention. 
Petr
