### ISSUE TITLE
bcftools stats per-sample counts (PSC) nSingletons

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#349]
I suspect `[11]nSingletons` in the `PSC` section of the `bcftools stats` output is incorrectly calculated. No singletons are counted by `bcftools stats`, but this `view` command run on the same vcf file prints lots of singleton records:

    bcftools view -H -c 1 -C 1 $vcf

The command line for bcftools `stats` was:

    bcftools stats  -s - -

**Comment by mcshane** [comment]
Hi Tommy. Could you prepare a small example file to show the problem?

**Comment by tommycarstensen** [comment]
Hi Shane. I just created a small VCF for which it worked fine. Then I realised I was piping this output to `stats`:

    $bcftools view -i 'MAF>0.05 & TYPE="snp"' $vcf

My bad! Sorry about that!
