### ISSUE TITLE
drop all samples

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#350]
I'm trying to store a minimal vcf with just the AF tag. Is there a simple way to drop all samples? I tried negating all sample names in a text file (-S "^names.txt") and selecting null samples (-s "")

current attempt:
`bcftools annotate -O z -x "^INFO/AF,FORMAT,FORMAT/GT" -s "" tmp.vcf.gz`

**Comment by mcshane** [comment]
`bcftools view -G $vcf`
