### ISSUE TITLE
add INFO header lines when using fill-tags plugin

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#351]
Some generic INFO lines added to the header would be helpful when using the `fill-tags` plugin. I ran into issues on downstream processing when they were missing.

**Comment by pd3** [comment]
Not sure what you mean, can you be more specific? This works for me

    $ cat test.vcf | grep ID=AN
    <no output>
    $ bcftools +fill-tags test.vcf | grep ID=AN
    ##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
