### ISSUE TITLE
GQ is 'nan' instead of '.'

### ISSUE THREAD

**Issue by denisemauldin** [samtools/bcftools#353]
Hi all,

When doing a bcftools merge, I got the following line:

chr1    10106   .       C       A       3       LowGQX  SNVSB=0;SNVHPOL=3;  GT:GQ:GQX:DP:DPF:AD     ./.:nan:.:.:.:. 0/1:32:0:3:1:2,1        ./.:nan:.:.:.:.

I attempted to make a set of test VCFs for this using the individual lines that go into that line and when I did a bcftools merge with them, those had a . instead of 'nan'.

file 1:
chr1	10103	.	T	.	0.00	LowGQX	END=10255;BLOCKAVG_min30p3a GT:GQX:DP:DPF	.:.:0:0
file 2: 
chr1	10106	.	C	A	3.00	LowGQX	SNVSB=0.0;SNVHPOL=3;GT:GQ:GQX:DP:DPF:AD	0/1:32:0:3:1:2,1
file 3:
chr1	1	.	N	.	0.00	LowGQX	END=10130;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	.:.:0:0

Note that the field that is nan is 'GQ' and that two of the files don't have 'GQ' values on those lines while the third one does. Did I just get a weird set of runs?  Should I include more lines for context in the test files?

Thanks,
Denise

**Comment by adamspargo** [comment]
Hi, were you able to produce a set of files to illustrate this?

**Comment by denisemauldin** [comment]
I am unable to yet.  I'll reopen when/if I get a similar result.

**Comment by anatolyu** [comment]
Hello adamspargo,

I have the same issue. When I merge 1300 files I have  ./.:nan:.:.:.:. . I tried to figure out what it is and re-run with the smaller number of files. For ten files it gives a correct string: ./.:.:.:.:.:. .
