### ISSUE TITLE
bcftools reheader discards the VCF header if there's no variants (ie creates a 0B file)

### ISSUE THREAD

**Issue by drmjc** [samtools/bcftools#356]
Hi,
I was using bcftools reheader v1.2 to rename samples & all was fine. But in VCF files where there are no variants (as can happen in our automated somatic pipeline), instead of getting a vcf.gz file with the header and updated sample names, I got an empty file.

The specific message was:

    FIXME: No body in the file: strelka.passed.somatic.snvs.vcf.gz

Could you please just print the header after updating the sample ID's instead?
cheers.

**Comment by pd3** [comment]
Hi, this is now fixed. Thanks for reporting the bug
