### ISSUE TITLE
bcftools view maf filter

### ISSUE THREAD

**Issue by brittbio** [samtools/bcftools#357]
Hello,
I am trying to filter vcf files by maf frequency filter in which I only keep SNPs with an MAF>0.01. Below is the command that I ran, however when I look at the output there are still variants present with MAF<0.01. I have used other bcftools on these vcf files with no issues. Am I using the bcftools view maf filter incorrectly? Thank you so much! :)  Brittany

Command Run:
bcftools view -q 0.01 chr.all.vcf.gz | bgzip -c > chr.all.vcf.bcftoolsmaf01.gz

**Comment by wkretzsch** [comment]
Hi,
Right now you are filtering on *non-reference* allele frequency instead of *minor* allele frequency (MAF).  Here is the description of the `-q` option from the documentation:
````
-q, --min-af FLOAT[:nref|:alt1|:minor|:major|:nonmajor]
minimum allele frequency (INFO/AC / INFO/AN) of sites to be printed. Specifying the type of allele is
optional and can be set to non-reference (nref, the default), 1st alternate (alt1), the least frequent (minor), 
the most frequent (major) or sum of all but the most frequent (nonmajor) alleles.
````
To filter on minor allele frequency you need to add `:minor` after your float like so:
````
bcftools view -q 0.01:minor chr.all.vcf.gz
````

**Comment by brittbio** [comment]
Thank you so much!!

Brittany

**Comment by brittbio** [comment]
Sorry, one last question just to clarify.  If I have multiple versions of a variant in which some have MAF greater than my thresholds and some have less it looks like bcftools removes all of the variants with the  -q 0.01:minor option. Is that correct?  For example for SNP 22:16050654 there are 4 versions of it with the MAFs of  0.00180, 0.01737, 0.11961, 0.00399. However in the output of the bcftools filtering -q 0.01:minor  the SNP 22:16050654  is not in the vcf file.  
Thank you!
Brittany

**Comment by wkretzsch** [comment]
Hi Brittany,
I'm not quite clear on what you mean by 4 versions of the variant.  Are you talking about 4 non-reference alleles (obviously not possible for a SNP)?  Could you provide the first 9 columns of SNP 22:16050654 to clarify?

**Comment by brittbio** [comment]
Sorry for the confusion, and thanks for helping me with this. The variant is a copy number variant in which there are 4 different numbers of variants a person could have. Below is the output from the chromosome.info file and the vsf dose files, the first 9 columns. These files were created with the Michigan Imputation Server. Let me know if you need another info, Thanks! :)

#grep 22:16050654 chr22.info
  #22:16050654	A	<CN0>	0.00180	0.00180	0.99820	0.00000	Imputed	-	-	-	-	-
  #22:16050654	A	<CN2>	0.01737	0.01737	0.98263	0.00000	Imputed	-	-	-	-	-
  #22:16050654	A	<CN3>	0.11961	0.11961	0.88039	0.00000	Imputed	-	-	-	-	-
  #22:16050654	A	<CN4>	0.00399	0.00399	0.99601	0.00000	Imputed	-	-	-	-	-
#zcat chr22.dose.vcf.gz | grep 22:16050654 > grep.22.16050654.dose
#22	16050654	22:16050654	A	<CN0>	.	PASS	MAF=0.00180;R2=0.00000	GT:DS:GP
#22	16050654	22:16050654	A	<CN2>	.	PASS	MAF=0.01737;R2=0.00000	GT:DS:GP
#22	16050654	22:16050654	A	<CN3>	.	PASS	MAF=0.11961;R2=0.00000	GT:DS:GP
#22	16050654	22:16050654	A	<CN4>	.	PASS	MAF=0.00399;R2=0.00000	GT:DS:GP

**Comment by wkretzsch** [comment]
Hi Brittany,
Unfortunately, I'm not familiar with Michigan Imputation Server results.  However, judging from the VCF, it looks like you have four entries for the exact same variant, where the non-reference allele is missing.  I'm not sure this is a VCF spec compliant way of coding CNVs.

In any case, I would expect Bcftools only to drop lines for which the MAF is below your threshold if the `INFO/MAF` tag is correct.  However, I think Bcftools recalculates the MAF for each line, and does not use the `INFO/MAF` tag for filtering.  In your case, I would recalculate the MAF of each of the lines by hand to make sure the `INFO/MAF` numbers and real MAF match up.

**Comment by pd3** [comment]
That's correct, MAF is recalculated by bcftools. This could (and probably should) be changed so that it's recalculated only when not available.

**Comment by brittbio** [comment]
Makes sense, thanks so much for your help! :)

**Comment by wkretzsch** [comment]
@pd3 I agree.  Probably there should also be a shared `--recalculate` flag that forces recalculation of all calculable tags.

**Comment by wkretzsch** [comment]
@brittbio another thought: as the non-reference allele is missing, depending on how the internals of Bcftools, it might well be that these variants are always filtered out, no matter what value you use for `-q`. As there is no alternate allele, the MAF is not defined.  In that case it might well be the right choice for Bcftools to filter out those sites...

**Comment by pd3** [comment]
Try `-i 'MAF>0.01'`, I believe that should work

**Comment by brittbio** [comment]
Thanks!

**Comment by alanmejiamaza** [comment]
Hi, as this thread is still open. The following command would filter SNPs with maf <,=0.02, independent of AF stated in the vcf file?
bcftools filter -e 'MAF>0.02' file.vcf > file1.vcf
Thanks

**Comment by winni2k** [comment]
Please create a new issue for these questions @scienception and @alanmejiamaza .
