### ISSUE TITLE
bcftools merge missing 3rd sample reference

### ISSUE THREAD

**Issue by denisemauldin** [samtools/bcftools#361]
Hi all,

When combining three files I'm getting a missing call where I would expect a 0/0 ref call.

Here's a gist with VCF files:
https://gist.github.com/denisemauldin/835f58b4efe32e7a1311

G06
chr1    10107   .       C       .       0.00    LowGQX;HighDPFRatio     END=10110;BLOCKAVG_min30p3a     GT:GQX:DP:DPF   .:.:0:1

D05
chr1    10106   .       C       .       0.00    LowGQX  END=10107;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:12:5:0

H09
chr1    10107   .       C       .       0.00    LowGQX  END=10120;BLOCKAVG_min30p3a     GT:GQX:DP:DPF   0/0:5:2:0

Here's the current merge results:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	G06	D05	H09
chr1	10106	.	C	.	0	LowGQX	END=10107;BLOCKAVG_min30p3a;AN=2	GT:GQX:DP:DPF	./.:.:.:.	0/0:12:5:0	./.:.:.:.
chr1	10107	.	C	.	0	LowGQX;HighDPFRatio	END=10110;BLOCKAVG_min30p3a;AN=2	GT:GQX:DP:DPF	.:.:0:1	./.:.:.:.	0/0:5:2:0

I expected the lines to be:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	G06	D05	H09
chr1	10106	.	C	.	0	LowGQX	END=10107;BLOCKAVG_min30p3a;AN=2	GT:GQX:DP:DPF	./.:.:.:.	0/0:12:5:0	./.:.:.:.
chr1    10107   .       C       .       0       LowGQX;HighDPFRatio     BLOCKAVG_min30p3a     GT:GQX:DP:DPF   .:.:0:1      0/0:12:5:0     0/0:5:2:0
chr1    10108  .     ?   .   0  LowGQX;HighDPFRatio    END=10110;BLOCKAVG_min30p3a;AN=2  GT:GQX:DP:DPF   .:.:0:1	./.:.:.:.	0/0:5:2:0
chr1	10110	.	?	.	0	LowGQX;HighDPFRatio	END=10120;BLOCKAVG_min30p3a;AN=2	GT:GQX:DP:DPF	./.:.:.:.	./.:.:.:.	0/0:5:2:0

Why is it instead resulting in a ./.:.:.:. at position 10107 for D05?  Why is 10110 to 10120 not covered?  Do I need to provide some other flags?

Thanks,
Denise

**Comment by pd3** [comment]
Hi Denise, what version of bcftools are you using? gvcf merging is not in the main repo yet, but hopefully this version should work https://github.com/pd3/bcftools/

**Comment by pd3** [comment]
Verified, the gvcf-capable merging referenced above works as expected:

    bcftools merge -g 1.vcf.gz 2.vcf.gz 3.vcf.gz | bcftools query -f'%POS %REF %ALT %END[  %GT]\n'
    10106 C . 	 .          ./.   0/0 	 ./.
    10107 C . 	 .          . 	  0/0 	 0/0
    10108 N . 	 10110      .     ./. 	 0/0
    10111 N . 	 10120      ./.   ./. 	 0/0

**Comment by jmarshall** [comment]
Will be fixed by the merging of the **merge** improvements.

**Comment by mcshane** [comment]
This should be resolved now that #455 has been merged.
