### ISSUE TITLE
bcftools call --ploidy-file

### ISSUE THREAD

**Issue by djeffares** [samtools/bcftools#366]
When using Version: 1.3 (using htslib 1.3), I do not seem to be able to set ploidy to 1. 
My command is below.

Regards,
Dan

samtools mpileup -f Spombe_genome.2015-01-12.fa bams/M3*realigned.bam \
--VCF --uncompressed \
--min-MQ 10 \
--output-tags DP,AD,INFO/AD,ADF,ADR,INFO/ADF,INFO/ADR,SP | \
bcftools call --ploidy-file allchrs.ploidy \
--multiallelic-caller \
--variants-only

And the ploidy file is:
I 1 5579133 F 1
II 1 4539804 F 1
III 1 2452883 F 1
MATR 1 20128 F 1
MT 1 19431 F 1
AB325691 1 20000 F 1

**Comment by pd3** [comment]
Hi, the program required explicit sample sexes to be passed via -S. This is inconvenient if one works with haploid data only. This is now fixed in https://github.com/pd3/bcftools, let me know in case of problems.
Thanks

**Comment by djeffares** [comment]
Hi,

Thanks for the feedback. I’ll give it a try & let you know if there are any problems. 

Great software btw, I see that its still ranking highly as a caller, e.g. PMID:26639839.

cheers,
Dan





On 11 Jan 2016, at 15:05, pd3 <notifications@github.com> wrote:

Hi, the program required explicit sample sexes to be passed via -S. This is inconvenient if one works with haploid data only. This is now fixed in https://github.com/pd3/bcftools <https://github.com/pd3/bcftools>, let me know in case of problems.
Thanks

**Comment by roddypr** [comment]
Hi, any idea when this will be available on the stable distribution of bcftools (e.g. the one downloaded using Brew)? I'm organising a bioinformatics course and it would be amazing to not have to install a development version.

**Comment by jmarshall** [comment]
@roddypr: It's available in bcftools 1.3.1 released today.

As to when it'll be available via brew, that depends on the brew folks updating their recipe for the new release.  You might like to file an issue at [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science).

**Comment by roddypr** [comment]
@jmarshall Just tried version 1.3.1 and it works!
Thanks very much for your reply and for the update :)
