### ISSUE TITLE
bcftools normalization may break position order

### ISSUE THREAD

**Issue by JaeYJung** [samtools/bcftools#368]
After split/normalization (`$BCFTOOLS.v1.3 norm -m-both $FILE | $BCFTOOLS.v1.3 norm -f $REF - > $OUT`),
one variant (`POS=42356854`) was pushed into a wrong position (after `POS=42356855`), so could not make index file with "unsorted positions" error.

Sample VCF file is attached.

[test1.vcf.txt](https://github.com/samtools/bcftools/files/77301/test1.vcf.txt)

**Comment by pd3** [comment]
Hi, thank you for the bug report. I believe this is now fixed, please let me know in case of problems https://github.com/pd3/bcftools/tree/bugfixes
thanks
