### ISSUE TITLE
Feature request: specify multiple regions (or at least contiguous regions spanning chromosomes) for `mpileup`

### ISSUE THREAD

**Issue by jrandall** [samtools/bcftools#369]
The new experimental `bcftools mpileup` (along with the historical `samtools mpileup`) have an `-r` option for specifying a single region on which to operate. However, I don't think they have any way to run over multiple regions. This is a particular issue when trying to run against the 6000+ contigs in GRCh38 (many of which are only a few kbp long). In GATK, an interval_list can be given (to the `-L`) option that contains a list of many "chromosomes" to process, and GATK HaplotypeCaller happily processes a contiguous chunk of genome spanning thousands of chromosomes without any apparent slowdown. 

On the other hand, `bcftools mpileup` has to be invoked once for each of the 6000+ contigs in most cases just to call a few kbp. This has enormous overhead, both in terms of the cost of setting up the run but also in monitoring thousands of extra processes and assembling the bits back together. 

`bcftools view` already supports multiple regions (via `-R`) as does `samtools view` (via `-L`).  It would be nice if `bcftools mpileup` supported this as well.

**Comment by pd3** [comment]
This is now added in https://github.com/pd3/bcftools/commit/cfd7cf9092ffddc1ec0441a3c463bc2ac7084bad, https://github.com/pd3/htslib/commit/fa6c73316ac95156b5081629adb1ac3a3a2efccf and https://github.com/pd3/htslib/commit/b611659090dfb1cfe82b70ccc698f024dffe4f3f

Please let me know in case of problems
