### ISSUE TITLE
Filtering on VCF QUAL scores

### ISSUE THREAD

**Issue by pishotta** [samtools/bcftools#370]
I have encountered difficulty filtering on the QUAL scores found in the VCF output of the freebayes variant caller.  The problem relates to the calculation of the QUAL scores for non-variant loci.when the --report-monomorph switch is provided.  I want to filter out low quality calls for both variants and non-variants using a filter like "bcftools view -e 'QUAL<20' foo.vcf.gz", but that filters out all the high quality non-variants BECAUSE the QUAL score freebayes reports is the Phred-scaled probability that a REF/ALT polymorphism exists at the specified site (given the sequencing data) which would, of course, be very low for a high quality non-variant call, not very high as it would be for a high-quality variant call.  But is that the right way to calculate a valid VCF QUAL score?<P>The VCF 4.2 Spec defines QUAL as the "<b>Phred-scaled quality score for the assertion made in ALT. i.e. −10log10 prob(call in ALT is wrong). If ALT is ‘.’ (no variant) then this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10 prob(no variant).</b>" The 4.1 Spec also contained the statement: "<b>High QUAL scores indicate high confidence calls.</b>"<p>This seems clear to me,  Whether variant or non-variant, the <b>higher</b> the QUAL score, the <b>better</b> the call.  Just what I want for filtering all calls consistently and uniformly --  the quality of the call, not simply the probability of a non-variant. Unfortunately, freebayes, for the reason just mentioned, does not produce results amenable to this approach, as it produces high QUAL scores for highly confident variant calls, but low QUAL scores for highly confident non-variant calls;<p>So now I'm confused.  Am I misunderstanding the published VCF format specs?  Is the freebayes QUAL score for called monomorphic loci not in conformity with the formal provisions of the specification?  Am I not using bcftools correctly? What gives?<p>Both freebayes and bcfools are wonderful products and I want to organize them into an efficient pipeline, but this issue has thrown a monkey wrench (no offense to monkeys) into the works, so please help me clarify this.  The difference is critical, but I would not want to take anyone to task over not following the VCF specs if it is I who misinterprets them.<p>-- Fred P.

**Comment by lh3** [comment]
As I am involved in samtools/hts-specs#122 – freebayes is conforming to the spec. By default, no variants in the freebayes output have ALT=".". According to the spec, low qualities in this case indicate low-confident variants. These low QUAL do **NOT** mean to show high confident reference calls. The general rule: filter out low QUAL calls. This is applied to both ALT="." and ALT!=".".

**Comment by pishotta** [comment]
Hi,<p>I mostly agree with what you are saying when applied to "variant" calls, but I think you are missing my point.  I am NOT talking about "variant" calls, I am talking about the "non-variant" calls freebayes outputs when given the --report-monomorphic switch.  Extract from VCF4.1 output below:<pre>#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT<br>chr1    69442   .       G       .       0       .       DP=177;DPB=177;EPPR=3.61144;GTI=0;MQMR=4.53107;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4224;RO=177;RPPR=233.272   GT:DP:RO:QR:AO:QA       0/0:177:177:4224:.:.<br>chr1    69443   .       C       .       0       .       DP=178;DPB=178;EPPR=3.0591;GTI=0;MQMR=4.70787;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4329;RO=178;RPPR=209.178    GT:DP:RO:QR:AO:QA       0/0:178:178:4329:.:.<br>chr1    69444   .       A       .       0       .       DP=178;DPB=178;EPPR=3.44947;GTI=0;MQMR=4.70225;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=4163;RO=178;RPPR=190.586   GT:DP:RO:QR:AO:QA       0/0:178:178:4163:.:.<br>chr1    69445   .       A       .       0       .       DP=179;DPB=179;EPPR=3.99292;GTI=0;MQMR=4.69832;NS=1;NUMALT=0;ODDS=0;PAIREDR=0;PQR=0;PRO=0;QR=3938;RO=179;RPPR=180.622   GT:DP:RO:QR:AO:QA       0/0:179:179:3938:.:.</pre>ALT is in fact reported as "." (because no non-reference allele was detected), There was good depth of coverage and all other measures were supportive of the fact that these were good, confident calls, but the QUAL score is 0.  Over 99% of millions of non-variant calls show 0 or very near QUAL scores, So if I filter out "low QUAL scores", I lose them all.
<p><p>The problem isn't with the VCF4.1 specification/definition of the QUAL field.  I am concerned that the freebayes calculation of QUAL is not performed correctly for non-variants.  The spec says:<blockquote> QUAL - quality: Phred-scaled quality score for the assertion made in ALT. i.e. −10log10 prob(call in ALT is wrong). If ALT is ‘.’ (no variant) then this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10 prob(no variant). High QUAL scores indicate high confidence calls. Although traditionally people use integer phred scores, this field is permitted to be a floating point to enable higher resolution for low confidence calls if desired. If unknown, the missing value should be specified. (Numeric)</blockquote>It says when ALT is not ".", QUAL is the Phred score that the locus DOES NOT HAVE a variant present; but if ALT is ".", then QUAL is the Phred score that the locus DOES HAVE a variant present.  This provides the symmetry required for bcftools to filter QUAL scores collectively, whether variant or non-variant.
<p><p>I initially queried Erik Garrison (freebayes author) on this point (https://github.com/ekg/freebayes/issues/237), and he said that "QUAL is the probability of polymorphism, which is low at monomorphics by their definition", which is how he is calculating it in all cases, variant or not. He suggested I consider using 1-QUAL as a measure of the probability that the non-variant call is correct, but for a variety of reasons that confused me even further (Phred scores don't work quite like that) so I thought I should confirm my understanding of the VCF4.1 spec.  Currently, I believe that:<P><ol><li>The freebayes calculation of QUAL scores for variant calls DOES conform to VCF4.1 specifications; and,</li><li>The freebayes calculation of QUAL scores for monomorphic non-variant calls (generated when freebayes is provided with the --report-monomorphic option) DOES NOT conform to VCF4.1 specifications.</li></ol>Wouldn't you agree?  If not, what is your explanation of this behavior and how can it be reconciled with the specs?<p><p>-- Fred P.

**Comment by lh3** [comment]
@ekg, does freebayes' QUAL conform to the VCF spec, in particular for non-variant sites?

**Comment by ekg** [comment]
@lh3 I believe it's not running the model for these sites because there is no alternate allele considered. I can try to introduce a placeholder into the calculations so the monomorphic sites resemble the polymorphic ones.

@pishotta Let me resolve this so that it behaves as expected. The qualities will still be low for monomorphic sites however.

Which leads back to the discussion we had on the freebayes boards. As it represents the posterior probability of polymorphism, the only way for QUAL to be high at confident monomorphic sites is if we change the definition of it. @lh3 --- does this match your understanding?

**Comment by ekg** [comment]
I think things may have changed since 4.1/4.0? In any case, @mcshane pointed this out to me so I don't continue in rapid-response confusion.

So what is the assertion made in ALT? Does it include the genotyping? If it does, then the call quality will tend to decrease as we add samples due to the increased state space. In other words: The posterior under the particular configuration asserted by the ALTs and genotypes would decrease as a fraction of the total space, and thus the QUAL would decrease.

How do I implement this? I'm not sure I can change the QUAL score definition without disrupting a lot of people's pipelines.

Or, is it the marginal probability of the assertion made in ALT? All the configurations in which we find that particular set of alleles (again, this is not what I've implemented...)

**Comment by pishotta** [comment]
I think the priorities of the spec are to define parameters it is highly desirable to know, without much concern as to the difficulties of computing them.  I believe that is the case with the QUAL column.  We pipeliners want a clean, simple, uniformly behaving parameter that we can use in the same way for all calls of all types to filter out the "poor" and retain the "good".  The spec seems to provide that with QUAL. (Woo-Hoo!)  Easy to say, but not necessarily easy to do.  I feel your pain.  I'm no statistician at all, but I can appreciate that the no-variant-found-or-detected call might present as a degenerate case for a bayesian approach.

The spec's definition of QUAL involves a few weird mathematical double negatives, but following your lead, let me give it a shot.  You do always calculate the probability (say "p", 0 to 1) of there being a polymorphism at a locus, don't you?  So in the case of a variant call, QUAL = (-10log10(1-p)), the PHRED score of the probability that there is NOT a variant.  I believe that is what you are doing there, but in the case of a non-variant call, shouldn't the QUAL score be calculated as QUAL = (-10log10(p)), the PHRED score of the probability that there IS a variant?  I may have the "p" and "1-p" mixed up, but I believe something like that is the intention of the spec for the parameter QUAL (which discussion pretty much exhausts my knowledge of statistics).

-- Fred P.

**Comment by lh3** [comment]
@ekg Let P be the probability of the sample having a variant allele. If `ALT!=.`, QUAL equals `-10log10(1-P)`. If `ALT=.`, QUAL equals `-10log10(P)` and is a big number at most sites. QUAL has been like this since the very first VCF spec (actually Richard and I defined it this way).

**Comment by ekg** [comment]
This is the same definition I used in freebayes minus the part about it
inverting if the call is monomorphic. I will change this to match.

**Comment by mcshane** [comment]
OK. I'm going to close this issue here, and let @ekg track the resolution on the original issue at ekg/freebayes#237

**Comment by pishotta** [comment]
Thanks @lh3, @ekg and @mcshane. I think that will fix this issue.  I've noticed another smaller (I think) issue in the VCF files I will mention there.  Not sure I understand its implications (if any), but thx again for this pending switch.

**Comment by alexjironkin** [comment]
Hi,

QUAL = 0 report also happens in the mpileup | bcftools (https://github.com/samtools/samtools/issues/566) and seem to trace back to bcftools. Is this going to be fixed (in conjuction with the freebays discussion)?
