### ISSUE TITLE
Depth distribution of bcftools stats output

### ISSUE THREAD

**Issue by hurchu** [samtools/bcftools#380]
Why are all [4] number of genotypes 0? Thanks!

# DP    [2]id   [3]bin  [4]number of genotypes  [5]fraction of genotypes (%)    [6]number of sites      [7]fraction of sites (%)
DP      0       1       0       0.000000        1       0.390625
DP      0       2       0       0.000000        30      11.718750
DP      0       3       0       0.000000        5       1.953125
DP      0       4       0       0.000000        4       1.562500
DP      0       5       0       0.000000        4       1.562500
DP      0       6       0       0.000000        3       1.171875
DP      0       7       0       0.000000        5       1.953125
DP      0       8       0       0.000000        1       0.390625
DP      0       9       0       0.000000        1       0.390625
DP      0       10      0       0.000000        3       1.171875
DP      0       11      0       0.000000        1       0.390625
DP      0       14      0       0.000000        4       1.562500
DP      0       15      0       0.000000        1       0.390625
DP      0       16      0       0.000000        1       0.390625
DP      0       17      0       0.000000        1       0.390625
DP      0       18      0       0.000000        1       0.390625
DP      0       19      0       0.000000        1       0.390625
DP      0       20      0       0.000000        3       1.171875
DP      0       22      0       0.000000        2       0.781250
DP      0       24      0       0.000000        1       0.390625
DP      0       28      0       0.000000        1       0.390625
DP      0       29      0       0.000000        1       0.390625
DP      0       31      0       0.000000        1       0.390625
DP      0       32      0       0.000000        1       0.390625

**Comment by mcshane** [comment]
My guess is that you have no genotypes in your VCF. Is it a sites-only VCF?

**Comment by hurchu** [comment]
Hi Shane,

There are genotypes in my VCF files. I tested several different VCF files and all the VCF files have GT field. But the output of bcftools stats are all 0.

Thanks!

**Comment by hurchu** [comment]
I just used the default command to run bcftools stats.
bcftools stats test.vcf > test.txt

The following is one example record in my VCF file.

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
1       69270   .       A       G       95.43   TruthSensitivityTranche99.90to100.00    AC=2;AF=1.00;AN=2;DP=250;DS;Dels=0.00;FS=0.000;HRun=0;HaplotypeScore=0.0000;MQ=3.48
;MQ0=243;QD=0.38;VQSLOD=-10.2561;culprit=MQ;set=FilteredInAll        GT:AD:DP:GQ:PL  1/1:202,45:250:14.98:128,15,0

**Comment by mcshane** [comment]
Ah. stats by default will only look at the site information. To delve into genotypes and per-sample information, you need to run `bcftools stats -s- test.vcf`.

I'll close this, but link in issue #316 to make sure this gets documented when that issue is dealt with.

**Comment by hurchu** [comment]
Thank you so much! :+1:
