### ISSUE TITLE
bcftools norm allele split function error

### ISSUE THREAD

**Issue by yujin2011** [samtools/bcftools#382]
Trying to split the multi-alleles variants of a vcf file and got following error:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
bcftools: vcfnorm.c:414: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted (core dumped)

The command:
bcftools norm -m - -f /bigdata/Genetics/reference/hg19/hs37d5.fa /bigdata/Genetics/reference/ExAC/0.3/ExAC.r0.3.nonpsych.sites.vcf.gz

the vcf file:
ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3/subsets/

-Jin

**Comment by mcshane** [comment]
Looks like this is not a completely valid VCF. They `AC_Het` tag is `Number=A`, but some positions have more than the expected number of records.
```
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:13404
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:13528
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:17478
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:69521
INFO/AC_Het is Number=A in header. Expected 3, but found 6 at: 1:69552
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:138829
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:138909
...
```
e.g at 1:13404, REF=G, ALT=A,T and AC_Het=0,1,0, but it should have only 2 values.

**Comment by yujin2011** [comment]
If one variant has three different alleles, say 0, 1, 2, should we have three possible hetezygous genotypes("AC_Het")?  say 0/1, 0/2, 1/2.

Best,
Jin

**Comment by yujin2011** [comment]
Hi mcshane,

Thanks for the quick response. 

I think you are right the header information of the vcf file is not accurate. For AC_Het. It is given "A" which implies it equals to the number of alternate allele. but actually it should be (n_alt^2+n_alt)/2. So I guess I should change "Number=A" to "Number=." to make it a complete vcf file?

BTW Does BCFtools recognize Ac_Het when splitting the alleles?

Thanks,
Jin


````
vcf v4.2 specification on " number=?"

• If the field has one value per alternate allele then this value should be ‘A’.
• If the field has one value for each possible allele (including the reference), then this value should be ‘R’.
• If the field has one value for each possible genotype (more relevant to the FORMAT tags) then this value
should be ‘G’.
• If the number of possible values varies, is unknown, or is unbounded, then this value should be ‘.’.
````

**Comment by mcshane** [comment]
Setting it to `Number=.` would make it "valid", but you have lost the meaning of AC_Het as you don't know to which alleles each count corresponds. If you set it to `Number=.` norm will not split the AC_Het INFO field.

Probably best thing is to ping someone from ExAC (@konradjk?) to point out the problem and ask for a fix of the VCF file.

**Comment by konradjk** [comment]
Yes, this is a known issue (https://github.com/konradjk/exac_browser/issues/164). We'll be putting out a fixed VCF shortly.
