### ISSUE TITLE
Problem with filtering indels

### ISSUE THREAD

**Issue by sephraim** [samtools/bcftools#383]
I was doing some testing with filters, and I noticed an issue with the `-i 'TYPE="indels"'` filter.

Here's my test VCF:

```
$ bcftools view -H test.vcf
1	1000000	.	C	T	.	.	.
1	2000000	.	C	T,A	.	.	.
1	3000000	.	C	T,A,G	.	.	.
1	4000000	.	T	TTT	.	.	.
1	5000000	.	TTT	T	.	.	.
1	6000000	.	T	GTAA	.	.	.
1	7000000	.	T	GTGAC	.	.	.
```

If I apply a filter to only include indels, then I would expect only the last 2 variants (T>GTAA and T>GTGAC) to be included. However, only the insertion (T>TTT) and the deletion (TTT>T) are included:

```
$ bcftools view -H -i 'TYPE="indels"' test.vcf
1	4000000	.	T	TTT	.	.	.
1	5000000	.	TTT	T	.	.	.
```

Likewise, if I try the `-e 'TYPE="other"'` filter, I would not expect the T>GTAA and T>GTGAC variants to get excluded, but they do:

```
$ bcftools view -H -e 'TYPE="other"' test.vcf
1	1000000	.	C	T	.	.	.
1	2000000	.	C	T,A	.	.	.
1	3000000	.	C	T,A,G	.	.	.
1	4000000	.	T	TTT	.	.	.
1	5000000	.	TTT	T	.	.	.
```

Is there a reason why variants such as T>GTAA and T>GTGAC are classified as `other` instead of `indels`? Additionally, why are insertions such as T>TTT and deletions such as TTT>T both classified as `indels`?

I am using bcftools 1.3 and htslib 1.3. Any insight would be very helpful. Thank you very much.

**Comment by mcshane** [comment]
The T>GTAA and T>GTGAC variants are both classified as complex substitutions, not a simple insertion or deletion. T substituted by GTAA for the first and T substituted for GTGAC in the second. With some reference context it is possible they could be decomposed into multiple SNP+INDEL sites, but bcftools classifies based on the representation in the given records.

**Comment by sephraim** [comment]
Thank you for the clarification, @mcshane.
