### ISSUE TITLE
Error: Could not parse --min-ac g

### ISSUE THREAD

**Issue by bretonics** [samtools/bcftools#391]
When generating the consensus sequence from the BAM file 
`samtools mpileup -uf reference.fasta sorted.bam | bcftools view -cg - | vcfutils.pl vcf2fq > cns.fq`

I keep getting this error: 
>Error: Could not parse --min-ac g

I can see the consensus sequence and the assembly aligments `samtools tview sorted.bam`.

**Comment by mcshane** [comment]
Looks like you are using samtools/bcftools 1.0 or greater, which means you should be using `call` rather than `view`. Please see https://github.com/samtools/bcftools/wiki/HOWTOs#consensus-calling for how to generate consensus sequence with samtools/bcftools>=1.0

**Comment by bretonics** [comment]
This might be obvious, but using the consensus `call` yields the same sequence we would see using `samtools index sorted.bam; samtools tview sorted.bam`, correct? Which should be the consensus sequence from the aligned assembly from say bowtie2...?
