### ISSUE TITLE
variant calling with gvcf fails on Mac OS X Mavericks v10.9.5

### ISSUE THREAD

**Issue by tantrev** [samtools/bcftools#392]
I am trying to perform variant calling with an outputted gvcf file, but bcftools exits early without any warning when the "-g" option is used (if the "-g" option is omitted, bcftools performs as expected).

Perhaps my command notation is incorrect?

`samtools mpileup -uf Mus_musculus.GRCm38.dna.primary_assembly.fa SRR1512928.dedupped.bam | bcftools call -cg > SRR1512928.samtools.gvcf`

The assembly I used may be found via ftp://ftp.ensembl.org/pub/release-84/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz and the file I am working with may be found [here](http://tinyurl.com/hcwc8gc).  Any ideas?

**Comment by mcshane** [comment]
There a few things.

1. What version are you using?
2. `-g` requires an argument. I am surprised you do not get an error message about that. I do for all versions I have tried.
3. gvcf is only supported for the `-m` calling mode at the moment. At least in 1.3, there should be an error message saying so if you try to use `-c` and `-g`.
4. While looking at what was going wrong for you, found an bug in 1.3 where the gvcf mode is assuming that the input has a DP annotation. It will segfault if not. So need to add the -t DP option to the mpileup command. Can you try:
```
samtools mpileup -t DP -uf Mus_musculus.GRCm38.dna.primary_assembly.fa SRR1512928.dedupped.bam | bcftools call -mg0 > SRR1512928.samtools.gvcf
```

**Comment by tantrev** [comment]
Thank you for the quick response.

1. I tried both v1.3 and compiling the latest from source.
2. My bad! I was just being an idiot - it does indeed throw an error.
3. Same as above, warnings were present as expected.
4. You're absolutely right, this was the crux of things.  Works perfectly with the "-t DP" option in v1.3.

You're a saint, thank for fixing/figuring this out!

**Comment by tantrev** [comment]
Also, this is unrelated but do you have any advice for parameters to use with single-cell data?  I have been comparing variant calling with default parameters in Freebayes and bcftools, and Freebayes seems to call ~10-20x higher numbers of variants than bcftools.

**Comment by jmarshall** [comment]
I would recommend asking for usage advice on the [samtools-help mailing list](http://www.htslib.org/support/), where there are many more people with interesting experience to offer (and to learn from the resulting conversation).

**Comment by pd3** [comment]
@tantrev The sensitivity can be increased by running `call -m` with greater value of `-P`, this might help.
