### ISSUE TITLE
tag2tag GP to GL wrong log?

### ISSUE THREAD

**Issue by mp15** [samtools/bcftools#394]
https://github.com/samtools/bcftools/blob/develop/plugins/tag2tag.c#L121uses the log() function, which gives the natural logarithm of the GP. Are you sure you didn't mean log10f()?

**Comment by pd3** [comment]
Yes, GLs should be log10 scaled. Sorry about that

**Comment by jmarshall** [comment]
(The P1/P2/P3 labels are for triage and represent **consensus** about priority, so it's not really kosher to add them to issues off the bat.  In particular, `P1: Urgent` is for _crashers/utterly-wrong-answers/etc that **always affect everybody** without a workaround available_, so please use it sparingly and not on issues in minor tools like plugins.)
