### ISSUE TITLE
bcftools treats INFO field as errors

### ISSUE THREAD

**Issue by JaeYJung** [samtools/bcftools#397]
I tried to run bcftools (v1.3) with an annotated vcf, and got the following error:

[W::vcf_parse] INFO 'ENST00000377049.3:c._104__107delTGTT,ENST00000320498.4:c._104__107delTGTT' is not defined in the header, assuming Type=String
Could not parse the header line: "##INFO=<ID=ENST00000377049.3:c.*104_*107delTGTT,ENST00000320498.4:c.*104_*107delTGTT,Number=1,Type=String,Description="Dummy">"
[W::vcf_parse] INFO 'ENST00000377049.3:c._222G>A,ENST00000320498.4:c._222G>A' is not defined in the header, assuming Type=String
Could not parse the header line: "##INFO=<ID=ENST00000377049.3:c.*222G>A,ENST00000320498.4:c.*222G>A,Number=1,Type=String,Description="Dummy">"
Undefined tags in the header, cannot proceed in the sample subset mode.

So it looks like that bcftools can't handle transcript changing annotation (from VEP) properly. Other tools like GATK didn't show such errors.

**Comment by bioinformed** [comment]
I've seen that problem occur when HGVS strings in the annotations include
semicolons.  The "right" fix is for the variant annotator and htslib to
support percent escaping.  I am working on finalizing a set of patches to
htslib that add UTF-8 and percent encoding that I will share in the next
few weeks.

**Comment by mcshane** [comment]
@JaeYJung Could you share a small test case including the header?

**Comment by pd3** [comment]
Closing the issue due to lack of feedback.
