### ISSUE TITLE
what does bcftools call -P mean？

### ISSUE THREAD

**Issue by orisnas** [samtools/bcftools#398]
It says ’expected substitution rate, or 0 to disable the prior‘.
How does it work

**Comment by pd3** [comment]
It's the prior probability theta in http://samtools.github.io/bcftools/call-m.pdf, set a higher value for increased sensitivity.

**Comment by RachelRodgers** [comment]
I'm using bcftools call on short viral sequences, and would like to make the variant calls as liberal as possible.  Is it unreasonable to set the prior to 0.99 to achieve this?  I don't really understand the underlying biological theory so don't want to do something ridiculous.  Just playing around with it so far has looked ok.

**Comment by pd3** [comment]
The model will make more calls, hence filtering will be made slightly more difficult. A bigger factor is read depth and the method of calling, i.e. single vs multi-sample. A single-sample calling is more sensitive and can be done either with literally calling one sample at a time or by using the `call --group-samples` option, see the documentation for more.
