### ISSUE TITLE
Is there a fast way to split multiallelics into multiple rows?

### ISSUE THREAD

**Issue by winni2k** [samtools/bcftools#40]
I would like to split multiallelic SNPs into multiple rows so that each alternate allele gets its own row and "looks like" a biallelic SNP.  Is there a fast way to do this with bcftools?

**Comment by noporpoise** [comment]
What is the difference between `-m -both` and `-m -any` when splitting multiallelics with `bcftools norm`?

**Comment by pd3** [comment]
`-m both` is a shortcut for `-m snps -m indels`, snp records will not be mixed with indels. On the other hand, `-m any` can mix everything regardless of the alleles.

**Comment by noporpoise** [comment]
That makes sense when combining. When splitting up multiallelics, is `-m -any` the same as `-m -both`?

**Comment by cmasotti** [comment]
Related to this subject, please, can anyone give a clue about splitting multiallelics on high ploidy samples (vcf generated through GATK-HaplotypeCaller, pool of individuals, in this case ploidy=6)?  Is it possible?  

Using bcftools norm -m -both, I get an error for every multiallelic site:  
```"Error at chr1:111489032, the tag PL has wrong number of fields"```  
This problematic row:  
```  
chr1    111489032       rs138279022     AACACAC A,AACAC 4885.86 PASS AC=2,1;AF=0.333,0.167;AN=6;BaseQRankSum=-1.095e+00;ClippingRankSum=0.00;DB;DP=395;FS=1.331;MLEAC=2,1;MLEAF=0.333,0.167;MQ=60.52;MQRankSum=4.98;QD=14.90;ReadPosRankSum=-6.781e+00;SOR=0.789 GT:AD:DP:GQ:PL 0/0/0/1/1/2:181,136,11:328:97:4921,324,114,130,317,793,9678,4748,167,0,97,497,6920,4900,359,284,605,6589,5119,657,805,6467,5439,1184,6491,5998,6728,11522  
```  
Thanks a lot for any suggestion.

**Comment by winni2k** [comment]
This looks like a feature request.

**Comment by cmasotti** [comment]
I've posted a similar comment [here](https://gatkforums.broadinstitute.org/gatk/discussion/comment/47171#Comment_47171) on GATK forum, as the bug with LeftAlignAndTrimVariants looks the same: the tool cannot split multiallelics correctly in non-diploid cases (also a feature request to GATK!). Thanks!

**Comment by freeseek** [comment]
When you merge alleles, it makes a difference:
```
(echo "##fileformat=VCFv4.2"
echo "##contig=<ID=chr1,length=248956422,assembly=38>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "chr1\t975523\t.\tT\tC\t.\t.\t."
echo -e "chr1\t975523\t.\tT\tTC\t.\t.\t.") > in.vcf
```

```
$ bcftools norm -m +any in.vcf | bcftools view -H
Lines   total/split/realigned/skipped:	2/0/0/0
chr1	975523	.	T	C,TC	.	.	.
```

```
$ bcftools norm -m +both in.vcf | bcftools view -H
Lines   total/split/realigned/skipped:	2/0/0/0
chr1	975523	.	T	C	.	.	.
chr1	975523	.	T	TC	.	.	.
```

But when you split alleles, the only piece of code that takes the "-" choices into account are these:
```
            case 'm':
                if ( optarg[0]=='-' ) args->mrows_op = MROWS_SPLIT;
                else if ( optarg[0]=='+' ) args->mrows_op = MROWS_MERGE;
                else error("Expected '+' or '-' with -m\n");
                if ( optarg[1]!=0 )
                {
                    if ( !strcmp("snps",optarg+1) ) args->mrows_collapse = COLLAPSE_SNPS;
                    else if ( !strcmp("indels",optarg+1) ) args->mrows_collapse = COLLAPSE_INDELS;
                    else if ( !strcmp("both",optarg+1) ) args->mrows_collapse = COLLAPSE_BOTH;
                    else if ( !strcmp("any",optarg+1) ) args->mrows_collapse = COLLAPSE_ANY;
                    else error("The argument to -m not recognised: %s\n", optarg);
                }
                break;
```
and:
```
        if ( args->mrows_op==MROWS_SPLIT )
        {
            split = 1;
            if ( args->mrows_collapse!=COLLAPSE_BOTH && args->mrows_collapse!=COLLAPSE_ANY )
            {
                if ( !(bcf_get_variant_types(line) & args->mrows_collapse) ) split = 0;
            }
            if ( split && line->n_allele>2 )
            {
                args->nsplit++;
                split_multiallelic_to_biallelics(args, line);
                for (j=0; j<args->ntmp_lines; j++)
                    normalize_line(args, &args->tmp_lines[j]);
            }
            else
                split = 0;
        }
```
So whether you use `both` (corresponding to `COLLAPSE_BOTH`) or `any` (corresponding to `COLLAPSE_ANY`) makes no difference in the logic of the code.

**Comment by lourdesrosano** [comment]
> So whether you use `both` (corresponding to `COLLAPSE_BOTH`) or `any` (corresponding to `COLLAPSE_ANY`) makes no difference in the logic of the code.

@freeseek Thanks a lot!! Also, for such a detailed and fast reply; I really appreciate it 😄
