### ISSUE TITLE
FIXME: <chr>:<pos> .. idx=-<int>, ori_pos=<pos>, len=60, off=0

### ISSUE THREAD

**Issue by har-wradim** [samtools/bcftools#400]
When using `bcftools consensus` I occasionally receive error messages of the following type:

    $ samtools faidx myref.fa someregion | bcftools consensus -s mysample -i mycalled.vcf.gz
    FIXME: <chr>:<pos> .. idx=-<int>, ori_pos=<pos>, len=60, off=0

E.g.:

    FIXME: 24:1178158 .. idx=-5, ori_pos=1178162, len=60, off=0
    FIXME: 24:1470641 .. idx=-5, ori_pos=1470645, len=60, off=0
    FIXME: 24:2810110 .. idx=-4, ori_pos=2810113, len=60, off=0
    FIXME: 24:2905901 .. idx=-5, ori_pos=2905905, len=60, off=0

Corresponding vcf records are all indels and look as follows:

    24      1178158 .       GTTTTTTTTTT     GTTTTTT 228     .       DP=98;IDV=92;IMF=0.474227;INDEL;MQ0F=0;MQSB=1;SGB=-0.693145;VDB=1.49041e-18;AC=2;AN=2;DP4=0,0,30,11;MQ=40       GT:PL   1/1:255,123,0
    24      1470641 .       AGGGGG  AGG,AGGG        65      .       DP=7;IDV=6;IMF=0.15;INDEL;MQ0F=0;MQSB=1;SGB=-0.616816;VDB=0.000560625;AC=1,1;AN=2;DP4=0,0,1,5;MQ=40     GT:PL   1/2:123,43,34,93,0,84
    24      2810110 .       ACTGTGTCTGTGT   ACTGTGT 197     .       DP=44;IDV=42;IMF=0.688525;INDEL;MQ0F=0;SGB=-0.693146;VDB=5.26142e-10;AC=2;AN=2;DP4=0,0,42,0;MQ=40       GT:PL   1/1:224,126,0
    24      2905901 .       AGAAAAAAAATGA   AA,A    193     .       DP=112;IDV=94;IMF=0.606452;INDEL;MQ0F=0;MQSB=1;SGB=-0.693147;VDB=2.06881e-20;AC=1,1;AN=2;DP4=0,0,83,6;MQ=40     GT:PL   1/2:255,255,45,255,0,235

The mycalled.vcf.gz file was produced with `bcftools call -mv -Oz -o mycalled.vcf.gz mysorted.vcf` with mysorted.vcf coming ultimately from `samtools mpileup`.

What exactly is causing this issue? What are the potential remedies?

**Comment by pd3** [comment]
Any chance you could provide a small test case to reproduce the error?

**Comment by har-wradim** [comment]
@pd3  The error is tagged 'FIXME': see [line 414](https://github.com/samtools/bcftools/blob/master/consensus.c#L414) in consensus.c (unchanged in [your fork](https://github.com/pd3/bcftools/blob/develop/consensus.c#L414)), so I guess it must be a well-known issue, but if you like I can try to build a minimalistic example.

**Comment by pd3** [comment]
Yeah, I know where it is happening. However, it would be helpful to see the data in order to understand why it is happening. Thanks

**Comment by matt-shenton** [comment]
I am experiencing this error too.

I am trying to output consensus sequence for regions in a gff file, using vcf files that each contain information for only one sample (after subsetting them by sample).

I think that the error occurs if there is an indel outside of the required sequence. e.g. generating the sequence with 
samtools faidx /home/user/genome.fasta Chr06:4446988-4447160 | bcftools consensus .... etc

an indel which occurs in the vcf file at Chr06:4446986 ACCTCCTCCTCCTCCTCCTCC ->	ACCTCCTCCTCCTCCTCC shortens the sequence by 3 bases, and seems to cause the problem.

I am still testing, but maybe can get around this by outputting 100bp either side and trimming them afterwards.

Hope this is helpful

cheers
Matt

**Comment by pd3** [comment]
I believe this commit should fix the problem https://github.com/pd3/bcftools/commit/965cf4b443a657b804c8e2abf433f66264f790e8. This was helpful, thank you.

**Comment by matt-shenton** [comment]
Thanks a lot. It seems to solve the problem. 
Best wishes

Matt

**Comment by wenyuhaokikika** [comment]
Sorry, I still have doubts about this question.

I am using the latest version 1.17 version.

```sh
$ bcftools -v                                                
bcftools 1.17
Using htslib 1.17
Copyright (C) 2023 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
My mutation comes from [gatk](https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels-) pipeline, it will eventually provide an all .vcf.gz file.

The mutation file is like this (the eighth column "info" is omitted here because it is too long):
```sh
$ zcat all.vcf.gz  | grep -v '^##' | csvcut -t -c 1-7,9 | csvformat -T  | head
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  FORMAT
14      18603014        .       T       C       183.64  PASS    GT:AD:DP:GQ:PL
14      18605722        .       T       C       241.64  PASS    GT:AD:DP:GQ:PGT:PID:PL:PS
14      18605723        .       T       A       241.64  PASS    GT:AD:DP:GQ:PGT:PID:PL:PS
14      18605767        .       G       GAAC    252.6   PASS    GT:AD:DP:GQ:PL
14      18605931        .       C       T       438.64  PASS    GT:AD:DP:GQ:PL
14      18978530        .       T       TA      86.6    PASS    GT:AD:DP:GQ:PL
14      19402316        .       T       C       1760.64 PASS    GT:AD:DP:GQ:PL
14      19402341        .       T       G       289.64  PASS    GT:AD:DP:GQ:PL
14      19402349        .       T       C       2212.64 PASS    GT:AD:DP:GQ:PL
```
I want to mutate some dna fragments according to a vcf file, these dna fragments are similar to:
```sh
$ head -10 ./cds.fa
>CHR_HSCHR7_2_CTG6:142847306-142847317 transcript_id:ENST00000631435.1;rank:1
GGGACAGGGGGC
>CHR_HSCHR7_2_CTG6:142847306-142852306 transcript_id:ENST00000631435.1;rank:2
GGGACAGGGGGC
>14:22438547-22438554 transcript_id:ENST00000415118.1;rank:1
GAAATAGT
>14:22438547-22443547 transcript_id:ENST00000415118.1;rank:2
GAAATAGT
>14:22449113-22449125 transcript_id:ENST00000448914.1;rank:1
ACTGGGGGATACG
```
And it has a corresponding bed file:
```sh
CHR_HSCHR7_2_CTG6       142847306       142847317       1       ENST00000631435.1       GGGACAGGGGGC
CHR_HSCHR7_2_CTG6       142847306       142852306       2       ENST00000631435.1       GGGACAGGGGGC
14      22438547        22438554        1       ENST00000415118.1       GAAATAGT
14      22438547        22443547        2       ENST00000415118.1       GAAATAGT
14      22449113        22449125        1       ENST00000448914.1       ACTGGGGGATACG
14      22449113        22454113        2       ENST00000448914.1       ACTGGGGGATACG
14      22439007        22439015        1       ENST00000434970.2       CCTTCCTAC
14      22439007        22444007        2       ENST00000434970.2       CCTTCCTAC
7       142786213       142786224       1       ENST00000632684.1       GGGACAGGGGGC
7       142786213       142791213       2       ENST00000632684.1       GGGACAGGGGGC
CHR_HSCHR14_3_CTG1      105866322       105866332       1       ENST00000632524.1       CTAACTGGGGA
CHR_HSCHR14_3_CTG1      105861322       105866322       2       ENST00000632524.1       CTAACTGGGGA
CHR_HSCHR14_3_CTG1      105881805       105881824       1       ENST00000633009.1       GGTATAGTGGGAGCTACTAC
CHR_HSCHR14_3_CTG1      105876805       105881805       2       ENST00000633009.1       GGTATAGTGGGAGCTACTAC
CHR_HSCHR14_3_CTG1      105882310       105882327       1       ENST00000634070.1       GGGTATAGCAGCGGCTAC
CHR_HSCHR14_3_CTG1      105877310       105882310       2       ENST00000634070.1       GGGTATAGCAGCGGCTAC
```
First, I filter the mutations based on the bed file, and removed those mutations that did not occur in the dna region.
I only keep mutations in the vcf file that are in the bed range
```sh
bcftools view -R ./cds.bed ./dna-seq-gatk-variant-calling/results/annotated/all.vcf.gz  | bcftools view -f 'PASS,.' | bgzip -c > all.vcf.gz && tabix all.vcf.gz
```

When i run the command the error occurs
```sh
$ bcftools consensus -f ./cds.fa ./all.vcf.gz -o mutated.fa
Warning: Sequence "CHR_HSCHR7_2_CTG6" not in ./all.vcf.gz
Warning: Sequence "CHR_HSCHR7_2_CTG6" not in ./all.vcf.gz
FIXME: 14:22438694 .. idx=147, ori_pos=22438546, len=8, off=0
```
As shown below,，I found that there is no error when I run it alone, but this error occurs when two dna sequences appear at the same time, why?

```sh
$ echo ">14:22449113-22449125 transcript_id:ENST00000448914.1;rank:1\nACTGGGGGATACG\n" | bcftools consensus all.vcf.gz
>14:22449113-22449125 transcript_id:ENST00000448914.1;rank:1
ACTGGGGGATACG
Applied 0 variants

$ echo ">14:22438547-22443547 transcript_id:ENST00000415118.1;rank:2\nGAAATAGT\n" | bcftools consensus all.vcf.gz
>14:22438547-22443547 transcript_id:ENST00000415118.1;rank:2
GAAATAGT
Applied 0 variants

$ echo ">14:22438547-22443547 transcript_id:ENST00000415118.1;rank:2\nGAAATAGT\n>14:22449113-22449125 transcript_id:ENST00000448914.1;rank:1\nACTGGGGGATACG\n" | bcftools consensus all.vcf.gz
>14:22438547-22443547 transcript_id:ENST00000415118.1;rank:2
FIXME: 14:22438694 .. idx=147, ori_pos=22438546, len=8, off=0
```
I don't understand why this happens, looking forward to your reply, thank you~~~
