### ISSUE TITLE
segfault on bcftools merge

### ISSUE THREAD

**Issue by martiliasf** [samtools/bcftools#401]
$ gdb bcftools
GNU gdb (GDB) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bcftools...done.
(gdb) r merge -m snps -O b 352-1030-clean.recode.bcf 352-1035-clean.recode.bcf 354-1036-clean.recode.bcf
Starting program: /nas02/apps/samtools-1.3/bin/bcftools merge -m snps -O b 352-1030-clean.recode.bcf 352-1035-clean.recode.bcf 354-1036-clean.recode.bcf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000041c699 in merge_info (args=0x70e010, out=0x1b43bb0) at vcfmerge.c:1040
1040             const char *key = hdr->id[BCF_DT_ID][inf->key].key;
(gdb) bt 40
#0  0x000000000041c699 in merge_info (args=0x70e010, out=0x1b43bb0) at vcfmerge.c:1040
#1  0x000000000041e566 in merge_line (args=0x70e010) at vcfmerge.c:1529
#2  0x000000000041ec47 in merge_buffer (args=0x70e010) at vcfmerge.c:1857
#3  0x000000000041f3e8 in merge_vcf (args=0x70e010) at vcfmerge.c:1937
#4  0x000000000041fabd in main_vcfmerge (argc=8, argv=0x7fffffffd610) at vcfmerge.c:2062
#5  0x0000003feea1d9f4 in __libc_start_main () from /lib64/libc.so.6
#6  0x000000000040c4d9 in _start ()

**Comment by pd3** [comment]
Thanks for the bug report. Any chance you could provide a small test case to reproduce the error?
Also, there is an improved version of the merge command which has not integrated into the main repository yet. Maybe you could try if that works for you in the meantime?
http://pd3.github.io/bcftools/
