### ISSUE TITLE
Bcftools merge: Reference for missing genotype?

### ISSUE THREAD

**Issue by Rmulet** [samtools/bcftools#402]
Vcftools vcf-merge has an option (-R) to use REF allele (0/0) instead of the default missing genotype. To the best of my knowledge, this feature is not available on Bcftools, which means that any variant not present in one of the files will be treated as missing information in the merge. However, in several situations this is not what we want; for instance, when merging data from different populations it is reasonable to assume that positions without variation in one population are monomorphic.

Thus, I believe it would be a very useful addition, since now there is no choice other than using vcf-merge if one wants to achieve that result. If such a feature is already present in bcftools merge, I apologize for the inconvenience.

**Comment by pd3** [comment]
Please use the `setGT` plugin to replace the missing genotypes with REF

     bcftools +setGT merged.bcf -Ob -o filled.bcf -- -t . -n 0

**Comment by Rmulet** [comment]
Thanks a lot for the quick response. I did not know this feature, which definitely comes in handy. Nevertheless, replacing all the missing genotypes with REF after the merger affects all variants, not only those that are not present in one of the two files. In a situation like the one I described, that means that any positions where the missing genotype was really unknown will be interpreted as "0".

To further clarify on this, I give an example:

> **Population 1:**
> 22	16056115		rs587705870	G	A	.	.	.	GT	0	1
> 22	16056117		rs587767130	T	C	.	.	.	GT	0	1
> 22	16056120	rs587638992	G	.	.	.	.	GT	0	.
> 
> **Population 2:**
> 22	16056115		rs587705870	G	A	.	.	.	GT	0	1
> 22	16056120	rs587638992	G	A	.	.	.	GT	0	1
> 
> **Merger:**
> 22	16056115		rs587705870	G	A	.	.	.	GT	0	1	0	1
> 22	16056117		rs587767130	T	C	.	.	.	GT	0	0	0	1
> 22	16056120	rs587638992	G	.	.	.	.	GT	0	.	0	1

As I first explained, rs587767130 can be assumed to be 0 in the two individuals of the population 1 because no variants were detected in that group, and hence it does not appear in the VCF. However, it would not make sense to consider rs587638992 also as 0 in the individual 2 of the population 1 because that information was originally missing; i.e. we do not know whether or not it has a variant.

This is possible with vcf-merge -R, but it cannot be immediately achieved with bcftools +setGT to the best of my understanding.

**Comment by pd3** [comment]
OK, I added the option `-0, --missing-to-ref`, it is available from http://pd3.github.io/bcftools/

**Comment by Rmulet** [comment]
Thank you very much for the quick implementation of this new feature - this is exactly what I was looking for. I have just tried it and it works as intended.

**Comment by llevar** [comment]
+1 for this feature. Any ETA on when this will get merged?

**Comment by jodyhey** [comment]
This issue was for the following:
merging vcfs in a way that individuals with zero data at a site where listed with the reference,  i.e. 0/0
AND individuals with data that had ./.  where retained as ./.  
How do we implement this with current plugins?

**Comment by creepyorange** [comment]
> This issue was for the following: merging vcfs in a way that individuals with zero data at a site where listed with the reference, i.e. 0/0 AND individuals with data that had ./. where retained as ./. How do we implement this with current plugins?

Is there any progress on this problem? What's the best way to solve it?

**Comment by pd3** [comment]
Does the `bcftools merge -0` option not work? If so, can you open a new issue?

**Comment by creepyorange** [comment]
> Does the `bcftools merge -0` option not work? If so, can you open a new issue?

Oh, it does in fact. sorry for bothering
