### ISSUE TITLE
bcftools filter segfault

### ISSUE THREAD

**Issue by simonohanlon101** [samtools/bcftools#406]
Something changed between `Version: 1.2-11-g70f0cec-dirty (using htslib 1.2.1-39-g5ffc4a2)` and `Version: 1.3-36-g47e811c (using htslib 1.3-52-g33de0e9)` which breaks the filtering, specifically in my case, of the `FILTER` field. This may be related to having more than one filter in a VCF_4.1 file but I'm not sure. Running this filter command:
    `bcftools filter -S0 -e 'FILTER == "SNP_FILTER"' /mnt/files/filter.test.vcf`

Using the latest version of `bcftools` on a small test VCF reliably produces the following segfault:

> [1]    21989 segmentation fault (core dumped)  bcftools filter -S0 -e 'FILTER == "SNP_FILTER"' /mnt/files/filter.test.vcf

I have attached the test VCF (~27Kb which contains a header and around the first 70 positions). `bcftools 1.2` filters this file as expected.
[filter.test.vcf.zip](https://github.com/samtools/bcftools/files/212824/filter.test.vcf.zip)

**Comment by jmarshall** [comment]
Appears to have been caused by 8cc5c49ad979f58d718b917543393b44a59dc1f6.

**Comment by mcshane** [comment]
Thanks for the test case!
