### ISSUE TITLE
bcftools normalization error for chr position 1

### ISSUE THREAD

**Issue by TNalpat** [samtools/bcftools#410]
bcftools having Segmentation fault  while performing normalization.  The variant is at the start of the chromosome. Following is the entry from vcf file.

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  GS000038320-ASM
chr17   1       .       AAGC    AAAGC   -1      PASS    NS=1;LO=13311023        GT:GQ:HQ:LocId  1/.:-1:-1,-1:13311023

See attached vcf file

[masterVarBeta-GS000038320-ASM.tsv.decompose_chr17.vcf.txt](https://github.com/samtools/bcftools/files/218005/masterVarBeta-GS000038320-ASM.tsv.decompose_chr17.vcf.txt)

Thanks

Thomas

**Comment by jmarshall** [comment]
Please also show us the norm command line and options that leads to the segfault.

**Comment by TNalpat** [comment]
This is the command line :
bcftools norm -c w  -f  build37.fa -o out.norm.vcf  masterVarBeta-GS000038320-ASM.tsv.decompose_chr17.vcf

Reference genome is NCBI build 37 from complete genomics (ftp://ftp.completegenomics.com/ReferenceFiles/build37.fa.bz2) .
I have tried this for several other vcf file  and this issue occurring only when a variant present at the first position of the chromosome.

**Comment by jmarshall** [comment]
Thanks for the bug report.  This has already been fixed (by bf38eac19fbaede4fe9c1f2c17c061747c665ab9), so I guess this is effectively the same problem as #385.

**Comment by TNalpat** [comment]
Thanks
