### ISSUE TITLE
Options -r and -R behave differently

### ISSUE THREAD

**Issue by sephraim** [samtools/bcftools#411]
Hello,

It appears that specifying a chromosomal region with `-r` will include the starting position (e.g. `[start, end]` ), but using the `-R` option to specify the same region in a file will not include the start position (e.g. `(start, end]` ).

For example, let's say I have the following variant in my VCF (e.g. `my.vcf.gz`):

    M   7445   A   G

If I run the following command, then the above variant will be included in the result:

    bcftools view -r M:7445-7513 my.vcf.gz

I can have the same region in a BED file (e.g. `my.bed`) like follows:

    M   7445   7513

Now if I run the following command, the above variant will not be included in the result:

    bcftools view -R my.bed my.vcf.gz

I am using bcftools v1.3. Thanks for your help!

**Comment by pd3** [comment]
BED files use a different convention. While in `-r chr:beg-end` the coordinates are 1-based and inclusive, bed files use  half-open 0-based intervals `[beg-1,end)`. A quick solution is to `mv my.bed my.tab`, which should interpret the coordinates consistently with `-r`.

**Comment by sephraim** [comment]
Thank you @pd3. That worked for me. And thank you @mcshane for the clarification in the docs. You've both been very helpful.
