### ISSUE TITLE
bcftools annotate error - Incorrect number of values (2) for the MLEAC tag

### ISSUE THREAD

**Issue by drmjc** [samtools/bcftools#413]
Hi,
I'm trying to annotate a GATK HaplotypeCaller+GenotypeGVCFs v3.3 VCF file, using `bcftools annotate`, and receive the following message:

    $ bcftools annotate -O z -a customanno.vcf.gz -c INFO -o $out $vcf
    Incorrect number of values (2) for the MLEAC tag at 1:110168888

Dropping the INFO/MLEAC tag doesn't help (`bcftools annotate -x INFO/MLEAC ...`), and furthermore, `MLEAC` is defined as `Number=A` in the header, and appears to have the correct number (ie 1) of values for a monoallelic SNP. Have I missed something?

cheers,
Mark

Relevant excerpt from the VCF file below:

    ##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
    1	110162918	rs28362580	T	C	5538.79	.	AC=14;AF=0.304;AN=46;BaseQRankSum=-1.280e+00;ClippingRankSum=-3.630e-01;DB;DP=804;FS=1.750;InbreedingCoeff=-0.2321;MLEAC=14;MLEAF=0.304;MQ=60.00;MQ0=0;MQRankSum=0.626;QD=13.44;ReadPosRankSum=0.589;SOR=0.578	GT:AD:DP:GQ:PL	0/1:17,14:31:99:369,0,446	...
    1	110163076	rs6669802	A	G	15172.45	.	AC=36;AF=0.783;AN=46;BaseQRankSum=-2.671e+00;ClippingRankSum=0.630;DB;DP=741;FS=2.183;InbreedingCoeff=-0.0222;MLEAC=36;MLEAF=0.783;MQ=60.00;MQ0=0;MQRankSum=-1.770e-01;QD=22.09;ReadPosRankSum=0.534;SOR=0.687	GT:AD:DP:GQ:PGT:PID:PL	1/1:0,34:34:99:.:.:1045,101,0	...0/1:18,12:30:99:1|0:110163075_C_A:276,0,548	0/1:16,17:33:99:.:.:473,0,461	1/1:0,23:23:69:.:.:809,69,0	1/1:0,21:21:62:.:.:623,62,0
    1	110163879	rs28362581	G	A	5944.79	.	AC=14;AF=0.304;AN=46;BaseQRankSum=-5.000e-01;ClippingRankSum=0.136;DB;DP=744;FS=0.372;InbreedingCoeff=-0.2321;MLEAC=14;MLEAF=0.304;MQ=60.00;MQ0=0;MQRankSum=0.224;QD=15.44;ReadPosRankSum=0.136;SOR=0.654	GT:AD:DP:GQ:PL	0/1:14,17:31:99:390,0,352	...
    1	110164657	rs12046107	A	G	7686.79	.	AC=14;AF=0.304;AN=46;BaseQRankSum=-5.100e-01;ClippingRankSum=0.285;DB;DP=862;FS=4.080;InbreedingCoeff=-0.2321;MLEAC=14;MLEAF=0.304;MQ=60.00;MQ0=0;MQRankSum=-1.750e-01;QD=15.62;ReadPosRankSum=0.835;SOR=0.675	GT:AD:DP:GQ:PL	0/1:15,24:39:99:656,0,343	...

    $ bcftools -v
    bcftools 1.2
    Using htslib 1.2

**Comment by pd3** [comment]
The excerpt does not show the position 1:110168888. Can you show the output of

     bcftools query -f'%CHROM %POS  %ALT %MLEAC\n' -r 1:110168888 customanno.vcf.gz

and

      bcftools query -f'%CHROM %POS  %ALT %MLEAC\n' -r 1:110168888 $vcf

**Comment by drmjc** [comment]
Hi Petr,
    bcftools query -f'%CHROM %POS  %ALT %MLEAC\n' -r 1:110168888 customanno.vcf.gz
> 1 110168888  G 1,0

    bcftools query -f'%CHROM %POS  %ALT %MLEAC\n' -r 1:110168888 $vcf
> 1 110168888  G 40

customanno.vcf.gz shouldn't have MLEAC, so this was a surprise. I somehow overwrote my customanno.vcf.gz with a regular vcf. It all works fine now, so apologies for the noise.

cheers,
Mark

**Comment by pd3** [comment]
OK good, glad the problem is solved.
