### ISSUE TITLE
bcftools multi-allelic split: vcf with multiple sample.

### ISSUE THREAD

**Issue by TNalpat** [samtools/bcftools#419]
Hi,
I am trying to split/normalize a multi-sample vcf file with bcftools v1.3.1 and encountered  following error:
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:10415
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:10616
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:15903
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:19776
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:20729
[E::vcf_parse_format] Invalid character '/' in 'GQ' FORMAT field at chr1:21319

This was not an issue with bcftools v1.3. I have attached my vcf file.

[test.vcf.txt](https://github.com/samtools/bcftools/files/249405/test.vcf.txt)

Here is the command I have used:
bcftools norm -m-both -o  test_dc.vcf test.vcf.txt

Thank you

Thomas

**Comment by mcshane** [comment]
1.3.1 closed a number of VCF parsing holes that existed previously. In your case, you seem to have an invalid VCF file. Taking the first FORMAT record at position chr1:10415, you have
```
GT:AD:DP:GQ:PGT:PID:PL:OGT:OZYG	./.:13,0:13:./.:unknown
```
It looks like the GQ value has been omitted and this is saying the `GQ=./.` where I think this is supposed to be for the OGT field. The spec allows for dropping unknown trailing fields from the FORMAT field, but not in the middle of the list.

It looks to me like some tool has added `OGT:OZYG` values to the end of the FORMAT fields without padding out the missing fields in between.

**Comment by TNalpat** [comment]
Thanks for the clarification.
