### ISSUE TITLE
Problem reading some INFO fields

### ISSUE THREAD

**Issue by gchauhan83** [samtools/bcftools#424]
Few rows from the meta information section for AC and AF:

```
##INFO=<ID=AC,Number=1,Type=Float,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">									
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">									
```

When I run the command:
bcftools annotate -x ID test.vcf.gz

I get the error:

[W::vcf_parse] INFO 'AC' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'AF' is not defined in the header, assuming Type=String
Encountered error, cannot proceed. Please check the error output above.

Why is it not able to read an input file despite the presence of the right information in the meta information section?

Thanks for your suggestion.

**Comment by pd3** [comment]
That is odd, I suspect there is some problem with your VCF which you did not notice. Can you provide a small example for testing? By the way, the AC tag should be an integer.
