### ISSUE TITLE
Merging VCFs with non-matching REF/ALT allele and extracting desired fields of FORMAT/genotype field

### ISSUE THREAD

**Issue by gchauhan83** [samtools/bcftools#425]
If I try and merge two VCFs which do not match for REF and ALT allele at a position the program stops. But other popular tools do allow this feature by creating new records. Is there a way to do this in bcftools.

How can I extract desired field of  FORMAT/genotype fields for a particular set of samples using the popular "query" option.

Thanks for your help.

Ganesh

**Comment by pd3** [comment]
Not sure if I understand. Is this about merging SNPs and indels or different types of indels? Or about incorrect REF column, so that at the same position a different base is present across the VCFs?

**Comment by gchauhan83** [comment]
It is the second one: "incorrect REF column, so that at the same position a different base is present across the VCFs".

This I think will enable one to merge VCFs even if incorrect REF is present at some places, rather than throwing an error and exiting. Later the file can be parsed to remove the variants present only in the send set of samples. OR do you have a feature to allow merger  even when REF is wrong, so that at least the ones where the REF is correct, those variants get added.

Any suggestion on:
How can I extract desired field of FORMAT/genotype fields for a particular set of samples using the popular "query" option.

Thanks for getting back to me.

**Comment by pd3** [comment]
Sorry, we do not have a tool for merging such VCFs. I don't even know how it would and could work, if the reference allele was arbitrary. If your VCF uses Illumina's TOP notation, it can be flipped using this plugin
https://github.com/pd3/bcftools/blob/develop/plugins/fixref.c
