### ISSUE TITLE
Error reading FORMAT fields with integer values like 0.21 & 0.54 (having a ".")

### ISSUE THREAD

**Issue by gchauhan83** [samtools/bcftools#426]
Hi,

It seems if FORMAT fields have integer values with "." (eg 0.21 and 0.54) in them, the "query" function does not work. Is there a way to deal with this.
Also can we allow -ve values (<0) like -0.9, -0,6 etc.

Many thanks for your help.

Best
Ganesh

**Comment by gchauhan83** [comment]
Hi,

I used the following commands:
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' -r 1:3220382 test2.vcfcombine.vcf.gz

The error message was:
Invalid character '.' in 'BT' FORMAT field at 1:3220382

Thanks.

**Comment by pd3** [comment]
0.21 is not an integer, so it rightly complains about the unexpected "." character. It should be defined as float in the header.
