### ISSUE TITLE
view -r gives an error 'Failed to open input.vcf not compressed with bgzip'

### ISSUE THREAD

**Issue by MissTinger** [samtools/bcftools#429]
Everything is in the title. The command:

`bcftools view -r chr1:5034265-5123451 -o truncated.vcf input.vcf`

gives the error:
> Failed to open input.vcf: not compressed with bgzip

 This probably comes from htslib...

**Comment by pd3** [comment]
The file needs to indexed with `tabix` or `bcftools index`, this requires `bgzip` compression.

**Comment by MissTinger** [comment]
Thank you for this information but then, the manual is not explicit or not up to date:

In http://www.htslib.org/doc/bcftools.html#common_options:
> Uncompressed files are stored in memory, while bgzip-compressed and tabix-indexed region files are streamed.
Which suggests that -r or -R should work with uncompressed files.

In http://www.htslib.org/doc/bcftools.html#index:
> `bcftools index [OPTIONS] <in.bcf>|<in.vcf.gz>`
This suggests that VCF files need to be compressed to be indexed but not BCF files. 

Furthermore, when trying to index an uncompressed BCF file, I get the following error: 
> unknown filetype; expected bgzip compressed VCF or BCF
Which is not necessarily very clear about the necessity of compression of BCF files... 

Anyway, thank you for your quick answer, and for developing such good programs.

**Comment by pd3** [comment]
I see that may be confusing. The text above refers to compressed/uncompressed region files. However, for random access to VCF and BCF, the data file always needs to be compressed and indexed.

**Comment by jkbonfield** [comment]
I assume that it is permissable to compress with level 0, wrapping the data up in a bgzf format but without using actual deflate to do compression?  This is how samtools view -u works to output uncompressed BAM.  It's still a bgzf container even when uncompressed.

Can BCF handle that?

**Comment by pd3** [comment]
Yes, as long as the data is wrapped in BGZF blocks, it should work. We output plain file with -u though, without the bgzf containers.

**Comment by jkbonfield** [comment]
Hmm, is there any reason why BCF doesn't do the same as BAM with regards to -u?  It seems a bit of an odd divergence and if BCF -u generates files that cannot be randomly accessed right now then it also seems like a bug.

Are there tools out there that don't support compressed BCF at all? (Ie wouldn't access a level-0 bgzf BCF?)

**Comment by pd3** [comment]
No, it is not a bug and there is a reason. GATK could not process bgzip wrapped files at the time (I don't know the status now). Philosophically, uncompressed VCF should have the same meaning as uncompressed BCF, 0-level compression is a different thing. We can easily add a switch to allow 0-level compression if there is a need.
