### ISSUE TITLE
bcftools merge : not able to handle vcf called with haploid

### ISSUE THREAD

**Issue by ishengtsai** [samtools/bcftools#430]
Hi,

I try to merge vcf generated by freebayes assuming the strains are haploid and the following error occurred:

$ ~/bin/bcftools/bcftools merge -m all -O v -o scaff0001.vcf freebayes.PNOK.scaff0001.C.d.raw.vcf.gz freebayes.PNOK.scaff0001.C.h.raw.vcf.gz
Incorrect number of DPR fields (2) at PNOK.scaff0001.C:235, cannot merge.

The line that cause error is shown here:

PNOK.scaff0001.C        235     .       AC      ACTC    8.06424e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=29;AO=25;CIGAR=1M2I1M;DP=1234;DPB=1267.5;DPRA=1.42742;EPP=3.09716;EPPR=44.5415;GTI=0;LEN=2;MEANALT=1;MQM=19.04;MQMR=28.0613;NS=29;NUMALT=1;ODDS=62.7697;PAIRED=0.24;PAIREDR=0.826987;PAO=8.5;PQA=0;PQR=0;PRO=8.5;QA=864;QR=44110;RO=1208;RPL=0;RPP=57.2971;RPPR=58.692;RPR=25;RUN=1;SAF=12;SAP=3.09716;SAR=13;SRF=252;SRP=893.918;SRR=956;TYPE=ins      GT:DP:DPR:RO:QR:AO:QA:GL        0:2:2,0:2:68:0:0:0,-4.95884

Is there something that can be fixed?

Best,
Jason

**Comment by mcshane** [comment]
I think you'll find the issue is that `DPR` is set as `Number=A` in the header, whereas the number of values being added by freebayes is `Number=R`. See ekg/freebayes#267. You can get around this by fixing the header by replacing `Number=A` with `Number=R` for the `DPR` header line.

**Comment by pd3** [comment]
Another possibility is to remove the fields using `bcftools annotate -x`, if you don't need them.
