### ISSUE TITLE
Can not concat more than 1018 files

### ISSUE THREAD

**Issue by mmoisse** [samtools/bcftools#432]
I encountered a issue when trying to concating more than 1018 files. Until 1018 files I have no issues:

    $ bcftools concat -a -f <(head -n 1018 files_to_concat.txt ) -Ob -o test.bcf                                                                                                       
    $ ls -lah
    -rw-r--r--  1 user user 1.2M May 30 19:03 files_to_concat.txt
    -rw-r--r--  1 user user 802K May 31 09:32 test.bcf

    $ bcftools concat -a -f <(tail -n 1018 files_to_concat.txt ) -Ob -o test.bcf
    $ ls -lah
    -rw-r--r--  1 user user 1.2M May 30 19:03 files_to_concat.txt
    -rw-r--r--  1 user user 779K May 31 09:33 test.bcf

But once I go above I get an error about an index that could not be loaded, although it exists:

    $ bcftools concat -a -f <(head -n 1019 files_to_concat.txt ) -Ob -o test.bcf                                                                                                       
    Failed to open chunks/tmp/merged.chr10-98192563-98192719.BE_421.flt.bcf: could not load index
    $ ls -lah chunks/tmp/merged.chr10-98192563-98192719.BE_421.flt.bcf*
    -rw-r--r-- 1 user user 3.0K May 30 17:21 chunks/tmp/merged.chr10-98192563-98192719.BE_421.flt.bcf
    -rw-r--r-- 1 user user  103 May 30 17:28 chunks/tmp/merged.chr10-98192563-98192719.BE_421.flt.bcf.csi

    $ bcftools concat -a -f <(tail -n 1019 files_to_concat.txt ) -Ob -o test.bcf
    Failed to open chunks/tmp/merged.chrY-2368857-2368966.BE_421.flt.bcf: could not load index
    $ ls -lah chunks/tmp/merged.chrY-2368857-2368966.BE_421.flt.bcf*
    -rw-r--r-- 1 user user 2.1K May 30 17:24 chunks/tmp/merged.chrY-2368857-2368966.BE_421.flt.bcf
    -rw-r--r-- 1 user user   71 May 30 17:30 chunks/tmp/merged.chrY-2368857-2368966.BE_421.flt.bcf.csi

I also checked if the index was corrupted but this was not the case:

    $ bcftools concat -a -f <(head -n 1019 files_to_concat.txt | tail -n 5 ) -Ob -o test.bcf
    $ ls -lah
    -rw-r--r--  1 user user 1.2M May 30 19:03 files_to_concat.txt
    -rw-r--r--  1 user user 4.3K May 31 09:42 test.bcf
    
    $ bcftools concat -a -f <(tail -n 1019 files_to_concat.txt | tail -n 5 ) -Ob -o test.bcf
    $ ls -lah
    -rw-r--r--  1 user user 1.2M May 30 19:03 files_to_concat.txt
    -rw-r--r--  1 user user 2.3K May 31 09:40 test.bcf

**Comment by pd3** [comment]
When `concat` is run with `-a`, the program needs to keep all files open at the same time. There is a system limit on how many files can be open simultaneously, this can be checked and changed  by `ulimit`.

**Comment by mmoisse** [comment]
My ulimit -Sn is indeed 1024. In the end I solved it by merging 1000 files at a time.

**Comment by mcshane** [comment]
Closing as a duplicate covered by #376.
