### ISSUE TITLE
Feature request: bcftools missing2ref to consider coverage

### ISSUE THREAD

**Issue by gtamazian** [samtools/bcftools#433]
It would be useful if **missing2ref** considered the variant site coverage by reads to determine whether to replace the missing genotype with the reference homozygous one.

**Comment by pd3** [comment]
Provided that FORMAT/DP or INFO/DP exists, I suppose?

**Comment by gtamazian** [comment]
There may be several options for a source of evidence to check the coverage. FORMAT/DP and INFO/DP sounds good. Other possible options:

- a BAM file;
- a [bedGraph](https://genome.ucsc.edu/goldenpath/help/bedgraph.html) (BED3+1) file;
- a tab-separated file which columns are CHROM, POS and COVERAGE_VALUE;
- a [WIG](https://genome.ucsc.edu/goldenpath/help/wiggle.html) or [bigWig](https://genome.ucsc.edu/goldenpath/help/bigWig.html) file.

**Comment by pd3** [comment]
It could be made quite general: the `setGT` plugin (which is a replacement of `missing2ref`) could be in principle extended to include a new target type "q" (for "query"), defined by an arbitrary boolean expression similar to the standard `-i/-e` options. For example one could write

     bcftools +setGT in.vcf -- -n0 -tq -i 'FMT/DP>0' && GT="."'

The tool should preferably not rely on BAMs. BED and tab files can be used to add annotations to the VCF files in a separate step by `bcftools annotate`.

**Comment by pd3** [comment]
Hi, this is now implemented, a question mark is used instead of "q" proposed above, it can be used like this:
 
      bcftools +setGT test.vcf -- --target-gt ? --new-gt 0 --include GT="./."

Let me know if you find any problems
https://github.com/pd3/bcftools/blob/develop/plugins/setGT.c

**Comment by gtamazian** [comment]
Hi @pd3! Thanks for rapid response. However, I failed to compile **bcftools** from your fork:

```
vcfmerge.c:2426:43: error: use of undeclared identifier 'regidx_parse_reg'; did you mean 'regidx_parse_bed'?
            args->regs = regidx_init(NULL,regidx_parse_reg,NULL,sizeof(char*),NULL);
                                          ^~~~~~~~~~~~~~~~
                                          regidx_parse_bed
htslib/htslib/regidx.h:97:5: note: 'regidx_parse_bed' declared here
int regidx_parse_bed(const char*,char**,char**,reg_t*,void*,void*);   // CHROM,FROM,TO (0-based,right-open)
    ^
vcfmerge.c:2427:18: warning: implicit declaration of function 'regidx_insert_list' is invalid in C99 [-Wimplicit-function-declaration]
            if ( regidx_insert_list(args->regs,args->regions_list,',') !=0 ) error("Could not parse the regions: %s\n", args->regions_list);
                 ^
1 warning and 1 error generated.
make: *** [vcfmerge.o] Error 1
```
I used **htslib** from its main repository:
```
git clone https://github.com/pd3/bcftools.git
cd bcftools/
git clone https://github.com/samtools/htslib.git
make
```

**Comment by pd3** [comment]
You'll need either to clone the whole repository including the htslib submodule as described [here](http://pd3.github.io/bcftools/) or copy just the setGT.c module in your main repo bcftools/plugins.

**Comment by gtamazian** [comment]
I succeeded to compile the experimental **bcftools** branch with the updated **setGT** plugin.

In general **setGT** works fine, but I identified the following bug: `GT="."` and `GT="./."` lead to different results. You may try the following commands:
```
bcftools +setGT setgt_mwe.vcf -- -t ? -n '0/0' -i 'AN>2 && GT="."'
```
and
```
bcftools +setGT setgt_mwe.vcf -- -t ? -n '0/0' -i 'AN>2 && GT="./."'
```
applied to the attached MWE [setgt_mwe.vcf](https://github.com/samtools/bcftools/files/297919/setgt_mwe.vcf.gz).

**Comment by pd3** [comment]
This is expected behavior described in the man page: the -i/-e filtering considers GT="." a missing genotype regardless of phase and ploidy (".|.", "./.", "."). If unhappy with this behavior, please open a separate issue.

**Comment by pd3** [comment]
This has been now made more intuitive by this commit https://github.com/pd3/bcftools/commit/152dfa3f7e86d64182afceace49feb8f90048758, GT="." for exact match and GT~"\." for a regex match.
