### ISSUE TITLE
bcftools annotate to add FORMAT tags to specific samples

### ISSUE THREAD

**Issue by gtamazian** [samtools/bcftools#434]
Can `bcftools annotate` add FORMAT tags for a specific sample? For example, add the NN tag so that
```
... GT:GQ:GQX:DP:DPF:AD	0/1:176:39:27:6:16,11 ...
```
would become
```
... GT:GQ:GQX:DP:DPF:AD:NN	0/1:176:39:27:6:16,11:32 ...
```
for the sample which ID is specified by the `-s` option.

**Comment by pd3** [comment]
Yes, just provide a VCF to the -a option. The sample name has to be the same in both VCFs though, reheader may be required.

**Comment by mcshane** [comment]
Closing. Please reopen if @pd3's suggestion didn't work for you.
