### ISSUE TITLE
Wrong output when "bcftools --regions" uses .tbi index rather than .csi index

### ISSUE THREAD

**Issue by kaspernie** [samtools/bcftools#435]
Possible bug discovered in "bcftools --regions-file" and "bcftools --regions" (v. 1.3.1 and 1.3): Will output wrong positions if a .tbi index is present rather than a .csi index (output may include some correct positions, some extra wrong positions; and some correct positions may be missing)
Workarounds: 1) Create .csi index; 2) Use "bcftools --targets-file" or "bcftools --targets".
### Example with minimal VCF file where "bcftools --regions" gives correct output when using .tbi index

```
rm test.vcf*
echo -e "##fileformat=VCFv4.2\n##contig=<ID=1,length=630000000>\n#CHROM\tPOS\n1\t530000000" | bgzip -c > test.vcf.gz
bcftools index --tbi test.vcf.gz
bcftools view --regions 1:530000000 test.vcf.gz -H > a
rm test.vcf.gz.tbi
bcftools index --csi test.vcf.gz
bcftools view --regions 1:530000000 test.vcf.gz -H > b
rm test.vcf.gz.csi
bcftools view --targets 1:530000000 test.vcf.gz -H > c
wc -l a b c | sed 's/^/: /'
```

:  1 a
:  1 b
:  1 c
:  3 total

```
sort -u a b c | wc -l | sed 's/^/: /'
```

: 1
### Example with minimal VCF file where "bcftools --regions" gives wrong output when using .tbi index and "bcftools  --targets" gives correct output

```
rm test.vcf*
echo -e "##fileformat=VCFv4.2\n##contig=<ID=1,length=630000000>\n#CHROM\tPOS\n1\t540000000" | bgzip -c > test.vcf.gz
bcftools index --tbi test.vcf.gz
bcftools view --regions 1:540000000 test.vcf.gz -H > a
rm test.vcf.gz.tbi
bcftools index --csi test.vcf.gz
bcftools view --regions 1:540000000 test.vcf.gz -H > b
rm test.vcf.gz.csi
bcftools view --targets 1:540000000 test.vcf.gz -H > c
wc -l a b c | sed 's/^/: /'
```

:  0 a
:  1 b
:  1 c
:  2 total

```
sort -u a b c | wc -l | sed 's/^/: /'
```

: 1

**Comment by mcshane** [comment]
This is the old chestnut like samtools/samtools#241 where the TBI/BAI format is not valid for coordinates larger than 2^29, but samtools/tabix/bcftools silently say they succeed in creating them.

**Comment by daviesrob** [comment]
After samtools/htslib#470 the above test results in this:
```
$ ./bcftools index --tbi test.vcf.gz
[E::hts_idx_push] Region 539999999..540000000 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6
index: "test.vcf.gz" is corrupted or unsorted
$ echo $?
255
```

The error message from `index` needs to be fixed.  There's nothing wrong with `test.vcf.gz`, it just can't be represented in a `.tbi` index.
