### ISSUE TITLE
bcftools call on samples consisting of both haploid and diploid

### ISSUE THREAD

**Issue by ishengtsai** [samtools/bcftools#436]
Hi, 

I read the documentations and try to use bcftools to call variants from samples consisting of haploid and diploid. But all the genotype calls of haploid are like diploid (0/0, 0/1, 1/2 etc rather than 0, 1, 2...), and I was wondering if I have passed the files wrongly. Help would be appreciated.

head sampleList.ploidy.txt
718-S1	1
A42	1
KPN112	1
KPN130	2
KPN141	1
KPN163	2
KPN172	2

# command
~/bin/bcftools/bcftools call -vmO v --samples-file sampleList.ploidy.txt -o samtools.PNOK.scaff0001.C.vcf samtools.PNOK.scaff0001.C.bcf

Best,
Jason

**Comment by pd3** [comment]
Hi Jason,

there is a bug in 1.3 (fixed just now by https://github.com/pd3/bcftools/commit/bb2ec1a5188312f76e87ee9b2df433eda497b223) which was introduced by switching to a new way of specifying the ploidy using the --ploidy and --ploidy-file options.  These new switches allow to process the whole chromosome chrX in one go, without the need to call the male PAR and non-PAR regions separately

     bcftools call --ploidy ?  # print list of pre-defined ploidies
     bcftools call --ploidy GRCh37?   # prints the ploidy definition

Petr

**Comment by ishengtsai** [comment]
It now works like a charm! Thank you very much!

Best,
Jason

![image](https://cloud.githubusercontent.com/assets/5182142/16027526/0c8fa06e-3209-11e6-8e9f-eb33b1373bf4.png)

**Comment by ktk002** [comment]
Hello,

We are having the same issue as ishengtsai where we are getting diploid calls instead of haploid as seen here:
1       4       .       AC      ATGAC,ACGTTGAC,ATCGTTGAC        88.4671 .       INDEL;IDV=7;IMF=0.583333;DP=12;VDB=1.07597e-06;SGB=-0.670168;MQ0F=0;AF1=1;AC1=1;DP4=0,0,10,0;MQ=36;FQ=-999      GT:PL   1:191,80,65,129,0,119,169,44,96,163

We have tried rerunning with both bcftools version 1.4 and 1.5, but the bug fixes did not fix this heterogeneous call for us. What are your suggestions?

Thank you,
Kellie

**Comment by pd3** [comment]
Can you please provide a small test case to reproduce the problem?

**Comment by ktk002** [comment]
[bcf.zip](https://github.com/samtools/bcftools/files/1098460/bcf.zip)

Yes, this contains the mpileup file and the bcftools command used on it to replicate this issue was: 
`bcftools call -c -v --ploidy 1 TB1310.2-10.mpileup
`

**Comment by sarahbuzz** [comment]
Hi @pd3,
Looks like this is still an issue in v1.9. Is there a flag/parameter that needs to be input on the `samtools mpileup` call or on the `bcftools` call to ensure haploid variant calling?
Thanks, Sarah
