### ISSUE TITLE
bcftools norm --check-ref not flagging alleles

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#439]
I have a vcf generated from snp chip data via plink. The vcf contains alleles I and D instead of the actual sequence. I tried to use ` --check-ref xw` to remove them but no filtering/warning seems to happen. Is this expected?

`bcftools norm -d any -f GRCh37.fa -N -c wx -O z tmp.vcf.gz > tmp2.vcf.gz`

**Comment by dwaggott** [comment]
A quick workaround is to use standard filters for problematic REF/ALT alleles. This won't catch the SNPs with incorrect REF/ALT due to chip design mapping issues though. That `-c` flag would be helpful.

`bcftools view -e 'REF="N" | REF="I" | REF="D"' tmp.vcf.gz | bcftools norm -d any -f GRCh37.fa -N -O z > tmp2.vcf.gz`

**Comment by pd3** [comment]
This should solve your problem https://github.com/pd3/bcftools/commit/63566bfca6e4f1ef59e8ac357a8eb44fc0ca279d, let me know in case of problems.
