### ISSUE TITLE
ROH output

### ISSUE THREAD

**Issue by mcgml** [samtools/bcftools#451]
Hi,

I'm trying to identify regions of homozygosity in a single consanguineous sample. I used the command: `bcftools roh -s sampleId -T BED VCF`

Here's an example of the output:

> 1	762273  1	3.0
> 1	762472  1	19.8
> 1	876499  1	17.0
> 1	877715  1	22.6
> 1	877831  1	23.0
> 1	878314  1	25.6
> 1	879317  1	27.7
> 1	880238  1	27.9
> 1	880390  1	27.2

How can i convert these single positions into a range of homozygosity? Would removing low quality sites and applying something like circular binary segmentation do the job?

Thanks
Matt

**Comment by pd3** [comment]
Take the whole region and use the average quality, for example like this
https://gist.github.com/pd3/6ad82fdfffcd5afd4af6dcf804e6addd#file-roh-to-range

**Comment by mcgml** [comment]
Thank you!

Matt

**Comment by rernst** [comment]
Just a note for people using the above gist. There is a bug in the script that causes roh regions which contain only one roh position to be printed with a wrong end position (end of previous region).

Small example:
```bash 
cat roh_ouput
X	130872087	1	6.5
X	130873045	1	4.8
X	130875051	0	99.0
X	130875936	1	1.8
X	130878582	1	3.5

cat roh_regions
X	130872087	130873045	1	5.7
X	130875051	130873045	0	99.0
X	130875936	130878582	0	2,7
```

**Comment by pd3** [comment]
Added a comment here https://gist.github.com/pd3/6ad82fdfffcd5afd4af6dcf804e6addd#gistcomment-1917861

**Comment by pd3** [comment]
The script is now updated. Note that with new versions of bcftools it should not be needed.
