### ISSUE TITLE
bcf consensus

### ISSUE THREAD

**Issue by ishengtsai** [samtools/bcftools#453]
Hi,

I am writing to ask about more details in bcftools consensus mode to clarify some points. Please correct me if I am wrong.

haploid: as there is only one haplotype, you have to specify -H 1 in order for it to work. I found that bcftools will give errors to haploid vcfs if this option is not specified. 

bcftools consensus -f ref.fa -s samplename **-H 1** vcf.gz -o samplename.fa 

However, in diploid samples, there are some discrepancies:

-H 1
CTATTA**T**TACTACAAAATTACTCATCATGTTATCATTCAAGATGGTGTGATCATTATATC
-H 2
CTATTA**c**TACTACAAAATTACTCATCATGTTATCATTCAAGATGGTGTGATCATTATATC
-i
CTATTA**T**TACTACAAAATTACTCATCATGTTATCATTCAAGATGGTGTGATCATTATATC

-H 1
TGTCCGTTCCTGTGGTCCGTAGCC**C**TTCCAGTGTACTAAATACTCCACTCGTCTCCTTCG

-H 2
TGTCCGTTCCTGTGGTCCGTAGCC**t**TTCCAGTGTACTAAATACTCCACTCGTCTCCTTCG

-i 
TGTCCGTTCCTGTGGTCCGTAGCC**C**TTCCAGTGTACTAAATACTCCACTCGTCTCCTTCG

Shouldn't -i mode give Y? Does lower letter mean anything?

Additionally, I assume that -H 1 and -H 2 are called after bcftools's phasing, but what about regions that can not be phased?

Best,
Jason

**Comment by ishengtsai** [comment]
Hi , 

Is there suggestions to this issue? We were just wondering if consensus option of different haplotypes are produced after phasing, or were assigned randomly?

Best,
Jason

**Comment by pd3** [comment]
RE the haploid question: You are right that the tool could be smarter and not bother you with the `-H` option when the sample is haploid.

The `H1: T` vs `H2: C` vs `i: T` is worrying. There is no randomness in the process, the output should be 100% reproducible and intuitive. I am not able to reproduce the behavior. Would it be possible to narrow it down to a small test case for debugging?

**Comment by ishengtsai** [comment]
Hi Petr,

Thanks for the reply. I will try to produce a bam file and associated vcf to reproduce this error.

Also, I was wondering if you can  answer my additional question: are the generated haplotype 1 and 2 consensus sequence phased, i.e., the consensus option is really phasing + output consensus ?  What about regions that can't be phased?

Best,
Jason

**Comment by pd3** [comment]
It operates by taking the first or second allele in the GT field, trusting completely that whatever is in the VCF, it is correct. If there are unphased genotypes, they should be filtered first.
