### ISSUE TITLE
Issue in plotting the .vchk file with plot-vcfstats

### ISSUE THREAD

**Issue by muhammadsohailraza** [samtools/bcftools#457]
Hi Everyone,
I am using bcftool-1.3.x and trying to plot the variant statistics from chk file 

plot-vcfstats VQSR_snp99.0_raw_indel_QJ_12SAMPLE.vcf.vchk -p /share_bio/unisvx3/zengchq_group/sohail/_TIBETAN/GATK/SELECTVAR/VCF/plot

ERROR:
The command exited with non-zero status 139:
        python /share_bio/unisvx3/zengchq_group/sohail/_TIBETAN/GATK/SELECTVAR/VCF/plot-plot.py

 at /share_bio/unisvx3/zengchq_group/sohail/Softwares/bcftools-1.3.1/plot-vcfstats line 78
        main::error('The command exited with non-zero status 139:\x{a}\x{9}python /share_b...') called at /share_bio/unisvx3/zengchq_group/sohail/Softwares/bcftools-1.3.1/plot-vcfstats line 282
        main::plot('HASH(0x236b808)') called at /share_bio/unisvx3/zengchq_group/sohail/Softwares/bcftools-1.3.1/plot-vcfstats line 67

I have already the read:
https://github.com/samtools/bcftools/issues/229

and in my plot-vcfstats "if plot_tstv_by_qual and len(dat)>2" issue is already fixed . but still getting thi error.. Could you please look into this..

Thank you!

**Comment by pd3** [comment]
Can you please send us the vchk output?

**Comment by muhammadsohailraza** [comment]
your email id?

**Comment by pd3** [comment]
It's on my profile page. Thanks

**Comment by muhammadsohailraza** [comment]
sent you an e-mail with the title: "Github: Issue in plotting the .vchk file with plot-vcfstats"‏.
Thanks.

**Comment by pd3** [comment]
Thank you for the testing file. The latest version of `plot-vcfstats` works with the file, please download it here https://raw.githubusercontent.com/pd3/bcftools/develop/plot-vcfstats

**Comment by muhammadsohailraza** [comment]
Again error:
I run new "plot-vcfstats", it exited with an error message again:

The command exited with non-zero status 139:
        python plot.py

 at ./plot-vcfstats line 76
        main::error('The command exited with non-zero status 139:\x{a}\x{9}python plot.py\x{a}\x{a}') called at ./plot-vcfstats line 275
        main::plot('HASH(0x19d9cb0)') called at ./plot-vcfstats line 65

**Comment by pd3** [comment]
It does work for me. Assuming we are both using the same version of plot-vcfstats linked above and the same vchk file you send me (VQSR_snp99.0_raw_indel_QJ_12SAMPLE.vcf.vchk), the problem must be in matplotlib version incompatibility. If you `cd` in the output directory and run `python plot.py` manually, you should be able to see more detailed error message.

**Comment by muhammadsohailraza** [comment]
You were right , that was matplotlib problem...  problem solved..  Thank u.!.
