### ISSUE TITLE
bcftools view to subset individuals out of vcf

### ISSUE THREAD

**Issue by elise625** [samtools/bcftools#458]
Hello,

I'm trying to get rid of some subjects from my large vcf file.
In my text file, I listed out the individual ID per row that I wan't to delete from my vcf.
I ran: bcftools view -S idstodelete.txt variants.vcf.gz

but it keeps kicking back with this error:
 Error: subset called for sample that does not exist in header: "6"

I know individual ID 6 is in the vcf but for some reason, it's not recognizing it.

What should I do?

**Comment by pd3** [comment]
Most likely the sample name contains some other characters such as spaces for example. One easy way to check this is to run:

     bcftools query -l file.vcf | awk '$1=="6"' | od -c
