### ISSUE TITLE
LRR + BAF tool

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#459]
Hello!

Do you recommend any tools to generate the LRR and BAF tags in the vcf?

LRR ~ fold change i.e. log2 depth sample / depth other samples
BAF = (ALT depth)/(Total depth)

This was all I found http://penncnvexomeseq.sourceforge.net/

**Comment by pd3** [comment]
Hi, no, we don't, sorry. A naive approach would be to use allelic depths (FORMAT/AD) to calculate these values. However, in my experience this is very noisy, unusable.
