### ISSUE TITLE
segmentation fault in converting with --haplegendsample2vcf

### ISSUE THREAD

**Issue by stephanripke** [samtools/bcftools#460]
hi.
I am trying to convert the impute2 formatted reference into vcf. 
I have these three files:
ALL_1000G_phase1integrated_v3_chr22_impute_macGT1.hap.gz
ALL_1000G_phase1integrated_v3_chr22_impute_macGT1.legend.gz
ALL_1000G_phase1integrated_v3_chr22_impute_macGT1.sample

here is a head of them:
*hap.gz:
2184 columns, 394274 rows with 0 and 1

*sample (1092 rows):
id1 GBR EUR 1
id2 GBR EUR 2
id3 GBR EUR 2
id4 GBR EUR 2
id5 GBR EUR 1
id6 GBR EUR 2

*legend.gz (394275 rows):
id position a0 a1
22:16050408_T_C 16050408 T C
22:16050612_C_G 16050612 C G
22:16050678_C_T 16050678 C T
22:16050984_C_G 16050984 C G
22:16051107_C_A 16051107 C A

I am using bcftools 1.3.1 like this:
bcftools convert -H ALL_1000G_phase1integrated_v3_chr22_impute_macGT1

and unfortunately get an segmentation fault. so difficult to find out.....
any help apreciated,
Stephan

p.s. 
happy to share these files, though they are just slightly edited versions from the originals from https://mathgen.stats.ox.ac.uk/impute/data_download_1000G_phase1_integrated.html

**Comment by wkretzsch** [comment]
Hi Stephan.  Can you try specifying the three files explicitly?  For example:

```bash
BASE=ALL_1000G_phase1integrated_v3_chr22_impute_macGT1
bcftools convert -H $BASE.haps.gz,$BASE.legend.gz,$BASE.sample
```

Looking at the plugin code I see that the .sample file is expected to have a postfix of `.samples`.  That should probably be changed...

**Comment by pd3** [comment]
Hi, 
thank you for the bug report and help from @wkretzsch. I added a check for this, so that next time it will complain rather than segfault.
