### ISSUE TITLE
leave a time stamp in the metadata lines

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#467]
Would it be possible to have bcftools leave a time stamp in the metadata lines, when a command is executed? Here is what GATK does to the VCF (truncated):

##GATKCommandLine.HaplotypeCaller=<ID=HaplotypeCaller,Version=3.5-0-g36282e4,Date="Fri Jan 15 21:20:05 SAST 2016"

**Comment by pd3** [comment]
Yes, that's a good idea. Added now.
