### ISSUE TITLE
No quality score given when using -V

### ISSUE THREAD

**Issue by joonan30** [samtools/bcftools#468]
Hi,

I am trying to get ROH from WGS cohort data. When I ran `bcftools roh -s sampleID -I -G 30 cohort.vcf`, I could get the prediction matrix with the quality score. 

Then, I tried it with the parameter used in Narasimhan 2016 Science: `bcftools roh -G 30 -a 6.7e-8 -H 5e-9 -s sampleID -I -V -m 1000GP_Phase3/genetic_map_chr22_combined_b37.txt cohort.vcf`. The output has no quality score (though it predicted AZ/HW):

22      51244396        0       ..
22      51244435        0       ..
22      51244443        0       ..
22      51244515        0       ..

Is this expected behaviour for the use of -V option?

Thanks

**Comment by pd3** [comment]
Hi, it seems that you are running an older version of BCFtools. Can you update to a more recent version, preferably the latest develop from github?

     git clone https://github.com/samtools/htslib.git    
     git clone https://github.com/samtools/bcftools.git
     cd bcftools
     make
