### ISSUE TITLE
bcftools annotate doesn't subset samples

### ISSUE THREAD

**Issue by TracyBallinger** [samtools/bcftools#469]
I'm trying to add an annotation to a vcf file that has many samples in it.  My annotation file only has annotations for a few of the samples, so I am using this command: 
bcftools annotate -a mydata.baf.txt.gz -h baf.hdr -s sample1,sample2 -c CHROM,POS,FMT/BAF -Ob -o output.bcf vcffile
And I get this error: 
bcftools: vcfannotate.c:876: setter_format_real: Assertion `col->icol+nsmpl <= tab->ncols' failed.
Aborted (core dumped)

However, when I break it up into two steps as so, it seems to work.
bcftools view -s sample1,sample2 vcffile -Ob | bcftools annotate -a mydata.baf.txt.gz -h baf.hdr -c CHROM,POS,FMT/BAF -Ob -o output.bcf -

As you can see, I've found a work around, but thought I'd mention it incase I'm missing something.

**Comment by pd3** [comment]
Hi Tracy,
thank you for bringing this up. Your observation is correct, the command cannot annotate subsets of samples from tab-delimited annotation files yet, only VCFs were supported. Added this feature now. Note that it will not sub-sample the VCF, but will annotate the requested samples.
Cheers,
Petr
