### ISSUE TITLE
bcftools view -s/-S reports error about undefined tags in the header

### ISSUE THREAD

**Issue by yfangumich** [samtools/bcftools#470]
Hello,

I was trying to subset one vcf.gz file resulted from imputation  by command:
bcftools view -S samplefile -Oz chr22.dose.vcf.gz > test.vcf.gz 

samplefile contains rows of sample ID names like:
sample_1
sample_2

However I got error message like below:
[W::vcf_parse] FILTER 'GENOTYPED' is not defined in the header
Undefined tags in the header, cannot proceed in the sample subset mode.

I checked the header of my vcf file and it looks like this:

##fileformat=VCFv4.1
##FILTER= < ID=PASS,Description="All filters passed" >
##filedate=2016.8.11
##source=Minimac3
##contig=< ID=22 >
##FORMAT=< ID=GT,Number=1,Type=String,Description="Genotype" >
##FORMAT=< ID=DS,Number=1,Type=Float,Description="Estimated Alternate Allele Dosage : [P(0/1)+2*P(1/1)]" >
##FORMAT=< ID=GP,Number=3,Type=Float,Description="Estimated Posterior Probabilities for Genotypes 0/0, 0/1 and 1/1" >
##INFO=< ID=AF,Number=1,Type=Float,Description="Estimated Alternate Allele Frequency" >
##INFO=< ID=MAF,Number=1,Type=Float,Description="Estimated Minor Allele Frequency" >
##INFO=< ID=R2,Number=1,Type=Float,Description="Estimated Imputation Accuracy" >
##INFO=< ID=ER2,Number=1,Type=Float,Description="Empirical (Leave-One-Out) R-square (available only for genotyped variants)" >
##bcftools_viewVersion=1.3.1+htslib-1.3.1
##bcftools_viewCommand=view chr22.dose.vcf.gz
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample_1 sample_2 sample_3 ...

Should I modify the header or is there anything I am missing here?

Thanks.

**Comment by pd3** [comment]
Yes, just include the missing tags in the header, for example like this:

      bcftools view -h file.vcf > hdr.txt
      <edit hdr.txt>
      bcftools reheader -h hdr.txt -h file.vcf > new.vcf

In this case the program could be less strict.

**Comment by yfangumich** [comment]
Thanks for the instruction on how to modify the header! But could you be able to tell which specific problem does the header of my file have?

By doing other operations I figured
"[W::vcf_parse] FILTER 'GENOTYPED' is not defined in the header"
is only a warning, the job could run smoothly beyond it.

So I guess,
"Undefined tags in the header, cannot proceed in the sample subset mode."
is the real problem. But I can't tell which tags are undefined.

Thanks for the help.

**Comment by mcshane** [comment]
Looks like there is a value `GENOTYPED` in the FILTER column but `PASS` (and `.`) is the only FILTER defined in the header. So adding this should work unless there are others.
```
##FILTER=<ID=GENOTYPED,Description="Site was genotyped">
```
If this is the case, then you might want to email the UMich imputation folks to let them know the this line should be added (cc @Santy-8128)

**Comment by yfangumich** [comment]
Looks like it IS the problem. After I added the line identifying GENOTYPED, there was another warning:
[W::vcf_parse] FILTER 'GENOTYPED_ONLY' is not defined in the header

So I ended up adding two lines into the header:
`##FILTER=<ID=GENOTYPED,Description="Site was genotyped">`
`##FILTER=<ID=GENOTYPED_ONLY,Description="Site was genotyped only">`

Not really sure if the description of the second line is accurate, but after adding these two lines in the header, the subset operation ran smoothly.

The file was the imputation result from um imputation server. I'll email them about this issue.

Thanks!

**Comment by Santy-8128** [comment]
Hi Yu,

Yes, our VCF files have some issues with the FILTER header. We have missed
defining some of them. We will fix that in the next release. Sorry for the
inconvenience.

**Comment by candicecjj** [comment]
@Santy-8128 
Hi Santy,

I am using Michigan Imputation Server recently and have the same problem as Yu mentioned here. I was wondering if the issue is fixed?

Thanks!

**Comment by Santy-8128** [comment]
Hi,


If you have files already downloaded from the imputation server, the only
way to fix them is to edit the files.
Otherwise, if you are running locally, you can re-clone from the git-repo
in which we have updated this fix.




*Regards,*
*Sayantan Das,*



*Doctoral Student Department of BiostatisticsUniversity of Michigan, Ann
Arbor.MI 48109-2029*

**Comment by natalieepoz** [comment]
@Santy-8128 @yfangumich 
Hi,

I imputed my data in march 2017 and facing this same problem. 
However, reheader option in bcftools did not work, no idea why...
I need to do this for all chromosome and you can imagine it could take a large space to resave it. 
any other ways to replace the headers in all files? 

Best
Natalie

**Comment by Santy-8128** [comment]
Can you tell me what issues you are having with the reheader ?

*Regards,*
*Sayantan Das,*



*Post-Doctoral Fellow Department of BiostatisticsUniversity of Michigan,
Ann Arbor.MI 48109-2029*

**Comment by natalieepoz** [comment]
Hi @Santy-8128 
thanks for your quick response 
this is what I get. 
bcftools reheader --header hdr.txt --header filename.vcf  --output test_header.vcf

About:   Modify header of VCF/BCF files, change sample names.
Usage:   bcftools reheader [OPTIONS] <in.vcf.gz>

Options:
    -h, --header <file>     new header
    -o, --output <file>     write output to a file [standard output]
    -s, --samples <file>    new sample names

I also tried with saving the output file with ">", but I still get the same. 

thanks

**Comment by mcshane** [comment]
`bcftools reheader --header new_header.txt --output new.vcf original.vcf`

**Comment by Santy-8128** [comment]
Yes, you used the --header tag twice. Thanks Shane for the quick reply.

[P.S. This is an issue only if you are using files from the imputation
server. if you ran your imputation locally, you can re-clone minimac3 which
shouldn't have this bug. It has been fixed quite sometime ago]


*Regards,*
*Sayantan Das,*



*Post-Doctoral Fellow Department of BiostatisticsUniversity of Michigan,
Ann Arbor.MI 48109-2029*

**Comment by natalieepoz** [comment]
Thank you so much @mcshane and @Santy-8128

**Comment by sarahcn** [comment]
@Santy-8128 can you please provide an example of what the header should look like, i.e. with all the fields defined? Otherwise I'm not sure what the contents of "new_header.txt" (to use @mcshane's example syntax) should be. Thanks~

**Comment by Santy-8128** [comment]
This should be the two lines that need to be added to the header (only if
your files were downloaded from the Imputation server). If you ran locally,
your files should be fine.

##FILTER=<ID=GENOTYPED,Description="Site was genotyped">
##FILTER=<ID=GENOTYPED_ONLY,Description="Site was genotyped only">



*Regards,*
*Sayantan Das,*



*Post-Doctoral Fellow Department of BiostatisticsUniversity of Michigan,
Ann Arbor.MI 48109-2029*

**Comment by pd3** [comment]
The new header is literally the new header, the file will be copied verbatim
