### ISSUE TITLE
undefined reference to `bcf_hdr_format' when running make

### ISSUE THREAD

**Issue by jjfarrell** [samtools/bcftools#471]
When running make on the cloned develop branch of bcftools, the following error occurs:

gcc -rdynamic  -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o bin.o hclust.o version.o regidx.o smpl_ilist.o mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o ccall.o em.o prob1.o kmin.o  ../htslib/libhts.a -lpthread -lz -lm -ldl
reheader.o: In function `reheader_bcf':
/restricted/projectnb/genpro/github/bcftools/reheader.c:374: undefined reference to `bcf_hdr_format'
collect2: ld returned 1 exit status
make: *** [bcftools] Error 1

**Comment by jjfarrell** [comment]
The develop branch of htslib.git is needed to avoid that error.

git clone --branch=develop git://github.com/samtools/htslib.git
git clone --branch=develop git://github.com/samtools/bcftools.git
git clone --branch=develop git://github.com/samtools/samtools.git
cd bcftools; make
cd ../samtools; make

**Comment by pd3** [comment]
I believe this is resolved, closing now.
