### ISSUE TITLE
Non-ACGT reference allele (ambiguity code in assembly)

### ISSUE THREAD

**Issue by sjackman** [samtools/bcftools#473]
My assembled genome of short reads has 9 sites with ambiguity codes. When I align the reads to the reference, it's clear what the true base should be. When I call variants using `bcftools call -c -v --ploidy=1 -Oz` these variants sites are lost. I suspect `-v` is to blame. All of the REF ambiguity codes are two-nucleotide codes, and the ALT allele agrees with one of the two possible nucleotides. Could/should these non-ACGT REF sites be retained by `-v`? They could easily be filtered out later with `bcftools filter` but once they've been dropped, they can't be recovered.

**Comment by pd3** [comment]
Yes, the sites should ideally be retained. Because the VCF specification does not allow ambiguity codes in REF and ALT, the programs are expected to translate to ACGT. This has not been done for bcftools yet.

**Comment by mp15** [comment]
The VCF specification is trying to span two bridges here (https://github.com/samtools/hts-specs/issues/54). I'm wondering if the right answer is just turning each of these sites into a multi-allelic automatically?

**Comment by sjackman** [comment]
I suspected above that the `-v` option is to blame, but it's not. The sites with non-ACGTN reference bases are never output by `bcftools`. Until consensus is reached at samtools/hts-specs#54, could `bcftools` put an `N` in the reference? That seems better to me than outputting nothing.

**Comment by sjackman** [comment]
I've changed the ambiguity code sites to `N`, and even still they're omitted from the VCF file. I believe Ns are allowed in the reference. Is there a reason I'm not getting these sites with the following command?

```sh
samtools mpileup -u -f ref.unamb.fa reads.bam | bcftools call -c --ploidy=1 -Oz
```

**Comment by pd3** [comment]
Check the `-M, --keep-masked-ref` option, that should work for `N`'s.

**Comment by sjackman** [comment]
Ah, missed that. Thanks!

**Comment by finswimmer** [comment]
Hello,

I just append my problem to this issue. I do the variant calling like this:

```
bcftools mpileup -q20 -f genome.fa -r chr3:16902880-16902886 ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239481/NA12748.final.cram|bcftools call -mv
```

This results in:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA12748
chr3	16902883	.	BGCGC	BGTGTGTGTGTGCGCGCGC	222	.	INDEL;IDV=9;IMF=0.321429;DP=28;VDB=0.855853;SGB=-0.676189;MQSB=0.993109;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=7,10,4,7;MQ=58	GT:PL	0/1:255,0,180
```

This is problematic in multiple ways:

1. As mentioned above Non-ACTGN characters are (currently) not allowed in REF alleles
2. I wonder how a variant call can result in an ambiguity code?

The third one is more critical for me: When I now run `bcftools norm`, on a vcf file that contains result like above, an error arises:

```
Non-ACGTN reference allele at chr3:16902883 .. REF_SEQ:'NGCGC' vs VCF:'BGCGC'
```

I would expect that each bcftools command can handle vcf file produced by bcftools. Until now this has worked very well :+1: 

fin swimmer

**Comment by benostendorf** [comment]
Hi @finswimmer , 

did you solve the issue? I'm dealing with the exact same one (also at same genomic location) and not sure how to proceed. 

Error message:
```
Non-ACGTN reference allele at chr3:16902883 .. REF_SEQ:'NGCGC' vs VCF:'BGCGC'
```

Thanks,
Ben

**Comment by finswimmer** [comment]
@benostendorf unfortunately I couldn't really solve this problem. I just could bypass it in my specific pipeline by using `freebayes` in an intermediate step. Would be really happy to see this fixed in `bcftools`.

**Comment by slw287r** [comment]
```
bcftools norm --threads 32 -Oz -o foo_norm.vcf.gz -f hs37d5.fa foo.vcf.gz
Non-ACGTN reference allele at hs37d5:34948112 .. REF_SEQ:'CGGAATGNAATGGAATG' vs VCF:'cggaatgraatggaatg'
make: *** [Makefile:25: foo_norm.vcf.gz] Error 255
```

```
bcftools --version
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pd3** [comment]
Run the command with `-c s` to set the correct base or`-c w` to give a warning and skip the site rather than throwing an error. The first works only with the latest github version, previously it would set only the REF allele but not the ALT alleles.
