### ISSUE TITLE
 "bcftools query" doesn't work with "-S  sample" option

### ISSUE THREAD

**Issue by yujin2011** [samtools/bcftools#476]
The "bcftools query" function seems not passing the subset sample option correctly.

Following are two command lines and returning results using "bcftools query" and "bcftools view" to do the sample subsetting:

1. bcftools view -S is working:
bcftools view A.normalized.vcf.gz -S B.sample  | bcftools query  -f "%CHROM\t%POS\t%REF\t%ALT\t%INFO/AC\t%INFO/AN\n"  |  head -n1
2       11486   A       G       **142     1806**

2. bcftools query -S is not working:
bcftools query A.normalized.vcf.gz -S B.sample -f "%CHROM\t%POS\t%REF\t%ALT\t%INFO/AC\t%INFO/AN\n"  |  head -n1
2       11486   A       G       **432     5088**

The results are the same with both stable and experimental versions. 

stable versions:
bcftools 1.3.1-6-gf7f36d9
Using htslib 1.3.1-19-g1cc7d12

experimental:
bcftools 1.3.1-95-gfa1f094
Using htslib 1.3.1-61-ge87ae87

**Comment by pd3** [comment]
Hi, it is an expected behavior: `query` shows existing annotations and does not recalculate existing fields. The intended way is to subset with `view` first and then stream through `query.` When streaming like this, it is a good idea to add `-Ou` to the first command for efficiency.
