### ISSUE TITLE
Suggestions: add more info regarding GT comparison in "bcftools stat"

### ISSUE THREAD

**Issue by yujin2011** [samtools/bcftools#477]
Dear bcftools developers,

I am a heavy user of bcftools. There are two possible improvements occurring to me during my daily usage of it:

The current "bcftools stats" can compare the genotypes between two vcf files given the overlapping sample list and it can output the #matched and #unmatched for RR, RA and AA.

1. It would be helpful to also report the counts of different kinds of mismatched, 
say #mismatch RA = #RA->AA + #RA->RR

It is possible to recover part of the genotype comparison information by swapping the order of vcf files and running "bcftools stats" twice. But there is no general solution to recover all the information by this, because the matrix is singular.

2. It would also be helpful to add genotype category of "./."

With the above information, it can reproduce the full genotype comparison tables in a single run and make the detailed analysis much easier.

Best,
Jin

**Comment by pd3** [comment]
Hi Jin,
this was requested before and now, finally, implemented [here](https://github.com/samtools/bcftools/commit/d00f1d939104bb716434061ededf4faa62afc453). Please try it out & let me know in case of problems.
Petr

**Comment by yujin2011** [comment]
great, thanks
