### ISSUE TITLE
INFO/AD output or FMT/AD output

### ISSUE THREAD

**Issue by mns1972** [samtools/bcftools#478]
Dear team,

I wonder if you would be able to clarify this issue please.

I'm under the impression that the INFO and FMT AD field in a vcf output file following samtools mpileup | bcftools call follows this format: _(unfiltered)_ **REF allele counts,ALT(1-...x) counts**.

I believe that this convention seems to be in reverse in my outputs, ie. **ALT,REF** counts...
It may be the case that I'm performing this process wrongly, hence I'd just like to check this with you. These are the steps I took:
I.
cat chr.txt | xargs -I {} -n 1 -P 12 sh -c \
"samtools mpileup -C50 -d 1000 -E -p -v -t AD,INFO/AD,DP,DPR,SP,DV -u -r {} \
-f ~/bin/Pseudogenomes/C57BL6J_b38/C57BL6J_b38.fa ./Suspenders/Patski_GA_C57BL6J_SPR_merged_align_sorted.bam | \
bcftools call -mv -f GQ -Oz > ./Patski_snpcalls/Patski_denovo_{}.vcf.gz"

II.
bcftools concat --threads 36 -f BCF_file_list.txt -Oz -o ./Patski_snpcalls/Patski_denovo_merged.vcf.gz

III.
bcftools index ./Patski_snpcalls/Patski_denovo_merged.vcf.gz

I seem to be obtaining a number of 1/1 variant (homozygous Alt allele by convention) calls. In my case, I would have only expected to get the opposite 0/0 (homozygous Ref allele by convention) calls. Indeed when I plot the data, as I'd expect to observe, I do see skewed counts from one allele. But this seems to be from the **Alt** - ie. the reverse of what I would have expected. Instead I would have expected to observe skewed counts from the **Ref** allele? I'd be grateful for your help.
(I'm using samtools | bcftools | htslib 1.3.1) 

Many Thanks,

**Comment by pd3** [comment]
Hi, your `bcftools call` command includes the `-v` option, which removes non-variant 0/0 sites.

**Comment by mns1972** [comment]
I now realise how the output format works following the `-v ` option! Thanks a lot!!
I had followed the commands suggested on the samtools webpage.... has to be said that this format can be a bit confusing.
