### ISSUE TITLE
consensus does not yield the consensus sequence

### ISSUE THREAD

**Issue by sjackman** [samtools/bcftools#480]
It should be clarified in the documentation that `bcftools consensus` does not output the the consensus base (most frequent allele) at each position (based for example on `DP4`). It modifies every position of the FASTA file that is found in the VCF file, always taking the ALT allele, ignoring the depths of the REF and ALT allele. To take the most frequent allele at each position, you must first filter the VCF file like so:
```sh
bcftools filter -i '(DP4[0]+DP4[1]) < (DP4[2]+DP4[3]) && DP4[2] > 0 && DP4[3] > 0'
```
This command includes records for which the depth of the ALT allele exceeds the REF allele, and the ALT allele has at least one read from each strand.

A command line option to `bcftools consensus` to output the consensus sequence (the most frequent base) at each position would be useful.

**Comment by alielw** [comment]
Hi,
This is super useful. 
1. For the filtering what does DP4 etc mean?
2. What does consensus do with missing data? For example, if the site is not sequenced then does it print the reference allele in the consensus or print an N?
Thanks!

**Comment by sjackman** [comment]
> For the filtering what does DP4 etc mean?

It doesn't appear to be in the VCF standard: http://samtools.github.io/hts-specs/VCFv4.3.pdf
It's defined by `samtools mpileup`: http://samtools.sourceforge.net/mpileup.shtml

> What does consensus do with missing data? For example, if the site is not sequenced then does it print the reference allele in the consensus or print an N?

It outputs whatever base in the the `ALT` column if one exists for that position in the VCF file, or otherwise retains the reference base (I believe).

**Comment by pd3** [comment]
Hi, sorry about the confusing command name. The program works with genotype/haplotype calls, applying them to create a modified fasta sequence. However, you'd like it to act as a primitive variant caller, followed by what it currently does.

This can be achieved in two steps. First use the `bcftools +setGT -t q` plugin to set the genotypes according to an appropriate `-i/-e` rule. Then `consensus` can be used.
