### ISSUE TITLE
bcftools 1.3.1 hardcoded to build against htslib 1.3.1

### ISSUE THREAD

**Issue by jrandall** [samtools/bcftools#481]
htslib 1.3.2 has been released, but the bcftools 1.3.1 release is not set up to build against it. 

In my environment at Sanger, I was able to build like so:
`
touch /software/hgi/pkglocal/htslib-1.3.2/include/htslib.mk && make HTSDIR=/software/hgi/pkglocal/htslib-1.3.2/include HTSLIB=/software/hgi/pkglocal/htslib-1.3.2/lib/libhts.so.1.3.2 BGZIP=/software/hgi/pkglocal/htslib-1.3.2/bin/bgzip TABIX=/software/hgi/pkglocal/htslib-1.3.2/bin/tabix USE_GPL=1 GSL_LIBS="$(PKG_CONFIG_PATH=/software/hgi/pkglocal/gsl-1.16/lib/pkgconfig pkg-config --libs gsl) -Wl,-rpath=/software/hgi/pkglocal/gsl-1.16/lib" EXTRA_CPPFLAGS="-I. -I/software/hgi/pkglocal/htslib-1.3.2/include -DPLUGINPATH=\\\"/software/hgi/pkglocal/bcftools-1.3.1-htslib-1.3.2/libexec/bcftools\\\"" LDFLAGS="-L/software/hgi/pkglocal/xz-5.2.2/lib -L/software/hgi/pkglocal/bzip2-1.0.6/lib -L/software/hgi/pkglocal/zlib-1.2.8/lib -Wl,-rpath=/software/hgi/pkglocal/xz-5.2.2/lib -Wl,-rpath=/software/hgi/pkglocal/bzip2-1.0.6/lib -Wl,-rpath=/software/hgi/pkglocal/zlib-1.2.8/lib -Wl,-rpath=/software/hgi/pkglocal/htslib-1.3.2/lib" prefix=/software/hgi/pkglocal/bcftools-1.3.1-htslib-1.3.2 install
`

As intuitively obvious as that is, I feel like `bcftools` could benefit from an `autoconf` treatment so that one can just re-run more or less the same `./configure` line used for a previous build.

**Comment by jkbonfield** [comment]
This is perhaps an issue of mixing the tarballs with git.

If you're checking htslib out from git, then it's probably best to do the same for samtools and bcftools too (using the  release tagged branches, not develop).  Then samtools/bcftools all operate in sibling directories and by default will look in ../htslib, which worked OK for me.
