### ISSUE TITLE
fill-tags: Wrong AC, AN and AC_Hemi for ./1 GT

### ISSUE THREAD

**Issue by mh11** [samtools/bcftools#487]
There is an inconsistency counting the Alleles in the fill-tags plugin. The GT below produces
`0/0     1/.     1/.     0/1     1/1     AN=8;AF=0.625;AC=5;AC_Het=1;AC_Hom=2;AC_Hemi=2`
while the following misses some alleles:
`0/0     ./1     ./1     0/1     1/1    AN=6;AF=0.5;AC=3;AC_Het=1;AC_Hom=2;AC_Hemi=0`

The fill-AN-AC plugin provides the same output for both: 
`AN=8;AC=5`

Please can you have a look what's the issue,
Thanks

**Comment by pd3** [comment]
Hi, thanks for spotting this. The plugin is not ready for half-missing genotypes, it only handles full diploid or haploid genotypes. I am not sure what is the expected result. The half-missing genotype `./1` is technically diploid, but we don't count missing alleles. The right answer therefore should be `AN=8;AC=5;AC_Het=1;AC_Hom=2;AC_Hemi=0`. Do you agree?

**Comment by pd3** [comment]
By default the half-missing genotypes are counted as hemizygous, unless the a new `-d, --drop-missing` option is given. I hope this helps.

**Comment by mh11** [comment]
Sorry for the delay - yes, the -d option helps a lot. Thanks
