### ISSUE TITLE
bcftools query outputs incorrect values for genotype fields

### ISSUE THREAD

**Issue by AohRveTPV** [samtools/bcftools#488]
```
$ bcftools query -f '%GQ\n' test/query.vcf
.
.
.
.
.
.
.
.
.
.
.
.
.
```

Maybe related to #420 ?

**Comment by pd3** [comment]
This requests printing of INFO/GQ which does not exist. In order to print FORMAT/GQ run as

     bcftools query -f '[ %GQ]\n' test/query.vcf

I now added a check to catch such errors and expanded the documentation.

**Comment by AohRveTPV** [comment]
Thank you!
