### ISSUE TITLE
IDEL wrong calling

### ISSUE THREAD

**Issue by dashainparis** [samtools/bcftools#491]
Hello,

I ran this command: 
`[bio@x4270m2 exome_analysis]$ bcftools call -m --output-type v -p 0.02 /big_pool/bio/atlas/exome_analysis/out_vcf_mpileup_chr18 > D0094.var.qual.chr18.vcf`

And got these variants:

chr18   63411655    .   G   .   999 .   DP=39;MQSB=1;MQ0F=0;AN=2;DP4=1,37,0,0;MQ=60 GT  0/0
chr18   63411655    .   GTTTTTTTTTTTTTT .   25.362  .   INDEL;IDV=13;IMF=0.333333;DP=39;VDB=0.491428;SGB=-0.683931;MQ0F=0;AN=2;DP4=0,13,0,13;MQ=60  GT  0/0

I assume it should be deletion of this region 'GTTTTTTTTTTTTTT', I had a look at IGV browser, and what I saw that actually at this position should be an insertion of 'T':

![screen shot 2016-09-30 at 13 32 29](https://cloud.githubusercontent.com/assets/3019242/18992452/1519fbe4-8727-11e6-83ba-2145a659140e.png)
![screen shot 2016-09-30 at 13 32 29](https://cloud.githubusercontent.com/assets/3019242/18992465/22b2c6a0-8727-11e6-8e37-67690a01cd1c.png)

And then, I double checked by using blast:

![screen shot 2016-09-30 at 15 06 26](https://cloud.githubusercontent.com/assets/3019242/18992491/388bedf8-8727-11e6-9680-113202c729cd.png)

And checked again by just looking at reads:

REF      CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTAAAGCTTCTCAGCTTGCTGGGCTGTGAAAGA
READ     CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTTAAAGCTTCTCAGCTTGCTGGGCTGTG
         CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTAAAGCTTC
         CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTTAAAGCTT
         CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTAAAGCTTCT
         CATAAATTTGAAGTAAATAATCATACTGAAAGTTTTTTTTTTTTTTTAAAGCTTCT

As you can see there is an actual insertion, but I have no idea how can I detect it by the output of bcftools. Could you please help me with this?

Thanks!

**Comment by pd3** [comment]
The output you show above does not look like the VCF output produced by samtools/bcftools. There must be two columns with alleles, one for REF and the other for ALT. Only one is shown in your output though.

**Comment by pd3** [comment]
Closing this now, please reopen with a test case if still an issue
