### ISSUE TITLE
bcftools output format

### ISSUE THREAD

**Issue by cdeanj** [samtools/bcftools#492]
Suppose I run the following command:

bcftools isec -p dir A.vcf.gz B.vcf.gz C.vcf.gz

Why do I get three output files instead of one? How can I run isec and get only the variants that are common among all three files?

**Comment by pd3** [comment]
Hi, you need the `-w` option to tell the program which file to output, by default it will write out all. Please check the manual here http://samtools.github.io/bcftools/bcftools.html#isec
