### ISSUE TITLE
FORMAT/AD and FORMAT/DP not annotated with bcftools annotate

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#494]
I am trying to annotate a VCF file with the original `FORMAT/AD` and `FORMAT/DP` annotations. The `QUAL` and `INFO` annotations are copied over successfully, but not the `FORMAT` annotations. Am I doing something wrong or is this a bug? Here is my command line:

`$bcftools annotate \
 -a $vcfWithAnnotations -c QUAL,FORMAT/AD,FORMAT/DP,INFO,^INFO/AN,^INFO/AC,^INFO/AF,^FORMAT/GT,^FORMAT/PL,^FORMAT/GQ,^INFO/VariantType,^INFO/Dels \
 -S ^$samples \
 $vcfToBeAnnotated`

The file paths on lustre are:
`vcfToBeAnnotated=/lustre/scratch115/projects/adrp1/users/tc9/SHAPEIT/out_hapssample2vcf/20.vcf.gz`
`vcfWithAnnotations=/lustre/scratch115/projects/adrp1/users/tc9/pipeline_UG3.4_recall_union/out_ApplyRecalibration/20.vcf.gz`
`samples=/lustre/scratch115/projects/adrp1/users/tc9/analysis/IBD/samples.nonfounders.txt`

All samples present in `$vcfToBeAnnotated` are also present in `$vcfWithAnnotations`. The file `$vcfToBeAnnotated` only contains the GT FORMAT annotation.

**Comment by tommycarstensen** [comment]
I've updated the paths to a location we both have read access to:

 vcfToBeAnnotated=/lustre/scratch109/sanger/tc9/pd3/vcfToBeAnnotated.vcf.gz
 vcfWithAnnotations=/lustre/scratch109/sanger/tc9/pd3/vcfWithAnnotations.vcf.gz
 samples=/lustre/scratch109/sanger/tc9/pd3/samples.txt

AD and DP annotations missing:

```
bcftools annotate -a $vcfWithAnnotations -c QUAL,FORMAT/AD,FORMAT/DP,INFO,^INFO/AN,^INFO/AC,^INFO/AF,^FORMAT/GT,^FORMAT/PL,^FORMAT/GQ,^INFO/VariantType,^INFO/Dels -S ^$samples $vcfToBeAnnotated | grep -v ^# | cut -f9,10 | head
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
GT:AD:DP	0|0:.:.
```

**Comment by pd3** [comment]
Thank you for making the files available. The very latest version (84b8675) works. Note that the logic of the `-c` option is somewhat twisted in your usage as it gives both positive and negative lists of tags. For example, `^FMT/GT,FMT/PL` stands for "all FORMAT tags with the exception of GT and PL". Similarly `FMT/GT,FMT/PL` stands for "only GT and PL".

    bcftools annotate -a $vcfWithAnnotations -c QUAL,FORMAT/AD,FORMAT/DP -S ^$samples $vcfToBeAnnotated | grep -v ^# | cut -f9,10 | head -3
    GT:AD:DP	0|0:2,0:2
    GT:AD:DP	0|0:4,0:4
    GT:AD:DP	0|0:5,0:5
