### ISSUE TITLE
--samples-file ^FILE not working with bcftools annotate

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#496]
I'm using `--samples-file ^file.txt` along with `bcftools annotate`, but the samples in `file.txt` are not removed from the output VCF file. I suspect this might be a bug.

The sample IDs are the same in the source VCF and the destination VCF. I receive no warnings.

**Comment by pd3** [comment]
This is the expected behavior. We have a tool for removing samples already (`view`). The `annotate` command is useful to add annotation to specific samples without removing the rest.
