### ISSUE TITLE
TYPE expression misses variant records with alternative alleles of various kinds

### ISSUE THREAD

**Issue by gtamazian** [samtools/bcftools#498]
# What is wrong?

If a variant record contains multiple alternative alleles that correspond to variants of various kinds (e.g., an SNP and an indel), then the expression specifying the variant type misses them. For example, the following command produces no output when launched with [the attached MWE file](https://github.com/samtools/bcftools/files/523178/bcftools_type_missing_variants_mwe.vcf.gz):

```
bcftools view --include 'TYPE="snps"' bcftools_type_missing_variants_mwe.vcf.gz
```

The composite expressions like `TYPE="snps" | TYPE="indels"` also do not work.

# What is the reason?

The bug is caused by the way how the variant type is determined and how it is handled in the expression.

The variant type is determined in the *bcf_set_variant_types* function in the *vcf.c* file of the **htslib** library. This function specifies the type of each reference-alternative allele pair by calling the *bcf_set_variant_type* function and combines their results in the *var_type* field of the *bcf_dec_t* structure (lines 2902-2907) using the bitwise OR operator. Thus, if a variant record has two alternative alleles corresponding to an SNP and an indel, then its *var_type* value will be
`VCF_SNP | VCF_INDEL` = `1 | 4` = `5`.

**bcftools** decides whether a variant satisfies an expression or not in the *filter_test* function from the *filter.c* file of **bcftools**. In this function, the *var_type* value of a variant is compared to the variant type value stored in the filter structure created when the expression was parsed in the *filter_init* function of the same file. And *filter_init* is the place where the bug originates from.

In *filter_init*, `TYPE` is considered a special tag and is processed separately (lines 1589-1604 in *filter.c*). In these lines, the tag value from the expression is compared to the variant type values (`snps`, `indels`, `mnps`, `other` and `ref`) and the appropriate filter value is chosen. However, the chosen filter value will correspond only to a certain type of variants (e.g., `VCF_SNP`, that is, `1` for `snps`) and will not include variants of mixed types (like SNPs and indels).

In `filter_test`, the variant type value is checked to be equal to the filter value. If it differs from the filter value, then the variant is skipped. That is also the reason why composite expressions like `TYPE="snps" | TYPE="indels"` do not work: given a mixed SNP-indel variant with the *var_type* value `5`, **bcftools** compares it to `VCF_SNP` and `VCF_INDEL` filter values (that is, `1` and `4`) and skips it.

# How to fix it?

There are multiple ways to fix this bug. I would propose to introduce extended `TYPE` tag values: `snps+`, `indels+`, `mnps+` and `others+` that will allow for variant records with at least one alternative allele leading to the specified variant type. In that case, one has to modify only the *filter_init* function so that it would add several filter values for such tags (i.e., `VCF_SNP | VCF_INDEL`, `VCF_SNP | VCF_MNP`, `VCF_SNP | VCF_OTHER` and others for `snps+`). Also this solution preserves compatibility because it does not change the behavior of **bcftools** if standard `TYPE` tag values are specified.

**Comment by pd3** [comment]
Hi, thank you for the analysis. I added this, although somewhat differently. The  regex-like operator "~" can be now used to require at least one allele of the given type. The equal sign "=" remains unchanged and requires that all alleles are of the given type:

               TYPE="snp"
               TYPE~"snp"
               TYPE!="snp"
               TYPE!~"snp"
