### ISSUE TITLE
Discrepancies  in the number of SNPs in new version of bcftools

### ISSUE THREAD

**Issue by KrithikaSubramanian** [samtools/bcftools#499]
Hello all,
I am having discrepancies in the number of SNPs in new version of bcftools. Here are the commands 
I used and results I got for older and newer version respectively.

Using older (0.1.19)version command:
bcfools view -cvg Output.bcf -> Varaint.vcf
Result: 301snps

Using New (1.3.1) version command"
bcftools view Output.bcf -v snps -g het -O v  -o Variant_new.vcf
Result: 1634snps

I am not sure if I am using the right commands. Can somebody help me troubleshoot the issues.

Thanks
Krithika

**Comment by pd3** [comment]
The file format produced and read by versions <= 0.1.19 is not compatible with new versions of bcftools. If you need to convert an older file, please check the note in the manual about BCF1 http://samtools.github.io/bcftools/bcftools.html

**Comment by KrithikaSubramanian** [comment]
Thank you for your support @pd3. 
I am using older version

Krithika
