### ISSUE TITLE
vcfutils.pl vcf2fq

### ISSUE THREAD

**Issue by simonohanlon101** [samtools/bcftools#50]
Is the vcfutils.pl supposed to work with the new format specification of samtools/bcftools? I tried using the vcfutils.pl script included in the develop branch of bcftools to extract a fastq sequence from my bcf file but it fails giving the error:
````
Use of uninitialized value $q in numeric lt (<) at /usr/local/bin/vcfutils.pl line 508, <> line 103.
Use of uninitialized value $q in addition (+) at /usr/local/bin/vcfutils.pl line 518, <> line 103.
````

Using a bcf file generated using samtools 0.2 / bcftools 0.2 I tried to call this using:
````
bcftools view my.raw.snps.bcf | vcfutils.pl vcf2fq - > ./my.raw.fastq 
````

The original bcf file was generated using the command
````
samtools mpileup -6EBSDugp -f ./my_ref.fasta my.sorted.bam | bcftools call -vm -O b - > ./my.raw.snps.bcf
````

Am I doing something wrong or is there a bug in vcfutils.pl?

**Comment by sciuscia** [comment]
HI,
using samtools/1.1  bcftools/1.1

I'm having the same issue with: 
samtools mpileup -uf ref.fa my.bam | bcftools call -m - |  vcfutils.pl vcf2fq > consensus.fq 
Use of uninitialized value $q in addition (+) at /sw/apps/bioinfo/bcftools/1.1/milou/bin/vcfutils.pl line 539, <> line 71726.

and if I use 
bcftools call -c 
I got all nnnnn in the final fq file.

**Comment by mcshane** [comment]
Consensus via `vcf2fq` requires `bcftools call -c`.

The consensus command was added between 1.1 and 1.2. Please retry with 1.2 or latest develop and reopen if there is still an issue.

**Comment by duoduoo** [comment]
Hi mcshane,

Indeed through bcftools consensus this works for me.
But what if I do want to generate this through vcfutils.pl? I have the same problem, and if I still want to try to generate the fastq through vcfutils.pl?
