### ISSUE TITLE
gVCF homozygous blocks

### ISSUE THREAD

**Issue by Jhermes22** [samtools/bcftools#501]
Hi,

I am getting conflicting calls for some positions in my vcf file, with the same site being marked both as SNP and part of a homozygous block.

An example of my vcf file:

contig86    436259  .   C   A   228 PASS    DP=46;VDB=4.76112e-09;SGB=-0.693146;RPB=0.666667;MQB=0.178571;MQSB=0.999927;BQB=0.0238095;MQ0F=0;AC=2;AN=2;DP4=2,0,25,17;MQ=55  GT:PL:DP:SP:DP4 1/1:255,80,0:44:3:2,0,25,17
contig86    436259  .   c   .   .   PASS    END=436313  GT  0/0

This is the command used to obtain the vcf.

samtools mpileup -q 20 -Q 20 -ugt DP,SP,DP4 -f reference.fas -r contig86 bamfile.bam \
 | bcftools call -m -O v -g 8 \
 | bcftools filter -sFILTER -g3 -G10 -e'%QUAL<20 || FMT/DP<8' - > test.vcf

This is the output from samtools mpileup, before bcftools.

contig86    436257  .   G   <X> 0   .   DP=49;I16=27,16,0,0,1640,63560,0,0,2401,138103,0,0,865,20267,0,0;QS=1,0;MQSB=0.997163;MQ0F=0    PL:DP:SP:DP4    0,129,255:43:0:27,16,0,0
contig86    436258  .   T   <X> 0   .   DP=46;I16=27,18,0,0,1751,68863,0,0,2483,142187,0,0,909,21143,0,0;QS=1,0;MQSB=0.948756;MQ0F=0    PL:DP:SP:DP4    0,135,255:45:0:27,18,0,0
contig86    436259  .   C   A,<X>   0   .   DP=46;I16=2,0,25,17,54,1458,1653,65495,79,3121,2382,138582,35,725,877,20567;QS=0.0323935,0.967606,0;VDB=4.76112e-09;SGB=-0.693146;RPB=0.666667;MQB=0.178571;MQSB=0.999927;BQB=0.0238095;MQ0F=0  PL:DP:SP:DP4    255,80,0,255,126,255:44:3:2,0,25,17
contig86    436259  .   catctcgggtaatctcgggtaatctcgggtaatctcg   cATCTCGGGTAATCTCGGGTAatctcgggtaatctcgggtaatctcgggtaatctcg   0   .   INDEL;IDV=1;IMF=0.0217391;DP=46;I16=20,16,1,0,6891,1.42137e+06,255,65025,2088,122724,39,1521,826,19744,25,625;QS=0.981578,0.0184223;VDB=1.48144e-09;SGB=-0.379885;MQSB=0.998122;MQ0F=0  PL:DP:SP:DP4    0,72,255:37:0:20,16,1,0
contig86    436260  .   A   <X> 0   .   DP=53;I16=28,23,0,0,1907,73193,0,0,2864,165866,0,0,987,22425,0,0;QS=1,0;MQSB=0.965492;MQ0F=0    PL:DP:SP:DP4    0,154,255:51:0:28,23,0,0
contig86    436261  .   T   <X> 0   .   DP=53;I16=27,22,0,0,1909,75255,0,0,2782,161782,0,0,981,22487,0,0;QS=1,0;MQSB=0.999546;MQ0F=0    PL:DP:SP:DP4    0,148,255:49:0:27,22,0,0

Probably the indel is causing the confusion, but this does not seem right? How do I avoid having the same site being called variable and homozygous-reference in the vcf?

Thanks!

**Comment by pd3** [comment]
Thank you for the bug report. The mpileup version seems older, there is no `<*>` ALT allele in the output - could you please check if the problem remains also in the newest github version? Ideally with `bcftools mpileup`, there it is possible to produce the gvcf already at the mpileup step: `bcftools mpileup --gvcf .. | bcftools call `.

**Comment by Jhermes22** [comment]
Hi,


Using the same commands as in my previous message, but the latest github versions of samtools and bcftools (from http://samtools.github.io/bcftools/), I still get the positions marked both as SNP and homozygous reference, but now the ALT allele is gone:

contig86	436259	.	C	A	228	PASS	DP=46;VDB=4.76112e-09;SGB=-0.693146;RPB=0.666667;MQB=0.178571;MQSB=0.999927;BQB=0.0238095;MQ0F=0;AC=2;AN=2;DP4=2,0,25,17;MQ=55	GT:PL:DP:SP:DP4	1/1:255,80,0:44:3:2,0,25,17
contig86	436259	.	catctcgggtaatctcgggtaatctcgggtaatctcg	.	.	PASS	END=436313;MinDP=37	GT:DP	0/0:37


Using mpileup from bcftools does not seem to make a difference. I used

$BCFTOOLS mpileup  --gvcf 8 -f $REF -q 20 -Q 20 $BAM -r contig86 \
 | $BCFTOOLS call -m -O v -g 8 \
 | $BCFTOOLS filter -sFILTER -g3 -G10 -e'%QUAL<20 || FMT/DP<8' - > test.devel.bcftools.vcf

And the output:

contig86	436259	.	C	A	228	PASS	DP=46;VDB=4.76112e-09;SGB=-0.693146;RPB=0.666667;MQB=0.178571;MQSB=0.999927;BQB=0.0238095;MQ0F=0;AC=2;AN=2;DP4=2,0,25,17;MQ=55	GT:PL:DP	1/1:255,80,0:44
contig86	436259	.	catctcgggtaatctcgggtaatctcgggtaatctcg	.	.	PASS	END=436313;MinDP=37	GT:DP	0/0:37


software versions:
samtools  Version: 1.3.1-41-gce4a601 (using htslib 1.3.2-132-g609120d)
bcftools  Version: 1.3.1-157-g54a215f (using htslib 1.3.2-132-g609120d)

Thanks!

**Comment by pd3** [comment]
Any chance you could share the few output lines directly from `mpileup`? Although not impossible, it is more difficult to debug the problem going backwards, from the outputs. Thanks

**Comment by Jhermes22** [comment]
Hi,

Sure, the 10 lines before and after the position are pasted below, obtained with 

$BCFTOOLS mpileup --gvcf 8 -f $REF -q 20 -Q 20 $BAM -r contig86


contig86	436223	.	G	<*>	0	.	DP=7;I16=3,4,0,0,275,10831,0,0,411,24201,0,0,130,2872,0,0;QS=1,0;MQSB=0.810265;MQ0F=0;MinDP=7	PL:DP	0,21,219:7
contig86	436224	.	T	<*>	0	.	DP=7;I16=3,4,0,0,270,10486,0,0,411,24201,0,0,127,2815,0,0;QS=1,0;MQSB=0.810265;MQ0F=0;MinDP=7	PL:DP	0,21,217:7
contig86	436225	.	A	<*>	0	.	DP=7;I16=3,4,0,0,264,10258,0,0,411,24201,0,0,124,2764,0,0;QS=1,0;MQSB=0.810265;MQ0F=0;MinDP=7	PL:DP	0,21,213:7
contig86	436226	.	A	<*>	0	.	DP=7;I16=3,4,0,0,247,8877,0,0,411,24201,0,0,121,2719,0,0;QS=1,0;MQSB=0.810265;MQ0F=0;MinDP=7	PL:DP	0,21,199:7
contig86	436227	.	T	<*>	0	.	DP=33;I16=3,4,0,0,261,9829,0,0,411,24201,0,0,137,3269,0,0;QS=1,0;MQSB=0.810265;MQ0F=0;MinDP=7	PL:DP	0,21,209:7
contig86	436228	.	C	<*>	.	.	END=436242;MinDP=29;QS=1,0	PL:DP	0,87,255:29
contig86	436243	.	G	A,<*>	0	.	DP=39;I16=18,16,3,2,1310,51162,187,7091,1902,109782,270,14922,705,16301,101,2171;QS=0.872502,0.127498,0;VDB=0.764622;SGB=-0.590765;RPB=0.0763108;MQB=0.786454;MQSB=0.961094;BQB=0.907302;MQ0F=0	PL:DP	52,0,255,155,255,255:39
contig86	436244	.	T	<*>	.	.	MinDP=39;QS=1,0	PL:DP	0,117,255:39
contig86	436245	.	G	T,<*>	0	.	DP=40;I16=21,17,0,1,1488,58788,22,484,2115,121455,60,3600,789,18143,13,169;QS=0.985115,0.014885,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.997523;BQB=1;MQ0F=0	PL:DP	0,95,255,114,255,255:39
contig86	436246	.	T	<*>	.	.	END=436258;MinDP=38;QS=1,0	PL:DP	0,114,255:38
contig86	436259	.	C	A,<*>	0	.	DP=46;I16=2,0,25,17,54,1458,1653,65495,79,3121,2382,138582,35,725,877,20567;QS=0.0323935,0.967606,0;VDB=4.76112e-09;SGB=-0.693146;RPB=0.666667;MQB=0.178571;MQSB=0.999927;BQB=0.0238095;MQ0F=0	PL:DP	255,80,0,255,126,255:44
contig86	436259	.	catctcgggtaatctcgggtaatctcgggtaatctcg	cATCTCGGGTAATCTCGGGTAatctcgggtaatctcgggtaatctcgggtaatctcg	0	.	INDEL;IDV=1;IMF=0.0217391;DP=46;I16=20,16,1,0,6891,1.42137e+06,255,65025,2088,122724,39,1521,826,19744,25,625;QS=0.981578,0.0184223;VDB=1.48144e-09;SGB=-0.379885;MQSB=0.998122;MQ0F=0	PL:DP	0,72,255:37
contig86	436260	.	A	<*>	.	.	END=436272;MinDP=49;QS=1,0	PL:DP	0,148,255:49
contig86	436273	.	T	G,<*>	0	.	DP=61;I16=30,27,1,0,2207,86757,32,1024,3277,192337,60,3600,1207,28023,13,169;QS=0.985586,0.0144144,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.992254;BQB=1;MQ0F=0	PL:DP	0,143,255,172,255,255:58
contig86	436274	.	C	<*>	.	.	END=436286;MinDP=58;QS=1,0	PL:DP	0,175,255:58
contig86	436287	.	G	C,<*>	0	.	DP=65;I16=33,27,1,0,2368,94144,41,1681,3458,203216,60,3600,1341,31933,25,625;QS=0.982671,0.0173288,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.983663;BQB=1;MQ0F=0	PL:DP	0,143,255,181,255,255:61
contig86	436288	.	T	<*>	.	.	END=436313;MinDP=60;QS=1,0	PL:DP	0,181,255:60
contig86	436314	.	C	T,<*>	0	.	DP=66;I16=0,0,37,23,0,0,2286,88498,0,0,3579,213921,0,0,1347,32301;QS=0,1,0;VDB=0.000269093;SGB=-0.693147;MQSB=0.98483;MQ0F=0	PL:DP	255,181,0,255,181,255:60
contig86	436315	.	C	<*>	.	.	END=436331;MinDP=58;QS=1,0	PL:DP	0,175,255:58
contig86	436332	.	C	A,<*>	0	.	DP=64;I16=36,26,1,0,2407,94767,22,484,3630,214452,60,3600,1332,31498,25,625;QS=0.990898,0.00910219,0;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.957934;BQB=1;MQ0F=0	PL:DP	0,167,255,187,255,255:63
contig86	436333	.	G	<*>	.	.	END=436380;MinDP=43;QS=1,0	PL:DP	0,129,255:43
contig86	436381	.	A	C,<*>	0	.	DP=46;I16=16,13,6,5,1063,40001,415,16013,1591,89731,600,33600,596,13730,270,6642;QS=0.717495,0.282505,0;VDB=0.121466;SGB=-0.676189;RPB=0.847377;MQB=0.999885;MQSB=0.236088;BQB=0.847377;MQ0F=0	PL:DP	196,0,255,255,255,255:40


Thanks!

**Comment by pd3** [comment]
Thank you for the output. The problem seems unrelated to gVCF, this is a general behavior of mpileup which outputs snps and indels in separate records and sometimes generates ambiguities like that. This is usually dealt with at the stage of variant filtering. I am afraid this is a bigger problem which will not be addressed anytime soon.

**Comment by Jhermes22** [comment]
Thanks for looking into this further. Could you please just let me know why would bcftools filter (with -g3 option) not mark the SNP as failing the filter? Or am I misunderstanding the -g option:
    -g, --SnpGap <int>            filter SNPs within <int> base pairs of an indel

**Comment by pd3** [comment]
Hmm, can't reproduce this. Assuming you are referring to the position 436259, this prints the desired output:

    $ bcftools filter -s SnpGap -g3 test.vcf | bcftools query -f'%CHROM:%POS %FILTER %REF %ALT\n' -t contig86:436259
    contig86:436259 SnpGap C A,<*>
    contig86:436259 PASS catctcgggtaatctcgggtaatctcgggtaatctcg cATCTCGGGTAATCTCGGGTAatctcgggtaatctcgggtaatctcgggtaatctcg

**Comment by Jhermes22** [comment]
Sorry for the late reply.

I am afraid I still get the two variants as passing the filters, please see below. I also get a warning about the filter name. 

$BCFTOOLS -v
bcftools 1.3.1-157-g54a215f
Using htslib 1.3.2-132-g609120d
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$BCFTOOLS filter -s SnpGap -g3 test.vcf | bcftools query -f'%CHROM:%POS %FILTER %REF %ALT\n' -t contig86:436259
Warning: using "SnpGap" filter name instead of "SnpGap"
contig86:436259 PASS C A
contig86:436259 PASS catctcgggtaatctcgggtaatctcgggtaatctcg .

**Comment by pd3** [comment]
That's odd, any chance you could send me the test file you are using? There is an email on my profile  page. Thank you.

**Comment by pd3** [comment]
Ah, I see the problem now: the program does the correct thing here, the second record is not a deletion. It is a reference call, the ALT allele is `.`.

**Comment by Jhermes22** [comment]
Ok, I understand now. Thanks for your help with all this!
