### ISSUE TITLE
bcftools concat -l question

### ISSUE THREAD

**Issue by wvnicholson** [samtools/bcftools#502]
I was having difficulties with the vcftools program vcf-phased-join and somebody on the vcftools mailing list suggested using "bcftools concat -l".  I thought I should check if "bcftools concat -l" really does the same thing?  Also, I'm having another "bcftools concat -l" - with a large-ish set of VCF files I get the error message "The chromosome block 1 is not contiguous".  What exactly does this mean?  (The VCF files are from lifting over - using Picard - phased VCF files between two somewhat different genome references),

William

**Comment by pd3** [comment]
Hi, it does the same thing, concatenates haplotypes by matching phase in overlapping haplotypes. The error message suggests that chromosomes in the VCF do not come in blocks, for example there could be records from chr1, then chr2, then chr1 again. This can be fixed by sorting the VCF, either by standard unix commands or `vcf-sort` from vcftools package.

**Comment by wvnicholson** [comment]
The type of blocking as described does not arise individually with any of the input VCF files specified in the command (i.e. although some files represent multiple chromosomes the lines for those chromosomes always group into blocks as described so once all of the lines for "chr1" are done we would never get back to "chr1" after the "chr2" lines in your example); but it may happen with intermediate files created by "bcftools concat -l".  Is the latter scenario possible?  (I am already using my own utility to get a list of VCF files sorted according to the first chromosome and base position in the file.  I am reluctant to do something more complex like breaking up the input VCF files into separate files according to chromosome as well unless that really is necessary.  However, I may look into that this afternoon anyway as I need to re-run the liftover program for an unrelated reason),
William

**Comment by wvnicholson** [comment]
It looked like I had this working with the VCF files split as described below (and after fixing a bug in my program that sorted the input file names); but with a larger example "bcftools concat -l" now just gives a segmentation fault and dumps core without giving a more informative error message,
William

**Comment by pd3** [comment]
Can you check if your files conform to VCF specification with `vcf-validator` please? Your description does not give enough information. Is it possible to create a test case to reproduce the problem?

**Comment by pd3** [comment]
Closing this now, please reopen with a test case if still an issue
