### ISSUE TITLE
VarScan VCF file deletion contains "-" in Alt field

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#507]
VarScan (v 2.4.2) uses the invalid Alt field character "-" to signify a deletion, as in Ref=C, Alt= -T, which should instead show two Ref bases and only the T as the Alt base.  I was surprised that bcftools (v 1.3.1) did not fix this.

**Comment by pd3** [comment]
I am closing the issue, please see https://github.com/samtools/bcftools/issues/506 for discussion
