### ISSUE TITLE
bcftools query %sample 

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#508]
I got an error trying to write the sample name using query.

bcftools-dev query -f '%SAMPLE %CHROM  %POS  %REF  %ALT\n' tmp.vcf.gz
Error: no such tag defined in the VCF header: INFO/SAMPLE

**Comment by pd3** [comment]
%SAMPLE is counted amongst format fields, so it should be enclosed in brackets, for example as

    bcftools query -f ['%SAMPLE %CHROM %POS %REF %ALT\n]' 

Here it depends on what exactly the output you are aiming for should look like

**Comment by dwaggott** [comment]
Thanks!
