### ISSUE TITLE
Genotype matrix with Sample Header

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#511]
Is there a way to get the sample names in the header of a query call? I tried using `%SAMPLE` and `-H`, however the indices and tag name are printed.

```
bcftools query -H -f '[\t%GT]\n' 
[1]U004257:GT [2]U004367:GT [3]U004621:GT [4]U012430:GT
```

**Comment by pd3** [comment]
Have you tried `bcftools query -l` ?

**Comment by dwaggott** [comment]
Yes that works. Oh, right I could just `cat` that on without outputting the header.

**Comment by dwaggott** [comment]
For completeness on creating a big GT matrix... for loading into R

```
(bcftools query -l xxx.vcf.gz | tr "\n" "\t" &&  bcftools query -f '[\t%GT]\n' xxx.vcf.gz) > genotype_matrix.txt
```
