### ISSUE TITLE
query output ALT allele count 

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#512]
Feature request. When generating a big GT matrix using `query` as referenced in #511 it would be great if the GT's could be converted into a numerical value i.e. count of ALTs. Something similar to the translated genotype functionality already reported.

`%TGT            Translated genotype (e.g. C/A)`

**Comment by pd3** [comment]
This should be possible by streaming first through `+fill-tags` plugin and then output `%AC`. Or is that different from what you need?

**Comment by dwaggott** [comment]
Not sure, I'm looking for the FORMAT/SAMPLE level allele counts. i.e. 0/0=0, 0/1=1, 1/1 =2

**Comment by pd3** [comment]
Ah, OK, no, that's different. So no, we don't have a tool for that.

**Comment by dwaggott** [comment]
Right, I'll close. It probably fits better as a convert function. i.e. ped format.

**Comment by mcshane** [comment]
I think +dosage is close to what you want. You could probably hack it to your needs.

**Comment by pd3** [comment]
Ah, that's right. Forgot about that one. Thanks @mcshane

**Comment by dwaggott** [comment]
Oh! Totally missed that. Thanks.
