### ISSUE TITLE
problem with expression logic when checking if a field is missing OR something else

### ISSUE THREAD

**Issue by jaredo** [samtools/bcftools#513]
Hello!

Maybe I am using  expressions incorrectly, but I cannot get the following to work. I wish to extract variants where an annotated frequency is less than 0.01 or where that frequency is missing (ie. it is probably rare).

eg.

```
#example file
$ bcftools view -H test.vcf
chr7	117120162	.	C	T	.	PASS	EXAC_AF=2.471e-05
chr7	117305137	.	C	T	.	PASS	.

#as expected
$ bcftools view -i 'EXAC_AF<.01' test.vcf -H
chr7	117120162	.	C	T	.	PASS	EXAC_AF=2.471e-05

#as expected
$ bcftools view -i 'EXAC_AF="."' test.vcf -H
chr7	117305137	.	C	T	.	PASS	.

#not expected
$ bcftools view -i 'EXAC_AF="."|EXAC_AF<.01' test.vcf -H
chr7	117120162	.	C	T	.	PASS	EXAC_AF=2.471e-05

$ bcftools view -i 'EXAC_AF="."||EXAC_AF<.01' test.vcf -H
chr7	117120162	.	C	T	.	PASS	EXAC_AF=2.471e-05
```

[The example file is here](https://gist.github.com/jaredo/3d24df591d5e33818854a369feb66b13)

**Comment by pd3** [comment]
Hi, you are using it right, there is a bug in handling missing values. Thank you for reporting the bug, it is now fixed.
