### ISSUE TITLE
Segfault with +setGT and -i/-e

### ISSUE THREAD

**Issue by terhorst** [samtools/bcftools#514]
I get a segfault when trying to using the setGT plugin with the newly added filtering feature. The offending lines seem to be plugins/setGT.c:232-233. `smpl_pass` is hardcoded to `NULL` on line 46, so dereferencing leads to the crash. Since there is no ability to select on sample anyways, commenting out those lines fixes it for me.

**Comment by pd3** [comment]
Thank you for reporting the bug, this is now fixed
