### ISSUE TITLE
documentation ahead of `master` branch

### ISSUE THREAD

**Issue by jrandall** [samtools/bcftools#515]
The documentation at  https://samtools.github.io/bcftools/bcftools.html lists the `fixref` plugin but this is not yet available in any released version or on the `master` branch. 

https://github.com/samtools/bcftools/blob/gh-pages/bcftools.html#L1846-L1848

**Comment by jmarshall** [comment]
The documentation for released versions is at <http://www.htslib.org/doc/>.  That there is also information at <https://samtools.github.io/bcftools/> that duplicates htslib.org is a problem.

See also #183.

**Comment by pd3** [comment]
The documentation tells which commit it refers to, see the section VERSION. The problem is not that bcftools.html is ahead of master branch, but that it takes so long to make a new release.

**Comment by jrandall** [comment]
@pd3 I think given that end users are confused by the docs, it would be useful if we could put a disclaimer right at the top of the page that says something to the effect of "This documentation refers to an unreleased development version of bcftools, please refer to http://www.htslib.org/doc/bcftools.html for documentation for the current release."
