### ISSUE TITLE
Feature request: Sort

### ISSUE THREAD

**Issue by Jacob-Munro-VCCRI** [samtools/bcftools#526]
Hi,

I really appreciate bcftools and find it very useful, however one issue that I frequently run into is that various callers will output unsorted vcf files. It would be very useful to have a sort function built into bcftools, and possibly could automatically be performed when bcftools index is used.

Thanks,
Jacob.

**Comment by tommycarstensen** [comment]
Hi Jacob,

Can you use the built in unix `sort`?

    cat <(zcat $vcf | grep -B10000 -m1 ^#CHROM) <(bcftools view -H $vcf | sort -k1V,1 -k2n,2) | bgzip > out.vcf.gz

There is probably a more elegant way of printing the header of a VCF files, which I don't know about...

P.S. Which caller generates unsorted VCF files? I'm pretty sure one of the ten commandments is to not generate unsorted VCF files...

**Comment by pd3** [comment]
The `bcftools sort` command has been now added https://github.com/samtools/bcftools/commit/8fe6acd8bb405fa8215852c045c531256db6371d. Please let  me know if you encounter any problems.

**Comment by lokeyCEU** [comment]
Thanks for adding this! bcftools sort is going to be a lifesaver.
Will it be able to do lexical and numerical sorting?

**Comment by pd3** [comment]
In this version it leaves the chromosomes in the default order given by the VCF header. I am unlikely to add chromosome reordering myself anytime soon, but happy to accept pull requests.
