### ISSUE TITLE
feature request: option to remove/exclude sites with -R ^FILE

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#527]
One can do -S ^FILE to treat FILE as an exclusion set rather than an inclusion set. I just realised to my surprise, that you can't do the same with -R ^FILE. I would like to request this feature.

I'll just generate an inclusion regions list instead of an exclusion regions list for now. Thanks!

**Comment by pd3** [comment]
One can use `-T ^FILE`, but we don't plan supporting `-R ^FILE`, sorry!

**Comment by tommycarstensen** [comment]
Sorry, I was about to close. Just read the docs: "Unlike -r, targets can be prefixed with "^" to request logical complement."
