### ISSUE TITLE
No windows found on "official" test data after v1.3? Worked well in v1.2.

### ISSUE THREAD

**Issue by dnil** [samtools/bcftools#529]
Semi-official [test for bcftools roh](https://samtools.github.io/bcftools/howtos/roh-calling.html) does not find any autozygous regions after upgrade to v1.3. Could you please verify that it is still performing as intended? Thank you!

**Comment by pd3** [comment]
There have been quite a few bug fixes and changes since v1.3. Can you please try the latest version which can be obtained as described here? http://samtools.github.io/bcftools/

**Comment by dnil** [comment]
Works well with latest version!

**Comment by rernst** [comment]
Is it possible to create an official release containing these fixes or can you give me an eta for the next release? Thanks!

**Comment by mcshane** [comment]
1.4 was released on March 13
