### ISSUE TITLE
FORMAT offsets may point to INFO offsets.

### ISSUE THREAD

**Issue by bicycle1885** [samtools/bcftools#536]
When `INFO` and `FORMAT` have a same name entry (e.g. `DP`), the `fmt_key` field value of `FORMAT` points to the former offset rather the latter one. The following would be the minimal reproducible input:
```
##fileformat=VCFv4.3
##contig=<ID=chr1>
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA00001
chr1	1	.	A	C	1	PASS	DP=10	DP	11
```

```
$ bcftools --version
bcftools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ bcftools view -O b bug.vcf >bug.bcf
$ gzip -cd bug.bcf | hexdump -C | tail -6
00000170  09 49 4e 46 4f 09 46 4f  52 4d 41 54 09 4e 41 30  |.INFO.FORMAT.NA0|
00000180  30 30 30 31 0a 00 23 00  00 00 04 00 00 00 00 00  |0001..#.........|
00000190  00 00 00 00 00 00 01 00  00 00 00 00 80 3f 01 00  |.............?..|
000001a0  02 00 01 00 00 01 07 17  41 17 43 11 00 11 01 11  |........A.C.....|
000001b0  0a 11 01 11 0b                                    |.....|
000001b5
```

Looing at the last few lines of the hexdump, the format key offset looks
pointing to a wrong entry (here the INFO DP):

    000001b0  0a 11 01 11 0b                                    |.....|
                    ^^
                    I think this is expected to be 02 because it points to the FORMAT DP.

Is this an expected output or a bug?

**Comment by pd3** [comment]
The the dictionary of strings (that is, tag names) in the header does not distinguish between INFO and FORMAT. If the tag name is the same, an identical value is used. So no, it is not a bug.
