### ISSUE TITLE
Filtering genotypes by logic and regex produces unexpected results

### ISSUE THREAD

**Issue by mrtnb** [samtools/bcftools#538]
I am trying to filter heterozygous reference variants from my single sample VCF file. To do so I thought to use the filter command to include samples, for which the unphased genotypes (1/0, 2/0, ...) match a regex. It works fine for one allele:
```
$ bcftools filter --include 'GT~"0/[1-9]"' my.vcf | grep -v "^#" | cut -f 10 | cut -d':' -f1 | sort | uniq -c
   1074 0/1
      6 0/2
```
But I also have heterozygous reference variants of the form  0/1, 0/2 etc. So I extended the expression but ran into problems with this:
```
$ bcftools filter --include 'GT~"0/[1-9]" || GT~"[1-9]/0"' my.vcf | grep -v "^#" | cut -f 10 | cut -d':' -f1 | sort | uniq -c
     27 ./.`
   6434 0/0`
   1074 0/1`
      6 0/2`
   1059 1/0`
   1342 1/1`
      1 1/2`
      1 2/0`
      8 2/2`
```
As you see there are matches for 0/0, 1/1 and 2/2, that I do not want to include. Is this an issue with the interpreter of the expression?

bcftools 1.3.1
Using htslib 1.3.1

**Comment by pd3** [comment]
Hi, thank you for reporting the bug. It was fixed a while ago, can you use the latest version? Please see the installation instructions here http://samtools.github.io/bcftools/

**Comment by mrtnb** [comment]
The development version worked for me. Thanks.
