### ISSUE TITLE
--pval-threshold option with multiallelic caller 

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#542]
Hi,

Does the -p option work for -m (multi allelic caller) as well? In the help section and the manual its mentioned only for consensus caller (-c).. Ex:
-p, --pval-threshold <float>    variant if P(ref|D)<FLOAT with -c [0.5]

**Comment by pd3** [comment]
Hi, just updated the documentation: `-p` works with `-c` only, please use `-P` with `-m`

**Comment by prasundutta87** [comment]
Thanks..so by default its 1.1e-3 (0.001), and it will be applied even if I don't use -P?

**Comment by pd3** [comment]
That's correct, the default value is 0.001.

**Comment by prasundutta87** [comment]
Great..thanks a lot for your help..I don't have to re-run the program now since it was applied by default..
