### ISSUE TITLE
bcftools norm command error messages

### ISSUE THREAD

**Issue by cmccabe1** [samtools/bcftools#543]
I am not sure what the below means as I do not see them in the attached .vcf.  Thank you.
[file.vcf.gz](https://github.com/samtools/bcftools/files/745629/file.vcf.gz)

    `bcftools norm -m-both -o step1.vcf file.vcf.gz
    [W::vcf_parse] INFO 'CLCNKB' is not defined in the header, assuming Type=String
    [W::vcf_parse] INFO 'DOCK7,ANGPTL3' is not defined in the header, assuming Type=String
    Could not parse the header line: "##INFO=     <ID=DOCK7,ANGPTL3,Number=1,Type=String,Description="Dummy">"
    [E::vcf_parse] Could not add dummy header for INFO 'DOCK7,ANGPTL3'
    [W::vcf_parse] INFO 'AP4B1-AS1' is not defined in the header, assuming Type=String
    [W::vcf_parse] INFO 'FLG' is not defined in the header, assuming Type=String
    [W::vcf_parse] INFO 'PPOX,B4GALT3' is not defined in the header, assuming Type=String
    Could not parse the header line: "##INFO= <ID=PPOX,B4GALT3,Number=1,Type=String,Description="Dummy">"
    [E::vcf_parse] Could not add dummy header for INFO 'PPOX,B4GALT3'
    [W::vcf_parse] INFO 'PPOX,B4GALT3' is not defined in the header, assuming Type=String
    Could not parse the header line: "##INFO=<ID=PPOX,B4GALT3,Number=1,Type=String,Description="Dummy">"
    [E::vcf_parse] Could not add dummy header for INFO 'PPOX,B4GALT3'
    Lines   total/split/realigned/skipped:	760/13/0/0`

**Comment by pd3** [comment]
The error messages are correct. For example you could run a command like this to view the lines with the undefined annotation CLCNKB

      zcat file.vcf.gz | awk '$8~/[\t;]CLCNKB/' | less

This can be fixed by editing the header and replacing

      bcftools view -h file.vcf.gz > header.txt
      # edit the header
      bcftools reheader -h header.txt file.vcf.gz > fixed.vcf.gz

**Comment by cmccabe1** [comment]
So by processing these vcf files that have undefined annotation in them, there is minimal loss? By that I mean if they are undefined maybe they are not real/low quality?  I guess I am just confused as to why undefined is there anyway? Thanks.

**Comment by pd3** [comment]
No, that's a purely technical matter, nothing to do with quality - the program that produced the VCF simply did not bother to add the annotation description to the header. The specification allows this for VCF, but it is discouraged because the binary version, BCF, needs to have the declarations in order to function properly.

**Comment by cmccabe1** [comment]
Thank you very much for all your help :).
