### ISSUE TITLE
--trim-alt-alleles do not updates the AD field

### ISSUE THREAD

**Issue by npatel22526** [samtools/bcftools#545]
Hi 

The --trim-alt-alleles option does not seems to update the AD field, when ALT is trimmed. See below 
Sample1.trio.vcf is normal vcf that extracted from a large VCF and Sample1.trio.post.trim.vcf is vcf after --trim-alt-alleles.

- Sample1.trio.vcf
chr1	16054878	.	C	A,T	1498.02	PASS	AC=0,2;AF=0.0003078,0.0006771;AN=6;	GT:AD:DP:GQ:PL	0/2:**2,0,9**:11:44:263,269,341,0,72,44	0/2:**14,0,3**:17:64:64,106,506,0,399,390	0/0:14,0,0:14:30:0,30,450,30,450,450

- Sample1.trio.post.trim.vcf
chr1	16054878	.	C	T	1498.02	PASS	AC=2;AF=0.0006771;AN=6;	GT:AD:DP:GQ:PL	0/1:**2,0,9**:11:44:263,0,44	 0/1:**14,0,3**:17:64:64,0,390	0/0:14,0,0:14:30:0,30,450

This makes it harder to parse VCFs for downstream analysis.

Thanks,
Nick

**Comment by mcshane** [comment]
How is `AD` defined in your header? Unless it is defined as `Number=R`, there is no way for bcftools to know that there should be one value per allele and hence trim upon removal of alleles. `bcftools reheader` can be used to edit your header if necessary.

**Comment by npatel22526** [comment]
Thanks you so much for quick response, there was indeed the issue. I had "Number=." for the AD.

After fixing the header the issue solved. 

best,
Nich
