### ISSUE TITLE
bgzip

### ISSUE THREAD

**Issue by charlesdavid** [samtools/bcftools#551]
I am trying to use bcftools isec. I can not index or run isec without getting error about file not compressed with bgzip. Manual says that these tools work with normal vcf and bcf files. What gives? I do not use bgzip.

**Comment by pd3** [comment]
The files need to be indexed, for that they need to be compressed. One can either use external tools (bgzip and tabix from htslib) or use the `-Ob` or `-Oz` bcftools options. Please check the documentation here http://samtools.github.io/bcftools/bcftools.html

**Comment by charlesdavid** [comment]
Yes, used the bcf step. Thanks!
