### ISSUE TITLE
Query slow w/ 1000's samples: option to skip reference genotypes? (performance)

### ISSUE THREAD

**Issue by akotlar** [samtools/bcftools#557]
My goal is to find all non-reference samples as quickly as possible, while also still outputting Chrom, Pos, Ref, Alt. I don't particularly care about reference genotypes or missing genotypes.

Right now processing a 1000G vcf file using bcftools query (or bcftools view -Ou | bcftools query ) is quite slow. One option that seems reasonable is to reduce the burden of calculating the genotype for any given sample if it is reference. It could be outputted instead as a "." to keep in line with missing data schema of VCF. Right now I am essentially doing this in a downstream step, but processing time is lost. This could be provided as a flag, such as --ref-to-missing.

**Comment by tommycarstensen** [comment]
Can you provide an example? Your question is not quite clear to me. Thanks.

Would the flags `--private` and `--min-ac` be relevant to your query? You need to loop over the entire VCF file no matter what. There is no way around that.

**Comment by akotlar** [comment]
Sure, take any [1000 genomes phase 3 vcf](http://www.internationalgenome.org/data), and run:

```
bcftools query - -H -f '%CHROM\\t%POS\\t%REF\\t%ALT\\t%TYPE[\\t%IUPACGT]\\n'
```

It's not about reading (or looping) over the entire file, rather skipping unneeded work for any given line. bcftools provides several options to skip rows that have missing data entirely, but no option to keep the line and exclude samples that are reference. This requires the user to manually handle that downstream.

My ideal scenario is that we allow a flag (say --remove-invariant-gt), which outputs
SampleGenoIUPACGT SampleIdx Sample2GenoIUPACGT Sample2Idx
for all samples that are non-reference and non-missing ('./.','.|.','0/0',and '0|0' would all be skipped). The indices refer to the position of that sample in the header, to maintain 1:1 relationship, or, if you prefer, output sample names via %SAMPLE, as query already allows.

This is a significant change, so I instead proposed a smaller solution, to just call reference sample genotypes as missing, which will prevent bcftools query from transforming those genotypes when paired with IUPACGT.

The goal here is to make bcftools perform slightly faster with large sample files, and to save people the need to manually check every sample's genotype to determine whether they should care about it or not. A valid, and maybe common use case of bcftools is to find all variants that have non-reference genotypes and do something with those samples.
