### ISSUE TITLE
View seems to exit from header-related warnings with unchecked error (2)

### ISSUE THREAD

**Issue by akotlar** [samtools/bcftools#558]
In my case, the below warnings are completely ok, and the same warnings in ```bcftools query``` don't result in unrecoverable error. However, view seems to die because of them, or due to an unreported error.

Warnings should not cause early exit, or we should be able to suppress them with a --quiet option.
```
[W::vcf_parse] contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] INFO 'NS' is not defined in the header, assuming Type=String
[vcf.c:1479 bcf_write] Unchecked error (2), exiting.
```

**Comment by pd3** [comment]
Hi, sorry for the delay in responding. The difference between the two commands is that `view` can output a BCF. Why does it matter? The binary BCF format stores the tag names in the header and in the body only references the names, therefore all tags must be known at the time the header is written. You can fix the file using `bcftools reheader`.
