### ISSUE TITLE
adding undefined annotations to vcf before processing

### ISSUE THREAD

**Issue by cmccabe1** [samtools/bcftools#560]
I am using bcftools version 1.3.1 and trying to add undefined annotations to a vcf before using bgzip and tabix.

If I try to run the norm command on the vcf I get:
```
bcftools norm -m-both -o file.vcf file.vcf.gz
     [W::vcf_parse] INFO 'RSC1A1,RSC1A1' is not defined in the header, assuming Type=String
     Could not parse the header line: "##INFO=     <ID=RSC1A1,RSC1A1,Number=1,Type=String,Description="Dummy">"
```

So I use:
    ```
     # find undefined annotations#
     bcftools view -h file.vcf > header.txt
     # add undefined to vcf#
     bcftools reheader -h header.txt file.vcf > fixed.vcf
```

I then use bgzip and tabix on the fixed.vcf and rerun the norm command:
    ```
 bcftools norm -m-both -o fix.vcf fixed.vcf.gz
     [W::vcf_parse] INFO 'RSC1A1,RSC1A1' is not defined in the header, assuming Type=String
     Could not parse the header line: "##INFO= <ID=RSC1A1,RSC1A1,Number=1,Type=String,Description="Dummy">"
     [E::vcf_parse] Could not add dummy header for INFO 'RSC1A1,RSC1A1'
     [W::vcf_parse] INFO 'RSC1A1,RSC1A1' is not defined in the header, assuming Type=String
     Could not parse the header line: "##INFO=<ID=RSC1A1,RSC1A1,Number=1,Type=String,Description="Dummy">"
     [E::vcf_parse] Could not add dummy header for INFO 'RSC1A1,RSC1A1'
     Lines   total/split/realigned/skipped:	116/4/0/0
```

However, I am getting the same error as the undefined annotations is not added. I attached the original vcf renamed as a txt.  Thank you :).

[file.txt](https://github.com/samtools/bcftools/files/803821/file.txt)

**Comment by pd3** [comment]
Hi,
is it an intention or a mistake, to have a tag name with a comma in it? Such names are not allowed. To remove the second part, the following command can be used

    cat file.vcf | sed 's/RSC1A1,RSC1A1/RSC1A1/' > fixed.vcf

**Comment by cmccabe1** [comment]
This is an intention, well, it is how the vcf output from the instrument.  If the undefined annotations are variable, depending on the vcf being processed, what is the best way remove all instances of the secong part after the comma.  That is in vcf 1 it may be RSC1A1,RSC1A1,RSC1A1, but in vcf 2 be RSC1A1,RSC1A1,RSC1A1 and GRB3,GRB3.  Is there a way to guard against multiple entries/detect them in each vcf before the header is edited?  Thank you :).

**Comment by pd3** [comment]
Modify the expression like this

    cat file.vcf | sed 's/RSC1A1,[^\t;]*/RSC1A1/ ; s/GRB3,[^\t;]*/GRB3/' > fixed.vcf

**Comment by pd3** [comment]
I believe this has been resolved, reopen if not
