### ISSUE TITLE
bcftools csq: Aborted (core dumped)

### ISSUE THREAD

**Issue by sigurjonaxel** [samtools/bcftools#561]
I seem to have found a bug in bcftools csq when using this variant 

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
7	65140974	chr7:65140974:XG	CCC	CC,TG	698977	.	.

bcftools csq -f Homo_sapiens.GRCh38.dna.primary_assembly.fa -g Homo_sapiens.GRCh38.87.gff3.gz  bug2.vcf

Indexed 196822 transcripts, 1180930 exons, 704604 CDSs, 276325 UTRs
Calling...
bcftools: csq.c:2061: hap_init: Assertion `dbeg <= splice.kalt.l' failed.
Aborted (core dumped)

files :
ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa
ftp://ftp.ensembl.org/pub/release-87/gff3/homo_sapiens/Homo_sapiens.GRCh38.87.gff3.gz
[bug2.vcf.gz](https://github.com/samtools/bcftools/files/803893/bug2.vcf.gz)

Best regards,
Sigurjon

**Comment by pd3** [comment]
Thanks very much for the bug report and the test case. The commit 7d91cb7 should fix the issue. Let me know in case of problems.
