### ISSUE TITLE
--delete option for mendelian plugin removes site instead of converting GT to ./.

### ISSUE THREAD

**Issue by pkothiyal** [samtools/bcftools#566]
I'm trying to understand the different options available for +mendelian and here's something I was hoping to clarify. I have a test VCF (MIE for trio1, chr1:100):
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mom1    dad1    child1  mom2    dad2    child2
chr1    100     .       A       G       100     PASS    .       GT      **0/0     0/0     1/1**     1/1     0/1     1/1
chr1    101     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0
chr1    102     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0

and here's the output VCF I get with different options (in bold):
##bcftools_pluginVersion=1.3.1-144-ge844d50-dirty+htslib-1.3.2-80-g4295de4
##bcftools_pluginCommand=plugin mendelian -- test.mie.vcf -T test.trio.txt **-d**; Date=Mon Mar  6 13:15:15 2017
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mom1    dad1    child1  mom2    dad2    child2
chr1    101     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0
chr1    102     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0

##bcftools_pluginCommand=plugin mendelian -- test.mie.vcf -T test.trio.txt **-l+**; Date=Mon Mar  6 13:16:35 2017
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mom1    dad1    child1  mom2    dad2    child2
chr1    101     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0
chr1    102     .       A       T       100     PASS    .       GT      0/0     0/1     0/1     1/1     0/1     1/0

##bcftools_pluginCommand=plugin mendelian -- test.mie.vcf -T test.trio.txt **-lx**; Date=Mon Mar  6 13:16:01 2017
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mom1    dad1    child1  mom2    dad2    child2
chr1    100     .       A       G       100     PASS    .       GT      0/0     0/0     1/1     1/1     0/1     1/1

Based on the help message, I expected -d (--delete) option (first output above) to convert inconsistent GT to ./. while still keeping the site instead of deleting the row altogether. It seems to show the same behavior as option -l+. Is this expected and am I misinterpreting --delete?

Thanks,
Prachi

**Comment by pd3** [comment]
This indeed is a bug, fixed just now. Thank you for letting us know.
