### ISSUE TITLE
bcftools view -v snps not working for multiallelics

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#567]
I have this VCF file:

```
##fileformat=VCFv4.2
##fileDate=20140319
##reference=human_g1k_v37.fasta
##contig=<ID=20,length=63025520,assembly=b37>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Net Genotype across all datasets">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
20      13607554        .       CC      CCC,CT  4755.1  PASS    .       GT      1|2
```

When I run `bcftools view -v snps` on it, then the record is printed despite being an indel. Is this the expected behaviour?

**Comment by mcshane** [comment]
This is one indel (`CC>CCC`)  and one SNP (`CC>CT`), which is actually `C>T` at 20:13607555.

**Comment by tommycarstensen** [comment]
Thanks Shane. But in this file it's the indel `CC>T` for sample NA12878, which is the only sample present. Isn't bcftools wrong? Or does bcftools not consider individual genotypes? Ahhh, it just considers the record it seems. OK, I get it. Still unfortunate though. Thanks!

**Comment by mcshane** [comment]
Well, one chromosome has the insertion and one the SNP, but yes this filtering option does not look at genotypes at all.
