### ISSUE TITLE
cannot find -llzma

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#570]
FYI I got a dependency error after the latest update.

```
gcc -rdynamic   -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o bin.o hclust.o version.o regidx.o smpl_ilist.o csq.o mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o ccall.o em.o prob1.o kmin.o  ../htslib/libhts.a -lpthread -lz -lm -lbz2 -llzma  -lm -lz -ldl 
/home/dwaggott/.linuxbrew/bin/ld: cannot find -llzma
collect2: ld returned 1 exit status
make: *** [bcftools] Error 1
```

Daryl

**Comment by jkbonfield** [comment]
This is a consequence of moving mpileup from samtools to bcftools (I think, unless bcftools could read BAM/CRAM elsewhere already) coupled with htslib gaining support for lzma/bzip2 in CRAM.  The two combined together means that bcftools now requires lzma/bz2 libraries in order for mpileup on CRAM files to work.

However this is an issue with the INSTALL file which doesn't explain this.  Sorry for the omission.

**Comment by daviesrob** [comment]
If you're not interested in reading CRAM files, you can remove this dependency by going into htslib and running:
```
make distclean
./configure --disable-lzma
make
```

See HTSlib's INSTALL file for how to make `configure` if you don't already have it.

Then in bcftools:
```
make distclean
make
```
That should get you a liblzma-free bcftools.

**Comment by xindiguo** [comment]
I got this error when trying to remove the dependency.
`-bash: ./configure: No such file or directory`

**Comment by pd3** [comment]
I think one needs to run `autoheader` and `autoconf` first to generate `configure`.

**Comment by xindiguo** [comment]
I have installed the xz package instead and it worked.

**Comment by achalneupane** [comment]
@daviesrob Thanks, that works!
