### ISSUE TITLE
Problem building with an installed htslib

### ISSUE THREAD

**Issue by jenniferliddle** [samtools/bcftools#573]
The Makefile has a line:
include $(HTSDIR)/htslib_static.mk

If HTSDIR points to an installed htslib (rather than somewhere you have built it) then htslib_static.mk does not exist.
An installation directory is set to read-only, which means that when the makefile tries to make this file, it fails.

**Comment by daviesrob** [comment]
It also tries to include `$(HTSDIR)/htslib.mk`, which also isn't installed.

As far as I can tell, bcftools cannot currently build against an installed htslib.  We can fix this by copying over some of the autoconf files from samtools.
