### ISSUE TITLE
Bcftools minimal support reads 

### ISSUE THREAD

**Issue by sunliang3361** [samtools/bcftools#574]
Hi, what is the default minimal support reads for bcftools to call a snp/indel? I found that there is an indel in my sample with two support reads, it seems that bcftools will not consider it as an indel. Is there any parameter I can set up for the minimal support reads (such as varscan)? Thanks

**Comment by pd3** [comment]
This is in the `mpileup` part, check the `-F`, `-m` and `-p` options.
