### ISSUE TITLE
bcftools call -v option

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#577]
Hi,

according to the help section of bcftools call, -v is variant sites only. I get both indels and SNVs with it.

When I don't use -v option, I do not get any result, as in no variants are discovered except a few indels. And all my GT field is 0/0. Could you please explain this difference?

**Comment by pd3** [comment]
Sorry, I don't understand the question. The `-v` option drops sites which have no alternate allele (`ALT=.`). That is the only difference.

**Comment by prasundutta87** [comment]
Thank you for the clarification.

**Comment by prasundutta87** [comment]
I believe I can close the issue on my own?
