### ISSUE TITLE
bcftools mpileup --redo-BAQ option

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#578]
Hi,

How important is it to use --redo-BAQ option?

If I don't use it, isn't BAQ calculated by default from the original BQ (base quality) scores?

**Comment by pd3** [comment]
The option takes effect only if the BQ tag is already present in the BAM and you need to redo it from some reason. So generally you don't need it.

**Comment by prasundutta87** [comment]
Ok. So is there any way to see the calculated BAQ score in the final VCF file? I am inherently not producing the mpileup file to save space. I am using this command:

 bcftools mpileup -q 60 -f reference.fa alignment.bam -O u | bcftools call -mv > result.vcf

**Comment by pd3** [comment]
No, the BAQ values are calculated at the level of reads, the VCF only shows the positions.

**Comment by prasundutta87** [comment]
Ok. Thank you for the information. I just wanted to know the range of BAQ scores for my general understanding because I read in the manual that BAQ scores are lower for single nucleotide variants that are near INDELS and bcftools won't call a variant from that particular position.
