### ISSUE TITLE
BCFTools does not see BCF files when merging

### ISSUE THREAD

**Issue by heatherself18** [samtools/bcftools#580]
I'm trying to merge multiple BCF files and I keep running in the an error were bcftools does not recognize the files. Here is my code and the error: 
heather@heather-G55VW:~/Downloads/bcftools$ ./bcftools merge -l listbcf.txt -Ob -o AllBCF.bcf
[E::hts_open_format] fail to open file '123771.bcf	    432540.bcf	 759248.bcf  B012.bcf  B078.bcf  B149.bcf'
Failed to open 123771.bcf	    432540.bcf	 759248.bcf  B012.bcf  B078.bcf  B149.bcf: No such file or directory

I'm working on a linux. The files names in the list all match file names in the folder and when I put in a view command I do not run in to a fail to open problem.

**Comment by pd3** [comment]
What does the file `listbcf.txt` look like? There should be one file name per line.

**Comment by heatherself18** [comment]
That was the issue! changed the file to be one name per line and it merged fine! 

Thanks for the help!

**Comment by pd3** [comment]
Good, glad the problem was found. The documentation has been updated to make this clear.
