### ISSUE TITLE
bcftools: vcfnorm.c:705: split error

### ISSUE THREAD

**Issue by mehar-GIT** [samtools/bcftools#581]
I am trying to split multi-allelic variants in a VCF file generated by CombineVariants module in GATK. which combines the vcf files from GATK and samtools.  

$bcftools norm -m-both -o out1.vcf SNP_INDEL_raw.vcf.gz
bcftools: vcfnorm.c:705: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted

I checked the thread ( https://github.com/samtools/bcftools/issues/382 )  but did not help in this case which suggests something to do with AC_Het tag in the header. However, i do not have this tag in my vcf header. COuld someone help to fix this?

**Comment by pd3** [comment]
The error is caused by incorrect number of fields of some tag. I believe the most recent version of bcftools prints a more informative message. Can you try that please?

**Comment by mehar-GIT** [comment]
Hi,

 

The installation of the new version fails as shown below with ‘make install’.

 

…..

gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c

cram/cram_io.c:60:18: fatal error: lzma.h: No such file or directory

compilation terminated.

make[1]: *** [cram/cram_io.o] Error 1

make[1]: Leaving directory ` /bcftools-1.4/htslib-1.4'

make: *** [htslib-1.4/libhts.a] Error 2

 

 

It does not give me more information to make a successful installation.

 

Br

Mehar

**Comment by pd3** [comment]
There is a new dependency on lzma, but that is not needed for most users. It can be disabled as described here https://github.com/samtools/bcftools/issues/570. It would be better if lzma was not required by default.

**Comment by mehar-GIT** [comment]
Hi,

 

Installation is successful by disabling Izma. This is how ‘norm’ works with the new version.

 

/bcftools-1.4/bcftools norm -m-both -o out1.vcf SNP_INDEL_raw.vcf.gz

Error: wrong number of fields in INFO/MLEAC at chrX:66915580, expected 2, found 1

 

Grepped the above variant from vcf file:

 

less TMP_files/SNP_INDEL_raw.vcf.gz | grep 66915580

chrX        66915580             .               AACACACACACACACACACACACACACACACACAC                AACACACACACACACACACACACACACACACACACACAC,AACACACACACACACACACACACACACACACACACAC 1592.73 .                AC=2,0;AC1=1;AF=1.00,0.00;AF1=0.5;AN=2;DP=411;DP4=6,19,25,40;FQ=206.309;FS=0.000;IDV=46;IMF=0.221154;INDEL;MLEAC=2;MLEAF=1.00;MQ0=0;MQ0F=0;MQSB=0.991377;PV4=0.225104,1,0.121592,0.271147;QD=7.85;SGB=-0.693147;SOR=0.693;VDB=7.95816e-08;set=GatkINDEL-SamINDEL  GT:DP:GQ             1/1:62:99

 

 

Could you suggest a fix now?

**Comment by pd3** [comment]
See the advice here https://github.com/samtools/bcftools/issues/382#issuecomment-183441130
Re-header the VCF, changing the expected number of fields to 'Number=.' for the INFO/MLEAC tag. In its current definition the VCF body does not match the definition in the header, the program cannot split the field.

**Comment by mehar-GIT** [comment]
Setting INFO/MLEAC and INFO/MLEAF to ‘Number=.’ Worked with bcftools split. However, does it lead to any loss of data in the final split version of vcf?

**Comment by pd3** [comment]
The tags will be repeated as is in both lines after splitting.

**Comment by sheerun** [comment]
Could bcftool fix records or just throw a warning instead?

**Comment by pd3** [comment]
There is an easy workaround, change the header to `Number=.`. BCFtools should not be trying to magically fix the records, this is the responsibility of program that generates the VCFs.
