### ISSUE TITLE
8000 read depth issue

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#583]
Hi,

Previously in the old version, samtools mpileup's max read depth was limited to 8000. I am aware that it was hardcoded into the main code of samtools. Was it to limit the memory usage or there is any scientific reason to it?

BCFtools mpileup does not show the 8000 message like previos samtools versions did. Is the max read depth still limited to 8000 or we can make it more?

**Comment by pd3** [comment]
The depth limitation is for performance reasons only. The maximum depth could be always set higher, the warning message was confusing. This is now fixed.
