### ISSUE TITLE
csq: allow disabling FORMAT annotation

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#586]
we (and I'm sure most users) only utilize the BCSQ in the INFO field. It would be nice if there were a way to disable FORMAT annotation.

**Comment by pd3** [comment]
This is currently possible with `--samples -` which ignores all samples. Do you mean you'd like to run the program in haplotype aware mode and still use only the INFO annotations?

**Comment by brentp** [comment]
aye, that's what I wanted--I should have guessed, but  could we have an explicit mention of this in the usage.
