### ISSUE TITLE
Does norm support breakends?

### ISSUE THREAD

**Issue by garrett-stevens** [samtools/bcftools#592]
I have a VCF that was created from a structural variant calling tool. When I try to normalize it using BCFtools norm, I get an error referencing a "Non-ACGTN alternate allele." Here's the line from the VCF:
```
#CHROM	POS	ID	REF	ALT
1       797265  .  G       G]8:245687]
```
And here's my command and error:
```bash
bcftools norm --fasta-ref data/human_g1k_v37_decoy.fasta.gz --multiallelics -both --output my_norm.vcf my.vcf
Non-ACGTN alternate allele at 1:797265 .. REF_SEQ:'(null)' vs VCF:'G]8:245687]'
```

This ALT allele looks to me like a breakend that's properly formatted to VCF 4.1 specs. Does norm support breakends? Or am I doing something wrong?

**Comment by pd3** [comment]
The command was not ready for breakends. This is now fixed, in the sense that the norm will ignore such records, rather than throwing an error. Note that you'll need to upgrade htslib once this pull request is merged https://github.com/samtools/htslib/pull/516
