### ISSUE TITLE
plot-vcfstats SyntaxError on Ubuntu 16.04

### ISSUE THREAD

**Issue by dburkhardt** [samtools/bcftools#593]
When I run plot-vcfstats, there's an error with the version of python that's being used. Here's the output.

```$ plot-vcfstats -p study.plots study.vcf.stats
Parsing bcftools stats output: study.vcf.stats
Plotting graphs: python plot.py
  File "plot.py", line 63
    if x.ndim != 1: raise ValueError, "smooth only accepts 1 dimension arrays."
                                    ^
SyntaxError: invalid syntax
The command exited with non-zero status 256:
	python plot.py

 at /usr/local/bin/plot-vcfstats line 76.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /usr/local/bin/plot-vcfstats line 275
	main::plot(HASH(0x1864080)) called at /usr/local/bin/plot-vcfstats line 65
```

My guess is that in `plot.py`, python3, not python2 is being invoked. I can't seem to find this file though.

**Comment by pd3** [comment]
The python script is generated by `plot-vcfstats`. This commit should fix the issue  https://github.com/samtools/bcftools/commit/68898afa967eb3175faed1918971c7bf65f67839

**Comment by pinninti1991** [comment]
Hi, how to solve this problem.
**CMD-** plot-vcfstats hg38multi.vchk -p plots/
Parsing bcftools stats output: hg38multi.vchk
Plotting graphs: python plots/plot.py
  File "plots/plot.py", line 60
    if x.ndim != 1: raise ValueError, "smooth only accepts 1 dimension arrays."
                                    ^
SyntaxError: invalid syntax
The command exited with non-zero status 256:
	python plots/plot.py

 at /usr/bin/plot-vcfstats line 78.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}python plots/pl"...) called at /usr/bin/plot-vcfstats line 271
	main::plot(HASH(0x27f55f0)) called at /usr/bin/plot-vcfstats line 67
