### ISSUE TITLE
use of undelcared identifier 'VCF_BND'

### ISSUE THREAD

**Issue by aguang** [samtools/bcftools#595]
after cloning bcftools and running make, I get the following error with filter:

echo '#define BCFTOOLS_VERSION "1.4-20-g52e9bb2"' > version.h
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o main.o main.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcfindex.o vcfindex.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o tabix.o tabix.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcfstats.o vcfstats.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcfisec.o vcfisec.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcfmerge.o vcfmerge.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcfquery.o vcfquery.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o vcffilter.o vcffilter.c
gcc -g -Wall -Wc++-compat -O2 -I. -I../htslib -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -I.   -c -o filter.o filter.c
filter.c:1618:82: error: use of undeclared identifier 'VCF_BND'
            else if ( !strcasecmp(out[ival].key,"bnd") ) { out[ival].threshold = VCF_BND<<1; out[ival].is_str = 0; }
                                                                                 ^
1 error generated.
make: *** [filter.o] Error 1

I can't seem to find this error anywhere online. What is the issue here?

**Comment by pd3** [comment]
Ah, sorry, it waits for this pull request https://github.com/samtools/htslib/pull/516

**Comment by mcshane** [comment]
samtools/htslib#516 was merged
