### ISSUE TITLE
strange behavor of bcftools query 

### ISSUE THREAD

**Issue by yyshi1** [samtools/bcftools#596]
Hello, 

We used 1000G phase III as a reference panel for imputation. When I queried the output of imputed data and observed following:
1. input 3:5968276, returned one record
 bcftools query -r 3:5968276 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz
3:5968276

2. input: 3:5968282, returned three records
 bcftools query -r 3:5968282 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz
3:5968276
3:5968280
3:5968282

3. input: 3:5968280, returned two records
bcftools query -r 3:5968280 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz
3:5968276
3:5968280

I found rsID in 1000G Browser and looked rs information at dbSNP. I summarized the finding below:
Chr:position(vcf format)	1000G browser	dbSNP	Pos_start	Pos_end	Variants returned
3:5968276	rs67521917	NC_000003.11:g.5968277_5968282delTCTCTA	5968277	5968282	1
3:5968282	rs12691247	NC_000003.11:g.5968282A>C	5968282	5968282	5968282 3
3:5968280	rs150876520 	NC_000003.11:g.5968281_5968282delTA	5968281	5968282	2

Could you explain how bcftools query work with these three examples? Is this expected behavior of bcftools query?

Yunling

**Comment by pd3** [comment]
If you add also `%REF %ALT\n` to your query, it should become clear - the `-r` option returns all records that overlap the `-r` region. If you want to restrict to exact match use the `-i` option. For example, for the second case add `-i 'POS=5968282'`.

**Comment by yyshi1** [comment]
I thought about "-r" as query on a range based.  But why query -r 3:5968276 only returned 1 record and query with -r  3:5968282 or -r 3:5968280 returned more than one records. I can see that they all end with 5968282 if I represent as ranges[start, end].

I tried -i option.
bcftools query -i POS=5968280 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz
It returned one 3:5968280 and did not finish after over a hour. I thought I should use index file.
chr3.1.02.dose.vcf.gz was indexed with tabix and chr3.1.02.dose.vcf.gz.tbi file was generated.

I query .tbi file with bcftools as following and got error.
bcftools query -i POS=5968280 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz.tbi
[E::hts_hopen] fail to open file 'chr3.1.02.dose.vcf.gz.tbi'
[E::hts_open_format] fail to open file 'chr3.1.02.dose.vcf.gz.tbi'
Failed to open chr3.1.02.dose.vcf.gz.tbi: Success

**Comment by pd3** [comment]
I said "add", not replace. The commands should look like this:

     # check why are the other records printed: most likely a deletion or SV that spans the position?
     bcftools query -r 3:5968280 -f "%CHROM:%POS   %REF %ALT\n" chr3.1.02.dose.vcf.gz

     # you don't want to leave out the -r option, otherwise the program will stream through the whole vcf
     bcftools query -r 3:5968280 -i POS=5968280 -f "%CHROM:%POS\n" chr3.1.02.dose.vcf.gz

**Comment by pd3** [comment]
I believe this has been resolved, closing now
