### ISSUE TITLE
Can't plot using plot-vcfstats

### ISSUE THREAD

**Issue by knahavandi1** [samtools/bcftools#597]
I keep getting an error when attempting to plot using plot-vcfstats:

![image](https://cloud.githubusercontent.com/assets/22385407/25360545/97c7ac98-2917-11e7-8c16-aa0f574a92be.png)

**Comment by pd3** [comment]
Is this the same error? https://github.com/samtools/bcftools/issues/593
If yes, updating bcftools and re-running stats should help

**Comment by knahavandi1** [comment]
Yes, it is the same error. I installed bcftools yesterday. Would updating still solve the issue? Also, do I need to uninstall and reinstall in order to update?
Thank you!

**Comment by pd3** [comment]
My statement above was not correct, you only need to use the new `plot-vcfstats` script.
You'll need the latest github version which you can obtain as described here http://samtools.github.io/bcftools/

**Comment by aderzelle** [comment]
Hello,

I have the same problem, I have attempted to install the latest github version but I can't compile
`Makefile:34: ../htslib/htslib_static.mk: No such file or directory
make: *** No rule to make target '../htslib/htslib_static.mk'.  Stop.`

Any idea? Thanks a lot

**Comment by pd3** [comment]
Hi, did you update also htslib, as described here http://samtools.github.io/bcftools/?

**Comment by aderzelle** [comment]
Indeed I hadn't and now it compiles well. 
However, there is another issue, I am opening a new issue as it seems different form the original one.

**Comment by pd3** [comment]
OK, closing this issue then
