### ISSUE TITLE
Can't run bcftools stats: Incorrect allele ("1") at ...

### ISSUE THREAD

**Issue by MafaldaSFerreira** [samtools/bcftools#599]
Hello,

I've been running into an error lately when I try to run bcftools stats but that I believe is probably an error produced in bcftools call. 

I have a set of .bcf files generated with samtools mpileup. Original bams were mapped with BWA-mem, treated with AddOrReplaceReadGroups, MarkDuplicates and RealignerTargetCreator. 

This is my call for the files; I run them inside a lop

`samtools mpileup -Q 20 -q 20 -go %s_raw.bcf -f %s %s` 

where the second %s is a path to the reference and the third the name of the input bam.

Then I run bcftools call, again inside a loop:

`cat chromosome.list | xargs -I {} -n 1 -P 20 sh -c 'bcftools call -cO z -r {} --format-fields GQ -o %s/%s.{}.vcf.gz %s'`

where the call would look something like this:
`cat chromosome.list | xargs -I {} -n 1 -P 20 sh -c 'bcftools call -cO z -r {} --format-fields GQ -o LER_ALM_1580_raw/LER_ALM_1580_raw.{}.vcf.gz LER_ALM_1580_raw.bcf'`

then I concatenate all the chromosome files using bcftools concat. 

Finally, I try to run bcftools stats, like so (example from one sample): 

`bcftools stats -F /scratch/3/mafalda/SpeciesForReference/LER_ALM1580/LER_ALM1580.gatk.iteration4.consensus.FINAL.fa -s - LER_ALM_1580_raw.vcf.gz > LER_ALM_1580_raw_v2.vcf.gz.stats`

And get this error:
`[E::bcf_calc_ac] Incorrect allele ("1") in LER_ALM_1580 at 1:461`

If I look this position up:
`bcftools view -r 1:461 LER_ALM_1580_raw.vcf.gz`

This is what I get:
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956	GT:PL:GQ	0/1:29:5

I've tried to exclude chromosome 1 from the concatenated file, but I get errors in other chromosomes. Basically, an heterozygous appears in GT but according to REF and ALT, we should have an homozygous, right? 

I've repeated the analysis for only one sample and only for chromosome 1, either using or not --format-fields GQ in the bcftools call command. If I don't use that flag, the output vcf, in that specific region will be:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956 GT:PL	0/0:29

but if I do ask to add a GQ field, I have again:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956 GT:PL:GQ	0/1:29:5

What puzzles me is that I've run this analysis before with adding "GQ" field in bcftools call and I didn't have any problems with the vcf output.

Any ideas what could be causing this or how I should proceed? 

Thank you

**Comment by MafaldaSFerreira** [comment]
I've repeated the analysis for only one sample and only for chromosome 1, either using or not --format-fields GQ in the bcftools call command.  If I don't use that flag, the output vcf, in that specific region will be: 

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956	GT:PL	0/0:29

but if I do ask to add a GQ field, I have again:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956	GT:PL:GQ	0/1:29:5

**Comment by pd3** [comment]
The output from `bcftools view` you show does not look like the raw mpileup output. Are you sure you are not feeding `bcftools call` a file that was already processed? You can tell by the presence of the INFO/QS tag. I am assuming you are running some recent version.

**Comment by MafaldaSFerreira** [comment]
The file I'm feeding bcftools call is the output of samtools mpileup command I wrote in my initial comment. The output of my samtools command is a .bcf file. Samtools should apply -Q 20 and -q 20, as specified to my initial bams. 

As for output, I've asked samtools to output a bcf since that is an option. I believe it should not conflict with bcftools since it accepts bcf files as input.

Also, the LER_ALM_1580_raw.vcf.gz I was used as input for bcftools view is the output file of bcftools call and not mpileup. And I note that this same pipeline works just fine if I don't use the --format-fields flag in bcftools call.

The versions I'm running are:
samtools v.1.3.1
bcftools: 1.2-185-g8e8679d 

Thank you for your response.

**Comment by pd3** [comment]
You should use the same release of samtools/bcftools. To prevent these mismatches, we recently transferred the mpileup command from samtools to bcftools. Could you please try with this latest version? http://samtools.github.io/bcftools/

If it still does not work, could you show the raw `mpileup` line, before it's processed with `call`?

**Comment by MafaldaSFerreira** [comment]
I will ask the person in charge to update the versions in the server to release 1.4. However, I've repeated now with the same version of samtools and bcftools (1.3.1, in this case)(I've realized bcftools 1.3.1 was also in the server). Just to confirm the versions, this is in the header of outputs from samtools mpileup and bcftools call, respectively:
##samtoolsVersion=1.3.1+htslib-1.3.1
##bcftools_callVersion=1.3.1+htslib-1.3.1

And the same thing occurs. 

This is the same line in the samtools mpileup command, before inputing to call:

`bcftools view -r 1:461 LER_ALM_1580_raw.bcf`

CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	T,<*>	0	.	DP=1;I16=0,0,0,1,0,0,29,841,0,0,60,3600,0,0,4,16;QS=0,1,0;SGB=-0.379885;MQ0F=0	PL	29,3,0,29,3,29

But, as I said, I will follow your advice and ask for an update of the versions and see how it goes.
Thank you.

**Comment by MafaldaSFerreira** [comment]
We have updated the versions.
samtools:
Version: 1.4 (using htslib 1.4)
bcftools:
Version: 1.4 (using htslib 1.4)

I decided to only to chromosome 1 to make this faster. I'm going to copy paste what I did:

`bcftools mpileup -Q 20 -q 20 -r 1 -O u -o LER_ALM_1580_raw_v14.bam -f /scratch/3/mafalda/SpeciesForReference/LER_ALM1580/LER_ALM1580.gatk.iteration4.consensus.FINAL.fa LER_ALM_1580.realigned.bam`

`bcftools call -cO z --format-fields GQ -o LER_ALM_1580_raw_v14.vcf.gz LER_ALM_1580_raw_v14.bcf`

`bcftools index LER_ALM_1580_raw_v14.vcf.gz`

 Viewing that position again:
This is the output of bcftools call:
`bcftools view -r 1:461 LER_ALM_1580_raw_v14.vcf.gz`

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956	GT:PL:GQ	0/1:29:5

This is the output of bcftools mpileup:
`bcftools view -r 1:461 LER_ALM_1580_raw_v14.bcf`

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	T,<*>	0	.	DP=1;I16=0,0,0,1,0,0,29,841,0,0,60,3600,0,0,4,16;QS=0,1,0;SGB=-0.379885;MQ0F=0	PL	29,3,0,29,3,29

If, on the other hand I don't use --format-fields GQ, I get this:
`bcftools call -cO z -o LER_ALM_1580_raw_v14_noQG.vcf.gz LER_ALM_1580_raw_v14.bcf`

`bcftools view -r 1:461 LER_ALM_1580_raw_v14_noQG.vcf.gz`
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LER_ALM_1580
1	461	.	C	.	3.53256	.	DP=1;SGB=-0.379885;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,1;MQ=60;FQ=-29.9956	GT:PL	0/0:29

So, the same thing is happening. What do you think?
Thank you in advance!

**Comment by pd3** [comment]
This is now fixed by https://github.com/samtools/bcftools/commit/108b069db02aa1216cc9a2efb7dc7fe015717b70, thank you for reporting the bug

**Comment by MafaldaSFerreira** [comment]
Thank you! Now everything works well! 👍

**Comment by lt11** [comment]
Hi, I had the same problem with bcftools merge:
[E::bcf_calc_ac] Incorrect allele ("1") in SK1-hc at chrI:13

I was using:
bcftools 1.15.1
Using htslib 1.15.1

My vcf file contains only indels. No problem if I use a vcf with only SNPs.

Here's a couple of lines from the file:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SK1-hc
chrI	13	.	CA	.	60	.	.	GT:FRMR:FRMQ:CHRQ:STARTQ:ENDQ	1:1:1:chrI:4168:4168

May this problem be related to the missing ALT allele (".")? Any other suggestion? 

Thanks in advance!

**Comment by lt11** [comment]
A couple of tests on my side seem to confirm my hypothesis.

**Comment by pd3** [comment]
That's right. The program expects a valid VCF on output. There is no alternate allele in this record, therefore the genotypes must not be anything else than `0` or `.`.
