### ISSUE TITLE
bcftools call | norm "incorrect allele index 1"

### ISSUE THREAD

**Issue by maleasy** [samtools/bcftools#602]
Hello,

I am having trouble with `bcftools call` when using the consensus caller (error occurs with 1.3.1 and 1.4).

My command is:
```
bcftools mpileup -f reference.fa -a DP sample1.bam sample2.bam sample3.bam sample4.bam | bcftools call -c -f GQ  | bcftools norm -f reference.fa -m +b
oth -o norm.vcf
```

Error message by bcftols norm:

    Error at ref_15:193: incorrect allele index 1

When creating the VCF by `bcftools call`:
```
bcftools mpileup -f reference.fa -a DP sample1.bam sample2.bam sample3.bam sample4.bam | bcftools call -c -f GQ -o call.vcf
```

The region that is referenced in the error message looks like this in `call.vcf`:

    ref_15  193     .       A       .       70.4254 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,57,0,0;MQ=35;FQ=-69.846  GT:PL:DP:GQ     0/0:0:14:99     0/0:0:15:99     0/0:0:12:99     0/0:0:16:99
    ref_15  193     .       ATT     .       5.62879 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.1476e-05;SGB=0.0467143;MQ0F=0.0175439;AF1=0.580358;AC1=5;DP4=0,5,0,4;MQ=41;FQ=-3.26874;PV4=1,0.000553408,1,1       GT:PL:DP:GQ     0/0:0:0:6       0/1:13:1:5      0/0:0:5:20      0/1:33:3:4
    ref_15  194     .       T       .       49.05   .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,36,0,0;MQ=39;FQ=-48.4681 GT:PL:DP:GQ     0/0:0:6:73      0/0:0:9:82      0/0:0:5:70      0/0:0:16:99
    ref_15  194     .       T       TCA     84.1435 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.10571e-10;SGB=-3.4056;MQ0F=0.0175439;AF1=0.826403;AC1=7;DP4=0,5,0,13;MQ=34;FQ=36.7077;PV4=1,0.00106452,0.0423993,1 GT:PL:DP:GQ     1/1:66,15,0:5:18        1/1:51,12,0:4:15        0/1:16,0,78:8:25        1/1:25,25,25:1:4
    ref_15  195     .       T       .       49.0486 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,35,0,0;MQ=39;FQ=-48.4667 GT:PL:DP:GQ     0/0:0:6:73      0/0:0:9:82      0/0:0:5:70      0/0:0:15:99
    ref_15  195     .       TC      TCC     999     .       INDEL;IDV=15;IMF=0.9375;DP=57;VDB=1.8628e-18;SGB=7.12752;MQ0F=0.0175439;AF1=0.769293;G3=0.25,1.88856e-07,0.75;HWE=0.0430754;AC1=6;DP4=0,5,0,30;MQ=39;FQ=35.7281;PV4=1,1,0.200564,1      GT:PL:DP:GQ     1/1:112,15,0:5:17       1/1:156,27,0:9:29       0/0:0,15,88:5:8 1/1:199,48,0:16:50
    ref_15  196     .       C       .       31.8474 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,7,0,0;MQ=39;FQ=-31.0526  GT:PL:DP:GQ     0/0:0:1:40      0/0:0:0:37      0/0:0:5:52      0/0:0:1:40
    ref_15  196     .       C       CATA    999     .       INDEL;IDV=1;IMF=0.0714286;DP=57;VDB=8.64257e-25;SGB=0.541338;MQ0F=0.0175439;AF1=0.460855;AC1=4;DP4=0,20,0,21;MQ=35;FQ=150.908;PV4=1,1,4.26018e-07,1     GT:PL:DP:GQ     1/1:110,7,0:11:5        0/1:92,0,24:9:28        0/1:78,0,117:12:80      0/0:0,27,61:9:25

-> The problem is the second line shown for position 193, where the reference is "ATT" and the alternate is ".", but there are 0/1 genotypes. 
It seems to me that the alternate should be "A"

The same `incorrect allele index 1` error also occurs if I try to merge `call.vcf` with another VCF on the same reference using `bcftools merge`.

Any help appreciated.

**Comment by pd3** [comment]
Hi, this looks like exactly this problem https://github.com/samtools/bcftools/issues/599, can you please check?

**Comment by maleasy** [comment]
Hi,

i agree, it looks like the same issue.

best,
chris

**Comment by maleasy** [comment]
I downloaded the fix for #599 (commit `108b069db02aa1216cc9a2efb7dc7fe015717b70`).
The `bcftools norm` error `incorrect allele index 1` is indeed gone.

Looking at `call.vcf` created as outlined above with the fixed `bcftools` binary, the lines are now:

    ref_15  193     .       A       .       70.4254 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,57,0,0;MQ=35;FQ=-69.846  GT:PL:DP:GQ     0/0:0:14:99     0/0:0:15:99     0/0:0:12:99     0/0:0:16:99
    ref_15  193     .       ATT     .       5.62879 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.1476e-05;SGB=0.0467143;MQ0F=0.0175439;AF1=0.580358;AC1=5;DP4=0,5,0,4;MQ=41;FQ=-3.26874;PV4=1,0.000553408,1,1       GT:PL:DP:GQ     0/0:0:0:6       0/0:13:1:1      0/0:0:5:20      0/0:33:3:0
    ref_15  194     .       T       .       49.05   .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,36,0,0;MQ=39;FQ=-48.4681 GT:PL:DP:GQ     0/0:0:6:73      0/0:0:9:82      0/0:0:5:70      0/0:0:16:99
    ref_15  194     .       T       TCA     84.1435 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.10571e-10;SGB=-3.4056;MQ0F=0.0175439;AF1=0.826403;AC1=7;DP4=0,5,0,13;MQ=34;FQ=36.7077;PV4=1,0.00106452,0.0423993,1 GT:PL:DP:GQ     1/1:66,15,0:5:18        1/1:51,12,0:4:15        0/1:16,0,78:8:25        1/1:25,25,25:1:4
    ref_15  195     .       T       .       49.0486 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,35,0,0;MQ=39;FQ=-48.4667 GT:PL:DP:GQ     0/0:0:6:73      0/0:0:9:82      0/0:0:5:70      0/0:0:15:99
    ref_15  195     .       TC      TCC     999     .       INDEL;IDV=15;IMF=0.9375;DP=57;VDB=1.8628e-18;SGB=7.12752;MQ0F=0.0175439;AF1=0.769293;G3=0.25,1.88856e-07,0.75;HWE=0.0430754;AC1=6;DP4=0,5,0,30;MQ=39;FQ=35.7281;PV4=1,1,0.200564,1      GT:PL:DP:GQ     1/1:112,15,0:5:17       1/1:156,27,0:9:29       0/0:0,15,88:5:8 1/1:199,48,0:16:50
    ref_15  196     .       C       .       31.8474 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,7,0,0;MQ=39;FQ=-31.0526  GT:PL:DP:GQ     0/0:0:1:40      0/0:0:0:37      0/0:0:5:52      0/0:0:1:40
    ref_15  196     .       C       CATA    999     .       INDEL;IDV=1;IMF=0.0714286;DP=57;VDB=8.64257e-25;SGB=0.541338;MQ0F=0.0175439;AF1=0.460855;AC1=4;DP4=0,20,0,21;MQ=35;FQ=150.908;PV4=1,1,4.26018e-07,1     GT:PL:DP:GQ     1/1:110,7,0:11:5        0/1:92,0,24:9:28        0/1:78,0,117:12:80      0/0:0,27,61:9:25

i.e. the wrong `0/1` genotypes at position 193 are gone.
However, when looking at `norm.vcf` the respective entries are:

    ref_15  193     .       ATT     .       70.4254 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,57,0,0;MQ=35;FQ=-69.846  GT:PL:DP:GQ     0/0:0:14:99     0/0:13:15:99    0/0:0:12:99     0/0:33:16:99
    ref_15  194     .       T       TCA     84.1435 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.10571e-10;SGB=-3.4056;MQ0F=0.0175439;AF1=0.826403;AC1=7;DP4=0,5,0,13;MQ=34;FQ=36.7077;PV4=1,0.00106452,0.0423993,1 GT:PL:DP:GQ     1/1:0,15,0:5:18 1/1:0,12,0:4:15 0/1:0,0,78:8:25 1/1:0,25,25:1:4
    ref_15  195     .       T       TC      999     .       INDEL;IDV=15;IMF=0.9375;DP=57;VDB=1.8628e-18;SGB=7.12752;MQ0F=0.0175439;AF1=0.769293;G3=0.25,1.88856e-07,0.75;HWE=0.0430754;AC1=6;DP4=0,5,0,30;MQ=39;FQ=35.7281;PV4=1,1,0.200564,1      GT:PL:DP:GQ     1/1:0,15,0:5:17 1/1:0,27,0:9:29 0/0:0,15,88:5:8 1/1:0,48,0:16:50
    ref_15  196     .       C       CATA    999     .       INDEL;IDV=1;IMF=0.0714286;DP=57;VDB=8.64257e-25;SGB=0.541338;MQ0F=0.0175439;AF1=0.460855;AC1=4;DP4=0,20,0,21;MQ=35;FQ=150.908;PV4=1,1,4.26018e-07,1     GT:PL:DP:GQ     1/1:0,7,0:11:5  0/1:0,0,24:9:28 0/1:0,0,117:12:80       0/0:0,27,61:9:25

I wonder if they should instead be

    ref_15  193     .       A       .       70.4254 .       DP=57;MQ0F=0.0175439;AF1=0;AC1=0;DP4=0,57,0,0;MQ=35;FQ=-69.846  GT:PL:DP:GQ     0/0:0:14:99     0/0:13:15:99    0/0:0:12:99     0/0:33:16:99
    ref_15  194     .       T       TCA     84.1435 .       INDEL;IDV=8;IMF=0.571429;DP=57;VDB=1.10571e-10;SGB=-3.4056;MQ0F=0.0175439;AF1=0.826403;AC1=7;DP4=0,5,0,13;MQ=34;FQ=36.7077;PV4=1,0.00106452,0.0423993,1 GT:PL:DP:GQ     1/1:0,15,0:5:18 1/1:0,12,0:4:15 0/1:0,0,78:8:25 1/1:0,25,25:1:4
    ref_15  195     .       T       TC      999     .       INDEL;IDV=15;IMF=0.9375;DP=57;VDB=1.8628e-18;SGB=7.12752;MQ0F=0.0175439;AF1=0.769293;G3=0.25,1.88856e-07,0.75;HWE=0.0430754;AC1=6;DP4=0,5,0,30;MQ=39;FQ=35.7281;PV4=1,1,0.200564,1      GT:PL:DP:GQ     1/1:0,15,0:5:17 1/1:0,27,0:9:29 0/0:0,15,88:5:8 1/1:0,48,0:16:50
    ref_15  196     .       C       CATA    999     .       INDEL;IDV=1;IMF=0.0714286;DP=57;VDB=8.64257e-25;SGB=0.541338;MQ0F=0.0175439;AF1=0.460855;AC1=4;DP4=0,20,0,21;MQ=35;FQ=150.908;PV4=1,1,4.26018e-07,1     GT:PL:DP:GQ     1/1:0,7,0:11:5  0/1:0,0,24:9:28 0/1:0,0,117:12:80       0/0:0,27,61:9:25

Is the `ATT` reference allele correct at position 193? Shouldn't it be `A` after `bcftools norm` if there is no alternate allele?

**Comment by pd3** [comment]
Perhaps. It is such an odd case that there is no clear right and wrong, it depends on the intended use I guess.

**Comment by pd3** [comment]
We discussed this internally and decided that the program should trim the reference allele.

**Comment by pd3** [comment]
This is now fixed. Thanks for reporting the bug.

**Comment by maleasy** [comment]
Thank you for fixing it!
