### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by aersoares81** [samtools/bcftools#610]
Hi, I have this error during make:

`gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
thread_pool.c: In function 'hts_tpool_init':
thread_pool.c:676:5: warning: implicit declaration of function 'pthread_mutexattr_settype' [-Wimplicit-function-declaration]
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
     ^~~~~~~~~~~~~~~~~~~~~~~~~
thread_pool.c:676:38: error: 'PTHREAD_MUTEX_RECURSIVE' undeclared (first use in this function)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
                                      ^~~~~~~~~~~~~~~~~~~~~~~
thread_pool.c:676:38: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [thread_pool.o] Error 1
make[1]: Leaving directory `/home/name/bcftools-1.4.1/htslib-1.4.1'
make: *** [htslib-1.4.1/libhts.a] Error 2`

I have samtools, etc, on the system, compiled without a problem. Any suggestions?

**Comment by aersoares81** [comment]
Btw, 1.31 compiles fine.

**Comment by jkbonfield** [comment]
Are you using RHEL 5 by any chance?

If so you can try enabling POSIX mode (add -D_POSIX_C_SOURCE=600 to CFLAGS).  We need to get this into the configure script it looks.

**Comment by aersoares81** [comment]
This is what I'm using:

```
> uname -r
3.0.101-0.47.52-default
> lsb_release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a
````

**Comment by aersoares81** [comment]
I tried adding "-D_POSIX_C_SOURCE=600", but then I got a lot of errors. I think it's a bit long, so I made a gist with the errors it output: [https://gist.github.com/aersoares81/e7cdf0e11164c11ed33ae791031260d2](url)

**Comment by jkbonfield** [comment]
The good news is it looked like it fixed the original thread_pool.c issue.

Therefore the solution is probably to revert this change:

**Comment by jkbonfield** [comment]
Sorry I was forgetting my standards.  I meant "-D_XOPEN_SOURCE=600", as listed (but commented out) in the htslib Makefile.

If you could do a full make clean in both htslib and bcftools and retest using that flag then it would help a lot.  I'll look at adding this to the configure script, which is the correct way to address this.  XOPEN will allow it to support both POSIX definitions (the pthreads issue) as well as the XSI extensions (drand48, M_PI, etc).
