### ISSUE TITLE
doubt regarding -q 60

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#612]
Hi,

When I use -q 60 for using reads having minimum mapping quality of 60, in one of the variants the INFO/DP field has 19 reads and the FORMAT/DP has 12 reads (AD:7,5,0). 

My BAM file has reads with mapping quality of 0,1 and 60. Do the 19 reads present in the  INFO/DP counted irrespective of their mapping quality just to denote the general coverage in that variant postion? Whereas from those 19 reads, only 12 reads (present in FORMAT/DP) have mapping quality as 60 and have been used for variant call?

**Comment by pd3** [comment]
That's correct. It should become clear if you check the tag description in the header:

    ##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
    ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">

**Comment by prasundutta87** [comment]
Thanks a lot.
