### ISSUE TITLE
genotype assignment query

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#613]
Hi,

I have used samtools 1.4 mpileup with bcftools 1.2 to call variants. I have a doubt regarding assignment of genotype i.e. 0/1 (heterozygous) or 1/1 (homozygous) to the called variants. My question arose in order to understand if there is a threshold ratio between ref allele read counts and alt allele read counts based on which genotype is determined at a particular variant position.

I am aware that zygosity assignment depends on various factors, but eye balling the AD can give you an idea of the probable zygosity as well.

I have come across cases such as below where I am unable to understand clear reason behind assignment of 1/1 as MOSTLY the ref read % : alt read % is 0:100.

**CHROM	                POS	        GENE	                GT	ref	alt	total	  %alt        %ref         GQ**

NW_005782421.1	832996	LOC102390560	1/1	29	174	 203	  85.72	14.28	25
NW_005784541.1	107568	LOC102405926	1/1	200	1225 1425 85.96	14.04	111
NW_005784523.1	64377	LOC102404177	1/1	489	3372 3861  87.33	12.67	47
NW_005784956.1	608624	CTSB	                        1/1	3	24	  27	   88.89	11.11	22

Since in the downstream analysis, I am dealing with allele specific expression analysis, I will filter out all homozygous variants and due to this, I will filter out some of the example variants shown above which seem heterozygous but assigned 1/1. Can anyone explain me the above genotype assignment process?

**Comment by pd3** [comment]
This is not easy to answer, it is more complex than just counting the number of reference and non-reference reads. First of all, it depends on the options that were used, base and mapping qualities. Next, the caller is a population based caller - it takes into account the evidence not only from one sample, but also from other samples assuming HWE. See the math notes on the `call -c` and `call -m` models here  http://samtools.github.io/bcftools.

**Comment by prasundutta87** [comment]
Thanks for sharing this. The thing is I had only one sample and used -q 60 in the mpileup command (used default base quality threshold of 13). Its possible that some of the reads that is being considered for genotype assignment have lower base quality on the particular called variant's position and probably due to that some reads are not used for genotype assignment. Although, I guess we cannot be sure of that as well.

**Comment by pd3** [comment]
Most likely `-q 60` and the default `-Q 13` removed many of the non-reference reads. The FORMAT/AD and INFO/AD annotations should give the depth after filtering.

**Comment by prasundutta87** [comment]
Thanks for your reply. I gave -q 60 because that's what my aligner HISAT2 gives to uniquely mapped reads (because that is what I want) and I hope the mpileup file that is being constructed in-between considering only those uniquely mapped reads. I hope the '-q' options refers to the mapping scores present in my input BAM file and not the mapping scores that samtools provides in the mpileup file. If yes, what is the range of that mapping quality score?
