### ISSUE TITLE
Problem with merging gVCFs with "bcftools merge -g -"

### ISSUE THREAD

**Issue by maleasy** [samtools/bcftools#616]
I am having trouble merging to VCFs correctly with bcftools 1.4.1.

The command is like
```
bcftools merge -o merged.vcf.gz -O z -g - round1.vcf.gz round2.vcf.gz
```
`bcftools merge` does not report any errors, but when creating an index I get an error:
```
bcftools index -f merged.vcf.gz 
[E::hts_idx_push] unsorted positions on sequence #58: 240 followed by 1
index: failed to create index for "merged.vcf.gz"
```
When looking at `merged.vcf`, the VCF lines for the last reference/contig `400_ref` are duplicated.

I attached an archive with the files.

The VCFs were created from BAMs with  `bcftools mpileup ... | bcftools call -g 1 -m ... | bcftools norm`

The input data (reads and reference sequences) are simulated, part of a test set for an automated pipeline. I realize that it does look different from real data in some respects, but nevertheless I think my problem could point to a bug in the `bcftools merge` code.

[bcftools_merge_issue.tar.gz](https://github.com/samtools/bcftools/files/1019345/bcftools_merge_issue.tar.gz)

**Comment by pd3** [comment]
Thank you for reporting the bug and the test. This commit fixes the problem https://github.com/samtools/bcftools/commit/7b2c7f28ba2476d8f418bdb5a399654aae18d7c0
