### ISSUE TITLE
bcftools view filter DP on vardict call

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [samtools/bcftools#617]
Dear All,
I would like filter a vcf with  DP value above 20 X 
` bcftools view -f PASS -i 'DP>=10 ' 332.vardict.somatic.vcf > tmp.vcf`

Unfortunately it is empity the file (only header)
```

$ bcftools  version
bcftools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pd3** [comment]
In order for this to print anything else than header, the source file must be records with FILTER=PASS and INFO/DP annotation bigger than 10. Are you sure there are such records? If yes and you think it is a bug, a small test case to reproduce the problem would be helpful.
