### ISSUE TITLE
gtcheck output description

### ISSUE THREAD

**Issue by VidJa** [samtools/bcftools#622]
Hi I'm looking at genotype discordance between samples in a certain region in my VCF. The documentation explains how the discordance is calculated in the CN line.
However, in the output there is a line:

Warning: The CN block is deprecated and will be removed in future releases. Use ERR instead.

How is this ERR value calculated and how should i compare the two values

bcftools gtcheck  -r 'CHR02:1000000-1010000' calls.vcf.gz
Example output:
ERR     0.012448        482     SAMPLE_02     SAMPLE_01
....
CN      6       482     0       SAMPLE_02     SAMPLE_01

**Comment by VidJa** [comment]
never mind, its 6/482 of course

**Comment by pd3** [comment]
Looks like the question was resolved, great! Closing now
