### ISSUE TITLE
stats not working on file streams

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#630]
Would it be possible to have `bcftools stats` work on file streams? The `bcftools stats` command below produces this error:
```Failed to open /dev/fd/63: not compressed with bgzip```

Here the command:
```
$bcftools stats \
 --verbose \
 <(\
  $bcftools convert \
   --gensample2vcf \
   <(\
    zcat $(ls $path1/*.gz | sort -V) \
    | awk -v chrom=$chrom '{
     printf $1; printf " "chrom":"$3"_"$4"_"$5; for(i=3; i<=NF; i++) {
      printf " "$i}; printf "\n"}'),$path2) \
 <($bcftools concat $path3/*.vcf.gz)
```

Thanks!

**Comment by pd3** [comment]
The command `bcftools stats` does work on streams, try `cat file.vcf | bcftools stats`.
Here you are doing something different, trying to feed multiple unindexed files to the program. However, the program can only compare two files if they are indexed, it's the same as with the other commands - `isec`, `merge`, etc.

**Comment by tommycarstensen** [comment]
Thanks @pd3 ! I dug out an old slow and poorly written Python script of mine for this task instead: https://github.com/team149/tc9/blob/master/comparison/correlation.py
