### ISSUE TITLE
-s and -S does not work with query

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#632]
When running this command:

```bcftools query -l -s NA12878 /lustre/scratch114/resources/1000g/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf.gz```

I expect `NA12878` as the output, but instead all samples in the VCF file are printed.

**Comment by pd3** [comment]
That's true, the `-l` option ignores the `-s` option. What is the potential use of combining the two? 
Probably not as convenient, but standard unix commands can be used to check if a sample is present:

    bcftools query -l file.vcf | grep NA12878
    bcftools query -l file.vcf | grep -wf samples.txt

**Comment by tommycarstensen** [comment]
It's just an easy way of doing sample set intersections with `-S` while easily retaining the original sample order. The samples are almost always in alphabetical order anyway, so it can be achieved with `comm` or `join`. I just spent hours looking for a bug in my shell script, because I wasn't expecting this behaviour. I don't think `-l` should cancel out `-S`. Anyway, I leave the decision to you. Thanks either way.
