### ISSUE TITLE
query: print the entire INFO field? 

### ISSUE THREAD

**Issue by dmckean** [samtools/bcftools#637]
Is it possible to include all of the tags in the INFO field in a `bcftools query` format expression?

Something like `bcftools query -f "%CHROM\t%POS\t%INFO\n" foo.bcf`

Rather than `bcftools query -f "%CHROM\t%POS\tTAG1=%INFO/TAG1;TAG2=%INFO/TAG2..." foo.bcf`

**Comment by pd3** [comment]
Maybe we could add it. It did not seem necessary because the same result can be achieved with standard unix commands:

     bcftools view -H foo.bcf | cut -f1,2,8

**Comment by coffee-and-genomics** [comment]
I'm also getting this error: `Could not parse format string: %CHROM\t%POS\t%REF\t%ALT\t%INFO\n`
Using the command:

```
for i in "$TMP_DIR"/*.vcf.gz
do
    I_BASENAME=$(basename "$i" '.gz')
    bcftools query \
    --print-header \
    --include 'TYPE="snp"' \
    -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO\n' \
    "$i" > "${TMP_DIR}/${I_BASENAME}.snv.tsv"
done
```

If this is not an option then it should be removed from the documentation, which says it is indeed supported functionality. From the [samtools/bcftools documentation for the query function](http://samtools.github.io/bcftools/bcftools.html#query):

> Format: 
> [...]
> `%INFO           Prints the whole INFO column`
> [...]

Or, much more preferably, the functionality could be implemented as stated 🙂

**Comment by pd3** [comment]
The option works for me alright, you should consider upgrading to a newer version of bcftools.
http://samtools.github.io/bcftools/howtos/install.html
