### ISSUE TITLE
Feature request: ALL keyword for filtering expressions

### ISSUE THREAD

**Issue by wkretzsch** [samtools/bcftools#639]
Currently I can check if the FORMAT/DP value is greater than 10 for any allele of a sample using the expression
```
bcftools filter -i 'FORMAT/DP[*] > 10'
```

It would be useful to have a way of asserting that all alleles satisfy a requirement.  My reading of the docs is that this is not possible at the moment.

[Here](https://bioinformatics.stackexchange.com/a/987/492) is an SO answer that explains the problem further.

**Comment by pd3** [comment]
The filtering expressions have been now extended to include:
````
    TAG[1,2]   .. list
    TAG[1,2-5] .. ranges
    TAG[0-]    .. open intervals
    TAG[*]     .. any field
````
The any field keyword (`[*]`) was already supported before but did not work for FORMAT annotations. This should work now.

**Comment by wkretzsch** [comment]
This is amazing!  Thanks a bunch!
