### ISSUE TITLE
/mnt/sda1/var/lib/docker/tmp/GetImageBlob109056922: no such file or directory? (DOCKER)

### ISSUE THREAD

**Issue by BralK** [samtools/bcftools#640]
Sorry didn't know where else to post this very new to Docker. Please redirect me if I'm in the wrong place. 

So I was installing the Development Tools group in CentOS and midway installing it gives me this message: Error occurred during writing of a log message: Read-only file system

I've installed the same package before and have gotten this message once before. I had to go to my Mac virtual machine display and end the one I was working on and re-install Docker. It fixed it for a while, but obviously I can't keep doing that because I have work that I need to do and I don't want to lose all the progress I haven't quite built an image upon yet which is what I'm trying to do. I exited CentOS and tried to re-run it with docker run -it centos, but it gave me this: 
/mnt/sda1/var/lib/docker/tmp/GetImageBlob109056922: no such file or directory

What is this? docker version returns this: 
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

Again, sorry I'm very, very, very new to Docker so I don't have any idea what's going on or what to do. I don't want to consider rebooting my virtual machine unless nothing else works.

Thanks so much and please let me know if you need any more info.

**Comment by pd3** [comment]
Hi, bcftools has nothing to do with Docker, sorry. Closing the issue.
