### ISSUE TITLE
How to format text file with bcftools annotate -R?

### ISSUE THREAD

**Issue by BralK** [samtools/bcftools#644]
Hey, I'm back again sorry.

So I'm using bcftools to annotate a file and my first step is to change all the chromosome labels from chr3 to 3 and chr4 to 4 and so on. But when I tried to make a file following the instructions it says it can't parse it. The instructions I've read for this file are: "old_name new_name\n" pairs separated by whitespaces, each on a separate line.

So here is what my text file looks like: 

"chr3 3\n"

"chr4 4\n"

"chr5 5\n"

"chr6 6\n"

"chr7 7\n"

"chr8 8\n" 

And it still can't read it. Obviously I'm misunderstanding the syntax. Could someone please help me? 

Thanks so much and please let me know if you need any more information.

**Comment by pd3** [comment]
I am assuming you want to use `bcftools annotate --rename-chrs` rather than `-R, --regions-file`? Also the `\n` symbol is commonly used to represent the newline character. So your file should look like this:

````
chr3 3
chr4 4
````

**Comment by BralK** [comment]
Yes, sorry I must have misread the manual I mean to use --rename-chrs. But now it says that my .vcf file is an unknown file type? I literally opened the entire file a few lines above with `bcftools view -h sample.vcf` and now it says it can't read it because it's a vcf, thats odd. Just to make sure, the syntax should be like this: `bcftools annotate --rename-chrs chrchange.txt sample.vcf ` right? Should I try it with a different file?

Thanks.

**Comment by BralK** [comment]
Never mind, it's all good now, thanks.
