### ISSUE TITLE
bcftools merge: error "[E::bcf_calc_ac] Incorrect allele ("1")"

### ISSUE THREAD

**Issue by slzarate** [samtools/bcftools#648]
Hello,

I am running bcftools merge using bcftools version 1.5. Here is my output:

`bcftools 1.5`
`...`
`[W::bcf_hdr_check_sanity] PL should be declared as Number=G`
`[W::bcf_hdr_check_sanity] PL should be declared as Number=G`
`[E::bcf_calc_ac] Incorrect allele ("1") in ... at 1:10388`

I see that there was a similar issue reported prior to the 1.5 update (#599 and #602), but my version is 1.5 and it's still happening. Any thoughts?

**Comment by pd3** [comment]
The two issues are most likely unrelated to your problem. What is the history of the VCF? The warnings and the error message seems quite clear - the VCF has incorrect field, also the PL definition is not what it should be.

**Comment by slzarate** [comment]
Thanks, I ended up using bcftools concat instead.
