### ISSUE TITLE
unexpected behaviour of -S, which re-orders samples

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#649]
I was using `view -S` to extract a subset of samples from a VCF. However, whereas the sample order of the input was alphabetic, the sample order of the output was identical to that of the `-S` input file, which was shuffled randomly. This was very unexpected behaviour to me. Can it be fixed, so that the sample order is retained? Thanks!

P.S. I haven't checked, if this is only an issue, when `-S` is combined with `--force-samples`.

**Comment by pd3** [comment]
You can see it as a feature, not a bug. It adds a functionality not achievable otherwise. Can't you just sort your sample file?

**Comment by tommycarstensen** [comment]
Yes, I've sorted my sample file now. I agree, that it would be a desirable functionality in some cases. I've modified the documentation slightly and created a pull request here: https://github.com/samtools/bcftools/pull/650
