### ISSUE TITLE
bcftools annotate provides cryptic error message

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#651]
I am trying to annotate a VCF file using a TSV file, but I am getting no luck. Here is code to reproduce the issue:

Generating an annotation TSV file:
`echo -e "20\t60810\t0.527888" | bgzip > annot.tsv.gz && tabix -fb2 annot.tsv.gz`

Piping a VCF file for a variant to be annotated:
```
(echo "##fileformat=VCFv4.1"
echo "##contig=<ID=20,length=63025520>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "20\t60810\t.\tT\tG\t.\t.\t.") |
  bcftools annotate --no-version -a annot.tsv.gz -c CHROM,POS,GC \
  -h <(echo "##INFO=<ID=GC,Number=1,Type=Float,Description=\"GC content around the variant\">")
```

This is the outcome I get:
```
[E::bcf_sr_regions_next] Could not parse the file annot.tsv.gz, using the columns 1,2,5
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=20,length=63025520>
##INFO=<ID=GC,Number=1,Type=Float,Description="GC content around the variant">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
20      60810   .       T       G       .       .       .
```
With the variant not annotated and a cryptic error (i.e. why is it referring to non-existing column 5?).

I cannot understand what I am doing wrong. The documentation is very unclear. Would it be possible to have a few example to show how this is supposed to work (see `https://samtools.github.io/bcftools/bcftools.html`)?

**Comment by pd3** [comment]
The problem is the indexing step, the correct command is `tabix -s1 -b2 -e2`.
