### ISSUE TITLE
bcftools annotate segfault on NA annotation

### ISSUE THREAD

**Issue by agilly** [samtools/bcftools#654]
Received a segfault while trying to bcftools annotate a VCF. This was tracked down to having a single position with a NA instead of a Float in the annotation file. 

This was solved by modifying the type of the annotation to String in the header, but it would be good to either support a NA string, or raise a more explicit error message when a wrong type is encountered.

**Comment by pd3** [comment]
I think if you replace with a dot ".", it should work and place a missing value in the VCF

**Comment by agilly** [comment]
Thanks Petr! Is that mentioned in the help somewhere? Might be good to add  
it if it isn't.

**Comment by pd3** [comment]
This has been now included in the documentation, thanks for the suggestion
