### ISSUE TITLE
bcftools: how to create tabular format with query?

### ISSUE THREAD

**Issue by BralK** [samtools/bcftools#655]
Hi,
    I'm trying to create a table for my annotated vcf file using the bcftools query -f command. Here is my command line: 
`bcftools query -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%QUAL\t%FILTER\t%INFO/TAG\t%FORMAT\t%OCT1\n' annotated-file.vcf.gz`

but it gives me the error that it can't parse it properly. So I deleted each column until it worked and found out that it breaks down with the `%INFO/TAG\t` part. It says: `Error: no such tag defined in the VCF header: INFO/TAG. FORMAT fields must be in square brackets, e.g. "[ TAG]"` I just want the INFO column of my vcf file to be in the tabular form, FORMAT comes after INFO in my file, so I don't know why it thinks I'm trying to do the FORMAT column. There must be something I don't understand about the syntax.

Thanks

**Comment by pd3** [comment]
The error message suggests that there is no INFO tag "TAG" defined in the header. Is there?

**Comment by BralK** [comment]
No it just says INFO and the next column is FORMAT

**Comment by pd3** [comment]
The VCF must have correctly formatted header in order for this to work. The specification with examples can be found here http://samtools.github.io/hts-specs/VCFv4.3.pdf

**Comment by BralK** [comment]
Oh, I think I get it now. So how I run that command properly? Where do the square brackets go? I'm guessing that, wherever I'm supposed to put the brackets, I have to put the `GQ` from the header if it says `#INFO<ID=GQ` inside them, right?

**Comment by pd3** [comment]
There are some examples in the documentation that should make it clear http://samtools.github.io/bcftools/bcftools-man.html#query

The brackets are intended for FORMAT fields, this is to distinguish between two types of output:

Say your VCF has two samples with the following FORMAT fields:
````
FORMAT  SMPL_A   SMPL_B
GT:GQ    0/0:0   1/1:11
````

If you want to print all FORMAT/GT fields followed by all FORMAT/GT fields, you can do this:
````
$ bcftools query -f 'GQ:[ %GQ]    GT:[ %GT]\n' file.vcf
GQ: 0 11    GT: 0/0 1/1
````

Alternatively, you may wish to print the GQ,GT fields for each sample together. In that case do this:
````
$ bcftools query -f '[   %SAMPLE GQ:%GQ GT:%GT]\n' file.vcf
SMPL_A GQ:0 GT:0/0    SMPL_B GQ:11 GT:1/1
````
