### ISSUE TITLE
prior for estimating genotype likelihood

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#656]
Hi,

Can you let me know what priors have been used to estimate genotype likelihood in bcftools? Is it the same as mentioned in https://sourceforge.net/p/samtools/mailman/message/30188766/?

Can you also point me to the program where they are defined?

**Comment by pd3** [comment]
The use text prints the default values
https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L643-L644

they are set here
https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L760-L766

and used in https://github.com/samtools/bcftools/blob/develop/mcall.c (`-m`) and 
https://github.com/samtools/bcftools/blob/develop/ccall.c (`-c`)
