### ISSUE TITLE
bcftools: 'view' behaviour in vcf with phased GTs

### ISSUE THREAD

**Issue by NatShar** [samtools/bcftools#657]
Hi,
I encountered unexpected view's behavior with vcf containing phased GTs and dosses (outputted from minimac2).
Here is how data look like in original vcf
##fileformat=VCFv4.0
##source=1000Gv3_imputation
##filedate=20151015
##INFO=<ID=RSQ,Number=1,Type=Float,Description="Genotype imputation quality from minimac">
##INFO=<ID=EMPRSQ,Number=1,Type=Float,Description="Genotype imputation quality for genotyped SNPs">
##INFO=<ID=MAF,Number=1,Type=Float,Description="Minor Allele Frequency">
##INFO=<ID=DOS,Number=1,Type=String,Description="Allele for dosage">
##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Genotype">
##FORMAT=<ID=DS,Number=1,Type=Float,Description="Dosage from minimac2">
##reference=GRCh37
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  U196 E1388 H5160
1       10539   .       C       A       40      PASS    MAF=0.00060;RSQ=0.00000;        GT:DS   0|0:0.002       0|0:0.002       0|0:0.002
1       10642   .       G       A       40      PASS    MAF=0.00419;RSQ=0.00000;        GT:DS   0|0:0.008       0|0:0.008       0|0:0.008

And here same data using view (with or without any filtering):
1       10539   .       C       A       40      PASS    MAF=0.0006;RSQ=0        GT:DS   .:0.002 .:0.002 .:0.002
1       10642   .       G       A       40      PASS    MAF=0.00419;RSQ=0       GT:DS   .:0.008 .:0.008 .:0.008

The view does not behave same way with minimac outputted VCF that has only un-phased GTs and no doses: 
bcftools view  IAMDGC_Genotypes_20160607_c1.vcf.gz|grep -v "#" | cut -f1-12|head -3
1       798959  .       G       A       .       PASS    dbSNPID=rs11240777;ALT_dbSNP=A;AC=12507;AN=55746        GT      0/0     0/1     0/1
1       838555  .       C       A       .       PASS    dbSNPID=rs4970383;ALT_dbSNP=A;AC=12741;AN=50722 GT      0/0     0/0     0/1

Am I missing some bit that is setting view to behave differently in the second example?

**Comment by mcshane** [comment]
`GT` should be `Type=String` not `Type=Number`

**Comment by NatShar** [comment]
That was fast, helpful and sort of "anticlimactic" for me (spent too much time fuming before asking).

Thanks!
