### ISSUE TITLE
Could someone please clarify what the bcftools call -p option is meant to represent?

### ISSUE THREAD

**Issue by danshea** [samtools/bcftools#658]
Hi,

I'm confused as to the meaning of this option and how it should be used to increase or decrease the strictness of variant calling.

I read the man page, which states the following:

>-p, --pval-threshold float
>with -c, accept variant if P(ref|D) < float. 

Which leads me to believe that this option is the p-value threshold for calling a variant.  
Meaning I should set it to -p 0.001 (or lower) to ensure SNPs are called stringently.

But then I came across the following in a Nature paper in the methods section.
[https://www.nature.com/articles/sdata2016119#methods](https://www.nature.com/articles/sdata2016119#methods)

>We used ‘-p 0.9’ to ask Bcftools to report variants at a locus with more than 10% reads showing a >different genotype to that of the reference.

Did the option change meaning between versions, because I noted that the Nature paper is using an older version back when `bcftools call` was `bcftools view`.

But now I am wondering how I should be setting --pval-threshold and what exactly the option is representing?

Regards,
Dan Shea

**Comment by pd3** [comment]
The short answer is yes, the `-p` and `-P` parameters influence if a site is called variant.

A longer answer: there are two variant calling models implemented in `bcftools` and both are now accessible via the `call` command. The original model, the former `bcftools view`, is the new `bcftools call -c` command. Then there is another, newer model, implemented in `bcftools call -m`.  The math notes for both models are accessible from this page http://samtools.github.io/bcftools.

**Comment by danshea** [comment]
Hi pd3,

I am aware of the newer multiallelic caller `-m`, but specifically, I am interested in how I should be setting `-p` when using the original model `-c`. Is `-p` a p-value as the manpage implies?

I'll try to re-phrase my question.

Should I be setting `-p` as:

a p-value threshold (i.e. - the alpha for the hypothesis test) (e.g. - 0.05)

Or:

`1 - # of variants showing a different genotype to that of the reference" (e.g. - 0.9)

As the Nature paper claims. Which is correct?  
Because the value assigned to p will be very different.

Regards,
Dan Shea

**Comment by danshea** [comment]
Hi pd3,

Thank you for the clarification.

Regards,
Dan Shea
