### ISSUE TITLE
Should `bcftools index` return non-zero status when EOF marker is absent?

### ISSUE THREAD

**Issue by pd3** [samtools/bcftools#659]
The absence of the EOF marker indicates the input file is truncated (always?). Arguably it would be better to exit with a non-zero status so that pipeline can catch corrupted files early on.

**Comment by bioinformed** [comment]
By that logic, all `samtools` and `bcftools` commands fail on truncated input (for seekable files) unless a parameter is provided to reduce the error to a warning.  Having the default behavior simply raise a warning is fine for casual uses of these tools, but not raising errors on truncated files requires additional mitigations in all careful production pipeline implementations (speaking from experience).
