### ISSUE TITLE
Selecting VCF variants based on indel size

### ISSUE THREAD

**Issue by claudiadast** [samtools/bcftools#661]
I'm using bcftools to call variants from a VCF that meet several criteria, using the command:
bcftools query -i 'DP>20 & GQ>90.....(etc)'

One of the criteria I need to include is that the indel size be no more than 50bp. How can I add that to the above command? 

Thanks!

**Comment by pd3** [comment]
How about this:  `abs(strlen(ALT)-strlen(REF))<=50`
