### ISSUE TITLE
bcftools roh genetic map

### ISSUE THREAD

**Issue by irisjansen** [samtools/bcftools#664]
Hi!

It is isn't totally clear to me whether  one should use a genetic map when running bcftools roh. Is this only required for WES data or also preferred for WGS? Or is it always useful when working with unphased WGS data? If so, is there also a European population specific genetic map available?

Thank you,
Iris

**Comment by pd3** [comment]
The genetic map is helpful but not required, the program can work without it. I don't know of a population specific map. There are some pointers available on this page http://samtools.github.io/bcftools/howtos/roh-calling.html

**Comment by irisjansen** [comment]
Great, thank for the quick reply!

**Comment by mmokrejs** [comment]
Probably the help-text coudl be improved then to emphasize it is optional?

```
$ run-roh.pl --help
About: This is a convenience wrapper for "bcftools roh" which takes multiple VCF/BCF files
       and locates regions private to a sample or shared across multiple samples. On input it
       expects a directory with .vcf, .vcf.gz or .bcf files, a file with allele frequencies
       and a genetic map. See http://samtools.github.io/bcftools/howtos/roh-calling.html for
       details
```
```

-    and a genetic map. See http://samtools.github.io/bcftools/howtos/roh-calling.html for
+    and optionally a genetic map. See http://samtools.github.io/bcftools/howtos/roh-calling.html for
```

**Comment by pd3** [comment]
Updated, thank you
