### ISSUE TITLE
plot-vcfstats range error

### ISSUE THREAD

**Issue by subwaystation** [samtools/bcftools#666]
Hi,
I get the following error when I try to run `plot-vcfstats`:

```
Plotting graphs: python plot.py
Traceback (most recent call last):
  File "plot.py", line 240, in <module>
    for i in range(n): col[i] = cm(1.*i/n)
TypeError: 'range' object does not support item assignment
The command exited with non-zero status 256:
	python plot.py

 at /usr/bin/plot-vcfstats line 76.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /usr/bin/plot-vcfstats line 276
	main::plot(HASH(0x195a680)) called at /usr/bin/plot-vcfstats line 65
```
What could be the problem here?

Cheers,
Simon

**Comment by pd3** [comment]
What version of python is this (`python --version`)? Any chance you could attach the `plot.py` script?

**Comment by amin-saffari** [comment]
Same issues here! It must be because of python3 as in python3 range is a generator object and it does not return a list.
Change [...range(n)...](https://github.com/samtools/bcftools/blob/develop/misc/plot-vcfstats#L1601) to list(range(n)) should solve the case!

**Comment by subwaystation** [comment]
Hi @amin-saffari !
Then I get:
```
Traceback (most recent call last):
  File "plot.py", line 240, in <module>
    for i in list(range(n)): col[i] = cm(1.*i/n)
TypeError: 'range' object does not support item assignment
The command exited with non-zero status 256:
	python plot.py

 at /usr/bin/plot-vcfstats line 76.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /usr/bin/plot-vcfstats line 276
	main::plot(HASH(0x2216698)) called at /usr/bin/plot-vcfstats line 65
```
@pd3 
`python --version` gives me:
```
Python 3.6.2
```

**Comment by subwaystation** [comment]
It seems to me, that I have a different `plot-vcfstats` file than in the development version, I will attach it asap.
Furthermore, I install the `bcftools` fresh from the AUR (Archlinux User Repository).

**Comment by subwaystation** [comment]
[plot-vcfstats.txt](https://github.com/samtools/bcftools/files/1238221/plot-vcfstats.txt)

**Comment by subwaystation** [comment]
I just added the `.txt` ending so that I can upload it.

**Comment by amin-saffari** [comment]
@subwaystation,
Change the line above the line I mentioned from `\\tcol = range(n)` to `\\tcol = list(range(n))` that should be it! atleast in my side! 

@pd3 , It would be nice to enhance this code generator a dependency based upon the version of python which is default in different system!

**Comment by subwaystation** [comment]
@amin-saffari 
I changed it to `\\tfor i in list(range(n)): col[i] = cm(1.*i/n)` as you have told me. Then I get the new error above.

**Comment by amin-saffari** [comment]
Great! But you need to change the line above `\\tfor i in list(range(n)): col[i] = cm(1.*i/n)` as well!
Variable `col` is in the type range which you can't assigned value to it. So by changing `\\tcol = range(n)` to `\\tcol = list(range(n))` the new error should be gone!

**Comment by subwaystation** [comment]
@amin-saffari 
I am very sorry man, I misread your very helpful tips!
Thank you very much!

**Comment by pd3** [comment]
I am reopening the issue until it is updated in the code. Thank you both, for reporting and then solving the issue.
