### ISSUE TITLE
vcf.gz file, but bcftools says it's not compressed with bgzip

### ISSUE THREAD

**Issue by BralK** [samtools/bcftools#668]
Hi,

I am creating a script to annotate files, and when testing it out I entered an input file. The command I run on that file is: `bcftools annotate -a dict.vcf.gz -c INFO newfile.vcf.gz`

I used tabix to bgzip them both, but it gives me the message: `Failed to open newfile.vcf.gz: not compressed with bgzip`
`
Failed to open -: unknown file type`

I can open the file on its own, and I've played around with the script, but nothing seems to be able to fix this issue. Is there something I'm doing wrong?

Thank you so much.

**Comment by pd3** [comment]
Tabix only indexes, but does not bgzf-compress files. You'll need either use `bcftools view` or `bgzip` to compress the files first:
````
bgzip file.vcf       # or:   bcftools view file.vcf -Oz file.vcf.gz
tabix file.vcf.gz    # or:   bcftools index file.vcf.gz
````

Another useful command is `htsfile file.vcf.gz` which prints the actual file type.

**Comment by BralK** [comment]
Yes I have tried those but it still gives me the same error. When I use the bcftools view command it gives me the same error that says it can't open the file because it's not compressed with bgzip. But it can open the file because when I just run `bcftools view -h file.vcf.gz` it views it as it should. The tabix command returns the error: `tbx_index_build failed: file.vcf.gz`

`htsfile file.vcf.gz` returns: `file.vcf.gz:	VCF version 4.1 variant calling text` 

The script again shows the same error message before. Would you like me to show the commands I have in the script?

**Comment by pd3** [comment]
Clearly the file `file.vcf.gz` is not compressed, otherwise the htsfile output would report it was compressed. Do this:
````
mv file.vcf.gz plain.vcf
bcftools view -Oz -o compressed.vcf.gz plain.vcf
htsfile compressed.vcf.gz
bcftools index compressed.vcf.gz
````

**Comment by BralK** [comment]
Okay, that worked. Thank you very much I appreciate the persistent help.

**Comment by ati-lz** [comment]
Hi

Im having the same problem while Im trying to add a region file with -R tag to mpileup and call! I check the htsfile of the region file (vcf.bgz) and it says 
`htsfile gnomad.exomes.r2.0.2.sites.orig.chromadded.vcf.bgz
gnomad.exomes.r2.0.2.sites.orig.chromadded.vcf.bgz:	VCF version 4.2 BGZF-compressed variant calling data`

so I imagine it has been compressed correctly! But I get the following error:

`bcftools mpileup -E -Ou -R gnomad.exomes.r2.0.2.sites.orig.chromadded.vcf.bgz -f hsa_GRCh38.primary_assembly.genome.fa MARSseq.human.TTACGC.sam.sorted.bam MARSseq.human.GACCAG.sam.sorted.bam --annotate AD,DP,SP,INFO/AD | bcftools call -R gnomad.exomes.r2.0.2.sites.orig.chromadded.vcf.bgz -m -Ou | bcftools filter -Ou -i'DP>3 && QUAL>20' | bcftools sort -T tmp/ --max-mem 15G -Oz -o mpileup/556822.mpileup.vcf.gz

Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Writing to tmp/
[mpileup] 2 samples in 2 input files
Failed to open -: not compressed with bgzip
Failed to open -: unknown file type
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
bcftools: bgzf.c:847: bgzf_read: Assertion `fp->is_write == 0' failed.
Aborted (core dumped)
`

I even tried to convert this VCF to BED file and give the BED format as input, but I get the same error...

It would be great if you can provide some help!

Thanks

**Comment by pd3** [comment]
There are several commands streamed into each another. Do this stepwise, first checking the output of the first, saving it into a file, then of the second, etc. This way you'll find out where the bug is.

**Comment by andemexoax** [comment]
I am having a similar issue when trying to perform bcftools merge. I get these errors with the first file in the list, `[E::hts_hopen] Failed to open file filename.bcf.csi` and `[E::hts_open_format] Failed to open file filename.bcf.csi` and `Failed to open filename.bcf.csi Exec format error`...

I take .bcf files and index them with `bcftools index` ... using `htsfile` I find my files are indeed "CSI version 1 compressed index data", of "BCF version 2.2 compressed variant calling data", originally from files of "VCF file version 4.2 variant calling text" I am using "BCFtools Version: 1.9 (using htslib 1.9)"

this is my script `bcftools merge --missing-to-ref --file-list /vol_c/scripts/file_list.txt --merge all --threads 14 --output plants_all58.vcf`

**Comment by pd3** [comment]
The program can be trusted when it complains like this. Most likely the file names are similar but not quite the same? Or you don't have permissions to read the files? You'd have to provide full output from your commands for further debugging, for example like this:
```
$ cat /vol_c/scripts/file_list.txt
filename1.bcf
filename2.bcf

$ htsfile `cat /vol_c/scripts/file_list.txt`
filename1.bcf:	BCF version 2.2 compressed variant calling data
filename1.bcf.csi:	CSI version 1 compressed index data

$ ls -l `cat /vol_c/scripts/file_list.txt`
```

Please open a new issue next time.

**Comment by clemonsa** [comment]
@pd3 
I have a `plain.vcf` file, when I try to convert it to a `compressed.bcf.gz` using `bcftools view plain.vcf -Ob compressed.bcf.gz` I get this same error message.

Is bcftools unable to convert a file from plain text to the compressed version of a binary? I tried then directly converting to `plain.vcf` to `plain.bcf` in a pipeline to arrive at `compressed.bcf.gz` and the same error occurred.

I already used `htsfile` to confirm that the `plain.vcf` file is what it should be.

**Comment by pd3** [comment]
This is a very basic feature, so you are most likely doing something wrong. If you believe it is a bug, please open a new issue and include: the version of bcftools you are running (output of `bcftools --version`), full commands (the `view` command you give above is incorrect, it would stream binary data on the screen), full outputs, and best if you could make your file available for testing.
