### ISSUE TITLE
Seg fault using bcftools norm command

### ISSUE THREAD

**Issue by brianhill11** [samtools/bcftools#669]
Hi there, 

I'm getting a seg fault at this line: https://github.com/samtools/bcftools/blob/04608ff2bf11020a01de12db50fb2d2a3561ddca/vcfmerge.c#L665
Code tries to free a location that has not previously been allocated (according to gdb). The command I'm using is: 
```
bcftools norm -m +any -Oz -o /tmp/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.NA21127.vcf.gz ALL.chr22.phase3_shapeiated_v5a.20130502.genotypes.NA21127.vcf.gz
```
bcftools version 1.5, htslib version 1.5-10-gcc55632, both built with gcc. 

Input data is from sample NA21127 from the 1000 genomes phase 3 dataset. I've split chromosome 22 by sample into individual VCF files.
The VCF lines that seem to be causing this issue are:
```
22        27562252        rs553563245;rs72334397  AGAAT   AGAATGAAT,A     100     PASS    AC=0,1;AF=0.00798722,0.169329;AN=2;NS=2504;DP=23737;EAS_AF=0.0089,0.126;AMR_AF=0.0086,0.1744;AFR_AF=0.0076,0.1505;EUR_AF=0.007,0.2614;SAS_AF=0.0082,0.1411;VT=INDEL;MULTI_ALLELIC   GT      2|0
22        27562252        rs111922245     AGAATGAAT       A       100     PASS    AC=1;AF=0.419329;AN=2;NS=2504;DP=23737;EAS_AF=0.2728;AMR_AF=0.3386;AFR_AF=0.5605;EUR_AF=0.4006;SAS_AF=0.456;VT=INDEL        GT      0|1
```

As you can see, this is an interesting case where the first alternate allele in the top variant happens to be the reference allele in the second variant. 
 
I can send/post the VCF file if that would help.

Thanks,
Brian

**Comment by pd3** [comment]
Hi Brian, I was not able to reproduce it on my machine, but hopefully this commit should fix the problem https://github.com/samtools/bcftools/commit/c7523e43d9099c5fd61c01db1c617577de14bbc1
Thank you for the bug report.
