### ISSUE TITLE
plot-roh.py error

### ISSUE THREAD

**Issue by irisjansen** [samtools/bcftools#675]
Hi,

I am using the python script to plot the output of the perl script calculating/comparing roh's of multiple samples. I get the following error: "NameError: name 'plt' is not defined". However the script contains the following part, so it seems that 'plt' is defined correct?

"
import matplotlib as mpl
for gui in ['TKAgg','GTKAgg','Qt4Agg','WXAgg','MacOSX']:
    try:
        mpl.use(gui,warn=False, force=True)
        import matplotlib.pyplot as plt
        import matplotlib.patches as patches
        break
    except:
        continue
"

Do you have an idea what could be causing the error?

Thanks,
Iris

**Comment by pd3** [comment]
It seems your matplotlib installation does not offer any of the interactive engines listed above. You can try
````
$ python
import matplotlib.rcsetup as rcsetup
print(rcsetup.all_backends)
````
to list the backends and then try to run manually to confirm, e.g.
````
import matplotlib as mpl
mpl.use('GTKAgg')
````

**Comment by irisjansen** [comment]
Great thank you for your fast reply.

It works now, at lease part of it. If I understand correctly this script
takes the bcf files as input (generated by run-roh.pl). However, the
generated plot only includes the first individual of the bcffile, while
there are 61 individuals. How do I tell the script to generate a plot for
every individual? (I tried -s option but didn't make a difference).

Thank you,
Iris

**Comment by pd3** [comment]
The script `run-roh.pl` takes on input a directory with multiple single-sample VCFs or BCFs, then it runs the roh predictions. The plotting script works with the resulting tab-delimited text files `*.txt.gz`.

I just pushed a commit to make it work also with multi-sample VCFs https://github.com/samtools/bcftools/commit/8b53f1ee7c377339aec30b54890e5d95f5b6b118. However, beware that displaying 61 samples at once may take a lot of memory, matplotlib is not very efficient.
