### ISSUE TITLE
FORMAT 'GP' is not defined in the header

### ISSUE THREAD

**Issue by migraff** [samtools/bcftools#676]
I'm trying to remove the monomorphic SNPs from vcf files.  My script looks like this:
bcftools view -e @chr22_monomorphicSNPs.txt ../vcf/imputed3_chr22.vcf.gz  -O z > 1KGP3imputed_chr22.imputed.poly.vcf.gz

where chr22_monomorphicSNPs.txt is the list of SNPs to exclude.  However, i get the error:

[W::vcf_parse_format] FORMAT 'GP' is not defined in the header, assuming Type=String [E::bgzf_close] File write failed

the GP is not in the header.  Do i have to have this?  
Thanks!

**Comment by pd3** [comment]
Please use the `bcftools reheader` command to fix the header.
