### ISSUE TITLE
bcftools consensus -I and -H A options doesn't  exist in version 1.5 and 1.3.1

### ISSUE THREAD

**Issue by ericgonzalezs** [samtools/bcftools#677]
Hi all
 
I am using bcftools consensus to add the alternative SNPs to a fasta file. I tried bcftools versions 1.5 and 1.3.1

I am running it in two ways:

 bcftools consensus -i -s sample1 -f reference.fasta file.vcf.gz > pseudoreference.fasta
bcftools consensus -H A -s sample1 -f reference.fasta file.vcf.gz > pseudoreference2.fasta

With the first of my ways to run bcftools, I get the alternative allele in the new fasta only when my sample is homozygous alternative.  Here there it is an example of that, I show the region where the SNPs are, the SNP position separated and the vcf line of the SNP the sample that is the first one that appears. 
.

>10:410-420 
Reference             GTAGTT T AATT
Pseudoreference  GTAGTT T AATT

##VCF region
10    416    .    T    C    548.44    PASS    AC=2;AF=0.500;AN=4;BaseQRankSum=2.10;ClippingRankSum=0.367;DP=36;ExcessHet=4.7712;FS=32.570;MLEAC=2;MLEAF=0.500;MQ=44.99;MQRankSum=-2.196e+00;QD=15.23;ReadPosRankSum=-1.220e-01;SOR=5.669    GT:AD:DP:GQ:PL    0/1:10,9:19:99:325,0,319    0/1:10,7:17:99:252,0,259

>10:2820-2830
Reference              TTCCTGCCTTT
Pseudoreference  TTCCTTCCTTT

##VCF region
10    2825    .    G    T    253.54    PASS    AC=3;AF=0.750;AN=4;BaseQRankSum=-6.840e-01;ClippingRankSum=0.322;DP=12;ExcessHet=3.0103;FS=0.000;MLEAC=3;MLEAF=0.750;MQ=43.74;MQRankSum=-6.840e-01;QD=21.13;ReadPosRankSum=-9.560e-01;SOR=0.495    GT:AD:DP:GQ:PL    1/1:0,4:4:12:164,12,0    0/1:3,5:8:99:119,0,104

I would like to have always the alternative SNP even if the sample is heterozygous so I try the second bcftools script that is above and the result is the next error:

Can't apply 17-th haplotype at 10:416

Do you know how I can add to my fasta always the alternative allele always that my sample is heterozygous or homozyguous for the alternative allele?

I tried versions 1.3.1 and 1.5 for both the options are:

 -f, --fasta-ref <file>     reference sequence in fasta format
    -H, --haplotype <1|2>      apply variants for the given haplotype
    -i, --iupac-codes          output variants in the form of IUPAC ambiguity codes
    -m, --mask <file>          replace regions with N
    -o, --output <file>        write output to a file [standard output]
    -c, --chain <file>         write a chain file for liftover
    -s, --sample <name>        apply variants of the given sample

It looks that the -I option and -H A option doesn't exist. Do you know what is happening?

Best Wishes,

**Comment by pd3** [comment]
You are using a version of bcftools which does not support `-H A` yet. Please check here how to get the latest
http://samtools.github.io/bcftools/

**Comment by ericgonzalezs** [comment]
Thank you for your answer.

If I understand well I have the latest version, is bcftools 1.5 and the -H A option is not there

If I type  >bcftools consensus

I get: 
          About: Create consensus sequence by applying VCF variants to a reference fasta
          file. By default, the program will apply all ALT variants. Using the
          --sample (and, optionally, --haplotype) option will apply genotype
       (or haplotype) calls from FORMAT/GT. The program ignores allelic depth
       information, such as INFO/AD or FORMAT/AD.
        Usage:   bcftools consensus [OPTIONS] <file.vcf>
        Options:
          -f, --fasta-ref <file>     reference sequence in fasta format
          -H, --haplotype <1|2>      apply variants for the given haplotype
           -i, --iupac-codes          output variants in the form of IUPAC ambiguity codes
          -m, --mask <file>          replace regions with N
          -o, --output <file>        write output to a file [standard output]
          -c, --chain <file>         write a chain file for liftover
    -s, --sample <name>        apply variants of the given sample
      Examples:
        # Get the consensus for one region. The fasta header lines are then expected
        # in the form ">chr:from-to".
       samtools faidx ref.fa 8:11870-11890 | bcftools consensus in.vcf.gz > out.fa


The I and -H A option are note there. It's a problem with my installation? or what is happening?

And i think is the wright last version.

if I type >bcftools

I get:

        bcftools

       Program: bcftools (Tools for variant calling and manipulating VCFs and BCFs)
       Version: 1.5 (using htslib 1.5)
        ...

Best,

Eric

**Comment by pd3** [comment]
Hi, 
sorry for the confusion: 1.5 is the latest released numbered version, but the option is available in the development version, which is available for download as described on this page http://samtools.github.io/bcftools/. Alternatively, you can use the green "clone or download" button on the project page https://github.com/samtools/bcftools
If you are wondering if it is safe to use the development version, then yes, it is. The stable version is just an illusion with more unfixed bugs than the development version.
