### ISSUE TITLE
no missing values (.) in vcf file created using samtools/bcftools call -c

### ISSUE THREAD

**Issue by mariels** [samtools/bcftools#678]
Hello,

I have been using bcftools and samtools to generate a vcf file. I'm interested in genotypes/alleles frequencies information to test for loci under selection using Bayescan and related programs.

However, it seems I have no missing values (.) for my 60 individuals when I use the original 'consensus' SNP caller (-c). I am afraid that no coverage data have been treated as reference alleles with genotype 0/0. I should have missing data as I have whole genome sequences with coverage of 3 to 10x.

I have been using:
samtools mpileup -uf reference.fna bam1.bam bam2.bam bam3.bam bam4.bam etc.bam  | bcftools call -c - > data.raw.bcf

bcftools view data.raw.bcf | vcfutils.pl varFilter > data.flt.vcf 

and 
samtools mpileup -uf  reference.fna bam1.bam bam2.bam bam3.bam bam4.bam etc.bam  | bcftools call -cv --format-fields GQ - > data2.raw.bcf

bcftools view data2.raw.bcf | vcfutils.pl varFilter > data2.flt.vcf 

I would be interested in not having missing data coded as reference alleles and in excluding SNPs with a certain amount of missing data (and so I would need missing data to be coded in a certain way).  

I have also used the new multi-allelic caller and got the missing data coded correctly as (.).

samtools mpileup -ugf ref.fna bam1.bam bam2.bam bam3.bam bam4.bam etc.bam -Q 30  | bcftools call -vmO z --format-fields GQ,GP -o data3.vcf.gz

I think I will work with the vcf file generated using the multi-allelic caller but I would still be interested to know whether it is possible to identify missing data with the consensus caller and understand why I do not get missing data coded properly (i.e. whether there is something wrong in my command).
I do not have the AD (allelic depths for the ref and alt alleles), DP (read depth) fields, which could be another fitler.

Could anyone help on this issue? 

Thank you very much,

Marie

**Comment by pd3** [comment]
Hi Marie, unless someone is willing to contribute a pull request addressing the issue, I am afraid there is currently no way to make the `-c` caller correctly output the missing values, sorry!

**Comment by mariels** [comment]
Thanks for your answer.

Marie
