### ISSUE TITLE
bcftools consensus: return only regions of interest?

### ISSUE THREAD

**Issue by Rmulet** [samtools/bcftools#679]
Hi,

I am using bcftools consensus to generate a FASTA file from a VCF, but I am only interested in some particular regions. Since the program takes into account indel data, the coordinates that were valid for the original reference genome are no longer applicable to the new one. 

Although the --chain option can be used to map the coordinates, if would be convenient to have an option, similar to the "-R" found in other tools, to select what regions to output according to a BED file. 

Would that be possible?  Thanks for considering my suggestion.

Roger

**Comment by pd3** [comment]
Hi, it indeed is a reasonable request, but it is unlikely to be implemented soon. Fortunately there is an easy workaround that can be applied using existing tools - first subset the VCF using the `view` command, then run consensus?

**Comment by Rmulet** [comment]
Thanks for the prompt reply. I think I did not express my idea very clearly -- now I realize that what I was suggesting slightly diverges from the normal usage of the `-R` option in `bcftools`. Indeed, if I want to generate a consensus for a subset of the variants I only need to use `view` before `consensus`. However, in this case the idea is to produce a FASTA which only contains the regions delimited in the BED file, but obviously mapped to the new coordinates. 

A workaround for this is to generate a chain file, run `liftOver` and the extract the regions of interest with bedtools using the new coordinates. Unfortunately, that is a bit cumbersome and generates a potentially unnecessary, big, FASTA file.

**Comment by pd3** [comment]
Hmm, you could use `samtools faidx` on each region and then glue the chunks together with a small custom script?
````
samtools faidx ref.fa 8:11870-11890 | bcftools consensus in.vcf.gz > out.fa
````

**Comment by Rmulet** [comment]
Oh, yeah, that works, thanks! In the past I had tried a similar approach with `bedtools getfasta`, but it did not work, so I assumed it was simply not possible. Now I have realized it's just because `bedtools` uses 0-based coordinates, whereas bcftools and samtools are both 1-based.

Well, then I guess that feature is not so necessary, though it could still be convenient. Thanks again! :+1:

**Comment by pd3** [comment]
Good. Closing the issue as resolved then.
