### ISSUE TITLE
bcftools consensus --chain generates (null) lines for alternative assemblies

### ISSUE THREAD

**Issue by Rmulet** [samtools/bcftools#680]
Hi,

I have been using bcftools consensus recently with the --chain option to map BED coordinates from the reference to the new FASTA sequence.  Unfortunately there is an issue with non primary assembly chromosomes, i.e. those that are not named as "chrN": they are added to the chain file but their name is replaced with "(null)".

This can be fixed with some bash scripting (in my case I just got rid of them), but it does not seem like an ideal behaviour for this tool.

**Comment by pd3** [comment]
Hi, any chance you could provide a small test case for debugging the problem?

**Comment by Rmulet** [comment]
Hi again,

I think I have found the cause for this behaviour while trying to generate a small test case as requested. These "(null)" values appear whenever a sequence in the FASTA file is not listed as a contig in the VCF file -- in my case, only the primary assemblies are there, hence the error. When that happens, `bcftools consensus` displays an error message like the following:

> 
Warning: Sequence "chrUn_gl000245" not in test.vcf.gz

What should I do with the test case? Share it via pull request?

**Comment by pd3** [comment]
There is an email on my profile page, thank you

**Comment by pd3** [comment]
Hi, I think I saw an email from you in my mailbox but cannot find it, probably accidentally deleted. Could you please resend it?

**Comment by pd3** [comment]
Thank you for the testing file, it is now fixed.
