### ISSUE TITLE
'bcftools query -c none' doesn't work

### ISSUE THREAD

**Issue by huangk3** [samtools/bcftools#681]
the command returns the error, "The --collapse string "none" not recognised."

**Comment by pd3** [comment]
Thank you. Looking at the code, it needs updating. The `none` option is the default, so it does not need to be given. What are you trying to do by the way? This option is for cases when multiple VCFs are given, which is a rare situation with `query`.

**Comment by huangk3** [comment]
Hi @pd3 Thanks for looking into this. My input VCF for 'query' was normalized thus multi-allelic sites were split into separate records which share the same genomic coordinates. When I run 'query' on the normalized VCF without the '-c' command, those records were automatically collapsed into a single line in the result, so I wanted to use '-c none' to disable this behavior and make the output has the same number of lines and in the same order as the input VCF does.

**Comment by pd3** [comment]
This is now resolved by providing a workaround - pipe through `norm -d none` first.
