### ISSUE TITLE
bcftools stats --af-bins issue

### ISSUE THREAD

**Issue by mjko1210** [samtools/bcftools#685]
Hi,

There are two questions I want to ask.

1) I've noticed that allele frequencies are not correctly sampled according to '--af-bins' that I specify. 

My command was:
bcftools stats --af-bins 0.05,0.25,0.75,1 --af-tag AF -d 0,5000,500 -s- -c none sample1.vcf.gz sample2.vcf.gz > test.txt

From test.txt,
````
# AF, Stats by non-reference allele frequency:
# AF	[2]id	[3]allele frequency	[4]number of SNPs	[5]number of transitions	[6]number of transversions	[7]number of indels	[8]repeat-consistent	[9]repeat-inconsistent	[10]not applicable
AF	0	0.150000	177	88	89	208	0	0	208
AF	0	0.500000	113	51	62	239	0	0	239
AF	0	0.875000	58	36	22	36	0	0	36
AF	1	0.150000	200	64	136	281	0	0	281
AF	1	0.500000	49	28	21	245	0	0	245
AF	1	0.875000	37	22	15	54	0	0	54
AF	2	0.150000	311	105	206	397	0	0	397
AF	2	0.500000	3989	2758	1231	547	0	0	547
AF	2	0.875000	2212	1526	686	206	0	0	206
````
As you can see, AF bin was set to 0.15, 0.5, 0.875 instead of 0.05,0.25,0.75,1.
I tried it out with few other examples (AF bin) but it always gave me different sets of AF.

2) When I plot my bcftools stats outputs via plot-vcftools, concordance plot (plot_concordance_by_af)
doesn't seem plot all the data I have.

 My 'gts_by_af.dat' contains:
````
# [1]Allele Frequency	[2]RR concordance	[3]RA concordance	[4]AA concordance	[5]nRR	[6]nRA	[7]nAA	[8]R^2	[9]Number of genotypes
0.150000	1.000000	0.999535	1.000000	0	4304	0	0.592525	4314
0.500000	1.000000	0.500000	0.998635	0	14	2198	0.347468	2219
````
It plots data based on 'gts_by_af.dat', however, I don't know why it excludes data for AF=0.875 although I have them in bcftools stats output (test.txt). FYI, X-axis range for this plot was (0.10, 0.50).

My 'test.txt' includes:
````
# GCsAF, Genotype concordance by non-reference allele frequency (SNPs)
# GCsAF	[2]id	[3]allele frequency	[4]RR Hom matches	[5]RA Het matches	[6]AA Hom matches	[7]RR Hom mismatches	[8]RA Het mismatches	[9]AA Hom mismatches	[10]dosage r-squared	[11]number of genotypes
GCsAF	2	0.150000	0	315	0	0	0	0	0	315
GCsAF	2	0.500000	0	3987	0	0	2	0	0.639198	3999
GCsAF	2	0.875000	0	7	2195	0	7	3	0.347468	2219
````

Your suggestions will be much appreciated!

**Comment by pd3** [comment]
The output displays the midpoint of the bins.

**Comment by Liuyh275** [comment]
Hi，

I still have one question about AF-bins accuracy during analysis. 

When I set the command,
`bcftools AF.vcf.gz file.vcf.gz stats -s - -t chr20 --af-tag "AF" --af-bins 0,1`, and get the result as follows,

<img width="805" alt="p1" src="https://github.com/samtools/bcftools/assets/122274407/69648a30-dcff-46db-afef-b0eae427dda9">

Then I use the same data to set another command,
`bcftools AF.vcf.gz file.vcf.gz stats -s - -t chr20 --af-tag "AF" --af-bins 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.15, 0.2, 0.25, 0.5, 1`, and get the another result 
<img width="803" alt="p2" src="https://github.com/samtools/bcftools/assets/122274407/b44f50e9-4ea5-492d-95c5-86cdc2aeeb19">

What confused me is that the accuracy of the second case was much lower than that of the first, and I wanna get clearly what had happened, and how it worked during the procedure calculating the SNP-frequencies accuracy.

Your suggestions will be much appreciated!

best,
