### ISSUE TITLE
imputed genotype probability truncation

### ISSUE THREAD

**Issue by lzddr** [samtools/bcftools#686]
Is there an option to prevent 'bcftools merge' from truncating imputed genotype probabilities? E.g. from '1.000,0.000,0.000' to '1,0,0' 

Apologies if this has been asked before. Converting VCF outputs to binary and formatting needs to be exact. Thank you!

**Comment by pd3** [comment]
Hi, no, there is no such option. The program stores the data in binary representation, so it has no way of knowing if the number `1.0` was in the VCF written as `1.000` or `1.000000`. From our point of view they are both equivalent.
