### ISSUE TITLE
bcftools: csq.c:3137: sanity_check_ref: Assertion `vcf - rec->d.allele[0] < strlen(rec->d.allele[0])' failed.

### ISSUE THREAD

**Issue by raonyguimaraes** [samtools/bcftools#689]
Hi there,

I was trying to run bcftools csq using chr22 from 1000Genomes and I'm receiving the following error:

../../programs/bcftools/bcftools csq -f ../../input/hs37d5.fa -g ../../input/Homo_sapiens.GRCh37.87.gff3 ../../ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz > output.vcf
Parsing ../../input/Homo_sapiens.GRCh37.87.gff3 ...
Indexed 196476 transcripts, 1195710 exons, 724218 CDSs, 280277 UTRs
Ignored the following biotypes:
        46x     .. 3prime_overlapping_ncrna
Calling...
**bcftools: csq.c:3137: sanity_check_ref: Assertion `vcf - rec->d.allele[0] < strlen(rec->d.allele[0])' failed.**
**Aborted (core dumped)**

I can try to submit a fix if someone can explain to me what is the problem :)

Kind Regards.

**Comment by pd3** [comment]
The program is not ready for structural variants, such as CNVs. In this commit these records will be skipped. Thank you for reporting the problem.
