### ISSUE TITLE
query snpeff annotation (Question)

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#69]
Is there a way to query the unique formatting of the snpeff "EFF" tag? Understood if subfields are not in the plans but thought I'd ask given how popular the software is.  

It's possible via snpsift but I'm trying to stick to bcftools.
http://snpeff.sourceforge.net/SnpSift.html#filter

ps. do you want similar questions here or somewhere else?

**Comment by sangeeta-25** [comment]
i have a query regarding SnpEff tool. the variation information of the reference and alternate allele at the nucleotide level is different from the variation information  at nucleotide present in the INFO column, specially in the case of missense variation.which variation information is more reliable for the analysis information? please can anyone help me through this. thank you
