### ISSUE TITLE
Info tag error when doing bcftools query

### ISSUE THREAD

**Issue by claudiadast** [samtools/bcftools#692]
I tried running this command:

`bcftools query -i'AF>=0.05 && (GT=“0/1” || GT=“1/1”)' -f'[ %SAMPLE] %ID [ %GT] %TYPE\n' SSC00093_annotated.vcf > SSC00093_annotated_nCommon.txt`

But it gave me the following error:
`Error: the tag "INFO/“0" is not defined in the VCF header`

**Comment by pd3** [comment]
I am not able to reproduce the problem. What version of bcftools are you running? If the problem persist with the latest version, a small test case would be helpful.
