### ISSUE TITLE
Select variants that are polymorphic between two groups of samples

### ISSUE THREAD

**Issue by NeillGibson** [samtools/bcftools#694]
Hi,

I am wondering if it is possible to use BCFTools for selecting variants that are polymorphic between two groups of samples. 

So the combination of the 6 queries below. 

| Query  | Sample set1 | Sample set2 | Remark / examples (genome ref =A)
| ------------- | ------------- | ------------- | ------------- |
| A | Hom ref  | Het |  A/A v.s. A/T, A/C, A/G, C/T, C/G |
| B  | Hom alt  | Het |  T/T v.s. A/T, A/C, A/G, C/T, C/G or  C/C v.s. A/T, A/C, A/G, C/T, C/G or  G/G v.s. A/T, A/C, A/G, C/T, C/G | 
| C | Het  | Hom ref | A/T, A/C, A/G, C/T, C/G vs A/A |
| D | Het | Hom alt |  A/T, A/C, A/G, C/T, C/G v.s. T/T or A/T, A/C, A/G, C/T, C/G v.s. C/C or A/T, A/C, A/G, C/T, C/G v.s. G/G |
| E | Hom ref  | Het | A/A vs C/C, T/T, G/G |
| F | Hom alt  | Hom ref |  C/C, T/T, G/G vs A/A |

Or maybe just the variants where samples from set 1 are` Hom alt` and the samples from set 2 are `Het` or `Hom ref `. This would be the combination of query B and F. 

As far as I know currently it is only possible to:

- filter on genotype status over a single sample set (i.e. `-S SOI.txt --genotype ^hom`). 

- or allele frequency over single sample set  (i.e. `-S SOI.txt  --min-af 0.05 --max-af 0.40` )

Being able to explicitly filter on variants that contrast between two samples sets would be a very useful addition for us.  

Is this already possible? Or would it be possible to add this functionality? Thank you.

**Comment by pd3** [comment]
This is currently not possible. There is `vcf-contrast` which does something like this. Maybe plink's association tests could help here?

**Comment by NeillGibson** [comment]
The idea is to filter out variants that discriminate between a control and case group of samples. And to return the results as a standard VCF file.  This is needed because this is 1 of many queries that we use that can return a VCF. 

We work with some organisms were inbreeding is possible so in some cases it makes sense to do a fairly strict and simple comparison of genotypes between groups. 

I will have a look at `vcf-contrast` or maybe try to implement this filter myself in cyvcf2 python code (=python htslib wrapper: https://github.com/brentp/cyvcf2)

**Comment by dlaehnemann** [comment]
You could also have a look at the GTsubset plugin (https://samtools.github.io/bcftools/bcftools.html):
```
GTsubset
    output only sites where the requested samples all exclusively share a genotype
```
It can output sites for one set of samples where these samples share a genotype (e.g. A/C), whereas all the samples from the complement set have some different genotype at the same site (e.g. A/G, A/A, C/C, etc.). But I'm not sure if this is exactly what you want -- but it might help or might be a good template for a new or extended plugin to bcftools.

**Comment by NeillGibson** [comment]
@dlaehnemann  Thank you for the tip. I did not know about the GTsubset plugin. I will try it. 

I also don't know much about bcftools plugins in general.  For instance how to install them:

```
bcftools plugin -l
No functional bcftools plugins were found. The environment variable BCFTOOLS_PLUGINS is not set.
```
Is there documentation on how to install bcftools plugins and how to create these plugins?

Creating additional plugins in bcftools is maybe something we could also do. But we would need to outsource this, because we don't have anyone that can program in C. 

We currently write functionality that we miss in bcftools in cyvcf2 and use piped together bcftools commands and cyvcf2 scripts a query application. Both bcftools and cyvcf2 can read and output text vcf stream. See for example this issue and the cyvcf2 code linked to in the last comment https://github.com/samtools/bcftools/issues/544

We do sometimes find bcftools a bit human population genetics specific, so it is very nice that is is possible to create additional functionality for other domains in either the plugins or piped together bcftools + cyvcf2 commands.

**Comment by dlaehnemann** [comment]
Agreed, the plugin installation is not very well documented. It took me a moment of searching around until I found this:
https://samtools.github.io/bcftools/howtos/install.html

It contains the following notice:
```
Important  |  In order to use the BCFtools plugins, this environment variable must be set and point to the correct location: export BCFTOOLS_PLUGINS=/path/to/bcftools/plugins
```
So you need to set the shell (most probably bash) variable `BCFTOOLS_PLUGINS` to the plugins directory within your local bcftools installation. I guess making this a setting in your `.bashrc` makes most sense, as this will have it set for every bash instance you create.

I guess, this info should also go into the INSTALL file in the main repo and into the main documentation  at: https://samtools.github.io/bcftools/bcftools-man.html#plugin
For the latter, I'm not sure how this is generated, though. Also, I guess that setting this path might be something automatable in the installation process?

As for writing plugins: I didn't know much C when I started on this, but just working from the existing plugins as templates gets you a long way.

And if you're looking for other wrappers around htslib (including its VCF/BCF functionality), there is one in [Rust](https://www.rust-lang.org/), in case you have anyone around who knows or wants to learn this up and coming language: https://github.com/rust-bio/rust-htslib
