### ISSUE TITLE
bcftools plugin seg-faults if contig is not defined in the header

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#697]
While bcftools view and other commands work just fine:
```
$ echo -e "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n1\t1\t.\tA\tC\t.\t.\t." | bcftools view --no-version
> [W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
> ##fileformat=VCFv4.2
> ##FILTER=<ID=PASS,Description="All filters passed">
> #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
> 1	1	.	A	C	.	.	.	.
```

All bcftools plugins crash when `return rec;` is reached in the `bcf1_t *process(bcf1_t *rec)` function:
```
# echo -e "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n1\t1\t.\tA\tC\t.\t.\t." | bcftools +fill-AN-AC --no-version
> [W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
> Segmentation fault (core dumped)
```

This relates to the contig not being defined. If I define the contig, it works just as expected:
```
$ echo -e "##fileformat=VCFv4.2\n##contig=<ID=1,length=249250621,assembly=b37>\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n1\t1\t.\tA\tC\t.\t.\t." | /usr/bin/bcftools +fill-AN-AC --no-version
> ##fileformat=VCFv4.2
> ##FILTER=<ID=PASS,Description="All filters passed">
> ##contig=<ID=1,length=249250621,assembly=b37>
> ##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
> ##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
> #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
> 1	1	.	A	C	.	.	.	.
```

I have not traced where this bug comes from, but I assume it should be easy to find.

**Comment by pd3** [comment]
This is actually not easy to fix and will not be fixed. The quick solution is to follow the recommendation and either index the file or fix the header. For long answer please see below:

The difference between `view` and plugins is that `view` uses the same header for reading and writing. However, as we want the plugins to have full control over the output header, we keep separate headers for reading and writing. Now comes the catch. The on-the-fly error recovery which works for `view` when encountering undefined tags only modifies the header used for reading but is not visible to the header used for writing. With some extra work this could be changed, but it does not solve the fundamental problem: in both cases, this could never work for BCF output where all tags must be defined in the header. 

For plugin developers, there is a way to detect such errors by checking `rec->errcode` and exit nicely at least.

**Comment by freeseek** [comment]
However, the following command does not seg-dup:
```
$ echo -e "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n1\t1\t.\tA\tC\t.\t.\t." | bcftools view --no-version -Ou
> [W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
> [E::bcf_write] Unchecked error (1), exiting
```
Is it possible to have `bcftools plugin` behave the same? If not, how should `rec->errcode` be handled in `bcf1_t *process(bcf1_t *rec)`?

**Comment by pd3** [comment]
OK, I added a check for this so that the plugin exits nicely. The plugin can clear the flag in `process()` if this is not desired from some reason.
