### ISSUE TITLE
an option to update AC AF and AN

### ISSUE THREAD

**Issue by chenwenan** [samtools/bcftools#699]
Hi, 

Is there an option to update AC AF and AN based on the genotypes? 
Sometimes the VCF file show inconsistency between AC/AF/AN and the ones from the genotype, e.g., a vcf made from scratch or other tools. Is there a way to update these values based on the genotypes in the file? This is important because many filtering criteria will based on AC/AF/AN without re-calculating from genotypes. Inconsistency will make these filtering results wrong. 

Thanks,

WC

**Comment by NeillGibson** [comment]
Filtering on a subset (or just all samples) will have the correct `AN `and `AC `values in the VCF that is written to standard out or the output file.  

Use `bcftools query -l > SOI.txt` to get a full list of samples. Then do `bcftools view -S SOI.txt input.vcf.gz` . The resulting output should have the correct `AC `and `AN `values. 

The `INFO/AF` field is not updated when filtering on samples. This always stays the original `AF` that was calculated when the file was created. 

To get the current subset `AF ` do `AC/AN`  (=current subset AF)

See also these quotes from the doc, and the documentation in general: http://www.htslib.org/doc/bcftools.html#view

> -s, --samples [^]LIST
>     Comma-separated list of samples to include or exclude if prefixed with "^". The sample order is updated to reflect that given on the command line. Note that in general tags such as INFO/AC, INFO/AN, etc are not updated to correspond to the subset samples. bcftools view is the exception where some tags will be updated (unless the -I, --no-update option is used; see bcftools view documentation). To use updated tags for the subset in another command one can pipe from view into that command. For example: 

> 
>  -I, --no-update
>     do not (re)calculate INFO fields for the subset (currently INFO/AC and INFO/AN) 


> Note that filter options below dealing with counting the number of alleles will, for speed, first check for the values of AC and AN in the INFO column to avoid parsing all the genotype (FORMAT/GT) fields in the VCF. This means that a filter like --min-af 0.1 will be based ‘AC/AN’ where AC and AN come from either INFO/AC and INFO/AN if available or FORMAT/GT if not. It will not filter on another field like INFO/AF.

> frequency of alternate alleles (AF=AC/AN)

>  -q, --min-af FLOAT[:nref|:alt1|:minor|:major|:nonmajor]
>     minimum allele frequency (INFO/AC / INFO/AN) of sites to be printed.

I hope this information answers your question.

**Comment by pd3** [comment]
Hi, there is the `fill-tags` plugin for this, please check this howto http://samtools.github.io/bcftools/howtos/plugin.fill-tags.html

**Comment by chenwenan** [comment]
Thank you both for the suggestions. I think the fill-tags is the solution I am looking for.
