### ISSUE TITLE
bcftools not recognizing 'F_MISSING' in filter

### ISSUE THREAD

**Issue by LukeAndersonTrocme** [samtools/bcftools#704]
In the process of updating a pipeline that used VCFtools to use BCFtools instead. 

For reference, here is the VCFtools code that does work : 
`vcftools \
--gzvcf $outputDIR/$name.3bed.vcf.gz \
--remove-indels \
--max-non-ref-af 0.98 \
--max-missing 0.01 \
--minQ 10 \
--recode --keep-INFO-all \
--out  $outputDIR/$name.3bed_filtered`

I have been having issues with updating this to BCFtools. Namely, when i try : 
`bcftools filter -e "QUAL < 10 || F_MISSING < 0.01 || MAF > 0.98"`

I get the following error `[filter.c:1444 filters_init1] Error: the tag "INFO/F_MISSING" is not defined in the VCF header`

from the [website](https://samtools.github.io/bcftools/bcftools.html)

> variables calculated on the fly if not present: number of alternate alleles; number of samples; count of alternate alleles; minor allele count (similar to AC but is always smaller than 0.5); frequency of alternate alleles (AF=AC/AN); frequency of minor alleles (MAF=MAC/AN); number of alleles in called genotypes; number of samples with missing genotype; fraction of samples with missing genotype

>N_ALT, N_SAMPLES, AC, MAC, AF, MAF, AN, N_MISSING, F_MISSING

I'm using the data from the 1000Genome project.

**Comment by freeseek** [comment]
What version of bcftools are you using? Your command works for me.

Maybe try to re-install bcftools as follows:
```
git clone --branch=develop git://github.com/samtools/bcftools.git
git clone --branch=develop git://github.com/samtools/htslib.git
cd htslib && make && cd ..
cd bcftools && make && cd ..
/bin/cp bcftools/bcftools ~/bin/
```
(you will need libbz2-dev installed)

**Comment by LukeAndersonTrocme** [comment]
Hi Freeseek, 

Thanks for the reply, yes you are right, I just had to update my version. 

For future reference, here's what works : 

`/usr/local/bin/bcftools-1.6/bcftools filter \
--regions-file $pathToBed/BEDFILE.bed \
$inputVCF \
| /usr/local/bin/bcftools-1.6/bcftools filter \
-e "QUAL < 10 || F_MISSING > 0.01 || MAF > 0.98" \
| /usr/local/bin/bcftools-1.6/bcftools view \
-m2 -M2 -v snps --output-type z \
--output-file \
$outputDIR/$name._filtered.vcf.gz \
| /usr/local/bin/bcftools-1.6/bcftools index \
-t --output-file $outputDIR/$name._filtered.vcf.gz.tbi`

**Comment by pd3** [comment]
@LukeAndersonTrocme I'll close the issue now. Please consider contributing to the documentation if you find it insufficient. Happy to accept pull requests to the howtos or the manpage
https://github.com/samtools/bcftools/tree/gh-pages/howtos
https://github.com/samtools/bcftools/blob/develop/doc/bcftools.txt
