### ISSUE TITLE
Feature request: Please add HGVS to bcftools csq

### ISSUE THREAD

**Issue by mcgml** [samtools/bcftools#706]
Hi

The Bcftools CSQ tool is excellent! I'm using it to identify any missed double substitutions. For clinical we could do with HGVS output: http://www.hgvs.org/mutnomen

Any chance of adding this feature?

Many thanks
Matt

**Comment by pd3** [comment]
Hi, thank you for the feedback. The scope of HGVS is quite large. Can you please rephrase your question to be more specific?

**Comment by jodyphelan** [comment]
Hi there,

Great tool it has been really useful to the community!
I was wondering if there has been any more thought on this feature request? I would like to extract functional annotations in HGVS format. At the moment I have a script that takes in a VCF with the csq annotations and converts the various different types of mutations, for example:

* **Missense**: 450S>450Q to p.Ser450Gln
* **Frameshift** 4407846GGC>G to c.355_356delGC

My script does an ok job but there is an odd error here and there I have to catch and I was wondering if this information (gene nucleotide and amino acid positions) is internally stored and whether it could be output in HGVS format straight from `bcftools csq`?

Thanks,
Jody

**Comment by pd3** [comment]
Unfortunately this is currently not supported and is not nowhere near the top of the list. However, the likelihood of adding this might greatly increase if someone compiled a comprehensive list of the desired modifications and opened a new feature request.

**Comment by jodyphelan** [comment]
Ok thanks for the input. If I get this list together I'll open up a new feature request.

**Comment by anderspitman** [comment]
@jodyphelan would you possibly be able to share your script?
