### ISSUE TITLE
bcftools --ligate question

### ISSUE THREAD

**Issue by kimberlymcm** [samtools/bcftools#708]
I'm wondering how the --ligate command concatenates overlapping phased vcfs? Presumably it looks at the heterozygous calls in the overlapping region to determine the proper phasing. Is it then using some sort of min distance method to determine the proper way to concatenate?

**Comment by pd3** [comment]
That is correct. The score is calculated here
https://github.com/samtools/bcftools/blob/develop/vcfconcat.c#L301-L303

**Comment by kimberlymcm** [comment]
Thanks so much for the help. 

I think I am still a bit confused about what exactly is happening when the files are ligated. 
For example, I have ligated two files with overlapping SNPs (ex. one has SNPs 1-100, and the next has SNPs 90-200). I see that there are two "PS" Phase Set numbers throughout the output. I assume that each number is in some way referencing the phase from one of the two original files. If I don't set a --min-PQ, does the --ligate command, for each sample, look at the min distance for all the overlapping SNPs (SNPs 90-100) and decide which way to orient all of the second file's SNPs based on the first, basically by deciding whether or not to flip the phase of all the 90-200 SNPs? Or is the comparison done somehow on a SNP by SNP basis?

**Comment by pd3** [comment]
Say on output there are two files with a small overlap. The program assumes that the phasing in both files is essentially correct. Then it uses the overlapping part to decide which of the two possibilities is more likely and whether the haplotypes in the second file should be flipped or used as they are.
