### ISSUE TITLE
supplementary read handling and default read filtering in mpileup query

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#710]
Hi,

Can you let me know how bcftools mpileup handle supplementary alignments? I have aligned my paired end sequencing reads using BWA MEM. I am aware that mpileup filters all secondary alignments. As an extension to this question, mpileup discards reads with following flags (found from http://seqanswers.com/forums/showthread.php?t=19702) -

    1)are not paired
    2)not properly mapped
    3)mate is not mapped
    4)alignment is not primary
    5)reads fail quality control of vendor
    6)is marked as PCR duplicates.

Could you kindly let me if the above information is correct or point me to the program where the filtering criteria is applied?

**Comment by pd3** [comment]
Hi,

in `bcftools mpileup` this is controlled with the `-ff` and `-rf` options. The defaults are printed in the usage page `UNMAP,SECONDARY,QCFAIL,DUP`.

The defaults are set in the code at this line
https://github.com/samtools/bcftools/blob/develop/mpileup.c#L894

and applied here
https://github.com/samtools/bcftools/blob/develop/mpileup.c#L194-L196

**Comment by prasundutta87** [comment]
Thanks for the reply. What about supplementary reads? Are they used as any normal read? (of course, after checking the proper pair flag for them)

**Comment by prasundutta87** [comment]
Thank you very much. I am closing this issue.
