### ISSUE TITLE
Incorrect number of AD fields (2)

### ISSUE THREAD

**Issue by JRodrigoF** [samtools/bcftools#711]
Hi, 

A (wrong?) behaviour with bcftools merge when dealing with either ref or missing genotypes such as the below example: 

File 1 extract:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	V00055	V00082
Y	2600000	.	N	.	.	.	AN=0	GT:AD:DP:RGQ	.:0,0:0:0	.:0,0:0:0
 
File 2 extract: 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	GRC001622	GRC004194
Y	2600000	.	N	.	.	.	AN=0	GT:AD:DP:RGQ	.:0,0:0:0	.:0,0:0:0

~/bcftools-1.6/bcftools merge FILE_1.vcf.gz FILE_2.vcf.gz

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
##FILTER=<ID=LowQual,Description="Low quality">
##FILTER=<ID=NC,Description="Inconsistent Genotype Submission For At Least One Sample">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##reference=file:///mmg/jflores/resources/human_reference/Homo_sapiens_assembly19.fasta
##contig=<ID=Y,length=59373566>
##bcftools_mergeVersion=1.6+htslib-1.6
##bcftools_mergeCommand=merge FILE_1.vcf.gz FILE_2.vcf.gz; Date=Fri Nov 10 17:18:38 2017
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	V00055	V00082	GRC001622	GRC004194
Incorrect number of AD fields (2) at Y:2600000, cannot merge.

In contrast, vcf-merge behaves as expected, if I'm correct: 

vcf-merge FILE_1.vcf.gz FILE_2.vcf.gz

##source_20171110.1=vcf-merge(v0.1.14-12-gcdb80b8) FILE_1.vcf.gz FILE_2.vcf.gz
##sourceFiles_20171110.1=0:FILE_1.vcf.gz,1:FILE_2.vcf.gz
##INFO=<ID=SF,Number=.,Type=String,Description="Source File (index to sourceFiles, f when filtered)">
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	V00055	V00082	GRC001622	GRC004194
Y	2600000	.	N	.	.	.	AC=0;AN=0;SF=0,1	GT:DP:RGQ:AD	.:0:0:0,0	.:0:0:0,0	.:0:0:0,0	.:0:0:0,0

Please let me know your observations, 
Best, 
Rodrigo

**Comment by JRodrigoF** [comment]
[FILE_1.vcf.gz](https://github.com/samtools/bcftools/files/1461838/FILE_1.vcf.gz)
[FILE_2.vcf.gz](https://github.com/samtools/bcftools/files/1461839/FILE_2.vcf.gz)

**Comment by JRodrigoF** [comment]
[FILE_1.vcf.gz](https://github.com/samtools/bcftools/files/1461842/FILE_1.vcf.gz)
[FILE_2.vcf.gz](https://github.com/samtools/bcftools/files/1461843/FILE_2.vcf.gz)

**Comment by pd3** [comment]
This is expected behavior. The AD tag is defined as `Number=R` in the header, therefore for records with `REF=N` and `ALT=.` there is only one allele and there should be only one value, that is `AD=0`, not `AD=0,0`.
