### ISSUE TITLE
Phred score ROH

### ISSUE THREAD

**Issue by esvw** [samtools/bcftools#714]
Hi,

When using BCFtools to calculate runs of homozygosity (ROH) a Phred-score (shown as 'Quality (fwd-bwd phred score)') is given. How should I interpret this Phred-score? Is there a any threshold to use?

Thanks!

esvw

**Comment by pd3** [comment]
In theory the score could be interpreted as the probability of the state assignment being incorrect. In practice it is just a score, bigger values indicate a more confident call. 

The values come from the forward-backward algorithm. I wouldn't trust the probabilistic interpretation much, already the values that enter the calculation are only crude approximations. Therefore also the threshold will depend on your data, best is to check the calls visually to learn what works best.
