### ISSUE TITLE
comparing multiple call files to a baseline file

### ISSUE THREAD

**Issue by drowl001** [samtools/bcftools#718]
Hello all,

I am using bcftools i sec command to compare my calls against a variant baseline file but I have multiple call files(>400) which i want to individually compare against the baseline.Is there a way to do this without having to manually run the command each time for every call file?
I am a newbie in programming and bioinformatics and would appreciate a point in the right direction on this one.
Thank you!

**Comment by pd3** [comment]
Hi, you an achieve this by writing a simple script. However, this is beyond the support we can provide, you'll find many scripting tutorials online.
