### ISSUE TITLE
query vector subscript error

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#723]
Hello,

I'm querying the ANN format tag created by snpeff. I don't seem to be able to pull out the first element in the vector. The element itself is a vector that I can parse using awk.

```
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO'">

bcftools query -f '%ANN{0}\n' tmp.vcf
todo: type 7 
```

**Comment by pd3** [comment]
Added now, please try it out.

**Comment by XRCHAM** [comment]
I have the same problem, and I tried as follows, and still gave same problem.
`bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/ANN{0}\t%CHROM:%POS\n' tmp.vcf`
or
`bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%ANN{0}\t%CHROM:%POS\n' Merge_S1-8.AG-snpEff.vcf`
todo: type 7

**Comment by pd3** [comment]
What version of bcftools are you running? (`bcftools --version`) I suspect you have an older version, please upgrade to the latest, that should fix the problem. http://samtools.github.io/bcftools/howtos/install.html
