### ISSUE TITLE
a random last line attached after view

### ISSUE THREAD

**Issue by huwenhuo** [samtools/bcftools#725]
I used below for split vcf files:
`bcftools view -c1 -Oz --compression-level 0 -s sampleName -o outputfile big_vcf.vcf`

I got some wired results at the end of the output files, there is an extra line:
`õ<80>^X<85>^Ë^@^@^_<8b>^H^D^@^@^@^@^@ÿ^F^@BC^B^@^[^@^C^@^@^@^@^@^@^@^@^@`

Any idea of this?

**Comment by mcshane** [comment]
Are you trying to get uncompressed VCF? If so, you should use `-Ov` and not bother setting `--compression-level` (the default) instead. Guessing what you are seeing is the BGZF EOF line?
