### ISSUE TITLE
install: cannot stat ‘bcftools’: No such file or directory

### ISSUE THREAD

**Issue by sjackman** [samtools/bcftools#727]
`make -j install` fails with
```
install: cannot stat ‘bcftools’: No such file or directory
```
A workaround is to run `make -j` before `make -j install`. Ideally `make -j install` would not fail.
See the failed build at
https://travis-ci.org/Homebrew/homebrew-science/builds/319874345#L2609
and related issue at https://github.com/Homebrew/homebrew-science/pull/6510

**Comment by pd3** [comment]
Hopefully this should resolve it. Thank you for reporting

**Comment by sjackman** [comment]
Thanks, @pd3!
