### ISSUE TITLE
output --hapsample

### ISSUE THREAD

**Issue by mmalvarezub** [samtools/bcftools#729]
Hi, I have a .vcf file with phased genotypes whose lines look like this: 

1    691545    1:691545    A    T    .    .    PR    GT    0/0    0/0    0/0 (etc.)

Trying to convert it into .haps/.sample, I first used this command:

./bcftools convert --hapsample input.vcf -o output

But it does not do anything. If instead I add the --vcf-ids flag after the --hapsample one:

./bcftools convert --hapsample --vcf-ids input.vcf -o output

I get a pair of .haps/.sample files, but the problem is that the .haps lines look like this:

1    1:691545    691545    A    T   0*    0*    0* ...

All the individuals' haplotypes are either a '0' or a '1' plus an '*'. Do you have any idea of what can I be doing wrong?

Thanks, regards,

Miguel

**Comment by winni2k** [comment]
Hi Miguel,
The genotypes in your VCF are unphased as indicated by the slash between alleles (i.e. `0/0`).  The haps format allows for unphased alleles, but requires annotation with a `*`.  See the documentation in [`convert.c`](https://github.com/samtools/bcftools/blob/develop/convert.c#L714-L743).

Are you sure your genotypes are phased? If you are really, really sure, then you may want to replace all `/` by `|` in your VCF and you should get the HapSample file you expect.

HTH

**Comment by mmalvarezub** [comment]
Oh, right, that must be the problem then, my original vcf files are phased and then I removed some SNPs from them using PLINK and the resulting files are not phased anymore, I'll work on that. Thanks!
