### ISSUE TITLE
Converting ~500 23andMe files to VCF format then Merging

### ISSUE THREAD

**Issue by heatherself18** [samtools/bcftools#731]
Does any have a script/know how to convert a large number of 23andMe files to a VCF format and then merge those files? 

I'm trying to prepare a large amount of data to send to the Sanger Institute for imputation.

I can convert one 23andMe file at a time using:

bcftools convert -c ID,CHROM,POS,AA --tsv2vcf sample#.txt - human_g1k_v37.fasta -s Sample# -Oz -o #.vcf.gz

**Comment by winni2k** [comment]
`bcftools merge`?

**Comment by heatherself18** [comment]
I know how to merge files one at a time, I need a way to convert then merge multiple files at once.

**Comment by winni2k** [comment]
Hmm, I still don't understand what the problem is. Can you convert each file separately and then merge all the converted files using a single `bcftools merge` command? (The merge command takes several input files at once)

**Comment by pd3** [comment]
@heatherself18, we exchanged some emails about this a while ago. This is a script example that does what you need. If it still does not make sense, please google for "how to write a shell script".

````
# The wildcard *.txt selects all files in the current directory that
# end with ".txt". If your input files are named differently, you
# need to change it accordingly.
ls *.txt | while read FILE; do

   # Print the command, do not execute
   echo "bcftools convert --tsv2vcf $FILE -f ref.fa -s $FILE -Ob -o  $FILE.bcf"

   # Execute the command. If it does not work, try to run it manually
   # first. Only after understanding what the problem is, edit 
   # and run the script again
   bcftools convert --tsv2vcf $FILE -f ref.fa -s $FILE -Ob -o $FILE.bcf

   # Create index, necessary for the merging step
   bcftools index $FILE.bcf 

   # Create a list of files to merge. Before running the script,
   # make sure the file does not exist or is empty. The latter
   # can be assured by putting a separate "> file.list" command
   # before the start of the loop.
   echo $FILE.bcf >> file.list
done

# Merge
bcftools merge -l file.list -Ob -o multisample.bcf
````

**Comment by heatherself18** [comment]
Thank you! 

I had lost our e-mail correspondence.
