### ISSUE TITLE
bcftools csq recompose variants that are not within same codons

### ISSUE THREAD

**Issue by haochenl** [samtools/bcftools#732]
I run the NA12878 phased variant vcf file using bcftools csq 1.6 on GRCh37. Here is a BCSQ example on chromosome 1: 

BCSQ=\*frameshift|RP11-156E8.1|ENST00000607453|protein_coding|-|276ALSPFRATTLALGEDQRPRLPPGPRPCPSRPEAGAGLVPGLACCFITRSPTPPFPYFSSIWGQHARAHTPRPLLSCLCDVALLDFCC*>268PVPASRHDPRAGGRPEAPSAPRPPALSLQTRGRSRTCPGPSMLLHHTVPNPSFPLFLIHLGTARARTHPSPPPVLFVRRGVARFLLL|**245133489T>G+245133539A>G+245133549GGC>G**

The three variants in **bold** are 40 bp and 10 bp apart for each pair. I couldn't figure out what are the principles that those variants would be recomposed together.

**Comment by pd3** [comment]
The transcript is on the reverse strand, so everything after a frame shifting indel is part of the same compound variant.

**Comment by haochenl** [comment]
Thanks for the clarification! It is awesome that you guys do annotations on the transcript level :)

**Comment by haochenl** [comment]
By the way, there must be a criteria when you stop searching after the frame shift indel. Is there a distance cutoff or anything like that?

**Comment by haochenl** [comment]
Hi, I recently discovered a similar case of re-composition of distant SNV into MNV which is not involved with frameshift (on chromosome 1 as well):

BCSQ=missense|TOR1AIP1|ENST00000271583|protein_coding|+|146MTRRGLRDSHSSEEDEASSQTDLSQTISKKTVRSIQEAPAVSEDLVIRLRRPPLRYPRYEATSVQQKVNFSEEGETEEDDQDSSHSSVTTVKARSRDSDESGDKTTRSSSQYIESFWQSSQSQNFTAHDKQP>146TTRRGLRDSHSSEEDEASSQTDLSQTISKKTVRSIQEAPAVSEDLVIRLRRPPLRYPRYEATSVQQKVNFSEEGETEEDDQDSSHSSVTTVKARSRDSDESGDKTTRSSSQYIESFWQSSQSQNFTAHDKQR|179852074T>C+179858444G>A+179876988C>G

I am not sure why these three SNVs are composed together. My initial inspection is that this 179858444G>A variant happens to be at a splice site, which might lead to an exon skipping event. Is bcftools csq trying to predict splice variant as well?

**Comment by pd3** [comment]
We don't know the effects on the splice sites well, so we don't try to make the prediction. This was a bug and should be now fixed.  Thank you for reporting and testing.
