### ISSUE TITLE
bcftools adds dictionary without lengths during recompression -> breaks GATK4 runs

### ISSUE THREAD

**Issue by nyl2002** [samtools/bcftools#733]
bcftools view -O z -l 0 All_20170710.vcf.gz -o All_20170710_u.vcf.gz

 -I was tried to fix this behavior

Quite frustrating that a mere recompression changes file content in a way that breaks things, such as GATK4 Haplotypecaller.

And: Unpacking and removing will not help, because upon recompression, the erroneous dictionary will be added again.
bgzip seems not to be able to do -0 or -1 so it is quite annoying that this long awaited way to change compression level (to including 0) is broken.

In times of fast lz4 disk (de)compression (zfs etc.) it is quite frustrating to be forced into using a CPU 
hungry compression algorithm like bgzip that wastes resources on every file read (since indexing and using uncompressed .vcf in GATK4 etc. is not possible).

The only solution seems to be to manually add a dictionary with lengths, which will break things again on different hs37/hs38 versions, because GATK4 will break on contig or length differences.

There is probably a good reason why this much used file does not include a dictionary in the header.

Even running -h to write the header only, also writes the dictionary. That is even more unintuitive.

**Comment by lh3** [comment]
> There is probably a good reason why this much used file does not include a dictionary in the header.

It is dbSNP's fault for not adding contig lines. I don't see a good reason for that.

> In times of fast lz4 disk (de)compression (zfs etc.) it is quite frustrating to be forced into using a CPU hungry compression algorithm like bgzip that wastes resources on every file read

Have you done a benchmark? For VCFs, often the performance bottleneck is at parsing, not at decompression. This is particularly true for GATK/etc because its parser is much slower than the htslib parser. In general, if performance is a concern, use BCF.

That said, it seems that bgzip (v1.4) does not allow to tune the compression level at the command line. Ideally, recompression should be done with something like this:
```
bgzip -c -0 ori.gz > ori-0.gz
```

**Comment by nyl2002** [comment]
bgzip -c -0 ori.gz > ori-0.gz
>That is exactly what I have been looking at for a while.

> It is dbSNP's fault for not adding contig lines. I don't see a good reason for that.
I think it is because GATK4 and others can be prickly about contig mismatch, when you use different reference versions such as hs38, hs38a, hs38DH, hs37d5 etc.

I have solved it with a script for now handling the header separately when a dict was added.

> This is particularly true for GATK/etc because its parser is much slower than the htslib parser. 
Agree. bcftools parses clinvar etc. really fast.

I currently have many BAM versions with e.g. different references from the same persons though, since I'm experimenting with GATK4, DeepVariant and I'm very interested in alt-contigs in RCCX/MHC class III/HLA, which is unfortunately apparantely missing from IMGT/HLA.

Between cloud runs I pack the differently aligned BAMs ~25x with interleaving etc. and gzip becomes a big slowdown for that.

And I would like to use the 0 level as above also exactly to clarify benchmarking when I try different spark configurations.

**Comment by lh3** [comment]
> I think it is because GATK4 and others can be prickly about contig mismatch, when you use different reference versions such as hs38, hs38a, hs38DH, hs37d5 etc.

Using an unmatched reference build will lead to fatal errors downstream. Contigs build and naming must match.

> Between cloud runs I pack the differently aligned BAMs ~25x with interleaving etc. and gzip becomes a big slowdown for that.

As long as you parse VCF with GATK, parsing will be the bottleneck, not decompression.

**Comment by pd3** [comment]
The `bcftools reheader -f, --faidx` option can be used to update the contig names and lengths when necessary, see https://github.com/samtools/bcftools/commit/9fb878af1a262be8676e0bd754adb9b560d809e0. Closing the issue now.
