### ISSUE TITLE
Haplotype assignment is not correct in bcftools csq

### ISSUE THREAD

**Issue by haochenl** [samtools/bcftools#734]
These two variants (from the NA12878 phased vcf file) are annotated by bcftools csq haplotype mode:
`1       175129945       .       TCTTCTTCT       T       467.29       PASS       BCSQ=@175129954       GT:PS:PQ:JQ:BCSQ       0|1:169895821:62:255:3`
`1       175129954       .       TG       T       467.29       PASS       BCSQ=inframe_deletion|KIAA0040|ENST00000545251|protein_coding|-65NKKKK>65KK|175129945TCTTCTTCT>T+175129954TG>T       GT:PS:PQ:JQ:BCSQ       0|1:169895821:38:255:63`

Here is the haplotype assignment queried by "bcftools query -f'[%CHROM\t%POS\t%SAMPLE\t%TBCSQ\n]'":
`1       175129945       NA12878       @175129954       @175129954`
`1       175129954       NA12878       inframe_deletion|KIAA0040|ENST00000545251|protein_coding|-|65NKKKK>65KK|175129945TCTTCTTCT>T+175129954TG>T       inframe_deletion|KIAA0040|ENST00000545251|protein_coding|-|65NKKKK>65KK|175129945TCTTCTTCT>T+175129954TG>T`

Since both of the variants are phased. The first haplotype should the reference sequence, which is "." in the third column of the query. Is there any documentation about the logic behind the bitmask BCSQ score in the sample field. I can try to interpret by myself. Thanks!

**Comment by pd3** [comment]
What options did your run the program with? The NA12878 phased VCF contains unphased genotypes. I suspect you used `-p m`, which merges **all** genotypes into a single haplotype. You probably wanted to use `-p R`.

The BCSQ bitmask is described in the paper: it interleaves each haplotype so that when stored in BCF format, only 8 bits per sample are required for most sites.

**Comment by haochenl** [comment]
Thanks for the response! You are right that I used `-p m` as the parameter which merged the haplotypes. Actually, the parameter that kind of fits my purpose is `-p s`. And I got the expected haplotypes in the result from "bcftools query". I am hesitated about using `-p R`. As in the documentation, it will remove reference allele in the genotype (0/1 -> 1|1) and translate unphased genotypes to phased ones (1/2 -> 1|2). In that case, I wonder if the result is going to represent the true haplotype information or not. Something I would like to include is to translate unphased homozygous genotype to phased one, such as 1/1 -> 1|1. I will be nice that can be an option in bcftools csq.

**Comment by haochenl** [comment]
For the bitmask, I will check the paper. Thanks!

**Comment by pd3** [comment]
This was actually the intention, homozygous genotypes should be of course considered phased. However, checking the program, I found a bug. This is now fixed by b5c3358, `-p s` should now work as expected.

**Comment by haochenl** [comment]
Awesome! Thanks for the update!
