### ISSUE TITLE
bcftools merge  on QUAL field

### ISSUE THREAD

**Issue by ytguojian** [samtools/bcftools#735]
Hi,
I have merged 30 vcf files with bcftools merge option. However, I do not know how it calculate the QUAL value in the merged vcf file. Could you help me? Does it consider the QUAL values in separately VCF files that used for merging?
I want to do some filtering based on this value, but I do not know how it comes.

Cheers,

**Comment by pd3** [comment]
In general case there is not enough information to calculate QUAL the same way a variant caller would when merging VCFs, therefore the maximum QUAL is used.
https://github.com/samtools/bcftools/blob/develop/vcfmerge.c#L857
