### ISSUE TITLE
How to filter out mixed SNP/spanning deletion variants?

### ISSUE THREAD

**Issue by WimSpee** [samtools/bcftools#736]
Hi, 

I used to use this bcftools command to select for pure SNP variants (i.e. SNP only, also no mixed variants.)

`bcftools view --exclude-types indels,mnps,other`

When filtering VCF files produced by GATK4 this command does not filter out SNP+spanning deletion variants. 
https://software.broadinstitute.org/gatk/documentation/article.php?id=6926

```
Chr_14  32413   .       C       T,* 
Chr_14  105801  .       C      *,G
```

Also exluding `bnd `type variants does not help. 
`bcftools view --exclude-types indels,mnps,other,bnd`

Is there another way to also exclude this type of mixed variants?  Or shouldn't this type of variants fall under the existing `indels` type?

Thank you.

**Comment by pd3** [comment]
Hi,

just pushed a commit https://github.com/samtools/bcftools/commit/db2e2b66f4164e650d627297375c60dfdcca7ad6 which allows to filter these records using
````
-e'ALT="*" || type!="snp"'
````
As described in the commit message, this should be changed in htslib eventually.

**Comment by WimSpee** [comment]
Thank you.
