### ISSUE TITLE
norm -d none not recognized 

### ISSUE THREAD

**Issue by dantaki** [samtools/bcftools#738]
According to the documentation here https://samtools.github.io/bcftools/bcftools-man.html#norm I should be able to supply `none` to the `-d` argument 

```
bcftools merge -0 -m all trio1.bcf trio2.bcf trio3.bcf | \
    bcftools norm -m -any | \
    bcftools norm -Oz -f GRCh38_full_analysis_set_plus_decoy_hla.fa -d none >merged.vcf.gz
```

I get this error 

```
The argument to -d not recognised: none
```
I also get this error
```
$ bcftools query merged.vcf.gz -f '%ID\n' --collapse none
The --collapse string "none" not recognised.
```
this is the version I am running 
```
$ bcftools --version
bcftools 1.6
Using htslib 1.6
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
I would like to use the `none` option since 

>  only records with identical REF and ALT alleles are compatible 

I have to account for both the position and both ref and alt alleles, currently `-d both` only outputs the first variant according to position.

Thanks for the help

**Comment by pd3** [comment]
This is now resolved by the commit above. Thank you for reporting the inconsistency in function and documentation.
