### ISSUE TITLE
bcftools view inclusion depends on previous VCF line

### ISSUE THREAD

**Issue by ctsa** [samtools/bcftools#739]
I'm trying to use bcftools 1.6 to select all records in a VCF where at least one sample  has both FORMAT/GT == "1/1" and FORMAT/FT == "PASS". After getting eratic behavior from bcftools I've produced a simple testcase to investigate. The following command shows a failure to select the SNV at position "61066" which seems like it should pass the inclusion criteria:

```bash
gzip -dc foo3.vcf.gz | bcftools view -H -i 'FMT/GT=="1/1" & FMT/FT=="PASS"
```

...but after simply removing the SNV record which preceeds it, the SNV at 61066 can be selected by the same bcftools command:

```bash
gzip -dc foo3.vcf.gz | awk '$2!="60988"' | bcftools view -H -i 'FMT/GT=="1/1" & FMT/FT=="PASS"
```

Example VCF attached here:  [foo3.vcf.gz](https://github.com/samtools/bcftools/files/1696833/foo3.vcf.gz)

Am I misunderstanding how the include expressions are supposed to work in this case?

**Comment by pd3** [comment]
Can you please check if the bug is present in the latest github version? Hopefully this is now fixed already.

**Comment by ctsa** [comment]
It is fixed on master. Looking forward to seeing this in an upcoming release.
