### ISSUE TITLE
bcftools consensus not outputting IUPAC code

### ISSUE THREAD

**Issue by dkoubino** [samtools/bcftools#740]
I tried to use bcftool consensus to get fasta files for each sample from the dataset based on the reference sequence and a .vcf file with the variants. I have a reference fasta and .vcf file obtained by dDocent pipeline.
I used this command:
bgzip file.vcf
tabix file.vcf.gz
bcftools consensus -i -s sampleID -f reference.fasta file.vcf.gz > output.fasta
However, I did not get the IUPAC code, nor both alleles. When I set the option for allele one and allele two, I get identical sequences, despite in the .vcf I can see two variants at this position. I noticed the problem was reported before, but I did not find a reply giving the solution for this. I.e. how to get the output with IUPAC code for heterozygotes or two alleles. Many thanks.

**Comment by pd3** [comment]
You probably intended the `-I, --iupac-codes` switch instead of `-i, --include <expr>`? If this was not the problem and is only a typo, a small test case would be very helpful.

**Comment by dkoubino** [comment]
When I used the -I, I got this:
consensus: invalid option -- 'I'

About: Create consensus sequence by applying VCF variants to a reference fasta
       file. By default, the program will apply all ALT variants. Using the
       --sample (and, optionally, --haplotype) option will apply genotype
       (or haplotype) calls from FORMAT/GT. The program ignores allelic depth
       information, such as INFO/AD or FORMAT/AD.
Usage:   bcftools consensus [OPTIONS] <file.vcf>
Options:
    -f, --fasta-ref <file>     reference sequence in fasta format
    -H, --haplotype <1|2>      apply variants for the given haplotype
    -i, --iupac-codes          output variants in the form of IUPAC ambiguity codes
    -m, --mask <file>          replace regions with N
    -o, --output <file>        write output to a file [standard output]
    -c, --chain <file>         write a chain file for liftover
    -s, --sample <name>        apply variants of the given sample
Examples:
   # Get the consensus for one region. The fasta header lines are then expected
   # in the form ">chr:from-to".
   samtools faidx ref.fa 8:11870-11890 | bcftools consensus in.vcf.gz > out.fa

**Comment by pd3** [comment]
You are running an older version of bcftools. Can you try with the latest http://samtools.github.io/bcftools/? If the problem persists, we will need a small test case to reproduce the problem.

**Comment by pd3** [comment]
Thank you for the test case. This commit should fix it, please let me know if not.
