### ISSUE TITLE
counts of hets or homo genotypes

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#743]
I'm extracting sites with specific genotypes i.e.  homozygous alternates (AA).
`bcftools-dev view -O z  -g hom -m 2 -t ^X,Y,MT -i 'DP>2670 & GT="AA" & AC<100 & AD[0]==0 & AD[1]>=10' $vcf`

Is there a way to set all non AA genotypes to missing? 

Is there a way to get counts of genotype class by site i.e. n_AA, n_AR, n_RR?

**Comment by dwaggott** [comment]
Ah, the `fill-tags` plugin adds AC_hom tags. That helps. I'll keep the issue open regarding changing genotypes that mean certain criteria.

**Comment by pd3** [comment]
Yes, it is possible:
````
bcftools +setGT file.vcf -- -t q -n . -i 'GT!="AA" 
````
The latest github version might be necessary for this, there were some bugs addressed recently, plus just pushed a commit which makes also the behavior of `-e` consistent with `-i`.

**Comment by dwaggott** [comment]
Very nice, I'll test and close.
