### ISSUE TITLE
bcftools has aversion to targets-files in vcf format where IDs start with number ?

### ISSUE THREAD

**Issue by ces** [samtools/bcftools#745]
When running bcftools mpileup and giving a vcf as a  --targets-file (which is very useful) I found it skipped lines (missing from output) where the ID for snp started with a number. Obviously was easily fixed by adding a letter to the start of the relevant IDs. Just thought I'd mention it as I didn't think it was illegal for an ID to start with a number, but possible I'm not up to date with the current VCF spec.

**Comment by pd3** [comment]
Hi, thank you for reporting this problem. Could you please provide a small example for testing? The cases I came up with seem to be working fine, so there is probably more to it..

**Comment by pd3** [comment]
Was able to reproduce the problem in the end. This is now fixed.
