### ISSUE TITLE
Problem of annotation when a start_lost is found

### ISSUE THREAD

**Issue by ediezben** [samtools/bcftools#746]
Hi, 

I am in the process of creating a pipeline which takes the csq annotation of a certain amount of vcfs and a protein coding sequence and generates the protein haplotype sequences for this specific gene for all the individual samples by sequentially performing the aminoacid changes found in the vcf for the gene. I found an issue I can't seem to get over. 

Apparently, in some instances the annotation of the start_lost event doesn't include an aminoacid change in the CSQ tag:

PvP01_02_v1	704283	.	attttttttttttttttttttttttt	atttttttttttttttt	83.5	.	INDEL;DP=52;VDB=0.0437;AF1=0.5;AC1=1;DP4=8,2,7,1;MQ=46;FQ=86.5;PV4=1,1,1,1;**BCSQ=start_lost|PVP01_0216200|PVP01_0216200|protein_coding|-**	GT:PL:GQ:BCSQ	0/1:121,0,167:99:3

But the following changes going downstream the protein sequence seem to have taken into account the shortening of the protein caused by this start_lost event, assigning a modified POS to the aminoacid change:

PvP01_02_v1	704115	.	T	C	72	.	DP=92;VDB=0.0308;AF1=0.5;AC1=1;DP4=35,40,7,7;MQ=49;FQ=75;PV4=1,1,6.7e-23,1;BCSQ=missense|PVP01_0216200|PVP01_0216200|protein_coding|-|**57N>54S**|704115T>C	GT:PL:GQ:BCSQ	0/1:102,0,255:99:3

Original aminoacid sequence: 
MGRDIKEFYNLRHRYLDKRKETNINILKSTRNKITCNNDVAVTNASTHLRENK**D**EC_N_KNAATSANKVKAQRKTAGFRK
Position 54 is **D** because the first deletion of three aminoacids by the start_lost event is not annotated in aminoacid change but taken into account for downstream events, _N_ is still in position 57 in the sequence.
This is the immediate change after the start_lost, so when I try to extract the aminoacid corresponding to 54 is not an N because the start_lost event didn't specify the aminoacid change that should be implemented. Is there any plan on fixing this? 

Thanks a lot for the functionality, it is great.

**Comment by pd3** [comment]
Hi, this is a problematic case. The program makes the simplifying assumption that when the start is lost, the protein is not made and it does not make sense to speak about aminoacid sequence anymore. However, it will still report the downstream variants as if the start was intact, because the variant could be a false call. The program should recognize cases where the start codon is disrupted by a deletion but the start is retained. I don't think this is your case though.

**Comment by ediezben** [comment]
Hi pd3,
thanks for replying to my query, I understand that it is a problematic case as it is even quite hard for me to understand what the impact of losing the start would be biologically, my question was whether if this is treated as either a complete lose of the gene or a false call in the start of the gene, wouldn't it then make more sense to keep the calls as if the start aminoacid was intact? because at the moment it is treating it as if it had lost 3 aminoacids in the start (aminoacid 57 is considered now 54). 
That way it would make the recreation of the protein sequence actually possible from the information of the VCF in case the start lost is considered a false call, while at the moment gathering all the information for that specific gene, it is not possible to recreate the protein sequence as the calls don't match the sequnce.
At the moment I am just avoiding this sample for this specific gene as I am not sure whether this is real in my data, but just thought might be of relevance for other cases.
Thanks again.
Regards,
Ernest

**Comment by pd3** [comment]
You are right, the behavior you suggested is preferable. This commit  4119a24 hopefully resolves the issue. Please try it out and let me know if it does not.
