### ISSUE TITLE
Feature request:  automatically convert 1/chr1 or warn about non-matching contig names

### ISSUE THREAD

**Issue by alanhoyle** [samtools/bcftools#747]
I have a number of VCFs that were generated with third-party tools, and they have contigs named "chr1", "chr2", etc.  I also have other VCFs for reference data (e.g. dbSNP VCFs) that label those same contig "1", "2" etc.  It would be useful if BCFtools either did an automatic conversion of the chr1/1 into synonyms, or it gave a warning when there was no overlap between the contig names in the VCF files.  

E.g. bcftools gtcheck gives a whole lot of lines that look like this:
  `CN	0.000000e+00	0.000000e+00	0 SampleOne 0`
  `CN	0.000000e+00	0.000000e+00	0 SampleTwo 1`

which is not useful.  

I realize that it's not complex to reprocess the data to either add or remove a 'chr' as appropriate, but with hundreds/thousands of VCFs, it's a pain to modify, bgzip, and tabix everything.  

At the very least, if there is no match between any of the CHROM columns, throwing a warning would be useful.

**Comment by pd3** [comment]
There are many other reference files out there for different species which use completely different chromosome naming conventions. There were proposals to include a dictionary of synonymous contig names in the VCF header, but this has not been codified yet.

I am afraid for now the solution would be to add an additional step to your pipeline. For example you can use `bcftools index -s` to get the chromosome names and then `bcftools annotate --rename-chrs` to fix the naming if necessary.
