### ISSUE TITLE
piping into vcf2sex

### ISSUE THREAD

**Issue by NatShar** [samtools/bcftools#749]
Hi,
Is it possible to pipe into vcf2sex? I have to process vcfs with overloaded INFO field, so I would love to conduct the check without making intermediate file with dropped INFO.

I tried the following string
bcftools annotate -x INFO file.vcf.gz | bcftools +vcf2sex - -- -b X:60001-2699520 -g GT -v 
got the error: not compressed with bgzip
with addition of  '| bgzip -c '  error became: could not load index

I would greatly appreciate any suggestions on the problem.

**Comment by pd3** [comment]
Hi, the `vcf2sex` plugin was deprecated and replaced with `guess-ploidy`
