### ISSUE TITLE
Documentation and filtering expression

### ISSUE THREAD

**Issue by Cashalow** [samtools/bcftools#750]
Hello, 

I am using bcftools version 1.6=0 from bioconda. I am trying to filter genotypes based on FORMAT/AD and FORMAT/DP.

According to the documentation, for a single sample present in my vcf, this expression:

```
gt="a" & MAX(FORMAT/AD[0:*])/FORMAT/DP <0.75
```

Should select sites with an ALT genotype whose alternative observation counts is less than 75% of the total coverage of the allele.

However, the notation `FORMAT/AD[0:*]` is not accepted by bcftools filter, with the error : 

```
Could not parse the index: AD[:*]
```
The error happends whether I try on a .vcf file or an index .vcf.gz file.

And if I try 

```
gt="a" & MAX(FORMAT/AD[*])/FORMAT/DP <0.75
```
This does not select the MAX value of all the value of FORMAT/AD but actually the first one (which ends up by filtering every of my position since the reference count is always lower than 0.75. 

Am I running my filtering expression wrong ? I am confused about the documentation but the one I am referring to ( https://samtools.github.io/bcftools/bcftools.html ) should apply to 1.6 ?

Thanks a lot for your help !

**Comment by pd3** [comment]
Hi, you'll need to upgrade to the latest version in order to use this feature. It was added to a very late 1.6, just before 1.7 release was made.

**Comment by Cashalow** [comment]
Wow okay thanks a lot ! 1.7 on its way to bioconda then.
