### ISSUE TITLE
Bcftools consensus performing unexpectedly 

### ISSUE THREAD

**Issue by skbrimer** [samtools/bcftools#752]
Hello bcftools team, 

I work with segmented viruses and for my ref.fa file its actually 10-12 individual fasta segments from genbank in one file. I use to be able to use `cat ref.fa | bcftools consensus vcf.gz > cns.fa` to get the consensus written to all the segments. I have also tried calling `bcftools consensus -f ref.fa -o cns.fa vcf.gz` and get the same output. My expected output is all the segments in the new cns.fa file, however I now seem to only get back the last one on the list. 

Is there a new way I need to call consensus to get it to append all?

Thank you, 
Sean

**Comment by pd3** [comment]
Any chance you could provide a small test case to demonstrate and debug the problem?

**Comment by skbrimer** [comment]
Sure! in the zip, there are 2 files, the reference and the reads that mapped, I tried to just give you all the files but it was too large. However this will allow you to recreate the issue. 

[bcftools support.zip](https://github.com/samtools/bcftools/files/1785494/bcftools.support.zip)

**Comment by pd3** [comment]
Thank you for the files, but I was expecting the inputs to the `consensus` command: the reference and the VCF file.

**Comment by skbrimer** [comment]
Sorry, I didn't understand please find them attached. 
[bcftools_troubleshoot.zip](https://github.com/samtools/bcftools/files/1793876/bcftools_troubleshoot.zip)

**Comment by pd3** [comment]
The problem is that `bcftools` don't like blank lines in your fasta file. I am not sure if they are allowed or not. In any case you can remove the blank lines and then it should behave as expected:
````
cat ref.fasta | grep -v ^$ | bcftools consensus file.vcf.gz
````

**Comment by skbrimer** [comment]
I apologize for my late response, Thank you for this I worked perfectly! I thought I had removed the blanks but apparently not. Thank you for the help!

**Comment by tolot27** [comment]
Why not fixing bcftools? Shall I open a separate issue for that?

**Comment by pd3** [comment]
If you think this is a problem, please open a new issue for this. Cheers.
