### ISSUE TITLE
Documentation for gtcheck is out of date

### ISSUE THREAD

**Issue by wac** [samtools/bcftools#753]
The documentation for the gtcheck command seems to refer to the CN block,  which is now flagged as deprecated,  and SM fields which are not present at all?  Is there any documentation describing the output or what the command is actually doing?  It appears to do pairwise comparisons of the genotypes in one file or all the genotypes from a query file vs the ones in the reference (is this the intended usage?)  
I am inferring the main ERR block refers to the discordance (maybe a normalised version of the CN, Discordance? Or maybe just straight up % differing genotypes?) ,  CLUSTER blocks refer to potentially related samples?  (maybe related to error range given by the --cluster command?  Range selected to be ... sibling/parent level?),  some kind of dot plots where the branch weights are the discordance and then for the further up branch points....something else? Average?  Max Error? of the overall group? All samples below in the tree? With some kind of complete or average clustering?

Thanks for any information or any references/descriptions!

**Comment by pd3** [comment]
Hi, sorry about the lack of documentation.

The program checks sample identity and can operate in two modes. If the `-g` option is given, the identity of the `-s` sample from the query file is checked against the samples in the `-g` file. Without the `-g` option, multi-sample cross-check of samples in the query file is performed.

`ERR` is the error rate, calculated as `ERR = nDifference / nTotal`. 

In the cross-check mode, related samples and outliers can be identified by clustering the samples by error rate. This is what the `CLUSTER` output is about. A simple hierarchical clustering based on minimization of standard deviation is used. This is useful to detect identity swaps, for example in a situation where one sample has been sequenced in multiple runs.

**Comment by wac** [comment]
Thank you for the very detailed and clear answer!
