### ISSUE TITLE
bcftools merge produces duplicate records

### ISSUE THREAD

**Issue by everestial** [samtools/bcftools#754]
I followed the comments on this issue https://github.com/samtools/bcftools/issues/166
But, the problem with duplicate record still exists with `bcftools`.

I am trying to merge several single sample VCFs which comes our after running "phaser" https://github.com/secastel/phaser/tree/master/phaser .  Below are the codes I tried and I have also attached small files, so you may replicate the problem.

**When I try `bcftools merge` on only four samples (ms01e, ms02g, ms03g, ms04h) the output VCF's doesn't have any duplicate record.**
    
     $ bcftools merge ms01e_phased.vcf.gz ms02g_phased.vcf.gz ms03g_phased.vcf.gz ms04h_phased.vcf.gz -O v -o RBphased_variants.FourSamples.Final.vcf
    # A record from the file "RBphased_variants.FourSamples.Final.vcf"
    2	14691373	.	A	.	1153.31	PASS	BaseQRankSum=2.02;ClippingRankSum=0;ExcessHet=3.0103;FS=1.098;InbreedingCoeff=-0.0861;MQ=58.74;MQRankSum=-2.459;QD=19.22;ReadPosRankSum=-0.466;SOR=0.96;DP=68;AN=8	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC:PM	0/0:4:4:0:0:0/0:.:.:0/0:.:.	0/0:7:7:18:0:0/0:.:.:0/0:.:.	0/0:4:4:12:0:0/0:.:.:0/0:.:.	0/0:2:2:3:0:0/0:.:.:0/0:.:.
    2	14691374	.	A	.	1320.25	PASS	BaseQRankSum=-1.049;ClippingRankSum=0;ExcessHet=0.2929;FS=0;InbreedingCoeff=0.4006;MQ=55.35;MQRankSum=0;QD=33.01;ReadPosRankSum=-0.671;SOR=0.892;DP=44;AN=2	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC:PM	0/0:4:4:0:0:0/0:.:.:0/0:.:.	./.:7:7:.:0:./.:.:.:./.:.:.	./.:0:0:.:0:./.:.:.:./.:.:.	./.:0:0:.:0:./.:.:.:./.:.:.

**But, when I merge 2 extra file (MA605 and MA611) I run into duplicate record problem.**

    $ bcftools merge ms01e_phased.vcf.gz ms02g_phased.vcf.gz ms03g_phased.vcf.gz ms04h_phased.vcf.gz MA605_phased.vcf.gz MA611_phased.vcf.gz -O v -o RBphased_variants.SixSamples.Final.vcf
    # duplicate records at the same lines from the file "RBphased_variants.SixSamples.Final.vcf"
    2	14691373	.	A	.	1153.31	PASS	BaseQRankSum=2.02;ClippingRankSum=0;ExcessHet=3.0103;FS=1.098;InbreedingCoeff=-0.0861;MQ=58.74;MQRankSum=-2.459;QD=19.22;ReadPosRankSum=-0.466;SOR=0.96;DP=68;AN=8	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC:PM	0/0:4:4:0:0:0/0:.:.:0/0:.:.	0/0:7:7:18:0:0/0:.:.:0/0:.:.	0/0:4:4:12:0:0/0:.:.:0/0:.:.	0/0:2:2:3:0:0/0:.:.:0/0:.:.	./.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.
    2	14691373	.	A	AAG	1153.31	PASS	BaseQRankSum=2.02;ClippingRankSum=0;ExcessHet=3.0103;FS=1.098;InbreedingCoeff=-0.0861;MQ=58.74;MQRankSum=-2.459;QD=19.22;ReadPosRankSum=-0.466;SOR=0.96;set=InDels;DP=676;AF=0.042;AN=4;AC=0	GT:AD:DP:GQ:PGT:PID:PL:PG:PB:PI:PW:PC:PM	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:12,0:12:9:.:.:0,9,135:0/0:.:.:0/0:.:.	0/0:22,0:22:12:.:.:0,12,180:0/0:.:.:0/0:.:.
    2	14691374	.	A	.	1320.25	PASS	BaseQRankSum=-1.049;ClippingRankSum=0;ExcessHet=0.2929;FS=0;InbreedingCoeff=0.4006;MQ=55.35;MQRankSum=0;QD=33.01;ReadPosRankSum=-0.671;SOR=0.892;DP=44;AN=2	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC:PM	0/0:4:4:0:0:0/0:.:.:0/0:.:.	./.:7:7:.:0:./.:.:.:./.:.:.	./.:0:0:.:0:./.:.:.:./.:.:.	./.:0:0:.:0:./.:.:.:./.:.:.	./.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.
    2	14691374	.	A	G	1320.25	PASS	BaseQRankSum=-1.049;ClippingRankSum=0;ExcessHet=0.2929;FS=0;InbreedingCoeff=0.4006;MQ=55.35;MQRankSum=0;QD=33.01;ReadPosRankSum=-0.671;SOR=0.892;set=HignConfSNPs;DP=710;AF=0.115;MLEAC=3;MLEAF=0.115;AN=4;AC=0	GT:AD:DP:GQ:PGT:PID:PL:PG:PB:PI:PW:PC:PM	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	./.:.:.:.:.:.:.:.:.:.:.:.:.	0/0:12,0:12:9:.:.:0,9,135:0/0:.:.:0/0:.:.	0/0:22,0:22:12:.:.:0,12,180:0/0:.:.:0/0:.:.

**I have attached there associated files below.** 

[MA605_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786772/MA605_phased.vcf.gz)
[MA611_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786773/MA611_phased.vcf.gz)
[ms01e_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786774/ms01e_phased.vcf.gz)
[ms02g_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786775/ms02g_phased.vcf.gz)
[ms03g_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786776/ms03g_phased.vcf.gz)
[ms04h_phased.vcf.gz](https://github.com/samtools/bcftools/files/1786777/ms04h_phased.vcf.gz)
[RBphased_variants.FourSamples.Final.vcf.gz](https://github.com/samtools/bcftools/files/1786840/RBphased_variants.FourSamples.Final.vcf.gz)
[RBphased_variants.SixSamples.Final.vcf.gz](https://github.com/samtools/bcftools/files/1786841/RBphased_variants.SixSamples.Final.vcf.gz)

**Comment by pd3** [comment]
I am not able to reproduce this behavior with the latest versions of bcftools. Looking in the header of the output files, you are running 1.2. Can you update to the latest version? 
http://samtools.github.io/bcftools
