### ISSUE TITLE
`bcftools sort` doesn't group identical lines

### ISSUE THREAD

**Issue by garrett-stevens** [samtools/bcftools#756]
I sometimes have to deal with lines being duplicated in my VCFs (usually because of `bcftools view -R`, see https://github.com/samtools/bcftools/issues/221 and https://github.com/samtools/bcftools/issues/562). I've been working around this by using `bcftools sort` and then the unix `uniq` command on the VCFs. I've noticed, though, that when the multiallelic variants in my VCF have been split (such as with `bcftools norm -m -both`), duplicate lines don't always sort together. Here's an example:
```bash
(echo "##fileformat=VCFv4.1"
echo -e "##contig=<ID=1,length=249250621,assembly=b37>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "1\t10006\t.\tA\tAC\t.\t.\t."
echo -e "1\t10006\t.\tA\tT\t.\t.\t."
echo -e "1\t10006\t.\tA\tAC\t.\t.\t.") | bcftools sort 2> /dev/null
```
produces:
```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1	10006	.	A	AC	.	.	.
1	10006	.	A	T	.	.	.
1	10006	.	A	AC	.	.	.
```
In this case, then, `uniq` won't get rid of the duplicates since they're not grouped together. Is this is a bug or the expected behavior (I know not all tools support multiallelic variant split VCFs)?

**Comment by pd3** [comment]
Currently the sort works only chr and pos, but this can be extended. In the meanwhile, would `bcftools norm -d` help?

**Comment by garrett-stevens** [comment]
That's close to what I want, but what I would need would be something like `bcftools norm -d none`, and it appears the options for `-d` are `snps|indels|both|any`. What's a bit confusing is the [docs for `norm`](http://www.htslib.org/doc/bcftools.html#norm) claim that `norm -D` is an alias for `norm -d none`, but when you run it, it's actually an alias of `norm -d both`:
```
Warning: `-D` is functional but deprecated, replaced by `-d both`.
```
Also, the docs for `-D` mention "Requires `-a`, `--allow-overlaps`," but `norm` doesn't have that option.

**Comment by pd3** [comment]
The documentation is not up to date, apologies. If you can update to the latest version of bcftools, the `norm -d none` removal is supported there.

Both the documentation and the sorting will be addressed in the next release. Thank you for your feedback.

**Comment by garrett-stevens** [comment]
I just updated to 1.7 and I now see the `norm -d none` option, that should work for me. Thanks so much!

**Comment by pd3** [comment]
This should be now working https://github.com/samtools/bcftools/commit/4dca79a0d64035b7ae0a1b54a00469a7903ef54b
