### ISSUE TITLE
bcftools array FORMAT subscripts produce error on tag AD

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#757]
In bcftools 1.7, this command:

```
bcftools annotate -e 'FORMAT/AD[1]==0' xxx.vcf.gz
```

produces this error message:

```
The FORMAT tag AD can have multiple subfields, run as AD[sample:subfield]
```

As far as I know, the AD tag does NOT have multiple subfields.

The tag has this header entry:

```
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
```

and here is a sample data line:

```
chr1    100731188       .       C       T       190.77  .       AC=1;AF=0.5;AN=2;BaseQRankSum=-1.635;ClippingRankSum=0;DP=35;ExcessHet=3.0103;FS=1.493;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=0;QD=5.45;ReadPosRankSum=1.871;SOR=0.332       GT:AD:DP:GQ:PL  0/1:23,12:35:99:219,0,615
```

**Comment by pd3** [comment]
That is correct behavior. The AD tag is defined as `Number=R` and should have as many values as there are alleles, including the reference allele. Also your data line example correctly shows two values. 

You can use the asterisk symbol to select any field `AD[1:*]`.

**Comment by tedtoal** [comment]
Ok, thanks.  I apologize for not reading the bcftools manual section carefully enough, I understand now.  However, I think the word "subfield" is being used inappropriately, and you might want to change it to "value".  In the VCF spec section 1.4.1 #8, the word "sub-field" is used to refer to the entire "key=value,value,..." construct; the wording as I read it says that a line's INFO is a field, composed of one or more comma-separated subfields, each subfield having the format key=value[,value...].

In the bcftools documentation I homed in on "array subscripts (0-based)" and the top example "(DP4[0]+DP4[1])/(DP4[2]+DP4[3]) > 0.3" without stopping to think about the issue of multiple samples in format fields.  Maybe wording like this would help others:

```
arrays 1-dimensional (INFO subfields; [value]) or 2-dimensional (FORMAT subfields; [sample:value]). 
Both "sample" and "value" subscripts 0-based, "*" for any sample or value, "-" to indicate a range,
"," to use a list. For FORMAT subfield subscripts, the colon ":" is used to select a sample and a
value.

INFO/AF[0] > 0.3             .. first AF value bigger than 0.3
FORMAT/AD[0:0] > 30          .. first AD value of the first sample bigger than 30
FORMAT/AD[0:1]               .. first sample, second AD value
FORMAT/AD[1:0]               .. second sample, first AD value
(and then continue with your other examples, arranged least complex to most complex)
```

**Comment by pd3** [comment]
Thank you for the suggestion and your help with improving the documentation.

@jkbonfield  proposed that the term "element" should make the wording clearer (https://en.wikipedia.org/wiki/Array_data_structure)

This is the updated version of the text:
````
Array subscripts (0-based), "*" for any field, "-" to indicate a range. Note that
for querying FORMAT vectors, the colon ":" can be used to select a sample and an
element of the vector, as shown in the examples below

        INFO/AF[0] > 0.3             .. first AF value bigger than 0.3
        FORMAT/AD[0:0] > 30          .. first AD value of the first sample bigger than 30
        FORMAT/AD[0:1]               .. first sample, second AD value
        FORMAT/AD[1:0]               .. second sample, first AD value
        DP4[*] == 0                  .. any DP4 value
        FORMAT/DP[0]   > 30         .. DP of the first sample bigger than 30
        FORMAT/DP[1-3] > 10         .. samples 2-4
        FORMAT/DP[1-]  < 7          .. all samples but the first
        FORMAT/DP[0,2-4] > 20       .. samples 1, 3-5
        FORMAT/AD[0:1]              .. first sample, second AD field
        FORMAT/AD[0:*], AD[0:] or AD[0] .. first sample, any AD field
        FORMAT/AD[*:1] or AD[:1]        .. any sample, second AD field
        (DP4[0]+DP4[1])/(DP4[2]+DP4[3]) > 0.3
        CSQ[*] ~ "missense_variant.*deleterious"
````

**Comment by jkbonfield** [comment]
Maybe *"\*" for any element* instead of *"\*" for any field*?  I assume field here is referring to the same thing as the end of the sentence?

**Comment by pd3** [comment]
Yes, updated.

**Comment by pd3** [comment]
This has been now addressed with other docs updates https://github.com/samtools/bcftools/commit/347a508c54b1de7a0ac005830ecad81b5f7fe2cd
