### ISSUE TITLE
bcftools norm: split_info_numeric: Assertion `ret==src->n_allele-1' failed

### ISSUE THREAD

**Issue by igordot** [samtools/bcftools#758]
I am trying to run `bcftools norm --multiallelics -both --output-type v` on a file and get this error:
```
bcftools: vcfnorm.c:414: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted (core dumped)
```

This seems to be the offending line (+/-3 for context):
```
chr1	1948519	.	T	C	418.77	PASS	AC=1;AF=0.5;AN=2;DP=45	GT:AD:DP:GQ:PL	0|1:31,13:44:99:447,0,1253
chr1	1948594	.	G	GT	654.73	PASS	AC=2;AF=1;AN=2;DP=31	GT:AD:DP:GQ:PL	1|1:1,28:29:75:555,75,0
chr1	1948919	.	T	TCCTTCCCTCCTCTTTCCCTCCCTTCTTTCCTTCCCTTTCCCTCCCTC	344.73	PASS	AC=2;AF=0.5;AN=2;DP=29	GT:AD:DP:GQ:PL	1|1:14,11:25:99:382,0,431
chr1	1948947	.	T	TCCCTCCCTCCCTTCCTTCCTCTTTCCTTCCTTCCTTTCCCTCCCTTACTCCTTCCTTCCCTTCCCCTTCCTTCTTCCTTCTCTCCCTCCCTCCCTTC,TCCCTCCCTTACTCCTTCCTTCCTTCCCTTCCCCTTCCTTCTTCCTTCTCTCCCTCCCTCCCTTC	1001.73	PASS	AC=2;AF=0.5,0.5;AN=2;DP=17	GT	1|1
chr1	1949052	.	TTTCC	T	778.73	PASS	AC=1;AF=0.5;AN=2;DP=36	GT:AD:DP:GQ:PL	1|0:6,19:25:99:816,0,165
chr1	1949125	.	T	TTCCC	138.73	PASS	AC=1;AF=0.5;AN=2;DP=28	GT:AD:DP:GQ:PL	1|0:8,5:13:99:176,0,298
chr1	1949564	.	T	TG	3769.73	PASS	AC=2;AF=1;AN=2;DP=95	GT:AD:DP:GQ:PL	1|1:0,95:95:99:3807,286,0
```
If I exclude it, everything is fine.

The long indel is causing a problem. It's longer than most, but does not seem to be unreasonable. Is this due to some system settings? Is there a way to avoid that?

**Comment by pd3** [comment]
The problem is probably the AC field. As a `Number=A` annotation multiple values are expected but only one is found.

In newer versions of `bcftools norm` the assert was replaced with a more informative message.

**Comment by igordot** [comment]
Thank you for pointing that out. You're right. The AC does seem to be incorrect. Curiously, AF still has 2 values.

I thought that the longer indels were the problem because the behavior is only observed for those (with millions of variants, filtering by indel length got rid all the problematic ones). Anyway, that is clearly a comment for the variant caller, not bcftools.
