### ISSUE TITLE
+prune unexpected behaviour - zero based positions

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#760]
I was doing LD-annotations of my VCF like this:
`bcftools +prune -R $R -l 1 -w 10kb -a MAX_R2 $vcf`

But the positions annotated as `MAX_R2_POS` are zero based instead of one based. Would it make sense to change this?

**Comment by pd3** [comment]
This was not intended and is fixed now. Thank you for letting us know about the bug.
