### ISSUE TITLE
bcftools query unexpected behaviour, when filtering on MAF

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#762]
I was querying the position of the common (MAF>5%) variants of a VCF file. I didn't quite get the result I expected. Filtering on MAF was not carried out. I would expect columns 3 and 4 of the output to be identical, when using the command below, but the MAF filtering only works when printing the AF field.

Command:
```
paste \
 <($bcftools query -f '%POS\t%AF\n' $vcf) \
 <($bcftools query -e 'MAF[0]<0.05' -f '%POS\n' $vcf) \
 <($bcftools query -e 'MAF[0]<0.05' -f '%POS\t%AF\n' $vcf) \
| head
```

Unexpected output (columns 3 and 4 not identical):
```
60131	0.000127065	60131	61098	0.242948
60180	0.000127065	60180	61795	0.489454
60343	0.000127065	60343	63231	0.122236
60386	0.00025413	60386	63244	0.163151
60419	0.000127065	60419	63733	0.0841169
60454	0.000127065	60454	63799	0.49695
60479	0.00520966	60479	63808	0.0841169
60568	0.000127065	60568	65900	0.757052
60571	0.00635324	60571	66370	0.796315
60579	0.000127065	60579	68264	0.136595
```

**Comment by pd3** [comment]
The behavior depends on the annotations present in the file. The `-f %AF` part simply prints `INFO/AF` field. The `-e MAF` part is based on `INFO/AN` and `INFO/AC` if present, and is calculated from the `FORMAT/GT` fields otherwise.

**Comment by tommycarstensen** [comment]
Thanks! Why would the output be dependent, on whether the `AF` is printed with `-f` or not? The filtering should only depend on the `-e 'MAF[0]<0.05'`, no?

**Comment by pd3** [comment]
I don't think it does, it shouldn't. Can you provide a small reproducible test case? This could be just the `paste` command messing it up.

**Comment by tommycarstensen** [comment]
Hi Petr. Thanks for looking into this. Here is a reproducible example for you with command as above after setting the bcftools path:
vcf=/nfs/users/nfs_t/tc9/pd3/762.vcf

Here is my version, which I pulled and re-compiled recently:
bcftools 1.7-1-ge07034a
Using htslib 1.7-24-gaa1a775

**Comment by pd3** [comment]
Thank you for reporting the bug, it is now fixed.
