### ISSUE TITLE
Problems with convert example

### ISSUE THREAD

**Issue by wodanaz** [samtools/bcftools#763]
I feel like I am missing something with the example described in https://samtools.github.io/bcftools/howtos/convert.html. I think it doesn't work for me because I don't have a SampleName list file. Can you elaborate and describe this file please according to the raw data from 23andme.

Thank you

**Comment by pd3** [comment]
`SampleName` in the example is not a file, but a string - a sample name. Conversion to a single-sample VCF is supported at the moment.

**Comment by wodanaz** [comment]
Great, thanks for your answer. I am running a conversion of the 23andme output ( only for chromosome 1) to vcf file and this is the screen result. 

Rows total: 	77016
Rows skipped: 	77016
Missing GTs: 	0
Hom RR: 	0
Het RA: 	0
Hom AA: 	0
Het AA: 	0

**Comment by pd3** [comment]
Apparently there was a problem with the conversion. What does your input look like?

**Comment by mcshane** [comment]
Your fasta has the `chr` prefix for the chromosome name, while it looks like your tab file does not.

**Comment by wodanaz** [comment]
It worked, thank you so much.
