### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by hou** [samtools/bcftools#764]
Is it possible to add new features so bcftools can do genotype level filtering?

For example, set genotypes to missing if GQ < 20 or DP < 10.

Similar with what vcftools does with the --minGQ <float> or --minDP <float> options.

**Comment by pd3** [comment]
See the plugin `setGT`, this should work:

````
bcftools +setGT in.vcf -- -t q -n . -i 'GQ<20 || DP<10'
````

**Comment by hou** [comment]
Great, many thanks for the hint!
