### ISSUE TITLE
How do extract a VCF tag named 'TYPE' in a bcftools expression?

### ISSUE THREAD

**Issue by tseemann** [samtools/bcftools#765]
Freebayes VCF records have a `TYPE` tag of form `TYPE={ins,del,mnp,snp,complex}`.

As far as I can tell, `TYPE` is a special keyword in bcftools:
`TYPE for variant type in REF,ALT columns (indel,snp,mnp,ref,bnd,other)`
http://samtools.github.io/bcftools/bcftools-man.html#expressions

This means we can't use it to pull out just `TYPE=ins` or just `TYPE=del` records from Freebayes VCF files:

```
% bcftools filter -i 'TYPE="del"' freebayes.vcf
The type "del" not recognised: TYPE="del"
```
Is there a way to do what I need?

Filed at freebayes here: https://github.com/ekg/freebayes/issues/456

**Comment by pd3** [comment]
Using `TAG` in expression is an abbreviation for `INFO/TAG` or `FORMAT/TAG`. In ambiguous cases, you need to include the `INFO` part as well. So in your case `INFO/TYPE` should work.

**Comment by tseemann** [comment]
@pd3 ok thank you for the clarification - that's good.

**Comment by finswimmer** [comment]
Hello, 

at least in the current version (1.9) using `INFO/TYPE` instead of just `TYPE` doesn't work. I get the same message as @tseemann shows.

fin swimmer

**Comment by pd3** [comment]
The `-i INFO/TYPE="del"` expression can work only if a tag named `TYPE` is present in the `INFO` field. Standalone `TYPE` is evaluated on the fly and can be one of `{indel,snp,mnp,ref,bnd,other}` as described in the documentation.
