### ISSUE TITLE
bcftools annotate fails when contigs are not defined in header

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#766]
given t.vcf of:
```
##fileformat=VCFv4.1
##INFO=<ID=SU,Number=.,Type=Integer,Description="Number of pieces of evidence supporting the variant across all samples">
##INFO=<ID=PE,Number=.,Type=Integer,Description="Number of paired-end reads supporting the variant across all samples">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       74911683        A1      A       T       53.79   PASS    SU=6;PE=6
```
the command:
```
 bcftools annotate t.vcf
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
Encountered error, cannot proceed. Please check the error output above.
```

if I bgzip and index, then this command works. This is suprising since normally that is a warning.

output of bcftools --version is:
```
bcftools 1.7-25-ge12f43d
Using htslib 1.7-41-g816a220
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pd3** [comment]
When the contig lines are not present in the header, bcftools can use the index to get the information it needs - hence the suggested "Quick workaround". 
This is not a bug. What exactly is the question here?

**Comment by brentp** [comment]
the first command fails with an error and exits before doing any annotation.

in other bcftools commands, this is just a warning. It's not clear to me why it's an error in bcftools annotate, but a warning elsewhere. I'm so used to seeing the `Contig XX not defined in header ...` that I thought that could not be the actual reason for the failure.

**Comment by pd3** [comment]
Sorry for a late response. Commands which only read VCFs can get away with the missing contigs, but writers need to know all the sequences beforehand, at the time the header is printed. This is because chromosome names in the BCF format are stored as pointers to the dictionary of names in the header. Only BCF writing has this problem and it is possible to make this work when VCF is output. However, it is not worth the effort as simple indexing solves the problem and missing contig names are discouraged anyway.

**Comment by tommycarstensen** [comment]
How come `bcftools norm` works, but `bcftools annotate` doesn't work without reheadering and adding information on the contigs. The "quick workaround" is not so quick in my opinion and `bcftools reheader --fai` does not work on a file stream. This seems more like a bug than a feature to me. I hope the user feedback from myself and @brentp is useful @pd3.

**Comment by Titorat** [comment]
One issue though,  is that it silently fail in my case and does not return a non-zero response in the snakemake pipeline

**Comment by pd3** [comment]
@Titorat Please open a new issue with the exact description of the problem.

**Comment by eesiribloom** [comment]
I have a VCF file where contigs are not in the header. I know this is discouraged but it is what I have sadly. I want to use `bcftools annotate `but I get this error:
```
[W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
Encountered an error, cannot proceed. Please check the error output above.
```
If feeling adventurous, use the --force option. (At your own risk!)
when I run `bcftools index -t` I get 
```
[E::hts_idx_push] Unsorted positions on sequence #2: 81289238 followed by 81288977
index: failed to create index for "ON010T_minda_ensemble.vcf.gz"`
```
when I run `bcftools sort` I get 
```
[W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
Error encountered while parsing the input at chr1:5740730
Cleaning
```
