### ISSUE TITLE
bcftools --include does not evaluate the length of second ALT allele correctly

### ISSUE THREAD

**Issue by golobor** [samtools/bcftools#767]
Hi,
I am trying to isolate SNPs from a vcf file with phased NA12878 variants using ```bcftools filter --include``` and may have encountered a bug in calculation of the length of ALT alleles.

I select SNPs from the first homologue using the following code:
```
bcftools filter -i '(STRLEN(REF)==1) & (((GT~"0|.") | ((GT~"1|.") & (STRLEN(ALT[0])==1))) | ((GT~"2|.") & (STRLEN(ALT[1])==1)))' hg38.hybrid.100K.vcf.gz
```
which I test on [the first 100K lines](https://gist.github.com/golobor/33a3790f0c3e75c5d3c27713541ef686/raw/7dbed04d9bab68df6c12be13ae25fad893841a69/hg38.hybrid.100K.vcf.gz) of the original vcf file.

The output of this command still contains some indels. Isolating different parts of this command identified the source of the issue in the erroneous evaluation of the length of ALT[1]:

```
bcftools filter -i '(STRLEN(REF)==1) & ( (GT~"2|.") & (STRLEN(ALT[1])==1 ))' hg38.hybrid.100K.vcf.gz
```

A quote from the output of this command:
```
##bcftools_filterVersion=1.7+htslib-1.7
##bcftools_filterCommand=filter -i '(STRLEN(REF)==1) & ( (GT~"2|.") & (STRLEN(ALT[1])==1 ))' hg38.hybrid.100K.vcf.gz; Date=Fri Mar 30 20:44:44 2018
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
chr1    17376539        .       T       A,TTTTTTTTATTTTTAGTGGGCTAA      50      PASS    SOURCE=GIAB     GT      2|1
chr1    20031044        .       G       C,T     0       PASS    SOURCE=PG       GT      2|1
chr1    20110398        .       G       C,T     0       PASS    SOURCE=PG       GT      2|1
chr1    24031633        .       G       A,C     0       PASS    SOURCE=PG       GT      2|1
chr1    26128786        .       T       A,TCA   50      PASS    SOURCE=GIAB     GT      2|1
chr1    30098074        .       A       C,T     0       PASS    SOURCE=PG       GT      2|1
```

I am using Bcftools Version: 1.7 (using htslib 1.7) from [bioconda](https://anaconda.org/bioconda/bcftools) on Ubuntu 16.04.

Thank you.

**Comment by pd3** [comment]
This is now fixed, thank you for the bug report.
