### ISSUE TITLE
Format that cannot be usefully indexed

### ISSUE THREAD

**Issue by fhodel** [samtools/bcftools#772]
While trying to index my file I get this error message: `index: "filename.vcf.gz" is in a format that cannot be usefully indexed`. However, my VCF file is bgzip compressed.

If I do:
`htsfile filename.vcf.gz`

I get:
`filename.vcf.gz: VCF version 4.3 gzip-compressed variant calling data`

Why do I get this error message then?

**Comment by Moo-cow** [comment]
Thank you every much!
