### ISSUE TITLE
bcftools isec 

### ISSUE THREAD

**Issue by NurislamSheih** [samtools/bcftools#773]
Hi,

I'm using bcftools isec to intersect two vcf. I want to know, if in one position of two vcf alleles are differ (e.g. vcf1 - POS:14, REF:C, ALT:A; vcf2 - POS:14, REF:C, ALT:G), it throws out this position or create two files, where it will be share for two vcf, but with different ALT - 0002.vcf - C A, 0003.VCF - C G
 
My command: 
`bcftools isec -p /data/Shared/  SNP_FILTERED.vcf.gz SNP_FILTERED_1.vcf.gz`

My task is to find the number of different alleles between two vcf files.

**Comment by BEFH** [comment]
check the README file in /data/Shared/. It will say what's in the files. If the alt is different it won't be in the overlap. You'll need to align the files.

**Comment by pd3** [comment]
@NurislamSheih the `-c` option needs to be used in order to match different alleles at the same position. However, the program will not give any indication if the alleles were the same or different.

**Comment by NurislamSheih** [comment]
Thank you so much for your answers)
