### ISSUE TITLE
Subsetting with `bcftools filter file1.vcf.gz -r chr#` fails for majority of chromosomes

### ISSUE THREAD

**Issue by evanbiederstedt** [samtools/bcftools#774]
I have a VCF file with chromosomes in the format `chr1`, not `1`. My goal is to subset this VCF by chromosome. 

The original VCF `file1.vcf` includes chromosomes chr1 through chr22, chrX and chrY. 

With `htslib`, I do the following 

```
bgzip file1.vcf
tabix file1.vcf.gz 
```
Then, I would like to subset the VCF via `bcftools filter`, i.e. 

>        -r, --regions chr|chr:pos|chr:from-to|chr:from-[,...]
> Comma-separated list of regions, see also **-R**, **--regions-file**. Note that **-r** cannot be used in combination with **-R**.
> 
>        -R, --regions-file FILE
> Regions can be specified either on command line or in a VCF, BED, or tab-delimited file (the default). The columns of the
>            tab-delimited file are:
>            CHROM, POS, and, optionally, POS_TO, where positions are 1-based and inclusive. Uncompressed files are stored in memory, while
> bgzip-compressed and
>            tabix-indexed region files are streamed. Note that sequence names must match exactly, "chr20" is not the same as "20". Also note
> that chromosome
>            ordering in FILE will be respected, the VCF will be processed in the order in which chromosomes first appear in FILE.
> However, within chromosomes, the
>            VCF will always be processed in ascending genomic coordinate order no matter what order they appear in FILE. Note that
> overlapping regions in FILE can
>            result in duplicated out of order positions in the output. This option requires indexed VCF/BCF files. Note that **-R** cannot be
> used in combination with **-r**.

This works well for the first few chromosomes, outputting to STDOUT or piping to a new VCF, e.g. 

`bcftools filter file1.vcf.gz -r chr4 > chr4.vcf`

The problem is, beginning with `chr6` through `chrY`, only the header is output. These regions exist in the original VCF, but subsetting doesn't seem to "find" them. 

Are there troubleshooting recommendations for this situation? What could be going wrong? Maybe the index is flawed or something

**Comment by pd3** [comment]
That's strange. Try something like

````
bcftools query -f'[%CHROM]\n' file1.vcf.gz | uniq -c
````

to make sure that the chromosome are in contiguous blocks (but `tabix` would fail if they were not) and if the chromosome names are as expected. By the way, you could also use `bcftools view` instead of `bcftools filter` for this.

**Comment by evanbiederstedt** [comment]
Thanks for the response. 

> By the way, you could also use bcftools view instead of bcftools filter for this.

I'm not sure I follow...

RE: chromosome ordering

I think these are in contiguous blocks, and as you mention, `tabix` is successful. I should maybe also mention that the VCF is also "valid" via `vcf-validator`. I'm happy to transfer over the VCF if that's helpful for the development team...Otherwise, I'm flummoxed why this happens.

**Comment by pd3** [comment]
The command `bcftools view` can be used for the exact same purpose as `bcftools filter`.

A test case to reproduce the problem would be great, I can't think of any reason why this should be happening.

**Comment by evanbiederstedt** [comment]
@pd3  Ah, I understand what you mean now. 

I'll e-mail instructions as to how to download the VCF to your Sanger address. That's probably the best way forward

**Comment by pd3** [comment]
Thank you, I've got the file. From a cursory glance the problem will most likely be unchecked memory in htslib, there are extremely long alleles in the VCF. I will post an update here

**Comment by pd3** [comment]
OK, I can confirm that the reason is that the VCF contains **insanely** long alleles. It breaks standard unix commands like `awk` and `grep`, had to write a small dedicated program just to show how bad it is. The longest line in the VCF is longer than 5e9 characters!

If this is intended, I am afraid you'll need to look at different solution, VCF was not intended for this.
