### ISSUE TITLE
Missing info field from samtools/bcftools-1.8 output

### ISSUE THREAD

**Issue by TashyK** [samtools/bcftools#775]
I recently updated software to samtools/bcftools-1.8 (from v 1.2). After mapping of illumina data to a references (using BWA), I use samtools to call SNPs and bcftools to produce VCF files. 

While I get output there are a bunch of headers missing from my VCF files - the most important being the AF field, which I need for downstream analysis. 

Any help or advice would be much appreciated. 

Here is example code:
"$pathtotools"samtools-1.8/bin/samtools mpileup -Bguf MTB_ancestor_reference.fas "$GENOME".sort.bam | 
"$pathtotools"bcftools-1.8/bin/bcftools call -Ob -m > "$GENOME".all.raw.bcf ; 
"$pathtotools"bcftools-1.8/bin/bcftools view -v snps,indels -Ob "$GENOME".all.raw.bcf > "$GENOME".var.raw.bcf ; 
"$pathtotools"bcftools-1.8/bin/bcftools view "$GENOME".all.raw.bcf > "$GENOME".all.raw.vcf ; 

And an example of the first bit of my VCF file.
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##samtoolsVersion=1.8+htslib-1.8
##samtoolsCommand=samtools mpileup -Bguf MTB_ancestor_reference.fas 1_S1_L001.sort.bam
##reference=file://MTB_ancestor_reference.fas
##contig=<ID=MTB_anc,length=4411532>
##ALT=<ID=*,Description="Represents allele(s) other than observed.">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of reads supporting an indel">
##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of reads supporting an indel">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">
##INFO=<ID=RPB,Number=1,Type=Float,Description="Mann-Whitney U test of Read Position Bias (bigger is better)">
##INFO=<ID=MQB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality Bias (bigger is better)">
##INFO=<ID=BQB,Number=1,Type=Float,Description="Mann-Whitney U test of Base Quality Bias (bigger is better)">
##INFO=<ID=MQSB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality vs Strand Bias (bigger is better)">
##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">
##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=ICB,Number=1,Type=Float,Description="Inbreeding Coefficient Binomial test (bigger is better)">
##INFO=<ID=HOB,Number=1,Type=Float,Description="Bias in the number of HOMs number (smaller is better)">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
##bcftools_callVersion=1.8+htslib-1.8
##bcftools_callCommand=call -Ob -m; Date=Fri Apr 20 05:00:12 2018
##bcftools_viewVersion=1.8+htslib-1.8
##bcftools_viewCommand=view 1_S1_L001.all.raw.bcf; Date=Fri Apr 20 05:09:40 2018
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1_S1_L001.sort.bam
MTB_anc 11      .       A       .       63      .       DP=1;MQ0F=0;AN=2;DP4=1,0,0,0;MQ=60      GT      0/0
MTB_anc 12      .       C       .       115     .       DP=3;MQ0F=0;AN=2;DP4=3,0,0,0;MQ=60      GT      0/0
MTB_anc 13      .       C       .       115     .       DP=3;MQ0F=0;AN=2;DP4=3,0,0,0;MQ=60      GT      0/0
MTB_anc 14      .       C       .       115     .       DP=3;MQ0F=0;AN=2;DP4=3,0,0,0;MQ=60      GT      0/0
MTB_anc 15      .       C       .       115     .       DP=3;MQ0F=0;AN=2;DP4=3,0,0,0;MQ=60      GT      0/0
MTB_anc 16      .       G       .       150     .       DP=5;MQ0F=0;AN=2;DP4=5,0,0,0;MQ=60      GT      0/0
MTB_anc 17      .       G       .       185     .       DP=8;MQ0F=0;AN=2;DP4=8,0,0,0;MQ=60      GT      0/0
MTB_anc 18      .       T       .       187     .       DP=8;MQ0F=0;AN=2;DP4=8,0,0,0;MQ=60      GT      0/0
MTB_anc 19      .       T       .       187     .       DP=8;MQ0F=0;AN=2;DP4=8,0,0,0;MQ=60      GT      0/0
MTB_anc 20      .       C       .       189     .       DP=8;MQ0F=0;AN=2;DP4=8,0,0,0;MQ=60      GT      0/0

**Comment by pd3** [comment]
The plugin `+fill-tags` can be used to recalculate and add annotations, among other AF: AF, AC, AC_Hemi, AC_Hom, AC_Het, AN, ExcHet, HWE, MAF, NS.
