### ISSUE TITLE
Q: filter according to a file containing variant IDs

### ISSUE THREAD

**Issue by samuelandjw** [samtools/bcftools#776]
I want to filter a vcf file by including SNPs with IDs given by a file. I have read through the documentation but I still have no clue how to do it.
Suppose I have a file called `test.snp`:
```
10_60833_TAGAA_T
10_60993_G_A
```
I tried filtering using `bcftools view -i'ID=@test.snp' a.vcf.gz`. Yet I got the error message:
`Could not read: @test.snp`

**Comment by pd3** [comment]
There was a silly bug introduced recently and fixed shortly afterwards
https://github.com/samtools/bcftools/pull/769

The latest github version should work. Please reopen if not.
