### ISSUE TITLE
cannot include position given by an external file using bcftools view

### ISSUE THREAD

**Issue by samuelandjw** [samtools/bcftools#778]
Suppose I have this toy vcf.gz file (I skipped the header and genotypes):
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
22	16050036	22_16050036_A_C	A	C	.	PASS	AR2=0.8;DR2=0.82;AF=0.921622;AC=8866;AN=9620
```
I can retrieve the record by `bcftools view -i POS=16050036 test.vcf.gz` . However, If I store the position in a file called `test_pos` whose only content is the position:
```
$ cat > test_pos
16050036
```
and attempt to retrieve the record using `bcftools view -i POS=@test_pos test.vcf.gz`, I cannot get the record at 22:16050036.

The version of bcfools I am using is
```
$ bcftools -v
bcftools 1.8-10-g1c470c4
Using htslib 1.8-7-gf100074
```

**Comment by pd3** [comment]
The `@file` syntax was intended for IDs. To filter by position, use the `-r, -R, -t, -T` options.

**Comment by samuelandjw** [comment]
@pd3 Thanks for clarifying. Perhaps giving an error message when using POS with `@file` is more helpful?

**Comment by pd3** [comment]
Yes, it would be good to have a check for this. Related to #798
