### ISSUE TITLE
Extremely high GQ at very low DP and AD

### ISSUE THREAD

**Issue by maehrlich1** [samtools/bcftools#779]
I ran the following command using bcftools 1.8 with htslib 1.8:

```bash
#start GNU parallel to run each region (e.g. chromosome, scaffold) on separate CPU core
parallel  --gnu --max-procs $NUM_CORES --keep-order "\

##GENERATE PILEUP 
bcftools mpileup --regions {} --output-type z --skip-indels --annotate AD,DP,SP --fasta-ref $REF_GENOME --min-MQ 20 --min-BQ 20  --no-version -b Intermediate_files/2.bam_alignments/samples_list.txt -o Intermediate_files/3.mpileup/mpileup_{}.vcf.gz;\

##CALL SNPS
bcftools call --multiallelic-caller --variants-only --keep-masked-ref -f GQ --no-version Intermediate_files/3.mpileup/mpileup_{}.vcf.gz | sed -e 's|$(pwd)\/||g' -e 's/Intermediate_files\/2\.bam_alignments\///g' -e  's/\.R.\.fastq.sorted_bam//g'  > Intermediate_files/4.Raw_SNPs/raw_SNPs_{}.vcf;\

" ::: `grep ">" $REF_GENOME | cut -d ' ' -f1 | sed 's/>//g'`

##COMBINE SNPS FROM ALL REGIONS
bcftools concat --no-version `ls -v Intermediate_files/4.Raw_SNPs/*.vcf` > Results/master_raw.vcf
```

In my output VCF I now see several FORMAT fields showing very high GQ although both DP and AD are very low. This is an example site (sorry for the long entry, there are 240 samples in this file):

`NC_012312.1     6226    .       G       A       143     .       DP=4;VDB=0.0949329;SGB=-0.0168057;MQ0F=0;AC=8;AN=8;DP4=0,0,0,4;MQ=60    GT:PL:DP:SP:AD:GQ       ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     1/1:41,3,0:1:0:0,1:127  ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     1/1:41,3,0:1:0:0,1:127  ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     1/1:41,3,0:1:0:0,1:127  ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     1/1:41,3,0:1:0:0,1:127  ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0
     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0     ./.:0,0,0:0:0:0,0:0`

As you can see 4 samples are called hom-alt with AD= 0,1 with PL=41,3,0. I have no problem with this as I was planning to filter on GQ to remove sites like this, however GQ scores are 127 for all 4 samples!

I know the multiallelic caller incorporates population-wide allele frequency priors but a GQ of 127 seems very excessive given only a single read per sample and 4 reads total.

PS: I also thought GQ values >99 are displayed as 99 to reduce file size...

**Comment by pd3** [comment]
I agree this is counter-intuitive, but is consistent with the logic of the mathematical model: there are no reference reads observed and all samples with coverage are consistent. The lack of contrary evidence is interpreted by the model as a good alt-hom call.

Filtering by GQ alone is not sufficient, I suggest the depth is taken into account as well.

**Comment by maehrlich1** [comment]
Thank you, I just assumed that depth is taken into account during the GQ calculation. I ended up filtering on DP instead...
