### ISSUE TITLE
Error: The INFO field is not defined in the header: dbSNP138_ID

### ISSUE THREAD

**Issue by asifemon** [samtools/bcftools#781]
**I am using bcftools for merging multiple files into a single file. But, it gives me following error:**

##bcftools_mergeVersion=1.8+htslib-1.8
##bcftools_mergeCommand=merge X_1.vcf.gz X_2.vcf.gz X_3.vcf.gz; Date=Wed May  2 12:44:07 2018
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	X_1.variant	X_1.variant2	X_2.variant	X_2.variant2	X_3.variant	X_3.variant2
[W::vcf_parse] INFO 'dbSNP142_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP138_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP142_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO '1000G_phase1_release_v3_AF' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP138_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP142_ID' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO '1000G_phase1_release_v3_AF' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'dbSNP138_ID' is not defined in the header, assuming Type=String

**However,  these info are present in my vcf files header as you can see from following instances:**

##source=SelectVariants
##SnpEffVersion="4.0e (build 2014-09-13), by PC"
##SnpEffCmd="SnpEff  -no-downstream -no-upstream GRCh37.75 X_1.vcf.gz "
##INFO=<ID=EFF,Number=.,Type=String,Description="Predicted effects for this variant.Format: 'Effect ( Effect_Impact | Functional_Class | Codon_Change | Amino_Acid_Change| Amino_Acid_length | Gene_Name | Transcript_BioType | Gene_Coding | Transcript_ID | Exon_Rank  | Genotype_Number [ | ERRORS | WARNINGS ] )'">
##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
##SnpSiftVersion="SnpSift 4.0e (build 2014-09-13), by PC"
##SnpSiftCmd="SnpSift annotate -noId -info dbSNP138_ID dbSNP138.vcf.gz -"
##SnpSiftCmd="SnpSift annotate -noId -info dbSNP142_ID dbSNP142.vcf.gz -"
##SnpSiftCmd="SnpSift annotate -noId -info 1000G_phase1_release_v3_AF 1000G_phase1_release_v3.vcf.gz -"
##SnpSiftCmd="SnpSift annotate -noId -info ESP6500_AF ESP6500.vcf.gz -"

**Comment by pd3** [comment]
The fields are not defined in the header you are showing, they just happen to appear in comment lines. They would have to be defined as e.g.
```
##INFO=<ID=dbSNP138_ID,Number=.,Type=Flag,Description="Explain what this means">
````
The VCF specification can be found here: http://samtools.github.io/hts-specs

**Comment by asifemon** [comment]
Thanks. But, could you please tell how can I fix this problem considering I have hundreds of vcf files. The solution with "reheader" as you pointed out somewhere else would be very difficult to achieve with large amount of vcf files to be edited.

**Comment by pd3** [comment]
Write a script to do this for you. This is beyond the support we can provide, sorry!
