### ISSUE TITLE
static inline int tsv_setter_aa1() in vcfconvert.c

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#784]
Very minor issue: in function static inline int tsv_setter_aa1() in vcfconvert.c missing genotypes are converted as follows
```
        gts[0] = bcf_gt_missing;
        gts[1] = bcf_int32_vector_end;
```

However, the <a href="https://samtools.github.io/hts-specs/VCFv4.2.pdf">VCF specification</a>, says:

If a call cannot be made for a sample at a given locus, ‘.’  should be specified for <b>each</b> missing allele in the GT field (for example ‘./.’ for a diploid genotype and ‘.’  for haploid genotype).

I think that the above code generates haploid missing genotypes that might not work with other software (e.g., Beagle complains). I think the correct code should be as follow:
```
        gts[0] = bcf_gt_missing;
        gts[1] = bcf_gt_missing;
```

**Comment by pd3** [comment]
If I remember correctly, this part of the code does not know what the correct ploidy is because the input format does not tell us. However, the `+fixploidy` plugin can be used afterwards.

**Comment by freeseek** [comment]
I actually never used the function itself and I don't even know what format bcftools convert --tsv2vcf works with, but I assumed there was some assumption of diploid genotype. The end of function tsv_setter_aa1() indeed contains this:
```
    if ( ref==a0 && ref==a1  ) args->n.hom_rr++;    // hom ref: RR
    else if ( ref==a0 ) args->n.het_ra++;           // het: RA
    else if ( ref==a1 ) args->n.het_ra++;           // het: AR
    else if ( a0==a1 ) args->n.hom_aa++;            // hom-alt: AA
    else args->n.het_aa++; // non-ref het: AA
```
which does not include the possibility for hemizygous calls and tsv_setter_aa() contains this:
```
 if ( ret==-1 ) error("Error parsing the site %s:%d, expected two characters\n", bcf_hdr_id2name(args->header,rec->rid), rec->pos+1);
```
Anyway, feel free to close this issue.

**Comment by pd3** [comment]
You are right, diploid genotypes are always assumed here. Changing accordingly. Thank you for the feedback.
