### ISSUE TITLE
bcftools: csq.c:2288: cds_translate: Assertion `npad>=0 && sbeg+seq.l+npad<=seq.m' failed

### ISSUE THREAD

**Issue by faithman** [samtools/bcftools#787]
Hi,
I use bcftools v1.7.
when I run `bcftools view --threads=20 -O v input.vcf.gz | bcftools csq -O v --fasta-ref WS245.fa.gz --gff-annot ce.gff3.gz --phase a > results`, I got a break at the position of 17Mb of Chromosome V of C.elegan.
`sbeg=891  seq.l=1 seq.m=887
bcftools: csq.c:2288: cds_translate: Assertion npad>=0 && sbeg+seq.l+npad<=seq.m' failed.
Aborted`
Everthing looks fine in other Chromosome.

Thanks!
Ye

**Comment by pd3** [comment]
Any chance you could share a small test case for debugging?

**Comment by pd3** [comment]
An authentication is required on this site, can you share the files in a different way? My email address is on my profile page.

**Comment by faithman** [comment]
Sorry for the inconvenience! I just confused by your email address. I have changed the access to the link. Please check it again https://northwestern.box.com/s/4tyf5a7nuvtzdp2wbe9atdetoqwudjfc.
Thank you so much for the help!

**Comment by pd3** [comment]
Thank you for the test. It prints many warnings about overlapping variants but otherwise works for me when I run with the latest version from github. It will probably work with the latest release 1.8. Can you try if the latest version works for you as well?

**Comment by faithman** [comment]
Hi Petr,
I still got totally the same error when I use 1.8 version. I still use a batch of other functions of bcftools, the other functions work good for me.

**Comment by pd3** [comment]
Ah, I forgot there was another bugfix since the latest releaase. The latest release 1.8 indeed crashes as well, apologies. Tthe latest github version works for me, download and installation instructions here http://samtools.github.io/bcftools.

**Comment by pd3** [comment]
This is seems solved, please reopen if not.
