### ISSUE TITLE
Documentation of 'merge' should mention 'concat'

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#788]
On the documentation page, in the section on the 'merge' command, it says "For vertical merge, take a look at 'bcftools norm'.  I think it should instead say to take a look at 'bcftools concat', since 'bcftools norm' can only accept one input file but 'concat' can concatenate multiple files.

**Comment by pd3** [comment]
The documentation has been updated in https://github.com/samtools/bcftools/commit/72c10e3685988cd051ba8f4e48a292576cd7dc06, thank you for your feedback!
