### ISSUE TITLE
bcftools consensus throws "Failed to parse TBX_GENERIC"

### ISSUE THREAD

**Issue by andreas-wilm** [samtools/bcftools#789]
Dear all,

I get the following error with attached files and bcftools 1.6 and 1.8, but not with 1.3:

    bcftools consensus -f cons.X8vZEo.0.fa test.vcf.gz
    [E::get_intv] Failed to parse TBX_GENERIC, was wrong -p [type] used?
    The offending line was: "PDH205_CGTACG-gap-filled-assembly      7       .       G       T       49314   PASS    DP=1814;AF=1;SB=0;DP4=0,0,1380,434"

Worst of all, bcftools terminates but with exit code 0.

All other bcftools commands and tabix itself work

Andreas

- [test.vcf.gz](https://github.com/samtools/bcftools/files/1997442/test.vcf.gz)
- [cons.X8vZEo.0.fa.gz (unzip first)](https://github.com/samtools/bcftools/files/1997444/cons.X8vZEo.0.fa.gz)

**Comment by andreas-wilm** [comment]
Looks like tabix didn't like this vcf file. It got processed without warning, but apparently not as vcf. So bcftools consensus (and probably other subcommands depending on the index) choked. Indexing with force type helped. Closing

**Comment by jgarces02** [comment]
Hi @andreas-wilm, I've got the same problem and I cannot solve it... neither forcing type or whatever other think. Any idea, please? Thanks!

**Comment by andreas-wilm** [comment]
Hello, as mentioned there the trick is to recreate the index. Andreas
