### ISSUE TITLE
filter.c:53:8: warning:

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [samtools/bcftools#790]
i use the `make` to build from source code of bcftools(v1.8) on a mac air, but i got several errors:
###
filter.c:53:8: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]

...
consensus.c:436:28: warning: comparison of constant -2147483647 with expression
      of type 'uint8_t' (aka 'unsigned char') is always false
      [-Wtautological-constant-out-of-range-compare]
                if ( ptr[i]==bcf_int32_vector_end ) break;

###
there are several other types errors, i don not know what happened. can everyone help me, tks

**Comment by valeriuo** [comment]
You need to run `autoheader && autoconf && ./configure --enable-libgsl --enable-perl-filters` before `make`. 
You can read more about the bcftools installation options [here](https://github.com/samtools/bcftools/blob/develop/INSTALL#L45).

**Comment by tommycarstensen** [comment]
@Xiaohuaniu0032 and others, one can also just do `brew install bcftools` on a Mac. I did that myself after giving up on compiling it myself. I have no issues compiling it on Linux.

**Comment by pd3** [comment]
@tommycarstensen I was able to compile bcftools  on a Mac, although it was not without problems:

````
# assuming xcode and brew is already installed
brew install autoconf xz gsl

# brew installed the headers in /usr/local/include which was not searched by default
export CPPFLAGS=-I/usr/local/include/
./configure --enable-libgsl --enable-perl-filters

# the default options for linking with Perl provided by the system contained
# -arch i386 which was not liked by the system. After removing it the option
# from PERL_CFLAGS and PERL_LIBS in config.mk, the compilation completed
# without problems
make
make test-plugins
````
