### ISSUE TITLE
annotate -s doesn't work in v1.8

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#791]
bcftools annotate -s 'sampleID1,sampleID2' does not work in version 1.8

**Comment by pd3** [comment]
Can you provide more details please?

**Comment by tedtoal** [comment]
I used it on a VCF file with 5 sample columns, and I specified the argument as shown above, where sampleID1 and sampleID2 were the names at the tops of two of those columns.  The output file still had all 5 columns in it.  No error message was produced.

**Comment by pd3** [comment]
If you want to remove samples from the VCF, this is done with `bcftools view -s`. The command `annotate` interprets the `-s` option differently, limiting the samples to annotate. This is not new in version 1.8 and always used to be the case I believe.

**Comment by tedtoal** [comment]
Ah, I see, and the documentation says as much, but I missed it.  Sorry!

ted

—
Ted Toal, Postdoctoral Researcher
Carvajal-Carmona Lab
Dept. of Biochemistry and Molecular Medicine
4502 GBSF, One Shields Ave
Davis, CA  956626  (530) 263-5986
twtoal@ucdavis.edu
