### ISSUE TITLE
setGT giving haploid allele on GT field

### ISSUE THREAD

**Issue by everestial** [samtools/bcftools#796]
I am trying to set the missing `GT to 0|0` but I endp with only with `GT as single 0` in all the missing sites for all the samples.

**Initial:**

    CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	MA605	MA611	MA622	MA625	MA629	Ncm8	Sp154	Sp164	Sp21	Sp3	Sp76	SpNor33	ms01e	ms02g	ms03g	ms04h
    1	141	.	C	T	.	.	.	GT:PG:PG_al:PI	.	.	.	0|1:0|1:C|T:10763	.	.	.	.	.	.	.	.	.	.	.	.

**My script:**

    bcftools +setGT phasedVCF-short02.vcf.gz -- -t . --new-gt 0p > phasedVCF-short03.vcf
    Filled 110671 alleles

    bcftools +setGT phasedVCF-short02.vcf.gz -- -t . --new-gt 0p\n > phasedVCF-short03.vcf

    bcftools +missing2ref phasedVCF-short02.vcf.gz -- -p > phasedVCF-short03.vcf

Both these and several other scripts are giving the  **Output VCF:**

    CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	MA605	MA611	MA622	MA625	MA629	Ncm8	Sp154	Sp164	Sp21	Sp3	Sp76	SpNor33	ms01e	ms02g	ms03g	ms04h
    1	141	.	C	T	.	.	.	GT:PG:PG_al:PI	0:.:.:.	0:.:.:.	0:.:.:.	0|1:0|1:C|T:10763	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.	0:.:.:.

**Comment by finswimmer** [comment]
Hello,

I answered you on [biostars](https://www.biostars.org/p/315700/#315708).

fin swimmer

**Comment by everestial** [comment]
fixploidy doesn't work either. I tried to raise different flags and just doesn't make sense as per documentation. This too must be a bug.

**Comment by pd3** [comment]
I'd say the program is doing the correct thing. If the missing genotypes were in the form `./.` a diploid `0/0` should be output. The `+fixploidy` plugin can be used to fix the ploidy. You suggested it does not work, in that case can you please open a new issue specifically for this and provide more details, ideally a test case.

I am closing this issue now.

**Comment by everestial** [comment]
@pd3 
The irony here is that this VCF was generate using `bcftools merge `. When converting several VCFs to a single vcf, the sites that were null for all the FORMAT fields for a SAMPLE just turned to single `.`. Basically, any sample with `./.:.:.:` would turn into a single `.`

**Comment by finswimmer** [comment]
Hello,

i tried it with the dataset you give [here](https://github.com/samtools/bcftools/issues/795) and with the code I gave you on [biostars](https://www.biostars.org/p/315700/#315708). No problem here.

fin swimmer
