### ISSUE TITLE
Wrong variant filtering

### ISSUE THREAD

**Issue by reshetovdenis** [samtools/bcftools#798]
bcftools view -i 'INFO/CLNS_PATHOGENIC=1' CUSTOMER.clns.vcf.gz | grep -v '#'
should produce two lines with variant data. However it produces 0 lines.
But it produced 2 lines with the command:
bcftools view -i 'INFO/CLNS_PATHOGENIC=0' CUSTOMER.clns.vcf.gz | grep -v '#'
The bug is presented in both bcftools-1.7 and bcftools-1.8
[CUSTOMER.clns.vcf.gz](https://github.com/samtools/bcftools/files/2023155/CUSTOMER.clns.vcf.gz)

**Comment by pd3** [comment]
The problem is in the VCF header: the field is declared as a string, but numeric comparison is requested. This works: `-i 'INFO/CLNS_PATHOGENIC="1"'`.

But it still a bug, the program should complain instead of quietly ignoring this discrepancy.

**Comment by reshetovdenis** [comment]
Many thanks for prompt reply!

**Comment by pd3** [comment]
This is related to #778
