### ISSUE TITLE
bcftools mpileup split by tag

### ISSUE THREAD

**Issue by igordot** [samtools/bcftools#799]
It's possible to run variant calling on multiple BAMs:
```
bcftools mpileup -Ou -f <ref.fa> <sample1.bam> <sample2.bam> <sample3.bam> | bcftools call -vmO z -o <study.vcf.gz>
```
That assumes that each sample is in a different BAM.

Is it possible to split a single BAM into multiple samples? For example, single-cell experiments can have many samples in a single BAM, but the cell identities are stored in a tag.

**Comment by pd3** [comment]
Multiple samples can be in the same bam and a sample can be spread across multiple bams. In order for this to work, reads must be annotated with the read group ID and the header must include the `@RG ID:... SM:...` lines.
