### ISSUE TITLE
bcftools call piping seems broken

### ISSUE THREAD

**Issue by wmnwmn** [samtools/bcftools#80]
Piping mpileup output to 
"bcftools call -c -" 
or just
"bcftools call -c"
both lead to the error
"Failed to open: -"

Version: 0.2.0-rc10-20-ge1243ea (using htslib 0.2.0-rc10-8-g4b024e1)

**Comment by silvapaloma** [comment]
I have the same error with samtools/1.1   vcftools/0.1.8a   bcftools/1.1

bcftools call -c c1_consensus_intersectbed.pileup | vcfutils.pl vcf2fq > c1_final_consensus.fq
[E::vcf_hdr_read] no sample line
Failed to open: c1_consensus_intersectbed.pileup

what should I do?
