### ISSUE TITLE
Option to recalculate QUAL? 

### ISSUE THREAD

**Issue by dantaki** [samtools/bcftools#800]
I have a joint-called VCF that I split up according to pedigree. My analysis requires me to perform such a task, and I would like to recalculate QUAL. I believe I have the required information in the VCFs to do this. 

A previous post on biostars seems to indicate bcftools can do this, https://www.biostars.org/p/173882/#316181 

However, I cannot find the proper documentation to recalculate the QUAL scores. Is there a plugin or command I can use to do this?

**Comment by pd3** [comment]
There is not enough information in normal VCFs to recalculate the QUAL column with bcftools - this can be done only for raw `bcftools mpileup` output.

**Comment by dantaki** [comment]
Thank you!
