### ISSUE TITLE
weird error handling in bin.c

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#801]
@pd3 I have randomly noticed that the file bin.c contains the following code:
```
if ( !tmp ) error("Could not parse %s: %s\n", list_def, list[i]);
if ( min!=max && (bin->bins[i]<min || bin->bins[i]>max) )
    error("Expected values from the interval [%f,%f], found %s\n", list[i]);
```
However, there seem to be two separate errors in the code, which should be instead:
```
if ( *tmp ) error("Could not parse %s: %s\n", list_def, list[i]);
if ( min!=max && (bin->bins[i]<min || bin->bins[i]>max) )
    error("Expected values from the interval [%f,%f], found %s\n", min, max, list[i]);
```
The code is only called from vcfstats.c so it only affects the `bcftools stats --af-bins <list>` command.

**Comment by pd3** [comment]
Thank you for noticing and reporting. This is now fixed, also added warnings suggested by @jmarshall and cleaned the rest  of the code.

**Comment by jmarshall** [comment]
Noticed that only one of @freeseek's originally spotted errors has been fixed. This one remains:

     if ( !tmp ) error("Could not parse %s: %s\n", list_def, list[i]);

should be `if (*tmp) …`.

**Comment by pd3** [comment]
Ah, did not notice before there were two errors.Thanks.
