### ISSUE TITLE
isec with more than 2 files

### ISSUE THREAD

**Issue by dariober** [samtools/bcftools#802]
Hi- The documentation for [isec](https://samtools.github.io/bcftools/bcftools.html) has this example:

```
bcftools isec -e'MAF<0.01' -i'dbSNP=1' -e- A.vcf.gz B.vcf.gz C.vcf.gz -p dir
```

I'm trying to reproduce it as it may do what I need but when I run it I get:

```
bcftools isec -e'MAF<0.01' -i'dbSNP=1' -e- A.vcf.gz B.vcf.gz C.vcf.gz -p dir
Expected two file names or one of the options --complement, --nfiles or --targets
```

Am I missing something or the documentation should be corrected?

(For the record, in my case I have 3 files for which I need the variants private to each file, common to each pair, common to all 3)

With:

```
bcftools --version-only
1.8+htslib-1.8
```

**Comment by pd3** [comment]
The documentation is incorrect, with three or more files the options suggested in the error message are required. So for example this should work:
````
bcftools isec -n +2 A.vcf.gz B.vcf.gz C.vcf.gz -p dir
````
