### ISSUE TITLE
bcftools call --format-fields

### ISSUE THREAD

**Issue by ju-cheng** [samtools/bcftools#804]
Hi there, may I know for now what format-fields are allowed to output for each sample? Are the fields of something like DP (coverage of the REF and ALT) and AF (ALT allele fraction) allowed? Thanks

**Comment by pd3** [comment]
Please see the usage and examples here
http://samtools.github.io/bcftools/bcftools-man.html#query
http://samtools.github.io/bcftools/howtos/query.html

**Comment by pd3** [comment]
The depth-related tags are generated by `mpileup`, see `bcftools mpileup --annotate ?` for list.
The `bcftools call` command leaves those untouched but can add GQ and GP.
