### ISSUE TITLE
Question about bcftools +fixref

### ISSUE THREAD

**Issue by bloosnail** [samtools/bcftools#806]
Hello, 

On the bcftools fixref page for the command:

bcftools +fixref test.bcf -Ob -o output.bcf -- -f ref.fa -m flip -d

It states:

"Note that this is an extremely unsafe operation and will most likely result in nonsense genotypes. If you decide to use it anyway, make sure to check the sanity of the result with the af-dist plugin."

I was wondering why this command is so unsafe, if A/T C/G SNPs are dropped by it? Is it still unsafe if both our data and the reference fasta are always hg19? The other two recommended commands may not work for much of our data, as a lot of it does not have RS IDs for all SNPs, and even more are not TOP compatible (or by the time we obtain the data this information is already lost). At least on the datasets I've tried the command so far it always seems to flip/swap SNPs correctly, at least based on their population-matched allele frequencies to 1000 Genomes. Thanks. 

Daniel

**Comment by pd3** [comment]
It is unsafe because people use it blindly and ignore other possible sources of the REF allele discrepancies, like different reference build. Otherwise it should be OK. I recommend to sanity check manually a random subset of the data to make sure it is doing the right thing.
