### ISSUE TITLE
 runs of autozygosity failed

### ISSUE THREAD

**Issue by raonyguimaraes** [samtools/bcftools#81]
I'm receiving the following message when running the roh command:

bcftools roh Exome_3_EDS.var.annotated.vcf.gz

This file was produced by: bcftools roh(0.2.0-rc10-22-g5d5f886)
The command line was:	bcftools roh Exome_3_EDS.var.annotated.vcf.gz

[1]Sample	[2]Chromosome	[3]Position	[4]p-value	[5]ROH
bcftools: vcfroh.c:585: set_pdg_from_PLs: Assertion `pl[j]<256' failed.

Does anybody could point me to the right direction to solve this problem :)

I can try reading this file vcfroh.c:585 but there's a long time i don't program in C

**Comment by mcshane** [comment]
the `roh` command has gone through a number changes since this issue was raised. I'm going to close this, but please reopen or open a new issue if there are still problems.

**Comment by mlpimsler** [comment]
Hello-

I have also used GATK and I am also getting the same fatal error for the same reasons (PL > 256). I have tried using the instructions provided here, and while it worked for roh command, I was wondering if there was any option or branch that would permit me to use bcftools call or other command.

>$bcftools call --multiallelic-caller --variants-only -O v Big_varied.allCombined.vcf -o Big_VariantsOnly.vcf

>Note: Neither --ploidy nor --ploidy-file given, assuming all sites are diploid
>Assertion failed: (PLs[j]<256), function set_pdg, file mcall.c, line 350.
>Abort trap: 6

Thanks.

**Comment by pd3** [comment]
Hi, did you mean to use `call` or `roh`? The first is intended for processing `samtools mpileup` output to produce variant calls, not really useful to run it on GATK output.
