### ISSUE TITLE
bcftools annotate add FORMAT/GL for every sample

### ISSUE THREAD

**Issue by YantingHuang** [samtools/bcftools#810]
I did not get enough information from manual page about this question. I would like to add this information from tab-delimited file. 
Could you give 1 or 2 example lines about how this file should be organized?

**Comment by garrett-stevens** [comment]
FWIW, I have a sample of this type of thing working. It's based off of the wiki here: https://github.com/samtools/bcftools/wiki/HOWTOs#annotate-from-bed and looks like this:
File called `annots.tsv` containing
```
1	752567	752567	FooValue1	12345
1	752722	752722	FooValue2	67890
```
Then run 
```
bgzip annots.tsv
tabix -s1 -b2 -e3 annots.tsv.gz
```
Now a file called `annots.hdr` containing
```
##FORMAT=<ID=FOO,Number=1,Type=String,Description="Some description">
##INFO=<ID=BAR,Number=1,Type=Integer,Description="Some description">
```
And an input VCF (`in.vcf`) that looks like this
```
##fileformat=VCFv4.1
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE1
1	752567	.	A	C	.	.	.	.	.
1	752722	.	G	A	.	.	.	.	.
```
Then run
```
bcftools annotate -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf
```
And you get
```
##fileformat=VCFv4.1
##contig=<ID=1,length=249250621,assembly=b37>
##FORMAT=<ID=FOO,Number=1,Type=String,Description="Some description">
##INFO=<ID=BAR,Number=1,Type=Integer,Description="Some description">
##bcftools_annotateVersion=1.8+htslib-1.8
##bcftools_annotateCommand=annotate -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf; Date=Thu Jun 14 20:17:43 2018
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE1
1	752567	.	A	C	.	.	BAR=12345	FOO	FooValue1
1	752722	.	G	A	.	.	BAR=67890	FOO	FooValue2
```
Hopefully this gets you going in the right direction.

**Comment by YantingHuang** [comment]
Thank you Garrett. It is a very detailed explanation. 
Two more questions on your comment:
1. For multiple samples, if I would like to add multiple FOO field for sample1, sample 2, sample3...
How would bcftools annotate command be?
1	752567	752567	FooValue1(for sample1)	FooValue2(for sample2)	FooValue3(for sample3)    12345

2. I would add GL field which is composed of 3 floats (e.g. -0.353,-0.323,-1.544), I should specify this as string in the .hdr?

**Comment by garrett-stevens** [comment]
I'm not an expert, I just happened to have a working example, but here's my best guess:

1. I've never tried this, and I can't see any way to do it in the docs. It might not be supported. A possible workaround is to use the `--samples` option to annotate one sample at a time.

2. I think you can use `Number=3,Type=Float` in the header for that

**Comment by YantingHuang** [comment]
Thank you so much. I will try and if something works, I would share you with that.

**Comment by YantingHuang** [comment]
@garrett-stevens 

I found a way to do that.
if  I want to add 3 gl records to the vcf file, and the .tsv is like following (the last three columns are gl):
`1	233111951	-0.35,-0.24,-0.37	-0.21,-0.33,-0.85	-0.15,-0.88,-0.13`
Then just call 
`bcftools annotate -a annotation.tsv.gz -h annotation.hdr -c CHROM,FROM,FMT/GL -s GTEX-11DYG,GTEX-11EMC,GTEX-11GSO test_subset_sorted.vcf.gz > annotated.vcf.gz`
The key is to specify the samples to annotate using `-s` option and only one `FMT/GL` in the `-c` option is needed.

Moreover, `Number=3,Type=Float` is necessary and correct for .hdr (thanks again!)

Yanting

**Comment by biotechnepal** [comment]
Hi @garrettjstevens, 

I wonder what do we have to modify in this command "bcftools annotate -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf" if we want to annotate FMT/FOO  to SAMPLE2 (let's say the in.vcf has two samples) but not to SAMPLE1. 

I did like this "bcftools annotate -s SAMPLE2  -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf" but it again annotated FMT/FOO to SAMPLE1 instead of SAMPLE2.

KR,
Rajendra
