### ISSUE TITLE
Bcftools index with BAI.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#812]
The bcftools index help states that CSI is the default and that -c enables CSI, which makes me wonder A) why the option exists and B) how you can get anything other than CSI.  The code for -c just sets tbi to 0.

Is there no support for BAI in bcftools?  Given (I think) htsjdk doesn't support CSI, how does this work with sharing data between htsjdk and Bcftools?  Is it simply that everyone uses TBI indices and VCF? (I'm getting lost at this stage in a twisty maze of index formats, all alike.)

My purpose in the question is I'm adding code to htslib to generate BAI and CSI (so far) indices on the fly while writing BAM and BCF, but I cannot validate my bcf.bai output because I cannot figure out how to generate a legit one.

**Comment by mcshane** [comment]
I have never seen anywhere a `vcf.gz.bai` or `bcf.bai` file before.

**Comment by jkbonfield** [comment]
Ah ok, so I'll ditch my new logic that writes them.

I assume CSI predates BCF then (but not BAM, which is why we don't use it there by default)?

**Comment by mcshane** [comment]
> I assume CSI predates BCF then (but not BAM, which is why we don't use it there by default)?

I think that is right.

**Comment by lh3** [comment]
CSI was designed for BCFv2. They were implemented around the same time in 2012. BAI was described in the very first SAM spec released in 12/2008.

**Comment by lh3** [comment]
> Given (I think) htsjdk doesn't support CSI, how does this work with sharing data between htsjdk and Bcftools?

htsjdk doesn't work with BGZF'd BCFv2, I believe. Probably it doesn't support new features in BCFv2.2, either.

**Comment by jmarshall** [comment]
Relevant HTSJDK issues are samtools/htsjdk#447 (and PR samtools/htsjdk#1040), samtools/htsjdk#946, and samtools/htsjdk#628.

**Comment by jkbonfield** [comment]
If if htsjdk supports BCFv1, then what does it use as an index given it also doesn't yet have CSI support.  Do they have yet another index format? (We already have 4 for bgzf, I hope there's not a 5th!)

Anyway, I've made my code compatible with the rest of bcftools and gone CSI only.  I'm closing this as it's now just a discussion (and it was really just a question - the only "issue" could be documentation perhaps).
