### ISSUE TITLE
merge fails with message incorrect number of FORMAT fields but number is good

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#815]
bcftools Version: 1.8

Command:

`bcftools merge x.vcf.gz y.vcf.gz -O v -o m.vcf`

Output:

`Incorrect number of OBAM fields (6) at chr1:1755383, cannot merge.`

That message appears to be incorrect.

x.vcf.gz and y.vcf.gz are attached.

[x.vcf.gz](https://github.com/samtools/bcftools/files/2112998/x.vcf.gz)
[y.vcf.gz](https://github.com/samtools/bcftools/files/2112999/y.vcf.gz)

Here is OBAM format line:

```
##FORMAT=<ID=OBAMRC,Number=A,Type=String,Description="Whether the variant can be one of the given REF/ALT artifact mode complements.">
```

Here are deparsed FORMAT and SAMPLE fields from the only data line in each VCF file, they all appear to have the correct number of values, and in particular, OBAM has one value in each case, and the number of alternate alleles is 1 too:

```
|    GT                  |  AD                  |  AF                  |  F1R2                |  F2R1                |  MBQ                 |  MFRL                |  MMQ                 |  MPOS                |  OBAM                |  OBAMRC              |  OBF                 |  OBP                 |  OBQ                 |  OBQRC                |  SA_MAP_AF           |  SA_POST_PROB      |
|    0/0                 |  104,0               |  0.014               |  48,0                |  56,0                |  0                   |  153,0               |  0                   |  0                   |  false               |  false               |  .                   |  .                   |  .                   |  .                    |  .                   |  .                 |
|    0/1                 |  10,3                |  0.231               |  7,1                 |  3,2                 |  26                  |  129,0               |  60                  |  20                  |  true                |  false               |  0.333               |  0.004672            |  100                 |  31.44                |  0.182,0.212,0.231   |  0.023,0.02,0.957  |
|    GT                  |  AD                  |  AF                  |  F1R2                |  F2R1                |  MBQ                 |  MFRL                |  MMQ                 |  MPOS                |  OBAM                |  OBAMRC              |  OBQ                 |  OBQRC               |  SA_MAP_AF           |  SA_POST_PROB         |                      |                    |
|    0/0                 |  17,0                |  0.028               |  7,0                 |  10,0                |  0                   |  153,0               |  0                   |  0                   |  false               |  false               |  .                   |  .                   |  .                   |  .                    |                      |                    |
|    0/1                 |  175,76              |  0.311               |  104,40              |  71,36               |  26                  |  129,141             |  60                  |  20                  |  false               |  false               |  44.4                |  100                 |  0.293,0.283,0.303   |  0.007642,0.022,0.971 |                      |                    |
|
```

**Comment by pd3** [comment]
It turns out strings are not fully supported in FORMAT fields yet. This is not a trivial thing to add, but will be added. If you have control over the generated fields, is it possible to use numeric fields instead of strings in the meantime? In the test case you provided the tag is either "false" or "true", but one could easily work with "0" and "1" instead. In fact, integer values are preferable for several reasons: they will compress better, they will be faster to parse, and they will be also faster to process during the merging.

**Comment by tedtoal** [comment]
Thanks for the info.

I don't have control over the format because it is generated by a GATK tool (Mutect2).  My solution was, since I didn't use the OBAM and other fields, to remove most of the Mutect2 fields before using bcftools merge.

**Comment by pd3** [comment]
The support for merging FORMAT strings has been now added, with the exception of Number=G tags.

**Comment by janinl** [comment]
Hi @pd3 
I'm not sure if I should open a new ticket, but I identified that the commit 0668ecc for this ticket actually broke the merge of a field
`##FORMAT=<ID=FT,Number=1,Type=String>`
I'm running `bcftools merge` on 100 bcf files containing 100 samples each.

In my input files, FT takes 2 values: `.` or `LowGQX`.
With this commit, the `.` values still get correctly merged, but the `LowGQX` ones end up with random extra non-ascii characters in the output.

Sorry I know this is a bit vague as a bug report but I don't have permission to export the data.

Thanks

**Comment by pd3** [comment]
This seems related to #1031. Can you check if this commit https://github.com/samtools/bcftools/commit/d68da18fb066b277e99315c642fc1e577ede9f0f solves the problem also for you?
