### ISSUE TITLE
Problem during installing htslib-1.8

### ISSUE THREAD

**Issue by BiodeB** [samtools/bcftools#818]
I was trying to install htslib as a dependency of Auggustus in Ubuntu 16.04. Though, I have followed the following steps,
$cd htslib/
$autoheader
$autoreconf
$./configure
$make
$make install
I got stuck in the last step ($make install); it was showing that,

mkdir -p -m 755 /usr/local/bin /usr/local/include /usr/local/include/htslib /usr/local/lib /usr/local/share/man/man1 /usr/local/share/man/man5 /usr/local/lib/pkgconfig if test -n ""; 
then mkdir -p -m 755 ; fi install -p -m 644 libhts.so /usr/local/lib/libhts.so.1.8 install: cannot remove '/usr/local/lib/libhts.so.1.8': Permission denied Makefile:454: recipe for target 'install-so' failed make: * [install-so] Error 1
I couldn't understand what is the problem, PLEASE HELP.

**Comment by jkbonfield** [comment]
The "permission denied" error is because you do not have write access to /usr/local, likely because this is owned by "root".

You can change where it installs to by using `./configure --prefix=/some/other/location`.

**Comment by BiodeB** [comment]
Yes, the problem has been solved.

**Comment by ZIWEI-WONG** [comment]
> The "permission denied" error is because you do not have write access to /usr/local, likely because this is owned by "root". (Although it sounds like there may even be a version 1.8 in there already.)
> 
> You can change where it installs to by using `./configure --prefix=/some/other/location`.

Hi, jkbonfield, I encountered the same problem even when I logged in with 'root' account.. it confused me
