### ISSUE TITLE
-e of bcftools filter does not work when used with multiple conditions (probably a bug)

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#822]
Hi,

I am using bcftools v1.6 and just noticed something. May be it should be checked in the latest version as well, but am posting here to check if I did anything wrong.

bcftools filter -e 'QD < 10 & FS > 60 & SOR > 2 & MQ < 50 & MQRankSum < -2.5 & ReadPosRankSum < -2.5' test.vcf.gz >result.vcf

bcftools filter -i 'QD >= 10 & FS <= 60 & SOR <= 2 & MQ >= 50 & MQRankSum >= -2.5 & ReadPosRankSum >= -2.5' test.vcf.gz >result.vcf

Both the above mentioned operations should give me the exact same result. But, -e does not filter/exclude anything. When each condition is used separately with -e, it works fine. Should it work that way or is it a bug?

**Comment by pd3** [comment]
The logic in your examples is incorrect. The opposite of `-i 'A<x && B<y'` is `-e 'A>=x || B>=y'`.

Once corrected, the expressions still may give different results, consider how the expressions evaluate for missing values.

There were fixes and improvements in filtering, I'd encourage you to update to the latest version which will be released next week.

**Comment by prasundutta87** [comment]
You are right. I had some missing values in ReadPosRankSum and got different results with -e and -i as the missing values were included in my filtered variant set using -e and not with -i.

How can we adjust our command for missing values in such cases?

Furthermore, when I was testing with a small dataset, I got the same number of variants after I applied filtering on these conditions:

-i 'FS <= 60'|bcftools view -H|wc -l
-e 'FS > 60'|bcftools view -H|wc -l

**Comment by pd3** [comment]
With missing values, if `X=.` then both `X<10` and `X>=10` evaluate to FALSE. Note here were bugs in 1.6.

If FORMAT fields are not part of the expression, then the result is applied to the whole record. (The exact interpretation may depend on the command and is described in the documentation.)

**Comment by prasundutta87** [comment]
Thanks..yes it is solved..
