### ISSUE TITLE
Incorrect number of AD fields (3) at 0:3816, cannot merge.

### ISSUE THREAD

**Issue by Anuragbio** [samtools/bcftools#823]
I am using Version: 1.8-32-ge9c08eb (using htslib 1.8-32-g9cd85ab) of BCFtools and trying to merge two VCF files. I am getting the following error:

Incorrect number of AD fields (3) at 0:3816, cannot merge.

May you let me know how to resolve this error.

Best,
Anurag

**Comment by pd3** [comment]
This does not give enough information. Apparently the number of values at that position is incorrect for the AD tag. Check the definition in the VCF header and see if it is correct at the reported position.

**Comment by Asutu** [comment]
I'm having exactly the same issue with bcftools merge. The error message I got is:

`Incorrect number of AD fields (3) at scaffold1:783, cannot merge.`

Looking at the header line for this field and the line causing trouble, we see this:

```
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">
scaffold1	783	.	T	G	824.855	PASS	AB=0.4375;ABP=5.18177;AC=2;AF=1;AN=2;AO=28;CIGAR=1X15M;DPB=64;DPRA=0;EPP=5.80219;EPPR=7.89611;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=60;NS=1;NUMALT=2;ODDS=26.279;PAIRED=0.928571;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1010;QR=591;RO=16;RPL=13;RPP=3.32051;RPPR=11.6962;RPR=15;RUN=1;SAF=16;SAP=4.25114;SAR=12;SRF=13;SRP=16.582;SRR=3;TYPE=snp;ALLELICPRIMITIVE	GT:GQ:DP:AD:RO:QR	1|1:114:64:16,20,28:16:591
```

The VCF specs define the following:

`If the field has one value for each possible allele (including the reference), then this value should be ‘R’.`

which seems to be appropriate for the FORMAT AD field and in agreement with our VCF header line. However, in this example I guess the bcftools error comes from the fact that only one alternative allele is represented in ALT. Is this assumption correct?

The VCF file originally had primitive alleles which were decomposed with the vcflib tool vcfallelicprimitives.

Cheers,
Pedro

**Comment by pd3** [comment]
That's correct. There are three AD values but only two alleles, one REF and one ALT. Either change AD definition to `Number=.` or remove the tag completely using `bcftools annotate -x`.

**Comment by pd3** [comment]
I think this can be now closed.

**Comment by dalmiaa** [comment]
> As suggested, changing the AD definition from `Number=R` to `Number=.` solved this issue, and bcftools was able to merge the VCF files.
> 
> Thanks,
> P

Thank you! Could you please elaborate on how one does this?

**Comment by pd3** [comment]
```
# print the header
bcftools view -h file.vcf > header.txt

# edit
vi header.txt

# replace the header
bcftools reheader -h header.txt -o fixed.vcf file.vcf
```
