### ISSUE TITLE
Issue with space in filter name

### ISSUE THREAD

**Issue by jasongallant** [samtools/bcftools#824]
Hello,

I'm trying to subset a large VCF file produced by GATK.  The filters have spaces in their names, which causes bcftools to error with:

[W::vcf_parse] FILTER 'reccomended hard filter SNPs' is not defined in the header

I can verify that this is indeed specified in the header.  The problem can be resolved on a much smaller file and editing the filter name and each occurrence of the filter to exclude whitespace.

Curious if this is an easy patch to prevent future issues, or are we better naming our filters without spaces?

**Comment by pd3** [comment]
The VCF specification does not allow spaces in FILTER names. Best is to write a small script to substitute the spaces in FILTER names for underscores and raise an issue with GATK. 
I'd rather not patch poor naming decisions in bcftools.
