### ISSUE TITLE
vcfannotate.c apparent vector_end bug

### ISSUE THREAD

**Issue by jmarshall** [samtools/bcftools#828]
Is this really supposed to only set 50% of the entries to vector_end?

https://github.com/samtools/bcftools/blob/bd4a5eb9329af56f7fed0d766303d30c431d7af2/vcfannotate.c#L1381-L1382

```
gcc -Wall -g -O2 -I. -Ihtslib-1.9   -c -o vcfannotate.o vcfannotate.c
vcfannotate.c:1382:94: warning: variable 'j' is incremented both in the loop
      header and in the loop body [-Wfor-loop-analysis]
  ...j<ndst1; j++) { bcf_float_set_vector_end(ptr_dst[j]); j++; }
```

**Comment by pd3** [comment]
No, not intended. Thank you for noticing. Fixed now.
