### ISSUE TITLE
bcftools isec does not recognize a bgzf file

### ISSUE THREAD

**Issue by annat22** [samtools/bcftools#833]
Hello,
I'm using bcftools/1.8 to filter a vcf.gz file with this command
bcftools view --min-af 0.1:minor \
	--min-alleles 2 --max-alleles 2 --types snps \
	--no-header \
    -Oz -o Afile_filtered.vcf.gz A-file.vcf.gz

I then try to find the intersection between Afile_filtered.vcf.gz and Bfile.vcf.gz
I get this Warning: no BGZF EOF marker; file may be truncated
and then it halts saying unknown file type
When I check Afile_filter with htsfile it does recognize it as BGZF-compressed sequence data
Where could be the problem? How may I be able to find it?

Thanks

**Comment by pd3** [comment]
The option `--no-header` is the problem. Without the header the file is not a valid VCF and the program runs into problems.

**Comment by annat22** [comment]
Thanks. I removed it because it was running into problems with the header, but I guess I have to fix the header then. The concat option seems to work fine without the header, btw.

**Comment by pd3** [comment]
Some modes of operations are more tolerant than others, but one should not rely on it. I'll close the issue now as the problem seems resolved, reopen if not.
