### ISSUE TITLE
Incorrect number of QSS fields (2) 

### ISSUE THREAD

**Issue by DadongZ** [samtools/bcftools#834]
I got an error message`Incorrect number of QSS fields (2) at 1:3681211, cannot merge.` when I was running the `bcftools merge`:
```
bcftools merge --file-list vcffilelist.txt \
    --force-samples \
    --apply-filters PASS \
    --output /data1/workspace/DCI/Kirsch/Yvonne.Mowery/RNASeq-WES/WES/neoantigen/MAF/tmp/Lee-WES_2018.vcf \
    --regions-file /data1/Staging/S0276129_Padded-mm9tomm10-NoChr.bed\
    --output-type v \
    --threads 4
```

Any suggestions?

**Comment by pd3** [comment]
Just added some hints how to troubleshoot this here http://samtools.github.io/bcftools/howtos/FAQ.html. Please reopen if this does not solve the issue.

**Comment by DadongZ** [comment]
@pd3 I am not able to fix the issue following the instructions in your link.

**Comment by DadongZ** [comment]
@pd3 why you closed the issue without being solved? I can't reopen it.

**Comment by pd3** [comment]
Sorry, it looks a problem with your VCF, not bcftools, that's why I closed the issue.
