### ISSUE TITLE
reheader is not changing the sample names

### ISSUE THREAD

**Issue by zillurbmb51** [samtools/bcftools#838]
Hi there,
I was trying to rename my samples in the vcf file using 
`[zillur@hybrid july12]$ bcftools reheader -s 59 59.vcf -o 59s.vcf

[zillur@hybrid july12]$ bcftools query -l 59s.vcf

20

[zillur@hybrid july12]$ bcftools query -l 59.vcf

20

`
What I am doing wrong? Is there any way to change sample names in the vcf file?
Thanks in advance.
Best Regards
Zillur

**Comment by pd3** [comment]
The argument to `-s` is a file with the list of samples, please see the documentation http://samtools.github.io/bcftools/bcftools-man.html#reheader
