### ISSUE TITLE
option --allow-undef-tags for bcftools's view

### ISSUE THREAD

**Issue by NatShar** [samtools/bcftools#839]
Hi,
I need to sample-subset existing .vcf but some tags in the FORMAT fld that are not defined in the header do allow me to do so. I do not want to update/change the original vcf, only to subset it.

Can option --allow-undef-tags be added to the view 
or is there another way to subset the file
or to make view less sensitive to undefined tags in the FORMAT fld (it has all needed sample-specific info anyway)

Thanks

**Comment by pd3** [comment]
Either remove the tags using `bcftools annotate -x` or use `bcftools reheader` to fix the header. 
The feature you request will not be supported, as it is possible only for VCF, but not for BCF. In BCF all tags must be known at the time the header is written to the output.
