### ISSUE TITLE
The argument to -g not recognised. Expected one of hom/het/miss/^hom/^het/^miss, got "-c".

### ISSUE THREAD

**Issue by ashaneev** [samtools/bcftools#840]
Getting error message "The argument to -g not recognised. Expected one of hom/het/miss/^hom/^het/^miss, got "-c" while using  the following command. 
thank you.

**bcftools view -g -c sample1_300BP.bcf > sample1_300BP.vcf**

**Comment by pd3** [comment]
Have you checked the usage? The parameter `-g` requires an argument
````
-g,   --genotype [^]<hom|het|miss>          require one or more hom/het/missing genotype or, if prefixed with "^", exclude sites with hom/het/missing genotypes
````

**Comment by ashaneev** [comment]
ya. I checked it. but I'm little bit confused about the option.... 
Thankyou

**Comment by pd3** [comment]
You did not say what you are trying to do.  

The `|` character is a short way for "OR" and the square brackets say the character is optional and means negation.

So if you want everything except homozygous genotypes, use `-g ^hom`. Also take a look at the `-i/-e` filtering expressions.

**Comment by ashaneev** [comment]
Hi,

As i need to convert my bcf file into vcf. I converted it  with default
settings ( bcftools view test.bcf > test.vcf) as well as the following
command; bcftools call -mv test.bcf -Oz > test.vcf.gz

a huge size difference was there.I need all snps and indels present in my
sample.
Thankyou

**Comment by pd3** [comment]
The `-g` option is not needed for conversion from BCF to VCF. Also you don't need to convert to VCF before running the `call` command. This program is intended for processing the output `bcftools mpileup` by the way. Note that the program internally represents everything in the binary form, as BCF, therefore there is a performance penalty when working with VCFs. The huge difference comes from using an uncompressed output. Please check the `-O` option in the manual page http://samtools.github.io/bcftools/bcftools.html and some short tutorials here http://samtools.github.io/bcftools/howtos/index.html.
