### ISSUE TITLE
applying FMT/GQ>=40 filter in a multisample vcf file query

### ISSUE THREAD

**Issue by prasundutta87** [samtools/bcftools#841]
Hi,

I was wondering if I can be suggested what should be the best way to apply a filter based on genotype quality on a multi-sample vcf file. My aim is to only keep those samples whose GQ >=40. If it is not, it should become ./.

If I want to apply the above filter, is this the correct way?

bcftools filter -i 'FMT/GQ>=40' -S . <input_vcf> > <filtered_vcf>

When I tested the above code, samples where GQ is less than 40 also remained. Can I be explained how is this filter applied in a multi-sample VCF file? I believe the command is working as keep those variant sites where any one sample has a genotype quality >=40. Or else, the whole record is filtered. Correct me if I am wrong.

P.S. : Using bcftools 1.8

**Comment by pd3** [comment]
That is correct, the output is row-oriented, the entire row is always printed because otherwise the output would not be a valid VCF. 

If you'd be happy with a free-text output, you can use `bcftools query`, for example like this
````
bcftools query -f '[%CHROM:%POS %SAMPLE %GQ\n]' -i 'FMT/GQ>=40'`
````

**Comment by prasundutta87** [comment]
Thanks a lot.
