### ISSUE TITLE
Segmentation fault with bcftools annotate

### ISSUE THREAD

**Issue by tedtoal** [samtools/bcftools#843]
The following command, using bcftools v1.8, fails with a segmentation fault on a linux (Ubuntu) machine:

bcftools annotate -a test.bed.gz -c CHROM,FROM,TO,PON -O z -h test.txt test.vcf.gz >testOut.vcf.gz

I have attached the files.

[bcftools_annotate_bug.zip](https://github.com/samtools/bcftools/files/2202590/bcftools_annotate_bug.zip)

**Comment by jmarshall** [comment]
This is crashing while trying to print out an error message

> Could not parse PON at chr1:1755504 .. [chr19]

and was one of the things fixed as a consequence of #801.

That your `annotate` command was crashing mysteriously is a pretty good demonstration that correcting `error()` arguments was not just a theoretical concern! :smile:

**Comment by tedtoal** [comment]
Great, thanks, I'm glad I was able to prove that a correction was a good thing!  With that message, I found the problem - copy/paste of commands from console lost tabs, so annotation file had spaces not tabs.
