### ISSUE TITLE
plot-vcfstats error

### ISSUE THREAD

**Issue by pc-emory** [samtools/bcftools#846]
Hi,

I am getting an error for the plot-vcfstats command. I am using the output of 'bcftools stats' command ('test.vcf.gz.stats') as the input file for 'plot-vcfstats', and am running bcftools v1.8.

Do I need to do something differently?

=============================================
| => plot-vcfstats -s -T "test" -p /mydata /mydata/test.vcf.gz.stats

Parsing bcftools stats output: /mydata/test.vcf.gz.stats
Warning: Possible version mismatch, the definition line differs
	expected: # PSC	[2]id	[3]sample	[4]nRefHom	[5]nNonRefHom	[6]nHets	[7]nTransitions	[8]nTransversions[9]nIndels	[10]average depth	[11]nSingletons
	found:    # PSC	[2]id	[3]sample	[4]nRefHom	[5]nNonRefHom	[6]nHets	[7]nTransitions	[8]nTransversions[9]nIndels	[10]average depth	[11]nSingletons	[12]nHapRef	[13]nHapAlt	[14]nMissing
Plotting graphs: python plot.py
Traceback (most recent call last):
  File "plot.py", line 402, in <module>
    y1 = smooth(numpy.array([float(row[2]) for row in dat]),40,'hanning')
  File "plot.py", line 73, in smooth
    return y[(window_len/2-1):-(window_len/2)]
TypeError: slice indices must be integers or None or have an __index__ method
The command exited with non-zero status 256:
	python plot.py

 at /home/px/miniconda2/envs/ngs/bin/plot-vcfstats line 99.
	main::error('The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}') called at /home/px/miniconda2/envs/ngs/bin/plot-vcfstats line 287
	main::plot('HASH(0x1df59e8)') called at /home/px/miniconda2/envs/ngs/bin/plot-vcfstats line 69

**Comment by pd3** [comment]
Any chance you could attach the `test.vcf.gz.stats` file please?

**Comment by pd3** [comment]
Thank you. I was not able to reproduce the error on my platform, it looks like a version-specific issue. What version of python and matplotlib do you run?

**Comment by pc-emory** [comment]
| => python --version
Python 3.6.3 :: Anaconda, Inc.

>>> matplotlib.__version__
'2.2.2'

What do I need to do to resolve this?

thanks!!

**Comment by pc-emory** [comment]
So, what version of python, matplotlib, tectonic(?) do I need to make this run?

**Comment by valeriuo** [comment]
@pc-emory try using python 2. Python 3 division is floating point by default, which causes the non-integer indices.

**Comment by pc-emory** [comment]
Using python 2, and then reinstalling bcftools and matplotlib, I still get an error (plot-vcfstats.log):

"This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
restricted \write18 enabled.

kpathsea: Running mktexfmt pdflatex.fmt
I can't find the format file `pdflatex.fmt'!"

Do I need to install some other package too?

**Comment by valeriuo** [comment]
Try running `texconfig rehash` in a terminal window.

**Comment by pc-emory** [comment]
Hi Valeriuo,

Thanks for the response!

I am on a cluster and don't have root privileges. So, I get:

| => texconfig rehash
mktexlsr: /usr/share/texlive/texmf: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-config: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-dist: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-local//: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-var: directory not writable. Skipping...
mktexlsr: Done.

**Comment by pd3** [comment]
Thanks @pc-emory for the bug report and @valeriuo for your help with this. I added the python3 way of integer division, hopefully this solves the issue.
