### ISSUE TITLE
consensus -M --missing 

### ISSUE THREAD

**Issue by FatihSarigol** [samtools/bcftools#848]
Hello,
I first hoped that this new flag would let me call a site "N" for which there is no info in my vcf file instead of just copying the base in the reference, but as I see it's not doing that so I guess I misunderstood the words -skip- and -genotype-. Anyway, I'd like to ask if you are planning to bring a feature that lets the user do that (I know I could mask them with -m flag but then I'd need to generate a positions file for each sample's missing sites). In fact I am not sure for the downstream analyses doing which would be better as having plenty N's can also cause some problems, but when I take the reference without knowing the actual base in my sample that causes an underrepresentation of the difference; I was planning to compare both ways for doing a selection analysis in 14 species with mediocre sequencing coverage.
Thanks!

**Comment by pd3** [comment]
The `-M` option allows to take into account `./.` genotypes. Sites with REF=N can be skipped already using the `-i/-e` filtering options, for example using `-i 'REF!="N"'`.

**Comment by FatihSarigol** [comment]
Thank you, yeah that way it does work, good addition!
I was doing SNP calls from single sample alignments and couldn't find a way to end up with ./. for sites with no reads using bcftools and samtools **mpileup** and **call** (I think samtools **mpileup** -aa does that, but bcftools **call** skips them eventually), so I had first hoped it would let me call "N" the sites that the VCF totally skips without even calling ./. but by jumping to the next base with a read. 
Now going from the multiple sample path (which I guess is better anyway) for a site for which any of the samples has a read, the other samples that don't have any get ./. but if none of the samples has a read at all, they all still get the base of the reference with **consensus**, because **call** skips them (and the new recommended bcftools **mpileup** doesn't have the -aa setting of samtools anyway) so the sites become totally absent in the VCF. 
This is not a big issue for my sample comparison purpose as all would get N in that case, but still one may be curious if there is a way to retain those sites in the prior step as well. 
Many thanks!

**Comment by pd3** [comment]
This is now addressed by a new `-a, --absent` option. Please try it out and let me know in case of problems.

**Comment by ksw9** [comment]
Hi, Thank you for providing this --absent option. I'm wondering which version this option is available on? I couldn't find it on the below version: 
 bcftools 1.10.2
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
Thank you in advance!
