### ISSUE TITLE
mendelian plugin, output to stderr

### ISSUE THREAD

**Issue by SJChacko** [samtools/bcftools#850]
I'm running bcftools +mendelian to get counts of mendelian errors. The counts seem to be output to stderr where I'd have expected stdout, is that correct, or am I misunderstanding the output? 

(edited because I included a comment about man page for earlier version, sorry)

**Comment by pd3** [comment]
The program outputs to both stderr and stdout. VCF is sent to stdout while the summary numbers to stderr. I just improved this so that with the `-c` option, when no VCF is generated, the output goes to stdout by default or to the file specified with the `-o` option. I hope this helps
