### ISSUE TITLE
dosage plugin PL issue

### ISSUE THREAD

**Issue by bgb-ipl** [samtools/bcftools#851]
Hi,

I have a concern about the dosage plugin when it uses PL fields. Looking at the calc_dosage_PL function it seems you convert from PL using the exponential function. I think this is wrong and the correct formula should use the power of ten instead of the exponential so that the formula should be : 
```
vals[j] = pow(10.0, -0.1*ptr[j])
```

Using this little example from a GATK output : ```GT:AD:DP:GQ:PL	0/0:3,0:3:9:0,9,95```
bcftools 1.8 outputs : 0.3 while it I think the correct dose should be 0.111816. By the way, bcftools-1.9 outputs 2.1 which is another issue...

Best,

**Comment by pd3** [comment]
These are very silly bugs. Thanks very much for noticing and reporting. Both should be fixed now.
