### ISSUE TITLE
bcftools norm for SNPs

### ISSUE THREAD

**Issue by AlistairNWard** [samtools/bcftools#853]
Normalization is not complete for padded SNPs. For example, consider a joint called VCF with a multiallelic entry. This results in a REF allele of AC, and two ALT alleles of A, AA. If I subset to the sample containing ALT=AA, trim the alleles not present in the sample, I am left with REF=AC, ALT=AA. Using tools like vt, normalizing this variant will result in the expected REF=C, ALT=A and the variant coordinate updated. bcftools does not make this update, so downstream tools working with this VCF do not recognise the variant as a SNP. Is it possible to have the normalization return the left-aligned, shortest parsimonious representation of an allele?

Thanks!!

**Comment by pd3** [comment]
Thanks for reporting the bug, this should be fixed.

**Comment by pd3** [comment]
I was unable to reproduce the error. What version of bcftools are you using? If it's the latest version, can you provide a small test case?

**Comment by AlistairNWard** [comment]
Thanks for taking a look Petr. I was using bcftools v1.8, but I just tried using 1.9-26-g73a628e (using htslib 1.9-19-g6d3be93) and saw the same issue.

I might well be using an incorrect command, but this was what I used:

bcftools norm -m - test.vcf.gz | bcftools norm -D -

The offending entry started as:

chr21	5064056	.	CA	AA,C	3883.67	PASS	.	GT	0/1

and became:

chr21	5064056	.	CA	AA	3883.67	PASS	.	GT	0/1
chr21	5064056	.	CA	C	3883.67	PASS	.	GT	0/0

But I was assuming that the CA->AA would become C->A trimming off the flanking base that was required to encode the deletion. I added a vcf that contains this one entry that fails for me. Thanks again!

[test.vcf.gz](https://github.com/samtools/bcftools/files/2290272/test.vcf.gz)

**Comment by mcshane** [comment]
Think you probably need to give the second `norm` the reference (`-f`) otherwise it can't do the realignments. The option used to be mandatory so users would know, but maybe something has changed...

**Comment by AlistairNWard** [comment]
Thanks Shane. That does fix the issue. I had thought that since this required trimming from the right and no coordinate change, I wouldn't need the reference. But feeding in the reference does normalize properly. Thanks for the help.
