### ISSUE TITLE
query -f -i -r doesn't work

### ISSUE THREAD

**Issue by jjmmii** [samtools/bcftools#855]
I'm trying to query all samples with alt genotype (0/1 or 1/1) at one site. The following gives empty output:
`bcftools query -f'[%CHROM:%POS %SAMPLE %GT\n]' -i'GT="alt"' -r 2:190670539 test.vcf.gz`
(The long options also don't work:
`bcftools query --format '[%CHROM:%POS %SAMPLE %GT\n]' --include 'GT="alt"' --regions 2:190670539 test.vcf.gz` )
But when I omit the -i, it is apparent that several samples are alt:
```
$ bcftools query -f'[%CHROM:%POS %SAMPLE %GT\n]' -r 2:190670539  test.vcf.gz
2:190670539 sample1 0/0
2:190670539 sample2 0/1
2:190670539 sample3 0/0
2:190670539 sample4 0/1
2:190670539 sample5 0/0
2:190670539 sample6 0/0
2:190670539 sample7 0/0
2:190670539 sample8 0/0
2:190670539 sample9 0/1
2:190670539 sample10 0/0
2:190670539 sample11 0/1
2:190670539 sample12 0/1
2:190670539 sample13 0/1
2:190670539 sample14 0/0
```
But according to the manual, this is the way to print only samples with alternate (non-reference) genotypes:
`bcftools query -f'[%CHROM:%POS %SAMPLE %GT\n]' -i'GT="alt"' file.bcf`
although it didn't show an example with -r added.
Am I doing something wrong here?

**Comment by pd3** [comment]
Perhaps you are using an older version of bcftools?

**Comment by jjmmii** [comment]
Oh right! I updated to the latest version and it works now. I was using 1.3.1. Thank you pd3!
