### ISSUE TITLE
Soft filter using expressions and position

### ISSUE THREAD

**Issue by dmckean** [samtools/bcftools#857]
I don't think this need to be considered a feature request, just a workflow question.

The `CHROM` column is not available when using -i and -e expressions, is there a way to apply soft filters to specific chromosomes? I'm trying to add a call rate filter for autosomal variants, without dropping X and Y from the VCF altogether.

Something like `bcftools filter -i 'CHROM == "chrX" || CHROM == "chrY" || AN > 90' --soft-filter CALL_RATE` would be simple, but CHROM is not supported. Region and target arguments will remove X and Y sites from the output. I suppose CHROM isn't supported in expression arguments to prevent misuse where a block region or streaming target argument is more appropriate.

Right now I think my three options would be to

- Select autosomal sites with a region argument and concat chrX and chrY sites downstream ... `bcftools filter -R autosomes.bed.gz | bcftools concat  - <( bcftools view -r chrX,chrY ) # possibly with -a or --naive`
- Add a boolean info tag upstream to chrX and chrY variants and include that tag in the filter expression
- Save the soft filter to a separate file and bring it back in with `annotate` ... In my case, I'm not sure why this would preferable to `concat`

**Comment by pd3** [comment]
These workarounds are cumbersome. Just added support for CHROM in filtering expressions: 73a628e.
