### ISSUE TITLE
Replacing GT tag by custom tag

### ISSUE THREAD

**Issue by uitde007** [samtools/bcftools#861]
I'm trying to replace GT with an imputed genotype tag while keeping GTs missing in the imputed genotype tag (vcfannotategenotypes GT sets missing imputed genotype tag to missing GT):

`vcfannotategenotypes GTi`

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GTi,Number=1,Type=String,Description="Genotype from GTi.">

`bcftools annotate -a input.vcf.gz -c "FMT/GT:=FMT/GTi" input.vcf.gz`

[E::bcf_format_gt] Unexpected type 7
Aborted (core dumped)

**Comment by pd3** [comment]
This is now fixed by 90cca6a. Let me know if you encounter any problems.
