### ISSUE TITLE
Error in bcftools csq: *** Error in `bcftools': free(): invalid size: 0x0000000002736cf0 ***

### ISSUE THREAD

**Issue by BertBog** [samtools/bcftools#862]
I get an error when using bcftools csq to obtain the effect of mutations for a single gene. 
bcftools csq --output variants_csq.vcf --fasta-ref gtrV.fasta --gff-annot gtrV.gff variants.vcf.gz

I'm using samtools / bcftools version 1.9. The variants_csq.vcf file is generated but truncated at the second to last variant. And the following error is shown:
*** Error in `bcftools': double free or corruption (out): 0x000000000250b010 ***
Aborted (core dumped)

[variants.vcf.gz](https://github.com/samtools/bcftools/files/2282945/variants.vcf.gz)
[gtrV.zip (FASTA and GFF)](https://github.com/samtools/bcftools/files/2282955/gtrV.zip)

**Comment by pd3** [comment]
This bug was triggered by a variant starting at POS=1 and was caused by an integer underflow. It is now fixed. Thank you for reporting it and for the test case!
