### ISSUE TITLE
Use sample name in fasta sequence description line for bcftools consenus 

### ISSUE THREAD

**Issue by WimSpee** [samtools/bcftools#864]
Dear bcftools developers, 

I am trying to extract sequences for multiple samples for a region of interest. 

This can be done very convenient via this bash loop. 
```
for sample in `bcftools query -l input.bcf`
   do samtools faidx reference.fa Chr_01:12345-6789100000 | bcftools consensus input.bcf  -s $sample --missing ? --iupac-codes  >> ROI_sequences.fa
done
```

Converting the ROI_sequences.fa file to a user desired format fails on duplicate fasta description lines.  See the error at the end of this comment. 

Could you maybe by default or optionally include the sample name in the fasta description line? e.g. 
`>Sample_ABC_123|Chr_01:12345-6789100000`

This saves me from having to add the sample name to the description lines and also makes it easier to parse the concatenated fasta file via pyfaidx to any other user defined format.  (by pyfaidx not crashing on duplicate description lines).  

It's a minor nice to have issue but would make the bcftools consensus output easier to use without additional scripting for the above use case. 

Thank you

```
Python 3.4.5 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:47:47)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> vcf_path = 'input.bcf'
>>> roi_sequences_path = 'ROI_sequences.fa'
>>> from cyvcf2 import VCF
>>> from pyfaidx import Fasta
>>> samples = VCF(vcf_path).samples
>>> roi_sequences = Fasta(roi_sequences_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tools/general/app/anaconda-python-3.4/lib/python3.4/site-packages/pyfaidx/__init__.py", line 658, in __init__
    sequence_always_upper=sequence_always_upper)
  File "/tools/general/app/anaconda-python-3.4/lib/python3.4/site-packages/pyfaidx/__init__.py", line 310, in __init__
    self.read_fai(split_char)
  File "/tools/general/app/anaconda-python-3.4/lib/python3.4/site-packages/pyfaidx/__init__.py", line 338, in read_fai
    raise ValueError('Duplicate key "%s"' % key)
ValueError: Duplicate key "Chr_01:12345-67891000000"
```

**Comment by pd3** [comment]
I added a new `-p` option which allows to prefix the sequence name with an arbitrary string. I hope this helps.
