### ISSUE TITLE
bcftools csq - the fasta reference does not match the VCF REF

### ISSUE THREAD

**Issue by BertBog** [samtools/bcftools#869]
I'm having an issue with bcftools csq. I'm using the latest version (1.9), 
I'm trying to check the mutation consequences for mutations in one specific gene sequence.

When I use the following command:
`bcftools csq --output variants_csq.vcf --fasta-ref wzx1_5.fasta --gff-annot wzx1_5.gff variants.vcf.gz`  

I get the following error message: 
`Error: the fasta reference does not match the VCF REF allele at wzx1_5:1473 .. G`

Even though the mutation reference nucleotide matches the reference:
`samtools faidx wzx1_5.fasta wzx1_5:1473-1473`
`>wzx1_5:1473-1473`
`G`

I also used bcftools norm to check against the reference which did not flag / remove any of the variants (with --check-ref option). Bcftools consensus also worked fine. 

I've attached the test files (VCF, GFF and VCF) in this ZIP 
archive: [bcftools_issue.zip](https://github.com/samtools/bcftools/files/2302345/bcftools_issue.zip)

**Comment by pd3** [comment]
This is now fixed. Thank you for the bug report and the test case
