### ISSUE TITLE
create or edit INFO fields (feature request)

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#87]
Is it possible to edit or create new info tags using expressions?

I noticed some facility in the plugins but it would be nice to have something general.

For example, calculating the mean alt allelic fraction, genotype counts, case-control counts, rounding very large floats etc etc

**Comment by jrandall** [comment]
Is it possible the right way to do this *is* with `awk`? Perhaps `bcftools` could have a user-friendly way to pipe output into something like `awk` and back again? I guess `bcftools query` can already get records into a suitable format for `awk` to process and calculate new tags, but we may not have an easy way to go back to VCF/BCF.

**Comment by pasculorente** [comment]
Hi, this feature can be very convenient. I've been trying to merge a few INFO fields into one and a very straightforward way to do it would be to take advantage of the powerful expression system of bcftools. In my case, all fields are _Number=1_ and I want to select the first non null. 

`bcftools annotate --compute 'INFO/TARGET<-first(INFO/A,INFO/B,INFO/C)' input.vcf.gz`

The INFO/TARGET can be already defined into header or added with **--header-lines**.

Of course this would also require the implementation of the function _first_, which returns the first non null element, or null if all elements are null. I know for this case I can call annotate multiple times, it's just an example.

This feature can also help in the re-computation of math columns (like AF), generation of flags (even new FILTERS) or extracting values from arrays.

**Comment by stevekm** [comment]
I have an example [here](https://github.com/mskcc/pluto-cwl/blob/7eb2b0a4d37018142233d770595ac2e00376dab4/cwl/samples_fillout_workflow.cwl#L247-L303) where I create a new `INFO` field by using a combination of `bcftools query` and `annotate`. In this case, I wanted to add the INFO tag `SRC` to each variant, with the value being a comma-delimited list of samples that match criteria `AD>0`. 

As suggested, it is a pretty complicated operation to implement.

However, I now need this same functionality again, but for creating a custom `FORMAT` field for each sample in the vcf. In this case, I want to add a boolean for each sample to tell if it matched the criteria of `AD>0`. So far, I have not been able to figure out how to do this. Its not clear to me if this is possible or not?

**Comment by pd3** [comment]
The FORMAT fields can be filled with `bcftools annotate` as well. Another option would be to extend the `+fill-tags` plugin to work on FORMAT as well as on INFO. Currently it can do only very simple things like
```
bcftools +fill-tags in.bcf -Ob -o out.bcf -- -t 'DP:1=int(sum(DP))'
```
where
```
TAG:Number=Type(EXPR)
               Experimental support for user expressions such as DP:1=int(sum(DP))
               If Number and Type are not given (e.g. DP=sum(DP)), variable number (Number=.) of floating point
               values (Type=Float) will be used
```

**Comment by Nish9** [comment]
I find that it assumes the field mentioned in the expression to be a FORMAT field by default. Is it not meant to support both INFO and FORMAT fields in the expression?
```
$ bcftools +fill-tags panel_variants.somatic.filtered.AN.AC.vcf -Ov -o panel_variants.somatic.filtered.AF.vcf -- -t 'INFO/REF_AC=sum(DP4[0:1])'
Error: the field FORMAT/DP4[0:1] is not present
$ bcftools +fill-tags panel_variants.somatic.filtered.AN.AC.vcf -Ov -o panel_variants.somatic.filtered.AF.vcf -- -t 'INFO/REF_AC=sum(INFO/DP4[0:1])'
Error: the field FORMAT/INFO/DP4[0:1] is not present
```

**Comment by pd3** [comment]
@Nish9 It was not supported before, but should be now https://github.com/samtools/bcftools/commit/d68fe68551367809770f4128a4d9e3fc7fb0032c. Please try it out and let me know in case of problems.
