### ISSUE TITLE
Cannot merge files. Failed to open /path/data.vcf.gz: could not load index

### ISSUE THREAD

**Issue by MrLocuace** [samtools/bcftools#881]
Hello, I have 3 vcf.gz files A, B and C that I want to merge with bcftools. Each file was generated by:
1. Concatenating each individual chromosome vcf.gz file using concat
2. Uncompressed with mv
3. Compressed with bgzip
4. Indexed with tabix

Afterwards, I used merge A B to generate A_B.vcf.gz

However, I am unable to merge C with A, B or A_B, since I get this message:

Failed to open /path/C.vcf.gz: could not load index

When using concat, I also get this message only in C:
    [W::hts_idx_load2] The index file is older than the data file: path/c_i.vcf.gz.tbi

where the "i" in c_i.vcf.gz.tbi ranges from 1 to 22

Any idea about what is going on?

**Comment by MrLocuace** [comment]
Hi @finswimmer . Thank you for your response. I used mv because all other uncompressing options I tried (e.g. gunzip) produced a .gz.cpgz file, which could not be compressed with bgzip. Any suggestion?

I solved the indexing problem, it was a formatting mistake. Thank you

**Comment by MrLocuace** [comment]
Hi @wdecoster, do you have any suggestion for uncompressing and getting a .vcf file instead of a .gz.cpgz file?

**Comment by RamRS** [comment]
`.gz.cpgz` doesn't look like a common extension. Could you maybe `file outfile.gz.cpgz` or even `less outfile.gz.cpgz` and give us the output please?

**Comment by RamRS** [comment]
Also, could you check if the file is corrupted by any chance? The top result for `cpgz` is this page: http://osxdaily.com/2013/02/13/open-zip-cpgz-file/

**Comment by RamRS** [comment]
When you download the files next, can you check their `md5sum` before you work on them?

**Comment by MrLocuace** [comment]
Hi @RamRS, I did not download them. I generate them.

**Comment by RamRS** [comment]
>Concatenating each individual chromosome vcf.gz file using concat

Are you generating each "individual chromosome vcf.gz file"?

**Comment by finswimmer** [comment]
Hello again,

I have to repeat myself from the first post: Could you please provide the exact commands you use? Also show us how you have generated your ""individual chromosome vcf.gz file".

fin swimmer

**Comment by MrLocuace** [comment]
Hi @finswimmer, I solved the problem with the solution you gave me, after solving the indexing problem. I apologise for the inconvenient, I am new to these kinds of tools. Thank you very much

**Comment by RamRS** [comment]
Hey @MrLocuace , reminder to close the thread.
