### ISSUE TITLE
bcftools: plugins/fill-tags.c:432: process: Assertion `rec->n_allele < 8*sizeof(int)' failed.

### ISSUE THREAD

**Issue by sudhirjadhao** [samtools/bcftools#882]
I am running below command:
 bcftools +fill-tags Cases.vcf >Cases_MAF_bcftools.vcf

output:
bcftools: plugins/fill-tags.c:432: process: Assertion `rec->n_allele < 8*sizeof(int)' failed.
Aborted (core dumped)

There are some threads available regarding the same issue but I am not able to understand how to fix it.

Can you please help me to solve above issue

**Comment by pd3** [comment]
This is caused by too many alternate alleles, a limitation that is now fixed. Please try with the latest version from github, https://github.com/samtools/bcftools/commit/20a170e13a39e32cbae03490d869df44aaea32b4, let me know if you encounter any problems.
