### ISSUE TITLE
bcftools annotate not mapping src and dst sample names

### ISSUE THREAD

**Issue by jasper1918** [samtools/bcftools#884]
The manual(https://samtools.github.io/bcftools/bcftools.html#annotate) states that mapping from one sample name in the src VCF to the dst VCF is possible but I have been unable to use this feature.
` S, --samples-file FILE
subset of samples to annotate. If the samples are named differently in the target VCF and the -a, --annotations VCF, the name mapping can be given as "src_name dst_name\n", separated by whitespaces, each pair on a separate line.`

Example command:
```bcftools annotate -S file_cmp -a 20180907_stratify_NIST_vcfevalgt_dp10.vcf.gz -c FORMAT -O z STAR2_GATK.la.DP10_sorted_call.vcf.gz > STAR2_GATK.la.DP10_sorted_call.annotated.vcf.gz```

[test_files.tar.gz](https://github.com/samtools/bcftools/files/2380699/test_files.tar.gz)

**Comment by pd3** [comment]
Ah, this functionality got lost at some point. I fixed it and added a test. Thank you for reporting the bug and for the test case, it is fixed now.
