### ISSUE TITLE
False negative mutation existed in bcftools(v1.9) mpileup SNP/InDel calling

### ISSUE THREAD

**Issue by wangce1988** [samtools/bcftools#885]
Hello developers,

I'm using bcftools(v1.9) mpileup on Linux-x86_64 compiled by gcc-4.8.5.
I was running bcftools mpileup in SNP/InDel calling, and found a false negative SNP. This is a complex mutation with an insertion of TTA at chr17:37880996 and a SNP(G>T) at chr17:37880997, which can also be described as G>TTAT at chr17:37880997.
However, mpileup detected the insertion but not detected the SNP. The output near this location in vcf is as follows:

17      37880996        .       T       <\*>     0       .       DP=1431;I16=591,98,0,0,33741,1.82432e+06,0,0,34247,1.70449e+06,0,0,13862,316910,0,0;QS=1,0;MQSB=0.955204;MQ0F=0 
PL:DP:SP:ADF:ADR:AD     0,255,255:689:0:591,0:98,0:689,0
17      37880996        .       T       TTTA    0       .       INDEL;IDV=373;IMF=0.260657;DP=1431;I16=610,564,206,51,56840,3.96663e+06,13859,760741,58191,2.89006e+06,12811,639
075,24026,553210,5922,141312;QS=0.760344,0.239656;VDB=0.433235;SGB=-0.693147;MQSB=0.936529;MQ0F=0       PL:DP:SP:ADF:ADR:AD     170,0,255:1431:169:610,206:564,51:1174,257
17      37880997        .       G       <\*>     0       .       DP=1432;I16=582,141,0,0,35592,1.9537e+06,0,0,35891,1.78482e+06,0,0,14756,337572,0,0;QS=1,0;MQSB=0.841881;MQ0F=0 
PL:DP:SP:ADF:ADR:AD     0,255,255:723:0:582,0:141,0:723,0
17      37880998        .       G       <\*>     0       .       DP=1470;I16=595,150,0,0,36886,2.04327e+06,0,0,36980,1.83884e+06,0,0,15110,345944,0,0;QS=1,0;MQSB=0.877539;MQ0F=0
        PL:DP:SP:ADF:ADR:AD     0,255,255:745:0:595,0:150,0:745,0

In IGV, this site(sorted by base) looks like:
![default](https://user-images.githubusercontent.com/30822266/45528814-a1e81b80-b814-11e8-821a-4919c908f6f6.png)
Almost all base quality and alignment quality are high enough.

The command line I used in SNP/InDel calling is as follows:
bcftools  mpileup  -E  -O  v  -C  50  -q  30  -Q  30  -a  AD,ADF,ADR,DP,SP  -f  $referance.fasta  -d  100000  -L  100000  -F  0.0005  -R  target.bed  sampleID.target.rmdup.realigned.bam  >sampleID.raw.vcf

Please let me know if this is a bug or if I'm missing something.
Thanks！

Ce Wang

**Comment by pd3** [comment]
This looks like a bug or an artifact of the realignment. Does it help to disable BAQ, i.e providing `-B` instead of `-E`?

**Comment by wangce1988** [comment]
Yeah, this change really helped me. Thanks a lot! @pd3 
This is the new output:
17      37880996        .       T       <\*>     0       .       DP=1428;I16=798,143,0,0,46036,2.49374e+06,0,0,45572,2.21378e+06,0,0,19618,454288,0,0;QS=1,0;MQSB=0.391124;MQ0F=0        PL:DP:SP:ADF:ADR:AD     0,255,255:941:0:798,0:143,0:941,0
17      37880996        .       T       TTTA    0       .       INDEL;IDV=370;IMF=0.259104;DP=1428;I16=609,554,206,59,57045,3.97066e+06,14143,770543,57195,2.81997e+06,11952,539418,23812,548340,6061,144307;QS=0.77203,0.22797;VDB=0.43819;SGB=-0.693147;MQSB=0.936542;MQ0F=0  PL:DP:SP:ADF:ADR:AD     155,0,255:1428:140:609,206:554,59:1163,265
17      37880997        .       G       T,<\*>   0       .       DP=1429;I16=582,141,204,58,35616,1.95601e+06,12716,690438,35891,1.78482e+06,11779,529875,14756,337572,6104,147064;QS=0.744038,0.255962,0;VDB=0.000769325;SGB=-0.693147;RPB=0.434202;MQB=0;MQSB=0.452213;BQB=0.750293;MQ0F=0     PL:DP:SP:ADF:ADR:AD     163,0,255,255,255,255:985:4:582,204,0:141,58,0:723,262,0
17      37880998        .       G       <\*>     0       .       DP=1467;I16=816,214,0,0,50717,2.79519e+06,0,0,49685,2.40671e+06,0,0,21332,495236,0,0;QS=1,0;MQSB=0.631553;MQ0F=0        PL:DP:SP:ADF:ADR:AD     0,255,255:1030:0:816,0:214,0:1030,0
