### ISSUE TITLE
filter/query only on subset of samples

### ISSUE THREAD

**Issue by bsmith030465** [samtools/bcftools#886]
Hi,

I wanted to run a query on chrX on a bcf file that contains both male and female samples. I want to run a filter ('GQ>20 & DP>10') only for males in the file. How can I format my query such that the output contains both male and female samples, but the filter only on male samples?

The query I have below would just output only the male samples, correct?

bcftools -view -i 'GQ>20 & DP>10' chrX.bcf.gz -S maleIDs.txt -Ob -o chrX.filtered.bcf.gz

**Comment by pd3** [comment]
With the latest version, it is possible to provide a list of sample names and filter as 
`-i 'GQ[@samples.txt] > 20'`

**Comment by bsmith030465** [comment]
Thanks for the reply. I tried:

`bcftools view -i ‘GQ[@/mypath/samplesmaleIDs.txt] >= 20 &  INFO/DP[@/mypath/samplesmaleIDs.txt]  >= 10’ chrX.bcf.gz -Ob -o chrX.filtered.bcf.gz`

but got an error:

`Could not parse "@/mypath/samplesmaleIDs.txt". (Not a FORMAT tag yet a sample list provided.)
`

My 'samplesmaleIDs.txt' file is a list of sample ids, one id per line, e.g.
sample1
sample2
sample3

My bcftools version (downloaded a 2-3 weeks ago) is:

| => bcftools --version
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by finswimmer** [comment]
Hello @bsmith030465 ,

I guess this is your problem: 

`INFO/DP[@/mypath/samplesmaleIDs.txt]`

It has to be

`FORMAT/DP[@/mypath/samplesmaleIDs.txt]`

fin swimmer

**Comment by bsmith030465** [comment]
Hi,
Thanks. That worked! How can I verify that the output file actually filtered out the DP < 10 variants?

I tried to look at the DP field with both the filtered and unfiltered files:

bcftools query -f '%CHROM %POS[\t%DP]\n' chrX.bcf.gz | head -1
bcftools query -f '%CHROM %POS[\t%DP]\n' chrX.filtered.bcf.gz | head -1

However, in both cases, I seem to get identical results:
chrX 10454	3	0	13	35	16	18

chrX 10454	3	0	13	35	16	18

How can I verify that the DP < 10 will not be considered in the output file (chrX.filtered.bcf.gz)?

thanks!

**Comment by pd3** [comment]
Check this page for some examples: http://samtools.github.io/bcftools/howtos/filtering.html

**Comment by pd3** [comment]
I believe this has been solved by reading the documentation. Closing the issue now.
