### ISSUE TITLE
Group gvcf blocks by depth

### ISSUE THREAD

**Issue by finswimmer** [samtools/bcftools#889]
Hello, 

with the `-g` parameter one can define intervals for grouping non-variant sites as a gvcf blocks. For sites with the depth below the given values each one is printed seperatly.

I would find it useful to group these sites by depth.

Is there a way to do it? Otherwise this is an offical feature request :)

fin swimmer

**Comment by finswimmer** [comment]
Sounds good @pd3 . Any guesses when it might become available?

Thanks a lot.

fin swimmer

**Comment by finswimmer** [comment]
Hello @pd3 ,

I could test it now. But I can get it run correct. I tried this command:

```
$ bcftools +gvcfz input.gvcf -g'DP<10' 
Could not parse the expression: "DP<10"
```

And this:

```
$ bcftools +gvcfz input.gvcf -g'PASS:FORMAT/DP<10' 
Expected one FORMAT/GQ or FORMAT/RGQ value at 1:1020168
```

I have no GQ or RGQ in my file.

Am I doing something wrong?

fin swimmer

**Comment by pd3** [comment]
Ah, no, the problem is that the plugin makes an assumption about the presence of the GQ field. This will need to be generalized.

**Comment by pd3** [comment]
The plugin has been updated, it does not require neither GQ nor RGQ. I believe the issue is solved by this.
