### ISSUE TITLE
Bcftools CNV arguments

### ISSUE THREAD

**Issue by looxon93** [samtools/bcftools#890]
Hi,

I noticed problems with arguments in bcftools CNV. When I use --query-sample or --plot-threshold I get error: `unrecognized option '--plot-threshold'` although I just copied arguments from help of the tool. I assume that you are using underscore instead of dash in code?

Best,
Luka

**Comment by pd3** [comment]
Thank you for reporting the bug. The long option had changed and did not get updated. It should be fixed by 2dd4ea5.
