### ISSUE TITLE
samtools-0.1.8 pileup vs bcftools mpileup

### ISSUE THREAD

**Issue by jml96** [samtools/bcftools#891]
Hi,
I am adapting a variant calling pipeline to most recent versions of software.
The update worked fine for all the steps expect the one using samtools-0.1.8 pileup.
When I replace this command by bcftools mpileup I lose most of the reads.
I already tried to change the default parameters and the best result I can get is less than 50% of the depth observed with samtools-0.1.8 pileup uses the follwing command.
bcftools mpileup -Af my_reference.fa my_sample.bam.

Could you please let me know how can I obtain a vcf file without any filtering?
Thank you,
João

**Comment by pd3** [comment]
This is probably due to the changed behavior of `--max-depth`, which now does not increase automatically and honors the default of 250. Previously it would raise up to 8000, if I remember correctly.

**Comment by jml96** [comment]
Thank you Petr!
I tested this option while I was piping bcftools call -mOv and the variant I was using to test did not come out. Meanwhile I started using only bcftools mpileup.
