### ISSUE TITLE
bcftools 1.9 +fill-tags HWE Segmentation fault

### ISSUE THREAD

**Issue by wavefancy** [samtools/bcftools#894]
Dear developers,

When I use the fill-tags plugin for computing HWE, it will cause Segmentation fault (core dumped), however, this works for AC, AF, MAF et al. other tags.

zcat bug/hwe.seg.vcf.gz | bcftools +fill-tags -Ov -o bug/out.hwe.txt -- -t HWE
Segmentation fault (core dumped)

However, below works.
zcat bug/hwe.seg.vcf.gz | bcftools +fill-tags -Ov -o bug/out.hwe.txt -- -t AC

Test file please check [here](https://www.dropbox.com/s/0syehzu1l0e69ib/hwe.seg.vcf.gz?dl=0).

Best regards
Wallace

**Comment by pd3** [comment]
Thank you for the bug report and the test case. This is now fixed by cf72059
