### ISSUE TITLE
bcftools csq (core dumped): feature_set_seq: Assertion `aux->nseq < 256` failed.

### ISSUE THREAD

**Issue by nextgenusfs** [samtools/bcftools#895]
I think this is probably a GFF3 formatting issue -- but wondering what the error means so I can try to troubleshoot where the formatting is off. 

Thanks,
Jon
```
$ bcftools csq -f scaffolds.fasta -g reformatted.gff3 variants.vcf.gz
[W::bcf_hdr_check_sanity] GL should be declared as Number=G
Parsing reformatted.gff3 ...
bcftools: csq.c:675: feature_set_seq: Assertion `aux->nseq < 256' failed.
Aborted (core dumped)
```
Same error with the v1.9 release and the development branch
```
$ ./bcftools --version
bcftools 1.9-57-gcf72059
Using htslib 1.9-44-g80f3557
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pd3** [comment]
There was a limit on the number of sequences, it wouldn't work for assemblies. Please try it now.

**Comment by bnetoketim** [comment]
> I think this is probably a GFF3 formatting issue -- but wondering what the error means so I can try to troubleshoot where the formatting is off.
> 
> Thanks,
> Jon
> 
> ```
> $ bcftools csq -f scaffolds.fasta -g reformatted.gff3 variants.vcf.gz
> [W::bcf_hdr_check_sanity] GL should be declared as Number=G
> Parsing reformatted.gff3 ...
> bcftools: csq.c:675: feature_set_seq: Assertion `aux->nseq < 256' failed.
> Aborted (core dumped)
> ```
> 
> Same error with the v1.9 release and the development branch
> 
> ```
> $ ./bcftools --version
> bcftools 1.9-57-gcf72059
> Using htslib 1.9-44-g80f3557
> Copyright (C) 2018 Genome Research Ltd.
> License Expat: The MIT/Expat license
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> ```

I'm having exactly this error :
bcftools csq -f CYP_REFSEQ.fasta -g Homo_sapiens.GRCh38.101.chr_patch_hapl_scaff.gff3.gz -p a DVC_bcftools_flt_final.bcf -o DVC_bcftools_test_anno.vcf 
Parsing Homo_sapiens.GRCh38.101.chr_patch_hapl_scaff.gff3.gz ...
bcftools: csq.c:673: feature_set_seq: Assertion `aux->nseq < 256' failed.
Aborted (core dumped)
Please I need help!

**Comment by DewBudd** [comment]
I know saying "me too" isn't that helpful but I figure another example of the same error might help. I am using ~5000 reference sequences. It stops after the 256th one with the same error as bnetoketim.
`bcftools: csq.c:674: feature_set_seq: Assertion `aux->nseq < 256' failed. `

**Comment by jmarshall** [comment]
That error message has not existed since @pd3 fixed this issue in 2018. So I'm afraid these examples show only that you haven't updated to bcftools 1.10 (at least) or the current version.

**Comment by DewBudd** [comment]
I had assumed that since I had installed it with conda that I had the latest version but you are correct I have version 1.9. Thanks for the help.

**Comment by jmarshall** [comment]
Alas, that's a known conda problem that's been ongoing for months now: see conda/conda#9905, bioconda/bioconda-recipes#24199, and [this thread](https://twitter.com/jomarnz/status/1293515964466823168).

**Comment by bnetoketim** [comment]
> I had assumed that since I had installed it with conda that I had the latest version but you are correct I have version 1.9. Thanks for the help.

Hi @DewBudd, did it finally work for you?

**Comment by bnetoketim** [comment]
> That error message has not existed since @pd3 fixed this issue in 2018. So I'm afraid these examples show only that you haven't updated to bcftools 1.10 (at least) or the current version.

Thanks @jmarshall, it worked after I'd updated from bcftools 1.7-2 to bcftools 1.11
