### ISSUE TITLE
bcftools 1.9 not offering the option to add the DP in the FORMAT field

### ISSUE THREAD

**Issue by kalexiou** [samtools/bcftools#900]
Hi,

I couldn't find a way to add the depth-per-sample (DP) in the FORMAT fields of the VCF file that I generate with bcftools 1.9. However in the EXPRESSIONS part of the "bcftools call" manual (http://www.htslib.org/doc/bcftools.html#expressions), DP in the FORMAT field is used as a filter. How is bcftools extracting the depth-per-sample information in order to apply the filtering?

Thanks,
Kostas

**Comment by pd3** [comment]
This annotation must be generated by the mpileup step, type `bcftools mpileup -a ?` for a list of annotations.

**Comment by kalexiou** [comment]
Thanks for the fasta reply Peter!

Yes you are right. It is in the mpileup options.

Thanks
