### ISSUE TITLE
bcftools merge invalid character error

### ISSUE THREAD

**Issue by jorhodes** [samtools/bcftools#901]
Hi,

I'm trying to merge vcfs using bcftools 1.3.1 using merge, but I get the following error:

[E::vcf_parse_format] Invalid character 'f' in 'GT' FORMAT field

Any ideas on how to resolve this? Thanks

**Comment by pd3** [comment]
It seems the VCF is not valid. If you upgrade to the most recent bcftools and htslib, a more informative error message should be printed.

**Comment by finswimmer** [comment]
FYI: This is crossposted on [biostars](https://www.biostars.org/p/342008/#342033)

**Comment by pd3** [comment]
I am closing the issue, it seems to be caused by an invalid VCF.
