### ISSUE TITLE
How to access subfields of annotated VCF files

### ISSUE THREAD

**Issue by PedroBarbosa** [samtools/bcftools#903]
Hello,

I'd like to know how one can access the subfields added to the annotation field added in the INFO column. In my case, I'm interested in VEP output (with ANN field), how to extract, let's say, the consequence field?

`bcftools query -f "%INFO/ANN/Consequence\n" infile.vcf.gz` does not work.

Best,
PedroB

**Comment by pd3** [comment]
This is not possible, sorry. You'll have to stream through your own script to parse it and extract what you need.
