### ISSUE TITLE
bcftools: command not found

### ISSUE THREAD

**Issue by nupurgunwant** [samtools/bcftools#905]
I have downloaded both bcftools-1.9 and samtools-1.9 from [here](http://www.htslib.org/download/)
and installed using the following three commands in each folder:
```./configure --prefix=/where/to/install
make
make install
```
And have used samtools to convert my sam file to bcf file. 
But when in the next step, I want to convert bcf file to vcf file using bcftools and I use the command:
```bcftools view -vcg ../R1.bcf > R1.vcf``` I get the error ```bcftools: command not found```.
The same happens whenever I use any other bcftools command. Can you please tell me what I am doing wrong?

**Comment by pd3** [comment]
It looks like the `make install` command must have ended with an error? In any case, if there is a binary `bcftools` in your installation directory, you can either use the full path name or set the environment variable PATH accordingly. Check for example this post which explains how it works https://kb.iu.edu/d/acar.

**Comment by nupurgunwant** [comment]
Yes @pd3 , I got an error after ```make install``` earlier.
I did change the path now and my commands now were:
```./configure --prefix=/Users/nupurgunwant/Desktop/NGS/bcftools-1.9
make
make install```
and
```export PATH=/Users/nupurgunwant/Desktop/NGS/bcftools-1.9/bin:$PATH```

But I got this error
```[E::cg] unknown type
Accepted types are snps, indels, mnps, other```

Can you please tell me what am I doing wrong?
