### ISSUE TITLE
Wrong consensus call ?

### ISSUE THREAD

**Issue by cromozome** [samtools/bcftools#908]
I have generated a vcf from my bam file. for one position this is the vcf profile:
Reference    3315    .       A       G       111.008 .       DP=4083;VDB=0.982276;SGB=-0.693147;RPB=0.00428885;MQB=1;MQSB=1;BQB=0.00243132;MQ0F=0;AF1=0.5;AC1=1;DP4=1551,1075,307,240;MQ=60;FQ=114.016;PV4=0.214897,0.00011332,1,3.90683e-07 GT:PL   0/1:141,0,255

Now based on the above profile there are 1551 and 1075 forward and reverse reads supporting the reference allele and only 307 and 240 reads supporting the ALT allele, and yet when I do a consensus call it is the ALT allele that is reported in the consensus and not the Ref

Can anyone enlighten me if I am missing something ? or not interpreting the vcf information correctly ?

**Comment by pd3** [comment]
When you say "consensus", I suppose you mean whether the genotype should be homozygous reference (0/0), heterozygous (0/1) or homozygous alternate (1/1). 

Seeing this many alternate alleles at this position, the model must inevitably conclude it is a het. The other issue is whether this might be a mapping artefact as the proportion of alt vs ref reads significantly deviates from 0.5.

**Comment by cromozome** [comment]
Thanks! that made a lot of sense. This is viral genome so zygosity is kind of moot, but we are looking for quasispecies and this profile makes sense. We were looking to see if some variants consistently show up at greater prevalence then the allele in the reference sequence across different specimens and the "majority consensus" was a quick and dirty way to observe that

**Comment by pd3** [comment]
I am closing the issue as it seems resolved. Shout if not.
