### ISSUE TITLE
error with input file for mpileup command 

### ISSUE THREAD

**Issue by jullee** [samtools/bcftools#909]
I am using bcftools 1.9 on a Linux computer. When I go to use mpileup:

> /Linux/samtools-1.9/bin/bcftools mpileup -R -C 50 -E -q 20 -Q 20 -m 15 -F 0.9 -L 50 -Ov -f ref.fasta -o ANN0802.mpileup.vcf ANN0802.paired.bam 

I get this error:

> [E::hts_open_format] Failed to open file -C
> Could not parse the regions: -C

I've tried removing the -C 50, reordering where the input bam goes, etc. but always get an error about failing to open file "-.."

**Comment by garrettjstevens** [comment]
You need a file name after the `-R` option (for example, a BED file with the regions you want). It thinks whatever you are putting after `-R` is a file and tries to open it.
```
$ bcftools mpileup

Usage: bcftools mpileup [options] in1.bam [in2.bam [...]]

Input options:
...
  -R, --regions-file FILE restrict to regions listed in a file
...
```

See also: http://www.htslib.org/doc/bcftools.html#common_options

**Comment by jullee** [comment]
Thank you I thought that was the parameter to also ignore read groups...it
was a bit confusing in the list of parameters given by typing
"bcftools mpileup"
(almost looks like -R either restricts regions or ignores read groups when
the menu is displayed).

**Comment by pd3** [comment]
I believe this is resolved, closing the issue now.
