### ISSUE TITLE
bcftools sort cannot specify random temporary directories other than /tmp/bcftools-sort.XXXXXX

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#910]
I have an issue where I need to sort several VCF files and I cannot use the /tmp/ directory to do that as I don't have access.

By default, bcftools sort will create a temporary directory with mkdtemp("/tmp/bcftools-sort.XXXXXX");

If I want to specify something other than the /tmp/ directory though, such as ./bcftools-sort.XXXXXX, I don't get the same outcome as it will now create a temporary directory with mkdir_p("./bcftools-sort.XXXXXX") and this will not use the XXXXXX substring as a template to make the directory name unique.

I suggest two possible solutions:
1) Let the user only change the "/tmp" prefix for the output temporary directory when using the "-T" option
2) Have the code check whether there is an XXXXXX substring at the end of "args->tmp_dir" and if so use mkdtemp() rather than mkdir_p()

PS Also, to improve clarity, this line:
```
fprintf(stderr, "    -T, --temp-dir <dir>          temporary files [/tmp/bcftools-sort.XXXXXX/]\n");
```
should be changed to:
```
fprintf(stderr, "    -T, --temp-dir <dir>          temporary files [/tmp/bcftools-sort.XXXXXX]\n");
```
as mkdtemp() requires the last six characters to be XXXXXX.

**Comment by freeseek** [comment]
Alternatively, what samtools sort does seems more practical:
```
    if (tmpprefix.l == 0) {
        if (strcmp(fnout, "-") != 0) ksprintf(&tmpprefix, "%s.tmp", fnout);
        else kputc('.', &tmpprefix);
    }
    if (stat(tmpprefix.s, &st) == 0 && S_ISDIR(st.st_mode)) {
        unsigned t = ((unsigned) time(NULL)) ^ ((unsigned) clock());
        if (tmpprefix.s[tmpprefix.l-1] != '/') kputc('/', &tmpprefix);
        ksprintf(&tmpprefix, "samtools.%d.%u.tmp", (int) getpid(), t % 10000);
}
```
If the output file is specified, the temporary files have names such as OUTPUT.tmp.NNNN.bam and if the output is piped, they have names such as samtools.PID.TIME.tmp.NNNN.bam and "-T" specifies the output directory without using mkdtemp().

**Comment by pd3** [comment]
Yes, you are right, thank you for pointing this out. It's fixed now, mkdtemp() is used, not the samtools' pid way.
