### ISSUE TITLE
How to get the precise value of AF 

### ISSUE THREAD

**Issue by huizhen2014** [samtools/bcftools#914]
Hi, I found  the AF values of the vcfs by bcftools call only had 0.5 and 1. I think they were not the calculated value for the genotype, the frequency of genotype should be calculated by (FORMAT/AD[0:1])/(FORMAT/AD[0:0]+FORMAT/AD[0:1]), or using the DP4 infos. So I was wondering how I can directly get the precise value of AF with bcftools call process, thank you!

**Comment by pd3** [comment]
AF is the allele frequency of the alternate allele in genotypes among samples. What you thinking of is often denoted as VAF, Variant Allele Frequency, the number of alternate reads in the pileup.

**Comment by pd3** [comment]
Sorry to misleading you. The VAF annotation is not filled by any of the bcftools commands. Just wanted to explain why the AF you are seeing is not what you expected.

**Comment by huizhen2014** [comment]
Oh, I got you, thy!Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [samtools/bcftools] How to get the precise value of AF  (#914)From: Petr Danecek To: samtools/bcftools CC: Carlos Hui ,Author Sorry to misleading you. The VAF annotation is not filled by any of the bcftools commands. Just wanted to explain why the AF you are seeing is not what you expected.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/samtools/bcftools","title":"samtools/bcftools","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/samtools/bcftools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pd3 in #914: Sorry to misleading you. The VAF annotation is not filled by any of the bcftools commands. Just wanted to explain why the AF you are seeing is not what you expected."}],"action":{"name":"View Issue","url":"https://github.com/samtools/bcftools/issues/914#issuecomment-436288544"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/samtools/bcftools/issues/914#issuecomment-436288544",
"url": "https://github.com/samtools/bcftools/issues/914#issuecomment-436288544",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [samtools/bcftools] How to get the precise value of AF  (#914)",
"sections": [
{
"text": "",
"activityTitle": "**Petr Danecek**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@pd3",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"samtools/bcftools\",\n\"issueId\": 914,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"samtools/bcftools\",\n\"issueId\": 914\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/samtools/bcftools/issues/914#issuecomment-436288544"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406947155\n}"
}
],
"themeColor": "26292E"
}
]
