### ISSUE TITLE
What is the option bcftools mpileup/call to get minimum fields for VCF4.2 file?

### ISSUE THREAD

**Issue by yifangt** [samtools/bcftools#916]
How can I get the minimum fields of[ VCF4.2](http://samtools.github.io/hts-specs/VCFv4.2.pdf) file from SNP multiple allele calling for multiple samples (could be hundreds!)?
I used this cmd line to do the calling, 
```
bcftools mpileup -m 3 -C 50  -f ref.fasta -R bedfiles.list  -b bamfiles.list \
-a "AD,ADF,ADR,DP,SP,INFO/AD,INFO/ADF,INFO/ADR" \
-p | bcftools call -m --thread 4 -Oz -o samples.vcf.gz
```
but some of the fields described in **VCF4.2/4.3** format are not present. For example, **GL, AF, CN, CNQ** etc, which may be needed for filtering in later step.
1) What is the minimum/default fields of standard **VCF (v4.2+)** file from **bcftools mpileup/call** ?
2) How to add the fields that I want with the **-a option** as above? On top of the **-a options** above, I used **-a INFO/CN,INFO/CNQ**, but always got error **"Could not parse tag "INFO/CN" in "AD,ADF,ADR,DP,SP,INFO/CN,INFO/AD,INFO/ADF,INFO/ADR"** 
Appreciate any help.

**Comment by finswimmer** [comment]
Hello @yifangt ,

the only field that is is mandatory in the `INFO` and `FORMAT`column is `GT` in the `FORMAT`column. All others are optional and depends on the variant caller used. Some fieldnames has special meanings. So if a variant caller insert them, it has to take care of it.

Beside the filed that bcftools print by default you can define these ones:

```
$ bcftools mpileup -a \?

FORMAT annotation tags available ("FORMAT/" prefix is optional):

  FORMAT/AD  .. Allelic depth (Number=R,Type=Integer)
  FORMAT/ADF .. Allelic depths on the forward strand (Number=R,Type=Integer)
  FORMAT/ADR .. Allelic depths on the reverse strand (Number=R,Type=Integer)
  FORMAT/DP  .. Number of high-quality bases (Number=1,Type=Integer)
  FORMAT/SP  .. Phred-scaled strand bias P-value (Number=1,Type=Integer)

INFO annotation tags available:

  INFO/AD  .. Total allelic depth (Number=R,Type=Integer)
  INFO/ADF .. Total allelic depths on the forward strand (Number=R,Type=Integer)
  INFO/ADR .. Total allelic depths on the reverse strand (Number=R,Type=Integer)
```

fin swimmer

**Comment by pd3** [comment]
Just to clarify, not even FORMAT/GT is required. The "best practice" annotations depend on what you intend to do with the VCF. Also check the `fill-tags` plugin http://samtools.github.io/bcftools/howtos/plugin.fill-tags.html

**Comment by yifangt** [comment]
Thanks Petr! This seems to be what I was looking for.
What I was trying to do is to filter the resulted VCF file by different criteria from combination of the TAGs, but most of the TAGS are NOT there from my calling pipeline, and using the command by finswimmer only add 8 TAGS (5 FORMAT + 3 INFO). Here is my command line, for example:
```
$ bcftools mpileup -m 3 -C 50 -f ${REFERENCE} -R ${BEDFILE} -b ${BAMFILES} -a "AD,ADF,ADR,DP,SP,INFO/AD,INFO/ADF,INFO/ADR" -p | \
bcftools call -m -A -Oz -o ${OUTFILE} 
$ bcftools query -i'FMT/DP>10 & FMT/GQ>20' -f'%POS[\t%SAMPLE:DP=%DP GQ=%GQ]\n' ${OUTFILE} 
Error: the tag "GQ" is not defined in the VCF header 
```
> In order to use the BCFtools plugins, this environment variable must be set and point to the correct location:
> export BCFTOOLS_PLUGINS=/path/to/bcftools/plugins
> If a plugin still does not work, bcftools +name -vv explains why it would not load. 

As my bcftools was installed through conda, can I ask if this plugins should be installed only from source? Thanks a lot!

**Comment by yifangt** [comment]
I installed it thru conda. It seems working now!
Thank you!

**Comment by pd3** [comment]
@Rohit-Satyam Please do not append questions to unrelated threads, better is to open a new issue, here it can be easily overlooked.

As for your questions:
1) the usage page example suggests that `-t all` fills *almost* all available tags, not necessarily all
```
   # Fill (almost) all available tags
   bcftools +fill-tags in.bcf -Ob -o out.bcf -- -t all
```
I just pushed a commit [cd491e1](https://github.com/samtools/bcftools/commit/cd491e198546fd733ccab841bd28b10ca152d1ac) which extends the list to everything except TYPE and END.

2) the removal of INFO/AD is odd. It should not happen. If that's really the case, can you please provide a small test case together with the exact command you're using, and open this as a new issue? I am unable to reproduce the problem myself. I am assuming you are running the latest version.
