### ISSUE TITLE
How to work the "bcftools call -C trio"

### ISSUE THREAD

**Issue by huizhen2014** [samtools/bcftools#918]
Hello, although I have tried almost every kinds of parameters I could figure out to do the trio analysis with bcftools call -C trio , It still could not work. So, I was wonder if you can give me some tips to me. Here are my  scripts of analysis flow:
First, use bcftools mpileup to produce bcf files for mutiple bams ( a famlily)
bcftools mpileup -C 50 -P ILLUMINA -a "FORMAT/AD" -a "FORMAT/ADF" -a "FORMAT    /ADR" -a "FORMAT/DP" -a "FORMAT/SP" -R $bed -f $ref -O b P18027754LU01.sorted.dedup.bam P18027756LU01.sorted.dedup.bam P18027757LU01.sorted.dedup.bam >trio.combined.bcftools.bcf.gz
Then, make the PED file for my trios samples
cat > "SMA_Family_Pedigree.ped"<<-EOF
P18027754LU01 M
P18027756LU01 M
P18027757LU01 F
EOF
Last, use bcftools call to call the trio variants
bcftools call -C trio -m --ploidy GRCh37 -S "SMA_Family_Pedigree.ped" -R $bed -O z -o bcftools.trio.combined.raw.vcf.gz trio.combined.bcftools.bcf.gz

Indeed, the scripts above could not work, it the closest one to success. Thanks anyone who can help me.

**Comment by pd3** [comment]
I don't see anything obviously wrong. When you say it does not work, what does it mean? Do you get any error messages?

**Comment by pd3** [comment]
OK, I now see what's wrong, the sample file you've given is not a ped file. It should look like this:
````
ignored_column  daughterA fatherA  motherA  2
ignored_column  sonB      fatherB  motherB  1
````
The first column is ignored and the last indicates sex: 1=male, 2=female

**Comment by huizhen2014** [comment]
Thanks, it works now according to your instructions.
I see what confused me is the content in the website: http://samtools.github.io/bcftools/bcftools.html#common_options
File formats examples:
    sample1    1
    sample2    2
    sample3    2
or
    sample1    M
    sample2    F
    sample3    F

**Comment by pd3** [comment]
Yes, sorry for the confusion. I improved the formatting, hopefully it will be more clear now.
