### ISSUE TITLE
bcftools mpileup

### ISSUE THREAD

**Issue by ALFLAG** [samtools/bcftools#923]
Good evening.

I am working with a set of reads that do not align to an extremity of a viral genome.
In other words, the 10 first nucleotides of the viral genome are not covered by any reads.

Therefore when I call a consensus sequence, I expect the 10 first nucleotide of my consensus sequence being the N character. But it is not. The command to generate consensus just add the reference sequence instead of adding Ns.

here is the command line I'm using:

```
bcftools mpileup –O z –o file.pileup –q 5 –p –d 8000 –f reference.fasta file.bam &&
bcftools call –c --ploidy Y –O z –o file.vcf.gz file.pileup &&
tabix file.vcf.gz &&
bcftools consensus –f reference.fasta –o consensus.fasta file.vcf.gz
```
Would you help me to overpass this problem please ?

Regards,

Alexandre

**Comment by pd3** [comment]
This is currently not possible, all three commands output only sites with supporting evidence. This is necessary for bigger genomes (imagine human exome sequencing for example), huge files would be generated unnecessarily. Maybe there could be a new option added either to the call or consensus command, but it would require a volunteer to contribute the code.

**Comment by finswimmer** [comment]
`bcftools consensus` provide the `-m` parameter to mask region given in a region file.

One way I could imagine now, is to first run `samtools depth -aa` on the `bam` file, extract the uncovered region and convert it to one of the supported region file and use it during `bcftools consensus`.

fin swimmer

**Comment by ALFLAG** [comment]
Fin,
I had exactly he same idea. Thank you for conforting this thought.
I will try it soon and I'll come back here to debrief all of you.

Alexandre

**Comment by ALFLAG** [comment]
Hello,
So sorry for the very long delay of response.

The answer proposed by Fin works great and solved my problem.
Thanks a lot!

Alex
