### ISSUE TITLE
fixploidy plugin REF vs ALT choice

### ISSUE THREAD

**Issue by gungorbudak** [samtools/bcftools#924]
For a male individual's variant on chromosome X position 8769240, below is what we obtained for GT after `bcftools +fixploidy` with default `-p` using version 1.9

before
```
GT:PL:GQ:AD:DP  0/1:43,0,582:43:14,2:16
```
after
```
GT:PL:GQ:AD:DP 0:43,0,582:43:14,2:16
```

What is the actual reasoning behind the choice of `0` for GT here?

Thanks!

**Comment by pd3** [comment]
Nothing sophisticated, the logic is simplistic: the first GT allele is used.

**Comment by gungorbudak** [comment]
Thanks @pd3
