### ISSUE TITLE
position of variant in query read or alignment length

### ISSUE THREAD

**Issue by anwarMZ** [samtools/bcftools#930]
Hi,

I am trying samtools mpileup and bcftools to call variants on reads against an E.coli genome Assembly using BWA MEM.
But my main question is that i want to know the positions of a variant in the query reads that support the alternative allele or reference. I want to look from read's perspective that where does this variant happens. Can i do that using vcf file or any other alternative?

Thanks,
Zohaib

**Comment by pd3** [comment]
Each line in VCF corresponds to a genomic coordinate. In principle you could add an annotation which lists positions relative to all reads which cover that position, but it would be hugely impractical. I don't know what to advise other than writing a custom code.

For inspiration, there is the VDB annotation which uses this information to calculate if there is a bias in read placement. See the `calc_vdb` function https://github.com/samtools/bcftools/blob/develop/bam2bcf.c#L254-L335 for which the information is collected here https://github.com/samtools/bcftools/blob/develop/bam2bcf.c#L242.
