### ISSUE TITLE
bcftools merge issue

### ISSUE THREAD

**Issue by Celestic1** [samtools/bcftools#932]
I am trying to merge around 100 vcf.gz files that different samples into one. When I do the command `bcftools merge -Oz *.vcf.gz > merged.vcf.gz` I get the following error: 

`[E::hts_hopen] Failed to open file 4263772358_R02C01.vcf.gz`
`[E::hts_open_format] Failed to open file 4263772358_R02C01.vcf.gz`
`Failed to open 4263772358_R02C01.vcf.gz: Exec format error`

I bgzipped my file using `bgzip -c $i > $oname.vcf.gz` where $i is the input file and $oname is the input file name that I modified using regex. Any help would be much appreciated.

**Comment by Celestic1** [comment]
Also if I try to open individually using bcftools view, I get the following error: `Failed to open 4281452888_R02C02.vcf.gz: unknown file type`

**Comment by finswimmer** [comment]
Hello,

what's the output of: `zcat 4281452888_R02C02.vcf.gz | head`

fin swimmer

**Comment by Celestic1** [comment]
Hi finswimmer. I am at home and can't access my work computer. Will update tomorrow first thing in the morning.

**Comment by Celestic1** [comment]
@finswimmer the file is encoded in binary. Can't read it

**Comment by pd3** [comment]
Try `htsfile 4281452888_R02C02.vcf.gz`. Try also `zless 4281452888_R02C02.vcf.gz`. It can be something silly, like doubly-compressed file.

**Comment by Celestic1** [comment]
@pd3 I closed the ticket because I found a solution that you posted that worked. I used `bcftools views file.vcf -Oz -o file.vcf.gz` and then reindexed using bcftools index before merging.
