### ISSUE TITLE
23andme to vcf skipping all rows

### ISSUE THREAD

**Issue by sethadam30** [samtools/bcftools#933]
using --tsv2vcf all rows are skipped from my .tab 23andme file.
ref.fa = GRCh37.p13, indexed with samtools faidx

bcftools convert --tsv2vcf input.tab.gz -f ref.fa -s SampleName -Ob -o sample.bcf

Report=
Rows total:     554775
Rows skipped:   554775
Missing GTs:    0
Hom RR:     0
Het RA:     0
Hom AA:     0
Het AA:     0

**Comment by mp15** [comment]
Probably not a bug. Have a look at the header and 1st data line of your 23andme file. I suspect you'll find the chromosome names in one are chr prefixed and not chr prefixed in the other. (I also suspect you should double check the header to see whether 23andMe are using build 37 vs 38 in their more recent data downloads)

M

> On 14 Dec 2018, at 14:47, sethadam30 <notifications@github.com> wrote:
> 
> using --tsv2vcf all rows are skipped from my .tab 23andme file.
> ref.fa = GRCh37.p13, indexed with samtools faidx
> 
> bcftools convert --tsv2vcf input.tab.gz -f ref.fa -s SampleName -Ob -o sample.bcf
> 
> Report=
> Rows total: 554775
> Rows skipped: 554775
> Missing GTs: 0
> Hom RR: 0
> Het RA: 0
> Hom AA: 0
> Het AA: 0
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by pd3** [comment]
Also check if the input file looks like described here https://github.com/samtools/bcftools/issues/928

**Comment by sethadam30** [comment]
Both specifying the column orientation and making the CHROM identifiers the same b/t 23andme file and the ref.fa solved the issue

Make "chr" absent ref.fa
`cat GRCh37.p13.genome.fa | sed 's/>chr/>/g' > GRCh37.23andme.fa`

Specify column order for bcftools convert  
`bcftools convert -c ID,CHROM,POS,AA --tsv2vcf genome_p1.txt -f GRCh37.23andme.fa -s genomeP1 -Oz -o genomeP1.vcf.gz`

Make "chr" absent ref.fa

**Comment by sethadam30** [comment]
Me again...
When attempting to phase my data (23andme files converted to vcf) I realized that missing ALT alleles were presenting some issues.   When 23andme provides your "genotype" data, they do not provide the second allele tested for homozygotic SNPs. So, when converting to vcfs, homozygotes same as reference will be missing the ALT allele (the one not present in the sample).   Although not exactly the same as the test kit from 23andme, I'd like to replace "." in the ALT allele with the ALT allele(s) from a dbSNP reference .vcf file, since most all the variants have an rsID. Is there a bcftools way to do this, or should I just homebrew some scripts?  An example of the missing ALT allele is below.
```
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	genomeP1
1       1162435 rs3766186       C       A       .       .       .       GT      1/1     
1       1163804 rs7515488       C       T       .       .       .       GT      0/1     
1       1168115 rs142820961     C       .       .       .       .       GT      0/0

**Comment by pd3** [comment]
I think `bcftools annotate` might be able to add the ALT column by ID, if I recall correctly.

**Comment by sethadam30** [comment]
Right you are.. this seemed to do the trick, just takes a long time for a large target file.

`bcftools annotate -i 'ALT="."' -k --collapse all -a /dbSNP/All_20180423.vcf.gz -c ALT target.vcf.gz -Oz -o target.ALTfixed.vcf.gz`

-i ALT="." is to act only on the SNPs with missing ALT alleles in target vcf
-k is to keep the IDs that had ALT present
-a is the annotation reference, dbSNP vcf
-c ALT is the column to annotate
'--collapse all' to enable it to act on ALT alleles when "." does not match ALTs in annotation list (dbSNP)

**Comment by s-usr** [comment]
Hi... Can anybody share a link for the file 'GRCh37.23andme.fa'? Why is it designated as 'fasta'? Is it in a FASTA format? I thought this was a reference 4 column file just like the dna raw-data text file. Thanks.

**Comment by s-usr** [comment]
I opened an issue at https://github.com/samtools/bcftools/issues/1076.
