### ISSUE TITLE
mpileup fail to parse region 'chr2:0-0'

### ISSUE THREAD

**Issue by stekaz** [samtools/bcftools#935]
Using bcftools/1.9, we have been having an issue when trying to pileup the first position in a contig. This works as expected:

```
$ bcftools mpileup -f test.fa -r chr2:1 test.bam >/dev/null; echo $?
[mpileup] 1 samples in 1 input files
0
```

But strangely, this doesn't:

```
$ bcftools mpileup -f test.fa -r chr1:1,chr2:1 test.bam >/dev/null; echo $?
[mpileup] 1 samples in 1 input files
[E::mpileup] fail to parse region 'chr2:0-0'
1
```

It seems that if the first region (in the list of regions) begins at position 1, it is parsed correctly. But if there exists a region that begins at position 1 that isn't the first (in the list of regions), then an error is thrown. Have we found a bug?

**Comment by stekaz** [comment]
After a bit more digging, I wonder if the fix is to just `+1` to both the region start and end positions on this line:

https://github.com/samtools/bcftools/blob/master/mpileup.c#L626

i.e.:

```
ksprintf(&conf->buf,"%s:%u-%u",conf->reg_itr->seq,conf->reg_itr->beg+1,conf->reg_itr->end+1);
```

**Comment by stekaz** [comment]
After a bit more digging, I wonder if we just need to change this line:

https://github.com/samtools/bcftools/blob/master/mpileup.c#L626

to add 1 to the start and end:

```
ksprintf(&conf->buf,"%s:%u-%u",conf->reg_itr->seq,conf->reg_itr->beg+1,conf->reg_itr->end+1);
```

**Comment by pd3** [comment]
That's right, thanks very much for the bug report. This is fixed now.
