### ISSUE TITLE
encounter problems of vcf corruption 

### ISSUE THREAD

**Issue by zhouhufeng** [samtools/bcftools#937]
I am processing the GATK variant caller output, and found the following error when running bcftools view on it. 

[W::vcf_parse] Contig '' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::bcf_write] Broken VCF record, the number of columns at :1 does not match the number of samples (0 vs 2)

For this VCF file, I do have tabix indexed this file. 
And also open the vcf file but do not found there is any missing of the samples, all the sample GT columns are exist. don't know how to resolve this issue.

**Comment by finswimmer** [comment]
Hello @zhouhufeng ,

you should show us the complete header and the first few variants of your `vcf` file to help you better.

I guess at least one variant line starts with a tab or white-space character.

fin swimmer

**Comment by pd3** [comment]
Try `vcf-validator` from the vcftools package to see what is wrong with the VCF.
