### ISSUE TITLE
bcftools csq --ncsq 16 is too small to annotate

### ISSUE THREAD

**Issue by nextgenusfs** [samtools/bcftools#941]
I'm getting this warning while running `bcftools csq`:
```
Indexed 10362 transcripts, 29625 exons, 28516 CDSs, 9555 UTRs
Calling...
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 17-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 18-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 19-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 20-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 21-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 22-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 23-th csq
Warning: --ncsq 16 is too small to annotate X at chr4:4265442 with 24-th csq
```
This variant is a large deletion, around 50 kb. The other somewhat strange behavior (although it does make sense) is that for genes that are delete/missing it adds all of the available tags, for example:
```
BCSQ=splice_acceptor&3_prime_utr&coding_sequence|gene_006247|gene_006247-T1|protein_coding,3_prime_utr&coding_sequence|gene_006248|gene_006248-T1|protein_coding,5_prime_utr&3_prime_utr&coding_sequence|gene_006249|gene_006249-T1|protein_coding,splice_acceptor&3_prime_utr&coding_sequence|GENE1|gene_006250-T1|protein_coding,splice_donor&coding_sequence|gene_009987|gene_009987-T1|protein_coding,coding_sequence|gene_009988|gene_009988-T1|protein_coding     GT:DP:BCSQ      1:72:1365
```
The warning suggests there isn't any space left in that column or that it is limited to 16 consequences per line?  Would having a "consequence" flag as `deleted` save some space instead of listing all, i.e.:
```
#the current
splice_acceptor&3_prime_utr&coding_sequence|gene_006247|gene_006247-T1|protein_coding
#suggested simpler?
deleted|gene_006247|gene_006247-T1|protein_coding
```

**Comment by pd3** [comment]
The number of consequences in INFO/BCSQ is unlimited, but the FORMAT/BCSQ field is limited to 16 consequences to fit 2 haplotypes in a 32 bit integer. The number can be increased by setting `--ncsq` higher. 

The program reports consequences for all transcripts, so simplifying the consequence strings to `deleted` may not necessarily help.

**Comment by pd3** [comment]
Made the warnings more informative via 20d6cb84 and 7cc36652. Closing the issue now.
