### ISSUE TITLE
bcftools variant calling combined with nohup & not working

### ISSUE THREAD

**Issue by shannjiang** [samtools/bcftools#942]
Hi,

I am using bcftools to do variant calling by following the basic command (bcftools mpileup -f reference.fa alignments.bam | bcftools call -mv -Ob -o calls.bcf) in the website (https://samtools.github.io/bcftools/howtos/variant-calling.html).

Here is my command:
nohup /collab/sjiang4/soft/bcftools/bin/bcftools mpileup -f /collab/sjiang4/ucsc_ref/hg19.chr1.fasta /collab/sjiang4/dng_test/split/S13_02A_CHG000233_chr1.bam /collab/sjiang4/dng_test/split/S13_02A_CHG000234_chr1.bam /collab/sjiang4/dng_test/split/S13_02A_CHG000235_chr1.bam /collab/sjiang4/dng_test/split/S13_02B_CHG000236_chr1.bam /collab/sjiang4/dng_test/split/S89_01B_CHG000237_chr1.bam | /collab/sjiang4/soft/bcftools/bin/bcftools call -mv -Ov -o /collab/sjiang4/dng_test/split/s1347_chr1.vcf &

but it prompted me error info:
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Failed to open -: unknown file type

However, the command is working fine if not including nohup & command.
Is there anyone know how is it like this? Is there anyway I can submit my variant calling job onto server but not working in shell?

**Comment by pd3** [comment]
If you want to use `nohup` I think you might need to put your command inside a script and run as `nohup script.sh &`.

**Comment by shannjiang** [comment]
Thanks Petr. Yes, finally I figured it out I can nohup my job by putting it inside a .sh file.


Shan


________________________________
