### ISSUE TITLE
bcftools annotate does not support renaming of ID to INFO/TAG

### ISSUE THREAD

**Issue by marcora** [samtools/bcftools#947]
As an example, `bcftools annotate -c INFO/DB_ID:=ID -a <dbsnp.vcf>` should work but it doesn't!

**Comment by pd3** [comment]
Currently this works only for new annotations transferred from one file into another, but not within the same file. I'll mark this as a feature request.

**Comment by marcora** [comment]
Last time I tried, it did not work even when using an annotation file to annotate another.

**Comment by freeseek** [comment]
I actually have the same exact issue. I was trying:
```
bcftools annotate -a clinvar_20190731.vcf.gz -c VARIATIONID:=ID,ALLELEID input.vcf.gz
```
And I get the error:
```
[ID] 0
The tag "ID" is not defined in clinvar_20190731.GRCh38.vcf.gz
```
It seems like there is not way to currently do this with `bcftools`

**Comment by pd3** [comment]
An easy way to work around this is to create an annotation file first, for example using `bcftools query`, then annotate back.

**Comment by pd3** [comment]
This took longer but is now supported. Please let me know in case of problems.

**Comment by marcora** [comment]
thnx!

**Comment by shafiqnoa** [comment]
Hi, 
I just need to rename one of the tags in the INFO column but the following command is not working: 
bcftools annotate -c INFO/INFO:=INFO/RD2 -a 22.vcf.gz  -Oz -o 22_anno.vcf.gz 

Is there a way to rename tag/s?
