### ISSUE TITLE
Documentation of parallel variant calling

### ISSUE THREAD

**Issue by nikostr** [samtools/bcftools#949]
The [bcftools variant calling documentation](http://samtools.github.io/bcftools/howtos/variant-calling.html) explicitly mentions parallelization as one way of fine tuning the variant calling. What is the recommended way of doing this? Is it sufficient to specify number of threads for both `mpileup` and `call`, or is there some other recommended way of doing this?

**Comment by finswimmer** [comment]
AFAIK the number of threads you can specify for `mpileup` and `call` are just for the compression steps.

What is meant by "run in parallel" is, to run the variant calling for different regions in parallel e.g. for each chromosome. A tool that can be used for it is [gnu parallel](https://www.gnu.org/software/parallel/). 

A pipepline t o run the variant calling in parallel for each chromosome could look like this:

`$ parallel 'bcftools mpileup -Ou -f ref.fa -r {} in.bam | bcftools call -m -v -Oz -o {}.vcf.gz' ::: {1..22} X Y`

**Comment by rikrdo89** [comment]
Do you know this pipeline would adjust the memory and CPU needs of bcftools? I want to run this in my laptop but I am not sure if this code will work. When I call SNPs using RNAseq data, bcftools takes hours to complete so any multi-threading or parallelization function is very much appreciated.,

**Comment by pd3** [comment]
The memory requirements of bcftools are low, but the CPU depends on how many cores you have available. For example, if you have 4 cores, you will not gain anything by running more than 4 jobs in parallel.

**Comment by rikrdo89** [comment]
is it possible then to set the thread count when running a line of bcftools command.? I am looking for a way to speed up my analysis of calling SNPs in one chromosome across ~20 samples.

**Comment by pd3** [comment]
No, sorry. The parallelization as it currently stands is only for the compression/decompression. We parallelize the calling by chunking the genome into smaller regions instead.
