### ISSUE TITLE
fail to generate consensus sequence from multi-sample VCF file

### ISSUE THREAD

**Issue by computingmachine** [samtools/bcftools#950]
Hi,
I was trying to create consensus sequence from a vcf file which includes 10 samples. However, when I use the -s option, and the SRR6432717.sort.chrM.bam is one of the sample name

**bcftools consensus -i -s SRR6432717.sort.chrM.bam -f ../chrM.fa P1.var.raw.chrM.vcf.gz > out.fa

[E::hts_open_format] Failed to open file SRR6432717.sort.chrM.bam

Failed to open SRR6432717.sort.chrM.bam: No such file or directory**

It returns us that no such file or directory. Could you please tell me how to fix that?

**Comment by computingmachine** [comment]
Here is the VCF file
[P1.var.raw.chrM.zip](https://github.com/samtools/bcftools/files/2824994/P1.var.raw.chrM.zip)

**Comment by finswimmer** [comment]
You are using the `-i` parameter but haven't define any expression for sites that should be included. Just remove this parameter or define a valid expression.

fin swimmer
