### ISSUE TITLE
bcf_sr_add_reader() provides cryptic error message when handling streams

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#951]
If you try to extract a region on a stream:
```
bcftools view -Oz input.vcf | bcftools view -r chr19:44908684-44908684
```
You get a cryptic error message:
```
Failed to open -: not compressed with bgzip
```
Despite the stream being compressed with bgzip.

Notice that the following:
```
bcftools view -r chr19:44908684-44908684 <(bcftools view -Oz input.vcf)
```
Produces a more comprehensible error message:
```
Failed to open /dev/fd/63: could not load index
```

The function bcf_sr_add_reader() from htslib/synced_bcf_reader.c could easily check, when an index is required, whether the file is a stream with code like this:
```
if ( fname == "-" )
{
    files->errnum = idx_load_failed;
    return 0;
}
```

**Comment by pd3** [comment]
More recent bcftools/htslib checkouts from github give a more comprehensible error message. Now did the same for other commands as well via be4494b. Thank you for the bug report.
