### ISSUE TITLE
Error with bcftools view

### ISSUE THREAD

**Issue by stephaniemyan** [samtools/bcftools#952]
Hi,

I'm trying to run bcftools view to obtain a subset of samples from a larger VCF file. However, when I run the program, I get the following error:

`[E::bcf_calc_ac] Unexpected type 7 at chr1:16280`

chr1 16280 is the location of the first SNV in my VCF file.

This is my command:

`bcftools view -a -Oz -o sgdp_snvs.vcf.gz -s S_Eskimo_Naukan-2,S_Mixtec-1,S_Gambian-2,S_Mbuti-3,S_Ju_hoan_North-2,S_Yoruba-1,S_Karitiana-1,S_Han-2,S_Lahu-2,S_Papuan-13,S_Bengali-2,S_Punjabi-3,S_Yakut-1,S_English-2,S_Palestinian-3 ~/work/resources/sgdp-263-hs38DH/263.all.vcf.gz`

Here are the first 5000 lines of my VCF file:
[263.all.5000.vcf.zip](https://github.com/samtools/bcftools/files/2843372/263.all.5000.vcf.zip)

I've tried running other bcftools commands (`bcftools view -r`, etc.) and they seem to work okay, so I feel like it might be an issue with the `-s` command.

Could you tell me why I'm getting this error?

**Comment by finswimmer** [comment]
Hello @stephaniemyan ,

I cannot say whether this is a bug or something is wrong with your `vcf` file. As the error suggested there is a problem during calculation of the new AC value.

What works as a work around for me, is to first remove any information from the INFO column and build the subset afterwards.

`$ bcftools annotate -x INFO 263.all.5000.vcf|bcftools view -a -s S_Eskimo_Naukan-2,S_Mixtec-1,S_Gambian-2,S_Mbuti-3,S_Ju_hoan_North-2,S_Yoruba-1,S_Karitiana-1,S_Han-2,S_Lahu-2,S_Papuan-13,S_Bengali-2,S_Punjabi-3,S_Yakut-1,S_English-2,S_Palestinian-3`

I think @pd3 should have a look at this.

fin swimmer

**Comment by stephaniemyan** [comment]
That workaround worked for me too, thank you for your help!

**Comment by pd3** [comment]
A gentler workaround is to run `bcftools view --no-update` which prevents the program from updating the AC field.

The problem with your VCF is that the AN and AC are defined as `Type=String` in the header, they must be declared as `Type=Integer`. Check the VCF specification for details http://samtools.github.io/hts-specs/VCFv4.3.pdf
