### ISSUE TITLE
Yes, just include the missing tags in the header, for example like this:

### ISSUE THREAD

**Issue by beginner984** [samtools/bcftools#955]
Yes, just include the missing tags in the header, for example like this:

```
  bcftools view -h file.vcf > hdr.txt
  <edit hdr.txt>
  bcftools reheader -h hdr.txt -h file.vcf > new.vcf
```

In this case the program could be less strict.

_Originally posted by @pd3 in https://github.com/samtools/bcftools/issues/470#issuecomment-240693485_

**Comment by pd3** [comment]
This issue seems to be opened by mistake. Please correct me if I am wrong.

**Comment by beginner984** [comment]
This problem has been solved already
