### ISSUE TITLE
bcftoold does not recognize none of my vcf files

### ISSUE THREAD

**Issue by beginner984** [samtools/bcftools#956]
Sorry, 

I am trying bcftools on both of my indel and snp vcf files to query function but always give error

[fi1d18@cyan01 ~]$ bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' c.vcf
Error: no such tag defined in the VCF header: FORMAT/GT

I tried to look at header but I don't know where I should add missed tag

[fi1d18@cyan01 ~]$ bcftools view -h c.vcf > hdr.txt

[fi1d18@cyan01 ~]$ cat hdr.txt
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=BCNoise,Description="Fraction of basecalls filtered at this site in either sample is at or above 0.4">
##FILTER=<ID=DP,Description="Greater than 3.0x chromosomal mean depth in Normal sample">
##FILTER=<ID=DistanceToAlignmentEndMAD,Description="DistanceToAlignmentEndMAD < 3.0">
##FILTER=<ID=DistanceToAlignmentEndMedian,Description="DistanceToAlignmentEndMedian < 10.0">
##FILTER=<ID=LowMapQual,Description="LowMapQual > 0.1">
##FILTER=<ID=MapQualDiffMedian,Description="MapQualDiffMedian < -5.0 || MapQualDiffMedian > 5.0">
##FILTER=<ID=QSS_ref,Description="Normal sample is not homozygous ref or ssnv Q-score < 15, ie calls with NT!=ref or QSS_NT < 15">
##FILTER=<ID=Repeat,Description="Repeat >= 12">
##FILTER=<ID=SNVCluster100,Description="SNVCluster100 > 4">
##FILTER=<ID=SNVCluster50,Description="SNVCluster50 > 2">
##FILTER=<ID=SpanDel,Description="Fraction of reads crossing site with spanning deletions in either sample exceeeds 0.75">
##FILTER=<ID=StrandBias,Description="VariantStrandBias < 0.02 && StrandBias > 0.02">

Please help me to find what is going wrong with these files

Thank you

**Comment by pd3** [comment]
You are asking the program to output the `GT` field, but it is not present in the header, therefore it cannot output it. If you'd like the program to proceed anyway, add the `--allow-undef-tags` option to the command.

Check also the VCF specification to get familiar with the structure of a VCF file http://samtools.github.io/hts-specs/VCFv4.3.pdf

**Comment by beginner984** [comment]
Thank you 
error gone by changing 

bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' c.vcf

to 

bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%ID]\n' c.vcf

However when I am trying the same command on a multi samples .vcf file says that

Unknown file type

Is there anyway to run this command on a multi samples vcf file please?

Thanks for helping us

**Comment by pd3** [comment]
The command operates on a single file. You can either run it separately for all files or merge the files first using `bcftools merge` and then run `bcftools query`.
