### ISSUE TITLE
bcftools csq long localized predictions for frameshift variants

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#957]
I really like bcftools csq. I was wondering whether it would be possible to have an option for shorter protein prediction change, at least when the --local-csq option is active.

For example, for GRCh37 variant `20 31022441 A AG` you obtain the following prediction:
```
frameshift|ASXL1|ENST00000375687|protein_coding|+|642GGGGGPGGGGGGATDEGGGRGSSSGDGGEACGHPEPRGGPSTPGKCTSDLQRTQLLPPYPLNGEHTQAGTAMSRARREDLPSLRKEESCLLQRATVGLTDGLGDASQLPVAPTGDQPCQALPLLSSQTSVAERLVEQPQLHPDVRTECESGTTSWESDDEEQGPTVPADNGPILSLVGDDTLEKGTGQALDSHPTMKDPVNVTPSSTPESSPTDCLQNRAFDDELGLGGSCPPMRESDTRQENLKTKALVSNSSLHWIPIPSNDEVVKQPKPESREHIPSVEPQVGEEWEKAAPTPPALPGDLTAEEGLDPLDSLTSLWTVPSRGGSDSNGSYCQQVDIEKLKINGDSEALSPHGESTDTASDFEGHLTEDSSEADTREAAVTKGSSVDKDEKPNWNQSAPLSKVNGDMRLVTRTDGMVAPQSWVSRVCAVRQKIPDSLLLASTEYQPRAVCLSMPGSSVEATNPLVMQLLQGSLPLEKVLPPAHDDSMSESPQVPLTKDQSHGSLRMGSLHGLGKNSGMVDGSSPSSLRALKEPLLPDSCETGTGLARIEATQAPGAPQKNCKAVPSFDSLHPVTNPITSSRKLEEMDSKEQFSSFSCEDQKEVRAMSQDSNSNAAPGKSPGDLTTSRTPRFSSPNVISFGPEQTGRALGDQSNVTGQGKKLFGSGNVAATLQRPRPADPMPLPAEIPPVFPSGKLGPSTNSMSGGVQTPREDWAPKPHAFVGSVKNEKTFVGGPLKANAENRKATGHSPLELVGHLEGMPFVMDLPFWKLPREPGKGLSEPLEPSSLPSQLSIKQAFYGKLSKLQLSSTSFNYSSSSPTFPKGLAGSVVQLSHKANFGASHSASLSLQMFTDSSTVESISLQCACSLKAMIMCQGCGAFCHDDCIGPSKLCVLCLVVR*>642GGGGWPGWRWRRGHR*|31022441A>AG
```

While a more handy version like this (see <a href="https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=34210">here</a>):
```
frameshift|ASXL1|ENST00000375687|protein_coding|+|???>p.G646fs*12|31022441A>AG
```
which only tells you after how many aminoacids the stop codon will arise as a result of the frameshift. I have not looked much into it, but I guess it would be an easy option to add.

**Comment by pd3** [comment]
This is now added as a new `-b, --brief-predictions` option. The output format looks different though, as it can be generated by other variant types: `25E..329>25G..94`. I hope that's OK
