### ISSUE TITLE
Extracting start and end of variants

### ISSUE THREAD

**Issue by beginner984** [samtools/bcftools#959]
Hi,

With your kindly help I could extract some columns from vcf but I need to extract start and end not position itself

this gives position

bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%ID]\n' file.vcf

##bcftools_viewCommand=view -h c.vcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL  TUMOR

Could you please help me in getting start, end and strand from my vcf files?

Thanks a lot for any help

**Comment by pd3** [comment]
The expression is `%END`. This is documented in the manual http://samtools.github.io/bcftools/bcftools.html#query

**Comment by beginner984** [comment]
Thanks a lot, very helpful

Sorry for including a column corresponding to strand what I should add to my command?

Thank you so much

**Comment by beginner984** [comment]
Thanks a lot but returns error

[fi1d18@cyan01 ~]$ bcftools query -f '%CHROM\t%POS\t%END\t%REF\t%ALT[\t%ID]\n' c.vcf > rr.txt
Error: no such tag defined in the VCF header: INFO/END
[fi1d18@cyan01 ~]$ bcftools query -f '%CHROM\t%END\t%REF\t%ALT[\t%ID]\n' c.vcf > rr.txt
Error: no such tag defined in the VCF header: INFO/END
[fi1d18@cyan01 ~]$

**Comment by pd3** [comment]
Probably an old version of bcftools? Please see http://samtools.github.io/bcftools/ or http://samtools.github.io/bcftools/howtos/install.html for details how to get the most up to date version.

**Comment by beginner984** [comment]
Thanks a lot

How could I extract the strand please?
--------------------------------------------
On Thu, 2/14/19, Petr Danecek <notifications@github.com> wrote:

 Subject: Re: [samtools/bcftools] Extracting start and end of variants (#959)
 To: "samtools/bcftools" <bcftools@noreply.github.com>
 Cc: "beginner984" <izadi1991@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, February 14, 2019, 1:55 PM
 
 Probably an old version of
 bcftools? Please see http://samtools.github.io/bcftools/
 or http://samtools.github.io/bcftools/howtos/install.html
 for details how to get the most up to date version.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by garrettjstevens** [comment]
Just a fellow user here, but I don't think strand information is present in the VCF. By common convention, though, it seems most tools report variants on the forward strand.

See:
https://www.biostars.org/p/47711/
http://www.internationalgenome.org/faq/what-strand-are-variants-your-vcf-file/
http://seqanswers.com/forums/showthread.php?t=40479

**Comment by pd3** [comment]
It is not clear what do you mean by strand information. Phase? Something else? In any case, the program can only extract the information present in the VCF. As the original question has been resolved, I am closing the issue now.

**Comment by beginner984** [comment]
Thank you
I meant the strand column 

--------------------------------------------
On Fri, 2/22/19, Petr Danecek <notifications@github.com> wrote:

 Subject: Re: [samtools/bcftools] Extracting start and end of variants (#959)
 To: "samtools/bcftools" <bcftools@noreply.github.com>
 Cc: "beginner984" <izadi1991@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 22, 2019, 4:51 PM
 
 It is not clear what do you mean
 by strand information. Phase? Something else? In any case,
 the program can only extract the information present in the
 VCF. As the original question has been resolved, I am
 closing the issue now.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by pd3** [comment]
There is no strand column in the VCF. Please check the specification and see if you can rephrase your question http://samtools.github.io/hts-specs/VCFv4.3.pdf
