### ISSUE TITLE
bcftools +split bugs

### ISSUE THREAD

**Issue by freeseek** [samtools/bcftools#960]
The following command:
```
bcftools +split.so input.bcf -o dir -k INFO
```
will end up in segfault, as the array `args->fmt_tags` gets never initialized and in file `split.c` at line 310:
```
if ( !args->keep_fmt && !args->fmt_tags[id] ) continue;
```
it will try to access memory that has never been initialized.

On top of this, while `bcftools annotate -x` will remove from the header the tags that are requested to be removed, `bcftools +split -k` leaves the header the same as the one in the original file. This seems counter-intuitive. Maybe the `-k` option should be removed and the user should be advised to pipe the output of `bcftools annotate -x` into `bcftools +split` instead.

**Comment by pd3** [comment]
This is now fixed.
