### ISSUE TITLE
fill-tags when AN is zero

### ISSUE THREAD

**Issue by dmckean** [samtools/bcftools#963]
I'm using fill-tags to update a VCF that had some samples dropped and genotypes censored. It appears AF and MAF are not updated if the fill-tags plugin determines that `AN == 0` ([fill-tags.c:512](https://github.com/samtools/bcftools/blob/develop/plugins/fill-tags.c#L512)).

Test input (where SAMP_D was previously removed, SAMP_A at chr1:10152 was set as missing)
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=chr1,length=249250621,assembly=hg19>
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMP_A	SAMP_B	SAMP_C	SAMP_E
chr1	10146	.	AC	A	.	PASS	NS=3;AN=6;AF=0.5;AC=3	GT	./.	0/1	./.	0/1
chr1	10153	.	A	C	.	PASS	NS=1;AN=2;AF=0.5;AC=2	GT	./.	./.	./.	./.
chr1	10154	.	C	G	.	PASS	NS=2;AN=4;AF=0.25;AC=1	GT	./.	./.	./.	./.
chr1	10172	.	C	A	.	PASS	NS=3;AN=6;AF=0;AC=0	GT	0/0	0/0	0/0	./.
```
fill-tags output

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMP_A	SAMP_B	SAMP_C	SAMP_E
chr1	10146	.	AC	A	.	PASS	NS=2;AN=4;AF=0.5;AC=2;MAF=0.5;AC_Het=2;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=0.666667	GT	./.	0/1	./.	0/1
chr1	10153	.	A	C	.	PASS	NS=0;AN=0;AF=0.5;AC=0;AC_Het=0;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=1	GT	./.	./.	./.	./.
chr1	10154	.	C	G	.	PASS	NS=0;AN=0;AF=0.25;AC=0;AC_Het=0;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=1	GT	./.	./.	./.	./.
chr1	10172	.	C	A	.	PASS	NS=3;AN=6;AF=0;AC=0;MAF=0;AC_Het=0;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=1	GT	0/0	0/0	0/0	./.
```

fill-tags does not add or update MAF and AF when AN == 0. This behavior makes sense when the AF tag was not already present. Should fill-tags handle this case? Right now, I'm selectively dropping AF and MAF from those sites with `bcftools annotate -x 'INFO/AF,INFO/MAF' -i 'AN == 0' -k` before running fill-tags.

**Comment by pd3** [comment]
Yeah, I am not sure what is the right behavior here. If no allele is present, `AF=AC/AN=0/0=nan`. I am open to suggestions.

**Comment by dmckean** [comment]
I don't think leaving incorrect AF and MAF tags is best, but to you point, neither is setting either tag to 0. Rather than removing the tag from the record entirely, it could be set as missing. That seems closer to encoding `nan`. 

Something like:
```
if ( an ) {
  for (j=1; j<rec->n_allele; j++) args->farr[j-1] /= an;
} else {
  for (j=1; j<rec->n_allele; j++) bcf_flt_set_missing(args->farr[j-1]);
}
```

Needed around L512 for AF and L524 for MAF.
