### ISSUE TITLE
bcftools annotate -x INFO/RSPOS 

### ISSUE THREAD

**Issue by MartaRus** [samtools/bcftools#965]
Hi
I'm using the "annotate -x" option in order to remove some INFO fields from my vcf files. It works with all the INFO tags except the RSPOS filed! It is removed from the header but not from all the variants in the vcf files. And, where the RSPOS is not removed, appears "true" in the REF field (see attached file) 
[RSPOS.xlsx](https://github.com/samtools/bcftools/files/2888812/RSPOS.xlsx). Please, note that the RSPOS is removed for many variants but not all.
I'm using the 1.9 version of bcftools

Any idea?

thank you

**Comment by pd3** [comment]
This sounds odd. Any chance you could share a small test case to reproduce and debug the problem?

**Comment by MartaRus** [comment]
Yes. Here a part of my vcf. There are two positions with RSPOS in the INFO field. When I run the script to convert in tabular, it becomes as I shown you before.
[myvcf.xlsx](https://github.com/samtools/bcftools/files/2899607/myvcf.xlsx)

**Comment by pd3** [comment]
In order to reproduce the problem, the exact same input you feed to bcftools is needed. Can you attach the VCF instead of a XLS?

**Comment by MartaRus** [comment]
Here the file!
[FP1904-dbNSFP3.5_MsigDB.zip](https://github.com/samtools/bcftools/files/2925722/FP1904-dbNSFP3.5_MsigDB.zip)
Thanks!

**Comment by MartaRus** [comment]
I saw that the problem regards the variants (I don't know why and how) because, for some of those, the INFO fields eliminated with "bcftools annotate -x", are still present...any idea?

**Comment by pd3** [comment]
Some of the positions in your file have multiple INFO/RSPOS fields. The VCF specification does not allow multiple occurrences of the same tag, so it is probably not worth making bcftools aware of cases like this (the fix would have to be in htslib anyway). Instead I suggest this workaround:
````
# save the header
bcftools view -h FP1904-dbNSFP3.5_MsigDB.vcf > rmme.hdr

# remove the first occurrence of INFO/RSPOS
bcftools annotate -x INFO/RSPOS FP1904-dbNSFP3.5_MsigDB.vcf > rmme.vcf

# add the header line back and remove again
bcftools reheader -h rmme.hdr rmme.vcf | bcftools annotate -x INFO/RSPOS
````

The program that adds the RSPOS tag should be fixed.

**Comment by MartaRus** [comment]
thank you!
