### ISSUE TITLE
enh: bcftools csq API

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#968]
it seems only `init_data`, `process`, and `destroy_data` and the args_t struct are needed for using the csq functionality. 
would it be possible to make these and possibly an opaque or minimal args_t struct available in a separate header?

**Comment by pd3** [comment]
It is possible in principle but far from the objectives and priorities of the project. Still, if the motivation for creating an API is well reasoned and a good pull request is provided, I am not opposed to the idea. However, note that there are more dependencies (see the header files included in csq.c) and quite a few command line options that you'd have to be included in the API as well.

**Comment by brentp** [comment]
ok. thanks for the response and the software.
