### ISSUE TITLE
bcftools query returns 0 for very small floats in INFO field

### ISSUE THREAD

**Issue by letaylor** [samtools/bcftools#970]
Thanks for developing and maintaining such a great tool. 

Using bcftools 1.9, I encountered an unexpected issue when querying VCFs that had very small floats stored in them. If the float is small enough, “bcftools query” will return 0. Currently an easy work around is to store the float as a string. Below is an example VCF file that shows this behavior. 

```
##fileformat=VCFv4.2
##reference=GRCh37.p13
##contig=<ID=12,length=133851895>
##INFO=<ID=EFFECT_ALLELE,Number=1,Type=String,Description="">
##INFO=<ID=OTHER_ALLELE,Number=1,Type=String,Description="">
##INFO=<ID=EFFECT_ALLELE_FREQ,Number=1,Type=Float,Description="">
##INFO=<ID=BETA,Number=1,Type=Float,Description="">
##INFO=<ID=STE,Number=1,Type=Float,Description="">
##INFO=<ID=PV1,Number=1,Type=Float,Description="">
##INFO=<ID=PV2,Number=1,Type=String,Description="">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
12	49390677	ok_pv1	T	C	.	.	EFFECT_ALLELE=C;OTHER_ALLELE=T;BETA=-1.05017;STE=0.0716477;PV1=1.20781e-38;PV2=1.20781e-48
12	49390677	bad_pv1	T	C	.	.	EFFECT_ALLELE=C;OTHER_ALLELE=T;BETA=-1.05017;STE=0.0716477;PV1=1.20781e-48;PV2=1.20781e-48
```

If we query this file using the below command, for variant “bad_pv1”, we get PV1=0 and PV2=1.20781e-48. The only difference is the header line where PV1=Float and PV2=String. In contrast, for variant “ok_pv1”, PV1 is fine as the value is not as small. 

```bash
bcftools query -f "%CHROM,%POS,%ID,%INFO/EFFECT_ALLELE,%INFO/OTHER_ALLELE,%INFO/EFFECT_ALLELE_FREQ,%INFO/BETA,%INFO/STE,%INFO/PV1,%PV2\n" example.vcf
```
> 12,49390677,ok_pv1,C,T,.,-1.05017,0.0716477,1.20781e-38,1.20781e-48
> 12,49390677,bad_pv1,C,T,.,-1.05017,0.0716477,0,1.20781e-48

The string solution works fine for me, but I want others to be aware of this issue.

**Comment by jmarshall** [comment]
Floats are stored in BCF as single precision binary32 floating point numbers, which can represent down to about 1E-45 before underflowing to 0.

See also samtools/hts-specs#378 and in particular the mailing list thread linked there.

**Comment by pd3** [comment]
The common practice is to encode fields with extreme range in log space.

**Comment by letaylor** [comment]
@pd3 great idea. Thank you both.
