### ISSUE TITLE
feature request: remove *all* duplicates with bcftools norm --rm-dup

### ISSUE THREAD

**Issue by tommycarstensen** [samtools/bcftools#974]
Would it be possible to add a feature that allows *all* duplicate records to be removed? Right now this command removes duplicate records except for one unique record:

    bcftools norm --rm-dup

Thanks!

P.S. Otherwise I guess in my specific case I could merge the records and remove anything not biallelic. But it's a fudge solution. Thanks guys/Petr.

**Comment by pd3** [comment]
I have an old unreleased plugin which does, sort of, what you need: removes sites with overlapping variants. I added it to the repository now and added a new `-d, --rmdup` option; in this mode it will remove all duplicate positions.
