### ISSUE TITLE
reheader.c:494:21: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by bw2** [samtools/bcftools#975]
I'm building bcftools inside a [Debian docker image](https://github.com/bw2/str-callers/blob/master/docker/base-image-for-str-tools/Dockerfile#L65-L76) (the base image is `bitnami/minideb:stretch`)

I'm finding that the build stopped working after this commit:
https://github.com/samtools/bcftools/commit/092b0379a9aa32dfa527a3a4251787cf9a2aeb08

When I run make, I get this error:
```
...
vcfannotate.c:810:81: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o vcfroh.o vcfroh.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o vcfconcat.o vcfconcat.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o vcfcall.o vcfcall.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o mcall.o mcall.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o vcmp.o vcmp.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o gvcf.o gvcf.c
gcc -Wall -g -O2 -I. -I../htslib-1.9   -c -o reheader.o reheader.c
reheader.c: In function 'strip_header':
reheader.c:494:21: error: void value not ignored as it ought to be
                 if (hrec_add_idx(tmp, j) < 0)
                     ^~~~~~~~~~~~~~~~~~~~
Makefile:126: recipe for target 'reheader.o' failed
make: *** [reheader.o] Error 1
```

**Comment by pd3** [comment]
You probably need to update htslib?

**Comment by jkbonfield** [comment]
I assume this is the develop branch of bcftools?  If so it will need at least a similar aged develop branch of htslib.

https://github.com/samtools/htslib/commit/fe9c2f8f added a return value to hrec_add_idx so it could report errors back.  Bcftools was updated to honour these return values, but if you compile against released versions of htslib the compiler complains about the old void return.

**Comment by pd3** [comment]
I'll assume this is resolved. Please comment if not.
