### ISSUE TITLE
Splitting vcf file to underlying samples

### ISSUE THREAD

**Issue by beginner984** [samtools/bcftools#976]
Sorry this is not your issue but my problem

By strelka I have called SNV on my samples
`./configureStrelkaSomaticWorkflow.py --normalBam /1.bam --tumorBam /2.bam --referenceFasta /hs37d5.fa --runDir demo`

Now I a .vcf file in results

I tried 

```
[fi1d18@cyan02 fi1d18]$ bcftools query -l /somatic.snvs.vcf
NORMAL
TUMOR

```
I want two .vcf files for my samples because I need to check the consistency of mutations in two paired samples 

I tried 

I thought about splitting the resulted .vcf
```
`
[fi1d18@cyan02 fi1d18]$ vcf-subset -c NORMAL /somatic.snvs.vcf > NORMAL.vcf`

```
But nothing happens, 

Then I used `vcfkeepsamples/vcfremovesamples utilities from VCFlib toolkit` to select my samples one by one although I am not sure at all if I am correct

am I doing wrong that I think for checking the consistency of mutations in two paired samples I should split my resulted .vcf file? How I could split this .vcf to samples please?

**Comment by pd3** [comment]
For splitting the VCF by samples, check the `-s` option of the `bcftools view` command https://samtools.github.io/bcftools/bcftools.html#view or the `bcftools +split` plugin https://samtools.github.io/bcftools/bcftools.html#plugin.

There are also tools for trio analyses, such as the `bcftools +contrast` or `bcftools +mendelian`.

**Comment by pd3** [comment]
I'll assume this is resolved now.
