### ISSUE TITLE
request: bcftools annotate should not fail if missing tags in the header

### ISSUE THREAD

**Issue by nh13** [samtools/bcftools#979]
I'd like to run this command on all VCFs: 
```
bcftools annotate --remove FORMAT/F1R2,FORMAT/F2R1 
```
I would like `bcftools` **_not_** to fail if those tags are not present in the VCF.  Instead I get a exit code of 255:

```
Warning: The tag "F1R2" not defined in the header
Warning: The tag "F2R1" not defined in the header
No matching tag in -x FORMAT/F1R2,FORMAT/F2R1
```

Basically, remove them if present, if not, that's fine too.  The offending line I think is:

https://github.com/samtools/bcftools/blob/4782f894fc2fe77d547f82f432e40c6072675347/vcfannotate.c#L399

Related to: https://github.com/broadinstitute/gatk/issues/5704

**Comment by pd3** [comment]
This is now possible with the bew `--force` option.
