### ISSUE TITLE
bcftools consensus bug

### ISSUE THREAD

**Issue by ALFLAG** [samtools/bcftools#981]
Hello everyone!

I would like to known why bcftools consensus do not generate a correct consensus sequence.
Explanation: let's have a position in the reference sequence with a T nucleotide. On this position are aligned 29 reads, not enormous I agree but sufficient. All nucleotides in the reads for this position are a C. Why the program do not write C but instead write a T for this position.

ussually I used to pass this roblem, but this time I met this poblem more than 20 time for a single genome. Unfortunatly, I can not share these data with you.

Does Anyone have A) an explanation, and B) a solution ?

Thanks!

Alexandre

**Comment by ALFLAG** [comment]
Actually I was wrong, I can provide the vcf file I'm using.
You will find attach two file, the vcf file and the second file ("position.txt") is the list of genomic position where the reference nucleotide is written instead of the alternative nucleotide.

[position.txt](https://github.com/samtools/bcftools/files/2967720/position.txt)
[copy_variant_calling.vcf.txt](https://github.com/samtools/bcftools/files/2967726/copy_variant_calling.vcf.txt)
 Maybe there's a problem when bcftools is parsing these lines, I don' know.

Thank You.

Alexandre

**Comment by pd3** [comment]
Hi, as the question stands it is impossible to answer. I am assuming you checked the documentation http://samtools.github.io/bcftools/howtos/consensus-sequence.html. If you think it's a problem with bcftools, you'll need to provide a small test case to reproduce the problem.
