### ISSUE TITLE
Replace FORMAT expression function AVG with MEDIAN, MEAN, and MODE

### ISSUE THREAD

**Issue by dancooke** [samtools/bcftools#983]
From the [expressions documentation](
https://samtools.github.io/bcftools/bcftools.html#expressions):

    function on FORMAT tags (over samples) and INFO tags (over vector fields)

    MAX, MIN, AVG, SUM, STRLEN, ABS, COUNT

It's not clear if `AVG` is the mean, median, or mode. I think replacing `AVG` with `MEAN`, `MEDIAN`, and `MODE` would make this clearer and more useful.

**Comment by pd3** [comment]
The function `AVG` is the arithmetic mean, this should be updated in the man page. 

Thank you for the pull request. Can you make the failing travis errors go away and add documentation to doc/bcftools.txt?

**Comment by dancooke** [comment]
@pd3 Done.

**Comment by pd3** [comment]
Thanks! We will need to add tests for this new functionality, are you happy to include them in the pull request as well?

Also please don't remove AVG completely from the documentation, as for most people "average" is synonymous with arithmetic mean. (I guess you are coming from a different background, so our opinions may differ on this.)
