### ISSUE TITLE
Argument for index file

### ISSUE THREAD

**Issue by tomazberisa** [samtools/bcftools#984]
Bcftools does not currently allow explicitly specifying a path (or URL) to the index file for a vcf/bcf file.

This would be quite useful in situations where the index file does not conform to the standard naming scheme, e.g., presigned URLs on AWS S3.

The equivalent samtools solution is a great resolution to this same issue for bam format. See issue and pull request resolving it here:
https://github.com/samtools/samtools/issues/485
https://github.com/samtools/samtools/pull/978

**Comment by pd3** [comment]
With the htslib pull request https://github.com/samtools/htslib/pull/861 merged, it is now possible to access files with non-standard index names as e.g.
````
bcftools view -r X:2928329 file.bcf##idx##non-standard-index-name
````

**Comment by tomazberisa** [comment]
Can confirm this works with presigned URLs on AWS S3 as well.
Awesome, thank you!
