### ISSUE TITLE
Extract INFO/INFO Should be Documented and Broken Link

### ISSUE THREAD

**Issue by ttbek** [samtools/bcftools#986]
I was trying to extract a field called INFO from the INFO tag, as Sanger outputs with such naming from their imputation server.  

Something like: 
`bcftools query -f '%CHROM %POS %ID %REF %ALT %QUAL %FILTER %INFO[\t%DS]\n' chr22.dose.vcf.gz > chr22.dosage`
Well, this wasn't working.  The information here: https://github.com/samtools/bcftools/issues/765 was useful, so I needed: 
`bcftools query -f '%CHROM %POS %ID %REF %ALT %QUAL %FILTER %INFO/INFO[\t%DS]\n' chr22.dose.vcf.gz > chr22.dosage`

It would be good to provide a similar example here: https://samtools.github.io/bcftools/howtos/query.html  Not necessarily even an example, what pd3 wrote in the other issue would be sufficient.  

Also, there is a broken link to the manual page on that page that needs fixing, it currently points to https://samtools.github.io/bcftools/howtos/bcftools.html#query and gives a 404.

**Comment by pd3** [comment]
Thank you for the feedback on documentation! The link is now fixed and a small example added. If you encounter any other issues or have more suggestions for improvements, please do let us know. Also we support and encourage pull requests to the documenttion source files, such as https://github.com/samtools/bcftools/blob/gh-pages/howtos/query.txt
