### ISSUE TITLE
query: vector subset into FORMAT/AD does not match the alternate allele in multi-samples vcf files

### ISSUE THREAD

**Issue by DaGaMs** [samtools/bcftools#990]
I generated several vcf files using `bcftools mpileup`, and merged the output into one multi-sample file. Here is a representative line:

```
chrM    7    .    A    <*>,C    0    .    I16=728,1296,0,0,79816,3.17157e+06,0,0,120577,7.22915e+06,0,0,12557,89991,0,0;MQSB=0.953637;MQ0F=0;SGB=-0.379885;RPB=1;MQB=1;BQB=1;DP=20798;ADF=645,0,0;ADR=1094,0,1;AD=1739,0,1;QS=1,0,0.000136839    PL:DP:SP:ADF:ADR:AD    0,255,255,.,.,.:2024:0:728,0,.:1296,0,.:2024,0,.    0,255,255,.,.,.:1704:0:603,0,.:1101,0,.:1704,0,.    0,255,255,255,255,255:4081:0:1049,0,0:3031,0,1:4080,0,1    0,255,255,.,.,.:1739:0:645,0,.:1094,0,.:1739,0,.
```

As you can see, there are 4 samples, and samtools reports 2 alleles, plus the usual "wildcard" allele.

I now tried to extract the allele depth per observed _real_ allele with `query` (latest master branch):

`bcftools query -f '%CHROM\t%POS0\t%END\t%REF[\t%ALT{1}\t%DP\t%AD{0}\t%AD{1}]\n'`

What I get is this:

```
chrM    6    7    A    C    2024    2024    0    C    1704    1704    0    C    4081    4080    0    C    1739    1739    0```

It seems that `ALT{1}` correctly ignores the `<*>`, but `AD{1}` refers simply to the subset in the AD field, which is the value for `<*>` instead of the value for `C`.

How can I get the AD for the real first alt allele? Any help would be much appreciated!

**Comment by DaGaMs** [comment]
To bring home the point, here is what I get when I use different subset indices for ALT and AD:

`bcftools query -f '%CHROM\t%POS0\t%END\t%REF[\t%ALT{1}\t%DP\t%AD{0}\t%AD{2}]\n'`

```chrM    6    7    A    C    2024    2024    .    C    1704    1704    .    C    4081    4080    1    C    1739    1739    .```

Now I get the correct values. But the location of the `<*>` in the list of ALT alleles could vary, right? So I cannot rely on the off-by-one approach, I believe?

**Comment by pd3** [comment]
The `bcftools mpileup` command is only the first step in the variant calling process, its output should be streamed through `bcftools call`.  http://samtools.github.io/bcftools/howtos/variant-calling.html

Otherwise yes, you are right, `query` treats the alleles the same, regardless of what they are.

**Comment by DaGaMs** [comment]
Hi Petr, thanks for the quick response. I'm not actually planning to variant call, I just wanted to get information on per-allele read depths in mitochondrial DNA from different somatic samples.

The issue then is that it becomes impossible to query a multi-allele vcf file that has wildcard placeholders for the correct sub-vector per TAG, because the '<*>' could be in different positions for each chromosomal position, and there is no way to reference that. (i.e. you can't do something like `query -f "%ALT{1} %INFO/AD{ALT_INDEX{1}}"` or something like that)

I managed to work around the problem by normalising the vcf to bi-allelic. But I still feel this is a bug in bcftools that should probably be fixed, because people will potentially not even realise that they are extracting the wrong column from a per-allele INFO or FORMAT field...

**Comment by pd3** [comment]
This is not a bug, the program does the correct thing. In your example, `ALT{1}` refers to the second alternate allele, whereas `AD{1}` refers to the first alternate allele being defined as `Number=R`. 

You can use `query` to extract the information from VCF into a simpler tab-delimited format and then stream it through a custom perl or python or even awk script to obtain the information you need. (That's actually the intended use of `query`.)

**Comment by DaGaMs** [comment]
I would beg to differ. In order to know which allele AD{1} refers to, it is necessary to know the order of alleles. However, the order of alleles in `ALT` is different from the order on `AD`. This means that the only way to extract the correct column for a multi-allelic position is, as you say, to use a different script which would take the raw allele and AD string and slice them "manually". What then is the purpose of `AD{index}` and `ALT{index}` if not to avoid exactly this problem?

Besides, the current behaviour of `ALT{index}` in multi-allelic positions with `<*>` is, I feel, counter-intuitive, and likely to confuse users. If the `<*>` is at the _end_ of the allele list, it is referred to with the correct index: `A,C,<*>` + `query -f "ALT{3}"` will produce: `*`. However, if the `<*>` is in the middle, the index is off: `A,<*>,C` + `query -f "ALT{2}"` will produce `C`. I really think this is very problematic and bound to trip people up...

**Comment by pd3** [comment]
That's exactly how it is supposed to work: the `TAG{index}` notation allows you to access the values of the `TAG` vector using a 0-based `index`. For example, `AD{1}` prints the second value of the `AD` vector. Similarly, `ALT{1}` prints the second value of the alleles in the list of `ALT` alleles. It does that regardless on whether the allele is a normal or a symbolic allele, they are both equally valid.

That's what the program does, nothing more and nothing less. If you'd like a different behavior, classify this as a feature request, not as a bug. If you think the program does something else than advertised, then please provide a link to a small test case to reproduce the problem.

**Comment by DaGaMs** [comment]
> `ALT{1}` prints the second value of the alleles in the list of ALT alleles. It does that regardless on whether the allele is a normal or a symbolic allele, they are both equally valid.

That is exactly *not* the case. As I showed above, the call `query -f "ALT{2}"` on an ALT string `A,<*>,C ` results in `C`, *not* in `*`, so it behaves _differently_ on symbollic alleles, but only when they are in the middle of the ALT allele list

**Comment by pd3** [comment]
Again, this is how it is supposed to work, they are 0-based indexes. 

Given `ALT=A,<*>,C`, the expression `ALT{0}` is supposed to print `A`, `ALT{1}` is supposed to print `<*>`, and `ALT{2}` is supposed to print `C`. And it indeed does: 

````
$ (echo "##fileformat=VCFv4.2"
echo "##contig=<ID=1>"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "1\t100\t.\tT\tA,<*>,C\t.\t.\t.") > test.vcf

$ cat test.vcf
##fileformat=VCFv4.2
##contig=<ID=1>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	100	.	T	A,<*>,C	.	.	.

$ bcftools query -f 'REF=%REF\nALT0=%ALT{0}\nALT1=%ALT{1}\nALT2=%ALT{2}\n' test.vcf
REF=T
ALT0=A
ALT1=<*>
ALT2=C
````

**Comment by DaGaMs** [comment]
You're correct, apologies for that confusion. I think what confused me is the way the `AD` field is built. Here's an example again. I'm merging and then querying 4 `bcftools mpileup` outputs with `bcftools merge -m snps GEN00959*_chrM.vcf.gz | bcftools query -f "%CHROM\t%END\t%REF\t%ALT[\t%AD]\n"`. Here is some example lines:

```
chrM    63      T       <*>,C,A 3405,0,.,.      2932,0,1,.      5106,0,.,1      3119,0,.,.
chrM    64      C       T,<*>,A 3508,2,0,.      3021,14,0,1     5247,.,0,.      3221,3,0,.
chrM    65      T       G,<*>,C 3551,1,0,.      3060,.,0,1      5304,.,0,.      3251,.,0,1
chrM    66      G       A,<*>,T 3566,59,0,.     3057,1,0,.      5383,.,0,1      3317,1,0,1
```

If I understand this correctly, the first entry in `AD` is the count for the reference allele. Imagine you would like to extract the AD for the first and second most common allele at each position. Now, in the case of position `63` in the example above, you would need to select `AD{0}` and `AD{2}`. However, in position `64`, you would have to select `AD{0}` and `AD{1}`. 

So, my refined question would be: is there a way to get the `AD` for the ref allele iff the respective index in `ALT` is `<*>`?

**Comment by pd3** [comment]
Use `bcftools call -mA`. This removes the symbolic allele and preserves all other alleles.

Otherwise no, there is no mechanism to do what you proposed.
