### ISSUE TITLE
Hi, How to get bases count (A, T, G, C) at a position in a vcf file?

### ISSUE THREAD

**Issue by yubau1112** [samtools/bcftools#992]
Hi, How to get bases count (A, T, G, C) at a position in a vcf file?

Example: chr6 4064600 A 50 T 0 G 12 C 18 

because some HLA types must be specific nucleotide at a specific position.

my command is:
bcftools mpileup -Ou -Q 0 -f $reference_genome $sampleName.sorted.bam | bcftools call -A -m -o Variants.txt

than I can get results like folloing:
chr1    4064600 .       AGT     A       25.5984 .       INDEL;IDV=1;IMF=1;DP=1;SGB=-0.379885;MQ0F=0;AC=0;AN=2;DP4=0,0,0,1;MQ=60 GT:PL   0/0:4,3,
0

I found that DP4 value is "Number of 1) forward ref alleles; 2) reverse ref; 3) forward non-ref; 4) reverse non-ref alleles", but still can not get A:C:G:T, respectively.

**Comment by pd3** [comment]
`bcftools mpileup --annotate FORMAT/AD`
