### ISSUE TITLE
bcf query fails to parse info field from vcf feed to it by bcf annotate then bcf view

### ISSUE THREAD

**Issue by skyscraperjon** [samtools/bcftools#994]
I took an annotation vcf with auto generated info fields used
`bcftools annotate -a [AnnotationFile] -c INFO [RAW VCF] > [output]`
to annotate

then i did
` bcftools view -Oz -s [Samples] [output] > [output_samples].vcf.gz`

then i did 
`bcftools query -f'[%ID\t %SAMPLE\t %GT\t %INFO\n]' -i'GT="alt"' [output_samples].vcf.gz`

> Could not parse format string: [%ID\t %SAMPLE\t %GT\t %INFO\n]

I also tried piping view to query
I also tried to query the annotation output directly.

Not sure what is going on.

If I try 
`bcftools query -f'[%ID\t %SAMPLE\t %GT\n]' -i'GT="alt"' [output_samples].vcf.gz`

This works just fine as far as I can tell.

**Comment by pd3** [comment]
The expression as it stands is ambiguous, you probably wanted `%INFO/INFO`. I just pushed a fix which prints a warning to prevent this kind of mistake.

**Comment by skyscraperjon** [comment]
Thank you for your quick response! 

I see I see. I was wondering if there was a way to just get ALL info columns at once.

I am not sure if:

> %INFO/INFO

was the solution but using that returned:

> Error: no such tag defined in the VCF header: INFO/INFO. FORMAT fields must be in square brackets, e.g. "[ INFO]"

Which would be the obvious output since I do not have an INFO column with the ID=INFO


Sincerely,

~Jon

**Comment by pd3** [comment]
I made an incorrect assumption. If there is no `INFO/INFO` field, it is currently not possible to print the whole INFO for each sample.
