### ISSUE TITLE
view subset option --trim-alt-alleles unclear result

### ISSUE THREAD

**Issue by rbutleriii** [samtools/bcftools#995]
Either the documentation is unclear for the `--trim-alt-alleles` option, or it is not functioning as intended. Looking at a multi-sample vcf, I am using `bcftools view` to extract a single sample. Of the 3 million odd SNPs, the single sample only has around 200k, the rest being Ref/Ref. So, adding `-a` to the `bcftools view` command: 
```
bcftools view -s sample -a -Oz -o out.vcf.gz multi.vcf.gz
```
I would expect that trimming alternate alleles not seen in subset means dropping those Ref/Ref variants entirely. When I try it all the variants are still present, and I cannot figure out what if anything has changed. Is there a better definition of trim in this context? Would using the `--min-ac 1` option be the better approach to drop all of the ref/ref snps?

**Comment by pd3** [comment]
Yes, you need some other option to achieve what you need, for example the `--min-ac`. The `--trim-alt-alleles` does only what it says: removes alleles not seen in the genotype fields from the ALT column.

**Comment by rbutleriii** [comment]
> removes alleles not seen in the genotype fields from the ALT column.

Perfect, that is quite clear on the effect the option has. I would argue it is much clearer than the current:

> trim alternate alleles not seen in subset. 

It might also help to comment on the inevitable 'well what if all ALT alleles are removed?' The answer could be one of two things: leave a `.` as it does, or remove the variant line altogether. 

>-a, --trim-alt-alleles
>          remove alleles not seen in the subset's genotype fields from the ALT column (leaving a "." if none remain). Type A, G and R INFO and FORMAT fields will also be updated.

**Comment by pd3** [comment]
The documentation is now updated, thank you for the feedback.

Note that you can remove the reference-only records completely also using the filtering expressions, for example like this:
````
bcftools view -i 'GT="alt"' file.vcf
````
