### ISSUE TITLE
Extracting this columns from .vcf

### ISSUE THREAD

**Issue by beginner984** [samtools/bcftools#996]
Hi,
I have called SNV for tumour and matched normal samples, now I have .vcf and I want to get tumour and normal sequencing depth something like below

```
> head(mut_data[,c(1,3:9)])
    Sample CHROM       POS REF ALT Tumor_Varcount Tumor_Depth Normal_Depth
1 CHC2432T  chr1 102961055   G   A              4          64           62
2 CHC2432T  chr1 105492588   A   T              7          66           73
3 CHC2432T  chr1 108628724   C   T              4          45           54
4 CHC2432T  chr1 109692113   G   T              2          53           29
5 CHC2432T  chr1 109692114   G   T              2          53           31
6 CHC2432T  chr1 120676701   T   C              3          48           87
> 
```

For the 5 columns at first I know this is the code `%CHROM\t%POS\t%REF\t%ALT{0}\n` but for getting `Tumor_Varcount   =  Number of variant bases at the position in the tumor sample , Tumor_Depth Normal_Depth` I really don't know
Any help please?

Thank you so much in advance

**Comment by finswimmer** [comment]
Could you please show us how your `vcf` file looks like?

**Comment by beginner984** [comment]
Thank you

This is link of my .vcf

https://www.dropbox.com/s/lfn9greycjybnrt/_double_filtered_013_pre_indels.vcf?dl=0

**Comment by RamRS** [comment]
Hello @beginner984 , GitHub issues are not the place to ask for help with the usage. GitHub issues are for problems in the tool's code or issues with the expected behavior. If you have a question on how to use the tool, I suggest doing a bit of Googling first, and then maybe opening a post on Biostars or Bioinfo SE after you're sure you've tried all you can. In any case, GitHub is not the place for these.

**Comment by pd3** [comment]
I am not familiar with Strelka's output. But suppose you want to extract, for example, the second value of the  FORMAT/TIR field, you could use the following command
````
$ bcftools query -f'%CHROM\t%POS[\t%TIR{1}]\n' file.vcf | head -3
1	235042	0	19
1	3084364	2	7
1	4253459	0	25
````

**Comment by beginner984** [comment]
Sorry, says

```
[fi1d18@cyan01 gffread]$ bcftools query -f'%CHROM\t%POS[\t%TIR{1}]\n' /somatic.snvs.vcf | head -3
Error: no such tag defined in the VCF header: FORMAT/TIR
```

**Comment by pd3** [comment]
Check the FORMAT field TIR is present in your VCF. If it is, update to the latest github version as described here http://samtools.github.io/bcftools/howtos/install.html

**Comment by beginner984** [comment]
Sorry

you kindly suggested that `bcftools query -f'%CHROM\t%POS[\t%TIR{1}]\n' file.vcf | head -3` gives read depth for normal and tumor

How I can get the number of variant bases in tumor sample?

**Comment by RamRS** [comment]
> you kindly suggested that `bcftools query -f'%CHROM\t%POS[\t%TIR{1}]\n' file.vcf | head -3` gives read depth for normal and tumor

No, @pd3 did not say that at all. They said if you wish to get the second value of the `FORMAT/TIR` field, you need to use the command ``bcftools query -f'%CHROM\t%POS[\t%TIR{1}]\n' file.vcf`. The `head -n 3` was to show you a sample of the output.

To determine which field gives you normal/tumor read depth, you are going to need to read through the VCF header and understand what each field means, and you're going to understand the experiment design to understand what each sample identifier means, which of them are tumor, which are normal etc.

Honestly, this question is not about `bcftools` at all, this is about you understanding the VCF format and your VCF file. That is your job, not anyone else's.
