### ISSUE TITLE
bcftools FORMAT/FOO annotation to specific sample in multiple sample VCF

### ISSUE THREAD

**Issue by ShahiRB** [samtools/bcftools#998]
Hi,

I wonder what do we have to modify in this command "bcftools annotate -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf" if we want to annotate FMT/FOO to SAMPLE2 (let's say the in.vcf has two samples) but not to SAMPLE1.

I did like this "bcftools annotate -s SAMPLE2 -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf" but it again annotated FMT/FOO to SAMPLE1 instead of SAMPLE2.

I think these steps [A-E] will help to illustrate more. (SAMPLE2 that has to be annotated with "FooValue1" and "FooValue2")

A]. zcat annots.tsv.gz
1   752567  752567  FooValue1   12345
1   752722  752722  FooValue2   67890

B]. zcat annots.hdr
##FORMAT=<ID=FOO,Number=1,Type=String,Description="Some description">
##INFO=<ID=BAR,Number=1,Type=Integer,Description="Some description">

C]. cat in.vcf
#fileformat=VCFv4.1
##contig=<ID=1,length=249250621,assembly=b37>
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  SAMPLE1 SAMPLE2
1   752567  .   A   C   .   .   BAR=12345   FOO .   .
1   752722  .   G   A   .   .   BAR=67890   FOO .   .

D]. command:
bcftools annotate -s SAMPLE2 -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf>in_annoted.vcf

E]. cat in_annoted.vcf
##fileformat=VCFv4.1
##contig=<ID=1,length=249250621,assembly=b37>
##FORMAT=<ID=FOO,Number=1,Type=String,Description="Some description">
##INFO=<ID=BAR,Number=1,Type=Integer,Description="Some description">
##bcftools_annotateVersion=1.8+htslib-1.8
##bcftools_annotateCommand=annotate -s SAMPLE2 -a annots.tsv.gz -h annots.hdr -c CHROM,FROM,TO,FMT/FOO,BAR in.vcf; Date=Thu Jun 14 20:17:43 2018
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  SAMPLE1 SAMPLE2
1   752567  .   A   C   .   .   BAR=12345   FOO .   FooValue1
1   752722  .   G   A   .   .   BAR=67890   FOO .   FooValue2

Thanx!

**Comment by pd3** [comment]
The bug is not present in the latest github version, please check here how to upgrade http://samtools.github.io/bcftools/howtos/install.html

**Comment by ShahiRB** [comment]
@pd3 , Thanx
